### ISSUE TITLE
Compatibility: not compatible with Samsung Galaxy S9+?

### ISSUE THREAD

**Issue by jmoberreuter** [corona-warn-app/cwa-app-android#1002]
Android 10 and latest updates installed, also for Google Play Services. App is not offered in the play store for this device.

**Comment by GPclips** [comment]
Hello @jmoberreuter,

I just came across your issue. Does this issue still remain?
Generally, the Corona-Warn app is available in multiple countries of the PlayStore. For an overview, please check out this FAQ article: https://www.coronawarn.app/en/faq/#international

To be able to use the application, your PlayStore should be set to either of these countries. 

Also, it is important that you smartphone runs at least on Android 6, as you can see here: https://www.coronawarn.app/en/faq/#minimum_requirements

Please make sure your Google Play Services are up to date: https://www.coronawarn.app/en/faq/#googleplay, https://www.coronawarn.app/en/faq/#cause_3

**Comment by jmoberreuter** [comment]
Thanks! Changing the country of the store has solved the problem. I did find the error message "not compatible with your device" confusing, though. Thanks for your help and concern.

**Comment by kaimast** [comment]
Why do I have to change the country to install the app? Shouldn't people visiting Germany be able to use this? 

I agree with @jmoberreuter that the error message is very unintuitive.
