### ISSUE TITLE
[INFO]: Wrong "Aktualisiert: ..." / "Updated: ..." - Information on CWA start screen

### ISSUE THREAD

**Issue by Jo-Achim** [corona-warn-app/cwa-app-android#1024]
Android 10 with Android Sicherheitsupdate / Security-Update: 1. Juli 2020
Nokia 7.1, Build: 00WW_4_15C_SP02
Internet: WLAN (only)
CWA-Version: 1.2.1

Hello, 

to see the little problem, do...

1. Start CWA.
2. If CWA starts with "Prüfung läuft ..." (CWA-Start-Screen) then look at the message "Aktualisiert: ..." ("Updated: ...").
You will see: "Aktualisiert: **Gestern** ..." ("Updated: **Yesterday** ..."). / In my case: "Low risk".
3. Touch the "->" to go to the "Ihr Risikostatus" / "Your Riskstatus" screen.
4. Here you will see the correct: "Aktualisiert: **Heute** ..." / "Updated: **Today** ...".
5. Tapp on "X" to go back to the start screen again and NOW the correct message "Aktualisiert: **Heute** ..." / "Updated: **Today** ..." was displayed.

Instead of executing point 3, it is sufficient, for example, to switch off the smartphone / restart the CWA app.

The indication of the wrong information is repeatable. 

Best regards.

---
Internal Tracking ID: EXPOSUREAPP-2216

**Comment by vaubaehn** [comment]
Same here. CWA1.2.1, ENF 16203019000

**Comment by Jo-Achim** [comment]
Hi @vaubaehn,

> Not able to reproduce behaviour after switching off phone and restarting CWA, like suggested above.

Follow steps 1 and 2. 
3a. Then, instead to open then ‘Screenshot-Menu’ press the button too short, so the phone goes to ‘stand-by’. 
3b. Restart it (e.g. per fingerprint-scanner) and the last CWA-Start-Screen is displayed. 
After this, yesterday I saw the correct "Aktualisiert: **Heute ...**" / "Updated: **Today ...**" – instead of the wrong 'Gestern ...' / Yesterday ...' display under 2.

But today: after restarting the phone (3b.) the “Prüfung läuft …” is running and then: "URSACHE: 9002, Etwas ist schiefgelaufen. Timeout #998"! 
After some tapps to repeat and make screenshots, I see a 'time-out 60000 seconds' and after this the correct “Aktualisiert: Heute ..." / "Updated: Today ...". 
So I have actually no additional information. 

I'm adding an informal cross-reference in the thread: "URSACHE: 9002, Etwas ist schiefgelaufen. Timeout #998"".

**Comment by Jo-Achim** [comment]
> 
> 
> Brief impression of today ...
> 
> > CWA-Version: 1.2.1
> > ```
> > 1. Start CWA.
> > 
> > 2. If CWA starts with "Prüfung läuft ..." (CWA-Start-Screen) then look at the message "Aktualisiert: ..." ("Updated: ...").
> >    You will see: "Aktualisiert: **Gestern** ..." ("Updated: **Yesterday** ..."). / In my case: "Low risk".
> > 
> > 3. Touch the "->" to go to the "Ihr Risikostatus" / "Your Riskstatus" screen.
> > 
> > 4. Here you will see the correct: "Aktualisiert: **Heute** ..." / "Updated: **Today** ...".
> > 
> > 5. Tapp on "X" to go back to the start screen again and NOW the correct message "Aktualisiert: **Heute** ..." / "Updated: **Today** ..." was displayed.
> > ```
> 
> Is it possible that the incorrect previous update information ("Aktualisiert: Gestern ..." / "Updated: Yesterday ...") is still displayed in step 4?
> And, in this case, only with next step 5 then both on the 'CWA-Start-Screen' and then (after "->" again) on the "Ihr Risikostatus" / "Your risk status" screen the correct update time ("Aktualisiert: Heute ..." / "Updated: Today" ... ") is shown?
> 
> Best regards.

Yes, it is possible - CWA 1.3.0.

**Comment by daimpi** [comment]
Related to: https://github.com/corona-warn-app/cwa-app-android/issues/1081

**Comment by d4rken** [comment]
The OPs description sounds like there is an issue with the updated data being passed around via `LiveData` classes. They are not optimal for this approach and we've addressed quite a few of those issues for upcoming updates

Especially pausing+resuming the UI and the recreation of some UI parts would fit that behavior. I think this behavior could already improve as a side-effect of other changes in 1.6, as we moved a lot of non-UI code from `LiveData` (suitable for the UI layer) to a more reactive approach using Kotlin `Flow` (suitable for internal layers), removing the need for UI elements to "manually call refresh" and using patterns where the UI is "notified".

We're checking if this can still be reproduced on newer builds to evaluate whether extra changes are needed, or this will be fixed as a side effected from refactoring for upcoming features.

**Comment by Jo-Achim** [comment]
Android 10 with Android Security Update: September 1st, 2020
Nokia 7.1, Build: 00WW_4_16B
CWA version: 1.6.0
ENF version: 18204215000

The problem described in my first post today is under CWA 1.6.0. also occurred.

**Comment by Jo-Achim** [comment]
Android 10 with Android Security Update: September 1st, 2020
Nokia 7.1, Build: 00WW_4_16B
CWA version: 1.6.0
ENF version: 18204215000

Hello, here some screenshots from described problem (after the start of CWA and the 'Update...' triggered in this way)... 

After CWA-start and 'Update...' (Mainscreen):
![Screenshot_20201116-021437](https://user-images.githubusercontent.com/21124877/99238951-b102f380-27fa-11eb-8c7c-4b284ade0555.png)

After tap to [->]:
![Screenshot_20201116-021447](https://user-images.githubusercontent.com/21124877/99238975-ba8c5b80-27fa-11eb-9ee7-e4fb3da3092f.png)

Back to Mainscreen (tapped to [X]):
![Screenshot_20201116-021458](https://user-images.githubusercontent.com/21124877/99239009-c415c380-27fa-11eb-80c9-9bc8ec773cf4.png)

"Covid-19" - Info...
![Screenshot_20201116-021529](https://user-images.githubusercontent.com/21124877/99239042-cd9f2b80-27fa-11eb-9e1f-26b9ce12c7df.png)

Best regards.

**Comment by dsarkar** [comment]
Dear @Jo-Achim, can you reproduce this issue with CWA 1.9.1. Feedback very much appreciated. Best regards, DS.

---
Corona-Warn-App Open Source Team

**Comment by Jo-Achim** [comment]
No, not at the moment - but I will pay attention again.

**Comment by dsarkar** [comment]
@Jo-Achim, thanks for the feedback. We monitor this some more days before, hopefully, we can close this issue as fixed. Bes, DS

---
Corona-Warn-App Open Source Team

**Comment by Jo-Achim** [comment]
@dsarkar: Hello, I think that after the update, which also led to this change...

![Screenshot_20201221-190241_t](https://user-images.githubusercontent.com/21124877/102808559-c6061000-43c0-11eb-8a47-f60164e864df.jpg)

the problem of the 'different update dates / times' has been resolved. So I think this issue can be closed.
Many thanks.

Best regards, Joachim.

**Comment by dsarkar** [comment]
@Jo-Achim, and community, thanks for the feedback and contributions. We close this issue now. Best, DS

---
Corona-Warn-App Open Source Team
