### ISSUE TITLE
Deleting and adding test again via QR code

### ISSUE THREAD

**Issue by SemBur** [corona-warn-app/cwa-app-android#1026]
Hi,
not sure if this is the correct place, but can't find this information anywhere i've searched.

I had a test added to the application which was deleted. When i try to add test again, i get the error message that the code is invalid or was used already. How can i get the results now? Tried to call the hotline, but it's not connecting.

Thank you in advance.

**Comment by MikeMcC399** [comment]
This seems like a similar issue to https://github.com/corona-warn-app/cwa-app-android/issues/1001 .

**Comment by daimpi** [comment]
What mike said ^

You should have gotten a warning, that deleting the key is permanent. This is done for privacy reasons, so no one except for you can query your results.

That means unfortunately you'll have to wait until they contact you via Phone/mail:
> Hi unfortunately this is not possible. We have to ensure only one phone can scan the qr code and submit his diagnoses keys. We are not allowed to save an ID of the phone this is the reason why the qr code is only valid for one scan.
> Please wait for the normal way (a letter via post mail or Gesundheitsamt calls you) of the test lab to get your result.

([Source](https://github.com/corona-warn-app/cwa-app-android/issues/960#issuecomment-667996582))

**Comment by GPclips** [comment]
Hello @SemBur,

thanks for reaching out to us. As @MikeMcC399 mentioned this issue already has been addressed in different other threads. The one I like to refer to is https://github.com/corona-warn-app/cwa-app-android/issues/960. 

I will proceed and add the label "duplicate" as well as close your issue.

Thank you,
LMM

Corona-Warn-App Open Source Team
