### ISSUE TITLE
View Binding not nulled when view is destroyed

### ISSUE THREAD

**Issue by svenjacobs** [corona-warn-app/cwa-app-android#104]
This is just a minor issue but View Binding is not nulled in `onDestroyView()` of Fragments as recommended in [official documentation](https://developer.android.com/topic/libraries/view-binding#fragments). This could lead to memory leaks.

**Comment by marcmuschko** [comment]
Hi @svenjacobs,

thank you for pointing this out!
We appreciate the suggestion, will look into this to ensure the change has no negative impact and will (very likely) include it during the next few days. Until the suggestion is included or dimissed I will leave the issue open.

Thanks again and best,
Marc

**Comment by harambasicluka** [comment]
Closed in #182.
