### ISSUE TITLE
HTTP 404 for status 17 when Google COVID-19 exposure notifications unavailable

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#1043]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Describe the bug

The following error message is displayed and the link to https://www.coronawarn.app/en/faq/(17) throws HTTP 404 error, file not found.

CAUSE: 3
Something went wrong.
Your Corona-Warn-App is correctly installed, but the "COVID-19 exposure notifications" service is not available on your smartphone's operating system. This means that you cannot use the Corona-Warn-App. For further information, please see our FAQ page: https://www.coronawarn.app/en/faq/(17)"

## Expected behaviour

This is a corner case which should not normally occur. CWA is only officially available from Google Play Store which should ensure that it is only installed on compatibile devices.

However if the error does occur then the link to https://www.coronawarn.app/en/faq/(17) should resolve to useable content.

## Steps to reproduce the issue

Here CWA is installed on a virtual device which lacks bluetooth hardware. Bluetooth is however essential for CWA. We deliberately provoke this error condition.

1. In Android Virtual Device Manager create Nexus 5X with Play Store, release Q, API 29.
2. Complete setup of Nexus 5X.
3. In Google Play Store ensure all pending updates are installed.
4. Settings > Apps & notifications > search for "google play services"
App info > Advanced
Note version 17.7.86

5. Run CWA 1.2.1 in Nexus 5X emulator.
6. Run through CWA onboarding.
Notification appears:
"Update Google Play services
Corona-Warn won't run unless you update Google Play services."

7. Update Google Play services to version 20.30.19
8. Run through CWA onboarding.
CAUSE: 3
Something went wrong.
Your Corona-Warn-App is correctly installed, but the "COVID-19 exposure notifications" service is not available on your smartphone's operating system. This means that you cannot use the Corona-Warn-App. For further information, please see our FAQ page: https://www.coronawarn.app/en/faq/(17)"

Details shows error code 39501

## Technical details

- Mobile device: Virtual device Nexus 5X with Play Store, release Q, API 29.
- Android version: 10
- Google Play services 20.30.19

## Possible Fix

Create page for https://www.coronawarn.app/en/faq/(17)

**Comment by tkowark** [comment]
Thanks for reporting this issue. With https://github.com/corona-warn-app/cwa-website/commit/18be18ebc66beb0a1fc8540d24316f5de6d038e6, we created a redirect for the mentioned urls. I'll close this issue accordingly, but will open another linking to it that addresses the general faq link format.

**Comment by vaubaehn** [comment]
@MikeMcC399 , that was a very nice test case!
