### ISSUE TITLE
Exposure Log shows matches during the last 9 days...

### ISSUE THREAD

**Issue by KoWeeWan** [corona-warn-app/cwa-app-android#1045]
Hi team,
due to some inexplicable behavior of the CWA (to me), I started collecting my exposure logs for quite some time.
While checking them today I realized that there has been a match every day for the last nine days with the same hash.
However during this time I have been in two different cities with no overlapping contacts. On day one (August 12th) i was in city 1, from late August 13th to early August 17th I was in city 2. From then on again city 1.
No persons from city 1 live in city 2 or vice versa and we are talking 400km distance. 
[all-exposure-checks.zip](https://github.com/corona-warn-app/cwa-app-android/files/5102399/all-exposure-checks.zip)
I would suspect something is wrong here. However, if I am wrong I apologize for stealing your time.
Regards, Wee

**Comment by tkowark** [comment]
Hi @KoWeeWan ,

the hash is not specific to a match but the file of downloaded diagnosis keys. So, the file with yesterday's keys has a hash and will keep that hash unless it is changed (e.g., if keys need to be removed for some reason).

We'll make this clearer in the FAQ (https://www.coronawarn.app/en/faq/#keys_matches) according to https://github.com/corona-warn-app/cwa-documentation/issues/409

Best regards,
TK
Corona-Warn-App Open Source Project
