### ISSUE TITLE
Risikobegegnung mit niedrigem Risiko since more than 5 weeks

### ISSUE THREAD

**Issue by robrtr** [corona-warn-app/cwa-app-android#1047]
App (android) is showing a Risikobegegnung mit niedrigem Risiko since more than 5 weeks. However this must be a bug as data should refresh after 2 week's?

**Comment by MikeMcC399** [comment]
@robrtr 
This is probably the same as https://github.com/corona-warn-app/cwa-app-android/issues/911 
If so, then it should be fixed in version 1.3.0 when this is released. Look for EXPOSUREAPP-1837 and https://github.com/corona-warn-app/cwa-app-android/releases where it shows up in 1.3.0 RC1.

**Comment by GPclips** [comment]
Hello @robrtr,

as @MikeMcC399 mentioned, this is a duplicate and therefore will be closed.

Thanks,
LMM

Corona-Warn-App Open Source Team
