### ISSUE TITLE
Android README.md should link to top level of English FAQ

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#1050]
## Where to find the issue

https://github.com/corona-warn-app/cwa-app-android/blob/dev/README.md
Last sentence of first paragraph.

## Describe the issue

"**Visit our [FAQ page](https://www.coronawarn.app/de/faq/#android_location) for more information and common issues**" links to https://www.coronawarn.app/de/faq/#android_location

1.  Since the README.md contents and project working language is English, the README.md should link to the English language version of the FAQ.
2. The link should be to the top level of the FAQ, not to the specific issue at anchor #android_location .

## Suggested change

Change the link from https://www.coronawarn.app/de/faq/#android_location to https://www.coronawarn.app/en/faq/

**Comment by tkowark** [comment]
Thanks for the hint. I've create a PR that will automatically close this issue once merged.
