### ISSUE TITLE
Tage seit der letzten Risiko-Begegnung bleibt bei "15" stehen 

### ISSUE THREAD

**Issue by bjoer** [corona-warn-app/cwa-app-android#1062]
Die Anzahl der Tage seit der letzten Risiko-Begegnung wird nicht korrekt berechnet.

Sofern die letzte Risikobegegnung länger als 15 Tage in der Vergangenheit liegt wird ab dem 16. Tag weiter der Wert von 15 Tagen angezeigt

**Comment by kereng5** [comment]
Wo sieht man die Anzahl Tage seit der letzten Risiko-Begegnung?
Nur bei hohem Risiko? Nur bei iPhone?

**Comment by bjoer** [comment]
In meinem konkreten Fall handelt es sich um die App für Android und um ein hohes Risiko.

Ob die Tage auch bei nicht hohem Risiko und/oder dem IPhone angezeigt werden ist mir nicht bekannt

**Comment by GPclips** [comment]
Hello @bjoer,

thanks for reaching out to us. To help you as fast as possible, please provide the following:
- App version you are using
- Android Version
- Screenshot of the application of the part of the screen where your bug occurs 
- Steps to reproduce (even if it is just the steps to retrace the issue)

As soon as we have the information, I can go into discussion with our development team.

Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
Closed due to missing feedback.

@bjoer If the bug persists for you or you can provide the information @GPclips asked for, feel free to comment here or open anoother issue.

Regards,
CH

Corona-Warn-App Open Source Team
