### ISSUE TITLE
Problems with add a test

### ISSUE THREAD

**Issue by necotec** [corona-warn-app/cwa-app-android#1089]
Hello developer.

I have an issue with your app. Specific with the section "Sie wurden getestet?". I clicked there, I can scan the Qr code on my paper from doctor.... I had seen, there is a working site and no error. I closed the App and a little bit later, there was no test... I can scan the Qr code, but the App says, there is an issue.

![Screenshot_20200827-095234.png](https://user-images.githubusercontent.com/64785948/91604322-be80ae00-e96e-11ea-910e-1280f8213c40.png)

Tested on Huawei P Smart 2016.

More tests on my Google-free Volla Phone with VollaOS (Android 9.0). Same issue ;p

Can you fix that or help me?

Thank you

**Comment by mtb77** [comment]
Hi @necotec,

thanks for reporting your issue. Do you mean with "there is a working site and no error" that the app was trying to process your first scan of the QR code and because of a missing response, you closed the app and tried it again?

Thanks and get well soon,

Sascha

Corona-Warn-App Open Source Team

**Comment by necotec** [comment]
No. After adding the test, I had seen it. After a restart of the App, it was away.

How I can readd the test? Is it possible?

**Comment by mtb77** [comment]
Hi @necotec,

we are actually heavily working on the QR code mechanism and resolving issues around that. In this case it is hard to figure out wether the QR code has not being activated by the Laboratory or if the first attempt was accepted by the backend and then after closing the app not assigned to your mobile. 
To prevent abuse use of the QR code, it can be only used once - afterwards it is marked in the backend as used.  

Please see also:
https://www.coronawarn.app/de/faq/#qr_test
https://github.com/corona-warn-app/cwa-documentation/issues/400


Sascha

Corona-Warn-App Open Source Team
