### ISSUE TITLE
Ursache 3 (39058) while in Denmark

### ISSUE THREAD

**Issue by WilliamReed2004** [corona-warn-app/cwa-app-android#1090]
## Technical details

- Mobile device:
- Android version:

**Comment by Tho-Mat** [comment]
Duplikate of #1021

**Comment by mtb77** [comment]
@Tho-Mat @WilliamReed2004 can I close this issue then? 

Thanks,

Sascha

Corona-Warn-App Open Source Team

**Comment by Tho-Mat** [comment]
yes

**Comment by mtb77** [comment]
Duplicate #1021 

Thanks,

Sascha

Corona-Warn-App Open Source Team
