### ISSUE TITLE
Tage seit der letzten Risiko-Ermittlung "-4"

### ISSUE THREAD

**Issue by wessjan** [corona-warn-app/cwa-app-android#1091]
Die Anzeige der Tage, die seit der letzten Risikoermittlung bleibt seit einigen Tagen konstant bei -4:
![IMG_20200830_152955](https://user-images.githubusercontent.com/15079538/91660450-3d442b00-ead6-11ea-96ad-d9b7aa0b8519.jpg)
Davor meldete die App brav, dass sie dauerhaft aktiv gewesen sei.

Die Einstellungen sind: 

- Risiko-Ermittlung: An
- Mitteilungen: An
- Priorisierte Hintergrundaktivität: An

Version: Android/1.2.1
System: Samsung Galaxy S7 Duos

Jan

**Comment by MikeMcC399** [comment]
This is the same issue as [Negative value of the counter for how long the app has been active](https://github.com/corona-warn-app/cwa-app-android/issues/828) https://github.com/corona-warn-app/cwa-app-android/issues/828.

The fix [Active tracing days count can be negative (EXPOSUREAPP-1844)](https://github.com/corona-warn-app/cwa-app-android/pull/1029) is in version [1.3.0 RC6](https://github.com/corona-warn-app/cwa-app-android/releases/tag/1.3.0-SNAPSHOT-RC6) but is not yet released.

**Comment by wessjan** [comment]
sorry for the dup, havn't found that in the issue list.

**Comment by MikeMcC399** [comment]
Hi @wessjan 
It's understandable that you missed it. I just remembered that I had seen it and I looked in the open issues first, then I found it in the closed issues.
No harm done!
