### ISSUE TITLE
Error 909 when opening the App

### ISSUE THREAD

**Issue by ucmichan** [corona-warn-app/cwa-app-android#1095]
Actions
1. Open the app

Result
Every time the app gets opened, the error 909 appears.

Device:
Galaxy S10 (beyond1)
Android 10

---
Internal Tracking ID: EXPOSUREAPP-2430

**Comment by Marco2907** [comment]
Hello @ucmichan , thanks a lot for sharing your content. This new error occurs few days ago. I will keep the issue and discuss this with our development team. I will come back to you as soon as possible. 

Thank you.

Best,
MP

Corona-Warn-App Open Source Team

---
Internal Tracking ID: EXPOSUREAPP-2430

**Comment by MikeMcC399** [comment]
Hi @ucmichan 
Was "Error 909" the complete error text or did you see something else?
Was there perhaps also a DETAILS link displayed which you could tap?
Screen shots might help if you have any additional information.

**Comment by GPclips** [comment]
Hello @ucmichan ,

please provide the following information, that we can enrich the internal ticket:

- does the error still occur?

- please provide screenshots for our dev team

- If possible please provide the stack trace

Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Dear @ucmichan,

Is this issue resolved with CWA version 1.7.1? We would appreciate the feedback.  Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by ucmichan** [comment]
Thanks. I think this can be closed. We never received any further feedback from the user and also it seems that it was reported only once a few months ago. So feel free to close the issue.

**Comment by dsarkar** [comment]
Dear @ucmichan,

Thanks for the feedback. Best wishes,
DS

---
Corona-Warn-App Open Source Team
