### ISSUE TITLE
App crashes directly after start

### ISSUE THREAD

**Issue by HennekJN** [corona-warn-app/cwa-app-android#1099]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Describe the bug

Today I noticed that I cannot start the app anymore. It crashes directly after start.

## Steps to reproduce the issue

Just start the app.
The splash screen is displayed for 1/2 second, then it disappears.

## Technical details

- Mobile device: Sony Xperia XZ2 Compact (H8324)
- Android version: 10 (52.1.A.3.49)
- App version: 1.2.1

**Comment by MikeMcC399** [comment]
Hi @HennekJN 
You might like to refer to [App closing immediately on start](https://github.com/corona-warn-app/cwa-app-android/issues/1053) https://github.com/corona-warn-app/cwa-app-android/issues/1053 which discusses a very similar issue on a different device.

**Comment by HennekJN** [comment]
@MikeMcC399 
That case mainly deals with Huawei-specific issues. 
The only hint that worked was to delete all app data + cache. Now it works again, but the collected contacts are gone, of course...

**Comment by MikeMcC399** [comment]
@HennekJN 
Yes, unfortunately if you delete the app data, then the history is also reset. Deleting the cache only doesn't delete the history.
If CWA crashes directly after the start, then you would not have been able to use the CWA Settings > Reset App function, and I can't say anyway if that would have cleared your problem.

I have submitted a [wish-list item - Google Exposure Notification System should optionally preserve exposure data on app uninstall](https://github.com/corona-warn-app/cwa-wishlist/issues/164) which might help in the future if it is implemented. There is a related item [Backup exposure history to transfer to new/reseted phone](https://github.com/corona-warn-app/cwa-wishlist/issues/8) as well.

**Comment by Marco2907** [comment]
Hello @HennekJN , thanks for sharing your content. I would close this issue because this is similar to #1053 and based on this the community informed the development team.

Thank you.

Best,
MP

Corona-Warn-App Open Source Team
