### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AlexKAM1969** [corona-warn-app/cwa-app-android#1101]
Hello everyone! Yesterday I passed the test and scanned the QR into the CWA application. Today, I accidentally deleted the test from the system. I try to scan the QR again, but I write the error "The QR / Tan is invalid or has been used already. Please try again or contact the technical hotline "Please help me what to do next? 
![Screenshot_20200901-125515_Corona-Warn](https://user-images.githubusercontent.com/70584699/91859357-a52b7a80-ec6a-11ea-8a9c-559e33498156.jpg)

---
Internal Tracking ID: EXPOSUREAPP-2443

**Comment by MikeMcC399** [comment]
Hi @AlexKAM1969 
This is the same as [QR Code cannot be re-added after accidental deletion](https://github.com/corona-warn-app/cwa-app-android/issues/960) https://github.com/corona-warn-app/cwa-app-android/issues/960.

The answer given there was:
>We have to ensure only one phone can scan the qr code and submit his diagnoses keys. We are not allowed to save an ID of the phone this is the reason why the qr code is only valid for one scan.
> Please wait for the normal way (a letter via post mail or Gesundheitsamt calls you) of the test lab to get your result.

**Comment by Marco2907** [comment]
Hi @AlexKAM1969 , thanks for sharing your content. As @MikeMcC399 mentioned, this is similar to #960. We will discuss this point with our development team and come back to you as soon as possible. 

Thank you. 

Best,
MP

Corona-Warn-APP Open Source Team

---
Internal Tracking ID: EXPOSUREAPP-2443

**Comment by MikeMcC399** [comment]
https://www.coronawarn.app/en/faq/?search=qr#qr_test now says:

>### Problems when using the QR code
>....
If you have already scanned the QR Code, it unfortunately cannot be scanned a second time, nor is it possible to delete a previously entered QR Code and scan it in again. We have to make sure that only one phone can scan the QR Code and transmit its diagnostic keys. For privacy reasons, we cannot store the phone's ID, so the QR Code is only valid for one scan.
...

Maybe @AlexKAM1969 can say if his issue has been answered?

**Comment by GPclips** [comment]
Hello @AlexKAM1969 and @MikeMcC399,

as @MikeMcC399 has answered, one cannot scan Qr-codes twice. This has been mentioned in our FAQ as well. Mike kindly pointed you to the entry. Therefore I will go on and close this issue.

Also, I like to mention, that we are currently working on a related topic: https://github.com/corona-warn-app/cwa-documentation/issues/400. 

Thanks,
LMM

Corona-Warn-App Open Source Team
