### ISSUE TITLE
Qr-code

### ISSUE THREAD

**Issue by Gradmar** [corona-warn-app/cwa-app-android#1111]
Ich muss den gleichen QR-Code erneut scannen, aber es funktioniert nicht!

**Comment by Marco2907** [comment]
Hallo @Gradmar , vielen Dank für dein Feedback. Ich würde dieses Issue schließen, da dieses im documentation repository vermerkt ist. 

https://github.com/corona-warn-app/cwa-documentation/issues/420 

Vielen Dank.
MP

Corona-Warn-App Open Source Team
