### ISSUE TITLE
Scanning 2 different QR-Codes not possible

### ISSUE THREAD

**Issue by ucmichan** [corona-warn-app/cwa-app-android#1117]
Actions
1. Scan a Corona Test QR Code from laboratory which is not connected with the App
2. Try to scan another Corona Test QR Code

Expected Result
New QR Code will be added to the App.

Actual Result
- The button "Test anzeigen" for the first test is outgreyed
- It is not possible to scan another Corona Test QR Code

**Comment by thomasaugsten** [comment]
Did you remove the test before scanning a new one?

**Comment by daimpi** [comment]
@ucmichan Are you able to delete the first (invalid) test, or is even this not possible like [here](https://github.com/corona-warn-app/cwa-app-android/issues/1084)?

It is currently unfortunately not possible to have multiple tests in the app at the same time: https://github.com/corona-warn-app/cwa-wishlist/issues/109

**Comment by ucmichan** [comment]
No it was not possible to delete the first test. In the main overview, it says "Datenabruf" for the Test-field but nothing happens. The button "Test anzeigen" is outgreyed. I cannot delete the first test.

**Comment by thomasaugsten** [comment]
We working on this to fix this. Please use the settings in the app to reset the app. No stored key will be deleted but you have to onboard again and the counter will start from 1of14 days. But all keys of the last 14 day will be checked

**Comment by Marco2907** [comment]
Hi @ucmichan, thanks for sharing your content. I will close this issue because this is related to the parent issue https://github.com/corona-warn-app/cwa-website/issues/345 

Thanks,
MP

Corona-Warn-App Open Source Team
