### ISSUE TITLE
Risikostatus wird nicht aktualisiert 

### ISSUE THREAD

**Issue by Yvonne0407** [corona-warn-app/cwa-app-android#1119]
Nach Update auf die neueste Version 1.3.0 keine Aktualisierung des Risikostatus. Auch nach aus- und wieder einschalten keine Änderung. 

![Screenshot_20200905-090605_Corona-Warn](https://user-images.githubusercontent.com/70796367/92301024-28491b00-ef60-11ea-9f84-9521aabb78bb.jpg)

Smartphone: Samsung Galaxy A50
![Screenshot_20200905-093034_Settings](https://user-images.githubusercontent.com/70796367/92301054-91c92980-ef60-11ea-85d7-7bf2e940c17c.jpg)

---
Internal tracking ID: EXPOSUREAPP-2213

**Comment by thomasaugsten** [comment]
39508 sagt das bereits schon eine Berechnung lief. Einfach bis morge. Warten dann müsste der Fehler weg sein. Wir werden Zeitnah eine Version veröffentlich bei dem das Tageslimit nicht so schnell erreicht wird.

**Comment by bufemc** [comment]
OK, hier also in deutsch. Hatte das Gleiche hier beschrieben: https://github.com/corona-warn-app/cwa-app-android/issues/1081

Das Problem tritt hier bei einem Handy auf, was die meiste Zeit aus ist, oft tagelang. Dann schalte ich es an, und habe trotzdem diesen Fehler. Obwohl es ja tagelang aus war. Warum wird da dann trotzdem das Limit erreicht? Laeuft da ggf. im Background etwas krumm? Wollte ich nur auch noch einwerfen, auch wenn mein Fall ggf. speziell ist, jage ich zu gerne Bugs.

**Comment by daimpi** [comment]
Das tracking issue für das rate limiting Problem (Error 39508) findet sich übrigens hier: #1021 🙂.

**Comment by Yvonne0407** [comment]
Es erklärt sich mir nicht. Immer wieder die gleiche Fehlermeldung.-- Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 05.09.20, 15:24 schrieb Daniel Frey <notifications@github.com>:

   
  Das tracking issue für das rate limiting Problem (Error 39508) findet sich übrigens hier: #1021 🙂.

**Comment by daimpi** [comment]
> Es erklärt sich mir nicht. Immer wieder die gleiche Fehlermeldung.

Ich verstehe leider nicht genau was du meinst. Hast du schon folgendes versucht: Die App beenden -> 24h warten -> App wieder öffnen?

**Comment by Yvonne0407** [comment]
Hab ich alles schon versucht.Hab die App jetzt de- und wieder neu installiert. Muss ich jetzt eben wieder ein paar Tage warten, bis die Risiko-Ermittlung funktioniert. Ich hoffe, dass die Aktualisierung trotzdem täglich geschieht.-- Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 05.09.20, 22:50 schrieb Daniel Frey <notifications@github.com>:

   
   
   Es erklärt sich mir nicht. Immer wieder die gleiche Fehlermeldung. 
   
  Ich verstehe leider nicht genau was du meinst. Hast du schon folgendes versucht: Die App beenden -> 24h warten -> App wieder öffnen?

**Comment by Marco2907** [comment]
Hallo @Yvonne0407 vielen Dank für deine Info. Besteht der von dir beschriebene Fehler aktuell immer noch? Falls ja, würde ich diesen Punkt mit zu unserem Entwicklungsteam mit aufnehmen und besprechen. 

Viele Grüße,
MP

Corona-Warn-App Open Source Team

**Comment by Yvonne0407** [comment]
Hallo,ich habe die App de- und wieder neu installiert. Bis jetzt läuft sie ohne Fehlermeldung, auch Tägliche Aktualisierung funktioniert auch wieder.Leider sind nun die letzten 14 Tage futsch, aber ich bin optimistisch. Danke für die Unterstützung und bleibt gesund.-- Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 08.09.20, 15:04 schrieb Marco2907 <notifications@github.com>:

   
  Hallo @Yvonne0407 vielen Dank für deine Info. Besteht der von dir beschriebene Fehler aktuell immer noch? Falls ja, würde ich diesen Punkt mit zu unserem Entwicklungsteam mit aufnehmen und besprechen. 
  Viele Grüße, MP 
  Corona-Warn-App Open Source Team

**Comment by svengabr** [comment]
Hello @Yvonne0407, thank you very much for your feedback.

I am happy to announce that the error 39508 is well known by the development team and a fix is going to be rolled out within the next days with the hotfix release 1.3.1.

There are currently many issues opened regarding the same issue. To keep the board clean, I need to close your issue as a duplicate. If you want to contribute to the existing discussion, please use the main issue [here](https://github.com/corona-warn-app/cwa-app-android/issues/1021).

* [CAUSE: 3 Something went wrong. ApiException: 39508 #1021 ](https://github.com/corona-warn-app/cwa-app-android/issues/1021)
* [Resetting the CWA triggers error 39508 #934](https://github.com/corona-warn-app/cwa-app-android/issues/934)
* [Risikostatus wird nicht aktualisiert #1119](https://github.com/corona-warn-app/cwa-app-android/issues/1119)
* [Fehler bei Kommunikation mit Google API (39508) #774](https://github.com/corona-warn-app/cwa-app-android/issues/774)
* [Auf Samsung Handy seit 2 Wochen Fehlermeldung 39508 #1130](https://github.com/corona-warn-app/cwa-app-android/issues/1130)
* [Google APIException (39508) after using the SwissCovid App #816 ](https://github.com/corona-warn-app/cwa-app-android/issues/816)

Best regards,
SG

Corona-Warn-App Open Source Team

**Comment by svengabr** [comment]
Duplicate of https://github.com/corona-warn-app/cwa-app-android/issues/1021
