### ISSUE TITLE
Entweder: fehlende Benachrichtigung trotz Begegnung mit hohem Risiko, oder: falsche Darstellung einer "milden" Risikobegegnung

### ISSUE THREAD

**Issue by AlfonsoMuskedunder** [corona-warn-app/cwa-app-android#1184]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Describe the bug
Vorab bitte ich um Entschuldigung, falls ich meine Fragen in der falschen issue-Kategorie stelle - keine kam mir genau passend vor. Mein Fall könnte sich aber um einen bug handeln (fehlende Benachrichtigung trotz schwerwiegender Risikobegegnung).

Nun zur Frage: Am Sonntag, 13. September, bin ich durch die CWA durch eine getriggerte Benachrichtigung gewarnt worden, dass ich am Dienstag zuvor eine Risikobegegnung gehabt habe. Seitdem zeigt mir die App ein "erhöhtes Risiko" an. Soweit, so erwartbar.

Heute ca. 9:30 habe ich die zufällig App geöffnet und musste feststellen, dass mir nun 2 Risikobegebnungen angezeigt werden. Die letzte Begegnung muss am 15.9. stattgefunden haben. Allerdings hat die App keine Warnungsbenachrichtigung ausgelöst; dabei zeigt sie an, dass sie heute schon um 7:26 aktualisiert wurde.

Nun frage ich mich: Kann die App hinsichtlich der Darstellung überhaupt zwischen verschieden schwerwiegenden Risikobegegnungen differenzieren, wenn bereits seit einer früheren Risikobegegnung ein erhöhtes Risiko angezeigt wird?

- Einerseits liest sich der Erklärtext eindeutig so, als sei auch die letzte Begegnung kritisch gewesen:
> Sie haben ein erhöhtes Infektionsrisiko, da Sie zuletzt vor 4 Tagen mindestens einer nachweislich Corona-positiv getesteten über einen längeren Zeitraum und mit einem geringen Abstand begegnet sind.
- andererseits weiß ich aus eigener Erfahrung, dass kurze/weit entfernte Risikokontakte zwar angezeigt werden, aber keine Warnbenachrichtigung auslösen

Ich könnte mir vorstellen, dass meine zweite Risikobegegnung nur kurz war, weswegen keine Warnbenachrichtigung getriggert wurde, und sie dennoch als schwerwiegende Begegnung dargestellt wird, da das Interface gar keine Möglichkeit vorsieht, eine Begegnung mit "kleinem" Risiko abzubilden, sobald der Status von vorneherein durch eine vorherige Begegnung ein hohes Risiko anzeigt.

Ich wäre dankbar, wenn die Entwickler hierzu Stellung nehmen könnten. Falls keine Differenzierung vorgesehen ist, wäre vielleicht zu bedenken, ob man eine solche einführt.

----
Internal Tracking ID: EXPOSUREAPP-2874

**Comment by daimpi** [comment]
> Ich könnte mir vorstellen, dass meine zweite Risikobegegnung nur kurz war, weswegen keine Warnbenachrichtigung getriggert wurde, und sie dennoch als schwerwiegende Begegnung dargestellt wird, da das Interface gar keine Möglichkeit vorsieht, eine Begegnung mit "kleinem" Risiko abzubilden, sobald der Status von vorneherein durch eine vorherige Begegnung ein hohes Risiko anzeigt.

Damit liegst du wahrscheinlich richtig. Genau vor diesem Problem hat @kbobrowski bereits [hier](https://github.com/corona-warn-app/cwa-documentation/issues/422) gewarnt.

Leider haben wir vom CWA-Team bisher noch nichts dazu gehört.

Kannst du vll. mal deinen ENF log hier teilen?

**Comment by AlfonsoMuskedunder** [comment]
@daimpi Danke für den Hinweis, das verlinkte issue hatte ich übersehen. Der Poster geht ja bereits davon aus, dass die _Darstellung_ falsch ist - ich hielt es zumindest auch für möglich, dass versehentlich keine Warnung ausgelöst wurde.

Hier ist auf jeden Fall mein log file:
[all-exposure-checks.txt](https://github.com/corona-warn-app/cwa-app-android/files/5250221/all-exposure-checks.txt)
(Ich hatte ja gehofft, dass man im log Informationen zur Dauer und Distanz finden würde, aber das wird ja anscheinend nicht vorgehalten. Kannst du mir übrigens nebenbei sagen, was sich genau hinter der Variablen "keyCount" verbirgt?)

**Comment by daimpi** [comment]
> Der Poster geht ja bereits davon aus, dass die Darstellung falsch ist - ich hielt es zumindest auch für möglich, dass versehentlich keine Warnung ausgelöst wurde.

Ja, ich denke beides ist möglich, die neue Begegnung könnte "niedriges Risiko" oder "erhöhtes Risiko" gewesen sein, afaik lässt sich das momentan nicht unterscheiden.

> Hier ist auf jeden Fall mein log file:
all-exposure-checks.txt

Thanks 🙂.
Ich hab deinen log mal in den [EN analyzer](https://felixlen.github.io/ena_log/) gesteckt und folgenden output erhalten: 
![grafik](https://user-images.githubusercontent.com/22129968/93686512-077fda00-fab7-11ea-8f70-670e8eb4a1c0.png)

Wir können dort zwei Sachen sehen:
1. Die Person mit der du eine Begegnung mit erhöhtem Risiko (rot) hattest hat ihre Schlüssel am 12.09 hochgeladen.
2. Die Person mit der du eine Begegnung mit erhöhtem oder niedrigem Risiko hattest hat ihre Schlüssel am 18.09 hochgeladen.

Aber da dein Risikostatus "erhöht" ist, weißt du ja sogar den Tag an welchem die Begegnungen jeweils stattgefunden haben.

> Ich hatte ja gehofft, dass man im log Informationen zur Dauer und Distanz finden würde, aber das wird ja anscheinend nicht vorgehalten

Diese Informationen stehen prinzipiell zur Verfügung und können auch von der CWA abgerufen werden, aber das RKI hat sich scheinbar dagegen entschieden siehe [dieses issue](https://github.com/corona-warn-app/cwa-wishlist/issues/100).

> Kannst du mir übrigens nebenbei sagen, was sich genau hinter der Variablen "keyCount" verbirgt?

Ja: Das ist die Anzahl der Schlüssel die in einem Paket für einen bestimmten Tag stecken. Du kannst [hier](https://micb25.github.io/dka/) sehen wie viele Schlüssel in den jeweiligen Paketen in den vergangenen Tagen enthalten waren: 
![grafik](https://user-images.githubusercontent.com/22129968/93686994-6c88ff00-faba-11ea-9424-5716dbd89d66.png)
Und `matchesCount` ist dann die Anzahl der Schlüssel in diesem Paket mit denen du ein match hattest.
Siehe auch der entsprechenden FAQ Eintrag [hier](https://www.coronawarn.app/de/faq/#keys_matches).

**Comment by thomasaugsten** [comment]
Zurzeit wird nur bei einem Wechsel von grüner zur roten Risikokarte eine Benachrichtigung ausgegeben, da wir auch in der Api nicht genau unterscheiden können ob die zweite Begegnung auch ein erhöhtes Risiko ist. Dazu müssten wir weitere API calls aufrufen die dazu führen, dass jeden Tag für jede Risikobegegnung eine Push Notification vom OS angezeigt wird.

**Comment by AlfonsoMuskedunder** [comment]
Danke für die Antwort!

> Zurzeit wird nur bei einem Wechsel von grüner zur roten Risikokarte eine Benachrichtigung ausgegeben, da wir auch in der Api nicht genau unterscheiden können ob die zweite Begegnung auch ein erhöhtes Risiko ist.

Wenn ich dies richtig verstehe, fände ich das in doppelter Hinsicht sehr problematisch!

1. Fall: es handelt sich bei der zweiten Begegnung tatsächlich um ein erhöhtes Risiko. Viele Nutzer werden sich darauf verlassen, dass sie in einem solchen Fall stets eine Push-Benachrichtigung erhalten und nicht täglich in der App nachsehen, sodass viele der erneuten Risikobegegnungen unerkannt bleiben. Dadurch könnten auch viele Infektionen unerkannt oder unnötig spät erkannt werden.
2. Fall: es handelt sich bei der zweiten Begegnung tatsächlich um ein "niedriges" Risiko. Nutzer, die diese bemerken und nicht wissen, dass es sich um ein low risk handelt, werden unter der Prämisse eines erhöhten Risikos ihren Arzt aufsuchen, der sich im Zweifel für eine Testung entscheidet. Zumindest in den Fällen einer Nichtinfektion kommt es zu unnötigen Kosten (Testung, Arbeitsausfall bis zum Testergebnis etc.)

Beide 'falsche' Einschätzungen würden zu unnötigen persönlichen und, in der Masse, gesellschaftlichen und volkswirtschaftlichen Kosten führen.

**Comment by AnOtherMuenchner** [comment]
Auch bei einem "niedrigen Risiko" wäre es für den Nutzer sehr hilfreich, wenn man Informationen bekommen würde, wann die Begegnung war. So weit liegen die Kontake nicht in der Vergangenheit und man kann sich wahrscheinlich sogar daran erinnern, was man zu dem Zeitpunkt gemacht hat oder man hat vielleicht sogar die eine oder andere Situation gezielt im Gedächtnis.

Auf jeden Fall würde es einen beruhigen, wenn man sich ziemlich sicher wäre, dass man zu dem Zeitpunkt eigentlich alleine war und der Kontakt wirklich weit weg gewesen sein muss. Man könnte aber auch handeln, wenn man wüßte, dass der Kontakt wohl doch weitaus näher war und das Signal wahrscheinlich aber stark abgeschwächt wurde.

**Comment by daimpi** [comment]
@thomasaugsten 
> Dazu müssten wir weitere API calls aufrufen die dazu führen, dass jeden Tag für jede Risikobegegnung eine Push Notification vom OS angezeigt wird.

Und ich vermute, dass das aus den gleichen Gründen die du [hier](https://github.com/corona-warn-app/cwa-app-android/issues/1066#issuecomment-678752471) genannt hast unerwünscht ist, right?
> The data privacy has strictly standards to not show any push notifications where other people can see the app is installed or the person received a test result. If it's really necessary the notification must not show sensible information or any hints that the person did a test.

Falls das der Fall ist: Erwartest du, dass sich diese Situation mit [ENF v.1.5+ und `ExposureWindow` mode](https://github.com/corona-warn-app/cwa-documentation/issues/373) verbessert?

**Comment by daimpi** [comment]
@AnOtherMuenchner 
> Auch bei einem "niedrigen Risiko" wäre es für den Nutzer sehr hilfreich, wenn man Informationen bekommen würde, wann die Begegnung war. So weit liegen die Kontake nicht in der Vergangenheit und man kann sich wahrscheinlich sogar daran erinnern, was man zu dem Zeitpunkt gemacht hat oder man hat vielleicht sogar die eine oder andere Situation gezielt im Gedächtnis.
> 
> Auf jeden Fall würde es einen beruhigen, wenn man sich ziemlich sicher wäre, dass man zu dem Zeitpunkt eigentlich alleine war und der Kontakt wirklich weit weg gewesen sein muss. Man könnte aber auch handeln, wenn man wüßte, dass der Kontakt wohl doch weitaus näher war und das Signal wahrscheinlich aber stark abgeschwächt wurde.

Es gibt dafür auch bereits ein issue: https://github.com/corona-warn-app/cwa-wishlist/issues/178.

Feel free to upvote 🙂.

**Comment by thomasaugsten** [comment]
Korrekt die Anzahl der Push Notification sollen auf ein Minimum reduziert werden.
Es wird mit ExposureWindows nicht unbedingt besser deswegen müssen wir die Umsetzung genau durchdenken.
Mit ExposureWindow hat man nicht mehr die Exposure pro TEK für jeden Tag. Es gibt dann nur noch 30 Minuten die dann bereitgestellt werden. Bei 5 ExposureWindows kann man nicht mehr sagen ob sie von einem TEK stammen oder von 5 unterschiedliche TEKs stammen. Zwar hat man zusätzliche Information via infectiousness abrufen aber da kann man auch nicht herausfinden ob die infectiousness aus 1 oder X TEKs mit der infectiousness stammen.

**Comment by AnOtherMuenchner** [comment]
> Korrekt die Anzahl der Push Notification sollen auf ein Minimum reduziert werden.

Nachdem es nur einen Check pro Tag gibt, kann es auch nur eine Push-Benachrichtigung pro Tag geben.

Ich finde, ein Treffer ist selbst bei geringem Risiko eine Nachricht wert. Es erhöht nicht unbedingt das Vertrauen, wenn die App nichts sagt, man aber zufällig nachschaut und dann doch was sieht. Wenn die Treffer so unbedeutet sind, dann sollte man sie besser komplett verstecken und nur auf explizites Nachschauen in einem Menüpunkt anzeigen.

**Comment by AlfonsoMuskedunder** [comment]
> Zurzeit wird nur bei einem Wechsel von grüner zur roten Risikokarte eine Benachrichtigung ausgegeben, da wir auch in der Api nicht genau unterscheiden können ob die zweite Begegnung auch ein erhöhtes Risiko ist. Dazu müssten wir weitere API calls aufrufen die dazu führen, dass jeden Tag für jede Risikobegegnung eine Push Notification vom OS angezeigt wird.

@thomasaugsten Danke für die Info. Ich würde jedenfalls generell zwei Dinge erwarten:

1. Dass die App mich _in jedem Fall_ per push benachrichtigt, wenn ein high risk encounter stattgefunden hat,
2. Dass nicht ein tatsächlicher low risk encounter im Textbaustein "So wird ihr Risiko ermittelt" als high risk encounter beschrieben wird.

Beide Erwartungen verletzt die App aber bei roter Risikokarte, was ich für gefährlich halte. Um die gewünschte Funktionalität wiederherzustellen, müsste ich in meiner Situation jedenfalls offenbar die App de- und wieder reinstallieren, was dann doch ein fragwürdiges UX design wäre.

**Comment by thomasaugsten** [comment]
Eine Neuinstallation hilft auch nicht weil die API bei der riskscore nicht zwischen high oder low risk unterscheidet sondern die Gesamtheit der exposures.

**Comment by daimpi** [comment]
@thomasaugsten thanks für die Info 🙂.
> Es gibt dann nur noch 30 Minuten die dann bereitgestellt werden. Bei 5 ExposureWindows kann man nicht mehr sagen ob sie von einem TEK stammen oder von 5 unterschiedliche TEKs stammen.

Genau zu diesem Thema hatten wir auch gerade kürzlich [eine Diskussion](https://covidapps.slack.com/archives/C0194ML0MLN/p1599515968088100) auf Slack 😄. 

Btw: feel free to join us there: [invitation link](https://join.slack.com/t/covidapps/shared_invite/zt-gmgl4l13-E4Xcn1ZfPFsPz6V_KjROCg)

**Comment by AlfonsoMuskedunder** [comment]
> Eine Neuinstallation hilft auch nicht weil die API bei der riskscore nicht zwischen high oder low risk unterscheidet sondern die Gesamtheit der exposures und ein riskscore für diese berechnet..

Gibt es denn keine Möglichkeit, die alten Datenpakete komplett zu löschen? Falls doch, müsste doch danach wieder die gründe Risikokarte ausgegeben werden und erst zukünftig neu auftretende high risks eine push-Nachricht triggern?

**Comment by vaubaehn** [comment]
@AlfonsoMuskedunder 
Du könntest via Android > Settings > Google > Covid-19-Benachrichtigungen > Zufallskennungen löschen tatsächlich ALLE alten Datenpakete der letzten 14 Tage löschen. Das wäre aber so, als hättest du die Corona-Warn-App gerade erst installiert: alle Begegnungen der letzten 14 Tage wären gelöscht, und falls du demnächst positiv getestet werden würdest (natürlich hoffentlich nicht!), könnte auch niemand, der dir in den vergangenen 14 Tagen begegnet ist, gewarnt werden.

**Comment by heinezen** [comment]
Hey everyone,

Thanks for all the feedback. The issue is now tracked in Jira ticket EXPOSUREAPP-2874.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
Hallo @AlfonsoMuskedunder 

seit der Meldung hier vom 19.09.2020 ist eine Menge in der App verbessert worden. Vielleicht schaust Du die [Blog-Beschreibung der Version 1.12](https://www.coronawarn.app/de/blog/2021-02-10-corona-warn-app-version-1-12/) an? Dort wird gezeigt, wie in der App Begegnungen kalendarisch dargestellt werden. Diese Version ist diese Woche freigegeben worden und über den [Google Play Store](https://play.google.com/store/apps/details?id=de.rki.coronawarnapp) zu bekommen.

Auch interessant ist die [Blog-Beschreibung der v2 Risikoberechnung](https://www.coronawarn.app/de/blog/2020-12-17-risk-calculation-exposure-notification-framework-2-0/), die mit der [Version 1.9](https://www.coronawarn.app/de/blog/2020-12-16-corona-warn-app-version-1-9/) eingeführt wurde.

**Comment by heinezen** [comment]
Hello everyone,

Since this issue was created, the app interface has changed a lot to mitigate confusion regarding risk encounters.

* The app switched to ENFv2 with a more refined risk calculation
* The UI was improved to show the exact date of risk encounters

The issue described here should no longer happen. We will therefore close this issue.

----
Corona-Warn-App Open Source Team
