### ISSUE TITLE
Extra space in FAQ link stops selection of specific FAQ entry

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#1199]
## Avoid duplicates 
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue
Follow-on from closed https://github.com/corona-warn-app/cwa-app-android/issues/1043 addressed by @tkowark 
@harambasicluka also involved.

## Describe the bug
In the following error message:
the link to https://www.coronawarn.app/en/faq/ goes to the top level of the FAQs.

CAUSE: 3
Something went wrong.
Your Corona-Warn-App is correctly installed, but the "COVID-19 exposure notifications" service is not available on your smartphone's operating system. This means that you cannot use the Corona-Warn-App. For further information, please see our FAQ page: https://www.coronawarn.app/en/faq/
(17)

![FAQ17](https://user-images.githubusercontent.com/66998419/93783219-c1985280-fc2b-11ea-8078-93802d8f72c1.gif)

## Expected behaviour

Clicking on the link https://www.coronawarn.app/en/faq/
(17) should go to https://www.coronawarn.app/en/faq/(17) not to https://www.coronawarn.app/en/faq/

## Steps to reproduce the issue

See https://github.com/corona-warn-app/cwa-app-android/issues/1043
1. Install apk (for instance from [apkmirror.com](https://www.apkmirror.com/apk/robert-koch-institut/corona-warn-app/)) on [Android Emulator](https://developer.android.com/studio/run/emulator) for version less than Android 11 (API 30) which by design lacks bluetooth hardware capability.
2. Run through onboarding.

## Technical details

Mobile device: Virtual device Nexus 5X with Play Store, release Q, API 29.
CWA version: ~~1.3.0~~ 1.3.1
Android version: 10
Google Play services 20.33.15

## Possible Fix

Check how URL is formulated.

## Additional context

This is a regression from CWA version 1.2.0. On the older version the URL displays as complete and clickable https://www.coronawarn.app/en/faq/(17) .

The repro steps should not occur in practice because CWA cannot run on an Android emulator, however it could be that the problem can also occur on a real mobile device due to other reasons.

Also there is mention about brackets being converted to # in https://github.com/corona-warn-app/cwa-app-android/pull/1074

---
Internal Tracking ID: EXPOSUREAPP-2859

**Comment by MikeMcC399** [comment]
@tkowark Are you available to look at this?

https://github.com/corona-warn-app/cwa-app-android/issues/1204 also shows a screenshot with a malformed link to https://www.coronawarn.app/de/faq/ (39508) . It looks like an extra space has crept in.

Removing the space and writing https://www.coronawarn.app/de/faq/(39508) resolves to https://www.coronawarn.app/de/faq/#API39508 as probably intended instead of linking to the top level of the FAQs at https://www.coronawarn.app/de/faq/

**Comment by tkowark** [comment]
@MikeMcC399 if the app generates malformed links, this topic has to be solved by the app team (e.g., @harambasicluka ).

What I could do in the website is create a redirect page for (17) so you would be directed to the right entry.

**Comment by MikeMcC399** [comment]
@tkowark Thanks for clarifying that the app team needs to step in.
The URL that Android uses, when tapping on the link in the error message, is https://www.coronawarn.app/de/faq/ , without the "(17)" which just appears as text after the URL. So I was inaccurate to say this is a malformed URL. https://www.coronawarn.app/de/faq/ is a valid URL, it is just not the URL which is intended to be used!

**Comment by MikeMcC399** [comment]
The space was added for 1.3.0. Perhaps somebody from the app team e.g. @harambasicluka could check that this addition was actually intended?

https://github.com/corona-warn-app/cwa-app-android/blob/1.2.1/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/reporting/ErrorReportReceiver.kt#L52
message += "($apiStatusCode)"

https://github.com/corona-warn-app/cwa-app-android/blob/1.3.0/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/reporting/ErrorReportReceiver.kt#L52
message += " ($apiStatusCode)"

**Comment by vaubaehn** [comment]
Hi, as far as I can see, the issue will be fixed in https://github.com/corona-warn-app/cwa-app-android/pull/1074/files , planned to be deployed in CWA 1.4.0.
@tkowark 's redirect method should be in effect then.

#whereistkowark
(you have been missed... Will we see you here again more often?)

**Comment by MikeMcC399** [comment]
@vaubaehn 
You are right about https://github.com/corona-warn-app/cwa-app-android/pull/1074/files [Fix: Replaced brackets with leading # to match website faq structure (EXPOSUREAPP-2261)](https://github.com/corona-warn-app/cwa-app-android/pull/1074/files) as (EXPOSUREAPP-2261) is listed under https://github.com/corona-warn-app/cwa-app-android/releases/tag/1.4.0-SNAPSHOT-RC1

Perhaps though the removal of the extra space in https://github.com/corona-warn-app/cwa-app-android/blob/1.2.1/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/reporting/ErrorReportReceiver.kt#L52 before the first bracket "(" of message += " ($apiStatusCode)" could be slipped into 1.3.1 hotfixes? Do we have a timeline for the 1.3.1 and 1.4.0 releases?

The problem is also reproducible by resetting the app if it has already retrieved keys for the current day. It shows up more clearly there because the final / and the (apiStatusCode) are all on one line in the following example:

![39508](https://user-images.githubusercontent.com/66998419/93899356-84e45e00-fcf4-11ea-9b9b-8b20eb8ca92d.jpg)

**Comment by vaubaehn** [comment]
@MikeMcC399 , yes, completely agree: deploying #1074 already in Hotfix 1.3.1 would defitively be good!
But this is in the hands of @JoachimFritsch , I guess.

**Comment by tkowark** [comment]
Just to go quickly off-topic and answer @vaubaehn 's question
> #whereistkowark
(you have been missed... Will we see you here again more often?)

First of all: thank you very much for the kind words! Unfortunately, I will not be around more often as I've transitioned out of the CWA project and are now working on other projects within SAP (but sometimes I see the @-mentions and cannot resist answering ;)). Thank you all again for you commitment to this project, constantly reporting upcoming issues and working with us to find solutions. This really is a once-in-a-lifetime experience for me!

**Comment by heinezen** [comment]
Hey @MikeMcC399,

The issue is now mirrored to Jira (EXPOSUREAPP-2859) and tracked, so everyone in here should get updated once more information becomes available or when the issue is resolved.

Thanks for reporting
CH

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
The issue is no longer reproducible on CWA 1.5.0.

I installed CWA 1.5.0 via apk on Android emulator Pixel 3a API 29 (Android 10) with Play Store installed. 

CWA threw error CAUSE: 3 with FAQ link
https://www.coronawarn.app/en/faq/#17 which opened the specific entry https://www.coronawarn.app/en/faq/#cause_3

Now closing this issue. Probably the internal tracking ID EXPOSUREAPP-2859 can also be closed.
