### ISSUE TITLE
Replace Try/Catch with CoroutineExceptionHandler for Exposure Notification Exceptions.

### ISSUE THREAD

**Issue by jakobmoellersap** [corona-warn-app/cwa-app-android#12]
## Current Implementation
The current Exposure Notification Client uses Try Catches for reporting Exceptions which is a hassle to implement correctly and error-prone.

## Suggested Enhancement
We should use a dedicated CoroutineExceptionHandler that is able to catch Errors from dedicated threads so that we have a smooth exit scenario in the error cases.

## Expected Benefits
A better UX by providing consistent crash scenarios.

**Comment by RickorDD** [comment]
This is a good point. I use this code in my project:

val coroutineExceptionHandler =
                    CoroutineExceptionHandler { _,
                                                t ->
                        Log.i("APP"," CoroutineException $t")
                    }
CoroutineScope(Dispatchers.IO + coroutineExceptionHandler).launch

What is with "optionals" in 
suspend fun getDateIndex(@Url url: String): List<String>
vs
suspend fun getDateIndex(@Url url: String?): List<String>

**Comment by jakobmoellersap** [comment]
we instead use explicit reporting into Dialog Messages and resort to Error logs instead. This was resolved in #176 and some follow-ups
