### ISSUE TITLE
Ursache 3 (21./22.09.2020)

### ISSUE THREAD

**Issue by Mithgarthsormr** [corona-warn-app/cwa-app-android#1204]
Ich hatte heute einen Fehler "Ursache 3". Siehe Screenshots. 

![Screenshot_20200922-071854_Corona-Warn](https://user-images.githubusercontent.com/60277471/93868584-ed1e4a00-fcca-11ea-81da-acfceb685946.jpg)
![Screenshot_20200922-071704_Corona-Warn](https://user-images.githubusercontent.com/60277471/93868586-ee4f7700-fcca-11ea-8143-d0937beafb7c.jpg)
![Screenshot_20200922-071852_Corona-Warn](https://user-images.githubusercontent.com/60277471/93868588-eee80d80-fcca-11ea-9c13-4a88a1ea0553.jpg)

## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Mobile device:
- Android version:

**Comment by MikeMcC399** [comment]
Hallo @Mithgarthsormr 
es gibt unter https://github.com/corona-warn-app/cwa-app-android/issues/1021 eine detaillierte Diskussion über diese Problematik.

Bzw. unter https://www.coronawarn.app/de/faq/#API39508 ist das Problem in den FAQs auch beschrieben.

**Comment by Mithgarthsormr** [comment]
Laut FAQ ist dieses Problem bereits behoben, ich habe allerdings die aktuellste Version installiert, die im Google Play Store bereitsteht

**Comment by MikeMcC399** [comment]
Das Problem ist leider in der aktuellen Android Version 1.3.0 noch nicht behoben.

**Comment by daimpi** [comment]
@Mithgarthsormr 
Das ist ein rate-limiting Error, also im Endeffekt hat die App heute bereits zu häufig versucht auf ein bestimmte API Funktion zuzugreifen. Was da normalerweise hilft: App beenden -> 24h warten -> App wieder öffnen.

Das limit wird nämlich jeden Tag (um 02:00 Uhr CEST) wieder zurückgesetzt.

Die Kontaktaufzeichnung ist dadurch allerdings nicht beeinträchtigt, nur beim Abgleich gibt es ein Problem.

Einen nachhaltigen Patch für das Problem bekommen wir wohl leider erst mit CWA 1.4.

**Comment by daimpi** [comment]
Duplicate of #1021

**Comment by sikraemer** [comment]
@daimpi 
Ich habe auch einen "Ursache 3"-Fehler seit dem Update von Android auf Version 11.
Kann ich davon ausgehen, dass es sich hierbei auch um das gleiche Fehlerbild handelt?

Mich beunruhigt etwas, dass laut App noch nicht lange genug aktiv sei um ein Risiko auszugeben.
Ich habe die App seit nahezu Beginn installiert und heute morgen war noch alles okay.

![Screenshot_20200923-183755](https://user-images.githubusercontent.com/11752354/94042975-7ff2dd80-fdcc-11ea-9053-ba8bb373a589.png)
![Screenshot_20200923-183804](https://user-images.githubusercontent.com/11752354/94042993-841efb00-fdcc-11ea-895f-6acbd8b759f6.png)

**Comment by daimpi** [comment]
@sikraemer Ich glaube nicht, dass es sich bei dir um Fehler 39508 handelt. Das scheint ein anderes Problem zu sein. Willst du dafür vll. ein neues issue aufmachen?

**Comment by sikraemer** [comment]
@daimpi 
Jetzt tut wieder alles und auch die Daten werden wieder korrekt angezeigt. Sehr seltsam...

Wenn es hilft, kann ich dennoch ein Issue aufmachen.

**Comment by daimpi** [comment]
@sikraemer ok super, dass es wieder läuft 👍.
Wann hast du denn auf Android 11 geupdated d.h. wie lange hattest du diesen Fehler bevor er jetzt wieder verschwunden ist?

> Wenn es hilft, kann ich dennoch ein Issue aufmachen.

Da der Fehler jetzt wieder weg ist, brauchst du denke ich erst mal kein issue aufmachen… beobachte das aber mal weiter und falls der Fehler wieder kommt mach gerne ein issue dafür auf 🙂.

**Comment by sikraemer** [comment]
@daimpi Geht klar.

Ganz genau hab ich aber nicht auf die Zeiten geachtet.

Installiert habe ich das Update am Vormittag - denke zwischen und 9 und 11 Uhr.
Aufgefallen ist mir der Fehler erst gegen ca. 17 Uhr.
So ca. 20:30 habe ich dann nochmal in die App gesehen und da ging wieder alles.

**Comment by svengabr** [comment]
Duplicate of https://github.com/corona-warn-app/cwa-app-android/issues/1021

**Comment by svengabr** [comment]
Hello everyone,

thank you all for your feedback so far. Since there are currently several issues with exactly the same problem, I need to close this issue to move the discussion to a central place.

Please continue the discussion here: #1021

I will link the existing findings in Jira so the information on this ticket won't get lost.

Best regards,
SG

Corona-Warn-App Open Source Team
