### ISSUE TITLE
Support the app in other Regions than Germany to allow foreign travels to get their results

### ISSUE THREAD

**Issue by Antonknopf** [corona-warn-app/cwa-app-android#1207]
The Corona Warn App is the way to view the results of a corona test that all travels coming from risk areas must go through.

Unfortunately it is currently not possible to install the app if the Google account isn't registered in Germany. 
Google only allows to change the country once per year so changing the country temporarily is not a solution.

As the German Government has chosen this route to distribute results, it should be possible for people from outside of Germany to install the app independent of their Country association.

**Comment by daimpi** [comment]
Which country are you currently using? Here is the list of countries for which CWA should work: https://www.coronawarn.app/en/faq/#international

If yours not yet supported, you can create an entry in the wishlist repo for your country or upvote an existing one: https://github.com/corona-warn-app/cwa-backlog/issues/9#issuecomment-648745301

Other than that you can also use the following workaround [suggested ](https://github.com/corona-warn-app/cwa-app-android/issues/993#issuecomment-671912052) by @kbobrowski for quering your test-results: 
> you can also grab recent APK and sideload it: https://www.apkmirror.com/apk/robert-koch-institut/corona-warn-app/corona-warn-app-1-1-1-release/corona-warn-app-1-1-1-android-apk-download/
> 
> Note that it won't update automatically, and as soon as CWA is released in your Play Store country you should uninstall it and install from Play Store, but for now I guess using it like this is better than not using at all.

**Comment by Antonknopf** [comment]
I need the support for the United States of America.
USA is currently not part of the supported countries.

**Comment by MikeMcC399** [comment]
There is a wishlist topic https://github.com/corona-warn-app/cwa-wishlist/issues/41 for supporting the USA Google Play Store, which is worthwhile reading to get the latest status.

There is also an [FAQ entry](https://www.coronawarn.app/en/faq/#international) which just discusses the general question of international Google Play Stores.

**Comment by MikeMcC399** [comment]
@daimpi 
> you can also grab recent APK and sideload it: https://www.apkmirror.com/apk/robert-koch-institut/corona-warn-app/corona-warn-app-1-1-1-release/corona-warn-app-1-1-1-android-apk-download/

Better to link to the version independent URL https://www.apkmirror.com/apk/robert-koch-institut/corona-warn-app/ since version 1.1.1 is no longer recent.

**Comment by svengabr** [comment]
> 
> 
> Which country are you currently using? Here is the list of countries for which CWA should work: https://www.coronawarn.app/en/faq/#international
> 
> If yours not yet supported, you can create an entry in the wishlist repo for your country or upvote an existing one: [corona-warn-app/cwa-backlog#9 (comment)](https://github.com/corona-warn-app/cwa-backlog/issues/9#issuecomment-648745301)
> 
> Other than that you can also use the following workaround [suggested ](https://github.com/corona-warn-app/cwa-app-android/issues/993#issuecomment-671912052) by @kbobrowski for quering your test-results:
> 
> > you can also grab recent APK and sideload it: ~https://www.apkmirror.com/apk/robert-koch-institut/corona-warn-app/corona-warn-app-1-1-1-release/corona-warn-app-1-1-1-android-apk-download/~
> > **Edit**: https://www.apkmirror.com/apk/robert-koch-institut/corona-warn-app/
> > Note that it won't update automatically, and as soon as CWA is released in your Play Store country you should uninstall it and install from Play Store, but for now I guess using it like this is better than not using at all.

Thanks, @daimpi for your response.

As mentioned, there is already a wishlist entry for USA here:
https://github.com/corona-warn-app/cwa-wishlist/issues/41

Best regards,
SG

Corona-Warn-App Open Source Team
