### ISSUE TITLE
Re-open of Android README.md should link to top level of English FAQ #1050

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#1228]
## Where to find the issue
Previous issue https://github.com/corona-warn-app/cwa-app-android/issues/1050 referred to 
https://github.com/corona-warn-app/cwa-app-android/blob/dev/README.md (which no longer exists)
now the default is master not dev, so the reference is to 
https://github.com/corona-warn-app/cwa-app-android/blob/master/README.md instead and where the issue has re-appeared.
Last sentence of first paragraph.

## Describe the issue
"Visit our FAQ page for more information and common issues" links to https://www.coronawarn.app/de/faq/#android_location

Since the README.md contents and project working language is English, the README.md should link to the English language version of the FAQ.
The link should be to the top level of the FAQ, not to the specific issue at anchor #android_location .

## Suggested change
Change the link from https://www.coronawarn.app/de/faq/#android_location to https://www.coronawarn.app/en/faq/

## Additional comments
This issue was supposed to be fixed by https://github.com/corona-warn-app/cwa-app-android/pull/1049 
It seems something went wrong or got lost as dev changed to master.

---
Internal Tracking ID: EXPOSUREAPP-2894

**Comment by svengabr** [comment]
Hey @MikeMcC399,

I am sorry to hear that the previous change didn't make it to production.

I have created a new Jira Ticket EXPOSUREAPP-2894

Best regards,
SG

Corona-Warn-App Open Source Team
