### ISSUE TITLE
GeneralSecurityException

### ISSUE THREAD

**Issue by HuiiBuh** [corona-warn-app/cwa-app-android#1239]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Describe the bug

Exception happens every time I try to open the app. 
Stacktrace: https://del.dog/finemunupp

## Expected behaviour

I can open the app. 

## Steps to reproduce the issue

? 

## Technical details

- Mobile device: Poco F1 with custom rom
- Android version: 10
- App version: 1.3.1

## Possible Fix

Clearing the storage of the app resolved the issue, but all the exposure data is lost afterwards.

**Comment by daimpi** [comment]
Are you experiencing this problem https://github.com/corona-warn-app/cwa-app-android/issues/1121?

It looks like a solution is coming with CWA 1.4: https://github.com/corona-warn-app/cwa-app-android/pull/1235 🙂.

**Comment by heinezen** [comment]
Hey @HuiiBuh,

Thanks for reporting. Your stack trace looks almost identical to the one posted in #1121, so you are probably experiencing the same issue. You can continue the discussion there oor subscribe to the issue foor updates on the fix. I will close this issue as a duplicate.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
Duplicate of #1121
