### ISSUE TITLE
Google and Apple APIs

### ISSUE THREAD

**Issue by white204** [corona-warn-app/cwa-app-android#124]
_"I think the most important feature for such an app is, to make it available to the biggest user spectrum possible. But when using Google APIs this target can't be reached."_

I agree to this.
Are the developers aware what google and/or apple are doing in their code?
The use of closed source apis does not exactly contribute to trust in the cwa-app. But this is important if millions of people are to use it.

**Comment by white204** [comment]
@Administrator: Sorry - I wanted to comment a post but obviously made a mistake. Please delete this issue for me.
Thank you.

**Comment by tkowark** [comment]
No worries. As per your request, I'll delete this issue, now.
