### ISSUE TITLE
App not compatible with my Xioami device (Android 10)

### ISSUE THREAD

**Issue by ALEXdotAfrica** [corona-warn-app/cwa-app-android#1261]
The app is incompatible with my device. A Xioami 9C running Android 10 and I am unable to download it

I am above the minimum requirements (Android 6.0) and have no problems running any other Google Play store apps on my phone. I can run the South African contact tracing app. I don’t see any reason why CoronWarn should not run on my phone.

I think the app should cover as many phones as possible (e.g. all phones above Android 6.0 in order to be effective). There are plenty of Xiaomi phones in Germany.

I should like to request that the app is updated.

**Comment by thomasaugsten** [comment]
Can you provide a screenshot of the error?

**Comment by ALEXdotAfrica** [comment]
Not much of an error as being denied the ability to download it. I am not even given the chance to generate an error. Attached.
![PastedGraphic-1](https://user-images.githubusercontent.com/33809592/94652932-0e022300-02fb-11eb-9310-456eecadbf5c.png)

**Comment by ALEXdotAfrica** [comment]
Sorry about the bad resolution on that one 
![image](https://user-images.githubusercontent.com/33809592/94653090-4e61a100-02fb-11eb-9569-8edfcade6c56.png)
![image](https://user-images.githubusercontent.com/33809592/94653125-5cafbd00-02fb-11eb-861a-9685017945b1.png)

The screenshots are from Firefox. I had to open the play store in the browser (logged into my Google account) to find the app because I cannot find it on the Play Store on my phone (presumably because my device is flagged as "incompatible".

**Comment by ALEXdotAfrica** [comment]
I should like to add that I do have the Google Play Services update installed, and that the South African COVID Alert SA app which also runs on GAEN, and has the same system requirements of Corona-Warn-App works perfectly.

**Comment by Nokius** [comment]
@ALEXdotAfrica I assume you use a ZA GooglePlay account, from information I have the Application is only available in a few Countries. May you are geoblocked :( Can you try to download it with [AuroaStore](https://auroraoss.com/) for example it's a wrapper of the PlayStore

**Comment by vaubaehn** [comment]
Hi @ALEXdotAfrica and @Nokius ,
I just commented here => https://github.com/corona-warn-app/cwa-app-android/issues/510#issuecomment-701231812

Can this issue here be closed?

**Comment by thomasaugsten** [comment]
Can you please retest with a german play store account and your phone?

**Comment by ALEXdotAfrica** [comment]
I do have a ZA Google Play account in response to @Nokius, I was advised in #510 to download from APK Mirror. https://www.apkmirror.com/apk/robert-koch-institut/corona-warn-app/. The app seems to be working. I am prompted that I have to turn off the exposure logging notifications on the SA app to use the App, I can only use one at a time. So the app seems to work sideloaded, I will turn off exposure logging/notifications for the app until I am in Germany, so I can use the app in South Africa until I arrive in Germany

**Comment by ALEXdotAfrica** [comment]
@thomasaugsten I have sideloaded the APK, I do not wish to change the play store, that is not advised till I change countries. Also I need to use the SA app until departure.

**Comment by ALEXdotAfrica** [comment]
> Hi @ALEXdotAfrica and @Nokius ,
> I just commented here => [#510 (comment)](https://github.com/corona-warn-app/cwa-app-android/issues/510#issuecomment-701231812)
> 
> Can this issue here be closed?

Yes the issue can be closed.

**Comment by vaubaehn** [comment]
@ALEXdotAfrica thanks for your information, happy to hear it works.
Just one thing: Please have an eye on updates of Corona-Warn-App. For Android, some users still experience severe issues from time to time. Most likely almost all may be solved in version 1.4.0 that could be released next week or somewhat later.

**Comment by daimpi** [comment]
@AlexanderAlferov 
> Yes the issue can be closed.

As the author you can even close this issue yourself 😉.
 
Additionally: you could create an entry for South Africa support in the wishlist repo as suggested here: https://github.com/corona-warn-app/cwa-backlog/issues/9#issuecomment-648745301 (afaik none exists so far).

**Comment by heinezen** [comment]
Hey @ALEXdotAfrica ,

Since your problem seems to be solved, I'll close this issue. If you have further remarks, just comment here and we will reopen the issue again. Also, you can create a request for South Africa to be added to the supported countries in the [wishlist repository](https://github.com/corona-warn-app/cwa-wishlist/issues) as @daimpi suggested.

CH

----
Corona-Warn-App Open Source Team
