### ISSUE TITLE
Risk Encounter Count

### ISSUE THREAD

**Issue by Tradeturner** [corona-warn-app/cwa-app-android#1342]
Hi, two days ago my app showed "Bisher keine Risiko-Begegnung". Yesterday it showed "1 Risiko-Begegnung", today it dropped back to "Bisher keine Risikobegegnung". How is that possible?
Thanks!

**Comment by Tho-Mat** [comment]
06.10.2020 was the first time you download the 2020-10-05.zip file. this was published at 06.10.2020 2:05 German time.
In this file you get all the keys uses have uploaded on 05.10.2020.
If a user uploads his keys, he uploads key for up to 14 day.
The 2020-10-05.zip file contains keys for 4.10.2020-22.09.2020
If you meet one infected person on 22.09 you would see "1 Risiko-Begegnung".
Today the keys for the 22.09. are to old. So you will see 'Bisher keine Risikobegegnung"

**Comment by Ein-Tim** [comment]
This Issue is also tracked here:

https://github.com/corona-warn-app/cwa-documentation/issues/430

**Comment by heinezen** [comment]
Hey @Tradeturner,

To help you with your issue we need more information about your device and app version. This would help us categorize your issue and determine if it is a bug. For example, you could provide:

* Device name
* Android version
* App version
* ENF version
* ENF Logfiles

You can also check if the issue description https://github.com/corona-warn-app/cwa-documentation/issues/430 that @Ein-Tim linked matches with the behaviour you experienced.

Best Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by Tho-Mat** [comment]
If i understand @Tradeturner right, he talks about the possibility.
In https://github.com/corona-warn-app/cwa-documentation/issues/430 
we talk about the text and the correct text should be "no risk in the last 14 days" or so

**Comment by Optiligence** [comment]
I also experienced this for the second time today. 

Before the update to v1.5 i had 2 low risk encounters. 
After i got the update on the 22nd i had 1 low risk encounter. 
From the 23rd to the 27th 0. 
On the 28th 1 new and today again 0. 

It’s hard for me to believe that they drop immediately the next day several times like this. 
[all-exposure-checks.json (6).txt](https://github.com/corona-warn-app/cwa-app-android/files/5456021/all-exposure-checks.json.6.txt)

**Comment by Optiligence** [comment]
created a new issue for this since it’s about v1.5 in particular

**Comment by dsarkar** [comment]
@Tradeturner, do you have any updates on your reported issue, i.e. did it occur more than once and also the information @heinezen requested. Also, for the records, a similar issue was reported here [iOS] https://github.com/corona-warn-app/cwa-app-ios/issues/1525.

Best wishes, 
DS

---
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
Due to missing feedback, we will close this issue.

----
Corona-Warn-App Open Source Team
