### ISSUE TITLE
URSACHE: 3 error message when switching to secondary user

### ISSUE THREAD

**Issue by LukBukkit** [corona-warn-app/cwa-app-android#1346]
## Avoid duplicates
* [X] This enhancement request has not already been raised before
* [X] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [X] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation
Hello,

if you create a new secondary user on an Android device, this user is unable to use this app. But it's not clear for the secondary user, why the app won't work. There's just an (maybe confusing) error message. 

When I expericended this problem this first time on my Nexus 5X my thought was, that the app just doesn't support this device. Only by googling and having a little bit luck, I came accros issue [#733](https://github.com/corona-warn-app/cwa-app-android/issues/733#issuecomment-650734982). This issue was also reproducible on my OnePlus 5T.

Secondary User: https://streamable.com/awm7zh
Primary User: https://streamable.com/ivdsel

See: https://source.android.com/devices/tech/admin/multi-user?hl=en

## Suggested Enhancement
It would nice if you could check, which type of user (primary or secondary) runs the app and warn secondary users, that the app might not work and they have to use an primary user account.

## Expected Benefits
This enhancement could prevent confusion for some people who are using secondary user accounts on their Android phones. My guess is, that the normal user won't be able to find the GitHub issue, I mentioned above, and will just uninstall the app.
     

---
Internal Tracking ID: EXPOSUREAPP-3149

**Comment by heinezen** [comment]
Hey @LukBukkit ,

Thanks for the feedback. I've relabelled your issue to `bug` because the behaviour you describe should probably not happen. We have added your issue to the internal Jira with ticket ID EXPOSUREAPP-3149. The developers will now look at your issue and decide how to address it. If there are any updates on the status, it will be posted here on Github.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by sancho1241** [comment]
Hi, almost a year hast passed and  the issue still persists for secondary users. In my case my son is secondary user on his device and I'm the admin. I trink this a common setup with kids which should work. Is there any chance to get this fixed soon?
Rgds,
Sancho

**Comment by svengabr** [comment]
I have just checked the linked Jira issue.

Jira Ticket is flagged as:
Resolution: `Wont Fix`
Status: `Obsolete`

Unfortunately, no additional information was added to this Jira ticket.
