### ISSUE TITLE
Device crashs and restarts after installing and setting up CWA

### ISSUE THREAD

**Issue by ucmichan** [corona-warn-app/cwa-app-android#1354]
Hi, an issue was reported in the Play Store with the following device:
Cat S41, Android 8

The user wrote:

> After the installation and initial setup + activation of Bluetooth everything is ok. Then when working on the smartphone a sudden crash and the device restarts completely. The whole thing is repeated several times. I didn't see any connection with a specific app or function. There was no error message. After uninstalling the Corona app, the spook was over immediately.

This is the only reviewer with this device who reported a problem like this. Let me know if I should ask the user for more details.

Steps to reproduce:

1. Download CWA
2. Open the App
3. Finish the initial setup for the app
4. Close the CWA
5. Use your phone as usual

Expected Result
App works correct in the background and the device is working as usual.

Actual Result
Device crashs and restarts automatically.

**Comment by heinezen** [comment]
Hey @ucmichan,

The Play Store and AppStore are also monitored by the Community Management Team, so mirroring the issues of other users to here is not necessary. You can still report it here if you experience the issue yourself, of course, but if that is not the case it's better to let the Store community managers handle this.

I'll close this issue for now. If you have any questions regarding this, you can still ask them here.

Regards,
CH

----
Corona-Warn-App Open Source Team
