### ISSUE TITLE
Total number of encounter changed during the same day

### ISSUE THREAD

**Issue by francescacoo** [corona-warn-app/cwa-app-android#1358]
Yesterday as I opened the app, refresh around 2AM I had a total of 3 low risk encounters.
Today I opened the app in the morning, refresh still around 2AM I still had 3 low risk encounters.
I opened the app still few times, same result, but at 15.45 (no refresh of data), the encounters became 2 low risk.

In the google database I can still see 3 exposures (same day, same hash key).

I would have expected to see the number changing only once daily.

Does it mean that I met one person 14 days ago (not sure if the 23d or 24th of September) and one exposure disappeared?
Is the update happening several times during the day and only the keys are updating once a day?
Why it didn't disappear this morning though but only later in the afternoon?
I believe the time of the encounter is not taken in consideration for privacy reasons.

I can share the exposure log if needed.

----

**Device name**
RedMi note 8t

**Android version**
9PKQ1.190616.001

**App version**
1.3.1

**ENF version**
17203704005

**The ENF logfiles you mentioned**

[all-exposure-checks-8-10-15-50.txt](https://github.com/corona-warn-app/cwa-app-android/files/5350498/all-exposure-checks-8-10-15-50.txt)
[all-exposure-checks-8-10-8-30.txt](https://github.com/corona-warn-app/cwa-app-android/files/5350499/all-exposure-checks-8-10-8-30.txt)
[all-exposure-checks-7-10-8-30.txt](https://github.com/corona-warn-app/cwa-app-android/files/5350500/all-exposure-checks-7-10-8-30.txt)

---
Internal Tracking ID: EXPOSUREAPP-3171

**Comment by heinezen** [comment]
Hey @francescacoo ,

From what you describe your issue looks similar to https://github.com/corona-warn-app/cwa-documentation/issues/430. Do you think the behaviour described there matches with your experience?

Suggestions for improving the status message have already been suggested in the linked issue. If you think your issue is the same and you want to give further feedback, you can also make a comment there.

Best Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by francescacoo** [comment]
no it's a bit different.

7.10.2020 updated the app at 2.22 it showed 3 low risk encounters and it stayed at 3 the whole day
8.10.2020 updated the app at 2.52 it showed 3 low risk encounters in the morning until 15.50 when I opened the app again and it showed 2 low risk encounters.

What I am questioning is why if the app was updated at 2.52 on 8.10.2020 the risk encounters changed from 3 to 2 only in the afternoon and not in the morning?

The log from this morning and this afternoon are the same, the hash key with 3 encounter is the same.

(I export the logs every morning when I have encounters)

**Comment by heinezen** [comment]
Hmm, just to be sure, can you provide the following information:

* Device name
* Android version
* App version
* ENF version
* The ENF logfiles you mentioned

I also found ths thread: https://github.com/corona-warn-app/cwa-app-android/issues/1302 which might answer your question. If not, I'll create an internal bug report with the information you provided and forward it to one of the developers.

CH

----
Corona-Warn-App Open Source Team

**Comment by francescacoo** [comment]
I am not sure in the previous ticket if "later day" means the same day or the day after.
From my understanding the app should be updated only once a day correct?

**Device name**
RedMi note 8t

**Android version**
9PKQ1.190616.001

****App version**
1.3.1




**ENF version**
17203704005

**The ENF logfiles you mentioned****

[all-exposure-checks-8-10-15-50.txt](https://github.com/corona-warn-app/cwa-app-android/files/5350498/all-exposure-checks-8-10-15-50.txt)
[all-exposure-checks-8-10-8-30.txt](https://github.com/corona-warn-app/cwa-app-android/files/5350499/all-exposure-checks-8-10-8-30.txt)
[all-exposure-checks-7-10-8-30.txt](https://github.com/corona-warn-app/cwa-app-android/files/5350500/all-exposure-checks-7-10-8-30.txt)

**Comment by heinezen** [comment]
@francescacoo Yes, it is currently updated once every 24 hours.

----
Corona-Warn-App Open Source Team

**Comment by francescacoo** [comment]
ok so it is definitely weird that my screen changed from 3 this morning to 2 this afternoon.
I only have the screenshot from yesterday and this afternoon sadly but you can see that it shows 2 while the last export it didn't change at all and still has 3 encounters.

![Screenshot_2020-10-08-15-55-25-779_de rki coronawarnapp](https://user-images.githubusercontent.com/1751355/95500919-db65c380-09a7-11eb-9633-51bf494f3063.jpg)

**Comment by francescacoo** [comment]
and the links you provided are useful but I believe different.
It is normal that on a different day the total encounter would change as soon as the 14 days have passed.
I didn't think it should change in the same day.

**Comment by francescacoo** [comment]
And this morning with the last update the risk encounters are 2 both in the log and in the CWA app.

So the CWA app "knew it" before and it had been updated twice during the same day is my guess?
Now I am not sure if the encounter happened the 23d or 24th

**Comment by francescacoo** [comment]
it might be similar to https://github.com/corona-warn-app/cwa-app-android/issues/1210

**Comment by francescacoo** [comment]
[all-exposure-checks-9-10-17-00.txt](https://github.com/corona-warn-app/cwa-app-android/files/5355810/all-exposure-checks-9-10-17-00.txt)
 The log from this afternoon if it helps

**Comment by daimpi** [comment]
@francescacoo This is very weird indeed and as you rightly pointed out above, likely related to #1210.

One thing I've found is that there is something curious happening when you compare the log files for the timeframe when the encounter count in CWA went from 3 to 2 on Sept 8th i.e. `8-10-8-30` vs. `8-10-15-50`:
The log file `8-10-8-30` contains 237 entries and the oldest set of checks in this log are those performed on 22.09.2020,  07:12 (14 checks). Curiously those are not anymore present in the `8-10-15-50` log which only contains 223 checks. 

That the content of the EN log changes in the middle of the day without any new checks being performed strikes me as unusual and we don't see this kind of behavior if we compare your logs from today with each other (`9-10-17-00` vs. `9-10-8-30`): here the number of checks and the content of the log didn't change during the day. 

But even so: my understanding so far was that this specific change in EN log content (dropping some old checks) should have zero impact on the number of encounters shown in CWA, but tbh I'm not familiar enough with how exactly this "number of encounters" display in CWA is updated. It would be great if maybe someone who knows more about this (@thomasaugsten @d4rken maybe? 🙂) could provide some insight into this. 

I know this is probably not the highest priority item, but maybe it's something which turns out to be indicative of a deeper bug/problem…

**Comment by heinezen** [comment]
@francescacoo I've now created a Jira ticket for the dev team (ticket ID: EXPOSUREAPP-3171). Whatever the problem may be, it will now be investigated. We will report back here if we find a solution or have any updates on the issue.

CH

----
Corona-Warn-App Open Source Team

**Comment by janzieg** [comment]
I can also reproduce this issue every day.

Example from today "15.11.2020":

Screenshot after opening the app in the morning (shows "17"):
![Screenshot_20201115-081829](https://user-images.githubusercontent.com/32765394/99196402-782c3580-278c-11eb-8332-cbd6c8137f70.png)

Screenshot after opening the app in the afternoon (switched to "14"):
![Screenshot_20201115-154625](https://user-images.githubusercontent.com/32765394/99196403-78c4cc00-278c-11eb-81f1-3e14751433ab.png)

The log shows "17" (the value that was shown in the morning) for "15.11.2020":
[all-exposure-checks_20201115.txt](https://github.com/corona-warn-app/cwa-app-android/files/5543090/all-exposure-checks_20201115.txt)

What I realized is that I expect the log to show "14" (the switched value) for tomorrow (the "16.11.2020") as the changed-over-day result always seems  to "predict" the next days latest log entry.

Maybe that helps...

**Comment by thomasaugsten** [comment]
@janzieg Can you please check tomorrow and also open the app often to see if the numbers still is changing.

**Comment by janzieg** [comment]
@thomasaugsten I will report tomorrow. I realized this behavior (changing value over day and "predicting") since 2 weeks or so.

**Comment by janzieg** [comment]
@thomasaugsten 
It didn´t happen today! Also it didn´t show "14" as I expected yesterday - todays screenshot fits to the latest log entry:
![Screenshot_20201116-180512](https://user-images.githubusercontent.com/32765394/99284424-8898ea80-2836-11eb-8af7-8d1322f44ce2.png)
[all-exposure-checks_20201116.txt](https://github.com/corona-warn-app/cwa-app-android/files/5548521/all-exposure-checks_20201116.txt)

I´m going to double check tomorrow again...

**Comment by janzieg** [comment]
Hi @thomasaugsten,

The problem didn´t show up the last days, but today again.
In the morning the app screen (no screenshot this time) showed "7" which fits to the log.
[all-exposure-checks_20201122.txt](https://github.com/corona-warn-app/cwa-app-android/files/5579314/all-exposure-checks_20201122.txt)

Few moments later the screen switched to "6":
![Screenshot_20201122-112844](https://user-images.githubusercontent.com/32765394/99901442-0d608a00-2cb7-11eb-8e4b-0407da69f308.png)

**Comment by heinezen** [comment]
The app switched to Exposure Window mode with release 1.9 where this behaviour should not happen anymore. Please make a comment if the ssame error still persits.

----
Corona-Warn-App Open Source Team
