### ISSUE TITLE
Device crashes and restarts after installion and setup of CWA

### ISSUE THREAD

**Issue by heinezen** [corona-warn-app/cwa-app-android#1360]
***This bug was mirrored from feedback in the Play Store, so it can be discussed by the Github community.***

## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Describe the bug

From user feedback:

> After the installation and initial setup + activation of Bluetooth everything is ok. Then when working on the smartphone a sudden crash and the device restarts completely. The whole thing is repeated several times. I didn't see any connection with a specific app or function. There was no error message. After uninstalling the Corona app, the spook was over immediately.

## Expected behaviour

The app or its background updates should not crash the device. App works correct in the background and the device is working as usual.

## Steps to reproduce the issue

1. Download CWA
2. Open the App
3. Finish the initial setup for the app
4. Close the CWA
5. Use your phone as usual
6. Device crashes

## Technical details

- Mobile device: Cat S 41
- Android version: Android 8

**Comment by MikeMcC399** [comment]
The Android operating system is designed to prevents apps interfering with other apps or with the operating system itself. The problem with the device crashing is likely to be a hardware problem.

Google publishes [advice to Fix an Android device that's restarting or crashing](https://support.google.com/android/answer/7664448?hl=en) including checking for an operating system update and ensuring the device has sufficient memory.

The [Cat S41 device manufacturer's support site](https://www.catphones.com/de-de/help-support/s41-support/) publishes a telephone number +49 234 978 49027 and e-mail address support@catphones.com for device support.

**Comment by MikeMcC399** [comment]
There hasn't been any activity on this issue for several months. Can it be closed?

BTW: There is a typo in the title "Device crashes and restarts after installion and setup of CWA"

"installion" should be "installation"

**Comment by dsarkar** [comment]
@heinezen @MikeMcC399 This issue can be closed. Since 1.15 Android crashes went significantly down.
