### ISSUE TITLE
App crashes on startup

### ISSUE THREAD

**Issue by SolidTux** [corona-warn-app/cwa-app-android#1365]
App crashes on startup. Phone: Redmi 9, rooted

Logs are attached.

[logcat_10-09-2020_09-59-04.txt](https://github.com/corona-warn-app/cwa-app-android/files/5353389/logcat_10-09-2020_09-59-04.txt)

**Comment by daimpi** [comment]
Similar to https://github.com/corona-warn-app/cwa-app-android/issues/1121, https://github.com/corona-warn-app/cwa-app-android/issues/1053. 

You could maybe try following [those instructions](https://github.com/corona-warn-app/cwa-app-android/issues/1053#issuecomment-690615473) to see whether this fixes the issue for you.

**Comment by heinezen** [comment]
Hey @SolidTux ,

Can you give us more information about the behaviour of the bug? The steps to reproduce the bug would be especially helpful. You can also answer these question if you are unsure how to describe it:

* Did the app work before the crash (or was it a fresh install)?
* Does the app display an error message before or while it crashes?
* Does the app window show at all or does it crash before showing anything from the app?

Additionally, can you please provide this information about your phone:

* Android version
* CWA App version
* ENF version
* ENF logfiles

This will help us to better determine the cause of the bug.

Thanks,
CH

----
Corona-Warn-App Open Source Team

**Comment by SolidTux** [comment]
> Similar to #1121, #1053.
> 
> You could maybe try following [those instructions](https://github.com/corona-warn-app/cwa-app-android/issues/1053#issuecomment-690615473) to see whether this fixes the issue for you.

Yes, that fixed the issue. Sorry for the duplicate!
