### ISSUE TITLE
Ursache 3: Etwas ist schief gelaufen / Samsung S10

### ISSUE THREAD

**Issue by Nuel1981** [corona-warn-app/cwa-app-android#1413]
**CW APP 1.3.1
Android Version 10
Samsung S10 /  SM-G973F**
![Screenshot_20201015-172819_Corona-Warn](https://user-images.githubusercontent.com/72933563/96151641-f090a400-0f0b-11eb-9377-3324cfa49a80.jpg)

![Screenshot_20201015-173139_Settings](https://user-images.githubusercontent.com/72933563/96152024-5aa94900-0f0c-11eb-9c5b-c9445bb26878.jpg)

**Der Fehler tritt seit über 24 Stunden auf, es werden keine Warnungen/Kontakte mehr  aktualisiert.**

**Comment by daimpi** [comment]
Duplicate of #1021

**Comment by abro1i** [comment]
Hi @Nuel1981,

thanks for your feedback. This issue is already under discussion here: #1021 

Best regards, 

ABB 

Corona-Warn-App Open Source Team

**Comment by abro1i** [comment]
Duplicate of #1021
