### ISSUE TITLE
Ursache 3: Etwas ist schief gelaufen 

### ISSUE THREAD

**Issue by Teddy265** [corona-warn-app/cwa-app-android#1414]
Hallo CWA-Team,
Gerätename = SAMSUNG Galaxy J5
CWA-Version = 1.3.1
Android-Version = 6.0.1
Trotz aller empfohlenen Einstellungen seit dem 1. Oktober keine Aktualisierung mehr!

**Comment by daimpi** [comment]
Sieht die Fehlermeldung etwa so aus?

<img src="https://user-images.githubusercontent.com/22129968/96158596-f7bbb000-0f13-11eb-9cc8-ff3f42bfbc0f.png" width="300">

**Comment by abro1i** [comment]
Hi @Teddy265,

thanks for your feedback. This issue is already under discussion here: #1021 

Best regards, 

ABB 

Corona-Warn-App Open Source Team

**Comment by abro1i** [comment]
Duplicate of #1021
