### ISSUE TITLE
(39508)

### ISSUE THREAD

**Issue by redmiii** [corona-warn-app/cwa-app-android#1416]
Corona-Warn-App (Version 1.3.1) läuft angeblich fehlerfrei. 
Risikostatus kann nicht aktualisiert werden. Risikoermittlung ist aber weiterhin aktiv. 

- Mobile device: Xiaomi Redmi 4a
- Android version: 6.0.1 MMB29M

**Comment by MikeMcC399** [comment]
Hallo @redmiii 

vermutlich hast Du folgende Fehlermeldung bekommen:
<string name="errors_google_api_error">"Ihre Corona-Warn-App läuft fehlerfrei. Leider können Sie Ihren Risikostatus im Moment nicht aktualisieren. Ihre Risiko-Ermittlung ist weiterhin aktiv und funktioniert. Weitere Informationen finden Sie in unseren FAQ: https://www.coronawarn.app/de/faq/"</string>

Mit dem Fehler 39508 bist Du nicht alleine. Viele andere Benutzer haben das Problem auch gehabt und es gibt deshalb einen Eintrag in den [FAQs](https://www.coronawarn.app/de/faq/) unter [[Google/Android]: Fehler bei Kommunikation mit Google API (39508)](https://www.coronawarn.app/de/faq/#API39508).

Die derzeit empfohlene Umgehung ist wie folgt:
- abends RISIKO-ERMITTLUNG AKTIV auf GESTOPPT stellen
- Handy am eingeschaltetem Ladegerät hängen lassen
- morgens RISIKO-ERMITTLUNG EINSCHALTEN durchführen

Manch andere Benutzer haben berichtet, dass das funktioniert: es gibt allerdings keine Garantie dafür!

Unter https://github.com/corona-warn-app/cwa-app-android/issues/1021 in Github ["CAUSE: 3 Something went wrong. ApiException: 39508"](https://github.com/corona-warn-app/cwa-app-android/issues/1021) findest Du die zentrale Stellung, wo der Status dieses Problems diskutiert und festgehalten wird.

**Comment by MikeMcC399** [comment]
Duplikat zu #1021

**Comment by abro1i** [comment]
Hi @redmiii,

thanks for your feedback. 

This issue is already known here #1021. Lets continue the discussion there to keep it in one place.

Best regards,

ABB

Corona-Warn-App Open Source Team

**Comment by abro1i** [comment]
Duplicate of #1021
