### ISSUE TITLE
CAUSE: 3 Something went wrong. ApiException: 39508

### ISSUE THREAD

**Issue by gaziwo** [corona-warn-app/cwa-app-android#1422]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Mobile device:
- Android version:

**Comment by gaziwo** [comment]
mobile device: SM-G800F
Android version: 6.0.1
Corona App: 1.3.1
last update risk status : Oct. 10th

happend several times before, but with the current release, the bug was gone. Now it is back again.

**Comment by heinezen** [comment]
Duplicate of #1021
