### ISSUE TITLE
Meine App zeigt weniger Risikobegegnungen an, als die meiner Partnerin

### ISSUE THREAD

**Issue by AllesMeins** [corona-warn-app/cwa-app-android#1424]
Generell vorneweg: Gibt es für mich eine Möglichkeit zu überprüfen, ob mein Telefon wirklich Kontakte aufzeichnet bzw. wieviele Kontakte ca. erfasst wurden?

Der Grund für diese Frage: In den letzten Monaten hat die App meiner Freundin bereits dreimal eine "Begegnung mit geringem Risiko" angezeigt, meine App bleibt dagegen seit Anbegin bei "keine Risikobegegnungen". Wir sind meistens gemeinsam unterwegs, weshalb ich erwarten würde dass wir auch die Risikobegegnungen teilen. Eine Risikobegegnung war sogar höcht wahrscheinlich während eines gemeinsamen 14-tägigen Urlaubs bei dem wir definitiv alles gemeinsam gemacht haben.

Darum die Frage: Kann hier ein Problem vorliegen? Kann ich irgendwie selber sicherstellen, dass wirklich Kontakte erfasst werden?

Ich nutze ein Sony Xperia XZ1Compact, die Freundin ein Samsung Galaxy S10 - beide jeweils mit aktuellen Updates.

**Comment by daimpi** [comment]
Hi @AllesMeins,
> Generell vorneweg: Gibt es für mich eine Möglichkeit zu überprüfen, ob mein Telefon wirklich Kontakte aufzeichnet […]
> […]Kann ich irgendwie selber sicherstellen, dass wirklich Kontakte erfasst werden?

Sofern dein Gerät nicht gerootet ist: Leider nein. Einen entsprechenden feature request findest du [hier](https://github.com/corona-warn-app/cwa-wishlist/issues/5).

> […] bzw. wieviele Kontakte ca. erfasst wurden?

Nein das ist nicht möglich. Die App kann rein technisch nicht wissen wie viele Begegnungen du gehabt hast (das ist aus Datenschutzgründen so entworfen worden): https://github.com/corona-warn-app/cwa-wishlist/issues/124#issuecomment-660121125

> Der Grund für diese Frage: In den letzten Monaten hat die App meiner Freundin bereits dreimal eine "Begegnung mit geringem Risiko" angezeigt, meine App bleibt dagegen seit Anbegin bei "keine Risikobegegnungen". Wir sind meistens gemeinsam unterwegs, weshalb ich erwarten würde dass wir auch die Risikobegegnungen teilen. Eine Risikobegegnung war sogar höcht wahrscheinlich während eines gemeinsamen 14-tägigen Urlaubs bei dem wir definitiv alles gemeinsam gemacht haben.

Der Schlüsselaustausch findet über Bluetooth low energy (BLE) statt. Die Signalstärke kann durch viele Faktoren beeinflusst werden: Distanz zum Sender, Orientierung der Antennen zueinander, Objekte im Funkweg etc. Es kann z.B. sein, dass ihr einer Familie kurz begegnet seid und das Gerät deiner Freundin gerade noch das Signal verwerten konnte,  während es für dein Gerät bereits zu schwach war. Es gibt aber auch noch eine Menge anderer Möglichkeiten wie das passiert sein könnte (z.B. unterschiedlich Zeitpunkte der [listening windows](https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#limitations)).

Das im Nachhinein zu rekonstruieren dürfte nahezu unmöglich sein. Aber die gute Nachricht ist, dass die Antwort auf die Frage ob hier ein Problem vorliegt, lautet: "Völlig ausschließen kann man das leider nicht, aber wahrscheinlich gibt es kein Problem".

Eine Möglichkeit in Zukunft mehr Infos angezeigt zu bekommen ist die Verwendung der corona-warn-companion App (funktioniert auch ohne root im RamBle mode): https://github.com/mh-/corona-warn-companion-android 🙂.

**Comment by svengabr** [comment]
@daimpi thank you very much for your answer here!

@AllesMeins are there still open questions from your side? Otherwise, I would mark this question as resolved.

Best regards,
SG

Corona-Warn-App Open Source Team

**Comment by AllesMeins** [comment]
Yes, thank you! I've got all the Info I need and strongly support the linked feature request. Because I'm probably not the only one wondering if the app works as intended and having to blindly trust is somewhat unsatisfactory.
