### ISSUE TITLE
Fehler 39508

### ISSUE THREAD

**Issue by Stefan2020G** [corona-warn-app/cwa-app-android#1426]
Liebe User, ich erhalte seit 2 Wochen die Fehlermeldung 39508 in der Corona Warn App. Ich habe sowohl im FAQ nachgelesen und auch die auf GitHub geschlossenen Issues (deutsch und englisch) gelesen. Die angegeben Tipps habe ich alle, ohne Erfolg ausprobiert. Kann mir jemand einen Hinweis geben?
Device Name: 358022067193229/01
Android version: 6.0.1
CWA App version: 1.3.1
Danke!

**Comment by heinezen** [comment]
Hey @Stefan2020G ,

There is a workaround in the main issue thread for this bug: https://github.com/corona-warn-app/cwa-app-android/issues/1021#issuecomment-707879303 . Please check if it works for you. The bug will also be fixed in the next release which will be available soon. I will close this thread as a duplicate of #1021. 

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
Duplicate of #1021

**Comment by Stefan2020G** [comment]
Hallo Christoph, 

 

vielen Dank. Ich habe den Tipp aus #1021 ausprobiert und die Fehlermeldung erhalten, dass die Antwortzeit (1 Minute) überschritten wurde. Jetzt weiß ich wenigstens woran es liegt und warte bis (hoffentlich bald) ein Update kommt.

 

Gruß,

 

Stefan

 

Von: Christoph Heine <notifications@github.com>  
Gesendet: Sonntag, 18. Oktober 2020 19:49
An: corona-warn-app/cwa-app-android <cwa-app-android@noreply.github.com>
Cc: Stefan2020G <familie.giesen@koeln.de>; Mention <mention@noreply.github.com>
Betreff: Re: [corona-warn-app/cwa-app-android] Fehler 39508 (#1426)

 

Hey @Stefan2020G <https://github.com/Stefan2020G>  ,

There is a workaround in the main issue thread for this bug: #1021 (comment) <https://github.com/corona-warn-app/cwa-app-android/issues/1021#issuecomment-707879303>  . Please check if it works for you. The bug will also be fixed in the next release which will be available soon. I will close this thread as a duplicate of #1021 <https://github.com/corona-warn-app/cwa-app-android/issues/1021> .

Regards,
CH

  _____  

Corona-Warn-App Open Source Team
