### ISSUE TITLE
Fehler Ursache 3 trotz Version 1.7  Exposure Notification Framework

### ISSUE THREAD

**Issue by tandreb** [corona-warn-app/cwa-app-android#1434]
## Describe the bug
Fehler Ursache 3 bei Aktivierung

## Steps to reproduce the issue
Starte App
Risiko-Ermittlung aktivieren

## Technical details
Phone: Honor 10
App Version 1.5.0
EMUI: 10.0.0.177
Android version: 10
Exposure Notification Framework: 17203704005

**Comment by MikeMcC399** [comment]
@tandreb 
Das klingt nach der Fehlermeldung 39508, die in https://github.com/corona-warn-app/cwa-app-android/issues/1021 behandelt wird. Stimmt das?

War vorher die app Version 1.3.1 installiert? Wenn ja, einfach bis nach 00:00 UTC (02:00 MESZ) warten und z.B. morgen früh die App wieder aufrufen. Höchstwahrscheinlich ist das Problem dann weg. 

Eine ausführlichere Erklärung dazu (falls das alles zutrifft) steht in https://github.com/corona-warn-app/cwa-app-android/issues/1021#issuecomment-712099886.

**Comment by tandreb** [comment]
Danke für den Hinweis auf Habe jetzt ebenfalls die Uhrzeit mal kurz umgestellt wie in https://github.com/corona-warn-app/cwa-app-android/issues/1021
https://github.com/corona-warn-app/cwa-app-android/issues/1021#issuecomment-674059696 erwähnt, jetzt geht es wieder.

**Comment by daimpi** [comment]
@tandreb 
> Habe jetzt ebenfalls die Uhrzeit mal kurz umgestellt wie in
#1021 (comment) erwähnt, jetzt geht es wieder.

Achte nur darauf, dass du die Uhrzeit möglichst bald wieder richtig einstellst, denn wenn die Uhrzeit auf deinem Gerät um mehr als 2h von der korrekten Uhrzeit abweicht, sendet und empfängt deine App unbrauchbare keys: https://github.com/corona-warn-app/cwa-app-ios/issues/1097
