### ISSUE TITLE
Show more detailed data provided by the API through DailySummary / ExposureInformation

### ISSUE THREAD

**Issue by jrudolph** [corona-warn-app/cwa-app-android#1438]
It seems at least since [v1.6](https://developers.google.com/android/exposure-notifications/release-notes) of ENF, the API allows some insights at which days risky encounters took place. It would help a lot for transparency if this data was surfaced in the App.

This is basically a follow-up to #584 which was closed as "is not available in the API" but it seems by now more information actually should be available.

**Comment by daimpi** [comment]
@jrudolph do you have something like https://github.com/corona-warn-app/cwa-wishlist/issues/205 in mind?

If so I would suggest closing this issue and moving the discussion there 🙂. 

Regarding [ENF v.1.5+ and `ExposureWindow` mode](https://github.com/corona-warn-app/cwa-documentation/issues/373): yes I also hope that we see a switch to the new API soon, especially now that Google strongly recommends switching to the new API (CWA is currently still using v1 legacy mode ^^).

Other related issues:
- Show more details on encounters: https://github.com/corona-warn-app/cwa-wishlist/issues/100
- Show day of encounter also for green encounters: https://github.com/corona-warn-app/cwa-wishlist/issues/178

**Comment by jrudolph** [comment]
> @jrudolph do you have something like [corona-warn-app/cwa-wishlist#205](https://github.com/corona-warn-app/cwa-wishlist/issues/205) in mind?
> 
> If so I would suggest closing this issue and moving the discussion there slightly_smiling_face.

Yep, of course, got lost in the CWA project jungle. :)

> Regarding [ENF v.1.5+ and `ExposureWindow` mode](https://github.com/corona-warn-app/cwa-documentation/issues/373): yes I also hope that we see a switch to the new API soon, especially now that Google strongly recommends switching to the new API (CWA is currently still using v1 legacy mode ^^).

:+1:
