### ISSUE TITLE
Ihre Riskio-Ermittlung konnte seit mehr als 24 Stunden nicht aktualisiert werden.

### ISSUE THREAD

**Issue by AHaumer** [corona-warn-app/cwa-app-android#1440]
Android 6.0 auf Acer T04, seit heute CWA 1.5 (heutiges update). Fehler seit 09.10.:
Ihre Riskio-Ermittlungg konnte seit mehr als 24 Stunden nicht aktualisiert werden.
URSACHE: 3 .... #39508 
Sollte laut FAQ behoben sein.
Ich war ein vehementer Befürworter der App - aber langsam geht meine Geduld zu Ende.

**Comment by daimpi** [comment]
@AHaumer 
Das issue wird hier getracked: #1021 

Da das Update erst heute bei dir ankam, hat deine App wahrscheinlich bereits vor dem Update das rate-limit erreicht, daran kann dann auch CWA 1.5 für heute nichts mehr ändern. Das Limit wird aber jeden Tag um 02:00 CEST (00:00 UTC) zurückgesetzt. Ich würde empfehlen einfach bis dahin zu warten und danach nochmal zu schauen ob das Problem verschwunden ist. 

Das issue hier kannst du schließen, die Unterhaltung können wir dann in #1021 fortsetzten 🙂.

**Comment by AHaumer** [comment]
Danke - jetzt funktioniert es wieder! Mir fällt ein Stein vom Herzen, ich setze auf die App.
