### ISSUE TITLE
High Risk, recent encounter not visible in the timestamp logs where app tells 

### ISSUE THREAD

**Issue by Morph-O-Mama** [corona-warn-app/cwa-app-android#1441]
Good evening 

On Saturday (17.10) my app has sent me an alert, whereas I have "Erhöhtes Risiko" due to the proximity of a positive tested person two days ago (15.10) alongside a "Risiko-Begegnungen" count of 12. 

Today it is at five days since last encounter and at a counter of 10 "Risiko-Begegnungen" (see screenshot)
![77045](https://user-images.githubusercontent.com/73195571/96634924-7ac97580-131b-11eb-994f-007becaaf30e.jpg)

The timestamps from the exported JSON shows me matchescount of value 0 all way through the 15th and 16th of October, timestamps for the 14th are not even existing. 

The matchescount value of 12 first appears on Saturday 17th, probably when the alert came through. But it has never been updated before

The only matchescount value of 1 happened to be on October 11th.

[{
        "appName": "Corona-Warn",
        "hash": "Y02bprOCbn0iF2mWuNxB7fHgr7TB3QVMavXuORKgjPw=",
        "keyCount": 16120,
        "matchesCount": 0,
        "timestamp": "20. Oktober 2020, 20:07"
    }, {
        "appName": "Corona-Warn",
        "hash": "O1U95vn3KkRXQNUNAu3gUK8zlSDgXu2\/H9uIqa4ynHI=",
        "keyCount": 21527,
        "matchesCount": 0,
        "timestamp": "20. Oktober 2020, 20:07"
    }, {
        "appName": "Corona-Warn",
        "hash": "VOq6FAOxQ1LW\/qlvvIuMC0MqCyzRAmLMYzJOxWM8yL0=",
        "keyCount": 23618,
        "matchesCount": 0,
        "timestamp": "20. Oktober 2020, 20:07"
    }, {
        "appName": "Corona-Warn",
        "hash": "wwFDWRHe3jEWIhnREZnrIeedXYGqmo6V4cLB6LcrPOA=",
        "keyCount": 26284,
        "matchesCount": 0,
        "timestamp": "20. Oktober 2020, 20:07"
    }, {
        "appName": "Corona-Warn",
        "hash": "FmksVqcKrN8X72caj6d58AoIbGv7R9aGOE+46lxx+4M=",
        "keyCount": 23657,
        "matchesCount": 0,
        "timestamp": "20. Oktober 2020, 20:07"
    }, {
        "appName": "Corona-Warn",
        "hash": "OqxTm1BUzkIuVVkkJQ0s6ei9tDZSSjNmRW7nKa1MUbE=",
        "keyCount": 14649,
        "matchesCount": 0,
        "timestamp": "20. Oktober 2020, 20:07"
    }, {
        "appName": "Corona-Warn",
        "hash": "qBoEuZ\/jjM\/tUO4eljKiHDNQx9+goBrxAT9uR6NtCZE=",
        "keyCount": 18134,
        "matchesCount": 0,
        "timestamp": "20. Oktober 2020, 20:07"
    }, {
        "appName": "Corona-Warn",
        "hash": "61qbbpK1q7PO6ggH\/F3caEx80WrENuDNts7vuaAIIlo=",
        "keyCount": 28218,
        "matchesCount": 0,
        "timestamp": "20. Oktober 2020, 20:07"
    }, {
        "appName": "Corona-Warn",
        "hash": "wnvqLcYE6GlPGoWbAj7A90fhyKkkPxKBImGrk\/8Ap4Y=",
        "keyCount": 34105,
        "matchesCount": 0,
        "timestamp": "20. Oktober 2020, 20:07"
    }, {
        "appName": "Corona-Warn",
        "hash": "JWrd8IJXHSXZ2yRLhd5SCqiCKtEmE96gQz3Hv3NtIz8=",
        "keyCount": 43934,
        **"matchesCount": 10,**
        "timestamp": "20. Oktober 2020, 20:07"
    }, {
        "appName": "Corona-Warn",
        "hash": "IJcGAZfoXfwKtmVoz7s4C5ZR9RO7nQcK0YuYNOcahpM=",
        "keyCount": 41646,
        "matchesCount": 0,
        "timestamp": "20. Oktober 2020, 20:07"
    }, {
        "appName": "Corona-Warn",
        "hash": "JU2g74zppJSAtobW56Jsi5pUcb7ItpT9XPAIZtKerhU=",
        "keyCount": 16674,
        "matchesCount": 0,
        "timestamp": "20. Oktober 2020, 20:07"
    }, {
        "appName": "Corona-Warn",
        "hash": "ZohD6\/+cb2d5fSEJHAJeEX24gxzZAZtm2byC4A8loNA=",
        "keyCount": 4814,
        "matchesCount": 0,
        "timestamp": "20. Oktober 2020, 20:07"
    }, {
        "appName": "Corona-Warn",
        "hash": "2delxM3sUxFV4A+G4LugCj8BYStKzUeeQSeeDpVSzY0=",
        "keyCount": 6386,
        "matchesCount": 0,
        "timestamp": "20. Oktober 2020, 20:07"
    }, {
        "appName": "Corona-Warn",
        "hash": "SdTEZwNHt0UO5ZrALV8cOLaktD8y7Jps+R5uZeMfPZI=",
        "keyCount": 11260,
        "matchesCount": 0,
        "timestamp": "19. Oktober 2020, 09:08"
    }, {
        "appName": "Corona-Warn",
        "hash": "Y02bprOCbn0iF2mWuNxB7fHgr7TB3QVMavXuORKgjPw=",
        "keyCount": 16120,
        "matchesCount": 0,
        "timestamp": "19. Oktober 2020, 09:08"
    }, {
        "appName": "Corona-Warn",
        "hash": "O1U95vn3KkRXQNUNAu3gUK8zlSDgXu2\/H9uIqa4ynHI=",
        "keyCount": 21527,
        "matchesCount": 0,
        "timestamp": "19. Oktober 2020, 09:08"
    }, {
        "appName": "Corona-Warn",
        "hash": "VOq6FAOxQ1LW\/qlvvIuMC0MqCyzRAmLMYzJOxWM8yL0=",
        "keyCount": 23618,
        "matchesCount": 0,
        "timestamp": "19. Oktober 2020, 09:08"
    }, {
        "appName": "Corona-Warn",
        "hash": "wwFDWRHe3jEWIhnREZnrIeedXYGqmo6V4cLB6LcrPOA=",
        "keyCount": 26284,
        "matchesCount": 0,
        "timestamp": "19. Oktober 2020, 09:08"
    }, {
        "appName": "Corona-Warn",
        "hash": "FmksVqcKrN8X72caj6d58AoIbGv7R9aGOE+46lxx+4M=",
        "keyCount": 23657,
        "matchesCount": 0,
        "timestamp": "19. Oktober 2020, 09:08"
    }, {
        "appName": "Corona-Warn",
        "hash": "OqxTm1BUzkIuVVkkJQ0s6ei9tDZSSjNmRW7nKa1MUbE=",
        "keyCount": 14649,
        "matchesCount": 0,
        "timestamp": "19. Oktober 2020, 09:08"
    }, {
        "appName": "Corona-Warn",
        "hash": "qBoEuZ\/jjM\/tUO4eljKiHDNQx9+goBrxAT9uR6NtCZE=",
        "keyCount": 18134,
        "matchesCount": 0,
        "timestamp": "19. Oktober 2020, 09:08"
    }, {
        "appName": "Corona-Warn",
        "hash": "61qbbpK1q7PO6ggH\/F3caEx80WrENuDNts7vuaAIIlo=",
        "keyCount": 28218,
        "matchesCount": 0,
        "timestamp": "19. Oktober 2020, 09:08"
    }, {
        "appName": "Corona-Warn",
        "hash": "wnvqLcYE6GlPGoWbAj7A90fhyKkkPxKBImGrk\/8Ap4Y=",
        "keyCount": 34105,
        "matchesCount": 0,
        "timestamp": "19. Oktober 2020, 09:08"
    }, {
        "appName": "Corona-Warn",
        "hash": "JWrd8IJXHSXZ2yRLhd5SCqiCKtEmE96gQz3Hv3NtIz8=",
        "keyCount": 43934,
        **"matchesCount": 11,**
        "timestamp": "19. Oktober 2020, 09:08"
    }, {
        "appName": "Corona-Warn",
        "hash": "IJcGAZfoXfwKtmVoz7s4C5ZR9RO7nQcK0YuYNOcahpM=",
        "keyCount": 41646,
        "matchesCount": 0,
        "timestamp": "19. Oktober 2020, 09:08"
    }, {
        "appName": "Corona-Warn",
        "hash": "JU2g74zppJSAtobW56Jsi5pUcb7ItpT9XPAIZtKerhU=",
        "keyCount": 16674,
        "matchesCount": 0,
        "timestamp": "19. Oktober 2020, 09:08"
    }, {
        "appName": "Corona-Warn",
        "hash": "ZohD6\/+cb2d5fSEJHAJeEX24gxzZAZtm2byC4A8loNA=",
        "keyCount": 4814,
        "matchesCount": 0,
        "timestamp": "19. Oktober 2020, 09:08"
    }, {
        "appName": "Corona-Warn",
        "hash": "WlPRGOqp9jGP0zru89529scVNEgKzr7Gr77PmWT4KhU=",
        "keyCount": 8845,
        "matchesCount": 0,
        "timestamp": "18. Oktober 2020, 11:17"
    }, {
        "appName": "Corona-Warn",
        "hash": "SdTEZwNHt0UO5ZrALV8cOLaktD8y7Jps+R5uZeMfPZI=",
        "keyCount": 11260,
        "matchesCount": 0,
        "timestamp": "18. Oktober 2020, 11:17"
    }, {
        "appName": "Corona-Warn",
        "hash": "Y02bprOCbn0iF2mWuNxB7fHgr7TB3QVMavXuORKgjPw=",
        "keyCount": 16120,
        "matchesCount": 0,
        "timestamp": "18. Oktober 2020, 11:17"
    }, {
        "appName": "Corona-Warn",
        "hash": "O1U95vn3KkRXQNUNAu3gUK8zlSDgXu2\/H9uIqa4ynHI=",
        "keyCount": 21527,
        "matchesCount": 0,
        "timestamp": "18. Oktober 2020, 11:17"
    }, {
        "appName": "Corona-Warn",
        "hash": "VOq6FAOxQ1LW\/qlvvIuMC0MqCyzRAmLMYzJOxWM8yL0=",
        "keyCount": 23618,
        "matchesCount": 0,
        "timestamp": "18. Oktober 2020, 11:17"
    }, {
        "appName": "Corona-Warn",
        "hash": "wwFDWRHe3jEWIhnREZnrIeedXYGqmo6V4cLB6LcrPOA=",
        "keyCount": 26284,
        "matchesCount": 0,
        "timestamp": "18. Oktober 2020, 11:17"
    }, {
        "appName": "Corona-Warn",
        "hash": "FmksVqcKrN8X72caj6d58AoIbGv7R9aGOE+46lxx+4M=",
        "keyCount": 23657,
        "matchesCount": 0,
        "timestamp": "18. Oktober 2020, 11:17"
    }, {
        "appName": "Corona-Warn",
        "hash": "OqxTm1BUzkIuVVkkJQ0s6ei9tDZSSjNmRW7nKa1MUbE=",
        "keyCount": 14649,
        "matchesCount": 0,
        "timestamp": "18. Oktober 2020, 11:17"
    }, {
        "appName": "Corona-Warn",
        "hash": "qBoEuZ\/jjM\/tUO4eljKiHDNQx9+goBrxAT9uR6NtCZE=",
        "keyCount": 18134,
        "matchesCount": 0,
        "timestamp": "18. Oktober 2020, 11:17"
    }, {
        "appName": "Corona-Warn",
        "hash": "61qbbpK1q7PO6ggH\/F3caEx80WrENuDNts7vuaAIIlo=",
        "keyCount": 28218,
        "matchesCount": 0,
        "timestamp": "18. Oktober 2020, 11:17"
    }, {
        "appName": "Corona-Warn",
        "hash": "wnvqLcYE6GlPGoWbAj7A90fhyKkkPxKBImGrk\/8Ap4Y=",
        "keyCount": 34105,
        "matchesCount": 0,
        "timestamp": "18. Oktober 2020, 11:17"
    }, {
        "appName": "Corona-Warn",
        "hash": "JWrd8IJXHSXZ2yRLhd5SCqiCKtEmE96gQz3Hv3NtIz8=",
        "keyCount": 43934,
        **"matchesCount": 12,**
        "timestamp": "18. Oktober 2020, 11:17"
    }, {
        "appName": "Corona-Warn",
        "hash": "IJcGAZfoXfwKtmVoz7s4C5ZR9RO7nQcK0YuYNOcahpM=",
        "keyCount": 41646,
        "matchesCount": 0,
        "timestamp": "18. Oktober 2020, 11:17"
    }, {
        "appName": "Corona-Warn",
        "hash": "JU2g74zppJSAtobW56Jsi5pUcb7ItpT9XPAIZtKerhU=",
        "keyCount": 16674,
        "matchesCount": 0,
        "timestamp": "18. Oktober 2020, 11:17"
    }, {
        "appName": "Corona-Warn",
        "hash": "soVm1mrjy2hY9ooOXUh0BDTg9+MJQ6Sak19WBGnOd18=",
        "keyCount": 12380,
        "matchesCount": 0,
        "timestamp": "17. Oktober 2020, 19:57"
    }, {
        "appName": "Corona-Warn",
        "hash": "WlPRGOqp9jGP0zru89529scVNEgKzr7Gr77PmWT4KhU=",
        "keyCount": 8845,
        "matchesCount": 0,
        "timestamp": "17. Oktober 2020, 19:57"
    }, {
        "appName": "Corona-Warn",
        "hash": "SdTEZwNHt0UO5ZrALV8cOLaktD8y7Jps+R5uZeMfPZI=",
        "keyCount": 11260,
        "matchesCount": 0,
        "timestamp": "17. Oktober 2020, 19:57"
    }, {
        "appName": "Corona-Warn",
        "hash": "Y02bprOCbn0iF2mWuNxB7fHgr7TB3QVMavXuORKgjPw=",
        "keyCount": 16120,
        "matchesCount": 0,
        "timestamp": "17. Oktober 2020, 19:57"
    }, {
        "appName": "Corona-Warn",
        "hash": "O1U95vn3KkRXQNUNAu3gUK8zlSDgXu2\/H9uIqa4ynHI=",
        "keyCount": 21527,
        "matchesCount": 0,
        "timestamp": "17. Oktober 2020, 19:57"
    }, {
        "appName": "Corona-Warn",
        "hash": "VOq6FAOxQ1LW\/qlvvIuMC0MqCyzRAmLMYzJOxWM8yL0=",
        "keyCount": 23618,
        "matchesCount": 0,
        "timestamp": "17. Oktober 2020, 19:57"
    }, {
        "appName": "Corona-Warn",
        "hash": "wwFDWRHe3jEWIhnREZnrIeedXYGqmo6V4cLB6LcrPOA=",
        "keyCount": 26284,
        "matchesCount": 0,
        "timestamp": "17. Oktober 2020, 19:57"
    }, {
        "appName": "Corona-Warn",
        "hash": "FmksVqcKrN8X72caj6d58AoIbGv7R9aGOE+46lxx+4M=",
        "keyCount": 23657,
        "matchesCount": 0,
        "timestamp": "17. Oktober 2020, 19:57"
    }, {
        "appName": "Corona-Warn",
        "hash": "OqxTm1BUzkIuVVkkJQ0s6ei9tDZSSjNmRW7nKa1MUbE=",
        "keyCount": 14649,
        "matchesCount": 0,
        "timestamp": "17. Oktober 2020, 19:57"
    }, {
        "appName": "Corona-Warn",
        "hash": "qBoEuZ\/jjM\/tUO4eljKiHDNQx9+goBrxAT9uR6NtCZE=",
        "keyCount": 18134,
        "matchesCount": 0,
        "timestamp": "17. Oktober 2020, 19:57"
    }, {
        "appName": "Corona-Warn",
        "hash": "61qbbpK1q7PO6ggH\/F3caEx80WrENuDNts7vuaAIIlo=",
        "keyCount": 28218,
        "matchesCount": 0,
        "timestamp": "17. Oktober 2020, 19:57"
    }, {
        "appName": "Corona-Warn",
        "hash": "wnvqLcYE6GlPGoWbAj7A90fhyKkkPxKBImGrk\/8Ap4Y=",
        "keyCount": 34105,
        "matchesCount": 0,
        "timestamp": "17. Oktober 2020, 19:57"
    }, {
        "appName": "Corona-Warn",
        "hash": "JWrd8IJXHSXZ2yRLhd5SCqiCKtEmE96gQz3Hv3NtIz8=",
        "keyCount": 43934,
        **"matchesCount": 12,**
        **"timestamp": "17. Oktober 2020, 19:57"**
    }, {
        "appName": "Corona-Warn",
        "hash": "IJcGAZfoXfwKtmVoz7s4C5ZR9RO7nQcK0YuYNOcahpM=",
        "keyCount": 41646,
        "matchesCount": 0,
        "timestamp": "17. Oktober 2020, 19:57"
    }, {
        "appName": "Corona-Warn",
        "hash": "vlpNbCLSOli7yCpMBw\/L8cDsOzjOp5I+vUvoL\/xnNKs=",
        "keyCount": 14299,
        "matchesCount": 0,
        "timestamp": "16. Oktober 2020, 00:40"
    }, {
        "appName": "Corona-Warn",
        "hash": "NwTBAPgIbhy6BZqYTW4l2\/4UkinZ7D8PSHGyWIn5e\/g=",
        "keyCount": 16008,
        "matchesCount": 0,
        "timestamp": "16. Oktober 2020, 00:40"
    }, {
        "appName": "Corona-Warn",
        "hash": "soVm1mrjy2hY9ooOXUh0BDTg9+MJQ6Sak19WBGnOd18=",
        "keyCount": 12380,
        "matchesCount": 0,
        "timestamp": "16. Oktober 2020, 00:40"
    }, {
        "appName": "Corona-Warn",
        "hash": "WlPRGOqp9jGP0zru89529scVNEgKzr7Gr77PmWT4KhU=",
        "keyCount": 8845,
        "matchesCount": 0,
        "timestamp": "16. Oktober 2020, 00:40"
    }, {
        "appName": "Corona-Warn",
        "hash": "SdTEZwNHt0UO5ZrALV8cOLaktD8y7Jps+R5uZeMfPZI=",
        "keyCount": 11260,
        "matchesCount": 0,
        "timestamp": "16. Oktober 2020, 00:40"
    }, {
        "appName": "Corona-Warn",
        "hash": "Y02bprOCbn0iF2mWuNxB7fHgr7TB3QVMavXuORKgjPw=",
        "keyCount": 16120,
        "matchesCount": 0,
        "timestamp": "16. Oktober 2020, 00:40"
    }, {
        "appName": "Corona-Warn",
        "hash": "O1U95vn3KkRXQNUNAu3gUK8zlSDgXu2\/H9uIqa4ynHI=",
        "keyCount": 21527,
        "matchesCount": 0,
        "timestamp": "16. Oktober 2020, 00:40"
    }, {
        "appName": "Corona-Warn",
        "hash": "VOq6FAOxQ1LW\/qlvvIuMC0MqCyzRAmLMYzJOxWM8yL0=",
        "keyCount": 23618,
        "matchesCount": 0,
        "timestamp": "16. Oktober 2020, 00:40"
    }, {
        "appName": "Corona-Warn",
        "hash": "wwFDWRHe3jEWIhnREZnrIeedXYGqmo6V4cLB6LcrPOA=",
        "keyCount": 26284,
        "matchesCount": 0,
        "timestamp": "16. Oktober 2020, 00:40"
    }, {
        "appName": "Corona-Warn",
        "hash": "FmksVqcKrN8X72caj6d58AoIbGv7R9aGOE+46lxx+4M=",
        "keyCount": 23657,
        "matchesCount": 0,
        "timestamp": "16. Oktober 2020, 00:40"
    }, {
        "appName": "Corona-Warn",
        "hash": "OqxTm1BUzkIuVVkkJQ0s6ei9tDZSSjNmRW7nKa1MUbE=",
        "keyCount": 14649,
        "matchesCount": 0,
        "timestamp": "16. Oktober 2020, 00:40"
    }, {
        "appName": "Corona-Warn",
        "hash": "qBoEuZ\/jjM\/tUO4eljKiHDNQx9+goBrxAT9uR6NtCZE=",
        "keyCount": 18134,
        "matchesCount": 0,
        "timestamp": "16. Oktober 2020, 00:40"
    }, {
        "appName": "Corona-Warn",
        "hash": "61qbbpK1q7PO6ggH\/F3caEx80WrENuDNts7vuaAIIlo=",
        "keyCount": 28218,
        "matchesCount": 0,
        "timestamp": "16. Oktober 2020, 00:40"
    }, {
        "appName": "Corona-Warn",
        "hash": "wnvqLcYE6GlPGoWbAj7A90fhyKkkPxKBImGrk\/8Ap4Y=",
        "keyCount": 34105,
        "matchesCount": 0,
        "timestamp": "16. Oktober 2020, 00:40"
    }, {
        "appName": "Corona-Warn",
        "hash": "VOq6FAOxQ1LW\/qlvvIuMC0MqCyzRAmLMYzJOxWM8yL0=",
        "keyCount": 23618,
        **"matchesCount": 0,**
        **"timestamp": "15. Oktober 2020, 00:47"**
    }, {
        "appName": "Corona-Warn",
        "hash": "wwFDWRHe3jEWIhnREZnrIeedXYGqmo6V4cLB6LcrPOA=",
        "keyCount": 26284,
        **"matchesCount": 0,
        "timestamp": "15. Oktober 2020, 00:47"**
    }, {
        "appName": "Corona-Warn",
        "hash": "FmksVqcKrN8X72caj6d58AoIbGv7R9aGOE+46lxx+4M=",
        "keyCount": 23657,
        **"matchesCount": 0,
        "timestamp": "15. Oktober 2020, 00:47"**
    }, {
        "appName": "Corona-Warn",
        "hash": "OqxTm1BUzkIuVVkkJQ0s6ei9tDZSSjNmRW7nKa1MUbE=",
        "keyCount": 14649,
        **"matchesCount": 0,
        "timestamp": "15. Oktober 2020, 00:47"**
    }, {
        "appName": "Corona-Warn",
        "hash": "qBoEuZ\/jjM\/tUO4eljKiHDNQx9+goBrxAT9uR6NtCZE=",
        "keyCount": 18134,
        **"matchesCount": 0,
        "timestamp": "15. Oktober 2020, 00:47"**
    }, {
        "appName": "Corona-Warn",
        "hash": "61qbbpK1q7PO6ggH\/F3caEx80WrENuDNts7vuaAIIlo=",
        "keyCount": 28218,
        **"matchesCount": 0,
        "timestamp": "15. Oktober 2020, 00:47"**
    }, {
        "appName": "Corona-Warn",
        "hash": "vlpNbCLSOli7yCpMBw\/L8cDsOzjOp5I+vUvoL\/xnNKs=",
        "keyCount": 14299,
        **"matchesCount": 0,
        "timestamp": "15. Oktober 2020, 00:45"**
    }, {
        "appName": "Corona-Warn",
        "hash": "NwTBAPgIbhy6BZqYTW4l2\/4UkinZ7D8PSHGyWIn5e\/g=",
        "keyCount": 16008,
        **"matchesCount": 0,
        "timestamp": "15. Oktober 2020, 00:45"**
    }, {
        "appName": "Corona-Warn",
        "hash": "soVm1mrjy2hY9ooOXUh0BDTg9+MJQ6Sak19WBGnOd18=",
        "keyCount": 12380,
        **"matchesCount": 0,
        "timestamp": "15. Oktober 2020, 00:45"**
    }, {
        "appName": "Corona-Warn",
        "hash": "WlPRGOqp9jGP0zru89529scVNEgKzr7Gr77PmWT4KhU=",
        "keyCount": 8845,
        **"matchesCount": 0,
        "timestamp": "15. Oktober 2020, 00:45"**
    }, {
        "appName": "Corona-Warn",
        "hash": "SdTEZwNHt0UO5ZrALV8cOLaktD8y7Jps+R5uZeMfPZI=",
        "keyCount": 11260,
        **"matchesCount": 0,
        "timestamp": "15. Oktober 2020, 00:45"**
    }, {
        "appName": "Corona-Warn",
        "hash": "Y02bprOCbn0iF2mWuNxB7fHgr7TB3QVMavXuORKgjPw=",
        "keyCount": 16120,
        **"matchesCount": 0,
        "timestamp": "15. Oktober 2020, 00:45"**
    }, {
        "appName": "Corona-Warn",
        "hash": "O1U95vn3KkRXQNUNAu3gUK8zlSDgXu2\/H9uIqa4ynHI=",
        "keyCount": 21527,
        **"matchesCount": 0,
        "timestamp": "15. Oktober 2020, 00:45"**
    },

**Comment by daimpi** [comment]
@Morph-O-Mama could you upload your log file here (just rename the ending from .json to .txt) that would make it easier to analyze.
Also: could you tell us which device your using, which Android version you're on and which ENF version you have (you can find your ENF version [here](https://www.coronawarn.app/en/faq/#ENF_version)).

**Comment by Morph-O-Mama** [comment]
@daimpi 
[all-exposure-checks.txt](https://github.com/corona-warn-app/cwa-app-android/files/5413679/all-exposure-checks.txt)

Huawei P20 
EMUI 10.0.0
Android 10
my current ENF is  17203915000

**Comment by daimpi** [comment]
@Morph-O-Mama thanks, I've put your log into [EN analyzer](https://felixlen.github.io/ena_log/) and got the following output:

![grafik](https://user-images.githubusercontent.com/22129968/96754182-38627000-13d1-11eb-96f6-b2d17258f3a0.png)


This is consistent with your screenshot showing 10 exposures and here is the corresponding log entry:
`{"timestamp":"20. Oktober 2020, 20:07","keyCount":43934,"matchesCount":10,"appName":"Corona-Warn","hash":"JWrd8IJXHSXZ2yRLhd5SCqiCKtEmE96gQz3Hv3NtIz8="}`

`timestamp` only tells you the time when your CWA downloaded diagnosis keys (DKs) from the server and matched them with rolling proximity identifiers (RPIs) recorded by your phone from contact with other phones. `timestamp` **doesn't** say anything about the actual point in time when the encounter happened.

If you're interested to learn more about how to interpret the EN log entries I would recommend the following threads/posts: 
- https://github.com/corona-warn-app/cwa-app-android/issues/1217
- https://github.com/corona-warn-app/cwa-app-android/issues/1302
- https://github.com/corona-warn-app/cwa-app-ios/issues/1096#issuecomment-688235743

**Comment by svengabr** [comment]
Dear @Morph-O-Mama,
 
thank you for your post, I can see that @daimpi (Many thanks also to you), analyzed your issue. Looking at the issue myself, I would not rate this as a bug and I don't see the need in opening a Jira issue for the developers at this point.
 
I will remove the bug label and you can continue the discussion here if you want. If all questions are resolved from your perspective, please close this issue.

Best regards,
SG

Corona-Warn-App Open Source Team

**Comment by Morph-O-Mama** [comment]
@daimpi  thank you for your explanation, I will cerainly take a look into your suggestions
@svengabr  I understand, thank you very much
