### ISSUE TITLE
Grootte van bestanden

### ISSUE THREAD

**Issue by amedee** [corona-warn-app/cwa-app-android#1443]
Dit is een officiele app van de overheid, dus ik bedien me van een van de officiele bestuurstalen van het land.

De app is 21MB op de Android store, dus ik ben wat beginnen graven.

Waarom moet `ic_sumbission_country_flag_spain.xml` een halve megabyte zijn, terwijl die van de andere landen allemaal onder de kilobyte zitten?

**Comment by amedee** [comment]
Never mind, wrong repo.

**Comment by vaubaehn** [comment]
anyway, 500kb for the flag seems a little bit much... :es: 
Cheers, and stay healthy please!
