### ISSUE TITLE
Installation fails on Android based Smartphones bought in China

### ISSUE THREAD

**Issue by amijoern** [corona-warn-app/cwa-app-android#1444]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Describe the bug

The App couldn't be installed on several Android based Smartphones bought in China, such as Xiaomi. But it appear it has no problem with those Chinese Smartphone which are available and purchased in Germany.

A example: on a Redmi smartphone the user received a note that he should "activate Exposure Logging", but the app showed no reaction after the option was confirmed.

## Expected behaviour
Explanation or fix for this Problem

## Technical details

- Mobile device:
- Android version:

**Comment by MikeMcC399** [comment]
@amijoern 
- It sounds like you are reported this problem on behalf of another user. Do you have access to the phone which has an issue?
- Was the CWA app installed directly from 
Google Play Store https://play.google.com/store/apps/details?id=de.rki.coronawarnapp&hl=en or via some other method?
- What version of Android is installed on the phone with the problem?
- Is Google Play Services installed on the phone? If yes, what version?
- What version of COVID-19 Exposure Notification Framework is installed on the phone? See [FAQ help on determining ENF version](https://www.coronawarn.app/en/faq/#ENF_version).

See also the FAQ note [[Google/Android]: Why are Android 6 and Google Play Services minimum requirements?](https://www.coronawarn.app/en/faq/#googleplay)

**Comment by svengabr** [comment]
Hello everyone,

the questions from @MikeMcC399 are on point, could you please provide additional information regarding your issue? The Contact Tracing API is a part of Google Play Services. Consequently, the app will not work on devices without enabled play services.

Best regards,
SG

Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
This was answered a while ago. See https://github.com/corona-warn-app/cwa-app-android/issues/1444#issuecomment-715284139

----
Corona-Warn-App Open Source Team
