### ISSUE TITLE
Is there a way to create a backup from an Android phone?

### ISSUE THREAD

**Issue by miri64** [corona-warn-app/cwa-app-android#1453]
I need to reset my phone and I noticed that for all (non-root) backup solutions the app is excluded and the documentation also mentions that the app is not synced with the usual backup services (totally understandable, given that I don't want to have this data associated with some cloud storage account off mine). Is there a way to get my hands on the files on my phone regardless so I can restore them after the factory reset? I know my way around `adb` et al. so I basically just need to know where I can find my data so I can copy it to my PC.

---------------
Internal Tracking ID: EXPOSUREAPP-2182

**Comment by MikeMcC399** [comment]
@miri64 

You may find https://github.com/corona-warn-app/cwa-app-android/issues/1238 helpful if you have a rooted device.

If your device isn't rooted then the request is open in https://github.com/corona-warn-app/cwa-wishlist/issues/8 and there is currently no solution for this.

**Comment by heinezen** [comment]
Closed in favour of https://github.com/corona-warn-app/cwa-wishlist/issues/8

----
Corona-Warn-App Open Source Team
