### ISSUE TITLE
App does not open, only white screen

### ISSUE THREAD

**Issue by Neuwessi11** [corona-warn-app/cwa-app-android#1456]
Because I could not find a fitting issue, I open a new one.
It's my sister's smartphone: If she opens CWA, there occurs a white screen with the Corona-"C" for about 30 sec. Then it goes back to the Desktopscreen.

Huawei P8 Lite (ALE-L21)
Android 6.0
CWA 1.5
EMUI 4.0.3

Before she updated to 1.5 she had a 'normal' 9002-bug.
Does anybody have any ideas?
Thanks!

---
Internal Tracking ID: [EXPOSUREAPP-4471](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4471)

**Comment by vaubaehn** [comment]
Hi @Neuwessi11 ,

Do you remember https://github.com/corona-warn-app/cwa-app-android/issues/642#issuecomment-678680356 ?
Meanwhile a fix had been implemented in CWA 1.5 that either tried to recover the data or to reset the data automatically as a last resort if recovery is not possible.
Unfortunately that fix was not sufficient yet, but an additional fix will come soon with a hotfix release 1.5.1, see #1433 .
The white screen that you saw was the time when the retry mechanism tried to recover. After the hotfix 1.5.1 the problem should be solved.
Thanks for reporting and many greetings! Stay healthy!

**Comment by Neuwessi11** [comment]
Hi vaubaehn,
ja, an #642 kann ich mich dunkel erinnern, aber ich wäre nicht auf die Idee gekommen, dass der White Screen damit zusammenhängt, da der ja keine Fehlermeldung gebracht hat.
Allerdings ist mir inzwischen #1053 über den Weg gelaufen, was ja das gleiche Problem zu sein scheint. Es tut mir leid, dass ich das übersehen habe, als ich dieses Issue kreiert habe.
Falls ich mit dieser Vermutung (mein Problem ist das gleiche wie #1053) richtig liege, kann dieser Thread natürlich auch der Übersicht halber wieder geschlossen werden und ich hänge mich dann an den anderen mit ran.

Eine Frage hätte ich aber noch: Was könnte bis zu 1.5.1 meiner Schwester helfen? Ich habe da komplett den Überblick verloren und wieder mal nur die Hälfte verstanden.
Danke!

**Comment by daimpi** [comment]
@Neuwessi11 
> Eine Frage hätte ich aber noch: Was könnte bis zu 1.5.1 meiner Schwester helfen?

Versuch mal folgendes: https://github.com/corona-warn-app/cwa-app-android/issues/1053#issuecomment-690614975. Das sollte das Problem beheben 🙂.

**Comment by svengabr** [comment]
Hey @Neuwessi11, thanks for your feedback.

As @vaubaehn already mentioned, your issue will most likely be fixed with the next hotfix 1.5.1 which will be released soon. The related pull request is https://github.com/corona-warn-app/cwa-app-android/pull/1433.

In the mean time you could try the [workaround](https://github.com/corona-warn-app/cwa-app-android/issues/1053#issuecomment-690614975) mentioned by @daimpi 

Best regards,
SG

Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
@Neuwessi11, did the updates solve your issue? Thanks for the feedback. DS

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-4471](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4471)

**Comment by Neuwessi11** [comment]
> 
> 
> @Neuwessi11, did the updates solve your issue? Thanks for the feedback. DS

dsarkar, yes, it seems so.
After going the routine it worked until now. But my sister run the helping routine first, so I cannot say per sure, if the updates solved the problem or the workaround (it's a huawei smartphone). But she never had to do anything again.

**Comment by dsarkar** [comment]
@Neuwessi11 Thanks again for contributing here. We will close this issue now. Best, DS

---
Corona-Warn-App Open Source Team
