### ISSUE TITLE
URSACHE: 4000

### ISSUE THREAD

**Issue by AHaumer** [corona-warn-app/cwa-app-android#1457]
Etwas ist schiefgelaufen. (Wer hätte das gedacht?)
error during web request, http status 901

CWA 1.5.0 on Android 6.0 on Acer T04

![Screenshot_20201022-220532](https://user-images.githubusercontent.com/6900273/96926020-50abbb00-14b5-11eb-8a47-54a05b785528.png)

**Comment by thomasaugsten** [comment]
Die App kann die Server nicht erreichen kommt die gleiche Meldung wenn WLAN deaktiviert ist?

**Comment by AHaumer** [comment]
Ich habe keine Datenverbindung ohne WLAN (kein Bedarf, kein Vertrag), und mein WLAN funktioniert bestens.

**Comment by MikeMcC399** [comment]
Ich habe http 901 status schon mal bekommen, als ich unterwegs war und eine schlechte Datenverbindung hatte.

Wenn es sich um einen Heim-WLAN handelt, würde ich versuchen, den Router neu zu starten und Handy auch.

Gibt es den Fehler dauerhaft oder nur sporadisch?

**Comment by vaubaehn** [comment]
@AHaumer 
Auch ich hätte noch ein paar Fragen...
- Kommt der Fehler regelmäßig/immer? Oder kam er jetzt zum ersten Mal?
- Kann das Telefon das WLAN auch im Standby benutzen (entsprechende Option in den WLAN-Einstellungen aktiviert)?
- UnknownHostException deutet darauf hin, dass der DNS-Sever nicht erreichbar war... Gibt es irgendetwas, das die Verbindung blockiert? Z.B., was [hier](https://www.coronawarn.app/de/faq/?search=timeout#cause9002_timeout) aufgeführt ist (bzw. hier: #998 )? Auch wenn kein 'timeout' angezeigt wird, könnten die in den verlinkten Quellen genannten Gründe zu dem Fehler hier beitragen.
- Hilft eines dieser issues: #984 oder #785 weiter, bzw. kann die Fehlerquelle eingrenzen?

**Comment by AHaumer** [comment]
Fehler kam zum ersten Mal, trat gestern abend nicht mehr auf.
Ja Telefon kann WLAN permanent benutzen. 
Nein keine Blockade. Notebook erreicht alle Ziele über das selbe WLAN.
Werde den beiden Tipps zur Fehlereingrenzung nachgehen, danke.

**Comment by dsarkar** [comment]
Dear @AHaumer,

Thanks for your posts. Is your reported issue still persistent? If not seems that it has been a one-off occurrence due to a bad internet connection. In that case, I would suggest closing the issue.

Best wishes,
DS

Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Duplicate of https://github.com/corona-warn-app/cwa-app-android/issues/785

**Comment by dsarkar** [comment]
Dear @AHaumer, dear community

I will close this issue now. Thanks for contributing. If necessary re-open or post here in this topic https://github.com/corona-warn-app/cwa-app-android/issues/785.

Best wishes,
DS

---
Corona-Warn-App Open Source Team
