### ISSUE TITLE
Corona App doesn't support Android Enterprise Devices

### ISSUE THREAD

**Issue by John4711** [corona-warn-app/cwa-app-android#1458]
Corona App doesn't support Android Enterprise Devices

This concern about 1000 devices. Installation was ok but it doesnt start properly.

![20200622_090430-1536x1152](https://user-images.githubusercontent.com/73314970/96931786-26aac680-14be-11eb-9497-e2c8fccd5ca9.jpg)

Is there any solutions about this problem. Otherwise I have to uninstall the app on over 1000 devices.

**Comment by daimpi** [comment]
@John4711 some questions:
- which devices do you have?
- which Android version do they run?
- which Google Play Services version do they run?
- which ENF version do they run? See [FAQ help on determining ENF version](https://www.coronawarn.app/en/faq/#ENF_version).

**Comment by MikeMcC399** [comment]
Hi @John4711 

I saw that you found https://github.com/corona-warn-app/cwa-app-android/issues/604 in the meantime.
Perhaps @svengabr has some current feedback?

Do you have a screen shot of the message before the detail screen that you posted? Is it showing error 17?

There is mention in https://www.coronawarn.app/en/faq/#cause_3 "[Google/Android]: While setting up the app, I’m getting the following error: 'CAUSE: 3. Something went wrong. Error when communication with Google API (17).' What does this mean?"
You have multiple user accounts on your device and the user that you use Corona-Warn-App with doesn’t have administrator rights.

**Comment by MikeMcC399** [comment]
I found also this hint on https://developer.android.com/work/managed-profiles.html#testing_tips

### Test on work profiles: tips and tricks
There are a few tricks that you may find helpful in testing on a work-profile device.

As noted, when you side-load an app on a work-profile device, it is installed on both profiles. If you wish, you can delete the app from one profile and leave it on the other.

(I should add that I have no experience with Android Enterprise, so just use the link for background reading, if you find it helpful.)

**Comment by dsarkar** [comment]
> @John4711 some questions:
> 
> * which devices do you have?
> * which Android version do they run?
> * which Google Play Services version do they run?
> * which ENF version do they run? See [FAQ help on determining ENF version](https://www.coronawarn.app/en/faq/#ENF_version).

Dear @John4711 ,

Thank you for your contribution. In order to look further into this issue, please provide the details as requested by @daimpi. 

Best wishes,
DS

Corona-Warn-App Open Source Team

**Comment by John4711** [comment]
Hello DS,

I would like to answer as best I can.

they are samsung devices (S7, S8, S9) with activated Knox services.
it depands. but they all have lates firmware and latest security patches
it depands. but they all have Google Play Services Versions - They will all updated silently.
ENF Version should be 1.5, but on Android Enterprise Installation Devices (DO) - I assume is/was not installable.

Best wishes,
C.

**Comment by John4711** [comment]
Regarding this comment:
Test on work profiles: tips and tricks

My Company has decided to install them only via DO-Installation - not with work profile

Best wishes,
c.

**Comment by John4711** [comment]
This is 1st message:
![0_20201009_120218](https://user-images.githubusercontent.com/73314970/97082857-f9b8f980-160c-11eb-854b-c6dd14f2874f.jpg)
Best wishes,
C.

**Comment by daimpi** [comment]
@John4711 
> ENF Version should be 1.5, but on Android Enterprise Installation Devices (DO) - I assume is/was not installable.

Does this mean the devices don't have ENF on them? What do you see when you [try to find out the ENF version](https://www.coronawarn.app/en/faq/#ENF_version) on one of the devices?

**Comment by MikeMcC399** [comment]
@John4711 

That message shows the exact problem! You are missing the Google Exposure Notification System.
Also it shows that you are using version 1.3.1 not the latest 1.5.0 version. (I can see that from the space before "(17)".

**Comment by John4711** [comment]
Here are all detailt messages:

![Screenshot_20201022-152546](https://user-images.githubusercontent.com/73314970/97082960-8499f400-160d-11eb-9efc-59ab972bc78b.jpg)
![Screenshot_20201022-152555](https://user-images.githubusercontent.com/73314970/97082961-86fc4e00-160d-11eb-8867-7e07daf8005f.jpg)
![Screenshot_20201022-152603](https://user-images.githubusercontent.com/73314970/97082963-88c61180-160d-11eb-8e8e-e2e92062d65f.jpg)
![Screenshot_20201022-152609](https://user-images.githubusercontent.com/73314970/97082964-8a8fd500-160d-11eb-8efb-ec0f44814c8a.jpg)
Best wishes,
C.

**Comment by John4711** [comment]
any ideas? I guess, it has something to do with mobile iron. I createt also a support ticket there.

**Comment by daimpi** [comment]
@John4711 

Could you do what is described in the [FAQ entry](https://www.coronawarn.app/en/faq/#ENF_version) regarding ENF version?

1. In the Settings, go to 'Google > COVID-19 exposure notifications'
2. Scroll down the 'COVID-19 notifications' page. At the very bottom, the version is displayed […]

Could you provide a screenshot of that if possible?

**Comment by John4711** [comment]
yes, I could do that on Monday at work.

**Comment by daimpi** [comment]
@John4711 
Ok, thanks. B/c we need to know whether ENF is at all running on those devices b/c without it there is no chance to get any ENF based app working in the first place… and as @MikeMcC399 [stated above](https://github.com/corona-warn-app/cwa-app-android/issues/1458#issuecomment-715915016): it looks like you're actually missing ENF on those devices.

**Comment by MikeMcC399** [comment]
@John4711 / @daimpi 
I think that @John4711 will find when he tries to look for Settings > Google > COVID-19 exposure notifications that "COVID-19 exposure notifications" will be completely missing, so it cannot be called.

The next step, if that entry is missing, would be to look in Settings > Apps for a system app
"Google Play services" which is what delivers the Google Exposure Notification System.

I think this is all about making sure that the CWA app gets the right environment to be able to run. You may need help from somewhere which is more familiar with Android Enterprise and Google Play Store / Google Play services.

**Comment by MikeMcC399** [comment]
@John4711 
The error screens you are seeing are identical to what I see on an Android 10 emulator which has no Bluetooth.
My hunch is that there is a security policy enabled which prevents Bluetooth usage or access on your devices. CWA will not work without Bluetooth.

**Comment by dsarkar** [comment]
Hi @John4711,

thank you for response, and indeed, as @daimpi and @MikeMcC399 suggest, can you please confirm that ENF and Bluetooth are both activated on your devices?

Best regards,
DS

Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@John4711 
Did you manage to solve your deployment issue?

**Comment by John4711** [comment]
Hi @dsarkar,

I can confirm, that ENF isn't installed on it, but BT is still activated and working.
I can confirm, that CWA is working on Android Enterprise Device Only Deployments, not on AE with Workprofiles. I guess, this is a Google Issue not an issue of MDM Vendor or CWA Dev Team.
I cannot open a ticket at google, but may be the CWA Dev Team.
Regards,
J.

**Comment by lduesing** [comment]
Did some tests about that problem.
To verify the problem without AE, but with Workprofiles:
- Install the "Test DPC" (com.afwsamples.testdpc)
- Add Work Profile (Do NOT start any app in work profile for now!)
- Install cwa in personal profile
- Start cwa
- (go to some crowded place, see the counter ticking)
- start ANY app in work profile (i.e. play store)
- (go again to some crowded place, you won't see anything ticking...)

**Comment by MikeMcC399** [comment]
This is an old issue, however I noticed that the [Google - Exposure Notifications implementation guide](https://developers.google.com/android/exposure-notifications/implementation-guide) now carries the following:

"Note: Only applications running on the phone's primary profile can access the Exposure Notification APIs. Calling these APIs from an application running in a secondary profile or in a work profile will result in the ExposureNotificationStatus [USER_PROFILE_NOT_SUPPORT](https://developers.google.com/android/reference/com/google/android/gms/nearby/exposurenotification/ExposureNotificationStatus#public-static-final-exposurenotificationstatus-user_profile_not_support)."

**Comment by MikeMcC399** [comment]
@John4711 / @dsarkar 

I suggest to close this issue if there is no further feedback. It seems to be a Google restriction which CWA cannot resolve.
