### ISSUE TITLE
!!! "Low risk" - living with positively tested and reported person. !!!

### ISSUE THREAD

**Issue by residualmind** [corona-warn-app/cwa-app-android#1465]
I'm skipping the formalities, since this looks serious.

A family member (A) has been living with a positively tested and reported person (B) for over a week. B has confirmed their test result through the app.

They even put their phones next to each other for over an hour a few times.

**Still, A has only 3 exposures and "low risk".**

A few days later, the number of exposures dropped to zero.

Phones used:
Huawei mate 20 pro
Huawei y7 2019

Please contact me for details.

**Comment by daimpi** [comment]
@residualmind 
could you share Person's A EN log and a detailed timeline, when exactly Person B uploaded their diagnosis keys (DKs) and when Person A and B were together?

**Comment by vaubaehn** [comment]
Most likely not the cause of the problem here, but could be related:
@thomasaugsten 
In Google Play Store reviews, from time to time people are reporting, that there Wifi is badly interfered by BLE being activated. Has it ever been examined, if it could also be the other way round, that a 2.4GHz Wifi could disturb receiving BLE beacons from a second device? Do you have any information about it?

**Comment by godofglow** [comment]
Same problem at my colleague

**Comment by stephankn** [comment]
Can you confirm, that both devices are broadcasting beacons? Do they receive BLE beacons from others? I checked the phones we use with the free "nRF Connect" app which can show BLE messages. If this already fails then it is a problem with the phone hardware/software stack, not CWA. In another issue (which I sadly can't locate right now) it was mentioned that CWA does not properly check whether the hardware supports all required BLE functionality.

**Comment by MikeMcC399** [comment]
@stephankn 

I found [Beacon Scope](https://play.google.com/store/apps/details?id=com.davidgyoungtech.beaconscanner&hl=en) to be easier to use to check sending and receiving Bluetooth LE beacons for Exposure Notification.

For [nRF Connect for Mobile](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=en) there are [some great screenshots](https://github.com/corona-warn-app/cwa-app-android/issues/674#issuecomment-646949156) in issue #674 for checking the device Bluetooth Low Energy compatibility.

**Comment by stephankn** [comment]
@MikeMcC399 thanks for linking. The notes in #674 comment https://github.com/corona-warn-app/cwa-app-android/issues/674#issuecomment-646949156 was exactly what I remembered.

It would be great if CWA could run this check as well. If that nRC connect app is able to read out this setting, CWA should be able to do as well. It could then display a warning stating that phone is not compatible. 

It is unclear whether this is the case in this issue. @residualmind or @godofglow, can you comment on this?

**Comment by dsarkar** [comment]
Hi @residualmind,

thank you for your contribution. Could you please provide additional information, i.e. amongst other things mentioned by @daimpi the ENF logs and version number of your CWA App. See here https://github.com/corona-warn-app/cwa-app-android/issues/1187#issuecomment-696269346 how to get those files. 

Best wishes, 
DS 

Corona-Warn-App Open Source Team

**Comment by residualmind** [comment]
Hi @dsarkar.

Both parties are running version 1.5.0.

I attached a zip (github didn't like the extension json) with both all-exposure-checks files.

I requested more information about the timeline.

[all-exposure-checks-person-a-and-b.zip](https://github.com/corona-warn-app/cwa-app-android/files/5439340/all-exposure-checks-person-a-and-b.zip)

**Comment by residualmind** [comment]
@dsarkar @daimpi 

The diagnosis keys were uploaded on october 14 afternoon, probably between 14:00 and 16:00.

A and B have been together in the same apartment since October 12, with phones usually 2m apart.

Since the app did not show anything, they intentionally put the phones next to each other, without any cases on october 15 for about an hour. They did the same on the next day, october 16 for about 2 hours.

Apart from that, during all day since the October 12, the phones are often 1.5m apart during longer parts of the day.

**Comment by vaubaehn** [comment]
@residualmind 

> The diagnosis keys were uploaded on october 14 afternoon, probably between 14:00 and 16:00.
> Since the app did not show anything, they intentionally put the phones next to each other, without any cases on october 15 for about an hour. They did the same on the next day, october 16 for about 2 hours.

CWA (and all other apps based on Google/Apple Exposure Notification Framework) can only take exposures into account, that happened **_before_** the upload of diagnosis keys. So putting the phones together after October 14 will not have had any effect.

The question is, why was no exposure tiggered between October 12 and October 14.

For person B, in the exposure log, there is no entry before October 14. Did this person install CWA on that day?

**Comment by residualmind** [comment]
@vaubaehn You're correct. The positive person only activated the app after their diagnosis - so that explains everything I think.
Thanks for your explanation and sorry to cause confusion, I wasn't aware that it works this way.

**Comment by daimpi** [comment]
@residualmind Ah yes that explains it o/c 👍. 

Here is a nice explainer on the principle underlying digital contact tracing apps like CWA: https://ncase.me/contact-tracing/

**Comment by vaubaehn** [comment]
> The positive person only activated the app after their diagnosis - so that explains everything I think.
> Thanks for your explanation and sorry to cause confusion

@residualmind That's what we're here for. Stay healthy! :)

**Comment by vaubaehn** [comment]
OT

Independent from this issue's subject here, I'm still wondering about this:

> 
> @thomasaugsten
> In Google Play Store reviews, from time to time people are reporting, that their Wifi is badly interfered by BLE being activated. Has it ever been examined, if it could also be the other way round, that a 2.4GHz Wifi could disturb receiving BLE beacons from a second device? Do you have any information about it?

Do you have any information about inteference of 2.4 GHz Wifi and Bluetooth wrt reliability of RPIs?

@svengabr I was thinking, whether it can be useful to create a short FAQ related to Wifi and Bluetooth interference. In Google Play Store reviews, it's a reason for some people to uninstall CWA, if BLE is disturbing Wifi. Some short recommendations could be given - maybe it's worth to think about it and create a new FAQ issue? What do you think?
