### ISSUE TITLE
UI partially not updating when exposure check is run in the foreground

### ISSUE THREAD

**Issue by crcsn** [corona-warn-app/cwa-app-android#1466]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Describe the bug

The "Updated: Today, 06:33" part of the risk card on the main view does not update, when the exposure check is run in the foreground, i.e. when an update was not done in the last ~24 hours and the user opens the app, so that the exposure check is manually triggered.

I opened the app this morning, the check ran (visible in the UI), and afterwards the first two lines of the risk card updated correctly (in the first line, the number of exposures went up from 1 to 2 for me today; in the second line it read "Exposure logging permanently active" again after the check). In the third line, it still read "Updated: Yesterday, [time]" Closing and reopening the app updated the UI, so that it read "Updated: Today, 06:33". I noticed the same bug yesterday.

## Expected behaviour

The "Updated" part of the UI should update immediately after the check is run in the foreground, as the other parts of the UI apparently do.

## Steps to reproduce the issue

1. Put the app in a condition, where it needs to do a manual run of the exposure check.
2. Open the app.
3. Let the exposure check run.

## Technical details

- Mobile device: Samsung Galaxy S10
- Android version: Android 10

**Comment by daimpi** [comment]
@crcsn 
Your problems sounds very similar to https://github.com/corona-warn-app/cwa-app-android/issues/1081

In [particular](https://github.com/corona-warn-app/cwa-app-android/issues/1081#issuecomment-696624268) 
> The mainView/risk card is not completely refreshed
Internal Tracking ID: EXPOSUREAPP-2795

Do you agree? If so feel free to close this issue here and move the discussion over to https://github.com/corona-warn-app/cwa-app-android/issues/1081 🙂.

**Comment by crcsn** [comment]
@daimpi 
true, that is indeed the same issue (EXPOSUREAPP-2795) that is _supposed_ to be discussed in the #1081 

Will close this.

**Comment by daimpi** [comment]
@crcsn no worries… it's hard to find the right one among the the plethora of issues 😅.
