### ISSUE TITLE
Exposure Logging Stopped and history lost

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#1468]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/) 
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Describe the bug
After opening the CWA app, EXPOSURE LOGGING was STOPPED and onboarding sequence was presented.
After completing the onboarding sequence, instead of seeing the Low Risk card, I am now seeing Unknown Risk status because CWA has not been active long enough.

## Expected behaviour
Since I did not reset the app in any way I did not expect it to reset itself.

CWA should have shown me that it had been running all the time with a Low Risk result.
The Google exposure check log should have had a history of 14 days.

## Steps to reproduce the issue

Open CWA.

This was a spontaneous reset, it is not normally reproducible.

## Technical details

- Mobile device: Samsung Galaxy A50 SM-A505FN
- Android version: 10
- CWA version: 1.5.0
- Google Play services version: 20.39.15 (120400-335085812) beta version
- Exposure Notification System version: 17203915000

## Possible Fix

Monitor for similar reports and take action if other users report it as well.

## Additional context

- I have had CWA running for more than 14 days and on Monday Oct 19, 2020 I updated to 1.5.0.
- I was enrolled on the Google Play services beta and although I have since left the beta there has been no new release available from the Google Play store, so I still have a beta version installed.
- The exposure checks log has been cleared out and there is now just one entry from after the onboarding sequence was completed.
- The device is not rooted, so I cannot see if the random IDs from the previous 14 days have been completely lost or not.
- There were no error messages shown.

---
Internal Tracking ID: EXPOSUREAPP-3427

**Comment by vaubaehn** [comment]
@d4rken is there any way that automatic recovery can be triggered without showing the dialog?

**Comment by MikeMcC399** [comment]
In https://github.com/corona-warn-app/cwa-app-android/issues/642#issuecomment-697226914 @Druidikaaa reported on Sept 23, 2020 being unexpectedly presented with the onboarding dialog with Android 10. Judging by the date, it would have been CWA 1.3.0 at the time.

**Comment by heinezen** [comment]
Thanks for reporting @MikeMcC399 ,

I've created a Jira ticket (EXPOSUREAPP-3427) with the provided information and forwarded it to the developers.

Regards
CH

----
Corona-Warn-App Open Source Team

**Comment by d4rken** [comment]
> @d4rken is there any way that automatic recovery can be triggered without showing the dialog?

Not on 1.5.0, the routine does not trigger AFAIK. The error is very specific.

@MikeMcC399 Did you open the app after 1.5.0 successfully with your previous data intact at any point? Meaning, can we rule out that the state was already present on 1.3.0 and you only became aware after opening the app after the 1.5.0 update? While 1.5.0 will attempt to prevent the encryption issue #642 if the issue was present, before the upgrade, it would still be there on 1.5.0.

**Comment by MikeMcC399** [comment]
@d4rken 
> Did you open the app after 1.5.0 successfully with your previous data intact at any point? Meaning, can we rule out that the state was already present on 1.3.0 and you only became aware after opening the app after the 1.5.0 update? While 1.5.0 will attempt to prevent the encryption issue #642 if the issue was present, before the upgrade, it would still be there on 1.5.0.

Yes, this is a pure 1.5.0 issue and data was first intact with 1.5.0.

I updated to CWA 1.5.0 immediately after it was released on Monday, Oct 19, 2020 12:00 and I opened it at least once a day manually after that. On Friday, Oct 23, 2020 I had opened it during the day and it behaved normally. Then early evening I opened it again and noticed the issue that it had reset itself.

The exposure check log shows 3 checks in the past 14 days:
23.10.2020 18:04 (after I completed onboarding following the reset)
24.10.2020 02:20
25.10.2020 02:21

**Comment by MikeMcC399** [comment]
Closing this issue, since it has not happened to me again, and there have been no other similar reports since then.
The current version is now 1.5.1 rather than 1.5.0 when this issue was opened.
