### ISSUE TITLE
Not able to register new test

### ISSUE THREAD

**Issue by osiktech** [corona-warn-app/cwa-app-android#1485]
Hi

since I updated to version 1.5.0 on my Android it seems the app is not able to fetch my old test result from mid september.

It says "Data being retrieved". The app itself seems to work fine, but at the moment I would not be able to add a new test.

![Screenshot_20201026-191630](https://user-images.githubusercontent.com/21309019/97211754-cd91aa00-17bf-11eb-8466-4ea486d7a788.jpg)

I guess I could delete local storage and caches. But I thought it might be interesting to see if this is a single user problem or might affect others as we and is worth debugging.

Let me know, if I can provide more information.

Best

**Comment by MikeMcC399** [comment]
Hi @osiktech 
This is the same as the issue #1084 and if you scroll down to https://github.com/corona-warn-app/cwa-app-android/issues/1084#issuecomment-716551517 you can read that a fix is planned.

**Comment by osiktech** [comment]
Dann it, I missed that one. Sorry for creating the duplicate.

Thanks for pointing in the right direction.

Best

**Comment by MikeMcC399** [comment]
No problem! 😄
