### ISSUE TITLE
Unable to leave the page submission_done after report of positive test

### ISSUE THREAD

**Issue by sebastian-nagel** [corona-warn-app/cwa-app-android#1511]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Describe the bug

After the report of a positive test the app is trapped on the page "Thank you". The App stays in a state where it is impossible to leave this page, it's only possible to switch between the first and second part. However, some other pages (eg. settings are still reachable).

- neither "force stop" or a reboot of the phone makes the app leave this state
- resetting the app helps. However, this brings the app back to a state just after installation with all information lost. At least, I hope the [faq](https://www.coronawarn.app/en/faq/#delete_random_ids) is correct that random IDs are not deleted.

## Expected behaviour

It should always be possible to leave any page even if the page includes two frames.

Minor app states (such as the last open page) should be persisted in a way that it does not require a "reset" to clear this state.

## Steps to reproduce the issue

1. follow the entire procedure to request a TAN (via phone) to submit a positive test result
2. on the submission page (first part) press Done
3. now the second part is shown, pressing the right arrow brings you back to the first part
4. pressing Done again (or the upper left X) brings you back to the first part (unable to leave the submission page)

Reproduced by requesting a second TAN now on mobile data (wifi when the issue has been seen first).

![Screenshot_20201031-144439](https://user-images.githubusercontent.com/1630582/97780984-84a77000-1b88-11eb-81eb-9b84fc28916e.png)
![Screenshot_20201031-144538](https://user-images.githubusercontent.com/1630582/97780986-88d38d80-1b88-11eb-9872-41b14d1d07f6.png)

## Technical details

- Mobile device: Fairphone 3
- Android version: 10

## Additional context

---
Internal Tracking ID: EXPOSUREAPP-3550

**Comment by heinezen** [comment]
Hey @sebastian-nagel 

Thanks for the feedback. We have created a ticket in the internal Jira for the bug (ticket ID: EXPOSUREAPP-3550 ). The devs will now look into this and provide a fix. We will notify you here in the Github issue once the situation is resolved.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Dear @sebastian-nagel and community.

Thanks again for contributing. This issue has been fixed and therefore will be closed now.

- The sub-screen with the "Done" button no longer exists since the new submission flow.
- The user lands on the home screen with the "Vielen Dank" card, the rest of the app is still reachable.
- It's no longer possible to be stuck on a screen.


Thanks again. Best wishes,
DS

---
Corona-Warn-App Open Source Team
