### ISSUE TITLE
Unnecessary "Activate Location Setting" onboarding message on Android 11

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#1541]
## Avoid duplicates 

* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue
This is a follow-on from the closed issue https://github.com/corona-warn-app/cwa-app-android/issues/986 regarding a sub-problem reported by @MikeJayDee in  https://github.com/corona-warn-app/cwa-app-android/issues/986#issuecomment-712168348.

## Describe the bug

In the screen "How to Enable Exposure Logging", which is displayed as part of the onboarding process, the following text is always displayed.

![Activate Location Setting EN DE](https://user-images.githubusercontent.com/66998419/109658933-6fa71180-7b67-11eb-8ed5-7c7aa8329a85.jpg)

In Android 11 (API 30), and above, Google has made an exception for their Exposure Notifications System and it is not required for the location setting to be enabled, therefore this text should not appear for this version of Android.

## Expected behavior

In Android 11 (API 30) and above, the information about location access should not be displayed. The Google Exposure Notifications System does not require the device's location setting to be enabled in order to use Bluetooth Low Energy. See https://support.google.com/android/answer/9930236.

(In Android 10 (API 29) and below, the text should continue to be displayed. The translation error for the English-language text (covered in https://github.com/corona-warn-app/cwa-app-android/issues/2345) ~~is planned to be fixed in 1.13.x~~ was fixed in 1.13.2. There is a follow-on text issue in https://github.com/corona-warn-app/cwa-app-android/issues/2506.)

## Steps to reproduce the issue

For Android 11:

1. CWA > three-dot icon > Settings > Reset App and confirm
2. Tap "LET'S GET STARTED"
3. Tap "NEXT"
4. On screen "How to Enable Exposure Logging" scroll down to the section under "The following countries currently participate" and note the information about "Allow location access".

## Technical details

- Android version: 11 (API 30)
- Mobile device: Pixel 3a emulator
- CWA version: ~~1.12.0~~ 1.14.3
- ENS version: 18210214000

## Possible Fix

Do not display ~~"Allow location access"~~ "Activate location access" for Android 11 during onboarding, using dynamic setting for visibility of `id/onboarding_location_card`?

`onboarding_tracing_location_headline` and `onboarding_tracing_location_body` are used in `layout\fragment_onboarding_tracing.xml`

Note also https://developers.google.com/android/exposure-notifications/implementation-guide#locationless_scanning_in_android_11 ~~which refers to `deviceSupportsLocationlessScanning()` which is already used in `de\rki\coronawarnapp\nearby\modules\locationless\DefaultScanningSupport.kt`~~ advises the use of getStatus() to determine the need to enable the location setting.

## Additional context

~~FAQ https://www.coronawarn.app/en/faq/#android_location is currently inaccurate concerning Android 11 in the main article, although the links to the Google pages correctly describe the differences between Android 10 and below compared with Android 11. (See https://github.com/corona-warn-app/cwa-website/issues/539.)~~
Fixed by https://github.com/corona-warn-app/cwa-website/pull/550.

Edit: Updated to correspond to app state for 1.14.3

---
Internal Tracking ID: EXPOSUREAPP-3618
related to
Internal Tracking ID: EXPOSUREAPP-2025

**Comment by heinezen** [comment]
Hello @MikeMcC399 ,

Thank you for the report. We have mirrored the issue to Jira (ticket ID: EXPOSUREAPP-3618) and it should soon be addressed by the devs.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Dear @MikeMcC399,

Update on your reported issue: There is actually another internal ticket on this issue: EXPOSUREAPP-2025 and related PR https://github.com/corona-warn-app/cwa-app-android/pull/1057. We will publish any further developments here.

Best wishes,
DS

Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@dsarkar 

PR #1057 seems to only cover the check about whether location services are needed. I can't see anything in that PR which deals with displaying the instructions "Allow location access" or not. Also PR #1057 was marked as merged on Aug 27 already. I see though that it implements the check using `deviceSupportsLocationlessScanning()` so perhaps that is why you mentioned it.

I assume that the issue with displaying the instructions will be tracked via EXPOSUREAPP-3618 as @heinezen said.

**Comment by dsarkar** [comment]
@MikeMcC399, sure your issue is tracked via EXPOSUREAPP-3618.

**Comment by dsarkar** [comment]
Hi @MikeMcC399, I would like to ask you a favor. The developers are asking if you can reproduce this error still. Thanks!

**Comment by MikeMcC399** [comment]
@dsarkar 
The problem still occurs using CWA Android 1.10.1

The following message is always displayed during onboarding:

![Allow location access](https://user-images.githubusercontent.com/66998419/98230529-8f348180-1f5b-11eb-8acc-6ecb9c0719c9.jpg)

For Android 10, the message is shown even when location is enabled.
For Android 11, the message should never be shown because it is not necessary to enable location in order to use CWA.

Do the developers think they have fixed the issue or why are they asking?

**Comment by dsarkar** [comment]
@MikeMcC399  Thanks!

**Comment by dsarkar** [comment]
@MikeMcC399, not sure why they asked to get feedback. What I can see in the ticket is that they are looking at this issue.

**Comment by dsarkar** [comment]
Regarding onboarding on Android 10, I get these two sequences (location services on versus location off). It looks ok to me. In particular, it skips the 'location' bit. Device Samsung A21s / Android 10 / CWA 1.12

Location services off

![image](https://user-images.githubusercontent.com/1409741/107772810-06d53200-6d3d-11eb-99b1-e8a41a9876c2.png)


Location services off

![image](https://user-images.githubusercontent.com/1409741/107772872-1a809880-6d3d-11eb-9879-033673a389b8.png)

**Comment by dsarkar** [comment]
Can't test the behavior on Android 11 yet, update to Android 11 for Samsung A21s is apparently in May 2021.

**Comment by MikeMcC399** [comment]
@dsarkar

You need scroll down on the screen "How to Enable Exposure Logging" to the section "Allow location access" where it says "Your location cannot be accessed." even when location is already enabled.  

![Allow location access](https://user-images.githubusercontent.com/66998419/98230529-8f348180-1f5b-11eb-8acc-6ecb9c0719c9.jpg)

On my Android 10 device running CWA Android 1.12.0 the issue is not fixed. Do you have a PR which is supposed to fix the issue?

**Comment by dsarkar** [comment]
@MikeMcC399 ok! 

> Do you have a PR which is supposed to fix the issue?
No. It says it is being analyzed still.

> You need to scroll down on the screen "How to Enable Exposure Logging" to the section "Allow location access" where it says "Your location cannot be accessed." even when the location is already enabled.

Ok, I can see it now.



I think one solution is to remove this card completely. Or just say that location services will be needed up to Android 11.

Later in the onboarding sequence, the logic seems to work correctly: Depending on the current setting, you are asked to "Turn on", or the step is skipped, respectively.

What do you think?

**Comment by MikeMcC399** [comment]
@dsarkar 

Thanks for your suggestions! After I looked at the German message I realise it's also a translation problem!

In the German message it is clear (to me) that it is telling the user that it needs the location enabled in order to use Bluetooth, however it will not be used to look up the location of the device.

![Standort-Verwendung erlauben](https://user-images.githubusercontent.com/66998419/107796999-b79dfa00-6d5a-11eb-9e21-d5dbdb7b11e7.jpg)

----

Now in the English message I've been understanding this all along to say that location isn't enabled and you need to enable it.

![Allow location access](https://user-images.githubusercontent.com/66998419/98230529-8f348180-1f5b-11eb-8acc-6ecb9c0719c9.jpg)

----

Let me split this off into a different issue about the translation of the message into English and leave this issue to discuss the technical implementation.

**Comment by dsarkar** [comment]
@MikeMcC399 I see, interesting! 

**Issue 1:** 
This card t is not an instruction, but an information, with an incorrect translation. You split this into another issue, ok, I will create an internal ticket.

**Issue 2:**
Now this issue remains, because you confirm that during  the on-boarding with the Android 11 emulator, you also see this info-card, and it should not be there. Correct?

**Issue 3:**
Regarding Android 11. During the o- boarding sequence, are you asked to allow location access in both cases, i.e. with location services on or off? I am not referring to not this info-card, but later this notification:
![image](https://user-images.githubusercontent.com/1409741/107822316-30627d80-6d7e-11eb-93d9-1cb160a55ef3.png)
If so, this doesn't seem right, no such notification should be necessary, and there this would be another 3rd issue, correct?

**Comment by MikeMcC399** [comment]
@dsarkar 

> Issue 1:
This card is not an instruction, but information, with an incorrect translation. You split this into another issue, ok, I will create an internal ticket.

Thanks. 👍 This is https://github.com/corona-warn-app/cwa-app-android/issues/2345.

> Issue 2:
Now this issue remains, because you confirm that during the on-boarding with the Android 11 emulator, you also see this info-card, and it should not be there. Correct?

Correct! I considered modifying the issue (#1541) to cover only Android 11, but that would make it messy, so I will open a new issue for Android 11 only. Perhaps I can also make a concrete suggestion for solution?

> Issue 3:
Regarding Android 11. During the o- boarding sequence, are you asked to allow location access in both cases, i.e. with location services on or off? I am not referring to not this info-card, but later this notification:
image
If so, this doesn't seem right, no such notification should be necessary, and there this would be another 3rd issue, another ticket, correct?

On Android 11 with an emulator I am **not** prompted to enable location, so thankfully there is no "Issue 3". 🙂

**Comment by MikeMcC399** [comment]
@dsarkar 
> I think one solution is to remove this card completely. Or just say that location services will be needed up to Android 11.

Removing the card would be a possibility. Let's see if we can get it cleaned up so that doesn't look like the best solution!

**Comment by MikeMcC399** [comment]
I have updated this issue to focus on Android 11.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for feedback. Issue one (translation issue) is crystal-clear, new ticket created.

This issue 2 here, Android 11 on-boarding: One solution is removing this card, but I am understand you might want to propose to the dev team something else? Like one for all solution?

**Comment by MikeMcC399** [comment]
@dsarkar 

> This issue 2 here, Android 11 on-boarding: One solution is removing this card, but I am understand you might want to propose to the dev team something else? Like one for all solution?

I updated the **Possible Fix** section in this issue #1541. That would only change what happens on Android 11 and leave earlier versions unchanged, which is fine if the translation gets fixed:

----
## Possible Fix

Do not display "Allow location access" for Android 11 during onboarding, perhaps using visibility of `id/onboarding_location_card`?

`onboarding_tracing_location_headline` and `onboarding_tracing_location_body` are used in `layout\fragment_onboarding_tracing.xml`

Note also https://developers.google.com/android/exposure-notifications/implementation-guide#locationless_scanning_in_android_11 which refers to `deviceSupportsLocationlessScanning()` which is already used in `de\rki\coronawarnapp\nearby\modules\locationless\DefaultScanningSupport.kt`

----

It's usually possible in Android to make views dynamically VISIBLE or GONE (not shown and don't take up space), see https://developer.android.com/reference/android/view/View?hl=en#setVisibility(int).

Unfortunately my own programming skills are not good enough to tackle this through a PR, but I am pretty sure that it is possible to implement.

**Comment by dsarkar** [comment]
@MikeMcC399 Alright, I will update the internal ticket and put context with the new translation issue. Many thanks for analysing thoroughly this issue.

**Comment by MikeMcC399** [comment]
@dsarkar 

There has been a change to the advice given by Google about how to check whether the Android operating system needs the location setting enabled or not.

---
The [Implementation Guide](https://developers.google.com/android/exposure-notifications/implementation-guide) says in the section:

[Locationless scanning in Android 11](https://developers.google.com/android/exposure-notifications/implementation-guide#locationless_scanning_in_android_11)

"The requirement to have location enabled has been a source of confusion for some users. Android 11 introduced a change that allows users to use the Exposure Notification system without having location enabled. This also requires a v1.6+ module as described in the [release notes](https://developers.google.com/android/exposure-notifications/release-notes#locationless_scanning).

To determine the state of the device and guide users through any manual settings changes needed to enable ENS you can use the [getStatus()](https://developers.google.com/android/reference/com/google/android/gms/nearby/exposurenotification/ExposureNotificationClient#getStatus()) method ([added in v1.7](https://developers.google.com/android/exposure-notifications/release-notes#new_getstatus_method)), which returns a variety of [ExposureNotificationStatus constants ](https://developers.google.com/android/reference/com/google/android/gms/nearby/exposurenotification/ExposureNotificationStatus) These constants are specific to the user's version of Android. For example, if the `getStatus()` method returns [LOCATION_DISABLED](https://developers.google.com/android/reference/com/google/android/gms/nearby/exposurenotification/ExposureNotificationStatus#public-static-final-exposurenotificationstatus-location_disabled), then they need to manually enable location."

---
The [v1.8 release notes](https://developers.google.com/android/exposure-notifications/release-notes#locationless_scanning) say:

[Locationless scanning](https://developers.google.com/android/exposure-notifications/release-notes#locationless_scanning)

"With Android 11, version 1.6 and higher of Exposure Notifications works without having to enable Location Services. This means there are now additional cases in which it is not necessary to prompt users to manually enable this setting.

To simplify checking when locationless scanning is available on the device, we have updated the SDK (v1.6.1) to include [deviceSupportsLocationlessScanning()](https://developers.google.com/android/exposure-notifications/exposure-notifications-api#locationlessscanning). This method returns a boolean value indicating whether a given device supports locationless scanning. (Note that as of the v1.7 SDK, we recommend checking via a [different approach](https://developers.google.com/android/exposure-notifications/implementation-guide#locationless_scanning_in_android_11).)"

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for the last comment: Internal Tracking ID: [EXPOSUREAPP-5471](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5471)

**Comment by dsarkar** [comment]
@MikeMcC399 Just forwarding a "Thanks" from a developer for this hint!

**Comment by MikeMcC399** [comment]
@dsarkar 

If the new advice given by Google (see https://github.com/corona-warn-app/cwa-app-android/issues/1541#issuecomment-788767684) is followed then the [getStatus()](https://developers.google.com/android/reference/com/google/android/gms/nearby/exposurenotification/ExposureNotificationClient#getStatus()) method should be used, which however only determines if the location setting needs to be enabled. Unlike [deviceSupportsLocationlessScanning()](https://developers.google.com/android/exposure-notifications/exposure-notifications-api#locationlessscanning) it does not determine whether the platform generally is dependent on location setting being enabled in order to use Bluetooth Low Energy.

The release notes https://developers.google.com/android/exposure-notifications/release-notes say:

"Deprecate deviceSupportsLocationlessScanning() in favor of the more informative getStatus() method"

so possibly this bug report / enhancement request should be deferred in favour of an enhancement to the related text strings which I posted in https://github.com/corona-warn-app/cwa-app-android/issues/2506.

**Comment by MikeMcC399** [comment]
If `deviceSupportsLocationlessScanning()` is deprecated, then perhaps simply suppressing the messages based on the Android version >= 11 would work? as in pseudo-code:

`    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) { suppress text }`

![Activate Location Setting EN DE](https://user-images.githubusercontent.com/66998419/109658933-6fa71180-7b67-11eb-8ed5-7c7aa8329a85.jpg)

**Comment by heinezen** [comment]
@MikeMcC399 

> If deviceSupportsLocationlessScanning() is deprecated, then perhaps simply suppressing the messages based on the Android version >= 11 would work? as in pseudo-code

According to the devs, this is not possible because some Android 11 devices still require location settings to be active.

However, there is a fix coming to the onboarding message in CWA 1.15 which will make the displayed message more clear.

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@heinezen 
> According to the devs, this is not possible because some Android 11 devices still require location settings to be active.

I only know about Android 11 devices prior to Android 11 Beta 3 or those Android 11 devices using Exposure Notifications System earlier than V1.7 requiring the location setting being enabled. (See https://developers.google.com/android/exposure-notifications/implementation-guide#locationless_scanning_in_android_11.) The beta period of Android 11 is now long in the past (and in fact Android 12 is now in beta) and the Android Google Exposure Notifications System is rolled out everywhere with V1.8.

I don't know that either of those cases need to be considered, however if the devs say that it isn't possible to implement the suggestion I made, then I go along with their evaluation.

Let's leave this issue open until the release of CWA 1.15 and hopefully close it after taking a look at the updated messages.

**Comment by MikeMcC399** [comment]
The release of CWA Android 1.15.1 shows the following messages during onboarding. They clarify that they do not apply to Android 11, so this issue can be closed.

![Activate Location Setting EN DE 1 15 1](https://user-images.githubusercontent.com/66998419/112622295-24f97c00-8e2b-11eb-902f-fc21b6c1557d.png)

**Comment by dsarkar** [comment]
@MikeMcC399 Also here thanks.
