### ISSUE TITLE
Corona Warn App crashes without error shortly after startup

### ISSUE THREAD

**Issue by Jonas164** [corona-warn-app/cwa-app-android#1542]
## Avoid duplicates
* [ x ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ x ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ x ] Bug is not already reported in another issue

## Describe the bug

My CWA on Android crashes every time I try to launch it. The splash screen with the CWA C-Logo appears for about 5 seconds before the app closes without presenting any error/feedback. During these 5 seconds, the phone becomes unresponsive (does not react to pressing of home/back button or even the hardware buttons.

## Expected behaviour

The app doesn't close after 5 seconds without error.

## Steps to reproduce the issue

Open the app and see it crash.

Im unsure on how to collect crash logs here.

## Technical details

- Mobile device: One Plus 6
- Android version: Android 10
- Oxygen OS version: 10.3.6

## Additional context

What I tried: Reinstalling the app, deleting all local data.

**Comment by MikeMcC399** [comment]
@Jonas164 
You didn't mention the version of the app. Is it 1.5.1?
Did reinstalling the app fix the issue or is the app still crashing? I assume it is still crashing, but wanted to be certain.

**Comment by Jonas164** [comment]
@MikeMcC399 
I have the latest app version 1.5.1.
Yes, app is still crashing. My tries did not fix the problem

**Comment by heinezen** [comment]
Hello @Jonas164 

Thanks for the feedback. Did the crashes appear after updating to version 1.5 or did they already happen before that?


Your bug might also be related to https://github.com/corona-warn-app/cwa-app-android/issues/1053 for which a workaround (https://github.com/corona-warn-app/cwa-app-android/issues/1053#issuecomment-690615473) exists. However, https://github.com/corona-warn-app/cwa-app-android/issues/1053 was mostly an issue on Huawei devices and not on OnePlus.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by Jonas164** [comment]
@heinezen I'm unsure if the crash happened before the update or after, I think it is like this for about 4 weeks now.

I might have figured out what causes this behaviour thanks to your link. When I clear my cache and local files, the app will start up just fine. When I lock my phone afterwards and let it idle for some minutes, cwa will once again start crashing on startup.
This must be an issue with my phones energy saving plan, even though I have it fully disabled for CWA. I will try to disable all the energy saving options I can find and hope for the best.

Wouldn't some error handling be a good idea in my case? It seems like just exiting the app when the database cant be decrypted isn't very intuitive. Maybe a warning to the user with advice on how to fix the problem?

**Comment by heinezen** [comment]
@Jonas164 If your issue is indeed the same as in https://github.com/corona-warn-app/cwa-app-android/issues/1053, then it might be fixed in the release 1.6. The issue was originally addressed in 1.5 and 1.5.1 (see https://github.com/corona-warn-app/cwa-app-android/issues/1053#issuecomment-714345887), but we are still receiving reports. However, we are still working on solution for this.

----
Corona-Warn-App Open Source Team

**Comment by Jonas164** [comment]
All right, I would close this then. Thanks alot for your work and stay healthy :)
