### ISSUE TITLE
Only 16 encounters in 14 days

### ISSUE THREAD

**Issue by lholl** [corona-warn-app/cwa-app-android#1555]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] I DONT KNOW: Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Describe the bug

I (and family members) only have exactly 16 encounters in 14 days, even though I went shopping and traveled by train. The risk assessment has been permanently active for over 14 days and I did not reset the app data.
![Screenshot_20201108-122001_Google Play services](https://user-images.githubusercontent.com/46422918/98463623-c6ee3400-21bc-11eb-99c4-f590ef0cf59a.jpg)

## Expected behaviour

A number of encounters of around 80-100 instead of 16.

## Steps to reproduce the issue

I found the 16 at (Android settings) -> Google -> Covid-19 notifications.

## Technical details

- Mobile device: Samsung Galaxy A50 / Samsung Galaxy S9
- Android version: 10

**Comment by MikeMcC399** [comment]
@lholl 

The number "16" is not the number of encounters. It is the number of times that the app has pulled the keys from the server and compared to what is stored on your phone. The value 16 is completely normal for Version 1.5.x of the app. That may increase for newer versions if they start checking more often.

There is a detailed explanation of the exposure check log on https://www.coronawarn.app/en/faq/#keys_matches (or https://www.coronawarn.app/de/faq/#keys_matches if you want the German text to go with your phone language).
