### ISSUE TITLE
Layout-Bug for TracingCard UI states resulting in not readable risk card/risk details fragment

### ISSUE THREAD

**Issue by vaubaehn** [corona-warn-app/cwa-app-android#1598]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Describe the bug
In the past days, CWA was fetching diagnosis keys from server in the background very soon after 0:00 UTC. Because the new DKs hadn't been deployed yet at that point in time, CWA was checking with old data from the day before... But this is a seperate issue (#1691).
To make sure to have a download of 'fresh' DKs, I deactivated Exposure Logging last night before sleep.
In the morning, I opened CWA, navigated to the fragment that allows for enabling Exposure Logging, enabled logging again, and then immediately navigated back to the home screen. Instead of a risk card showing "Daten werden heruntergeladen..." there was only a blank/white risk card. Tapping and holding the risk card switched the background of the card to light grey, and a white text "Daten werden heruntergeladen.." was visible. After releasing the finger, CWA switched to risk details screen, showing only a blank/white screen. Navigating back to the main screen showed again a white risk card. After the download was finished, the risk card updated automatically to a green card with white text "Prüfung..." (shouldn't the background be dark grey either?). After the DKs had been provided to ENF, the risk card updated automatically to the green card "Low Risk".
I guess, the background color was not set correctly, while the (white) text was visible.
I made some screenshots... see below.

## Expected behaviour

The risk card "Daten werden heruntergeladen..." and the risk details fragment should have a dark grey background, like seen in @d4rken 's screenshots #1486 . According to #1486 , the risk card should probably also have a dark grey background while "Prüfing läuft...".

## Steps to reproduce the issue

1. Deactivate Exposure Logging before 0:00 UTC.
2. After 0:00 UTC, open CWA, navigate to the fragment where you are able to activate Exposure logging.
3. Enable Exposure Logging. Immediately navigate back to the main screen.
4. See error:
![Screenshot_2020-11-13-08-00-27](https://user-images.githubusercontent.com/68376758/99075731-4499b180-25ba-11eb-81ef-fe78feeefe0d.jpg)
5. Tap and hold risk card:
![Screenshot_2020-11-13-08-00-51](https://user-images.githubusercontent.com/68376758/99075877-7e6ab800-25ba-11eb-8275-bd8c6713a303.jpg)
6. release finger, see CWA navigating to risk details:
![Screenshot_2020-11-13-08-00-56](https://user-images.githubusercontent.com/68376758/99075951-9e01e080-25ba-11eb-9cc2-a8b98a92eaee.jpg)
7. navigate back to main screen, wait for refresh of risk card:
![Screenshot_2020-11-13-08-01-15](https://user-images.githubusercontent.com/68376758/99076029-c7227100-25ba-11eb-9649-b600edfa5bd6.jpg)
8. wait for refresh of risk card after DKs had been provided to ENF:
![Screenshot_2020-11-13-08-30-51](https://user-images.githubusercontent.com/68376758/99076302-326c4300-25bb-11eb-8b29-1f941a8ce172.jpg)

## Technical details

- Mobile device: LG-G4
- Android version: 6,1
- CWA; 1.6.0
- ENF: 18204215000

## Possible Fix

Make sure that for UI states "Daten werden heruntergeladen..." and "Prüfung läuft..:" the correct background color is set when navigating from any other fragment to main screen.

edit:

~~Probably the bug is here:
[it's probably here](https://github.com/corona-warn-app/cwa-app-android/blob/74b3f37cfe215a8e1e49c484671f5e0881c37f9a/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/tracing/card/TracingCardState.kt#L291-L298)~~

~~Looks like `R.color.card_unknown` has background color white, or `RiskLevelConstants` should be defined for "Daten werden heruntergeladen..." and "Prüfung läuft...".~~

~~edit2: Would maybe make sense to define `RiskLevelConstants` for "Daten werden heruntergeladen..." und "Prüfung läuft...": Looks like while download `RiskLevelConstants` is unknown, and while "Prüfung läuft..." `RiskLevelConstants` is already "Low risk".~~

~~edit3: Digging some more, for me seems that `R.color.card_unknown` should point to color scheme `<color name="colorSemanticNeutralRisk">#5D6E80</color>`, but obviously `<color name="colorSemanticUnknownRisk">#FFFFFF</color>` is used:~~

~~[don't look](
https://github.com/corona-warn-app/cwa-app-android/blob/74b3f37cfe215a8e1e49c484671f5e0881c37f9a/Corona-Warn-App/src/main/res/values/colors.xml#L33-L36)~~

~~See also here for definition of `RiskLevelConstants`:~~
~~[save your time not looking here](https://github.com/corona-warn-app/cwa-app-android/blob/74b3f37cfe215a8e1e49c484671f5e0881c37f9a/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/RiskLevelConstants.kt#L3-L11 )~~

## Additional context

Feel free to hide above screenshots for better readability of this issue, after mirroring to Jira.

---
Related PR https://github.com/corona-warn-app/cwa-app-android/pull/1751. 
Overall PR: https://github.com/corona-warn-app/cwa-app-android/pull/1699 
---
Internal Tracking ID: EXPOSUREAPP-3834

**Comment by vaubaehn** [comment]
The other day I was deactivating exposure logging again, and then in the next morning re-activating it from insinde Google's COVID-19-Notifications page. This time the risk card had the expected dark grey background color when downloading diagnosis keys:

![Screenshot_2020-11-15-02-11-58](https://user-images.githubusercontent.com/68376758/99241473-35a34100-27fe-11eb-9f09-28513469411a.jpg)

This makes me think, that there is a problem with inhereting the color schemes from one layout to the other, rather then having a problem with defining the right color scheme for the right UI state.

So, maybe it's worth to have another look into https://github.com/corona-warn-app/cwa-app-android/blob/main/Corona-Warn-App/src/main/res/layout/include_risk_card_content.xml

**Comment by vaubaehn** [comment]
Hi @SamuraiKek , I found your PR #1615 targetted for 1.8.0. Looks like, as a side effect the bug reported here could be solved. However, will there be a chance to fix #1598 before 1.8.0? According to Google Play Store reviews, there is a number of users left behind a bit irritated of having a white risk card/white risk details fragment.
Kind regards, v.

**Comment by SamuraiKek** [comment]
> Hi @SamuraiKek , I found your PR #1615 targetted for 1.8.0. Looks like, as a side effect the bug reported here could be solved. However, will there be a chance to fix #1598 before 1.8.0? According to Google Play Store reviews, there is a number of users left behind a bit irritated of having a white risk card/white risk details fragment.
> Kind regards, v.

Hi @vaubaehn, yes, it looks like my PR could potentially fix this issue as well, although I don't believe there's going to be a fix for it before 1.8.0.

**Comment by vaubaehn** [comment]
@SamuraiKek 
Hi Alex, thanks for your reply. Ok, then we'll wait for 1.8.0. Likely there is an easy work around for affected users with a (stale?) white risk card/risk details fragment, i.e. simply navigating to a different fragment and back. Will try out tomorrow if I won't forget to disable exposure logging tonight :wink: 
Hope refactoring will be easy going for you - looks like a quite long list in #1615 :)
Best wishes, v.

**Comment by heinezen** [comment]
Hey @vaubaehn ,

I've mirrored this issue to Jira (ticket ID: EXPOSUREAPP-3834) now so that it gets properly tracked. We will see what we can do about it before the next release. As always, we'll notify you here when a fix is available.

Thanks for the report,
CH

----
Corona-Warn-App Open Source Team

**Comment by vaubaehn** [comment]
Some additional information:
I tested the issue some more times. By testing I found out, that the risk details fragment (the whole screen) does not have white text on white background, but seems to be completely empty. This is, because there was also no element for closing the screen to navigate back to main screen (I tried to close "blindly" by tapping into the left up corner with no effect). Also, there is no text for "Verhaltensregeln" visible which should be displayed in any case. 
Additionally, once I was able to have a different navigation back from the "tracing settings fragment" to the main screen (I accidently clicked something else, but forgot what it was...).  Back on the main screen, data were download ("Daten werden heruntergeladen...") with completely white risk card, but when I tapped into the risk card, I was navigated to the risk details fragment, now displaying the "Risiko-Ermittlung gestoppt" information and below the "Verhaltensregeln". After the download finished, the risk details fragment automatically changed to the "Prüfung läuft..." elements.
So, looks like there are a bunch of underlying problems in this issue. But they might probably WIP already?

**Comment by d4rken** [comment]
Thanks for the detailed description.

> So, looks like there are a bunch of underlying problems in this issue. But they might probably WIP already?

The risk card has changed over the various releases, getting new states with each, making the state matrix more complex with each step. I'm working on a complete overhaul:

* Step 1 is simplifying the states, in progress here #1751. I've addressed the bugs you found in that PR.
* Step 2 will be to split up the cards, currently it's one layout that has different visibility states for each element. The idea is to use a list. Convert each card (red,green, white, white) to their own layouts and then exchange the whole card. This will also make changes to specific cards sideeffect free, and converting everything to list items in the home screen, paves the way for easier addition of new features/card in future releases.

**Comment by dsarkar** [comment]
Related PR https://github.com/corona-warn-app/cwa-app-android/pull/1751. 

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Overall PR: https://github.com/corona-warn-app/cwa-app-android/pull/1699

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Hi @vaubaehn and community, Thank you for your contributions. This issue has been fixed. We will close this ticket now. Many thanks, best regards. DS

---
Corona-Warn-App Open Source Team
