### ISSUE TITLE
"Dokument mit QR-Code" screen not scrollable

### ISSUE THREAD

**Issue by real-or-random** [corona-warn-app/cwa-app-android#1607]
## Describe the bug

Lower text on QR code screen not readable because it's off bounds
![Screenshot](https://user-images.githubusercontent.com/1071625/99156763-e6f18c00-26c3-11eb-8fec-6e7f6404c951.jpeg)

## Expected behaviour

Scrolling works

## Steps to reproduce the issue

1. "Informieren und Helfen"
2. "Weiter"
3. "Dokument mit QR-Code"
4. "Erlauben"
5. Try to scroll

## Technical details

- Mobile device: Huawei P10
- Android version: 9

---
Internal Tracking ID:  EXPOSUREAPP-3436

**Comment by DerVogel2020** [comment]
Same on Samsung A5 2017 with Android 8.0.
I can read one line more, so it seems it depends in the devices screen how much of the text is displayed.
It should be scrollable if the screen is too small.

**Comment by real-or-random** [comment]
Code location: https://github.com/corona-warn-app/cwa-app-android/blob/74b3f37cfe215a8e1e49c484671f5e0881c37f9a/Corona-Warn-App/src/main/res/layout/fragment_submission_qr_code_info.xml#L25

**Comment by dsarkar** [comment]
Dear @real-or-random and @DerVogel2020,

Thank you for your contributions.

There is a ticket for the bug (Internal Tracking ID: EXPOSUREAPP-3436) in the internal Jira system. The developers will look into this issue. Any further developments will be notified here in this Github issue.

Best wishes,
DS

Corona-Warn-App Open Source Team

**Comment by PhilippNowak96** [comment]
Opened a PR which fixes this issue. The ScrollView was not constraint against the button and therefore it had enough space to not scroll.

**Comment by MikeMcC399** [comment]
@PhilippNowak96 
>Opened a PR which fixes this issue. The ScrollView was not constraint against the button and therefore it had enough space to not scroll.

It looks like the PR you mentioned is https://github.com/corona-warn-app/cwa-app-android/pull/1662.

**Comment by DerVogel2020** [comment]
I just updated to 1.7.1 and the error still occurs.![Screenshot_20201127-191025_Corona-Warn.jpg](https://user-images.githubusercontent.com/65366950/100475861-72b3e100-30e4-11eb-8a49-c5c229499d9c.jpg)

**Comment by real-or-random** [comment]
@DerVogel2020  I think that's expected. The fix is not in the 1.7 branch (but in the 1.8 branch), see the fixing commit.

**Comment by DerVogel2020** [comment]
Okay.

**Comment by dsarkar** [comment]
@real-or-random, @DerVogel2020, Should be fixed now. Once you got updated to CWA 1.9.1, we would appreciate your feedback. Thanks. DS

---
Corona-Warn-App Open Source Team

**Comment by real-or-random** [comment]
Ok, it's not as I expected because the entire view has been replaced... But yes, it's fixed with 1.9.1.  :+1:

**Comment by DerVogel2020** [comment]
Resolved for me.

**Comment by dsarkar** [comment]
Hi @DerVogel2020, @real-or-random, thanks for the feedback. Best, DS

---
Corona-Warn-App Open Source Team
