### ISSUE TITLE
minSdkVersion of cwa

### ISSUE THREAD

**Issue by herionhonig** [corona-warn-app/cwa-app-android#165]
## Your Question

* Documentation File: 
Google test app
https://github.com/google/exposure-notifications-android/blob/master/app/build.gradle
cwa (SAP/Telekom)
https://github.com/corona-warn-app/cwa-app-android/blob/master/Corona-Warn-App/build.gradle

* Line / Paragraph:

* Question:
In the Google test app on github the minSdkVersion is 21. This refers to Lollipop.

In your source minSdkVersion 23 (Marshmallow) is used.

The market share of Lollipop is 8.5 % and Marshmallow is 10.7%
Why don't you follow the recommendation from Google?

**Comment by tkowark** [comment]
Since this question is very specific to the android app, we moved it from the documentation repo.

**Comment by marcmuschko** [comment]
Dear @herionhonig,

thanks for reaching out! You are correct, a minimum API level of 21+ was required, however this has changed. Please have a look at the official documentation for the Exposure Notification API which can be found here: [https://static.googleusercontent.com/media/www.google.com/en//covid19/exposurenotifications/pdfs/Android-Exposure-Notification-API-documentation-v1.3.2.pdf](url)

In the revision history, the min API level was raised from 21 to 23, therefore we had to adjust our configuration as well. Hope this answers your question, please close your issue if it does.

Thanks and best,
Marc
