### ISSUE TITLE
"Risiko-Ermittlung war für 13 der letzten 14 Tage aktiv"

### ISSUE THREAD

**Issue by flowl** [corona-warn-app/cwa-app-android#1679]
I have activated the app since its release but since a few weeks there is always one day missing.
I never stopped the app for a single day.

I can't tell whether data is lost or this is only a visual bug.

Today: "Risiko-Ermittlung war für 13 der letzten 14 Tage aktiv"
Yesterday: "Risiko-Ermittlung war für 13 der letzten 14 Tage aktiv"
The day before yesterday: "Risiko-Ermittlung war für 13 der letzten 14 Tage aktiv"
...

App version 1.6.1
Android version most current compatible with Huawei P30 Pro
It says EMUI
Model VOG-L29
Build 10.1.0.161
Android Version 10
Kernel 4.14.116

**Comment by dsarkar** [comment]
Dear @flowl,

Thank you for your report. 
Could you please figure out the actual Android version on your phone? 
Also, could you please upload the ENF file and upload a screenshot showing the notification of active days? 

Thank you.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by flowl** [comment]
It says EMUI
Model VOG-L29
Build 10.1.0.161
Android Version 10
Kernel 4.14.116

I don't know how obtain an ENF file.
I can make an export called `all-exposure-checks.json`. The screen of that file xport function shows a check on every day between 1am and 4am with one exception at 2pm, no day off, no day missing.

**Comment by dsarkar** [comment]
Hi @flowl. Thanks for your answer. Yes, please upload  all-exposure-checks.json (add extension .txt). Also upload screenshots of several days, please. Thanks. Best, DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Dear @flowl,

We have now CWA version 1.7.1. Does your problem persist? Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by flowl** [comment]
@dsarkar The line with "X von 14 Tagen aktiv" has been removed completely so the problem is not reproducible anymore!

Thanks for the heads up.
Best

**Comment by MikeMcC399** [comment]
@flowl 
> The line with "X von 14 Tagen aktiv" has been removed completely so the problem is not reproducible anymore!

Does it now say "Risiko-Ermittlung dauerhaft aktiv" instead? If so, then your problem is gone.

If you recently installed, reset the app or had "Risiko-Ermittlung gestoppt" for some time, it would still include a line like "Risiko-Ermittlung war für n der letzten 14 Tage aktiv".

**Comment by flowl** [comment]
> Does it now say "Risiko-Ermittlung dauerhaft aktiv" instead? If so, then your problem is gone.

Yes it does :-)

**Comment by dsarkar** [comment]
Dear @flowl, @MikeMcC399 thanks for the feedback and contributions, respectively. We suggest that you can close this issue now. However, you might want to monitor this issue on iOS https://github.com/corona-warn-app/cwa-app-ios/issues/1127, which might be related to the issue you reported.  Best wishes,
DS

---
Corona-Warn-App Open Source Team
