### ISSUE TITLE
Update gradle wrapper from 6.1.1 to 6.7

### ISSUE THREAD

**Issue by deeprobin** [corona-warn-app/cwa-app-android#1687]
The title says it all :)

---
Internal Tracking ID: EXPOSUREAPP-4028

**Comment by heinezen** [comment]
Hey @deeprobin ,

Thank you for the suggestion. I have forwarded it to our internal Jira (ticket ID: EXPOSUREAPP-4028) where it will be discussed by the dev team.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
PR https://github.com/corona-warn-app/cwa-app-android/pull/1992

**Comment by MikeMcC399** [comment]
The PR "Update gradle wrapper (EXPOSUREAPP-4028)" https://github.com/corona-warn-app/cwa-app-android/pull/1992 is already showing in [v1.11.0-RC1](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.11.0-RC1).

**Comment by MikeMcC399** [comment]
https://github.com/corona-warn-app/cwa-app-android/blob/main/gradle/wrapper/gradle-wrapper.properties is now showing gradle version 6.7.1 so I suggest that this issue can be closed.

https://github.com/corona-warn-app/cwa-app-android/blob/a204c6ada1d05ba26ca54c341e69f4ff416f2ca8/gradle/wrapper/gradle-wrapper.properties#L6

CWA 1.11.0 was released on Jan 28, 2021 and the release/1.11.x branch was merged into the main branch of the repository on Jan 29, 2021 (see PR https://github.com/corona-warn-app/cwa-app-android/pull/2234).

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks.
@deeprobin Thanks for reporting. Please close this issue.
