### ISSUE TITLE
App erroneously gives the all-clear

### ISSUE THREAD

**Issue by J-0e** [corona-warn-app/cwa-app-android#1688]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Describe the bug

App gives all-clear with a pop-up notification ("low risk"!) way too early ("9 days since last encounter") and in contrast to in-app information ("increased risk"). (for details, see ## Additional context)

## Expected behaviour

Either no pop-up and the risk information counting up towards 14 days before the risk level decreases again.
Or a different (lower) risk level after the pop-up message (and then, perhaps, some clarification about the numbers; why an increased risk encounter supposedly 9 days ago was not important any longer) 

## Steps to reproduce the issue

No, idea, sorry. I did not think about bug reporting when I received the message.

## Technical details

- Mobile device: Motorola G7 Power
- Android version: 10

## Possible Fix

(see ## Expected behaviour)

## Additional context

I received a push message notifying me of an increased risk warning (my first one) Saturday morning. After opening the app, I noticed it was due to 1 exposure 8 days earlier ("8 days since the last encounter"). The next day, I checked the app and was welcomed with a popup message telling me that it had been 14 days or more since my last risk exposure (high risk? I do not recall the exact wording). The app informed me that the risk was low again. Unless I had symptoms, then I should go see a doctor. In the app, however, the risk state has not changed (still red and increased).

---
Internal Tracking ID: EXPOSUREAPP-3900

**Comment by heinezen** [comment]
Hello @J-0e ,

Thanks for the bug report. We have added your report to our internal Jira (ticket ID: EXPOSUREAPP-3900) and forwarded your information to the developers. The behaviour is now investigated. We will report back on Github in this issue, once we have more information.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
For documentation purposes: This issue relates to https://github.com/corona-warn-app/cwa-app-android/issues/1582

Regards,
DS

---
Corona-Warn-App Open Source Team

**Comment by J-0e** [comment]
![Screenshot_20201124-074957](https://user-images.githubusercontent.com/64587719/100072880-17ac9080-2e3d-11eb-9ac3-36692371d34b.png)
I got the same message today, see screenshot. At first, the warning message behind the prompt was green (presumably low risk) and changed to red while the prompt was active. 

Concerning reproduction: when I closed the prompt, the app was busy with the daily update.

**Comment by thomasaugsten** [comment]
We aware of this error because the ENF of Google returns for a short time an empty result this will be fixed in the v.1.8 in the beginning of december

**Comment by heinezen** [comment]
Hey @J-0e , this should be fixed in the latest update to CWA version 1.9. Please notify us, if you see this kind of message again. Thanks.

CH

----
Corona-Warn-App Open Source Team
