### ISSUE TITLE
Potentially confusing prompts when enabling Exposure Notifications

### ISSUE THREAD

**Issue by kbobrowski** [corona-warn-app/cwa-app-android#1721]
## Current Implementation

User may face unexpected / confusing questions about Location permissions when turning on Exposure Notification. Just a heads up - I was not able to test it with Corona Warn App yet but the same happens on both Latvian and Italian apps which are Exposure Notification-based, it seems to be triggered by Google Services and not by country-specific apps.

![en_permissions](https://user-images.githubusercontent.com/28542783/83974351-90ab4080-a90e-11ea-94aa-935fc13296b1.png)

## Suggested Enhancement

User may get a heads-up from Corona Warn App that he has to agree to turn on Location service, and can disagree with "Improving location accuracy". Not sure why the last prompt appears, perhaps it will be patched by Google since it is not necessary for the app to work properly. I was able to reproduce 3 prompts on Android 6 but on Android 10 only first 2 prompts appear.

French app gives following heads-up to the user (it has to get standard "Location" access though, but from user perspective it does not differ much from prompts above):

> Important message: Attention, Android will ask you for access to this phone's location. StopCovid will only use Bluetooth detection of nearby phones, and never location data

## Expected Benefits

May be possible to increase number of users agreeing to first two prompts (which is necessary for the app to work), and assure users that sharing location data with Google is not necessary and they can safely disagree without decreasing app functionality.

---
Internal Tracking ID: EXPOSUREAPP-2890

**Comment by MikeMcC399** [comment]
This issue is related to "Misleading / incorrect instruction to "Allow location access" during onboarding" https://github.com/corona-warn-app/cwa-app-android/issues/1541 where I brought up the topic that there are static texts stating that location must be enabled. If #1541 is resolved, then the information should become dynamic and correspond to the current settings and needs of the app, depending on Android version.

**Comment by MikeMcC399** [comment]
Hi Kamil @kbobrowski !

I'm not sure that the app can do much more than it is already doing in current versions like 1.14.3.

The app outputs the following informational texts during onboarding:

![Activate Location Setting EN DE](https://user-images.githubusercontent.com/66998419/110965979-156f3300-8355-11eb-8156-1017ff00c7d1.jpg)

The pop-up "Turn on the device location setting" will be shown if the location setting is disabled in Android settings during onboarding and if the Android version is 10 or less. This message is output by the Google Exposure Notifications System, and the app doesn't have control of this message.

The pop-up "Improve location accuracy?" I'm seeing also on Android 8 (I don't have a physical Android 6 device available to test on.) This pop-up isn't shown by Android 10. That corresponds with your findings. In any case it is a function of the Android system, and again the app has no control of the message.


Do you think your enhancement request still needs to stay open? The location issue doesn't seem to be causing confusion these days. At least it is not coming up as new issues here on GitHib.

**Comment by MikeMcC399** [comment]
I suggest closing this issue. CWA 1.15.1 shows the following messages during onboarding, which are now much clearer.

![Activate Location Setting EN DE 1 15 1](https://user-images.githubusercontent.com/66998419/112681298-c950e200-8e6e-11eb-9807-e47c0cc9da3f.png)

The other messages are from the operating system and the CWA app has no control over them.

**Comment by dsarkar** [comment]
Hi @kbobrowski, see https://github.com/corona-warn-app/cwa-app-android/issues/1721#issuecomment-808451893. We suggest closing this issue. Best, wishes, DS

---
Corona-Warn-App Open Source Team
