### ISSUE TITLE
Exposing secret keys from Android KeyStore is not possible

### ISSUE THREAD

**Issue by aschattney** [corona-warn-app/cwa-app-android#173]
de.rki.coronawarnapp.util.security.SecurityHelper:64

```kotlin
    /**
     * Retrieves the Master Key from the Android KeyStore to use in SQLCipher
     */
    fun getDBPassword() = keyStore
        .getKey(masterKeyAlias, null)
        .toString()
        .toCharArray()
```

This doesn't work because the content of the secret key is [not exposed](https://android.googlesource.com/platform/frameworks/base/+/master/keystore/java/android/security/keystore/AndroidKeyStoreKey.java).

The current return value of the function is:
```
android.security.keystore.AndroidKeyStoreSecretKey@{hash}
```

**Comment by jakobmoellersap** [comment]
Please confirm if #189 solved the issue or you think there is more work to be done here.

**Comment by aschattney** [comment]
Hey @jakobmoellersap

#179 does not fix the problem because the `toString()` method is called on the `SecretKey`. So the result of the `getDBPassword()` method is still the same. The content of the `SecretKey`s generated by the Android KeyStore can not be retrieved.

The [architecture documentation](https://github.com/corona-warn-app/cwa-app-android/blob/master/docs/architecture-overview.md#database) for the Android app currently states the following:

> SQLCipher is used to encrypt the database. Thus a key is initialised for the database access the first time we access it. The AppDatabase stores the key inside the shared preferences, which are themselves encrypted and bound to the master key from the android key store. On application reset (in the settings), the complete database is reinitialised. The password is randomly generated and is not used outside the storage package for accessing the data.

I implemented a _suggestion_ based on that description in #224.

**Comment by jakobmoellersap** [comment]
Resolved thanks to your contribution @aschattney 👍
