### ISSUE TITLE
"Risiko-Ermittlung dauerhaft aktiv" despite BlueTooth being disabled

### ISSUE THREAD

**Issue by icrf2000** [corona-warn-app/cwa-app-android#1734]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Describe the bug

This issue report is the same as #920. You closed it, pretending the issue was fixed. It isn't, I am using 1.6.1 and the broken behavior is the same as before. I would reopen #920 if I could, but cannot.

## Technical details

- Mobile device:
- Android version:

**Comment by heinezen** [comment]
Hey @icrf2000 

Thanks for the follow-up. We have reopened https://github.com/corona-warn-app/cwa-app-android/issues/920 and forwarded the feedback to the developers.

I'll close this issue, so that the discussion can continue in https://github.com/corona-warn-app/cwa-app-android/issues/920. 

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by icrf2000** [comment]
I have 1.7.1 in the meantime. The issue still exists. Here how it looks after having Bluetooth disabled for a bit more than 24 hours. It says "BLUETOOTH DEAKTIVIERT", shows the red alert in the notification bar, but nevertheless, pretends "Risiko-Ermittlung dauerhaft aktiv":

![Screenshot_20201129-084714_Corona-Warn](https://user-images.githubusercontent.com/11777822/100588776-8b91e180-32f2-11eb-851d-09bbd6facf02.jpg)

**Comment by icrf2000** [comment]
commented wrong issue, should go to 920. Done there and deleted comment here.

**Comment by dsarkar** [comment]
Dear @icrf2000,

Thanks for reporting, see my answer here https://github.com/corona-warn-app/cwa-app-android/issues/920#issuecomment-735655990, please.

Best wishes,
DS

---
Corona-Warn-App Open Source Team
