### ISSUE TITLE
Cannot delete test results

### ISSUE THREAD

**Issue by flatterndeAmsel** [corona-warn-app/cwa-app-android#1746]
## Describe the bug

I cannot delete the Covid-test.

I did use the CWA to get a Test. So far all went well. The Doctor did test me. The Result was send to the App (negative).

But then I did NOT delete the Test.

Weeks later:

Now  the Result cannot be ?requested?aksed?trafered?(sorry for my bad english) from the server.
The CWA displays "Datenabruf \n Das Ergebnis wird aktualisiert"

So I cannot use the App for further tests.

## Expected behaviour
 * Display Test.
 * Display Errormessage?

## Steps to reproduce the issue
Get a test, and Wait too long.

Or feed the App with some dummy Test who is dated too far in the past. And is not provided by the Server.(anymore?)

## Technical details

- Mobile device: XIAOMI Redmi note 4
- Android version: LineageOS Android Version 9

## Possible Fix
 * Ignore Test which are too old.
 * Give an option to delete too old tests.
 * Reset APP?

**Comment by flatterndeAmsel** [comment]
Duplicate of 

https://github.com/corona-warn-app/cwa-documentation/issues/400

#1084 Can’t access test results b/c CWA is stuck at “Datenabruf”

**Comment by dsarkar** [comment]
Dear @flatterndeAmsel,

Thanks for contributing. The problem regarding old test results should have been resolved with CWA  version 1.7.1. Can you confirm you are using CWA version 1.7.1.

Many thanks.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by flatterndeAmsel** [comment]
My CWA is Version 1.6.1

I'll write if the new version fixes it or no .
But I have to wait for the Playstore to update the App.

Thanks for answering, stay save.

**Comment by dsarkar** [comment]
Duplicate of https://github.com/corona-warn-app/cwa-app-android/issues/1084

**Comment by flatterndeAmsel** [comment]
The App was updated.
And
Version 1.7.1 did fix this Problem.

**Comment by dsarkar** [comment]
@flatterndeAmsel,

Thanks for the feedback. Very much appreciated. I will forward this to the developrs. 

Best wishes,
DS

---
Corona-Warn-App Open Source Team
