### ISSUE TITLE
Zero number of keys on Android 11 emulator

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#1752]
## Avoid duplicates 
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Describe the bug
Google exposure check log shows Number of keys 0 on an Android 11 emulated device.

## Expected behaviour

A non-zero number (305483) is displayed on an Android 8 physical mobile phone. The emulator should also display this number or a similar number, because it is the number of keys retrieved from the server.

### Preparation

In Android Virtual Device Manager of Android Studio 4.1.3:

1. Create Virtual Device
2. Select Pixel 3a with Play Store
3. Select Release Name R, API Level 30, ABI x86, Target Android 11.0 (Google Play)
4. Start emulator and wait for main Android screen to display
5. Wait 15 minutes for Google background updates to progress
6. Check Settings > Google
7. COVID-19 SUPPORT should appear in list, if not wait a bit longer
8. Tap on COVID-19 Exposure Notifications and make a note of the Exposure Notifications Version number e.g. v1.8 (213016000)
9. Open Google Play Store and Sign in
10. Tap I agree
11. Disable Backup to Google Drive
12. Tap ACCEPT
13. In Google Play Store search for corona-warn-app and Tap Install
14. Wait for installation to complete

### App Usage

1. Open Corona-Warn-App
2. Tap "LET'S GET STARTED"
3. Tap "NEXT"
4. Tap "ACTIVATE EXPOSURE LOGGING" and "Turn on"
5. Tap "NEXT"
6. Tap "NEXT"
7. Tap "DO NOT SHARE"
8. Dismiss pop-up with "OK" (may appear before or after ALLOW)
9. Tap "DO NOT ALLOW" in "Allow prioritized background activity" and OK
10. Low Risk card is now displayed with Updated: Today, (current time)
11. Close CWA

### Google Log

1. Settings > Google > COVID-19 Exposure Notifications
2. Tap three-dot icon > Exposure checks, tap timestamp
4. Note: Number of keys 0 in log display

---
![Number of keys 0](https://user-images.githubusercontent.com/66998419/100476568-35505300-30e6-11eb-9797-c2dd2a4db4c4.jpg)

## Technical details

- Mobile device: Google Pixel 3a emulator
- Android version: 11
- ENS version: ~~18204217000~~ v1.8 (213016000)
- CWA version: ~~1.7.1~~ 2.7.1

## Additional context

I have observed this behavior previously but not reported it, because an emulated device is not a true use-case. Since other users have occasionally also reported a problem with number of keys = 0 I wanted to drop this as a reproducible base-case which might warrant debug investigation.

---
Internal Tracking ID:  [EXPOSUREAPP-4130](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4130)

**Comment by tomjschwanke** [comment]
I have seen this bug in earlier versions of GMS / Google Play Services. For some reason the key count also showed the match count. I'm not sure what GMS versions Google ships with the Emulator, could you make sure that Google Play Services are the newest version (it might not auto-update immediately)?

**Comment by MikeMcC399** [comment]
@tomjschwanke 
> I have seen this bug in earlier versions of GMS / Google Play Services. For some reason the key count also showed the match count. I'm not sure what GMS versions Google ships with the Emulator, could you make sure that Google Play Services are the newest version (it might not auto-update immediately)?

You are completely right that there was a display bug in early versions of Google Play services / Exposure Notification System (ENS). That bug was fixed in 20.26.12 (see https://github.com/corona-warn-app/cwa-app-android/issues/744#issuecomment-651428585).

The version of ENS that I tested with was 18204217000, which corresponds to 20.42.17 of Google Play services. When I set up the emulator I waited 10 minutes for Google Play services to auto-update.

It may be a timing issue in the emulator, since the emulator runs slower than a physical device.

**Comment by dsarkar** [comment]
Hi @MikeMcC399,

Thanks again for your contributions. We have created a ticket for the bug (Internal Tracking ID: EXPOSUREAPP-4130) in the internal ticket system. Any further developments will be notified here in this Github issue.
  
Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
I assume that since this problem was reported on a standard Android emulator that it should be reproducible.

In any case here is a filtered output from logcat:

```
I/ExposureNotification: [MatchingTracer] Starting matching job. [CONTEXT service_id=236 ]
I/ExposureNotification: [MatchingTracer] Native pre-filter started. [CONTEXT service_id=236 ]
W/ExposureNotificationJni: Invalid input for initNative, scan records is empty
I/ExposureNotification: MatchingJni get native ptr 0 [CONTEXT service_id=236 ]
W/ExposureNotificationJni: Invalid input for matchingNative
I/ExposureNotification: MatchingJni get nullable key set from native. [CONTEXT service_id=236 ]
W/ExposureNotificationJni: Invalid input for lastProcessedKeyCount
W/ExposureNotificationJni: Invalid input for lastProcessedResult
E/ExposureNotification: [MatchingTracer] Failed because of native error UNKNOWN_MATCHING_RESULT [CONTEXT service_id=236 ]
W/ExposureNotificationJni: Invalid input for releaseNative
I/ExposureNotification: [MatchingTracer] Persisting matching request record. [CONTEXT service_id=236 ]
I/ExposureNotification: [MatchingTracer] Matching job complete. Run time=0.092s. Matches not found. [CONTEXT service_id=236 ]
I/ExposureNotification: [MatchingTracer] Sending exposure status update with no new exposures to client. [CONTEXT service_id=236 ]
I/ExposureNotification: [MatchingTracer] Successfully removed request. Matching job complete. [CONTEXT service_id=236 ]
```

**Comment by ndegendogo** [comment]
@MikeMcC399 does your emulator environment have RPI stored (or some kind of equivalent)?
Can it be that the matching algorithm of this ENS version has an upfront optimisation, and  short-cuts if there are no RPI for matching?

*(... just speculating ... because if this is true then 0 keys could be a valuable hint that something is seriously wrong with a device ...)*

**Comment by MikeMcC399** [comment]
@ndegendogo 
> does your emulator environment have RPI stored (or some kind of equivalent)?

It's a standard emulator which is part of the Android Studio 4.1.1 integrated development environment for building Android apps.

I don't really know what is going on inside ENS as I haven't rooted the emulator. I expected it to be simulating sending out Rolling Proximity Identifiers (RPIs) and storing them. It can't receive any RPIs though, because the Bluetooth interface is only simulated. It could be taking a short-cut if there an no received RPIs stored. I can only guess since this is closed-source.

**Comment by ndegendogo** [comment]
> can't receive any RPIs though, because the Bluetooth interface is only simulated ... can only guess since this is closed-source

@MikeMcC399 yes, sure. I was just trying to 'guess' any meaning into your log entries ...

`I/ExposureNotification: [MatchingTracer] Starting matching job. `
`I/ExposureNotification: [MatchingTracer] Native pre-filter started. `
`W/ExposureNotificationJni: Invalid input for initNative, scan records is empty`

**Comment by heinezen** [comment]
@MikeMcC399 Can this be reproduced with ENFv2? We cannot reproduce the issue since January.

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
@MikeMcC399 Thank you for testing again. We'll leave this open then.

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
Abandoning this issue, since it was reported 9 months ago already without any concrete feedback so far.

The issue does not affect real devices in use, only emulators.

**Comment by vaubaehn** [comment]
I think, @ndegendogo 's analysis was correct:

> > can't receive any RPIs though, because the Bluetooth interface is only simulated ... can only guess since this is closed-source
> 
> @MikeMcC399 yes, sure. I was just trying to 'guess' any meaning into your log entries ...
> 
> `I/ExposureNotification: [MatchingTracer] Starting matching job. `
> `I/ExposureNotification: [MatchingTracer] Native pre-filter started. `
> `W/ExposureNotificationJni: Invalid input for initNative, scan records is empty`

The issue https://github.com/cocoa-mhlw/cocoa/issues/202 has a pointer to the corresponding code in ENS:
https://github.com/google/exposure-notifications-internals/blob/aaada6ce5cad0ea1493930591557f8053ef4f113/exposurenotification/src/main/cpp/matchingjni.cc#L36

This would mean, that if no RPIs had been received/stored for any reason (and this is quite obvious for an emulator without Bluetooth), ENS does not match TEKs with RPIs. In result, number of (checked) keys and matches is `0`, which is then a correct result displayed.

**Comment by MikeMcC399** [comment]
@vaubaehn 
The Japanese characters scared me off trying to read the related issue. You were braver!

It seems you and @ndegendogo were right about the root cause, so I'm happy to have closed this issue off.
