### ISSUE TITLE
Multiple typos "Please delete the text" instead of "Please delete the test"

### ISSUE THREAD

**Issue by tfar** [corona-warn-app/cwa-app-android#1753]
https://github.com/corona-warn-app/cwa-app-android/blob/99b19dc6f64e2236d203d7a9ecaede6ace1130e4/Corona-Warn-App/src/main/res/values-en/strings.xml#L1137

https://github.com/corona-warn-app/cwa-app-android/blob/99b19dc6f64e2236d203d7a9ecaede6ace1130e4/Corona-Warn-App/src/main/res/values/strings.xml#L1144

Maybe more.

---
Internal Tracking ID: EXPOSUREAPP-4252

**Comment by tfar** [comment]
Saw there is already a PR to fix this.

**Comment by dsarkar** [comment]
PR https://github.com/corona-warn-app/cwa-app-android/pull/1749

**Comment by dsarkar** [comment]
Dear community,

Thank you for your contributions. This issue is fixed and will be closed now.
 
Best wishes,
DS

---
Corona-Warn-App Open Source Team
