### ISSUE TITLE
1.7.1 - stuck on checking screen - Android 7

### ISSUE THREAD

**Issue by Yanabamenara** [corona-warn-app/cwa-app-android#1755]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Describe the bug

When I updated the app yesterday evening, it took too long to check. Granted, that could have been because I wasn't able to do anything with it for two days, but I was at home for the time being, so there hadn't been any new contacts. 

This morning, it's the same. 

It's stuck on the checking screen, pressing the arrow sometimes makes it crash, sometimes it gets you to the screen where the hygiene rules are. I was fiddling with it for thirty minutes whereas before, with 1.5, I was done with in under 5.

Generally, the app has become a bit more unstable, as sometimes, when I open it, it still crashes, then opens when I retry. 

## Technical details

App version: 1.7.1 (updated from 1.7.0, which crashed, google play store on 27 November 2020).
Android version: 7.0 (security patch 1 December 2018) Kernel 3.18.35+jslave@WUH1000074104 #3
Hardware: Huawei Honor JMM-L22
Build JMM-L22C432B136
EMU-Version 5.1.3

## Additional context

After updating to 1.7.1. (from 1.7.0 which crashed on opening the app, rendering it unusuable), I can open the app again but it the checking seems to be stuck. 

@d4rken told me to open a new issue report after my posting this in another related thread. #1609

---
Internal Tracking ID: [EXPOSUREAPP-4054](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4054)

**Comment by d4rken** [comment]
I tried to find a crash in the last 24 hours with your device and Android version in the reports that get picked up by Google Play, unfortunately unsuccessful.

Would really like to see the stacktrace of that crash :thinking:. Would you be willing to mail a bug report to me or @thomasaugsten ? 

See https://developer.android.com/studio/debug/bug-report

**Comment by Yanabamenara** [comment]
Hmmmm... I think I have one, though I don't know if it's helpful. I'll mail it to @thomasaugsten cause he gave me the email.

**Comment by Yanabamenara** [comment]
I've sent @thomasaugsten one and I shall send him another tomorrow, after 24 hours.

**Comment by thomasaugsten** [comment]
A bug report immediately after the crash would be helpful

**Comment by Yanabamenara** [comment]
> A bug report immediately after the crash would be helpful

I shall try to get you guys one.

**Comment by Yanabamenara** [comment]
This evening, the app crashes again on opening. I've sent @thomasaugsten two bug reports, with both settings, short and long. One of them has 9 tombstones that list the corona app. 

I hope one of the two zips is helpful.

**Comment by d4rken** [comment]
Thank you very much for the the bug reports, they are helpful! I posted some details regarding the crash on opening in #1609.

> It's stuck on the checking screen

On the video or the logs I could not observe this "stuck" issue, did it happen this time? Could you further describe it?

> Pressing the arrow sometimes makes it crash, sometimes it gets you to the screen where the hygiene rules are.

I suspect this to be the same issue as #1609. The stacktrace in your bugreport points to a code path that is used on both screens. As you could open the app sometimes on the video, the there is the same chance that it crashes when running the same code path again when entering the details screen.

**Comment by Yanabamenara** [comment]
> Thank you very much for the the bug reports, they are helpful! I posted some details regarding the crash on opening in #1609.

Glad to hear that it helps. 
 
[...]
> On the video or the logs I could not observe this "stuck" issue, did it happen this time? Could you further describe it?

I wasn't able to make a vid, as the app now crashes on opening. 

It was that it went to check and it didn't seem to progress, as minutes (more than 5) passed. With 1.5. I was done in a minute or two.
 
> > Pressing the arrow sometimes makes it crash, sometimes it gets you to the screen where the hygiene rules are.
> 
> I suspect this to be the same issue as #1609. The stacktrace in your bugreport points to a code path that is used on both screens. As you could open the app sometimes on the video, the there is the same chance that it crashes when running the same code path again when entering the details screen.

Well, by now it crashes on opening again. *sigh*

**Comment by icke68746** [comment]
I have the same problem:
Since the last update, the app crashes when I open it. You see the logo briefly, then the program closes. This did not occur with version 1.7.0.
Operating system: Android 7.1.1
Corona app: Version 1.7.1
Device: Rufus Cuff
----Translated with deepl.com----Original:
Ich habe dasselbe Problem:
Seit dem letzten Update stürzt die App beim öffnen ab. Man sieht kurz das Logo, dann schließt sich das Programm. Das trat bei Version 1.7.0 nicht auf.
Betriebssystem: Android 7.1.1
Corona-App: Version 1.7.1
Gerät: Rufus Cuff

**Comment by MikeMcC399** [comment]
@Yanabamenara / @icke68746 
Are you still seeing crashes if you use version 1.10.1?

If there are crashes which occur using the latest Android CWA version 1.10.1 there is a new issue
https://github.com/corona-warn-app/cwa-app-android/issues/2049 to collect these cases.

**Comment by Yanabamenara** [comment]
> @Yanabamenara / @icke68746
> Are you still seeing crashes if you use version 1.10.1?
> 
> If there are crashes which occur using the latest Android CWA version 1.10.1 there is a new issue
> #2049 to collect these cases.

I use 1.9 still. I do not use 1.10.

**Comment by MikeMcC399** [comment]
@Yanabamenara 
> I use 1.9 still. I do not use 1.10.

Is 1.9 working for you without crashing?

**Comment by Yanabamenara** [comment]
> @Yanabamenara
> 
> > I use 1.9 still. I do not use 1.10.
> 
> Is 1.9 working for you without crashing?

So far, yes.

**Comment by heinezen** [comment]
This was fixed in CWA version 1.9. We will close this issue.

----
Corona-Warn-App Open Source Team

**Comment by icke68746** [comment]
> @Yanabamenara / @icke68746
> Are you still seeing crashes if you use version 1.10.1?
> 
> If there are crashes which occur using the latest Android CWA version 1.10.1 there is a new issue
> #2049 to collect these cases.

Runs again with version 10.0.1 . Läuft wieder mit Version 10.0.1 .
