### ISSUE TITLE
Fehler: Es konnte keine Übermittlungs-TAN erstellt werden

### ISSUE THREAD

**Issue by MichaelAnders** [corona-warn-app/cwa-app-android#1756]
Eine Bekannte wurde positiv getestet. Sie wollte ihr Ergebnis übermitteln. Sie hat eine TAN von der Hotline erhalten. Die App zeigt das Ergebnis positiv.

Beim Versuch ihr Ergebnis zu teilen bekommt sie obige Fehlermeldung. Telefon Hotline war überfragt, Lösung wäre laut einem Techniker die App zurück zu setzen - was sie aber nicht möchte, da sonst ihre Kontakte auch weg sind...

**Comment by dsarkar** [comment]
Dear @MichaelAnders,

Thank you for your report.

Could you please let us know the following:

CWA version:
Android version:
Mobile phone model:


Thanks. Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by MichaelAnders** [comment]
CWA version: 1.6.1
Android version: 9
Mobile phone model: Nokia 8 (TA-1012)

**Comment by dsarkar** [comment]
@MichaelAnders,

Thanks for feedback!

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by thomasaugsten** [comment]
Bitte die app zurücksetzen dabei werden keine Kontakte entfernt nur die Anzeige wird auf 1von 14 Tage. Zurückgesetzt. Danach eine neue Tan über die Hotline anfragen

**Comment by MichaelAnders** [comment]
Das hat funktioniert, danke!
