### ISSUE TITLE
Duplicate technical HTML file

### ISSUE THREAD

**Issue by fynngodau** [corona-warn-app/cwa-app-android#1757]
## Avoid duplicates
* [x] This enhancement request has not already been raised before
* [x] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [x] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

The three file `technical_de.html`, `technical_en.html` and `technical_tr.html` in `/Corona-Warn-App/src/main/assets/` are exactly equal.

## Suggested Enhancement

Remove the duplicate files and rename the remaing file to just `technical.html` (while changing the string resources pointing to the files accordingly).

## Expected Benefits

Having the file multiple times is confusing. I stumbled upon it when working on a fork of the project. It's a minor thing, of course, but if you like, I can open a quick PR for this change.

---
Internal Tracking ID: EXPOSUREAPP-4055

**Comment by fynngodau** [comment]
Maybe this should be a separate issue, but that file also doesn't display as intended because newlines in the file are not rendered unless they contain a `<br/>` (because it's HTML), which they don't. Therefore each component displays as one weird text block.

**Comment by heinezen** [comment]
Hey @fynngodau ,

Thank you for the hint. I have forwarded this issue to the developers by creating an internal Jira ticket (EXPOSUREAPP-4055) for your request. Of course, you can also make a PR to address the issue if you want.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by fynngodau** [comment]
Hello @heinezen,

I'd have a two commits ready that I would open a PR with, but the template tells me not to open PRs for "changes in localization files", which this would consist of exclusively. How would you like me to do this (and if so, onto what branch)?

**Comment by heinezen** [comment]
@fynngodau I would say it is still if you make a PR because the reason for the restriction is that we cannot accept unapproved texts into the repo (they have to be reviewed by the RKI). Since you are technically not changing any texts, I think we are allowed to bend the rules here. However, the dev team might have their own opinions on that, but we'll see.

You can set `main` as the PR target branch. The devs will change it to the correct release branch afaik.

----
Corona-Warn-App Open Source Team

**Comment by fynngodau** [comment]
#1822 was closed, thereby solving this issue. Hence, I will now close this issue.
