### ISSUE TITLE
Inkonsistente Anrede

### ISSUE THREAD

**Issue by be-we** [corona-warn-app/cwa-app-android#1760]
In der Corona-Warn-App wird der Benutzer sowohl mit **_du_** als auch mit **_Sie_** bzw. **_Ihr_** angeredet.

Beispiel für Anrede mit **_du_**:
- _„Wenn **du** diese Funktion verwenden möchtest, aktiviere Bluetooth“_

Beispiele für Anrede mit **_Sie_** bzw. **_Ihr_**:
- _„Waschen **Sie** **Ihre** Hände regelmäßig mit Seife für 20 Sekunden.“_
- _„So wird **Ihr** Risiko ermittelt“_

**Comment by MikeMcC399** [comment]
Hi @be-we 
> Beispiel für Anrede mit du:
>
>„Wenn du diese Funktion verwenden möchtest, aktiviere Bluetooth“

Der Text „Wenn du diese Funktion verwenden möchtest, aktiviere Bluetooth“ stammt vom Google Exposure Notification System und nicht von der Corona-Warn-App.

![COVID-19-Benachrichtigungen](https://user-images.githubusercontent.com/66998419/100545601-e37e0900-325c-11eb-974f-f649ac5940e2.jpg)

Wenn man auf diese Benachrichtigung tippt, wird man auf der (Google)-Seite COVID-19 Benachrichtigungen geleitet, wo man weiterhin geduzt wird z.B. "Die App kann dich benachrichtigen, wenn du dich in der Nähe ...". Wenn man allerdings auf das Fragezeichen im Kreis rechts oben tippt, landet man auf Google Hilfstexte im Internet, wo man gesiezt wird, z.B. "Wenn Sie wissen möchten, ob Sie mit einer Person Kontakt hatten ..."

Es ist genauso im Google Play Store durcheinander. Will man sich in den Play Store einloggen, wird man gesiezt. Ist man drin, wird man geduzt.

Es fehlt wohl eine Einstellung in Android, wo man mitteilt, ob man geduzt oder gesiezt werden möchte. 😁 

Soweit ich es beurteilen kann, ist die eigentliche Corona-Warn-App konsequent und siezt durchgängig (außer ganz speziell, wenn man die App teilt und schickt eine Mail an einen Freund oder Bekannten - dort heißt es "Ich bin dabei. Du auch?").

**Comment by corneliusroemer** [comment]
Übersetzungsinkonsistenz passiert schon mal gerne bei Du/Sie von Englisch->Deutsch.

@be-we Für die Entwickler ist es extrem nützlich, wenn du Screenshots von den stellen machst, die inkonsistent sind. Wie @MikeMcC399 zeigt, ist dein Beispiel für "Du" nicht von der Warn-App selbst. Hast du ein Beispiel von "Du" aus der App selbst? Ansonsten kann das Issue hier erstmal geschlossen werden.

**Comment by heinezen** [comment]
Hello @be-we ,

Thanks for your submission. Can you tell us the screen/location where these inconsistencies can be found? This would help us a lot in fixing the problem.

Also, as @corneliusroemer and @MikeMcC399 have already pointed out, please check if the texts are actually *in* the app or the app's notifications. The Google ENF in the background has its own notifications that might use other terminologies or form of address than the CWA.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by cyb3rko** [comment]
Damit kann das Issue geschlossen werden, oder?

**Comment by heinezen** [comment]
@cyb3rko I think so.

@be-we If you can can get the information I asked about at a later date, please post them here. We will then consider reopening the issue.

----
Corona-Warn-App Open Source Team
