### ISSUE TITLE
Use cipher suites recommended by BSI

### ISSUE THREAD

**Issue by IndianaDschones** [corona-warn-app/cwa-app-android#177]
## Current Implementation

TODO 😄 

https://github.com/corona-warn-app/cwa-app-android/blob/baa3e1300dd22cd139cc8c3f656e289e21f6f9f0/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/ServiceFactory.kt#L75-L77

## Suggested Enhancement

Use cipher suites recommended by BSI in [TR-02102-2](https://www.bsi.bund.de/SharedDocs/Downloads/EN/BSI/Publications/TechGuidelines/TG02102/BSI-TR-02102-2.pdf?__blob=publicationFile&v=10)

## Expected Benefits

Secure and state of the art TLS-configuration

**Comment by jakobmoellersap** [comment]
The Cipher suite question is solved now by #217 for the most critical parts (submission and verification) while for the distribution CDN we do not have strict cipher selection. Thus, I will close this issue. Thanks so much for your contribution in #178 which was taken over in the implementation of #217.
