### ISSUE TITLE
Cause 3: Google Schnittstelle #8 - google service timeout

### ISSUE THREAD

**Issue by openmindculture** [corona-warn-app/cwa-app-android#1785]
After startup, I got the following error message in a technical wording, which might not at all be helpful to the average German user. The error details are in English (see attached screenshots) and "Google Schnittstelle" is not written correctly. There is no call to action how to deal with the error.

URSACHE 3 Etwas ist schiefgelaufen
Fehler bei der Kommunikation mit der Google Schnittstelle \#8

## Expected behaviour

Every error should be worded in a helpful way in plain language containing a suggestion what to do, e.g. try again or submit an error report.

"Google Schnittstelle" should not be two words or the words should be connected by a hyphen (horizontal dash).

## Steps to reproduce the issue

I could not reproduce the issue.
Seen on Huawei Honor 6C (Pro?) (JMM-L22C432B136) running Android 7.0.
CWA App Version: 1.7.1

![Screenshot_20201202-082453](https://user-images.githubusercontent.com/6377941/100843339-819aea80-347a-11eb-922b-cc6157373b39.png)

![Screenshot_20201202-082509](https://user-images.githubusercontent.com/6377941/100843371-8c557f80-347a-11eb-967e-9049c35bb6c6.png)

![Screenshot_20201202-082518](https://user-images.githubusercontent.com/6377941/100843387-95465100-347a-11eb-994d-4693f807b327.png)

---
Internal Tracking ID:  EXPOSUREAPP-4132

**Comment by thomasaugsten** [comment]
Can you please create a bug report after receiving this error
https://developer.android.com/studio/debug/bug-report

**Comment by dsarkar** [comment]
Dear @openmindculture,

- Thank you very much for reporting your issue. 
- Could you create a bug report as requested by @thomasaugsten? 
- We have created a ticket for the bug (Internal Tracking ID: EXPOSUREAPP-4132) in the internal Jira system.  Any further developments will be notified here in this Github issue.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by openmindculture** [comment]
> * Could you create a bug report as requested by @thomasaugsten?

Althoug I cannot reproduce the bug and the app is working fine since yesterday,
I have created a report anyway. It contains tombstone files mentioning `de.rki.coronawarnapp` so hopefully you will be lucky to find valuable information for a bug fix. If you don't, I would still consider it helpful to provide better userfriendly error texts even for generic error messages, adding a call to action to help the user decide what to do or not to do.

[bugreport-HUAWEIJMM-L22-2020-12-04-10-20-14.zip](https://github.com/corona-warn-app/cwa-app-android/files/5641783/bugreport-HUAWEIJMM-L22-2020-12-04-10-20-14.zip)

**Comment by dsarkar** [comment]
Dear @openmindculture, Thanks for the feedback and bug report. My understanding is that the developers are actually on this topic as well, i.e. improving the error messages and actually hide certain unnecessary notifications, which seem to be errors but are not.  I will forward the report. Feedback is welcome, in particular, if you find a way to reproduce the issue.  Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by openmindculture** [comment]
Steps to reproduce:
Activate flight mode, exit all internet connections.
Power off the device.
Turn on the device again.
Unlock SIM and log in.
Exit flight mode.
Open Corona Warn App immediately (don't wait for network access.)
Error occurs.

**Comment by dsarkar** [comment]
@openmindculture, Thanks for feedback, very much appreciated. We will update the developers with the additional information. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by thomasaugsten** [comment]
@openmindculture  Can you still reproduce this bug? Can you please create a new bug report?

**Comment by openmindculture** [comment]
> @openmindculture Can you still reproduce this bug? Can you please create a new bug report?

@thomasaugsten I have not seen the message again ever since.
