### ISSUE TITLE
Indeterminate risk status after onboarding with no network

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#1830]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Describe the bug
When onboarding is attempted with no network connection, a blank risk card is shown.

## Expected behaviour
The risk card should say that there is no network connection available, and therefore risk is unknown.

## Steps to reproduce the issue

1. Uninstall CWA if already installed
2. Install CWA from Google Play Store
3. Disable WiFi
4. Open CWA
5. Tap LET'S GET STARTED, NEXT, ACTIVATE EXPOSURE LOGGING
6. Turn On
7. NEXT, NEXT, OK, ALLOW
8. go back from OPTIMISE BATTERY USAGE if necessary

The following screen shot shows the blank risk card:

![Indeterminate risk status](https://user-images.githubusercontent.com/66998419/101474788-ddb6b080-394b-11eb-874d-ba8c8bae6f1d.jpg)

As soon as WiFi is enabled, keys are fetched and Unknown Risk is correctly shown.

## Technical details

- Mobile device: Samsung Galaxy A5 (2017) SM-A520F, no SIM card installed
- Android version: 8.0.0
- CWA version: 1.7.1

---
Internal Tracking ID: [EXPOSUREAPP-4254](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4254)

**Comment by dsarkar** [comment]
Dear @MikeMcC399, 

Thank you for reporting this issue

We have created a ticket for the bug. Any further developments will be notified here in this Github issue.
  
Best wishes,
DS

---
Corona-Warn-App Open Source Team
Internal Tracking ID: [EXPOSUREAPP-4254](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4254)

**Comment by dsarkar** [comment]
FYI:

Related PR https://github.com/corona-warn-app/cwa-app-android/pull/1751
Related tickets: Internal Tracking IDs: [EXPOSUREAPP-4254](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4254),  [EXPOSUREAPP-3881](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3881)
Best, DS

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
No longer reproducible under CWA Android 1.9.1.
Instead, the green Low Risk card is shown with the text:
"Encounters have not yet been checked".

After enabling WiFi, status changes to:
"Updated: Today, hh:mm"
