### ISSUE TITLE
Notification doesn't expand when dragging

### ISSUE THREAD

**Issue by JanRaber** [corona-warn-app/cwa-app-android#1850]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details
- Device name: Xiaomi Mi 10 (MIUI Global 11.0.13.0 QJBEUVF)
- Android version: 10 QKQ1.191117.002
- App version: 1.7.1

## Describe the bug
When I receive notifications from cwa that contain multiple lines of text, I can't expand the notification. Therefore it's not possible to see the entire content of the notification, but just the first line of text. See animated GIF below.

![ExpandNotificationBug](https://user-images.githubusercontent.com/62836138/101626245-f93dbc00-3a1c-11eb-9847-56a24b2051a2.gif)

## Steps to reproduce the issue
1. Receive a multi line notification from cwa.
2. Try to expand the notification by dragging it.

## Expected behaviour
The notification expands and shows it's entire content.

---

Related PR https://github.com/corona-warn-app/cwa-app-android/pull/1999

---
Internal Tracking ID: [EXPOSUREAPP-4251](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4251)

**Comment by MikeMcC399** [comment]
@JanRaber 
It looks like the notification showing as a one line truncated text is:

`risk_details_deadman_notification_body`
<string name="risk_details_deadman_notification_body">"Bitte denken Sie daran, die Corona-Warn-App regelmäßig zu öffnen, um Ihren Risikostatus zu überprüfen."</string>

**Comment by JanRaber** [comment]
@MikeMcC399 thanks for sharing the full notification text.

At this point I'm not yet able to tell if this behaviour specific to my device. I'll try to reproduce this on another Android device. Did anybody experience this issue as well?
Is it intended that notifications are shown as one line truncated text and are not expandable?

**Comment by MikeMcC399** [comment]
@JanRaber 
The Deadman notification is an enhancement with quite a bit of new code (see https://github.com/corona-warn-app/cwa-app-android/pull/1513 (EXPOSUREAPP-2332)).

I would wait for a response from the Open Source Team / developers first before investing any more effort into investigating. It looks like the notification call needs a little tweaking.

**Comment by vaubaehn** [comment]
related: #1067 , https://github.com/corona-warn-app/cwa-app-android/issues/1066#issuecomment-678758294
FYI: @d4rken

**Comment by MikeMcC399** [comment]
@vaubaehn 
The Deadman notification comes from 
https://github.com/corona-warn-app/cwa-app-android/blob/main/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/deadman/DeadmanNotificationSender.kt


"By default, the notification's text content is truncated to fit one line. If you want your notification to be longer, you can enable an expandable notification by adding a style template with [setStyle()](https://developer.android.com/reference/androidx/core/app/NotificationCompat.Builder#setStyle(android.support.v4.app.NotificationCompat.Style))" 
See https://developer.android.com/training/notify-user/build-notification#builder.

I'm not experienced in this area, but it seems that private fun buildNotification might benefit from using:
     .setStyle(new Notification.BigTextStyle()
         .bigText(aVeryLongString))

**Comment by vaubaehn** [comment]
@MikeMcC399 
Yes, could be!

I referenced @kbobrowski 's PR and comment, because in the past there was already an issue, where the notification was not expandable.
See here:

https://github.com/kbobrowski/cwa-app-android/blob/5b6caee492714c99db905205d52caa343c419d8b/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/notification/NotificationHelper.kt#L158-L169

`sendNotification` has a property for `expandableLongText: Boolean = false` , and in order to expand the text, it needed a call like
```
    fun sendNotification(content: String, visibility: Int) {
        if (!CoronaWarnApplication.isAppInForeground) {
            sendNotification("", content, visibility, true)
        }
    }
```
where that property was set to `true `(which was missing in that old CWA version, so the text was not expandable).

But I'm not sure if NotificationCompat.Builder
https://github.com/corona-warn-app/cwa-app-android/blob/3ca4752876af458f7bf3a41d392623529e863ecf/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/deadman/DeadmanNotificationSender.kt#L36-L52

should have an `expandableLongText` by default?
There were so many UI changes since...

**Comment by MikeMcC399** [comment]
@vaubaehn 
I was able to see the problem on an Android 11 emulator, which had been idle for several days, and I tried out my fix suggestion on a test program, which worked, so I think we just need to let the developers take over now.

**Comment by vaubaehn** [comment]
@MikeMcC399 
> I was able to see the problem on an Android 11 emulator, which had been idle for several days, and I tried out my fix suggestion on a test program, which worked, so I think we just need to let the developers take over now.

That's great, good job! :+1: Wouldn't it be nice if you created a PR and contribute? You'd definitely deserve to get the contributer badge! And I'm sure devs would love to offer you to open a PR :)

**Comment by MikeMcC399** [comment]
@vaubaehn 
> That's great, good job! 👍 Wouldn't it be nice if you created a PR and contribute? You'd definitely deserve to get the contributer badge! And I'm sure devs would love to offer you to open a PR :)

I'm flattered by your confidence, however I can't test the app if I were to make changes (I'm not whitelisted), and the functionality involved has compatibility dependencies according to the version of Android in use, so changes would need to be checked on Android versions which I don't have hardware for anyway.

So, I'm happy for the real developers to be looking at this, and I'm glad if any pre-qualification that's been done in this issue speeds up the resolution.

**Comment by JanRaber** [comment]
@MikeMcC399 
> I was able to see the problem on an Android 11 emulator, which had been idle for several days, and I tried out my fix suggestion on a test program, which worked, so I think we just need to let the developers take over now.

Great work! This should be enough to verify that we're not facing a device specific issue.

**Comment by dsarkar** [comment]
Dear @JanRaber, @MikeMcC399, @vaubaehn, and community

Thank you for your contributions detailed analysis. This forwarded to the developers (Internal Tracking ID: EXPOSUREAPP-4251) in the internal Jira system. Any further developments will be notified here in this Github issue.
  
Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@dsarkar 
> Internal Tracking ID: EXPOSUREAPP-4251

Thank you for logging the issue internally! The repo steps from https://github.com/corona-warn-app/cwa-app-android/pull/1513 @AlexanderAlferov are sufficient to show the problem on an Android 11 emulator.

### Steps to reproduce
Risk calculation should fail and never succeed in 36 hours (either in foreground or background).

1. Wait until risk calculation finished
2. Go to settings -> Date & time
3. Add two days to current date
4. Deadman notification should appear

Here are screen shots from advancing the date by 3 days to next Sunday. The text which should be displayed, but which is truncated is:

`risk_details_deadman_notification_body`
<string name="risk_details_deadman_notification_body">"Please remember to open the Corona-Warn-App regularly to check your risk status."</string>
which appears as:
"Please remember to open the Corona-Warn-App regula.." in the example. The truncation will be dependent on the screen size of the device.

![Sunday](https://user-images.githubusercontent.com/66998419/101765056-15a32c80-3ae1-11eb-8101-e7de2b111379.gif)

---

![Truncated notification](https://user-images.githubusercontent.com/66998419/101765079-1cca3a80-3ae1-11eb-9381-2dc40a0bcbef.gif)

**Comment by dsarkar** [comment]
@MikeMcC399, thanks for the additional analysis. We update the developers with these details. Dipankar Sarkar

**Comment by dsarkar** [comment]
Dear @JanRaber, @MikeMcC399, @vaubaehn, and community

FYI - PR https://github.com/corona-warn-app/cwa-app-android/pull/1999

**Comment by MikeMcC399** [comment]
"Fix deadman notification text not being expandable and clean up code (EXPOSUREAPP-4251)" https://github.com/corona-warn-app/cwa-app-android/pull/1999 is showing as part of [v1.11.0-RC1](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.11.0-RC1).

**Comment by MikeMcC399** [comment]
The steps to reproduce, described in https://github.com/corona-warn-app/cwa-app-android/issues/1850#issuecomment-742457853, using the trick of moving the clock forward two days, do not work any more in CWA 1.11.0, which checks for the correct setting of the device's clock. The following error message appears if the clock is set to something different to the correct time: 

"Exposure Check Not Possible"

<string name="device_time_incorrect_dialog_body">"The time set on your device does not match the current time. As a result, your risk cannot be checked right now. Please set the correct time in your device settings."</string>
 
This is good improvement for CWA, which needs to have correct timestamps on all encounters, however it means it will take a minimum of 36 hours to verify that the fix to the deadman notification is working in the 1.11.0 release. (Unless somebody knows of another workaround to speed up testing.)

**Comment by MikeMcC399** [comment]
@JanRaber 
I tested the fix in CWA 1.11.0 by enabling Flight mode (so no WiFi or mobile network) and leaving the phone connected to a charger for 36 hours.

First it displayed the following notification, and I then tapped on the down-arrow which I've marked in yellow:
![Your Risk Status initial](https://user-images.githubusercontent.com/66998419/106511772-fc12d580-64d0-11eb-87c2-5f72f471c0d3.jpg)

---
It then expanded the notification so that the full text could be read:
![Your Risk Status expanded](https://user-images.githubusercontent.com/66998419/106511748-f3ba9a80-64d0-11eb-8706-12e853e60750.jpg)

If that fixes the problem you reported, you can go ahead and close this issue.

**Comment by dsarkar** [comment]
@MikeMcC399 Many thanks for checking!
@JanRaber, and community. Many thanks for reporting and contributing. Please, go ahead and close this issue as suggested by @MikeMcC399.

Best wishes, DS

**Comment by MikeMcC399** [comment]
@dsarkar 
Is your new label https://github.com/corona-warn-app/cwa-app-android/labels/read-to-close maybe supposed to be ready-to-close, not read-to-close?

**Comment by MikeMcC399** [comment]
@JanRaber 
Would you like to close your issue now or do you have some reservations?

**Comment by MikeMcC399** [comment]
@dsarkar / @heinezen 

This issue should be closed now, since the screenshots in https://github.com/corona-warn-app/cwa-app-android/issues/1850#issuecomment-771123737 show that it was solved already in version 1.11 and there has been no other feedback that it was not fixed.

With the release of 1.12 today, version 1.11 now becomes the previous release.

**Comment by JanRaber** [comment]
Sorry @MikeMcC399 for my late response, obviously you are right and this issue was fixed.
Thanks to everybody who was contributing and thanks for fixing this issue. I'm happy that I was able to give some tiny feedback to make this app a little bit better. Open source is just great :-) ! 
Closing now.

**Comment by dsarkar** [comment]
@JanRaber and community, Thanks for contributing. Best wishes, DS

---
Corona-Warn-App Open Source Team
