### ISSUE TITLE
Transnational country list missing Netherlands

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#1872]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy A50 SM-A505FN
- Android version: 10
- App version: 1.7.1

## Describe the bug

The list of countries does not include "Netherlands".
The device with the issue is connected to Internet. The CWA risk status shows: Updated: Today: 09:28.

According to https://www.coronawarn.app/en/faq/#interoperability_countries the Netherlands went live on 30.11.2020.

## Steps to reproduce the issue

![Missing Netherlands](https://user-images.githubusercontent.com/66998419/101888858-fe2a7900-3b9e-11eb-862c-7f9ef6a405b7.jpg)

1. Tap EXPOSURE LOGGING ACTIVE.
2. Tap Transnational Exposure Logging Participating Countries
3. Scroll down to header "The following countries currently participate in exposure logging:"
4. Examine the list of countries displayed.

## Expected behaviour

The list of countries should currently show:

1. Croatia
2. Denmark
3. Germany
4. Ireland
5. Italy
6. Latvia
7. **Netherlands**
8. Poland
9. Spain

## Additional information

On another device (Samsung Galaxy A5 (2017) SM-A520F / Android 8.0.0 / CWA Version 1.7.1) Netherlands **is** shown in the country list.

I tried restarting the device with the problem, however, this caused no change.

---
Comment Solved: https://github.com/corona-warn-app/cwa-app-android/issues/1872#issuecomment-743752778
Related PR https://github.com/corona-warn-app/cwa-app-android/pull/1858

---
Internal Tracking ID: [EXPOSUREAPP-4195](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4195)

**Comment by dsarkar** [comment]
Dear @MikeMcC399, and community

Thanks for reporting. I would like some feedback from the community:

Please check on you phones this issue and report back here with:

- Device model
- CWA version 1.7.1
- Android version   
- Netherlands shown (EN) ?
- Netherlands shown (DE) ?

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@dsarkar 
I know that tablets are not officially supported, but I run CWA also on one tablet for test purposes, which I leave on my desk at home. This device has the same problem. Switching languages doesn't change anything.

Device model: Samsung Galaxy Tab A
CWA version: 1.7.1
Android version: 10
Netherlands shown (EN) ? No
Netherlands shown (DE) ? No

**Comment by dsarkar** [comment]
![image](https://user-images.githubusercontent.com/1409741/101895102-5c5b5a00-3ba7-11eb-9245-3f4844d1cc30.png)

**Comment by MikeMcC399** [comment]
@dsarkar 
Which version of Android runs on your Huawei P10 lite? I'm seeing the issue only on Android 10, not on Android 8.

**Comment by vaubaehn** [comment]
No Netherlands (DE):
Android 6
Cwa 1.7.1

![Screenshot_2020-12-11-12-29-18](https://user-images.githubusercontent.com/68376758/101898693-dd692000-3bac-11eb-8bb9-0bc02348fa9e.png)

**Comment by Thusid** [comment]
Device model: Google Pixel 3XL
CWA version: 1.7.1
Android version: 11
Netherlands shown (EN) ? No
Netherlands shown (DE) ? No

**Comment by MikeMcC399** [comment]
Device model: Google Pixel 3a Emulator
CWA version: 1.7.1
Android version: 11
Netherlands shown (EN) ? Yes
Netherlands shown (DE) ? Yes

**Comment by MikeMcC399** [comment]
I was assuming it was a client issue, but perhaps there is a server issue (cluster, load-balancer or similar)?

**Comment by codejus** [comment]
Device model: Nokia 7 Plus
CWA version: 1.7.1
Android version: 10
Netherlands shown (EN) ? Yes
Netherlands shown (DE) ? Yes

Device model: BQ Aquaris X
CWA version: 1.7.1
Android version: 8
Netherlands shown (EN) ? No
Netherlands shown (DE) ? No

**Comment by d4rken** [comment]
This could be caused by the app always defaulting to the legacy config, which will be fixed in the next update by #1858.

It would be  a client issue.
The bug condition would be that the affected app installs previously had at CWA `1.6.X` or older installed.

Would that fit the cases reported here?

* Devices where Netherlands is missing have had `1.6.0` or older installed at some point
* Devices where Netherlands is shown either never had a version older than `1.7.0` installed or have deleted the app data at some point (through the system, not the app)

**Comment by MikeMcC399** [comment]
@d4rken 
Your theory sounds very feasible!

On a test device that had been running previous CWA versions and is currently on 1.7.1 I went into Settings > Apps > Corona-Warn > Storage > Clear data (not a good idea though if you are using the device for anything other than testing!)
then I ran through CWA onboarding.

Now I have 9 countries, including Netherlands (NL) showing.

**Comment by Thusid** [comment]
@d4rken
> Would that fit the cases reported here?
>
>    Devices where Netherlands is missing have had 1.6.0 or older installed at some point

This applies to my case: The app was installed with its first version, then never uninstalled. However, data and cache had to be deleted at the end of September (because of some error message).

**Comment by codejus** [comment]
@d4rken Your theroy matches with the expierience with my two devices.

On my BQ Aquaris X I've installed CWA first with Version 1.6 and later upgraded to 1.7.1. On my Nokia the first version I've installed was 1.7.1 after I had to setup it new after a repair.

**Comment by MikeJayDee** [comment]
A few more data points:
Pixel 5: NL not shown (new install on 19 October, presumably with version 1.5.0, phone is always on)
Pixel 2: NL shown (App reset to fix issue on 1 November, version 1.5.1 installed at that time, phone switched on every few days)
Galaxy S6: NL shown (used occasionally only, can't recall when I installed the app)

**Comment by MikeMcC399** [comment]
@dsarkar 
Could you please explain why you added the text **Fix 1.9**?

@d4rken wrote:
>This could be caused by the app always defaulting to the legacy config, which will be fixed in the next update by #1865.

#1865 (EXPOSUREAPP-4195) is merged into branch release/1.7.x and is contained in (v1.8.1-RC2)[https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.8.1-RC2].

**Comment by MikeMcC399** [comment]
@dsarkar 
I see that you are editing the titles and adding categories like here
[Fix 1.9][Solved]

Have you considered using GitHub labels for this purpose instead of coding categories into the title?

**Comment by MikeJayDee** [comment]
I assume that a side effect of this is that the parameters of the risk calculations are not updated. Is there a workaround, like resetting the data? Or not worth it and better to just wait?

**Comment by dsarkar** [comment]
> Have you considered using GitHub labels for this purpose instead of coding categories into the title?

@MikeMcC399. Thanks, that is the proper way of doing it. Fixed. DS

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
Now also Cyprus (which joined today) is missing from the Transnational Exposure Logging Participating Countries list on my main device which has been updated from previous CWA versions without resetting for quite a while and without uninstalling CWA.

On a test device which I recently re-installed, Cyprus is showing up together with Netherlands, so there are 10 countries listed there .

1. Croatia
2. **Cyprus**
3. Denmark
4. Germany
5. Ireland
6. Italy
7. Latvia
8. **Netherlands**
9. Poland
10. Spain

**Comment by dsarkar** [comment]
Good morning @MikeMcC399. Thanks for the information. Best, DS

---
Corona-Warn-App Open Source Team

**Comment by Thusid** [comment]
After updating to 1.9.1, the Netherlands as well as Cyprus are shown.

**Comment by MikeMcC399** [comment]
@Thusid 
Thanks for checking! I'm also seeing the full list on an updated 1.9.1 smartphone.

Here is a screen shot showing 10 countries.
![Country_list_1 9 1](https://user-images.githubusercontent.com/66998419/102689062-a376ca00-41fb-11eb-98d5-1295a5f361c5.jpg)

The list is no longer sorted alphabetically, but that is a different topic. The main point is that all the countries are displayed.

**Comment by dsarkar** [comment]
@MikeMcC399, thanks for the feedback! Best, DS
