### ISSUE TITLE
App can't be installed

### ISSUE THREAD

**Issue by HeynJens** [corona-warn-app/cwa-app-android#1893]
## Technical details

- Device name: Huawei Y5 II
- Android version: 5.1 Lollipop

## Describe the bug

The Corona-Warn-App can't be installed on Huawei 5 II. 

## Error-Message
Google Play Store: Not available on this device

## Steps to reproduce the issue
1. Start your Huawei 5 II
2. Go to Google Play Store
3. Try to install the app

## Expected behaviour
Download and installation.

## Possible Fix
Develop the app for older Android-Versions.

**Comment by codejus** [comment]
Hello @HeynJens 

Please refer to here [Issue #1799](https://github.com/corona-warn-app/cwa-app-android/issues/1799l) for the most recent discussion about Android 5 Support. In addtion there are many others.

To sum it up: In general CWA requires the API Version 23 which comes with Android 6: [CWA FAQ](https://www.coronawarn.app/en/faq/#googleplay). Despite Google has lowered the minimum API Version to 21 (Android 5) recently there are still other issues which prevent CWA from running on Android 5 devices. First some dependencies need still API Version 23 ([1799 comment](https://github.com/corona-warn-app/cwa-app-android/issues/1799#issuecomment-738137588) and probably the devices don't support the needed Bluetooth Low Energy features in full.

**Comment by HeynJens** [comment]
Okay, then I'm going to close this Issue cos it's redundant. Sorry, I have not seen issue #1799 (Android 5 Support)

**Comment by dsarkar** [comment]
Dear @HeynJens, and community

Thank you for your contributions. As @codejus suggests, please continue posting in the previously opened thread https://github.com/corona-warn-app/cwa-app-android/issues/1799.

  
Best wishes,
DS

---
Corona-Warn-App Open Source Team
