### ISSUE TITLE
Keine Aktualisierung des Risikos / App does not update risk state / Samsung SM  A300FU - CWA 1.7.1 - Android 6.0.1

### ISSUE THREAD

**Issue by phakrkr** [corona-warn-app/cwa-app-android#1894]
## Technical details
- Device name: Samsung SM A300FU
- Android version: 6.0.1
- App version: 1.7.1

## Problembeschreibung 

letzte Aktualisierung liegt mittlerweile 4 Tage zurück, trotz Aktivierung des Hintergrunddienstes etc.
auch sind keine Energiespar-Modi aktiv und die App ist zudem explizit von "App-Optimierung" ausgenommen.

Zufallsschlüssel scheinen jedoch generiert und ausgetauscht zu werden, zumindest ist dies über die Android-Benachrichtung zu erkennen (siehe Bilder)

## Bilder

![Screenshot_2020-12-14-22-33-20](https://user-images.githubusercontent.com/76014773/102141400-0dd8e480-3e61-11eb-901f-a8f59b0cd809.png)
![Screenshot_2020-12-14-22-54-02-1](https://user-images.githubusercontent.com/76014773/102141408-103b3e80-3e61-11eb-9f75-0fe1790b4601.png)

---
EDIT: Related issues
---
- [App does not update risk state GUI on Samsung S5 Mini](https://github.com/corona-warn-app/cwa-app-android/issues/1817) https://github.com/corona-warn-app/cwa-app-android/issues/1817.

---
Internal Tracking ID: [EXPOSUREAPP-4087](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4087)
Internal Tracking ID: [EXPOSUREAPP-4473](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4473)

**Comment by MikeMcC399** [comment]
@phakrkr 
Kannst Du bitte auch ein Screenshot posten, wenn Du auf 
14. DEZEMBER
07:57
tippst? Es geht um den Key Count

bzw. auch den Exposure Log posten (Drei-Punkte-Menü) bei Überprüfung auf m...

**Comment by phakrkr** [comment]
@MikeMcC399 

beim Exposure-Log, war ich mir jetzt nicht sicher.  meinst du die .json Datei, die bei "exportieren" erstellt wird?

hier der gewünschte Screenshot, auch der neuste

![Screenshot_2020-12-15-06-23-19-1](https://user-images.githubusercontent.com/76014773/102175363-b5750780-3e9f-11eb-907c-c75bc7837f14.png)
![Screenshot_2020-12-15-06-23-14-1](https://user-images.githubusercontent.com/76014773/102175481-ef460e00-3e9f-11eb-9094-9997dfd0e88e.png)

**Comment by MikeMcC399** [comment]
@phakrkr 
> beim Exposure-Log, war ich mir jetzt nicht sicher. meinst du die .json Datei, die bei "exportieren" erstellt wird?

Genau die Datei all-exposure-checks.json holen,
die dann auf all-exposure-checks.json.txt umbenennen (weil GitHub .json blockiert)
und dann hier posten.

Dein Problem hat große Ähnlichkeiten zu einem bereits gemeldeten Problem
[App does not update risk state GUI on Samsung S5 Mini](https://github.com/corona-warn-app/cwa-app-android/issues/1817) https://github.com/corona-warn-app/cwa-app-android/issues/1817.

**Comment by dsarkar** [comment]
Dear @phakrkr,

Many thanks for reporting. We have forwarded your case to the developers:
Internal Tracking ID: [EXPOSUREAPP-4087](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4087)
  
Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by sjnfr** [comment]
Hallo zusammen,
durch Google bin ich auf diesen Thread aufmerksam geworden. Das selbe Problem tritt bei mir auch auf. Falls ich in irgendeiner Weise mit Informationen aus meiner App zur Lösung beitragen kann, lasst es mich bitte wissen (wenn nicht, seht meinen Post als überflüssig an).

**Comment by MikeMcC399** [comment]
@sjnfr 
> Das selbe Problem tritt bei mir auch auf. Falls ich in irgendeiner Weise mit Informationen aus meiner App zur Lösung beitragen kann, lasst es mich bitte wissen

Hast Du eine identische Konfiguration, wie @phakrkr ?
Device name: Samsung SM A300FU
Android version: 6.0.1
App version: 1.7.1

Wenn nicht, dann bitte mit Details hier ergänzen!

**Comment by dsarkar** [comment]
Hi @phakrkr, also to you thanks for reporting. Please add the information as requested by @MikeMcC399.  There will be a new release of the CWA very soon. We would appreciate your feedback regarding the new release. Thanks! Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by sjnfr** [comment]
> 
> 
> @sjnfr
> 
> > Das selbe Problem tritt bei mir auch auf. Falls ich in irgendeiner Weise mit Informationen aus meiner App zur Lösung beitragen kann, lasst es mich bitte wissen
> 
> Hast Du eine identische Konfiguration, wie @phakrkr ?
> Device name: Samsung SM A300FU
> Android version: 6.0.1
> App version: 1.7.1
> 
> Wenn nicht, dann bitte mit Details hier ergänzen!

Identisch, bis auf Modellnummer:
SM-G800F

Wenn ich in meinem Google-Konto schaue, sehe ich - wie oben - dass die App abfragt. Nur das Ergebnis der Abfrage wird nicht dargestellt. Vielen Dank - thanks everyone!

**Comment by MikeMcC399** [comment]
SM-A300FU ist Samsung Galaxy A3 (2015)
SM-G800F ist Samsung Galaxy S5 Mini

@sjnfr
Für das Problem mit dem Modell Samsung Galaxy S5 Mini gibt es ein getrenntes Problembericht unter https://github.com/corona-warn-app/cwa-app-android/issues/1817

**Comment by sjnfr** [comment]
> 
> 
> SM-A300FU ist Samsung Galaxy A3 (2015)
> SM-G800F ist Samsung Galaxy S5 Mini
> 
> @sjnfr
> Für das Problem mit dem Modell Samsung Galaxy S5 Mini gibt es ein getrenntes Problembericht unter #1817

Oh, Entschuldigung. Soll ich mich dort nochmal melden?

**Comment by MikeMcC399** [comment]
@sjnfr 
> Soll ich mich dort nochmal melden?

Trage Dich am besten in #1817 ein, dann sind alle informiert. Defaultmäßig kriegst Du dann auch Updates von dort,

**Comment by phakrkr** [comment]
> @phakrkr
> 
> > beim Exposure-Log, war ich mir jetzt nicht sicher. meinst du die .json Datei, die bei "exportieren" erstellt wird?
> 
> Genau die Datei all-exposure-checks.json holen,
> die dann auf all-exposure-checks.json.txt umbenennen (weil GitHub .json blockiert)
> und dann hier posten.
> 
> Dein Problem hat große Ähnlichkeiten zu einem bereits gemeldeten Problem
> [App does not update risk state GUI on Samsung S5 Mini](https://github.com/corona-warn-app/cwa-app-android/issues/1817) #1817.

sorry, hab den ganzen Tag gearbeitet! hier die Datei, vielen Dank für deine Arbeit! 



> @phakrkr
> 
> > beim Exposure-Log, war ich mir jetzt nicht sicher. meinst du die .json Datei, die bei "exportieren" erstellt wird?
> 
> Genau die Datei all-exposure-checks.json holen,
> die dann auf all-exposure-checks.json.txt umbenennen (weil GitHub .json blockiert)
> und dann hier posten.
> 
> Dein Problem hat große Ähnlichkeiten zu einem bereits gemeldeten Problem
> [App does not update risk state GUI on Samsung S5 Mini](https://github.com/corona-warn-app/cwa-app-android/issues/1817) #1817.

sorry, habe den ganzen Tag gearbeitet. da ich leider nicht weiß, wie man hier eine Datei anhängt (sorry!) füge ich es jetzt so an:

`[{"timestamp":"15. Dezember 2020, 06:18","keyCount":344507,"matchesCount":0,"appName":"Corona-Warn","hash":"i9hYZRg+xXQoFv9mJ5wzPKRnUWAa6ThYB61IQXzN4GU="},{"timestamp":"14. Dezember 2020, 07:57","keyCount":339872,"matchesCount":0,"appName":"Corona-Warn","hash":"TciuYpeECaVcSJRtkGNiNqr7n\/0n4gnGwhR\/ulRu4qo="},{"timestamp":"13. Dezember 2020, 08:12","keyCount":335449,"matchesCount":0,"appName":"Corona-Warn","hash":"A\/S3ewPd58XGZdMkwaj2vpHl8chw4w43r0qynbMT+4I="},{"timestamp":"12. Dezember 2020, 08:15","keyCount":326522,"matchesCount":0,"appName":"Corona-Warn","hash":"z2bsXGzhWNWFXxnIUY23GfjCLMSv+u4Lfl3HdRXq7lc="},{"timestamp":"11. Dezember 2020, 08:20","keyCount":311645,"matchesCount":0,"appName":"Corona-Warn","hash":"WMe335ljnpCcEaOXr4rhf9tPNmEYveBuoetL9nJkDa0="},{"timestamp":"10. Dezember 2020, 07:34","keyCount":300200,"matchesCount":0,"appName":"Corona-Warn","hash":"AHXIvAlkdJiGfDXi0ckvRaDzueRL1PHT1sBS0q4v4Jc="},{"timestamp":"9. Dezember 2020, 01:06","keyCount":287527,"matchesCount":0,"appName":"Corona-Warn","hash":"cB6tOQMxnOENds7wdZXsLCTQGxh9rrQ3qPTWbwGAjig="},{"timestamp":"8. Dezember 2020, 06:16","keyCount":275542,"matchesCount":0,"appName":"Corona-Warn","hash":"lTrkBx7HpVd6eJHAuR\/AgW0UikpEhaIZKBfyt2r2pi0="},{"timestamp":"7. Dezember 2020, 09:01","keyCount":278094,"matchesCount":0,"appName":"Corona-Warn","hash":"cvRWwYRcSTOz++FwyFSIyMDkke6sd8LNR4vnmwVTLBE="},{"timestamp":"6. Dezember 2020, 09:47","keyCount":277384,"matchesCount":0,"appName":"Corona-Warn","hash":"zdyV7+4\/reGgrxXhoJTUAGRyvXIXgJXpZbpAehGV\/F4="},{"timestamp":"5. Dezember 2020, 06:35","keyCount":275135,"matchesCount":0,"appName":"Corona-Warn","hash":"O2f+PAY6wg1to\/\/Qya2OOCl8n6KUK\/P0S61QVJAjSeo="},{"timestamp":"4. Dezember 2020, 08:14","keyCount":274440,"matchesCount":0,"appName":"Corona-Warn","hash":"A3SdeM\/zWuJWaLL1EHUWXl7BJmk5Jbr1SXPOe++dO\/o="},{"timestamp":"3. Dezember 2020, 08:43","keyCount":276324,"matchesCount":0,"appName":"Corona-Warn","hash":"tn4ehPtYWp\/WXtLpxBHQR4KLgPfY9VHOPog\/OEwoBo8="},{"timestamp":"2. Dezember 2020, 13:47","keyCount":276750,"matchesCount":0,"appName":"Corona-Warn","hash":"dSiRrR29Y1F3n\/J9Px1MFkOEpUc1J6SzbD4s60S1JmQ="},{"timestamp":"2. Dezember 2020, 08:17","keyCount":276750,"matchesCount":0,"appName":"Corona-Warn","hash":"DnU\/L7vFJa80\/bBJF3q36pvV3pgX\/FPmNf0aEBRfP4A="},{"timestamp":"1. Dezember 2020, 01:26","keyCount":273450,"matchesCount":0,"appName":"Corona-Warn","hash":"doNGAapikNgtkcwAVRFuR2A2HbvZ9VCIarkpWb6VI54="},{"timestamp":"30. November 2020, 07:21","keyCount":277797,"matchesCount":0,"appName":"Corona-Warn","hash":"1HcR08yzfXLJHfsB5IW8g+Fg0ILIaYjF+fXyvKy2Quo="}]`

>

**Comment by ndegendogo** [comment]
> da ich leider nicht weiß, wie man hier eine Datei anhängt

@phakrkr vom Handy aus habe ich das auch noch nicht geschafft. 🤷
Vom PC aus kann ich die Datei auf den Kommentar ziehen

**Comment by MikeMcC399** [comment]
@phakrkr 
Im Exposure Log sieht man, dass einmal täglich ein Exposure Check gemacht wird.
Wenn Du durchgängig eine WiFi-Verbindung hast, dann sollte bis zu 6-mal täglich ein Exposure Check durchgeführt werden. Mit ausschließlich Mobildaten wird das nur einmal am Tag gemacht. Ansonsten sind die Daten nicht auffällig.

Hier ist der [Helptext zu GitHub Attachments](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests).

**Comment by phakrkr** [comment]
hm alles klar. die meiste Zeit besteht eine WiFi Verbindung. dann warte ich einfach mal was passiert.. 

habe es tatsächlich vom Telefon aus probiert, da ging Drag&Drop nicht. 

Danke noch mal für die Mühe!

**Comment by AnOtherMuenchner** [comment]
Samsung released a firmware update right now. Let's see if this update fixes the problem

**Comment by thomasaugsten** [comment]
@AnOtherMuenchner Can you please give some details for which phone and the firmware version or release notes?

**Comment by AnOtherMuenchner** [comment]
@thomasaugsten 

Sorry, this was the wrong thread. The update was on my S5 mini. It was the first update provided by Samsung for long time and I did not expect any update for the old mobile at all. I will put the fact into the parallel S5 mini thread.

**Comment by phakrkr** [comment]
durch das Update auf Version 1.9.1 scheint das Problem behoben. Ein Android Update kam nicht und ich bezweifle, dass das jemals noch so sein wird, für dieses Modell.

**Comment by gehwissenlos** [comment]
Hallo zusammen,
ich erlaube mir, mein Problem mit ebenfalls einem Samsung-Gerät hier anzuhängen:
Samsung Galaxy Note 9, SM-N960
App-Version 1.9.1
Android 10

Meine Daten wurden seit 25.12. nicht mehr aktualisiert, obwohl das davor immer zuverlässig mehrmals am Tag funktioniert hat.

Gruß
Manuel

[all-exposure-checks.json.txt](https://github.com/corona-warn-app/cwa-app-android/files/5746545/all-exposure-checks.json.txt)
![Screenshot_20201228-095432_Google Play services](https://user-images.githubusercontent.com/6155210/103203119-883f4500-48f4-11eb-8bcb-96f2707a82c9.jpg)
![Screenshot_20201228-095452_Google Play services](https://user-images.githubusercontent.com/6155210/103203122-89707200-48f4-11eb-952d-795b02ea7d69.jpg)

**Comment by thomasaugsten** [comment]
@gehwissenlos Aktualisiert die App denn korrekt wenn du sie manuell öffnest?

**Comment by gehwissenlos** [comment]
Nein, auch wenn ich ein beenden erzwinge und danach die App öffne passiert nichts.
Gibt es noch andere Wege dies manuell anzustoßen?

**Comment by thomasaugsten** [comment]
@gehwissenlos Zeigt denn die App auch den 25.12 an?

**Comment by gehwissenlos** [comment]
Ja klar.

![Screenshot_20201228-125159_Corona-Warn](https://user-images.githubusercontent.com/6155210/103212624-9b114400-490b-11eb-914a-32729f675076.jpg)

**Comment by d4rken** [comment]
Da es sich sehr wahrscheinlich um unterschiedliche Ursachen handelt, habe ich ein neues Ticket erstellen.

@gehwissenlos @thomasaugsten Lasst uns in #2001 weiter das Problem behandeln.

---

Re-Closing this, please move any new discussions regarding missing exposure checks to #2001.
