### ISSUE TITLE
Unnecessary Deadman notification after power on

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#1895]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy A5 (2017) SM-A520F
- Android version: 8.0.0
- App version: 1.7.1

## Describe the bug

If a device has been powered off for more than 36 hours, when it is powered on, the deadman notification is displayed. This is an unnecessary warning if the device is able to immediately carry out an exposure check.

The Deadman notification is:
```
Corona-Warn
Your Risk Status
Please remember to open the Corona-Warn-App regu..
```

## Steps to reproduce the issue

1. CWA is installed and EXPOSURE LOGGING ACTIVE shows in status bar.
2. Power off device.
3. Wait a minimum of 36 hours.
4. Power on device.

The following screen shots show a device powered off after a successful exposure check at 09:17 on Dec 13, 2020. It was powered on again after more than 36 hours. Very soon afterwards, at 23:07 on Dec 14, 2020, the Deadman notification was shown. One minute later at 23:08 the Google Exposure checks UI shows that a successful exposure check was carried out.

(There is a gap of 37h 41m between the two exposure checks.)

---
![Deadman notification after power on](https://user-images.githubusercontent.com/66998419/102184114-3daed900-3eaf-11eb-8452-a76ec1d8488c.jpg)

---
![Exposure checks after power on](https://user-images.githubusercontent.com/66998419/102184144-48696e00-3eaf-11eb-8e28-2d02106d7e57.jpg)

## Expected behaviour

When the device is powered on, it should first attempt an exposure check, if scheduled. 

The deadman notification should then only appear if that exposure check failed and the last successful exposure check was more than 36 hours ago.

## Additional context

The truncated Deadman notification is covered in https://github.com/corona-warn-app/cwa-app-android/issues/1850

---
Internal Tracking ID:  [EXPOSUREAPP-4313](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4313)

**Comment by dsarkar** [comment]
Dear @MikeMcC399 

Thank you for your contributions.

We have created a ticket for the bug in the internal Jira system. Any further developments will be notified here in this Github issue.
  
Best wishes,
DS

---
Corona-Warn-App Open Source Team
Internal Tracking ID: [EXPOSUREAPP-4313](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4313)

**Comment by thomasaugsten** [comment]
We prefer to show this notification because of the different OEM behaviors on Android we would prefer to avoid additional complexity in the background and notification and ensure the app is really started manually after this long period of time where the app was not active.
