### ISSUE TITLE
Only see picture "C" starting Android App [no error message]

### ISSUE THREAD

**Issue by progro1** [corona-warn-app/cwa-app-android#1942]
## Technical details

- Device name:     Xiaomi Mi5S german
- Android version: 8..0.0 OPR1.170623.032
- App version: 1.7.1

## Describe the bug
If i start the app, only the picture 'C' (Corona Sign) is shown and stay. No error messages.
The battery save modus is off "Keine Beschränkung" for Corona App

## Additional context

Maybe i have done something in the settings, with overlay windows
 because i cannot also get Courses from the webull service in Info-Assistant and the setting "Zugänglichkeit" is setting back to off if i try to get the graph from courses

**Comment by MikeMcC399** [comment]
@progro1 
It sounds like you might have a network issue.

Can you open https://www.coronawarn.app/ on a web browser on your mobile device?

**Comment by progro1** [comment]
Hi Mike,

than you for your very fast response.

Websites (also coronawarn) opens regulary on Crome and Mi Browser.

It's a dedicated problem of overlay sites (i think).

At the moment i get this (no display of the site) also in some plugins "Einstellungen öffnen" in the APP TV-Browser.

I don't Know what i have disabled and didn't find any hints in internet at the moment

 

Thanks in advance

progro

 
 

Gesendet: Freitag, 18. Dezember 2020 um 11:35 Uhr
Von: "Mike McCready" <notifications@github.com>
An: "corona-warn-app/cwa-app-android" <cwa-app-android@noreply.github.com>
Cc: "progro1" <progro@gmx.de>, "Mention" <mention@noreply.github.com>
Betreff: Re: [corona-warn-app/cwa-app-android] Only see picture "C" starting Android App [no error message] (#1942)


 

@progro1
It sounds like you might have a network issue.

Can you open https://www.coronawarn.app/ on a web browser on your mobile device?

**Comment by MikeMcC399** [comment]
@progro1 
If you are having problems with other apps as well, then you need to do generic troubleshooting steps which are really out-of-scope for here.

You might want to check if your device has run out of free memory. Also try restarting your device or doing a reset for instance

**Comment by progro1** [comment]
Thank you, no out of memory and restart does not help.
A reset is not in my mind at the moment. 
If i get infos, i will post here and hope, it will help others

**Comment by d4rken** [comment]
Just to note: Wait at least  ~20 seconds. If this is caused by encryption issues, i.e. #642 , then the retry could will block for at most 10 seconds, you'd be stuck on the "C" screen (splash screen).

The splash screen may also been shown for longer durations on the very first time a new install (or new update is launched), if the system performs APK optimizations, when these happens depend a bit on the Android version.

The most straight forward way to debug this would be to log at systemlog (`logcat`) during the app launch.

**Comment by progro1** [comment]
With installation of 1.9.1 it is working now. This problem is solved...others waiting :-)
