### ISSUE TITLE
Avoid changing the name of the default launcher intention

### ISSUE THREAD

**Issue by arnowelzel** [corona-warn-app/cwa-app-android#1955]
After the last update on December 17, 2020, the app icon disappeared in the launcher and I had to add it again.

Eventhough the relevant parts of the manifest look untouched compared to the previous version (https://github.com/corona-warn-app/cwa-app-android/blob/main/Corona-Warn-App/src/main/AndroidManifest.xml#L55-L63) something was changed so the app was not in the launcher any longer. Please take care that this will not happen again. It is really irritating if apps just disappear on the home screen.

**Comment by dsarkar** [comment]
Hi @arnowelzel, many thanks for reporting. However, I would like to ask you, please, use the bug template when you open an issue here in this context. I suggest that close this issue and submit a new issue and fill out all the relevant parts, so we have right from the beginning some additional information. Many thanks and best wishes, DS.

---
Corona-Warn-App Open Source Team

**Comment by arnowelzel** [comment]
Where is the bug template?
