### ISSUE TITLE
Transnational country list not sorted alphabetically

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#1957]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy A50 SM-A505FN
- Android version: 10
- App version: 1.9.1

## Describe the bug
The transnational country list is not sorted alphabetically.
This is a regression from version 1.7.1.

## Steps to reproduce the issue

1. Tap EXPOSURE LOGGING ACTIVE
2. Tap Transnational Exposure Logging
3. Scroll down to heading "The following countries currently participate in transnational exposure logging:

![Country_list_1 9 1](https://user-images.githubusercontent.com/66998419/102689238-cc4b8f00-41fc-11eb-8aec-8ae2e9ba3d2a.jpg)

## Expected behaviour

The country list should be sorted alphabetically.

## Possible Fix

Sort the country list alphabetically.

## Additional context

Also mentioned in https://github.com/corona-warn-app/cwa-app-android/issues/1872

---
Internal Tracking ID: [EXPOSUREAPP-4417](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4417)

**Comment by dsarkar** [comment]
Thanks for reporting. DS

---
Internal Tracking ID: [EXPOSUREAPP-4417](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4417)
Corona-Warn-App Open Source Team

**Comment by PhilippNowak96** [comment]
I created a PR which will address this issue: #1961

**Comment by MikeMcC399** [comment]
Fixed in CWA 1.11.0 released on Jan 28, 2021.
