### ISSUE TITLE
ClassNotFoundException ExposureSummary on microG since 1.9.1

### ISSUE THREAD

**Issue by Diapolo** [corona-warn-app/cwa-app-android#1960]
## Technical details

- Device name: Fairphone 2
- Android version: Android 10 / LineageOS for microG ([lineage-17.1-20201203-microG-FP2.zip](https://download.lineage.microg.org/FP2/lineage-17.1-20201203-microG-FP2.zip))
- App version: 1.9.1
- ENF version: 204713000
- microG version: [v0.2.15.204713](https://github.com/microg/GmsCore/releases/tag/v0.2.15.204713)

## Describe the bug

I initially got the error **URSACHE: 9002 - ClassNotFoundException** today after upgrading from 1.7.1 to 1.9.1 right after opening CWA the first time during **Prüfung läuft...**. I didn't bother, but saw that my last update state in the app was stuck at yesterday 16:24 or something.

Today I tried to reset the app and got the same error at the same step **Prüfung läuft...**. After a few minutes I get the expected screen after a reset.

![CWA 9002 - 01](https://user-images.githubusercontent.com/1419649/102697674-e787c000-4237-11eb-915f-9f7b32b80691.jpg)

## Detailed screenshots

![Screenshot_20201219-202711_Corona-Warn](https://user-images.githubusercontent.com/1419649/102697814-12bedf00-4239-11eb-8497-155baa553a34.png)
![Screenshot_20201219-202724_Corona-Warn](https://user-images.githubusercontent.com/1419649/102697820-1e120a80-4239-11eb-94c3-54072e4c6a3b.png)
![Screenshot_20201219-202733_Corona-Warn](https://user-images.githubusercontent.com/1419649/102697821-20746480-4239-11eb-821c-97ebcd35f913.png)

## Steps to reproduce the issue

1. Reset the app and activate Risikoermittlung
2. **Daten werden herungergeladen...** is working
3. Error shows up in the **Prüfung läuft...** step

## Additional information

Exposure notification details (microG) is showing me that I got key updates right after resetting.
Also see: microg/GmsCore#1325

## Expected behaviour

A working app like I had with 1.7.1 ;).

**Comment by thomasaugsten** [comment]
Please open an issue in the microG repo it looks like the implementation is missing an Class

**Comment by Diapolo** [comment]
This was fixed by https://github.com/microg/GmsCore/commit/714367b3aa6aa3bcc8b7bd087a9ff01d53f5476a.

**Comment by nidico** [comment]
I can confirm this issue does not occur with CWA 1.9.1 on microg GmsCore v0.2.16.204713 (released today).
