### ISSUE TITLE
Incorrect exposure date displayed since 1.9.1 update

### ISSUE THREAD

**Issue by DavidJacob** [corona-warn-app/cwa-app-android#1963]
## Technical details

- Device name: Pixel 3
- Android version: 11
- App version: 1.9.1

## Describe the bug

My app is showing me as being an `Increased Risk` since December 17th after a data update at 18:49. My girlfriend got the notification, told me about it and I checked my phone (I didn't get a notification but she did see it very quickly). I took a screenshot at 18:51 on December 17th of the app:
![corona-app-2020 12 17](https://user-images.githubusercontent.com/4319427/102720751-722ef480-42f6-11eb-83ad-3236ea6c9df7.png)

On December 20th, some time after midnight my app updated to 1.9.1 and now when I check my phone I see this:
![corona-app-2020 12 20](https://user-images.githubusercontent.com/4319427/102720757-7d822000-42f6-11eb-9a82-4e560d9cb196.png)

And in the `Risk of Infection` part at the bottom of my `Risk Status` it tells me I was last exposed 2 days ago:
![corona-app-risk-status-2020 12 20](https://user-images.githubusercontent.com/4319427/102720835-04cf9380-42f7-11eb-812c-e3fc7638336a.png)

I can't square all this information, especially when I check the logs. I exported them today around 18:30. Here they are: 

[all-exposure-checks.txt](https://github.com/corona-warn-app/cwa-app-android/files/5721286/all-exposure-checks.txt)

I don't even see an exposure on the 9th when I visit this website: https://felixlen.github.io/ena_log/

## Expected behaviour

I expect to see the increased risk warning from December 17th and not an increased risk warning from December 9th when I seemingly didn't have an exposure. The days since last exposure text in `Risk of Infection` should also match the date displayed above it.

If I can provide any additional info, just let me know.

Related issues
---
- https://github.com/corona-warn-app/cwa-app-android/issues/1963
- https://github.com/corona-warn-app/cwa-app-android/issues/1964

---
Internal Tracking ID: [EXPOSUREAPP-4425](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4425)

**Comment by thomasaugsten** [comment]
Thanks for reporting this issue. It will be fixed in the next version with PR #1974

**Comment by dsarkar** [comment]
@DavidJacob, FYI PR Fix 1.10 #1974 DS

---
Corona-Warn-App Open Source Team

**Comment by DavidJacob** [comment]
@dsarkar @thomasaugsten thanks for the fast response! It looks like the PR fixes the display for `you were last exposed x days ago`. Is the fix for the displayed date of `Most recently on 9 Dec 2020` also included in this? Or am I missing something that that is actually correct? I just don't see it in my logs.

**Comment by thomasaugsten** [comment]
The most recently date was correct the whole time
