### ISSUE TITLE
Exposure date mismatch

### ISSUE THREAD

**Issue by TobiasAT22** [corona-warn-app/cwa-app-android#1964]
Exposure date mismatch
---

- This issue has been fixed by the developers.
- The fix is planned to be implemented for CWA release 1.10

Related issues
---

- https://github.com/corona-warn-app/cwa-app-android/issues/1963
- https://github.com/corona-warn-app/cwa-app-android/issues/1964
- https://github.com/corona-warn-app/cwa-app-android/issues/2000
- PR Fix 1.10 https://github.com/corona-warn-app/cwa-app-android/pull/1974

Corona-Warn-App Open Source Team

---

ORIGINAL POST
---

Device name: SM-G975F
Android version: 10
App version: CWA 1.9.1

![20201220_003454](https://user-images.githubusercontent.com/76408796/102724177-03f62c00-430e-11eb-8129-e6f0cc1b1782.jpg)

## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name:
- Android version:
- App version:

## Additional context

---

Related issues
---
- https://github.com/corona-warn-app/cwa-app-android/issues/1963
- https://github.com/corona-warn-app/cwa-app-android/issues/1964
- PR Fix 1.10 https://github.com/corona-warn-app/cwa-app-android/pull/1974
---
Internal Tracking ID: [EXPOSUREAPP-4425](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4425)

**Comment by MikeMcC399** [comment]
This issue looks very similar to the previous issue https://github.com/corona-warn-app/cwa-app-android/issues/1963.

**Comment by dsarkar** [comment]
Dear @TobiasAT22 

Thank you for your contribution.

Please provide additional information, please:
- Device name:
- Android version:
- App version: CWA 1.9.1

We have created a ticket for the bug in the internal Jira system. Any further developments will be notified in this Github issue https://github.com/corona-warn-app/cwa-app-android/issues/1963.
  
Best wishes,
DS

---
Corona-Warn-App Open Source Team
Internal Tracking ID: [EXPOSUREAPP-4425](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4425)

**Comment by TobiasAT22** [comment]
Device name: SM-G975F
Android version: 10
App version: CWA 1.9.1

**Comment by dsarkar** [comment]
Dear @TobiasAT22. Thanks for info, forwarded to developers. DS

---
Corona-Warn-App Open Source Team

**Comment by thomasaugsten** [comment]
Thanks for reporting this issue. It will be fixed in the next version with PR #1974

**Comment by dsarkar** [comment]
FYI 
- PR Fix 1.10 https://github.com/corona-warn-app/cwa-app-android/pull/1974
DS

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
Could this issue be re-opened until Version 1.10 is released?
If not, users may not find it and will likely create duplicate reports, such as #2000.

**Comment by dsarkar** [comment]
@MikeMcC399  agreed. Re-opened for visibility, avoiding duplicates. DS

**Comment by dsarkar** [comment]
Should be fixed now. Feedback appreciated. Thanks. DS

**Comment by MikeMcC399** [comment]
> Should be fixed now. 

Reference is:
https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.10.1
Fix incorrect "days since last encounter value" in tracing details (EXPOSUREAPP-4425) https://github.com/corona-warn-app/cwa-app-android/pull/1974

and blog announcing release of 1.10.1
https://www.coronawarn.app/en/blog/2020-12-28-corona-warn-app-version-1-10/ with staged roll-out over 48 hours.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks. Closing this issue now. 

@TobiasAT22, @DavidJacob, @tolzhabayev, and community, thanks for contributing. Best wishes, DS

---
Corona-Warn-App Open Source Team
