### ISSUE TITLE
Mis typo

### ISSUE THREAD

**Issue by teqnya** [corona-warn-app/cwa-app-android#1965]
please change **risik** to be a **risk** 
line 1282/en (key name:  @errors_risk_detection_limit_reached_description)

---
Internal Tracking ID:  [EXPOSUREAPP-4429](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4429)

**Comment by MikeMcC399** [comment]
In file https://github.com/corona-warn-app/cwa-app-android/blob/main/Corona-Warn-App/src/main/res/values/strings.xml

`<string name="errors_risk_detection_limit_reached_description">`

<string name="errors_risk_detection_limit_reached_description">"No more exposure checks possible today, as you have reached the maximum number of checks per day defined by your operating system. Please check your **risik** status again tomorrow."</string>

**Comment by dsarkar** [comment]
Dear @teqnya, @MikeMcC399,


Thanks for spotting this. 
We have created a ticket for the bug in the internal Jira system. Any further developments will be notified here in this Github issue.
  
Best wishes,
DS

---
Corona-Warn-App Open Source Team
Internal Tracking ID: [EXPOSUREAPP-4429](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4429)

**Comment by thomasaugsten** [comment]
Fixed with #1973
