### ISSUE TITLE
Google Play Store web view shows current version as 1.7.1

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#1966]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Android Pixel 3a Emulator
- Android version: 11
- App version: not installed

## Describe the bug
[Google Play Store web view](https://play.google.com/store/search?q=corona-warn-app&hl=en) https://play.google.com/store/search?q=corona-warn-app&hl=en shows the current version of the Corona-Warn-App as 1.7.1.

When the Google Play app is opened, the current version available for installation is correctly shown as 1.9.1.

## Steps to reproduce the issue

In Pixel 3a Android 11 emulator

---
1. Open Google Play app
2. Search for "corona-warn-app"
3. Tap on CWA icon on left side
4. Scroll down to "About this app" and view App info
5. Version is shown as 1.9.1

![Play Store from app](https://user-images.githubusercontent.com/66998419/102752535-02f2e800-436a-11eb-900d-94fd6fc6662f.png)

---
6. Close Google play App
7. Open web browser to page play.google.com
8. Search for "corona-warn-app"
9. Tap on app tile
10. Scroll down to "What's New" & "Additional Information"
11. Note that this view is showing the app updated on December 17, 2020, however the version is 1.7.1 (not 1.9.1) and the "What's New" information also refers to version 1.7.1

![Play Store from web](https://user-images.githubusercontent.com/66998419/102752288-9ed02400-4369-11eb-87cf-05a1484daf3a.png)

---

## Expected behaviour

Viewing the Corona-Warn-App in a web-browser on https://play.google.com/store/search?q=corona-warn-app&hl=en should show the current version as 1.9.1.

## Possible Fix

This is an inconsistency in the information display in the Google Play Store.

## Additional context

The availability of CWA Android 1.9.1 was announced five days ago on December 16, 2020 in https://www.coronawarn.app/en/blog/2020-12-16-corona-warn-app-version-1-9/.

**Comment by dsarkar** [comment]
@MikeMcC399, thanks for the report. Following you instructions I cannot reproduce this issue. This, with one difference, App is already installed. DS

**Comment by MikeMcC399** [comment]
@dsarkar 
Thank you for checking! The website has been displaying the wrong information for several days and I waited to see if it would correct itself. Now one hour after I reported it, the site https://play.google.com/store/search?q=corona-warn-app&hl=en is showing the correct 1.9.1 version. 🤷‍♂️ 

Closing as no longer reproducible. 🙂

**Comment by dsarkar** [comment]
@MikeMcC399,  They must have changed it just now ... ;-) Thanks again.
