### ISSUE TITLE
Contact Journal dates in German with English locale

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#2009]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Android Pixel 3a emulator
- Android version: 11
- App version: 1.10.1

## Describe the bug

The dates in the Contact Journal appear in German when the device is set to English.

## Steps to reproduce the issue

1. Settings > System > Languages and input > Languages
2. Set or add English (United Kingdom) as first language in list.
3. Open CWA
4. Scroll down and tap "MANAGE JOURNAL"
5. Note that the names of the days are German and the date format is German.

![image](https://user-images.githubusercontent.com/66998419/103345142-e1dc7680-4a90-11eb-8f15-f896f3c33e37.png)

## Expected behaviour

When the UI is displaying text in English, the dates in the Contact Journal should also be shown in English.

## Additional context

There are some other localisation issues with the Contact Journal, which I will put into separate issues.

---
Internal Tracking ID: [EXPOSUREAPP-4485](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4485)

**Comment by dsarkar** [comment]
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4485

**Comment by dsarkar** [comment]
I can confirm this issue also on SAMSUNG Galaxy Android 10 A21S CWA 1.10.1

**Comment by MikeMcC399** [comment]
Perhaps this is related to the requirements mentioned by @thomasaugsten in https://github.com/corona-warn-app/cwa-app-android/issues/2010#issuecomment-752636833 that the Gesundheitsamt prefers English?

Hopefully at least the dates displayed to the user in the overview screen of the Contact Journal can use the phones' locale and not be forced to be displayed using the German locale. I would expect to be the operator using this screen and not the health authority.

**Comment by dsarkar** [comment]
@MikeMcC399 

Actually, on iPhone 6s / iOS 14.3. / CWA 1.10.1  not an issue

![image](https://user-images.githubusercontent.com/1409741/103401333-b61cc780-4b48-11eb-9288-8ed1fe08e5a6.png)

**Comment by PhilippNowak96** [comment]
Opened a PR to fix this issue: #2021

**Comment by axelherbstreith** [comment]
@MikeMcC399 we merged the PR by @PhilippNowak96 so the issue should be fixed in the current version. 

Big thank you to both of you for reporting and fixing the issue 👍

**Comment by MikeMcC399** [comment]
@axelherbstreith 
Thank you for following through on this fix.

> ... so the issue should be fixed in the current version.

"current version" is a little ambiguous in this context. I assume you mean the current version under development, or next version planned for release. Otherwise the current version according to https://www.coronawarn.app/en/ is version 1.10.1.

**Comment by axelherbstreith** [comment]
> @axelherbstreith
> Thank you for following through on this fix.
> 
> > ... so the issue should be fixed in the current version.
> 
> "current version" is a little ambiguous in this context. I assume you mean the current version under development, or next version planned for release. Otherwise the current version according to https://www.coronawarn.app/en/ is version 1.10.1.

@MikeMcC399 Yes, sorry for the confusion. I meant the current version under development. 👍

**Comment by MikeMcC399** [comment]
"Localize dates in contact diary (EXPOSUREAPP-4485) (closes #2009)" https://github.com/corona-warn-app/cwa-app-android/pull/2021 is included in [v1.11.0-RC1](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.11.0-RC1).
