### ISSUE TITLE
Contacts and places are sorted case insensitive

### ISSUE THREAD

**Issue by Bananeweizen** [corona-warn-app/cwa-app-android#2012]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only (cannot check on Apple hardware)
* [X] Bug is not already reported in another issue

## Describe the bug

Contacts and places are sorted case insensitive. That makes it harder to find a contact again, if names are (accidentally) created with mixed lowercase and uppercase characters. UI elements sorted alphabetically should generally be case insensitive in all applications.

## Steps to reproduce the issue

1. Create contact "B".
2. Create contact "A1".
3. Create contact "a2".

## Expected behaviour

Contacts should be sorted A1, a2, B (case insensitive). Contacts are sorted A1, B, a2 (case sensitive).
The same issue exists for places.

## Possible Fix

If that is a Java collection being sorted, a second argument String.CASE_INSENSITIVE for the Collections.sort() call would be an appropriate fix.

---
Internal Tracking ID: [EXPOSUREAPP-4488](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4488)

**Comment by PhilippNowak96** [comment]
I created a PR (#2017) to fix this issue for persons, locations and the overview itself.

**Comment by dsarkar** [comment]
Dear @Bananeweizen, @PhilippNowak96, and community

Thank you for your contributions. We have created a ticket for the bug in the internal Jira system. Any further developments will be notified here in this Github issue.
  
Best wishes,
DS

---
Corona-Warn-App Open Source Team
Internal Tracking ID: [EXPOSUREAPP-4488](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4488)

**Comment by dsarkar** [comment]
Tested: not an issue in iOS 14.3 / iPhone 6s / CWA 1.10.1

**Comment by MikeMcC399** [comment]
"Fix sorting of persons and places to be case insensitive for names (EXPOSUREAPP-4488)(closes #2012)" https://github.com/corona-warn-app/cwa-app-android/pull/2017 is included in [v1.11.0-RC1](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.11.0-RC1).
