### ISSUE TITLE
Test Result Notification is displayed after user has already seen result and delayed

### ISSUE THREAD

**Issue by crcsn** [corona-warn-app/cwa-app-android#2016]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy S10
- Android version: 10
- App version: 1.9.1 / 1.10.1

## Describe the bug

I received two test results in the last few days, one with 1.9.1 and one with 1.10.1 As I was expecting the result, I checked the app regularly and was displayed the result inside the app. In both occasions, I received the notification about the test result ("You have new messages from your Corona-Warn-App") around 45 Minutes after I already saw the result inside the app. I saw my first the result at ~8:45, notification was displayed at 10:18. I saw my second result a few days later at ~11:45, notification was displayed at 12:31.

These are possibly two bugs:
1. The user should not be notified about the test result, if the user has already seen the result.
2. (more of a suggestion) The delay between availability of the result on the server and the sending of the notification seems to be quite substantial, especially given that a user is usually anxiously expecting a result. I know that no push mechanism is being used to data protection reasons, but imho the server should possibly be polled more often to result in less delay. This issue could obviously only be observed by me, because the notification was created, which I believe to be a bug in itself.

## Expected behaviour

1. Notification for available test result should not be created, if user has already seen test result
2. Delay between availability of test result and display of notification should be (significantly) reduced

## Additional context

--- 
Internal Tracking ID: [EXPOSUREAPP-4516](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4516)

**Comment by dsarkar** [comment]
@crcsn Thanks for reporting. We will raise this issue internally. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Dear @crcsn 

Thank you for your contributions. 
 We have created a ticket for the bug in the internal Jira system. Any further developments will be notified here in this Github issue. 
   
Best wishes, 
DS 

--- 
Corona-Warn-App Open Source Team 
Internal Tracking ID: [EXPOSUREAPP-4516](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4516)

**Comment by MikeMcC399** [comment]
@crcsn 

Your issue is listed as fixed in [Version 1.11.0](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.11.0)
"Abort test result available notification scheduling when viewed (EXPOSUREAPP-4516) #2105".

I guess it is unlikely you will be in a situation again where you can test exactly this situation, so I wonder if you want to close the issue anyway?

**Comment by crcsn** [comment]
Yes, great the main issue was fixed! And indeed, I will most likely not be able to test that soon.

The time difference between the actual availability of the test result and the creation of the notification (due to the polling mechanism) now cannot really be observed by the user any longer, which at least creates an illusion of trust for the user, which is fine by me.
