### ISSUE TITLE
Remove old Kotlin Android Extensions plugin

### ISSUE THREAD

**Issue by PhilippNowak96** [corona-warn-app/cwa-app-android#2022]
## Avoid duplicates
* [x] This enhancement request has not already been raised before
* [x] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [x] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation
The CWA currently uses the Kotlin Android Extensions plugin at some places for Kotlin synthetics and for Kotlin Parcelize.

## Suggested Enhancement
Due to the deprecation of the Kotlin Android Extensions plugin it should be removed. The usages of Kotlin synthetics can be replaced by the already introduced Jetpack view binding (usages in custom views by findViewById respectively) and for the Kotlin Parcelize part there is a standalone plugin now. See: https://developer.android.com/topic/libraries/view-binding/migration

## Expected Benefits
Future proof implementation and unification of view binding technologies (KS was only used at some very few places).

## Additional notes
I will open a PR for this soon and link it here.

PR: #2023 

---
Internal Tracking ID: EXPOSUREAPP-4495

**Comment by heinezen** [comment]
Hello @PhilippNowak96 ,

Thank you for your suggestions and your contribution! We have created a ticket in our internal Jira for your request. The developers will now have a look at your proposal and make review. 

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by d4rken** [comment]
Closed via #2023 :+1:
