### ISSUE TITLE
[security] Use incognito mode (IME_FLAG_NO_PERSONALIZED_LEARNING) for the keyboard

### ISSUE THREAD

**Issue by chris400** [corona-warn-app/cwa-app-android#2025]
When filling the contact list in CWA, the app should use the _incognito mode_ of the keyboard aka [IME_FLAG_NO_PERSONALIZED_LEARNING](https://developer.android.com/reference/android/view/inputmethod/EditorInfo#IME_FLAG_NO_PERSONALIZED_LEARNING)
(Example of other apps: Google Chrome in incognito mode and Threema Messenger)

## Avoid duplicates
* [X] This enhancement request has not already been raised before
* [x] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [x] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
## Current Implementation
Currently the keyboard is used in the default behavior, which might send data to cloud services or store inputs locally.
## Suggested Enhancement
CWA should request incognito mode of the keyboard.
## Expected Benefits
Increased privacy, increased acceptance, increased user count

---
Internal Tracking ID: [EXPOSUREAPP-4675](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4675)

**Comment by dsarkar** [comment]
Dear @chris400,

Thank you for your contributions. 
We have created a ticket for this wishlist item in the internal Jira system. Any further developments will be notified here in this Github issue. 
   
Best wishes, 
DS 
  
--- 
Corona-Warn-App Open Source Team 
Internal Tracking ID: EXPOSUREAPP-4675

**Comment by cyb3rko** [comment]
Implemented, can be closed.

**Comment by dsarkar** [comment]
@chris400 @cyb3rko Thanks for contributing and feedback. Best, DS

---
Corona-Warn-App Open Source Team
