### ISSUE TITLE
Day counter is wrong

### ISSUE THREAD

**Issue by markusmarkusz** [corona-warn-app/cwa-app-android#2027]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Pixel 3a
- Android version: Android 11 (Dec. Patch)
- App version: 1.10.1

## Describe the bug

The cell phone was off for days. Even so, the app says the detections were active for the last 14 days.
Shouldn't be like that, because that's simply not the case.

## Steps to reproduce the issue
Idk.
![Screenshot_20210103-084607.jpg](https://user-images.githubusercontent.com/7966992/103485248-44b57100-4df5-11eb-9995-370d1c0f1b8e.jpg)
![Screenshot_20210103-084528.jpg](https://user-images.githubusercontent.com/7966992/103485253-56971400-4df5-11eb-918d-09ac5a5e6bc4.jpg)
![Screenshot_20210103-084531.jpg](https://user-images.githubusercontent.com/7966992/103485258-59920480-4df5-11eb-8210-0f1b8868cdc7.jpg)

## Expected behaviour

It should say that the detection was not permanently active.

## Possible Fix

Check if there was really a checkup and add a message if it wasn't active within the last 14 days.

## Additional context

Don't know anything to add.
If this works as expectet then you should adapt the message anyway or add an info, otherwise the information is simply wrong.

**Comment by MikeMcC399** [comment]
@markusmarkusz 
This is a duplicate of the issue reported in "If device is turned off, it is still counted as active exposure notification" https://github.com/corona-warn-app/cwa-app-android/issues/929.

**Comment by markusmarkusz** [comment]
Ah. Sorry
