### ISSUE TITLE
After Positive Test Result: Warn Others results in "4000 Etwas ist schiefgelaufen. Error during web request: code=400"

### ISSUE THREAD

**Issue by KlugB** [corona-warn-app/cwa-app-android#2035]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: LG G4
- Android version: 6.0
- App version: 1.10.1  - ENF Version: 18204516000

## Describe the bug

Error message "4000 Etwas ist schiefgelaufen. Error during web request: code=400"

## Steps to reproduce the issue

Andere Warnen - Einverstanden - Symptomerfassung - Symptom-Beginn - Fertig - "Datenabruf"

![image](https://user-images.githubusercontent.com/25726929/103761785-858cd000-5017-11eb-929b-e9e09989d85c.png)
![image](https://user-images.githubusercontent.com/25726929/103761860-a48b6200-5017-11eb-9db8-b9956960ea2d.png)

So it seems impossible on my device to share my "Zufalls-IDs" with others.

It is definitely not a network/firewall problem. Tried rebooting. All other apps have normal network access.

---

PR #2161

--- 
Internal Tracking ID: [EXPOSUREAPP-4515](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4515)

**Comment by dsarkar** [comment]
@KlugB, Thanks for reporting. 

- Did you try this https://www.coronawarn.app/en/faq/#access-list?

**Comment by MikeMcC399** [comment]
@dsarkar 
https://www.coronawarn.app/en/faq/#access-list is about http error 901 (see https://github.com/corona-warn-app/cwa-app-android/issues/785 and https://github.com/corona-warn-app/cwa-app-android/issues/1124)

Perhaps this error (code = 400) is a bad http request?

**Comment by MikeMcC399** [comment]
@KlugB 
Sorry to read that you have been tested positive! I hope things go well for you!

You might want to try submitting your test result without inputting symptoms, in case there is something wrong in the symptom part of the code. That way you might at least be able to warn other people without delay. The only difference is that the calculation about how infectious you were at the time of each contact will not be so specific.

**Comment by KlugB** [comment]
> Sorry to read that you have been tested positive! I hope things go well for you!

Not my phone, though, but my partners. Anyway, I have been tested positive, too, a couple of days earlier. The process worked fine on my LG G8s then. I most likely won't die, but I totally lost my sense of smell - cannot recommend this for sure. Stay healthy guys.

> You might want to try submitting your test result without inputting symptoms, in case there is something wrong in the symptom part of the code. That way you might at least be able to warn other people without delay. The only difference is that the calculation about how infectious you were at the time of each contact will not be so specific.

I tried this, resulting in the same error.

**Comment by MikeMcC399** [comment]
@KlugB 
> I tried this, resulting in the same error.

It was worth a try with re-submitting, even if that was a long shot. We'll have to wait for more specific feedback from the Open Source Team.

All the best to both of you!

**Comment by dsarkar** [comment]
Dear @KlugB,
 
Thanks for reporting. We have created a ticket for the bug in the internal Jira system. Any further developments will be notified here in this Github issue. 
 
Best wishes, 
DS 
  
--- 
Corona-Warn-App Open Source Team 
Internal Tracking ID: EXPOSUREAPP-4515

**Comment by MikeMcC399** [comment]
@KlugB
It may be that your issue is not going to get investigated and fixed fast enough to use the test result of your partner to warn others. If you are concerned about that part you could delete the test (perhaps take a screen shot first so you have some evidence) and then contact the TAN hotline (telephone 0800 7540002) (see https://www.coronawarn.app/en/faq/#who_can_help) to request a TAN. There is no guarantee that submitting a TAN on the phone with the problem will work better than submitting directly from the positive test result received on the phone. Deleting the test would of course stop any further investigation on the phone about the original problem you reported. You probably need to weigh up the pros and cons including the effort to request a TAN if you decide to try this.

**Comment by dsarkar** [comment]
FYI PR https://github.com/corona-warn-app/cwa-app-android/pull/2161

**Comment by MikeMcC399** [comment]
[Version 1.12.0](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.12.0), which is now released includes "Error message after positive test result (EXPOSUREAPP-4515)" #2161.

**Comment by dsarkar** [comment]
Hi @KlugB, @MikeMcC399 mentioned this issue has been fixed. Please, close this issue. Many thanks for contributing here! Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
@KlugB Thanks.

Thanks to everybody for contributing here! Best regards,  DS

---
Corona-Warn-App Open Source Team
