### ISSUE TITLE
Typo: "You result is being updated" when polling for test results.

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#2046]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
I searched in https://github.com/corona-warn-app/cwa-app-ios and could not find the incorrect string there, so I assume that the issue only affects Android, not iOS.
* [X] Bug is not already reported in another issue

## Technical details

- App version: 1.10.1

## Describe the bug

After test submission when results are being checked, the message
`"You result is being updated"` 
appears. This is a typo / grammatical translation error.

## Steps to reproduce the issue

1. Set device language to English
2. Open CWA app after having previously registered a test with a QR code.

## Expected behaviour

The text should say
`"Your result is being updated"` 

## Possible Fix
In https://github.com/corona-warn-app/cwa-app-android/blob/4f7664467cb9be280f39e5e61f9e0eb5f6063613/Corona-Warn-App/src/main/res/values/strings.xml#L1148

`submission_status_card_body_fetching`
<string name="submission_status_card_body_fetching">"You result is being updated"</string>
should be changed to
"Your result is being updated"

## Additional context

Incorrect string is also present in release/1.11.x branch

---
Internal Tracking ID: [EXPOSUREAPP-4443](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4443)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks. DS


---
Corona-Warn-App Open Source Team 
Internal Tracking ID: [EXPOSUREAPP-4443](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4443)

**Comment by MikeMcC399** [comment]
@dsarkar 
What does the label "Fix 1.11" mean? 
- fix planned but not done?
- fix already in changed code?

The string is not fixed in [1.11.0-RC1](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.11.0-RC1).

https://github.com/corona-warn-app/cwa-app-android/blob/892361b38cd79c40256519a20970b41314762552/Corona-Warn-App/src/main/res/values-en/strings.xml#L1142-L1143

**Comment by thomasaugsten** [comment]
Will be fixed in 1.11 
Translation PR will arrive this week

**Comment by dsarkar** [comment]
Hi @MikeMcC399, 

We use this label when we can see in written (usually in the JIRA tickets) that this fix is either completed or planned for (in this case) release 1.11 or if related PRs in the right branch.  Ideally, we the fix is already in the corresponding branch, but sometimes it is not implemented yet. 

Regarding this Fix-labels, which we introduced only recently (actually your suggestion), our thoughts/intentions are the following: Once the release is published, it is very easy to find issues related to this fix and to cross-check if the issue was resolved and can be closed. If not resolved, we would remove this label. 

![image](https://user-images.githubusercontent.com/1409741/104359966-a3bf6800-5510-11eb-86e0-d0b28d12ccf4.png)

**Comment by MikeMcC399** [comment]
@dsarkar 
Thank you very much for explaining about the use of the Fix version labels. I think this is very useful.

The code changes in GitHub are mostly very transparent, so it is easy to check up on status of that part of the apps. It becomes more difficult for strings and translations because of the offline work being done outside of GitHub.

For any future typo corrections, is the best way to open a separate issue or does it make sense instead to open a PR? It is more complicated to describe an issue with steps to reproduce instead of directly editing an affected string, but if PRs don't fit the process for text corrections then I guess we have to use issues.

**Comment by dsarkar** [comment]
@MikeMcC399 feedback regarding your comment https://github.com/corona-warn-app/cwa-app-android/issues/2046#issuecomment-759284493:


- For any text correction in target languages - EN, BG, PL, RO, TR they do not need a PR but only an information on in which file it is (Android or iOS) and the text key. They do the correction in the translation environment and deliver it to the development repository for the required release.

**Comment by MikeMcC399** [comment]
@dsarkar 
Thank you for clarification on the process!

This issue has been fixed by the translation delivery https://github.com/corona-warn-app/cwa-app-android/pull/2088 into [v1.11.0-RC2](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.11.0-RC2) 🙂 

I would still leave the issue open here until 1.11.x has been released, just in case somebody else notices the issue and searches for an open topic.

**Comment by MikeMcC399** [comment]
Fixed in CWA 1.11.0 released on Jan 28, 2021.

https://github.com/corona-warn-app/cwa-app-android/blob/a204c6ada1d05ba26ca54c341e69f4ff416f2ca8/Corona-Warn-App/src/main/res/values/strings.xml#L1181-L1182
