### ISSUE TITLE
Risk card not up-to-date with last exposure check in Google log

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#2061]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue
There have been similar issues reported, but I think this is a different situation.

## Technical details

- Device name: Samsung Galaxy A5 (2017) SM-A520F
- Android version: 8.0.0
- App version: 1.10.1
- Exposure Notification System version: 18204714000

## Describe the bug

The risk card Updated: date / time does not correspond to the latest exposure check shown in the Google UI.

In the screen shots below, Google shows exposure checks at 13:34 and 17:34 on Jan 9, 2021.
CWA shows the last exposure check occurring at 13:34.

---
![Updated today](https://user-images.githubusercontent.com/66998419/104106585-5eecc480-52b7-11eb-9e36-ed612cc9bf43.jpg)

---
![Exposure checks](https://user-images.githubusercontent.com/66998419/104106588-614f1e80-52b7-11eb-8fcc-7c6e2574d3fb.jpg)

## Steps to reproduce the issue

These are the steps to view the issue when it occurs. I do not yet have a reliable set of steps to reproduce the issue under all circumstances.

1. Open CWA and view the date / time shown on the risk card e.g. Updated: Today, 13:34
2. In CWA select the three-dot overflow menu > App Information, then tap the ENF Version information at the bottom of the screen.
3. Tap Exposure checks
4. Note the latest time-stamp in the list of exposure checks e.g. 17:34
5. Compare the time-stamp from CWA with the time-stamp from Google.

Restarting the device doesn't cause the CWA time-stamp to be updated.

Setting the device's time to 5 hours after the last recorded exposure check according to the Google time-stamp causes CWA to run a risk check immediately and the time-stamp in CWA is then shown correctly as the current time.

## Expected behaviour

The time-stamp of the latest exposure check listed in CWA should correspond to the latest exposure check in Google (with leeway of +/- 5 minutes due to some logging inaccuracies).

## Possible Fix

It seems like the risk card is not getting updated if CWA is opened before it is time for a new exposure check. If CWA is later opened and CWA performs an exposure check in the foreground, then the "updated" time-stamp becomes correct again.

## Additional context

CWA has generally been working reliably on this device for some months always using the latest released version.

---
Internal Tracking ID: [EXPOSUREAPP-4566](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4566)

**Comment by MikeMcC399** [comment]
Today I opened the app at 09:17 after seeing that Google had done a check at 09:14. CWA just hung for more than 10 minutes displaying "Check is running ..." with the animated circle moving around.

I have now reset the app and I will be watching what happens now.

**Comment by MikeMcC399** [comment]
Resetting the app did not solve the problem.
I reset at 09:31 today.

At 18:39 today CWA is still showing Updated: Today, 09:31 whereas
Settings > Google > COVID-19 Exposure Notifications > Exposure checks 
shows
10 JANUARY
**16:13**
09:31

So CWA is not showing the exposure check which Google logged being done at 16:13.

The device was plugged into a charger all day.

Let me know please if you need more information.

**Comment by d4rken** [comment]
Thanks for the extensive debugging efforts. Some thoughts:

The timestamp on the card is the `startedAt` date of the latest **successful** submission:

https://github.com/corona-warn-app/cwa-app-android/blob/4f7664467cb9be280f39e5e61f9e0eb5f6063613/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/modules/detectiontracker/ExposureDetectionTrackerExtensions.kt#L14-L22

The system log shows a timestamp so we did submit key packages, but we don't show the timestamp, so most likely the `ExposureDetectionTracker` does not flag that detection as successful, which would mean that the ENF did not send a broadcast or we did not receive it after the calculation is done:

https://github.com/corona-warn-app/cwa-app-android/blob/4f7664467cb9be280f39e5e61f9e0eb5f6063613/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/receiver/ExposureStateUpdateReceiver.kt#L36

The `ExposureDetectionTracker` will mark any outstanding calculation as "timed out" after ~15min:

https://github.com/corona-warn-app/cwa-app-android/blob/4f7664467cb9be280f39e5e61f9e0eb5f6063613/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/nearby/modules/detectiontracker/DefaultExposureDetectionTracker.kt#L47

During that timeout duration, if the app is opened, it should display the "Prüfung läuft" card. I currently don't know why we wouldn't receive the broadcast. Especially when plugged into a charger, I would have considered it as least affected by any energy saving measures.

:thinking:

**Comment by MikeMcC399** [comment]
@dsarkar 
Thanks for your detailed explanation of how things are supposed to work! I will continue to monitor and report back how the app behaves.

**Comment by MikeMcC399** [comment]
@d4rken 
After deleting app data the condition came up again after the second scheduled exposure check. To put the device back to a defined state I did a factory reset and reinstalled CWA. Otherwise there are now only preinstalled apps on the device.

So the Google exposure check log now shows
12 JANUARY
10:01
with which CWA also agrees.

I will continue to monitor by looking into the Google log at roughly 4 hours intervals and if there is a new exposure check I will only then open up CWA to see if the latest exposure is displayed there as well. If I do get the error condition again, I will capture a bug report just in case that might be of any use.

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-4566](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4566)

**Comment by MikeMcC399** [comment]
@d4rken 
The factory reset has stopped the issue from occurring. 

Previously one of two things were happening:
- Either CWA was not showing the latest exposure check from the Google log or
- CWA was hanging showing "Check is running ..."
This would fit in with a communications breakdown via Broadcast.

I will give it another day and if the problem doesn't come up again then I will close this issue.

**Comment by MikeMcC399** [comment]
My monitoring was interrupted yesterday by the Google Exposure Notification System major outage covered in https://github.com/corona-warn-app/cwa-app-android/issues/2081 which has since been resolved (see https://github.com/corona-warn-app/cwa-app-android/issues/2081#issuecomment-759964666).

I am currently not seeing the problem described in this issue. Exposure checks are working as expected and background exposure checks are occurring every 4 hours with the device connected to a charger.

The steps to reproduce concerning accessing the Google exposure check log have changed, since Google has updated the UI.
Settings > Google > COVID-19 Exposure Notifications
continues to show Version 18204714000 however this page no longer shows any timestamp of the last exposure check. To access the log of exposure checks, tap the three-dot overflow menu and select "Exposure checks". The list of exposure checks is sorted chronologically with the latest entry at the top of the list.
Compare the top date & time from this list with the timestamp on the risk card of CWA, such as "Updated: Today, hh:mm".

Last night and this morning, the two timestamps from Google and CWA continued to agree, therefore I am closing this issue as no longer occurring.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks.
