### ISSUE TITLE
Wrong spelling for Finland in English / Finnland in German

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#2069]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy A50 SM-A505FN
- Android version: 10
- App version: 1.10.1

## Describe the bug
1) The country Finland is shown as "Finnland" when the device is set to display English.
2) The country Finland is shown as "Finland" when the device is set to display German.

These are both incorrect spellings for the languages concerned.

### English language
1. Set device preferred language to English (United Kingdom)
2. Open CWA, tap EXPOSURE LOGGING ACTIVE
3. Tap Transnational Exposure Logging
4. Scroll down to the section showing flags and country names
5. Note that "Finnland" is in the list.

### German language
1. Set device preferred language to Deutsch (Deutschland)
2. To work around issue reported in https://github.com/corona-warn-app/cwa-app-android/issues/1958 Settings > Apps > Corona-Warn > Force stop
2. Open CWA, tap RISIKO-ERMITTLUNG AKTIV
3. Tap Länderübergreifende Risiko Ermittlung
4. Scroll down to the section showing flags and country names
5. Note that "Finland" is in the list.

## Expected behaviour

- The country should be displayed as "Finland" when the device UI is set to English. (See https://finland.fi/ for confirmation about spelling.)

- The country should be displayed as "Finnland" when the device UI is set to German. (See https://finland.fi/de for confirmation about spelling.)

## Possible Fix

In https://github.com/corona-warn-app/cwa-app-android/blob/main/Corona-Warn-App/src/main/res/values-en/strings.xml 
`country_name_fi`
change
"Finnland" to "Finland"

https://github.com/corona-warn-app/cwa-app-android/blob/main/Corona-Warn-App/src/main/res/values-de/strings.xml
`country_name_fi`
change
"Finland" to "Finnland"

---
Internal Tracking ID : [EXPOSUREAPP-4565](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4565)

**Comment by Ein-Tim** [comment]
> Please check for iOS and move if necessary.

Not a problem under iOS, "Finland" in English and "Finnland" in German.

**Comment by MikeMcC399** [comment]
@PhilippNowak96 
I'm not sure whether your change will get overwritten on not if you try to get it merged.

See https://github.com/corona-warn-app/cwa-app-android/blob/main/.github/pull_request_template.md
To the Community ❤️:
- The PR can not contain changes in localization files, e.g. values-[LANGUAGE-CODE]/strings/* and / or assets/* (see #332 for further information).

**Comment by PhilippNowak96** [comment]
Yes, I'm aware of this but I thought as it's such a little change which does not needed any additional translation work it might be approved and played back to their translation system. If not, it's fine for me, was a quick one 😄

**Comment by dsarkar** [comment]
Internal Tracking ID : [EXPOSUREAPP-4565](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4565)

**Comment by MikeMcC399** [comment]
"Fix typo in german and english strings for finland country name (EXPOSUREAPP-4565) (closes #2069) #2072" https://github.com/corona-warn-app/cwa-app-android/pull/2072 was corrected in [v1.11.0-RC1](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.11.0-RC1).
