### ISSUE TITLE
Missing word "case" in the text for submission_test_result_pending_steps_waiting_body

### ISSUE THREAD

**Issue by mgrolinger** [corona-warn-app/cwa-app-android#2070]
## Describe the bug
The current text for the the waiting period "Your test result is not available yet." is missing the word 'case' the third paragraph.
The text is the following: "In you are notified of a positive test result..." 

## Steps to reproduce the issue
1. Register a test
2. See in the description of the text for the pending test results in the lower part of the display.

## Expected behaviour
The correct text should be "In case you are notified of a positive test result..."

---
Internal Tracking ID: [EXPOSUREAPP-4567](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4567)

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-4567](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4567)

**Comment by dsarkar** [comment]
Hi @mgrolinger, 

Thanks for reporting. The plan is to change the text in release 1.11. Best wishes, DS


---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@mgrolinger 
The text `submission_test_result_pending_steps_waiting_body` has been updated:

---
"As soon as your test result becomes available, it will be displayed in the app.

You will also receive your test result outside of the app. The public health authorities will notify you, should your test be positive.

If you are notified of a positive test result outside the app, please remove the test currently registered in the app. Call the number shown under “Request TAN” to get a TAN. You can then use this TAN to register your result in the app and warn others."

---

So "**In** you are notified of a positive test result..." has become "**If** you are notified of a positive test result...".

I've checked this in CWA Android 1.11.0, which was released on Jan 28, 2021, by scanning in a test QR code, so I think this issue can be closed.

**Comment by dsarkar** [comment]
@MikeMcC399 Again, thanks for checking. 
@mgrolinger Thanks for reporting. Please, close this issue.

Best wishes, DS
