### ISSUE TITLE
Android Corona App does not report the (negative) result of PCR test made in hospital

### ISSUE THREAD

**Issue by momcilo78** [corona-warn-app/cwa-app-android#2085]
## Avoid duplicates
* [x] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Question is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Question has not already been asked in another issue

## Your Question
* Question: My wife had 1st level contact with infected colleague in hospital where she works as nurse. Due to ongoing outbreak that occurred there among personnel and patients and some light symptoms, she took test on 10.01.2021 and registered the test in corona app via QR-Code. She got the negative result directly from the hospital yesterday (12.10.2021) on paper (Synlab), however the corona app does not display the result. What could be the reason for not receiving the result in electronic form?

**Comment by MikeMcC399** [comment]
@momcilo78 
The situation you describe is talked about in the FAQ
https://www.coronawarn.app/en/faq/#qr_test

You could check with Synlab if they are feeding test results to the Corona-Web-App.

**Comment by momcilo78** [comment]
@MikeMcC399 Synlab was feeding these results in the past, however it is not clear if this interaction involves human interaction. We are aware that more than colleague is affected by this issue. Meanwhile she made second test since first one was too early for detection, but this time as a "civilian" outside of the hospital, which is expected to be routed to the same lab.

**Comment by MikeMcC399** [comment]
@momcilo78 
> Synlab was feeding these results in the past, however it is not clear if this interaction involves human interaction. 

Only Synlab can tell you exactly how they do this. We can only give you a generic answer here.

You can see the process flow in https://github.com/corona-warn-app/cwa-documentation/blob/master/images/solution_architecture/figure_2.svg where at step 3 the lab works with their Laboratory Information System which feeds the Test Result Server.

The form which goes to the lab has a QR code on it which has the same GUID embedded in it as the form which is handed to the patient. The one which the patient receives has the additional string https://localhost/? prefixed to the GUID.

**Comment by momcilo78** [comment]
Hi @MikeMcC399,

Thank you for the precise information on the flow. The fact that results stopped coming worried me. Since this issue is outside of the app and infrastructure I think it is best to close this issue. Furthermore this is mostly about software development and I was not sure if there is a portal where people who actually operate the application can be notified about issues?

**Comment by MikeMcC399** [comment]
Hi @momcilo78 
>  I was not sure if there is a portal where people who actually operate the application can be notified about issues?

There is a technical hotline for the app listed in the app and on the bottom of https://www.coronawarn.app/en/ 0800 7540001, but I can't tell you if they can help with this type of operational issue. Apart from that, the Robert Koch Institute publishes the e-mail address CoronaWarnApp@rki.de for feedback.

**Comment by dsarkar** [comment]
@momcilo78 

Sorry for German post, I will translate later ....

**Comment by momcilo78** [comment]
@MikeMcC399  thank you for pointing out the RKI, they would be probably the most knowledgeable when it comes to the process, but my original concern was that something went wrong with the infrastructure.
@dsarkar Vielen Dank, aber die Übersetzung ist nicht notwendig.
