### ISSUE TITLE
a very long download

### ISSUE THREAD

**Issue by Drachenbauer** [corona-warn-app/cwa-app-android#2091]
The green field shows, that files are being downloaded.
Since this morning.
Can something need a whoole day to Download?

**Comment by DooMMasteR** [comment]
Downloads are slow and now the app is stuck at checking... Since 2 hours...

**Comment by DooMMasteR** [comment]
Duplicate of #2081

**Comment by dsarkar** [comment]
@Drachenbauer Thanks for reporting. Monitor this issue https://github.com/corona-warn-app/cwa-app-android/issues/2081, please. 

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
Duplicate of #2081
