### ISSUE TITLE
Notification to open app from time to time comes back every few minutes

### ISSUE THREAD

**Issue by nicolaus-hee** [corona-warn-app/cwa-app-android#2093]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Google Pixel 4 XL
- Android version: 11
- App version: 1.10.1

## Describe the bug

This afternoon, I got a notification asking me to periodically open CWA (I assume to avoid Android from killing it in the background to save battery). Never got this notification type before. I couldn't get rid of the notification, though:

Clicked on it, CWA opened and notification disappeared, closed the app. A few minutes later, the notification came back. I repeated opening CWA, notification disappeared again, closed again, notification came back again. Seems to be endless. Had this four times in a row now.

![Screenshot_20210113-163200-2](https://user-images.githubusercontent.com/48563755/104473976-d4a9a680-55bd-11eb-9285-a15b715172f8.png)

## Steps to reproduce the issue

Didn't really cause this. Phone was lying around since >60mins when the first notification popped up. Had opened the app yesterday, phone not restarted since then. As described above, notification keeps coming back without me doing anything.

## Expected behaviour

Reacting to notification / clicking on it should make it disappear for a while (days?).

## Additional context

I'm also affected by #2081 

---
Possibly related:
#2081 
Internal Tracking ID: [EXPOSUREAPP-4594](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4594) duplicate of
Internal Tracking ID: [EXPOSUREAPP-4592](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4592)

---
Internal Tracking ID: [EXPOSUREAPP-4623](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4623)
PR: https://github.com/corona-warn-app/cwa-app-android/pull/2128

**Comment by MikeMcC399** [comment]
@nicolaus-hee 
I expect your issue is directly related to https://github.com/corona-warn-app/cwa-app-android/issues/2081 which you referred to. I also got a monthly reminder from Google today, which I had never seen before. I'm also suffering from the problem which is stopping exposure checks running through.

The notification you are seeing is from
`risk_details_deadman_notification_body`
and the related code is being revised for the next release.  See https://github.com/corona-warn-app/cwa-app-android/pull/1999.
The English text is
"Please remember to open the Corona-Warn-App regularly to check your risk status."

After https://github.com/corona-warn-app/cwa-app-android/issues/208 is fixed, it would be good to see if the issue you reported is still causing you problems.

**Comment by dsarkar** [comment]
@MikeMcC399, @nicolaus-hee Thanks for reporting and putting context. For the time being tracked with same JIRA tickets. DS

**Comment by MikeMcC399** [comment]
@nicolaus-hee 
Has your phone recovered and is it behaving normally again?
There is a statement in https://github.com/corona-warn-app/cwa-app-android/issues/2081#issuecomment-759964666 about a Google issue and fix. For me everything was working again last night.

**Comment by nicolaus-hee** [comment]
> @nicolaus-hee
> Has your phone recovered and is it behaving normally again?

The notification hasn't come back, indeed.

**Comment by dsarkar** [comment]
@nicolaus-hee, @MikeMcC399 Thanks for contributing. We think this issue was indeed related to #2081 and can be closed now. Any objections?

**Comment by nicolaus-hee** [comment]
> @nicolaus-hee, @MikeMcC399 Thanks for contributing. We think this issue was indeed related to #2081 and can be closed now. Any objections?

None. Thank you.

**Comment by dsarkar** [comment]
Re-opened.
1. The reason for the notification has been fixed (EN-Google issue)
2. However, the notification **spam** issue is being addressed (fix planned for 1.12)

**Comment by dsarkar** [comment]
PR: https://github.com/corona-warn-app/cwa-app-android/pull/2128

**Comment by MikeMcC399** [comment]
[Version 1.12](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.12.0), which is now released, includes "Notification to open app from time to time comes back every few minutes (EXPOSUREAPP-4623)" #2128.

**Comment by dsarkar** [comment]
Dear @nicolaus-hee and community. Many thanks for your contributions here. See @MikeMcC399 comments above. Please close this issue. Thanks! Best wishes, DS


---
Corona-Warn-App Open Source Team

**Comment by nicolaus-hee** [comment]
Thank you

**Comment by dsarkar** [comment]
@nicolaus-hee Thanks again for contributing! Best, DS
