### ISSUE TITLE
Format of hardcoded error messages regarding security

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#2120]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue
See also https://github.com/corona-warn-app/cwa-app-android/issues/1214#issuecomment-754599565

## Technical details

- App version: ~~1.10.1~~ branch release/1.11.x

## Describe the bug
In the following string, the message is not capitalised:
https://github.com/corona-warn-app/cwa-app-android/blob/4f7664467cb9be280f39e5e61f9e0eb5f6063613/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/CwaWebSecurityException.kt#L8

In the following string, the message is not capitalised ~~and there is no space between the words "refer" and "to"~~

In 1.10.1
https://github.com/corona-warn-app/cwa-app-android/blob/4f7664467cb9be280f39e5e61f9e0eb5f6063613/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/CwaSecurityException.kt#L8-L9

In release/1.11.x
https://github.com/corona-warn-app/cwa-app-android/blob/a36cf7ee45d4b9ae68e52ad52e53a69958634a3e/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/CwaSecurityException.kt#L8-L9

## Steps to reproduce the issue

Code inspection only.

## Expected behaviour
The error message in
[CwaWebException.kt](https://github.com/corona-warn-app/cwa-app-android/blob/main/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/http/CwaWebException.kt)
should be formatted consistent with the capitalisation of other similar error message in the app:
![image](https://user-images.githubusercontent.com/66998419/104813654-cf8d6700-580a-11eb-85a9-d1a8b5271ed3.png)

The error message in 
[CwaSecurityException.kt](https://github.com/corona-warn-app/cwa-app-android/blob/main/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/CwaSecurityException.kt)
should be capitalised ~~and contain a space between the words "refer" and "to"~~.

## Possible Fix
Capitalise the first word in the error message string of [CwaWebException.kt](https://github.com/corona-warn-app/cwa-app-android/blob/main/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/http/CwaWebException.kt)
    "an error occurred while trying to establish a secure connection to the server",
to
    "An error occurred while trying to establish a secure connection to the server",

Capitalise the first word in the error message string of
[CwaSecurityException.kt](https://github.com/corona-warn-app/cwa-app-android/blob/main/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/CwaSecurityException.kt) ~~and add a space at the end of the string so that~~
    "something went wrong during a critical part of the application ensuring security, please refer" +
becomes
    "Something went wrong during a critical part of the application ensuring security, please refer" +

## Additional context

Please let me know if the Open Source Team would like a pull request for the above suggested changes and if so what the target branch should be (release/1.n.x).

---
[EXPOSUREAPP-4655](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4655)

**Comment by PhilippNowak96** [comment]
Missing space is already fixed with 1.11, see https://github.com/corona-warn-app/cwa-app-android/blob/a36cf7ee45d4b9ae68e52ad52e53a69958634a3e/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/CwaSecurityException.kt#L8-L9

**Comment by MikeMcC399** [comment]
@PhilippNowak96 
> Missing space is already fixed with 1.11

Thank you for checking! Whilst I was writing this issue I had a nagging thought that I ought to check later branches, but since I had reported the problem in https://github.com/corona-warn-app/cwa-app-android/issues/1214#issuecomment-754599565 and there was no feedback there I thought that no action was being taken. Well I was wrong to make that assumption!

I have updated the issue description now accordingly.

**Comment by MikeMcC399** [comment]
PR #2121 created.

**Comment by dsarkar** [comment]
@MikeMcC399 Feedback: Quote: 

> "Translated text needs to be fixed by the translator not via community PR"

**Comment by MikeMcC399** [comment]
@dsarkar 
> "Translated text needs to be fixed by the translator not via community PR"

This is not translated text, which would be in "https://github.com/corona-warn-app/cwa-app-android/tree/main/Corona-Warn-App/src/main/res/values[-language]/strings.xml".

These are hard-coded, non-translated, English-language-only error messages which are controlled by the software developers, not by the translation process. The texts are in .kt (kotlin) source files, not strings.xml files.

We can leave it to the developers to decide if they want to accept the PR https://github.com/corona-warn-app/cwa-app-android/pull/2121 or reject it.

**Comment by dsarkar** [comment]
@MikeMcC399 

> We can leave it to the developers to decide if they want to accept the PR #2121 or reject it.

Indeed. ;-)

**Comment by d4rken** [comment]
Closed via #2121
