### ISSUE TITLE
Contact diary: Add Android launcher shortcut

### ISSUE THREAD

**Issue by GenosseFlosse** [corona-warn-app/cwa-app-android#2130]
* [y] This enhancement request has not already been raised before
* [y] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [y] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation
Open contact diary by opening app, scrolling down and pressing on contact diary button. (3 Actions)

## Suggested Enhancement
Add Android launcher shortcut (long press on app in launcher) for contact diary view. (2 Actions)

## Expected Benefits
Users avoid going into the app and scrolling down and again click on contact diary. They can also open contact diary with one long and one short press. Also users will be able to detach the shortcut into a full grown app icon and thus reducing the necessary UI actions to only 1 or 2 actions. (1 Action if current launcher supports detaching 

Better UX and lower UI interaction count will (hopefully) lead to higher acceptance. 

---
Internal Tracking ID: [EXPOSUREAPP-4659](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4659)

**Comment by PhilippNowak96** [comment]
Nice idea! I will open a PR soon. Let's see if the devs like it too and we can get it into the app for 1.12.

**Comment by d4rken** [comment]
Would nice to increase user engagement with the diary.
I like it too, but this will require more than a sign off by devs. 
Let's get this JIRA'd (ping @dsarkar) and discussed internally (ping @thomasaugsten ).

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-4659](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4659)

**Comment by GenosseFlosse** [comment]
Thanks @PhilippNowak96 for providing the PR insanely fast.

Here an additional thought:
Since you guys picked up on this, the logical continuation would be to add two additional shortcuts that let the user jump directly to the "People" or "Places" activity in today's date. This way the UX actions would remain the absolute minimum.

Hopefully it is not just me finding that useful but also the average user.

**Comment by Ein-Tim** [comment]
Same proposal in the Wishlist: https://github.com/corona-warn-app/cwa-wishlist/issues/295
Maybe move the discussion there? (@dsarkar)

**Comment by dsarkar** [comment]
@Ein-Tim, https://github.com/corona-warn-app/cwa-wishlist/issues/295 is now included in this JIRA ticket, so devs are aware of both threads. Thanks!

**Comment by Ein-Tim** [comment]
Thanks @dsarkar. Please consider implementation for both iOS & Android 👍

**Comment by MikeMcC399** [comment]
This has been implemented in CWA Android 1.14.3

![Add Entry](https://user-images.githubusercontent.com/66998419/110841990-d7b3d100-82a6-11eb-93bc-a5fbf6903784.jpg)

**Comment by dsarkar** [comment]
@GenosseFlosse and community. Thanks for contributing. This feature has been implemented. We suggest closing this issue now. Thanks. Best, DS

---
Corona-Warn-App Open Source Team
