### ISSUE TITLE
Contact Diary: Days of the week are shown in German instead of English

### ISSUE THREAD

**Issue by GenosseFlosse** [corona-warn-app/cwa-app-android#2140]
## Avoid duplicates
* [👍] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [👍] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [👍 ] Bug is not already reported in another issue

## Technical details

- Device name: POCOPHONE F1
- Android version: 10
- App version: 1.10.1

## Describe the bug
For the correct english strings in an enhancement request within CWA, I switched my phone to english language when the following bug appeared: **The days of the week do not have their english names**. They were not translated.
![signal-2021-01-18-195254](https://user-images.githubusercontent.com/59205524/104953616-06a87780-59c7-11eb-824f-94bcaaafd965.jpeg)

## Steps to reproduce the issue
For me, switching to english was enough.

## Expected behaviour
Days of the week shown in the current language of the app

**Comment by MikeMcC399** [comment]
@GenosseFlosse 
I already reported this problem in https://github.com/corona-warn-app/cwa-app-android/issues/2009. The fix should come out with the next release 1.11.

You can close your issue, since it is a duplicate.

**Comment by GenosseFlosse** [comment]
uuhm I am sorry I should have also searched in closed issues :)

**Comment by MikeMcC399** [comment]
@GenosseFlosse 
> uuhm I am sorry I should have also searched in closed issues :)

Actually #2009 is still open. The Android CWA issues here in GutHub don't usually get closed until the solution to the problem has been released. That is to avoid people not finding the issues. 🙂

**Comment by GenosseFlosse** [comment]
Then I probably didn't not have the right search string 😄
