### ISSUE TITLE
[CWA Appstore] Play Store Screenshot showing old version

### ISSUE THREAD

**Issue by GenosseFlosse** [corona-warn-app/cwa-app-android#2141]
## Duplicates
Same issue in iOS App Store:
https://github.com/corona-warn-app/cwa-app-ios/issues/1747#issue-775518391

## Describe the bug
Screenshot doesn't show current version with contact diary. 
![signal-2021-01-18-201157](https://user-images.githubusercontent.com/59205524/104954975-a830c880-59c9-11eb-97fa-2f6f44b413c3.jpeg)

## Expected behaviour

I expect the screenshot to show the current version.

## Possible Fix

Provide pictures for the play store that are up to date.

---
Internal Tracking ID: [EXPOSUREAPP-4673](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4673)

**Comment by MikeMcC399** [comment]
@GenosseFlosse 
You're right that the main screen is out of date, however if you scroll over to the right there is a screen shot of the Contact Journal / Kontakt-Tagebuch.

**Comment by GenosseFlosse** [comment]
Yeah but at first glance it doesn't look like the app I just installed and is therefore not correct. I am wondering why this hasn't been addressed before.

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-4673](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4673)

**Comment by MikeMcC399** [comment]
@GenosseFlosse 
> I am wondering why this hasn't been addressed before.

The most likely reason is that nobody else noticed it. It certainly hadn't been reported here previously.

**Comment by Ein-Tim** [comment]
No I think the clue is that you need to push a new version of the App to the App Store (there I am sure) and also to the Play Store if you want to update the content shown there.
So they either had to provide a version which only updates the information in the store (was already done under iOS, version 1.5.3) or they wait until they can release version 1.11 and correct the screenshot with this version.

**Comment by MikeMcC399** [comment]
@GenosseFlosse 
I've taken a look at the Google Play Store Corona-Warn-App screenshots on

https://play.google.com/store/apps/details?id=de.rki.coronawarnapp&hl=en and
https://play.google.com/store/apps/details?id=de.rki.coronawarnapp&hl=de

and I am seeing that they've been updated to correspond to the 1.11.0 release of the app. So they include the top of the statistics section on the far left screenshot, and on the far right screenshot the left-most statistics tile is shown.

According to https://www.coronawarn.app/en/blog/2021-01-28-corona-warn-app-version-1-11/ the Android version is going through a staged rollout which started two days ago on Jan 28, 2021, and was planned to take 48 hours, so you might not see 1.11.0 yet. It depends when your Google account gets the release. My account didn't get access until late this morning.

If it now looks good to you, you could close this issue.
