### ISSUE TITLE
App shows wrong risk_card_body_saved_days on startup

### ISSUE THREAD

**Issue by rillig** [corona-warn-app/cwa-app-android#2195]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: unknown
- Android version: 9.0
- App version: 1.10.1

## Describe the bug

I got a notification today telling me I should start the app more often.
I did exactly that, and the main screen displayed risk_card_body_saved_days with $1 being 0, which in German reads:
> Risiko-Ermittlung war für 0 der letzten 14 Tage aktiv

I knew that was wrong, and out of missing trustworthiness in the app, I planned to uninstall it immediately.
I gave the app a second chance though, and a few seconds later it displayed the correct risk_card_body_saved_days_full, which in German reads:
> Risiko-Ermittlung dauerhaft aktiv

I cannot reproduce this and I don't know the exact steps I did, but if the app has a race condition where it shows messages for data that is not yet completely loaded, that's definitely a bug that must be fixed.

## Possible Fix

Only display any messages after all data has loaded completely.

## Related Work

https://youtrack.jetbrains.com/issue/TBX-3658 -- I think this is a common bug pattern.

**Comment by dsarkar** [comment]
@rillig Thanks for contributing here. This issue is obsolete now since from version 1.15 on it shows days installed instead of active days. We suggest closing this issue. Best wishes, DS 

---
Corona-Warn-App Open Source Team
