### ISSUE TITLE
Unused Unknown Risk appears in Overview

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#2198]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue
See related closed issue https://github.com/corona-warn-app/cwa-app-android/issues/1830#issue-759345191 which shows that the behavior was changed in CWA Android 1.8.

## Technical details

- Device name: Samsung Galaxy A5 (2017) SM-A520F
- Android version: 8.0.0
- App version: 1.10.1

## Describe the bug

The app overview shows the status "Unknown Risk" however this status is unused starting with version 1.8.

## Steps to reproduce the issue

1. If CWA already installed, then uninstall
2. Install CWA
3. Disable Wi-Fi and mobile data
4. Open CWA
5. Tap "LET'S GET STARTED", "NEXT"
6. Tap "ACTIVATE EXPOSURE LOGGING" / Turn on
7. Tap "NEXT", "NEXT" / OK

Note that the risk card shows "Low Risk" (not "Unknown Risk").

![Encounters have not yet been checked](https://user-images.githubusercontent.com/66998419/105632754-36d39880-5e55-11eb-97f6-0f03d8a63b99.jpg)

---

8. Tap three-dot overflow menu in CWA, and "Overview"
9. Scroll down to section 2 with heading "Risk of Infection" and the table with title "The following risk status can be shown:" 

Note that the table includes the status "Unknown Risk" with grey color.

![Overview Unknown Risk](https://user-images.githubusercontent.com/66998419/105632885-dc870780-5e55-11eb-9817-46a8139fb306.jpg)

## Expected behaviour

The overview should not include the unused risk status "Unknown Risk". 

## Possible Fix

Align Overview with possible app status. 

- "Unknown Risk" should be removed.

## Additional context

The status "Unknown Risk" was removed with PR "Refactor riskcard & states; Chapter1 (EXPOSUREAPP-4049, EXPOSUREAPP-3834)" https://github.com/corona-warn-app/cwa-app-android/pull/1751 which was merged into branch release/1.8.x.

---
Internal Tracking ID: [EXPOSUREAPP-4744](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4744)

**Comment by dsarkar** [comment]
FYI https://github.com/corona-warn-app/cwa-app-android/pull/2171

**Comment by ralfgehrer** [comment]
This issue was addressed in this PR: https://github.com/corona-warn-app/cwa-app-android/pull/2171

**Comment by MikeMcC399** [comment]
@dsarkar / @ralfgehrer 
> This issue was addressed in this PR: #2171

It's good to see this is already in the release/1.12.x branch! Thank you.

**Comment by MikeMcC399** [comment]
I ran through the repro steps in #2198 and confirm the issue is fixed in CWA Android 1.12, therefore I am closing this issue.

- After onboarding with no Internet, the app shows "Low Risk"
- In Overview / Risk of Infection only Increased Risk and Low Risk are shown. Unknown Risk (correctly) no longer appears.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks!
