### ISSUE TITLE
Reset App late in day causes "Limit already reached" error message

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#2248]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
FAQ entry https://www.coronawarn.app/en/faq/#API39508 is related and is in the process of being updated (see https://github.com/corona-warn-app/cwa-website/issues/781)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue
This is a follow on to "Resetting the CWA triggers error 39508" https://github.com/corona-warn-app/cwa-app-android/issues/934 and it is related to "Error 39508 / Limit already reached" https://github.com/corona-warn-app/cwa-app-android/issues/1459

## Technical details

- Device name: Samsung Galaxy Tab A SM-T510
- Android version: 10
- App version: 1.11.0
- ENS version: 18205016000

## Describe the bug

If CWA is reset in the late evening after 6 exposure checks have been done, then after onboarding, the "Limit already reached" error message is displayed following by "Check is running". 

Exposure checks start working correctly however in the early hours of the next day.

## Steps to reproduce the issue

1. Connect device to charger and ensure WiFi access is available.
2. Examine exposure log after 20:00 UTC through Settings > Google > COVID-19 Exposure Notifications > three-dot overflow menu > Exposure checks.
![Six exposure checks](https://user-images.githubusercontent.com/66998419/106451564-0c05c780-6487-11eb-81d3-917bd3d631b0.jpg)

3. If 6 exposure checks after 00:00 UTC (currently 01:00 CET) on the current day have already been carried out, then ...
4. CWA > three-dot overflow menu > Settings > Reset App.
5. Go through onboarding and activate exposure logging.
6. Note error message "Limit already reached"
![Limit already reached](https://user-images.githubusercontent.com/66998419/106451631-1e800100-6487-11eb-8696-49843db95d1f.jpg)
![QuotaExceededException](https://user-images.githubusercontent.com/66998419/106451649-250e7880-6487-11eb-91d0-9fc432fdba92.jpg)
![Check is running](https://user-images.githubusercontent.com/66998419/106451663-28a1ff80-6487-11eb-8ba2-53e564264764.jpg)
![Encounters have not yet been checked](https://user-images.githubusercontent.com/66998419/106451667-2a6bc300-6487-11eb-8041-9f74b56054bf.jpg)

## Expected behaviour

Carrying out Reset App should not lead to an error message. After a reset a user can expect not to be influenced by past history.

## Possible Fix

- Increase the interval between exposure checks to 5 hours.
or
- When resetting the app, check if the quota has been exceeded and delay exposure checks until after the quota has been reset by ENS. Suppress the generic error message and output instead an error message for this specific situation.

---
Internal Tracking ID: [EXPOSUREAPP-4947](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4947)

**Comment by dsarkar** [comment]
@MikeMcC399, Thanks. Internally tracked, see above.

**Comment by thomasaugsten** [comment]
We should not increase the check period for all user because of this edge case.
After a reset don't have the information how many ENF checks where uses for this. We cannot delay the check.

**Comment by MikeMcC399** [comment]
@dsarkar 
Could we please add the https://github.com/corona-warn-app/cwa-app-android/labels/wontfix label to this issue? @thomasaugsten commented in https://github.com/corona-warn-app/cwa-app-android/issues/2248#issuecomment-773900831 and then closed the issue.

I have suggested in https://github.com/corona-warn-app/cwa-website/issues/848 that we add this information to https://www.coronawarn.app/en/faq/#API39508 so that users know it is expected that "Limit already reached" can appear if the app is reset after 21:00 in winter or 22:00 in summer if it has been permanently connected to WiFi during the day (and possibly also permanently connected to a charger).
