### ISSUE TITLE
Statistics snaps to second card after swiping right

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#2259]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy Tablet A SM-T510
10.1inch 1200 x 1920 pixels, 16:10 ratio (~224 ppi density)
- Android version: 10
- App version: ~~1.11.0~~ 1.12.0

## Describe the bug

After swiping the statistics left, then swiping right it is not possible to leave the card "Confirmed New Infections" showing completely.

The same issue appears when swiping completely left. The card "7-Day R Value" is not completely displayed.

## Steps to reproduce the issue

1. Scroll down to the statistics cards starting with "Confirmed New Infections" which looks similar to the following screenshot
![Starting statistics](https://user-images.githubusercontent.com/66998419/106497088-e9db6c00-64bd-11eb-91cc-20e7a757f478.jpg)
2. Now swipe to the left and back to the right fully. The first card on the left is no longer completely displayed. 
![Snapped statistics](https://user-images.githubusercontent.com/66998419/106497256-168f8380-64be-11eb-8104-b5a19a69fa0a.jpg)
3. To restore the view, tap on any of the ℹ️ icon and then tap the back button.

## Expected behaviour

If the cards are swiped fully to the right, then they should stay there and not be snapped slightly to the left again and vice versa.

## Possible Fix

PagerSnapHelper() is responsible. 

## Additional context

I found only my tablet (16:10 ratio), but not my phone (19.5:9 ratio) is affected. I don't know exactly the conditions where it starts to become problematic unfortunately, but it looks like it may only affect relatively wider devices.

---
Internal Tracking ID: [EXPOSUREAPP-4945](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4945)

**Comment by PhilippNowak96** [comment]
It's reproducible with a Nexus 10 2560x1600 xhdpi emulator (using Android 10 image) for me. Had no look with a 1200x1920 emulator. I think I will have a look into this :)

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-4945](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4945)

**Comment by dsarkar** [comment]
@MikeMcC399, @PhilippNowak96 Thanks. Internally tracked, see above.

**Comment by MikeMcC399** [comment]
PR #2260 (EXPOSUREAPP-4945) is now included in the [1.13.0 Milestone](https://github.com/corona-warn-app/cwa-app-android/milestone/19).

**Comment by MikeMcC399** [comment]
The fix was released with CWA Android 1.13.2 and I confirmed that it works on the device that I originally reported it on (Samsung Galaxy Tablet A SM-T510).

**Comment by dsarkar** [comment]
@MikeMcC399 thanks for reporting and feedback.
