### ISSUE TITLE
Misleading statistic panes ("Mittelwert" vs "Summe")

### ISSUE THREAD

**Issue by sellibitze** [corona-warn-app/cwa-app-android#2273]
This is not a "technical bug" but an unfortunate and misleading use of terminology in the user interface.

## Technical details

- Android App version: 1.11.0

## Describe the bug

The app's statistics panes with the daily number of new confirmed infections refer to the 7-day-sum as an "average" ("Mittelwert") but it's actually a *sum*, a number of confirmed infections over the last seven days, not a the average number of confirmed infections per day (averaged over the last 7 days).

The same problem might apply to the "7 day average" of persons that have warned others within the last seven days. But I don't have the data available to verify this.

## Expected behaviour

I expect to see the number of confirmed cases within the last 7 days being referred to as such and not an "average" / "Mittelwert".

## Possible Fix

Update your UI to use the proper terminology for this number. Perhaps "7-Tage-Summe"?

**Comment by MikeMcC399** [comment]
@sellibitze 
Could you provide a screenshot of what you are seeing, so we can discuss concrete numbers?

**Comment by sellibitze** [comment]
No need. It was a mistake of me filing this issue. The number I see (11.430) matches the 7-day-average as reported elsewhere.

Sorry for my confusion!
