### ISSUE TITLE
Allow app to display in reverse portrait mode

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#2274]
## Avoid duplicates
* [X] This enhancement request has not already been raised before
Related to wishlist "Screen rotation / landscape mode shows, but immediately switches back to portrait" https://github.com/corona-warn-app/cwa-wishlist/issues/86
* [X] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
This concerns specific Android settings, however the general enhancement may also apply to iOS

## Current Implementation

If the device is held in portrait mode and rotated top to bottom the app display does not rotate with the device. (CWA Version 1.11.0.)

## Suggested Enhancement

Allow the app to display in reverse portrait mode.

In https://github.com/corona-warn-app/cwa-app-android/blob/main/Corona-Warn-App/src/main/AndroidManifest.xml change all occurrences of

`android:screenOrientation="portrait"` to

`android:screenOrientation="userPortrait"`
 

## Expected Benefits

Many mobile devices have the charger socket at the bottom of the device. When a charger is connected it is easier to stand the device upside down when vertical viewing is preferred. Allowing the CWA app display to rotate to reverse portrait mode would enable viewing with a charger connected and with the device stood up.

## Reference Information

`android:screenOrientation`

The value can be:

value | description
-- | --
"portrait" | Portrait orientation (the display is taller than it is wide).
"userPortrait" | Portrait orientation, but can be either normal or reverse portrait based on the device sensor and the user's preference. Added in API level 18.

See https://developer.android.com/guide/topics/manifest/activity-element.html#screen for full list of options.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks. Have you tried this in the emulator? Do you have a PR ready? Or maybe @PhilippNowak96? Thanks!

**Comment by MikeMcC399** [comment]
@dsarkar 
I have tried it on a physical device and I couldn't see any problems. I can certainly submit a PR if you like. I would target release/1.13.x, not release/1.12.x since it is an enhancement, just in case there are any unexpected side-effects, to give time to check it out.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for the feedback. Regarding the PR, I don't have feedback from the developer side. However, I think a PR obviously increases the chances to get it implemented and also speed things up.

**Comment by MikeMcC399** [comment]
@dsarkar 
Thank you! I will submit a PR. Could you give me an EXPOSUREAPP-nnnn ID so I can use it to name the branch?

**Comment by mvglasow** [comment]
@MikeMcC399 can you elaborate on what did not work? (Unless that’s what you meant by “writ[ing] this up”.) Did the screen fail to rotate? Unexpected layout issues? Others?

**Comment by dsarkar** [comment]
@MikeMcC399 OK, thanks for letting us know. Standing by.

**Comment by MikeMcC399** [comment]
@mvglasow 
> can you elaborate on what did not work?

The screen didn't rotate on some devices just using "userPortrait". I want to provide more details after I've done some more experiments, then I will write more here. It's quite disappointing because it seemed like an easy simple solution, but apparently it's not simple at all.

**Comment by MikeMcC399** [comment]
I tried two different Samsung Galaxy phones (A5 & A50), running Android 8 and 10 respectively and a Pixel 3a phone emulator running Android 10 and none of them responded to the attribute android:screenOrientation="userPortrait" which according to the Android documentation https://developer.android.com/guide/topics/manifest/activity-element.html#screen should allow portrait and reverse portrait orientation. In fact only portrait was shown, not reverse portrait. The only device which went to reverse portrait display with this setting was a Samsung Galaxy Tablet A and tablets are not mainstream for CWA (see https://www.coronawarn.app/en/faq/#smartwatch).

It would be possible to allow the app to rotate to landscape left and right together with reverse portrait, but that is too big a change without dev discussion and agreement. It could easily open up multiple display issues even though at first glance CWA seems to display well in landscape mode.

So, regrettably I'm going to close this request. It was a nice-to-have enhancement request, but not essential.
