### ISSUE TITLE
Numbers are treated as links / autolinked too aggressively

### ISSUE THREAD

**Issue by Merthan** [corona-warn-app/cwa-app-android#2275]
## Describe the bug

Numbers are linked too aggressively, see here:

![grafik](https://user-images.githubusercontent.com/27968148/106742486-0211cf00-6615-11eb-99ee-9dce6efa5dcd.png)

## Steps to reproduce the issue

Visit the App Information Fragments

## Expected behaviour

Only actual phone numbers are marked as links and clickable, not ~2 digit numbers or postcodes

## Possible Fix

Writing a custom parser or changing TextView behaviour (which I'd like to do)

---
Internal tracking ID: [EXPOSUREAPP-4992](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4992)

**Comment by MikeMcC399** [comment]
@Merthan 
On my Android 10 phone I'm not seeing so many inappropriate autolinks. The ones I see are:
- postcodes (13353 and 69190)
- version number (13.5)
which are interpreted as phone numbers.

What is your environment?

**Comment by Merthan** [comment]
@MikeMcC399 

Android 11, Pixel 3a, newest app version 

As Pixels are often close to default behaviour I assume the majority of devices also get shown those links

**Comment by MikeMcC399** [comment]
@Merthan 
It's strange because I'm not seeing the problem at all on an Android 11, Pixel 3a emulator with CWA 1.11.0. I wonder if there are some settings or additional apps installed which could affect this?

**Comment by crcsn** [comment]
Can reproduce this issue on a Samsung Galaxy S10 running Android 11, CWA version 1.11.0

**Comment by vaubaehn** [comment]
Same here, LG-G4, Android 6, CWA 1.11 (but already noticed in earlier versions)

**Comment by Jo-Achim** [comment]
I found 3 'autolinked too aggressively'; see summarized screenshots:

![Links](https://user-images.githubusercontent.com/21124877/106782382-626f3380-664a-11eb-93d9-bd946549db13.jpg)


Android 10 with Android security update: January 1st, 2021
Nokia 7.1, Build: 00WW_4_16B_SP03
CWA version: 1.10.1 / 1.11.0
ENF: 18205016000
NetGuard Pro 2.290
Norton 360, v.5.1.0.5628

**Comment by PhilippNowak96** [comment]
Created a pull request to fix this issue. I could reproduce it also on a Pixel 4 XL.

Just ignore my first commit linked here (I deleted it already in my forked repo). This one was done with the wrong git config 😅

**Comment by dsarkar** [comment]
Internal tracking ID: [EXPOSUREAPP-4992](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4992)

**Comment by MikeMcC399** [comment]
I checked the fix merged from PR #2286 in the released CWA Android 1.13.2 build and with the locale set to English (United States) on Android 8 the phone number 116 117 shows correctly linked on:

- Three-dot icon > App Information > Technical Hotline and
- NEXT STEPS > No TAN yet?

Also the Terms of Use and Data Privacy views are correct: 
- Three-dot icon > App Information > Terms of Use / Data Privacy
Only URLs / E-Mail addresses are underlined.
Zip codes, year numbers, sections numbers, etc. are not underlined.

So it all looks good!

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for detailed feedback!
