### ISSUE TITLE
Typo in Onboarding Screen

### ISSUE THREAD

**Issue by Magoli1** [corona-warn-app/cwa-app-android#23]
## Describe the bug
When starting the app, the app opens the dialog for requesting the permission for sending and receiving the users covid-19 risk status. The description says : "Corona-**Wran**-App...", instead of "Corona-Warn-App".

## Steps to reproduce the issue

1. Start the app for the first time
2. Continue till the permission dialog

## Technical details

- Host Machine OS (Windows/Linux/Mac): Windows 10 Emulator With Android 28

## Possible Fix
We already have a fix ready for a PR. We sadly miss authorization to publish our branch. We would be happy if we could supply you with the PR 👍 (and possibly also other enhancements 😁  )

Best Regards 🚀 
Robert Jakobs & Tim Brüggenthies (@timbrueggenthies)

**Comment by tkowark** [comment]
Hi @Magoli1 , thanks for spotting that issue. Regarding the PR, you should be able to create your own fork of the repo and create a submit from there (see #31 )

**Comment by Magoli1** [comment]
@tkowark ,thanks for looking into our issue! 👍 
It seems like @Bananeweizen already fixed this, without claiming our issue. 
We wanted to comply to the [contributing guidelines](https://github.com/corona-warn-app/cwa-app-android/blob/master/CONTRIBUTING.md#steps-to-contribute) and as stated in our initial message, we already had a fix ready for a PR. We are glad that this issue is fixed, and we would be extremely happy if you @Bananeweizen could adhere to the guidelines, to prevent duplicate work in the future 👍 

BR Robert & Tim (@timbrueggenthies)

**Comment by tkowark** [comment]
Again, thanks to all three of you, @Magoli1 , @timbrueggenthies, @Bananeweizen

Regarding issue claiming, would be great if you could follow the proposed process by quickly commenting on the issue to avoid duplicate work.

On the other hand, for trivial issues like typos, you can also just create a PR without creating an issue first:
> If you have a trivial fix or improvement, go ahead and create a pull request, addressing (with @...) a suitable maintainer of this repository (see CODEOWNERS of the repository you want to contribute to) in the description of the pull request.

Looking forward to your next contributions!
