### ISSUE TITLE
App Information cut off at bottom on small screen

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#2302]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Nexus 5 emulator, API 30 
- Android version: 11
- App version: 1.12.0 ~~branch release/1.12.x~~ released version from Google Play Store

## Describe the bug

The bottom of the App Information is cut off on a smaller device and cannot be viewed. The app version information is not displayed.

~~It's possible this is only an issue with debug builds.~~

~~Also, I do not have a whitelisted Google account, so I have no access to the Exposure Notification System API with a debug apk.~~

## Steps to reproduce the issue

After release of 1.12.0 was installed from Google Play Store, I can confirm that the released build also has this issue.

1. Build variant deviceDebug on branch release/1.12.x
2. Run on Nexus 5 emulator, API 30 
3. Tap three-dot overflow menu > App Information
4. Try to scroll the view

![App Information does not scroll](https://user-images.githubusercontent.com/66998419/107147284-6b634c00-694d-11eb-9293-18567d2c5c17.png)

## Expected behaviour

It should be possible to view the version number by scrolling down. The version number is only partially displayed on this device.

## Possible Fix

The layout is https://github.com/corona-warn-app/cwa-app-android/blob/release/1.12.x/Corona-Warn-App/src/main/res/layout/fragment_information.xml

I temporarily removed the `android:screenOrientation="portrait"` under `android:name=".ui.main.MainActivity"` in `src\main\AndroidManifest.xml` and viewed App Information in landscape orientation on a small screen. I could scroll the view, but it wouldn't scroll down far enough to display the version number in full.

However, if in addition I remove
`android:layout_marginTop="@dimen/spacing_normal"` under `LinearLayout` of `fragment_information.xml` then the App Information scrolls and reveals the version number. This works both in the original portrait mode and in landscape mode. I don't think this is the solution, but it may be helpful as a troubleshooting step.

---
Internal tracking ID: [EXPOSUREAPP-5045](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5045) duplicate of
Internal tracking ID:  [EXPOSUREAPP-4939](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4939)
 PR #2267

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks. Internal tracking ID: EXPOSUREAPP-5045

**Comment by ralfgehrer** [comment]
Hi @MikeMcC399 many thanks for bringing this up. This issue should have been addressed by https://github.com/corona-warn-app/cwa-app-android/pull/2267 in `release/1.13.x'.

**Comment by MikeMcC399** [comment]
Hi @ralfgehrer 
Thanks for the link to PR #2267 and I confirm that the steps to reproduce in this issue show that the PR fixes the issue!

@dsarkar 
EXPOSUREAPP-5045 is solved by "Fix scrolling issue in InformationFragment (EXPOSUREAPP-4939)" #2267 planned for release 1.13.x.

I suggest leaving this issue open until 1.13 is released, as some people might see the issue on small devices when 1.12 is released.

**Comment by d4rken** [comment]
> https://github.com/corona-warn-app/cwa-app-android/pull/2180#issuecomment-778348094

@vaubaehn Yes, #2302 will fix the layout for both version information entries.

Pixel 3a at max font and element size:
<img src="https://user-images.githubusercontent.com/1439229/107806413-208b6f00-6d67-11eb-9e82-8f03f4c6eca4.png" width="400">

**Comment by vaubaehn** [comment]
@d4rken 
Hi Matthias,
:tada: :+1: 
Thanks for your response. Best wishes!

**Comment by MikeMcC399** [comment]
@d4rken 

Thanks for the screen shot with 1.13.0-RC2! 

I can't test to see if the ENF version is displayed in App Information in a development build, due to not being whitelisted. I did however test again using release/1.13.x at https://github.com/corona-warn-app/cwa-app-android/commit/1edad37a09d2b59efbe8197522f8848ba969aed4 level and Build variant deviceDebug on a Nexus 5 emulator, API 30, which has a smaller screen, and I can confirm that I can scroll to the bottom of the screen.

When this issue is fixed in a released version I would plan to update the FAQ entry
https://www.coronawarn.app/en/faq/#ENF_version
to describe how to find out the installed version of Google Exposure Notifications System (ENS) through the CWA app. I held back on that in https://github.com/corona-warn-app/cwa-website/pull/865 due to the scrolling bug in 1.12.0. I only corrected the description about how to display the ENS version number using the Google UI instead to make sure that the terms in the instructions matched the exact text shown by Google.

**Comment by MikeMcC399** [comment]
Confirmed fixed on CWA Android 1.13.2 release. Here is a screenshot from a Nexus 5 API 30 (Android 11) emulator. This device has a small screen. The App Information could be scrolled down to display both the app and the Google version numbers.

The "New Features" entry in the list is (correctly) scrolled off the top.

![App Information 1 13 2 Nexus 5](https://user-images.githubusercontent.com/66998419/110235205-10624c00-7f2f-11eb-9fea-7dac2f5e2cb6.png)

**Comment by dsarkar** [comment]
@MikeMcC399 And again, thanks for verifying.

**Comment by vaubaehn** [comment]
@ralfgehrer @dsarkar @MikeMcC399 
Unfortunately, this issue can be reopened, as it occurs again in CWA 2.1.2.

**Comment by MikeMcC399** [comment]
@vaubaehn 
> Unfortunately, this issue can be reopened, as it occurs again in CWA 2.1.2.

Thanks for the feedback! I have re-opened and I will check how it looks on the Nexus 5 emulator, API 30.

**Comment by MikeMcC399** [comment]
@vaubaehn

I don't see any issue on Nexus 5 emulator, API 30 with CWA version 2.1.2.

I suggest that you open a new issue with a screen shot and details of your hardware device. I will close this issue again, since the original problem is confirmed solved in the environment it was reported in.

![image](https://user-images.githubusercontent.com/66998419/116919543-b5f51b80-ac51-11eb-9664-c60f43b80d48.png)
