### ISSUE TITLE
Incorrect translation of `onboarding_tracing_location_body` regarding location setting (English)

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#2345]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue
This is related to #1541.

## Technical details

- Device name: Samsung Galaxy A5 (2017)
- Android version: 8.0.0
- App version: 1.12.0

## Describe the bug

The meaning of the translation into English of `onboarding_tracing_location_body` does not reflect the German meaning and it is incorrect:

![Allow location access](https://user-images.githubusercontent.com/66998419/107798857-fc2a9500-6d5c-11eb-862a-8d7b2c9ac8f1.jpg)

Android does not require access to the smartphone's location, it requires the smartphone's location setting to be enabled. These are two different things.

---
![Standort-Verwendung erlauben](https://user-images.githubusercontent.com/66998419/107798868-ff258580-6d5c-11eb-99b9-db03b145bbf4.jpg)

## Steps to reproduce the issue

With locale set to English (United Kingdom) ...

1. CWA > three-dot overflow menu > Settings > Reset App and confirm
2. Tap "LET'S GET STARTED"
3. Tap "NEXT"
4. On screen "How to Enable Exposure Logging" scroll down to the section under "The following countries currently participate" and note the message "Allow location access".

## Expected behaviour

Make the English text clear that the app requires the device setting "Location"  to be enabled in order to use Bluetooth Low Energy, however the app itself is not determining or using the location of the device.

Refer to https://support.google.com/android/answer/9930236?hl=en for an explanation.

## Possible Fix

Review the English translation of 
`onboarding_tracing_location_headline`
`onboarding_tracing_location_body`

<string name="onboarding_tracing_location_headline">"Allow location access"</string>

<string name="onboarding_tracing_location_body">"Your location cannot be accessed. Google and/or Android requires access to your smartphone’s location to use Bluetooth."</string>

It should reflect the true meaning as described under "expected behaviour"    

## Additional context

In Android 11 (API 30) and above, the whole reference to location access should not be displayed. The Google Exposure Notifications System does not require the device's location setting to be enabled in order to use Bluetooth Low Energy. See https://support.google.com/android/answer/9930236.

---
Internal tracking ID: [EXPOSUREAPP-5137](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5137)

**Comment by dsarkar** [comment]
Thanks @MikeMcC399.

Internal tracking ID: [EXPOSUREAPP-5137](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5137)

**Comment by dsarkar** [comment]
@MikeMcC399 FYI, see https://github.com/corona-warn-app/cwa-app-android/pull/2401/files , file no 2

**Comment by MikeMcC399** [comment]
@dsarkar 

Thanks for the information about the text changes! I can see the following in [v1.13.0-RC8](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.13.0-RC8). This is better than it was before. It may still be confusing to anyone unfamiliar with the background of the technology though.

In the German notice there is a clear distinction made between "Standort" and "Standort-Erlaubnis" in the text. In the new English notice they are both called "device location".

Here is a suggestion for an extension of this text:

**"Your device location cannot determined by the app, but the device location setting is required to be activated to use Bluetooth Low Energy in some Android versions."**

compared to the current text in [v1.13.0-RC8](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.13.0-RC8):

"Your device location cannot determined by the app, but device location is required to use Bluetooth Low Energy in some Android versions."

![image](https://user-images.githubusercontent.com/66998419/108395179-d0eced80-7215-11eb-8f51-00da86f90092.png)

**Comment by MikeMcC399** [comment]
@dsarkar 
Also the current text is missing a word anyway!

"Your device location cannot determined by the app ..."

would need to be

"Your device location cannot **be** determined by the app ..."

to be correct English. I just noticed this point.

**Comment by dsarkar** [comment]
@MikeMcC399 ok, will forward info. Thanks!

**Comment by dsarkar** [comment]
@MikeMcC399 
apart from the missing 'be' and wording change:

it says "... in some Android versions".

Implicitly this means not on Android 11 devices. Together with the fact that during the onboarding process on Android 11 devices there is **no** notification to allow location services, issue https://github.com/corona-warn-app/cwa-app-android/issues/1541 will be resolved at the same time. Do you agree?

**Comment by MikeMcC399** [comment]
@dsarkar 
>it says "... in some Android versions".
>
>Implicitly this means not on Android 11 devices. Together with the fact that during the onboarding process on Android 11 devices there is no notification to allow location services, issue #1541 will be resolved at the same time. Do you agree?

The wording change in the English text is a good workaround which is fast to implement for issue #1541 (Wrong "Allow location access" during onboarding for Android 11), however ...

- the equivalent text is not in the German string `onboarding_tracing_location_body` of the current release/1.13.x branch, which is at RC9 + additional commits
- it doesn't solve the issue cleanly, because it leaves the user to guess whether their Android version is involved or not

The programmatic change to hide the location card `id/onboarding_location_card`, if it is not required to activate the location setting, would still be my preferred solution. This is what I suggested in #1541.

**Comment by dsarkar** [comment]
@MikeMcC399 FYI PR https://github.com/corona-warn-app/cwa-app-android/pull/2427/files second file, line 501.

**Comment by MikeMcC399** [comment]
@dsarkar 
Thanks! https://github.com/corona-warn-app/cwa-app-android/pull/2427 corrects the information. I look forward to this being merged in release/1.13.x.

**Comment by dsarkar** [comment]
related: https://github.com/corona-warn-app/cwa-app-android/pull/2428

**Comment by MikeMcC399** [comment]
@dsarkar 
The text is looking good in the release/1.13.x branch, so it should be possible to close this issue after 1.13 is released.

**Comment by MikeMcC399** [comment]
The CWA Android 1.13.2 release includes the following informational text during onboarding, which solves the issue reported here. There is a follow-on issue in #2506 regarding the further improvement of the text.

![Activate Location Setting EN DE](https://user-images.githubusercontent.com/66998419/110233788-bcec0000-7f26-11eb-94f4-9e7ce05c85d1.jpg)

**Comment by dsarkar** [comment]
@MikeMcC399 ok, thanks. 
https://github.com/corona-warn-app/cwa-app-android/issues/2506 is dealt with in the same internal ticket 5137.
