### ISSUE TITLE
Wrong name for activation button in Consent section (English)

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#2346]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
Please check also on iOS and move if necessary
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy A5 (2017) SM-A520F
- Android version: 8.0.0
- App version: 1.12.0

## Describe the bug

In the Consent section of onboarding the text refers to the button to activate as "Enable exposure logging", whereas the button itself is labelled "ACTIVATE EXPOSURE LOGGING".

![Consent enable exposure logging EN DE](https://user-images.githubusercontent.com/66998419/107849234-3433e580-6dfa-11eb-9752-0cb7c4d3da4c.jpg)

The German text and button are in agreement.

## Steps to reproduce the issue

Language is English (United Kingdom).

1. Install app or reset app if already installed
2. Tap "LET'S GET STARTED"
3. Tap "NEXT"
4. On page "How to Enable Exposure Logging" scroll down to section headed "Consent"
5. Note the sentence 
"By tapping on the “Enable exposure logging” button, you agree to enabling the exposure logging feature and to the associated data processing by the app."
6. Compare the name of the button in the Consent text with the name shown on the button

## Expected behavior

When the locale is set to English the reference to the activation button and the label to the activation button should be identical: "Activate Exposure Logging"

## Possible Fix

In the string `onboarding_tracing_body_consent` from `values\legal_strings.xml` the term “Enable exposure logging” in the second sentence ...

"By tapping on the **“Enable exposure logging”** button, you agree to enabling the exposure logging feature and to the associated data processing by the app."

should be changed to agree with the label of the button `risk_card_button_enable_tracing` which contains the string "Activate Exposure Logging".

## Additional context

The German display is correct.
"Risiko-Ermittlung aktivieren" is used in both the Consent text `onboarding_tracing_body_consent` and on the button `risk_card_button_enable_tracing`.

---
Internal Tracking ID: [EXPOSUREAPP-5139](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5139)

**Comment by dsarkar** [comment]
Dear @MikeMcC399 

Thank you for your contributions.

We have created a ticket for the bug (Internal Tracking ID: EXPOSUREAPP-5139) in the internal Jira system. Any further developments will be notified here in this Github issue.
  
Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
@MikeMcC399 FYI Fix planned for release 1.14
PR https://github.com/corona-warn-app/cwa-app-android/pull/2452

**Comment by dsarkar** [comment]
PR iOS https://github.com/corona-warn-app/cwa-app-ios/pull/2080

**Comment by MikeMcC399** [comment]
**Verified fixed for CWA Android 1.14.3.**

The name displayed in the consent text is "Activate exposure logging". The label on the button is displayed as "ACTIVATE EXPOSURE LOGGING".

Apart from the difference of mixed case compared to all upper case, the texts are identical.

![Activate Exposure Logging EN](https://user-images.githubusercontent.com/66998419/110837509-9b31a680-82a1-11eb-8881-9164bbac2430.jpg)

I also checked that there was no regression with locale Deutsch (Deutschland). The text in Einverständnis is correctly displayed as "Risiko-Ermittlung aktivieren" and the button correspondingly shows "RISIKO-ERMITTLUNG AKTIVIEREN".

**The issue is resolved, so now closing.**

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for confirming the fix.
