### ISSUE TITLE
FYI Release 1.13, 1.14, 1.15

### ISSUE THREAD

**Issue by dsarkar** [corona-warn-app/cwa-app-android#2358]
See 
https://github.com/corona-warn-app/cwa-app-android/releases

https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.13.0-RC1
https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.13.0-RC2

https://www.coronawarn.app/en/blog/2021-02-26-corona-warn-app-1-13-announcement/

Release 1.14
---

https://github.com/corona-warn-app/cwa-app-android/pull/2375
https://github.com/corona-warn-app/cwa-app-android/pull/2484/files

https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.14.0-RC2 

Release 1.15
---
https://github.com/corona-warn-app/cwa-app-android/pull/2531/files

Release 2.0
---

**Comment by MikeMcC399** [comment]
@dsarkar 
I'm not sure if the functionality was there all the time, but on GitHub you can selectively sign up for release notifications. Go to Watch / Unwatch (top right) > Custom and select "Releases".

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks, didn't know that one. Watching all activity anyway. ;-)

The idea behind this issue is to direct users, which are not very familiar with the repo and GitHub to the release notes. Should increase the transparency for those who couldn't find the release notes and also might satisfy the curious ones. It's not a roadmap as discussed more than once in some wishlist issues, but it's something.

**Comment by MikeMcC399** [comment]
The release 1.13 has been announced today in the blog https://www.coronawarn.app/en/blog/2021-02-26-corona-warn-app-1-13-announcement/

> Deutsche Telekom and SAP’s project team will release the Corona-Warn-App’s next update in the coming days. With version 1.13, users will be able to donate data to the Robert Koch-Institut voluntarily via the app. Based on that, the experts can further improve the app.
>
> Additionally, users who have a red tile, i.e. an increased risk, will see a link to a scientific survey by the Robert Koch-Institut. By taking part in the survey, users can help the experts to analyze and better understand the app’s effectiveness. Detailed information on the update will be available [here](https://www.coronawarn.app/en/blog/) as soon as the project team has published version 1.13.

**Comment by MikeMcC399** [comment]
@dsarkar 

Can you explain to us the reason for the deletion of the [1.13 announcement](https://www.coronawarn.app/en/blog/2021-02-26-corona-warn-app-1-13-announcement/)? Is the release:
- delayed?
- cancelled?
- still due for release in the "coming days"?

**Comment by bbeyss** [comment]
> @dsarkar
> 
> Can you explain to us the reason for the deletion of the [1.13 announcement](https://www.coronawarn.app/en/blog/2021-02-26-corona-warn-app-1-13-announcement/)? Is the release:
> 
> * delayed?
> * cancelled?
> * still due for release in the "coming days"?

https://github.com/corona-warn-app/cwa-website/issues/921

**Comment by MikeMcC399** [comment]
CWA Android 1.13.2 has now been released.
See https://www.coronawarn.app/en/blog/2021-03-04-corona-warn-app-version-1-13/

**Comment by MikeMcC399** [comment]
@dsarkar 
Do you need to keep this issue open?

1.14 and 1.15 have been released.
