### ISSUE TITLE
Links are not clickable

### ISSUE THREAD

**Issue by IndianaDschones** [corona-warn-app/cwa-app-android#238]
## Describe the bug
The URLs in `Privacy (Datenschutzerklärung)` and `Legal (Rechtliche Hinweise)` are shown as links (colored and underlined) but not clickable.

The eMail-address in `Imprint (Impressum)` is neither highlighted nor clickable.

## Expected behaviour
Highlighted URLs should be clickable and open a webbrowser.

The eMail-address should be clickable.

## Steps to reproduce the issue
Open e.g. `Legal (Rechtliche Hinweise)` and try to click on one of the shown links. Nothing happens.

**Comment by marcmuschko** [comment]
Dear @IndianaDschones 

thank you for pointing this out! Clickable links, e-mails and phone numbers were in stakeholder discussion very recently.
In summary the decision was that the only clickable "link styled" elements in the app will be (at this point in time):
* navigation to technical support 
* navigation to settings 
Therefore the link styling was removed everywhere else in #256 and this issue can be closed.
If you find occurences where link styling is still applied and it might be a mistake, please let us know and reopen the issue. 
We are always happy about feedback! 

Best,
Marc

**Comment by danielw93** [comment]
> Therefore the link styling was removed everywhere else in #256 and this issue can be closed.
> If you find occurences where link styling is still applied and it might be a mistake, please let us know and reopen the issue.

Dear @marcmuschko,
 
have you considered making the text area of affected pages selectable instead?

As it is right now, there is no way I can actually visit the link to the google support page explaining the exposure logging functionality, which is included in the Privacy Statement (https://github.com/corona-warn-app/cwa-app-android/blob/c3416440e644a918f4001489de85f203c7681099/Corona-Warn-App/src/main/assets/privacy_en.html#L185).

As a user I find it very frustrating to see a link and not be able to either click on it or at least copy it to paste it into my browser.

Cheers, 
Daniel

**Comment by Fabian42** [comment]
Why should links not be clickable? Isn't that one of their main purposes? And yes, I agree, it should instead at least be selectable. In general, being able to select anything on the text pages would be good.
