### ISSUE TITLE
Google: What determines which UI is displayed?

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#2382]
## Avoid duplicates
* [X] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Question is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Question has not already been asked in another issue
This is a sub-set of a previous question #2379. 

## Your Question

I have a new Google UI showing on an Android 8 device although the version number of the Exposure Notifications System has not changed from 18210214000.

How did the UI change? Why is another device showing a different UI with the same version of ENS installed?

---
**Newest UI**

![Exposure Notifications UI V3-1](https://user-images.githubusercontent.com/66998419/108095279-fa741080-707f-11eb-9697-22bf8011bf0b.jpg)

![Exposure Notifications UI V3-2](https://user-images.githubusercontent.com/66998419/108095294-fe079780-707f-11eb-88ec-52cc33aa7852.jpg)

---
**Previous UI**

![Exposure Notifications UI V2](https://user-images.githubusercontent.com/66998419/108095324-05c73c00-7080-11eb-99ef-bd43a4f76d0c.jpg)

---
**Original UI**

![Exposure Notifications UI V1](https://user-images.githubusercontent.com/66998419/108095687-6eaeb400-7080-11eb-91d8-fdbbe1aa4f40.jpg)

## Related issues

"[EN-Google] No actualization, even not after new install, stuck in "Data is being downloaded..." / DE: Aktualisiert nicht mehr und nach Neuinstalation Daten laden endet nicht" https://github.com/corona-warn-app/cwa-app-android/issues/2081 particularly unanswered questions in https://github.com/corona-warn-app/cwa-app-android/issues/2081#issuecomment-759981811 and later.

**Comment by MikeMcC399** [comment]
An Android 10 device, which was yesterday showing the Google COVID-19 UI with Corona-Warn and Open on the same line (labelled above as previous UI), is today showing the UI with Open missing on that line (labelled above as Newest UI). Instead tapping on Corona-Warn brings up a new UI level showing Open app and a greyed-out section with a slider containing the text "Automatically warn others ...".

The version number of the Exposure Notifications System hasn't changed (18210214000) and CWA is still at version 1.12.0.

I have to assume that Google is dynamically controlling the behavior of the COVID-19 Exposure Notifications System and I can't find any documentation about how this works or what parameters are available to them. The only related data exchange directly with Google I found documented under [Telemetry Design](https://developers.google.com/android/exposure-notifications/telemetry-design).

**Comment by Jo-Achim** [comment]
Under such framework conditions it would be unnecessarily difficult to put an application on a 'safe and functional' basis.

**Comment by MikeMcC399** [comment]
@Jo-Achim 
This question is also related to the unanswered discussion in https://github.com/corona-warn-app/cwa-app-android/issues/2081#issuecomment-759981811 regarding the major outage "[EN-Google] No actualization, even not after new install, stuck in "Data is being downloaded..." / DE: Aktualisiert nicht mehr und nach Neuinstalation Daten laden endet nicht" where we heard that Google fixed the issue according to the statement quoted in https://github.com/corona-warn-app/cwa-app-android/issues/2081#issuecomment-759964666. Noticeably the fix did not change the version number of the Exposure Notifications System.

**Comment by MikeMcC399** [comment]
[Settings UX changes](https://developers.google.com/android/exposure-notifications/release-notes#settings_ux_changes) in the [updated release notes for v1.8](https://developers.google.com/android/exposure-notifications/release-notes) of the [Google API for Exposure Notifications](https://developers.google.com/android/exposure-notifications/exposure-notifications-api) say:

**"Exposure checks" and "Delete random IDs"**

The **Exposure checks** and the **Delete random IDs button** have both been moved from the main settings list to the overflow menu. There have been no functional changes to these options.

So we now have confirmation that the currently displaying Google COVID-19 Exposure Notifications UI version is the intended one.

I'm not anticipating receiving any more detailed information from Google, so I am now closing this issue.
