### ISSUE TITLE
Enhance Logging With Timber

### ISSUE THREAD

**Issue by Magoli1** [corona-warn-app/cwa-app-android#24]
## Current Implementation
Currently the app uses the native android logging framework. To do that, every class holds a reference to a dedicated logging tag, which is given the logger, in case it is used. Example:
https://github.com/corona-warn-app/cwa-app-android/blob/43412bdabe128dc674ec8a9ef8baa80d37292a3a/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/receiver/ExposureStateUpdateReceiver.kt#L38

## Suggested Enhancement
There is a leightweight library called [Timber](https://github.com/JakeWharton/timber), which automatically sets the logging tags to the calling class. We suggest to change the implementation for all logging calls towards Timber.

## Expected Benefits
Timber optimizes the developer experience inseveral cases, eg. it automatically makes sure that the tag is at most 23 characters long (more details [here](https://developer.android.com/reference/android/util/Log#isLoggable(java.lang.String,%20int))). We could alsoget rid of the tag in every class that is currently hardcoded.

We would be happy if we could supply you with the corresponding PR 👍 

Best Regards
Robert Jakobs & Tim Brüggenthies (@timbrueggenthies)

**Comment by marcmuschko** [comment]
Hi @Magoli1 

Thank you for the suggestion! While this would provide some improvements on development side, it does not seem to introduce critical benefits. As every library included has to be thoroughly checked we add these kind of things very carefully after much consideration beforehand. 
Therefore we will not be able to add the library at this point in time, and I'm closing the issue for now.

Nevertheless, thank you for the poposal!
Marc
