### ISSUE TITLE
Translucent status bar

### ISSUE THREAD

**Issue by fynngodau** [corona-warn-app/cwa-app-android#2483]
## Current Implementation

The Android status bar is displayed in black even when the app is displayed in light theme (white).

## Suggested Enhancement

I believe it would look much better if the app had a translucent-like status bar, as that would give it a more modern look.

I [implemented](https://codeberg.org/corona-contact-tracing-germany/cwa-android/commit/50c0ba4a4e8140ebd2eabdd0e6b54d2dcb2f88d0) this for CCTG, and though my implementation is a bit hacky, I think it looks great – notice how the status bar is green after the green risk card was opened, and the gradient in the QR code view goes through.

Recently I reworked my implementation to be a bit less hacky: [commit that replaces hacks with something that works better](https://codeberg.org/corona-contact-tracing-germany/cwa-android/commit/3f7cd7bb6623ed48c22e91a9c27bd8530f93c1e4), [commit that re-does the implementation for risk card](https://codeberg.org/corona-contact-tracing-germany/cwa-android/commit/ab3430cd34ca5ff2005a266501080c64e539c954) (should maybe be done like the next ones as well), [commit for edit checkin and QR code details fragment](https://codeberg.org/corona-contact-tracing-germany/cwa-android/commit/ab3430cd34ca5ff2005a266501080c64e539c954), [commit for confirm checkin fragment](https://codeberg.org/corona-contact-tracing-germany/cwa-android/commit/dbbe74f59b28b84ef894822036ee89de29b23b52).

| ![screenshot 1](https://codeberg.org/corona-contact-tracing-germany/cwa-android/raw/commit/2213efec2604f95de7da519ef509b0c577682ffa/metadata/en-US/images/phoneScreenshots/00.png) | ![screenshot 2](https://codeberg.org/corona-contact-tracing-germany/cwa-android/raw/commit/2213efec2604f95de7da519ef509b0c577682ffa/metadata/en-US/images/phoneScreenshots/01.png) | ![Screenshot_1618594808](https://user-images.githubusercontent.com/16943720/115063519-f6cc0100-9eeb-11eb-8b59-ba4e16f08515.png) |
|---|---|---|

## Expected Benefits

Users might like the app more when it feels better.

---
Internal Tracking ID: [EXPOSUREAPP-5446](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5446)

**Comment by dsarkar** [comment]
@fynngodau Thanks for the suggestion. Internal Tracking ID: [EXPOSUREAPP-5446](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5446).

**Comment by fynngodau** [comment]
I updated my original post with new commits from CCTG and a new screenshot how the QR code details view looks in our app.

**Comment by dsarkar** [comment]
@fynngodau Thanks.... mirrored as well to the internal ticket.

**Comment by rugk** [comment]
Any progress on an upstream integration of this little UI/UX feature?

**Comment by mtwalli** [comment]
No planned
