### ISSUE TITLE
Use adaptive icon

### ISSUE THREAD

**Issue by IndianaDschones** [corona-warn-app/cwa-app-android#249]
## Current Implementation

The app icon is always rectangular
![cwa-current-icon](https://user-images.githubusercontent.com/6652142/83970115-342b2f80-a8d4-11ea-855e-e27af0467c8d.png)

## Suggested Enhancement

Use [adaptive icons](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive)

![cwa-adaptive-icon](https://user-images.githubusercontent.com/6652142/83970178-8b310480-a8d4-11ea-85e5-1d6370593a39.png)

## Expected Benefits

The app icon is rendered acording to the users launcher settings. Fallback is a round icon.

**Comment by marcmuschko** [comment]
@IndianaDschones 
Now it should be resolved ( #306 ).
Closing the issue now but please let me know / reopen if it still seems to be off.
Thanks and best,
Marc
