### ISSUE TITLE
Harmonize location setting text in onboarding

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#2506]
## Avoid duplicates
* [X] This enhancement request has not already been raised before
* [X] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

This follows on from the issue https://github.com/corona-warn-app/cwa-app-android/issues/2345

## Current Implementation

During onboarding there is text displayed to explain about the need to activate the location setting in Android.

- The text is inconsistent between English and German translations. 
- The English translation is vague about which Android versions it applies to.
- The German translation does not mention different Android versions at all.

![Activate Location Setting EN DE](https://user-images.githubusercontent.com/66998419/109658933-6fa71180-7b67-11eb-8ed5-7c7aa8329a85.jpg)

## Technical details

- Device name: Samsung Galaxy A5 (2017) SM-A520F
- Android version: 8.0.0
- App version: ~~1.14.0 RC4 (Build Variant: deviceForTestersDebug)~~ 1.14.3

## Steps to reproduce the issue

With locale set to English (United Kingdom) ...

1. CWA > three-dot icon > Settings > Reset App and confirm
2. Tap "LET'S GET STARTED"
3. Tap "NEXT"
4. On screen "How to Enable Exposure Logging" scroll down to the section under "The following countries currently participate" and note the message "Activate Location Setting".

With locale set to Deutsch (Deutschland) ...

1. CWA > three-dot icon > Einstellungen > Anwendung zurücksetzen and confirm
2. Tap "LOS GEHT'S"
3. Tap "WEITER"
4. On screen "Wie Sie die Risiko-Ermittlung ermöglichen" scroll down to the section under "Derzeit nehmen die folgenden Länder teil" and note the message "Standort-Verwendung erlauben".

## Suggested Enhancement

- Make the English and German texts consistent between languages
- Specify the Android versions to which it applies

The string concerned is `onboarding_tracing_location_body` in the corresponding language variation of strings.xml

**EN**
Suggested change to:
"Your device location cannot be determined by the app, but the device location setting must be activated to use Bluetooth Low Energy in Android 10 and earlier."
    
**DE**
Suggested change to:
"Auf Ihren Standort wird nicht zugegriffen. Die Standort-Erlaubnis wird benötigt, um die Verwendung von Bluetooth Low Energy in Android 10 und früher zu ermöglichen."
    
## Expected Benefits

Make the necessity for enabling the Android location setting clearer in both English and German locale settings

---
Internal Tracking ID: [EXPOSUREAPP-5137](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5137)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for the suggestion. As far as I understand there are even some OEM Android 11 devices that require location services to be enabled, apparently Oneplus Devices with Android 11.

**Comment by MikeMcC399** [comment]
@dsarkar 

> As far as I understand there are even some OEM Android 11 devices that require location services to be enabled, apparently Oneplus Devices with Android 11. This might be the reason to be vague about the Android version. Asking for feedback.

It could be that any device which is not fully supported by Google Play services may have this issue. Are you able to check if the OnePlus devices you mention are Play Protect certified? OnePlus is also a Chinese supplier.

See https://support.google.com/android/thread/29434011?hl=en
Answering your questions on Huawei devices and Google services.

**In addition, sideloaded Google apps will not work reliably because we do not allow these services to run on uncertified devices where security may be compromised. Sideloading Google’s apps also carries a high risk of installing an app that has been altered or tampered with in ways that can compromise user security. **

To check if your device is certified, open the Google Play Store app on your Android phone, tap “Menu” and look for “Settings.” You will see if your device is certified under “Play Protect certification.” You can learn more on [android.com/certified](https://www.android.com/intl/en_in/certified/).

(I saw a mention that this is also an issue for the CCTG app.)

**Comment by dsarkar** [comment]
@MikeMcC399 FYI PR https://github.com/corona-warn-app/cwa-app-android/pull/2521

**Comment by dsarkar** [comment]
I think the EN string has not been aligned with DE string, waiting for feedback from dev team.

**Comment by MikeMcC399** [comment]
@dsarkar 
> I think the EN string has not been aligned with DE string, waiting for feedback from dev team.

You may have to wait for the translation team to pick this up.

**Comment by dsarkar** [comment]
@MikeMcC399 Exactly that is the answer I got ... ;-)

**Comment by MikeMcC399** [comment]
The problems raised in this issue have been resolved with the release of CWA Android 1.15.1:

- The text was inconsistent between English and German translations.<br>Now the English and German text versions correspond to each other in meaning.
- The English translation was vague about which Android versions it applies to.<br>The English text now says explicitly that it applies to Android 10 and below.
- The German translation did not mention different Android versions at all.<br>The German text now also specifies the version as in the English version.

Below are screenshots from CWA Android 1.15.1:

![Activate Location Setting EN DE 1 15 1](https://user-images.githubusercontent.com/66998419/112622295-24f97c00-8e2b-11eb-902f-fc21b6c1557d.png)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks.
