### ISSUE TITLE
Proprietary Google libs wrongly licensed via REUSE

### ISSUE THREAD

**Issue by mxmehl** [corona-warn-app/cwa-app-android#2520]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: N/A
- Android version: N/A
- App version: N/A

## Describe the bug

The declaration of copyright and licensing following the [REUSE](https://reuse.software) best practices does not seem to be completely correct. According to the [dep5 file](https://github.com/corona-warn-app/cwa-app-android/blob/main/.reuse/dep5#L27-L29), the proprietary [Google libraries](https://github.com/corona-warn-app/cwa-app-android/tree/main/Corona-Warn-App/libs) in this repo are also licensed under Apache-2.0 with SAP as copyright holder.

## Expected behaviour

The indicated licenses and copyright should match the reality. Otherwise, people will use and reuse the files in this repo under a wrong assumption.

## Possible Fix

Check the repo again for files that do not fall under Apache-2.0 and SAP's copyright.

As we see here, bulk-declaration for complex repositories tend to lead to mistakes. That is why REUSE suggest to add licensing and copyright information directly to file headers, or as accompanying `.license` files.

---
Internal Tracking ID: [EXPOSUREAPP-5542](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5542)

**Comment by dsarkar** [comment]
Hi @mxmehl,

Thank you for your report. This issue now internally being tracked: Internal Tracking ID: [EXPOSUREAPP-5542](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5542). 

Best wishes, DS

---

Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
@mxmehl  FYI PR https://github.com/corona-warn-app/cwa-app-android/pull/2755

**Comment by heinezen** [comment]
@fynngodau Yes, this has been completed. We will close te issue.

----
Corona-Warn-App Open Source Team
