### ISSUE TITLE
[0.8.5] App crashing immediately (file is not a database)

### ISSUE THREAD

**Issue by IndianaDschones** [corona-warn-app/cwa-app-android#253]
## Describe the bug
The current `master` https://github.com/corona-warn-app/cwa-app-android/commit/73c97f9175759cd5fddcd37e163cac9033418d3d (Version 0.8.5) is crashing immediately after opening the app

## Expected behaviour
The app should not crash and show a error message or sth. similar

## Steps to reproduce the issue
Build and run the current master

## Technical details
Log output:
```
 --------- beginning of crash
2020-06-07 15:47:30.655 23244-23244/de.rki.coronawarnapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.rki.coronawarnapp, PID: 23244
    net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
[REMOVED]
```

**Comment by jakobmoellersap** [comment]
Please reinstall the Application and try again. This should come from a change in the Database Encryption Behavior

**Comment by IndianaDschones** [comment]
You´re right. The app now starts as intended 👍 
Thanks for the fast response
