### ISSUE TITLE
Small typos in 1.13.2 de legal strings

### ISSUE THREAD

**Issue by vaubaehn** [corona-warn-app/cwa-app-android#2541]
cc: @janetback 

https://github.com/corona-warn-app/cwa-app-android/blob/d0ac6ce089653ad4be7713f11c8bca5ca4c70e6b/Corona-Warn-App/src/main/res/values-de/legal_strings.xml#L68

"... mehrfach **an** der Befragung teilnehmen..."
"... Die Kennung wird " **hierfür/hierzu** " einmalig an Google..."

---
Internal Tracking ID [EXPOSUREAPP-5576](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5576) Typos
Internal Tracking ID: [EXPOSUREAPP-5578](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5578) AHA+L+A

**Comment by fredsleeve** [comment]
Please consider also to specify "RKI" as "Robert Koch-Institut" and "Google" maybe as "Google LLC" (just in case some one thinks about "Google" search engine).

**Comment by dsarkar** [comment]
@vaubaehn Thanks. 

---
Internal Tracking ID [EXPOSUREAPP-5576](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5576)

**Comment by Jo-Achim** [comment]
I'll get in here ... 
A supplement / correction to the "**AHA**" rules under "Conditions of use", point 4. 

Correctly, the rules are not "**AHA**", but "**AHA+L+A**"; see: [https://www.infektionsschutz.de/coronavirus/alltag-in-zeiten-von-corona.html](url).

So **AHA+L+A** = keep your distance, observe hygiene, wear a mask in everyday life, ventilate regularly and use the corona warning app. 

Thus, the information under "Terms of Use", point 4 could look like this, for example (in German); changes to the previous text are written in _italics_:

> _Halten Sie sich an die **AHA+L+A-Regeln**:_
> 
> **A** – Halten Sie mindestens 1,5 m Abstand zu Ihren Mitmenschen.
> **H** – Waschen Sie sich regelmäßig für mindestens 20 Sekunden die Hände.
> **A** – Tragen Sie beim Einkauf und in öffentlichen Verkehrsmitteln eine _vorgeschriebene_ Alltagsmaske.
> _**L** – Lüften Sie geschlossene Innenräume in regelmäßigen Abständen für einige Minuten._
> _**A** – Nutzen Sie diese Corona-Warn-App und deren Funktionen, wie das Kontakt-Tagebuch usw._
> 
> So schützen Sie sich selbst und andere vor dem Virus.

Changes to the previous text are written in _italics_. 

Best regards, Joachim.

**Comment by dsarkar** [comment]
@vaubaehn @fredsleeve 

Android: https://github.com/corona-warn-app/cwa-app-android/pull/2561
iOS: https://github.com/corona-warn-app/cwa-app-ios/pull/2174

Just preposition corrected. 
The second item (hier) is not strictly considered an error. Same with respect to Google (LLC).

**Comment by dsarkar** [comment]
@Jo-Achim Thanks, could you please split your issue into a separate issue. Thanks.

**Comment by Jo-Achim** [comment]
> 
> 
> @Jo-Achim Thanks, could you please split your issue into a separate issue. Thanks.

Is that now obsolete?

**Comment by dsarkar** [comment]
@Jo-Achim 


> Is that now obsolete?

No. But should be created as a wishlist issue, not a bug. It was already analysed internally and is not considered as a bug, but will be considered as an enhancement. Thanks!

**Comment by dsarkar** [comment]
FYI https://github.com/corona-warn-app/cwa-app-android/pull/2579/files

**Comment by vaubaehn** [comment]
@dsarkar thanks for your notifications!

(it's awesome, how many people have already been involved in that issue just because of two missing letters "an", isn't it?)

**Comment by dsarkar** [comment]
@vaubaehn The has been changed. We suggest closing this issue. Best, DS 


---
Corona-Warn-App Open Source Team

**Comment by vaubaehn** [comment]
@dsarkar Thanks for your information - yes, the issue of the OP has been solved, and I will close this **epic** issue now :)
Have a nice Easter week-end!

@MikeMcC399 @Jo-Achim If there is still something left open for you, you may notify me for re-opening here, or open a new issue.

**Comment by dsarkar** [comment]
@vaubaehn Thanks, same to you, a nice Easter week-end!
