### ISSUE TITLE
Is Privacy Preserving Data Donation (PPDD) working on LineageOS with microG?

### ISSUE THREAD

**Issue by Diapolo** [corona-warn-app/cwa-app-android#2552]
I'm using the current CWA version 1.13.2 on my Fairphone 2 with LineageOS with microG (no Google-apps installed). As far as I know and read here in the repo PPDD is requiring Safetynet and thus it should not work on my device. At least I get not error or message that this IS the case. Can any dev comment on this?

Thanks,
Dia

**Comment by MikeMcC399** [comment]
Hi @Diapolo

I'm not a dev, but the official message is that Google Play services is a pre-requisite for running CWA.
See https://www.coronawarn.app/en/faq/#minimum_requirements

I did try out CWA 1.13.2 on an Android emulator without Google Play services and I only got a notification
"Update Google Play services
Corona-Warn won't run unless you update Google Play services."
I didn't get any special message when I enabled "Share Data".

I know that is not your configuration, but it might give you some clue.

**Comment by thomasaugsten** [comment]
Without SafetyNet or a reimplementation you are not able to send analytics information in the background this will not result in an error visible for the user. You will receive an error If you try to attend at the RKI survey when you receive a red exposure notification card.

**Comment by Ein-Tim** [comment]
Cross reference to: https://github.com/corona-warn-app/cwa-wishlist/issues/356

**Comment by MikeMcC399** [comment]
Is this question now answered? Can it be closed?

**Comment by Diapolo** [comment]
Yes, even if I would like an alternate solution without Safetynet ;-).
