### ISSUE TITLE
Current 1.14.3.0 RC takes 1-10s before main screen cards are shown

### ISSUE THREAD

**Issue by Bubu** [corona-warn-app/cwa-app-android#2557]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Nexus 5X
- Android version: 8.1
- App version: 1.14.3.0

## Describe the bug

In the current 1.14 RC release the app takes a very long time to display the main screen cards. It seems to be doing some network related things that block displaying the cards (The toolbars and bottom navigation bar are shown). When on a fairly good network connection it still takes around 1s until any of the cards are displayed. On a not so great network connection I've been staring at an empty home screen for 10+s.

This hasn't been an issue in previous releases.

## Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/105185/110466290-e0a17880-80d5-11eb-8063-74a5b66f908b.png)

* Complete onboarding
* Swipe away the app from recents
* Open the app
* See an empty main screen

## Expected behaviour

Cards show instantly after the splash screen finishes.

## Possible Fix

Remove the blocking call and update the relevant UI parts later after it completes... (But then I haven't investigated what it's actually doing)

---
Internal Tracking ID: [EXPOSUREAPP-5616](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5616)

**Comment by Bubu** [comment]
Did some more testing, also had that with 1.13.2 now... I currently suspect it's the tester flavour build. (Which makes this issue not relevant for production builds.) I'll continue keeping an eye on this.

**Comment by dsarkar** [comment]
@Bubu Thanks. We will wait for your feedback.

Internal Tracking ID: [EXPOSUREAPP-5616](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5616)

**Comment by Bubu** [comment]
I don't really know what's going on. I can't really reproduce this anymore now.

Sorry for the noise.

**Comment by dsarkar** [comment]
@Bubu No problem at all. Thanks for contributing! Best wishes, DS

---
Corona-Warn-App Open Source Team
