### ISSUE TITLE
Display Google Exposure Notifications System version more user-friendly

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#2564]
## Avoid duplicates
* [X] This enhancement request has not already been raised before
* [X] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

Last reviewed for relevance on App version: 2.22.1

The CWA Android App Information provides a version number of the Google Exposure Notifications System at the bottom of the screen. Use the three-dot menu on the CWA Start Screen to access App Information.

![App Information EN ENF Version](https://user-images.githubusercontent.com/66998419/110522151-e49ebc00-8110-11eb-8c2f-441ae5c674d2.jpg)

## Disadvantages of current implementation

1. The version number in the app (e.g. from the above screenshot 18210613000) does not correspond to the version number described in the [Exposure Notification release notes](https://developers.google.com/android/exposure-notifications/release-notes) e.g. v1.8.
2. To explain how to parse a full version number a detailed FAQ article https://www.coronawarn.app/en/faq/#ENF_version was published through PR #https://github.com/corona-warn-app/cwa-website/pull/207. This is more complicated than ought to be necessary.
3. The App Information display uses the abbreviation "ENF", however only Apple refers to an Exposure Notification framework (ENF). Google consistently refers to their module as "Exposure Notifications System", for example in the help directly linked to via Android Settings > Google > COVID-19 Exposure Notifications > Learn more. Google only rarely abbreviates this term and then they use "ENS" as in https://support.google.com/android/answer/9930236?hl=en 
"Google and Apple have built in safeguards to ensure that government contact tracing apps built with **ENS** cannot infer your location." or in the original program announcement https://blog.google/inside-google/company-announcements/update-exposure-notifications/.

## Suggested Enhancement

1. When an 11-digit ENS version number is retrieved from gms, parse and display the first two digits as the version number in addition to displaying the full version number in brackets.
2. Change the label from ENF to ENS.

So for instance instead of displaying:

`ENF Version: 18210613000`

that could become:

`ENS Version: v1.8 (18210613000)`

## Expected Benefits

1. It will be easier to recognize the version number of the Google Exposure Notifications System without a user having to understand the coding of VVYYWWnnnnn where 
VV = version
YY = year
WW = week
nnnnn
2. The version number displayed by the app will be directly relatable to the version number described in the [Exposure Notification release notes](https://developers.google.com/android/exposure-notifications/release-notes).
3. The FAQ https://www.coronawarn.app/en/faq/#ENF_version complexity can be reduced because it will no longer be necessary to describe to users how to decode a Google Exposure Notifications System version number by hand.

## Additional information

I made the equivalent enhancement request to Google for their UI and they have implemented it in the v1.8 (211213000) release.

---
Internal Tracking ID: [EXPOSUREAPP-5641](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5641)

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-5641](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5641)

**Comment by dsarkar** [comment]
@MikeMcC399 
Different topic:
Samsung A21 / Android 10 / CWA 1.13 / German locale / BT off / OS ENS pop-up notification in English.
Are you able to reproduce this?

![image](https://user-images.githubusercontent.com/1409741/110784038-7588ab00-8269-11eb-97dd-69e1745bbdb0.png)

**Comment by MikeMcC399** [comment]
@dsarkar 

The notification is from Google Exposure Notifications System, not from CWA. 

My Phone ENF Version is 18210214000 which is slightly older than yours (18210613000) and I cannot reproduce with the language set to Deutsch (Deutschland).

I have a tablet which is already running 18210613000 but that gave me no notifications at all.

If you want to continue to discuss this, please open a new issue as it doesn't belong here!

**Comment by vaubaehn** [comment]
The ENS UI was updated recently, now showing 
`
Version v1.8 (211213000)`

To support @MikeMcC399 's suggestion: CWA version number and ENS UI version number could be aligned (similar formattig) which is then also more user-friendly.

**Comment by MikeMcC399** [comment]
- This enhancement request is queued for release with CWA 2.27. 
- It brings the display of the Google Exposure Notifications System version in CWA into alignment with the Android Settings Google UI

App UI: CWA Three-dot symbol > App Information
Google UI: Android Settings > Google > COVID-19 Exposure Notifications

Closing, since the change is part of the [2.27.x milestone](https://github.com/corona-warn-app/cwa-app-android/milestone/64).
