### ISSUE TITLE
Duration Dialog Cancel not translated in German App

### ISSUE THREAD

**Issue by DerVogel2020** [corona-warn-app/cwa-app-android#2587]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy A5
- Android version: 8
- App version: 1.14.3

## Describe the bug

Edit the Duration for a location. The Cancel-Text is in English, in the German App.

## Steps to reproduce the issue

See attached Screenshot.
![Screenshot_20210311-194427_Corona-Warn.jpg](https://user-images.githubusercontent.com/65366950/110838920-50189300-82a3-11eb-9796-b77092344dd7.jpg)

## Expected behaviour

Abbrechen instead of Cancel

## Additional context

---
Internal Tracking ID: [EXPOSUREAPP-5736](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5736)

**Comment by PhilippNowak96** [comment]
The issue is located here: https://github.com/corona-warn-app/cwa-app-android/blob/86f032656e1268690de179bdc5fd91510c2b8e45/Corona-Warn-App/src/main/res/values-de/strings.xml#L1892

**Comment by DerVogel2020** [comment]
Suggestion: If it's possible, create a bot to check that no element value in the xml file with the German texts contains an English word.

**Comment by dsarkar** [comment]
@DerVogel2020 @PhilippNowak96 Thanks for reporting.

---
Internal Tracking ID: [EXPOSUREAPP-5736](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5736)

**Comment by ralfgehrer** [comment]
PR: https://github.com/corona-warn-app/cwa-app-android/pull/2614

**Comment by MikeMcC399** [comment]
@DerVogel2020 

Would you like to close this issue when you have had a chance to check it yourself with the 1.15.1 version? CANCEL has been changed to ABBRECHEN when the language is set to German.

![Dauer abbrechen DE](https://user-images.githubusercontent.com/66998419/112669292-d5817300-8e5f-11eb-9913-f5bee4464480.png)

**Comment by DerVogel2020** [comment]
If course. But I didn't receive the update yet.

**Comment by dsarkar** [comment]
@DerVogel2020 @MikeMcC399 Thanks for contributing here. Best, DS
