### ISSUE TITLE
Label discrepancy for direct access to Contact Journal

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#2588]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation). 
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy A50 SM-A505FN
- Android version: 10
- App version: 1.14.3

## Describe the bug

The Contact Journal short-cut is labelled
"Add Entry"

The New Features text says it is labelled 
“Add Journal Entry for Today”

"Add Entry" is not the same as “Add Journal Entry for Today”.

From New Features:
**"Direct Access to Contact Journal"**

"You can now add an entry to your contact journal directly, without having to open the app first. To do so, tap and hold the icon for the Corona-Warn-App for approximately 2 seconds, until a menu appears, and then tap “Add Journal Entry for Today”."</item>

## Steps to reproduce the issue

1. Tap and hold the icon for the Corona-Warn-App for approximately 2 seconds, until a menu appears.
2. Make a note of the label "Add Entry".
3. Do not tap on the Add Entry label, instead tap twice on the Corona-Warn-App icon to open the app at the Start Screen.
4. Assuming the app has already been used and onboarded after installation or update, tap the three-dot icon on the Start Screen.
5. Tap App Information > New Features
6. Scroll down to "Direct Access to Contact Journal" and read the text. Compare the name of the label in the text to the name of the label seen in step 1.

![Add Entry](https://user-images.githubusercontent.com/66998419/110840392-f4e7a000-82a4-11eb-8fb8-281a570bfab4.jpg)

## Expected behavior

The name of the short-cut label for the Contact Journal should correspond to the name given in the New Features text.

## Possible Fix

I can't say which of the labels is correct, but they should be identical, meaning one of them needs to be changed.

---
Internal Tracking ID: [EXPOSUREAPP-5810](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5810)

**Comment by DerVogel2020** [comment]
In German it's similar: "Tagebucheintrag für heute hinzufügen" in the new features list vs.  "Eintrag hinzufügen" when the App Icon is pressed.

**Comment by Ein-Tim** [comment]
iOS is correct, no discrepancy.

**Comment by dsarkar** [comment]
@MikeMcC399 @DerVogel2020 @Ein-Tim Thanks.

---
Internal Tracking ID: [EXPOSUREAPP-5810](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5810)

**Comment by MikeMcC399** [comment]
@dsarkar 
Thank you!

Would you consider changing the label [contact-diary](https://github.com/corona-warn-app/cwa-app-android/labels/contact-diary) to call it "contact-journal" instead because in the app and documentation it goes by the name of "Contact Journal"?

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for the suggestion, however, feedback:

> this is intentional as there is only very limited  space on the short cut for Android.

**Comment by MikeMcC399** [comment]
@dsarkar 
> this is intentional as there is only very limited space on the short cut for Android.

I can understand that the label is short, however the "New Features" text should have used the correct name of the label. In other words:

"You can now add an entry to your contact journal directly, without having to open the app first. To do so, tap and hold the icon for the Corona-Warn-App for approximately 2 seconds, until a menu appears, and then tap **“Add Entry”**."

Unless there is going to be a follow on to 1.14.3, like 1.14.4 for instance, for Android there is no chance to change this now because it will not be a new feature in 1.15.x, so we should probably close this issue now.

**Comment by MikeMcC399** [comment]
Closing due to "wontfix" response.
