### ISSUE TITLE
Contact Journal: When entering place information, the sequence (duration first, then note) is relevant

### ISSUE THREAD

**Issue by Thusid** [corona-warn-app/cwa-app-android#2594]
## Avoid duplicates
* [x] This enhancement request has not already been raised before
* [ ] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

When entering place information in the contact journal, currently the sequence is relevant (duration first, then note). If entered the other way around (note first, then duration) the note is lost.

## Suggested Enhancement

Either sequence should be feasible without data loss.

## Expected Benefits

No data loss.

---
Internal Tracking ID: [EXPOSUREAPP-5751](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5751)

**Comment by MikeMcC399** [comment]
@Thusid 
Good catch! I can reproduce this (on Android 8 and 11).

It should be classified as a bug, not an enhancement.

**Comment by dsarkar** [comment]
@Thusid @MikeMcC399 Thank you. 

Internal Tracking ID: [EXPOSUREAPP-5751](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5751)

**Comment by dsarkar** [comment]
FYI PR https://github.com/corona-warn-app/cwa-app-android/pull/2606

**Comment by MikeMcC399** [comment]
@Thusid 

I checked this on the released version 1.15.1, entering a note before setting the duration and the text in the note field was preserved.

Feel free to check it yourself and close the issue if you are satisfied!

**Comment by Thusid** [comment]
@MikeMcC399 Thank you for the hint.

I can confirm that this bug has been fixed (CWA 1.15.1).

**Comment by dsarkar** [comment]
@Thusid @MikeMcC399 Thanks!
