### ISSUE TITLE
Exceptions From Workers Get Reported As Toasts

### ISSUE THREAD

**Issue by Magoli1** [corona-warn-app/cwa-app-android#26]
## Current Implementation
Currently, the app opens a Toast, if any worker encounters an exception of any type. This can be an issue if the app is in the background, and a worker gets into an error state. Then the user gets a Toast message, possibly completely out of context due to currently being in another app. Example:
https://github.com/corona-warn-app/cwa-app-android/blob/43412bdabe128dc674ec8a9ef8baa80d37292a3a/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/worker/DiagnosisKeyRetrievalPeriodicWorker.kt#L37

In addition to that, a technical message is shown, as the Throwable localizedmessage is used for the text.

## Suggested Enhancement
If the user really needs to have information about these kind of errors, the user should get a notification with a human readable error text. This could be implemented by making use of the ``enum class ExceptionCategory``, which is already in place. In our eyes it would only make sense to notify the user, if the user can change the situation to the good.

## Expected Benefits
The user does not get disturbed during the usage of the mobile phone, especially when working in other apps. Also the user could decide if the error needs attention from the users side.

Best Regards
Robert Jakobs & Tim Brüggenthies (@timbrueggenthies)

**Comment by marcmuschko** [comment]
Dear @Magoli1 ,

thank you for mentioning this! 
At the moment, we do not have a finalized concept regarding error handling how, and which kind of messages will be displayed to the user. As soon as this is settled, we will include proper messaging and replace toasts when appropriate! 

I will pin this issue as others might stumble across the error handling concept in its current state as well, it will be closed once we have it resolved. We will also add it to the list of known issues.
Thank you and best,
Marc

**Comment by marcmuschko** [comment]
So coming back to the issue - as we now have error handling with proper dialogs in place I am closing this for now. 
If you find any inconsistencies or have other sugggestions regarding error handling in general, please let us know :)

Thanks and best,
Marc
