### ISSUE TITLE
Contact Journal: Place duration (Std.) not translated

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#2608]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation). Not yet known.
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy A5 (2017) SM-A520F
- Android version: 8.0.0
- App version: 1.14.3

## Describe the bug

The abbreviation for hours in the overview of the Contact Journal for a Place entry appears in German when the locale is set to English.

![Contact Journal duration EN DE](https://user-images.githubusercontent.com/66998419/111066345-d78e1e00-84be-11eb-92d6-3caa16874688.png)

All other text on this page is shown in English.

## Steps to reproduce the issue

1. Set the device locale to English (United Kingdom)
2. Open CWA
3. Tap Journal at the bottom of the screen
4. If this is the first time using the Contact Journal, first tap "OPEN JOURNAL"
5. Tap the calendar entry for today
6. Tap PLACES
7. Tap + PLACE
8. Enter "Test" in Description field
9. Tap "SAVE"
10. In Duration field time picker select any non-zero duration e.g. 00:15, tap OK
11. Tap Back button
12. Note that the place is displayed with
Test
00:15 Std.

## Expected behavior

When the locale is set to English (United Kingdom) then all text shown in the Contact Journal should be shown in English.

## Possible Fix

Translate the string "Std." into other supported languages, including English.

Consider using "hrs:min" for the English translation.

---
Internal Tracking ID: [EXPOSUREAPP-5809](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5809)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks.


---
Internal Tracking ID: [EXPOSUREAPP-5809](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5809)

**Comment by ralfgehrer** [comment]
PR: https://github.com/corona-warn-app/cwa-app-android/pull/2617

**Comment by MikeMcC399** [comment]
Looks good on 1.15.0-RC3.

Now `00:15 h` is displayed.

**Comment by MikeMcC399** [comment]
In the released version 1.15.1, with locale set to:

- English (United Kingdom) the place duration is shown with the abbreviation<br>**hrs**
- Deutsch (Deutschland) the place duration is shown with the abbreviation<br>Std.

So the translation issue has been successfully fixed.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for checking. Forwarded to internal ticket.
