### ISSUE TITLE
Contact Journal: Duration wraps unnecessarily

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#2610]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Google Nexus 5 API 30 emulator
- Android version: 11
- App version: 1.14.3

## Describe the bug

Under some circumstances the display of the duration for a place in the Contact Journal can wrap onto multiple lines, even though there is enough room on the display to keep the duration in one line. This makes it harder to read.

![Duration wrap bug zoom](https://user-images.githubusercontent.com/66998419/111074676-6a8d7f00-84e4-11eb-8d87-54f3cd93d504.png)

## Steps to reproduce the issue

1. In Android Settings > Display > Advanced > Font size
2. Select Large font size
3. Open CWA and tap Journal
4. If using Journal for first time, then tap "OPEN JOURNAL"
5. Tap date today, tap PLACES, tap + PLACE
6. In field Description type for instance "Test Place"
7. Tap Save
8. Select duration 15 (minutes)
9. Note that the Duration is shown as
`00:1`
`5`
10. In Android Settings > Display > Advanced > Font size
11. Select Default font size
12. Return to CWA app as before and note that the Duration is now displayed on one line only as
`00:15`

The screenshot shows the problematic display on the left, with the normal display on the right.

![Duration wrap bug](https://user-images.githubusercontent.com/66998419/111074629-269a7a00-84e4-11eb-8689-f625d518c6c4.png)

## Expected behavior

If room on the screen allows, then the display of the duration value for a recorded place in the Contact Journal should stay on one line.

---
Internal Tracking ID: [EXPOSUREAPP-5807](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5807)

**Comment by dsarkar** [comment]
Internal TRacking ID: [EXPOSUREAPP-5807](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5807)

**Comment by ralfgehrer** [comment]
PR: https://github.com/corona-warn-app/cwa-app-android/pull/2582

**Comment by MikeMcC399** [comment]
I checked with 1.15.0-RC3 on Google Nexus 5 API 30 emulator with font set to "Largest" and the problem was no longer reproducible.

I suggest leaving the issue open until 1.15.x is released and I will verify again with the released version.

**Comment by MikeMcC399** [comment]
Verified fixed with CWA Android 1.15.1 on
Device name: Google Nexus 5 API 30 emulator
Android version: 11
and Font size: Small, Default, Large and Largest.

In all cases the duration was displayed in one line without wrapping to following lines.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks. Verification forwarded to dev ticket.
