### ISSUE TITLE
Google Bluetooth disabled notification not translated to German

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#2657]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue
This bug was mentioned as an aside in https://github.com/corona-warn-app/cwa-app-android/issues/2564#issuecomment-796685805 from @dsarkar.

## Technical details

- Device name: Samsung Galaxy A5 (2017) SM-A520F
- Android version: 8.0.0
- App version: 1.14.3
- Google Exposure Notifications System version: 18210613000

## Describe the bug

The notification produced by the Google Exposure Notifications System when Bluetooth is disabled is partially in English when the device locale is set to Deutsch (Deutschland) i.e. German.

## Steps to reproduce the issue

1. Set device locale to Deutsch (Deutschland)
2. Open CWA and ensure that status "RISIKO-ERMITTLUNG AKTIV" is shown
3. Close CWA
4. Einstellungen > Verbindungen > Bluetooth and disable Bluetooth (AUS)
5. Wait for notification

The notification no longer appears immediately, like it did in the past. You need to wait. I don't know what controls the delay and I can't say how long you need to wait: somewhere between 5 and 30 minutes.

The screenshot below shows the notification with the locale set to Deutsch (Deutschland) on the left and English (United States) on the right,

![Unable to check for exposures DE EN](https://user-images.githubusercontent.com/66998419/111882975-ccecf080-89b8-11eb-88d6-85832a0dc06f.jpg)

## Expected behavior

If the device locale is set to Deutsch (Deutschland) then the complete text of the Google Exposure Notifications System notification should be in the German language. The notification is displayed (delayed) after Bluetooth is disabled whilst there is an active COVID-19 app on the device.

## Possible Fix

Ensure that German strings are available and used for the Google ENS notification message.
This is a Google issue.

---
Internal Tracking ID: [EXPOSUREAPP-5574](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5574)

**Comment by MikeMcC399** [comment]
@dsarkar posted detailed screenshots showing the previous message in https://github.com/corona-warn-app/cwa-app-android/issues/920#issuecomment-750849906:

![image](https://user-images.githubusercontent.com/1409741/103085022-c977e200-45e0-11eb-9f47-6fd6175c7128.png) 

This shows that it is a regression in Google ENS.

**Comment by heinezen** [comment]
@MikeMcC399 

Thank you. I have created a Jira ticket for the problem. We will notify Google about the issue.

----
Corona-Warn-App Open Source Team

**Comment by thomasaugsten** [comment]
Will be fixed in the next Google ENF release v1.8 >= 210900000

**Comment by dsarkar** [comment]
Duplicate of Internal Tracking ID: [EXPOSUREAPP-5574](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5574)

**Comment by MikeMcC399** [comment]
Verified fixed with Google Play services (Google Play-Dienste) 21.09.15, shown in CWA as 18210915000.

The following notification is shown 30 minutes after disabling Bluetooth when:
- device locale is set to Deutsch (Deutschland)
- CWA is installed and was showing "RISIKO-ERMITTLUNG AKTIV" before Bluetooth was disabled

![Bluetooth off notification DE](https://user-images.githubusercontent.com/66998419/112317894-c5756200-8cac-11eb-87bd-16ae6bfb23e9.jpg)

Closing due to successful resolution by Google.

**Comment by dsarkar** [comment]
@MikeMcC399  thanks for checking.

**Comment by dsarkar** [comment]
@MikeMcC399 I can confirm your observation in your last comment. Did you trigger to get the new ENS the following way?

OS Settings > Apps > Scroll down to Google Play Services and tap on it > Scroll down to details in store and tap on it > tap on update.

Then close CWA (swipe up) and re-open CWA.

**Comment by MikeMcC399** [comment]
@dsarkar 
> OS Settings > Apps > Scroll down to Google Play Services and tap on it > Scroll down to details in store and tap on it > tap on update.

That is a good way to check if any updates are available to Google Play services (including the Exposure Notifications System). In fact I have one device that updated on its own and another device Samsung Galaxy A50 SM-A505FN which still hasn't had an update offered. This one has 21.06.13 (120400-358943053) of Google Play services currently installed. I would have expected it to get [Version: 21.09.15 (120400-361652764)](https://www.apkmirror.com/apk/google-inc/google-play-services/google-play-services-21-09-15-release/google-play-services-21-09-15-120400-361652764-android-apk-download/) installed, but something seems to be preventing the rollout of this particular variant. Perhaps there is an issue and Google has paused the rollout?

**Comment by dsarkar** [comment]
@MikeMcC399 

> I would have expected it to get Version: 21.09.15 (120400-361652764) installed, but something seems to be preventing the rollout of this particular variant. Perhaps there is an issue and Google has paused the rollout?

I triggered the update with above described method about one hour ago.

**Comment by MikeMcC399** [comment]
@dsarkar 
> I triggered the update to Version: 21.09.15 (120400-361652764) with above described method about one hour ago.

Interesting! What device and what Android version is this for? Mine is A50 and Android 10.

**Comment by dsarkar** [comment]
@MikeMcC399 Samsung A21s and Android 10. Just now I got feedback from a dev: Also Google Play Services is rolled out in stages.

**Comment by dsarkar** [comment]
@MikeMcC399 Could you let me know if you could trigger a Google Play Services update at some point on your Samsung Galaxy A50 SM-A505FN  and if this then included ENS > 210900000? Thanks!

**Comment by MikeMcC399** [comment]
@dsarkar 
My Samsung Galaxy A50 SM-A505FN is still at 
`21.06.13 (120400-358943053)`
and no update for Google Play services is offered to me by Google Play Store at this time. I will continue to monitor the device.

**Comment by dsarkar** [comment]
@MikeMcC399 Good morning, could you update GPServices? Thanks.

**Comment by MikeMcC399** [comment]
@dsarkar 
Good morning!
No change on the device Samsung Galaxy A50 SM-A505FN. If I go to Google Play Store there is no option to Update, only to Deactivate.

**Comment by dsarkar** [comment]
@MikeMcC399 OK, thanks for the feedback! I assume that ENS version number has not change and notifications are still in English then (even when German locale). Will try to get some info, if roll-out has been stopped.

**Comment by MikeMcC399** [comment]
@dsarkar 
On my Samsung Galaxy A50 SM-A505FN the ENS has updated automatically to Version 18210915000.

The UI also now has an additional option "Add another region". This feature allows the user to choose a country and if appropriate also a region in a country. This then links to an entry for the appropriate app in the Google Play Store to be able to install the app. Google Exposure Notifications System still allows only one region to be active at one time, so if a user of CWA for Germany installs an app from another country and makes this other app active then CWA will be deactivated. By opening CWA it is possible to switch back to CWA as active app once again.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for the feedback. So apparently no always and every user can update Google Play Services on demand.

> The UI also now has an additional option "Add another region". This feature allows the user to choose a country and if appropriate also a region in a country. This then links to an entry for the appropriate app in the Google Play Store to be able to install the app. Google Exposure Notifications System still allows only one region to be active at one time, so if a user of CWA for Germany installs an app from another country and makes this other app active then CWA will be deactivated. By opening CWA it is possible to switch back to CWA as active app once again.

This reminds me that we probably need a FAQ explaining what to do if you travel.

**Comment by MikeMcC399** [comment]
@dsarkar 
> So apparently no always and every user can update Google Play Services on demand.

Unfortunately the way Google handles this is not transparent, so it's difficult to predict what is possible and not possible.

> This reminds me that we probably need a FAQ explaining what to do if you travel.

That would be a good idea. It could cover short trips, longer trips and what to do if a user lives in a border region and regularly moves between one country and another such as on a daily basis.
