### ISSUE TITLE
Exposure check not working 1.14.3

### ISSUE THREAD

**Issue by cfra** [corona-warn-app/cwa-app-android#2669]
## Technical details

- Device name: Pixel 3a XL
- Android version: 11, Security Update March 5 2021, Play system update February 1, 2021
- App version: 1.14.3

## Describe the bug

Since a few days, the app fails to perform the exposure check. I get an initial error message. Afterwards, the card is just stuck at the spinner:

![signal-2021-03-22-155405_001](https://user-images.githubusercontent.com/1347051/112010482-a5686600-8b27-11eb-8835-1cef35e3d8e6.png)
![signal-2021-03-22-155405_002](https://user-images.githubusercontent.com/1347051/112010503-aac5b080-8b27-11eb-93c5-4e573d63b9ee.png)
![signal-2021-03-22-155405_003](https://user-images.githubusercontent.com/1347051/112010529-aef1ce00-8b27-11eb-9809-0296f80f848a.png)

## Steps to reproduce the issue

I did not perform any notable actions prior to this problem and the app was working fine initially.

## Expected behaviour

Exposure status calculation should ideally run correctly.

Alternatively, it should terminate with a sensible error message that gets shown on the card.

The card should not get stuck indicating progress forever.

**Comment by thomasaugsten** [comment]
This is known issue on google side.
If you are interested you can report a log file and we can submit this to google.

https://developer.android.com/studio/debug/bug-report
and send to thomas.augsten@sap.com

This problem will disappear in the next days.

**Comment by MikeMcC399** [comment]
@thomasaugsten 
> This problem will disappear in the next days.

What will make the problem disappear?
1. Google configuration parameter change?
2. Google Play services update from Google Play Store?

**Comment by MikeMcC399** [comment]
@cfra 
Just for info, there is a main issue open on this topic https://github.com/corona-warn-app/cwa-app-android/issues/1962. This issue is mentioned in the link https://www.coronawarn.app/en/faq/#10 (redirects to https://www.coronawarn.app/en/faq/#API10) showing up in the error message you posted.

**Comment by cfra** [comment]
Sorry for the noise, for some reason scrolling to the `#10` anchor did not work for me when I followed the link. :see_no_evil:
