### ISSUE TITLE
Integrate battery optimization dialog into onboarding

### ISSUE THREAD

**Issue by fynngodau** [corona-warn-app/cwa-app-android#2683]
### Current situation

After completing the onboarding, users are facing a series of dialogs that ask them to disable battery optimizations (along with some additional information on exposure notifications). Those dialogs are merely a popup, potentially annoying and not looking important to users.

| Dialog with information on exposure notifications | Dialog asking users to disable battery optimizations | Additional dialog if battery optimizations are disabled |
|---|---|---|
| ![Screenshot_1616846248](https://user-images.githubusercontent.com/16943720/112720022-5aba6580-8efc-11eb-92bd-54ae479a5d25.png) | ![Screenshot_1616846253](https://user-images.githubusercontent.com/16943720/112720025-5c842900-8efc-11eb-9700-67c0e3ba88e1.png) | ![Screenshot_1616846261](https://user-images.githubusercontent.com/16943720/112720026-5db55600-8efc-11eb-8ab0-e1066b300d01.png) |

### Suggested improvement

The onboarding flow should contain a page that asks users to disable battery optimizations.

### Expected benefits

The onboarding flow feels better when it is actually complete when it seems to be done, instead of being followed by more popup dialogs. The rate of users who disable battery optimizations might improve, which would be good.

### See also
#2682 Warn about deactivated battery optimization on main screen
#1606 Improve UX for disabling battery optimization (an issue about using `ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS`)

For any readers having trouble disabling the battery optimization, there are some instructions in the FAQ
https://www.coronawarn.app/en/faq/#no_risk_update about how to do this.

---
Internal Tracking ID: [EXPOSUREAPP-5965](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5965)

**Comment by MikeMcC399** [comment]
@fynngodau 

This is very similar to the enhancement request #1606 which you already quoted.

Maybe the devs could fill us in on the decision which led to this function being removed? I guess it was because it wasn't reliable across all vendors.

I can quite imagine that most users will ignore the dialog, as you say. It's difficult for somebody unfamiliar with the concepts to understand what is being requested and what needs to be done.

It was interesting to read the feedback from @thomasaugsten in https://github.com/corona-warn-app/cwa-app-android/issues/2682#issuecomment-805142879 about how other methods are being used to mitigate the issue of battery optimization.

**Comment by fynngodau** [comment]
@MikeMcC399 This is quite the different question – #1606 is about the way that the app leads the user to the system dialog, this is about asking the user "more properly" than just with a not-as-pretty popup (i.e. with a full-screen page in the onboarding process).

**Comment by MikeMcC399** [comment]
@fynngodau 
Thanks for explaining your intentions. I support anything which reduces the complexity for the user!

**Comment by dsarkar** [comment]
Dear @fynngodau, @MikeMcC399, and community

Thank you for your contributions.

We have created a ticket for the bug (Internal Tracking ID: EXPOSUREAPP-5965) in the internal Jira system. Any further developments will be notified here in this Github issue.
  
Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
For any readers having trouble disabling the battery optimization, there are some instructions in the FAQ
https://www.coronawarn.app/en/faq/#no_risk_update about how to do this.

**Comment by dsarkar** [comment]
@MikeMcC399 I added your comment to OP. Thanks.

**Comment by fynngodau** [comment]
I added screenshots to my original post to illustrate which dialogs I am referring to.

**Comment by dsarkar** [comment]
@fynngodau OK, thanks. Added screenshots to the internal ticket.

**Comment by fynngodau** [comment]
Same spirit for the new root check: it is currently displayed before startup, therefore before any onboarding, and could have been realized as an additional onboarding screen as well (if wanted, also as one that is displayed at each startup).

**Comment by Ein-Tim** [comment]
Is there an update available here @dsarkar?

**Comment by mtwalli** [comment]
No planned
