### ISSUE TITLE
Malformed ripple effect in contact journal

### ISSUE THREAD

**Issue by fynngodau** [corona-warn-app/cwa-app-android#2701]
## Describe the bug

The (i) button next to the Note field in both People as well as Places view in contact journal has a malformed ripple effect. The effect should be circular like the (i) icon, but it actually is elliptic.

## Steps to reproduce the issue

Open contact journal, open any day, add a place, hold (i) icon. The following ripple effect is shown:

![Screenshot_1616949710](https://user-images.githubusercontent.com/16943720/112759881-46a65f00-8ff5-11eb-987c-44bcc5d87821.png)

## Expected behaviour

The ripple effect should be the same shape as the (i) icon.

## Technical details

- Device name: emulator and others
- Android version: 6, 10
- App version: 1.15.1

---
Internal Tracking ID: [EXPOSUREAPP-6002](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6002)

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-6002](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6002)

**Comment by d4rken** [comment]
Fynn's PR was merged into 2.1, so fixed "soon" :grin:, thanks!

**Comment by MikeMcC399** [comment]
@dsarkar 
Do you want to add the [Fix 2.1 label](https://github.com/corona-warn-app/cwa-app-android/labels/Fix%202.1) to this issue?

**Comment by heinezen** [comment]
@MikeMcC399 Done
