### ISSUE TITLE
Exception when deselecting person or location after selecting the note-field, Ursache 9002

### ISSUE THREAD

**Issue by DerVogel2020** [corona-warn-app/cwa-app-android#2703]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy A5 2017
- Android version: 8
- App version: 1.15.1

## Describe the bug

See title

## Steps to reproduce the issue

1. Open locations or persons
2. Select an existing item
3. Klick in the notes field, so the cursor is shown
4. Deselect the person or location, selected in step 2

## Expected behaviour

No exception

## Additional context

Ursache:
java.lang.NullPointerException: Parameter specified as non-null is null: method com.google.zxing.client.android.R$color.toContactDiaryPersonEncounter, parameter $this$toContactDiaryPersonEncounter
	at com.google.zxing.client.android.R$color.toContactDiaryPersonEncounter(Unknown Source:2)
	at de.rki.coronawarnapp.contactdiary.storage.repo.DefaultContactDiaryRepository$updatePersonEncounter$2.invokeSuspend(DefaultContactDiaryRepository.kt:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:13)

Screenshot
![Screenshot_20210328-201457_Corona-Warn.jpg](https://user-images.githubusercontent.com/65366950/112762881-655f2280-9002-11eb-9412-06878eae995d.jpg)

---
Internal Tracking ID: [EXPOSUREAPP-6003](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6003)

**Comment by vaubaehn** [comment]
Can reproduce the issue, but I either need to enter text in the note field and delete it before deselecting person/location, or after setting the focus into the text field I need to tap 'del' on keyboard and then deselect person/location.

**Comment by dsarkar** [comment]
@DerVogel2020 @vaubaehn Many thanks for reporting and analysing.

---
Internal Tracking ID: [EXPOSUREAPP-6003](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6003)

**Comment by ralfgehrer** [comment]
Should be fixed by this PR: https://github.com/corona-warn-app/cwa-app-android/pull/2715

**Comment by dsarkar** [comment]
@DerVogel2020 Thanks for contributing.
