### ISSUE TITLE
1.15.2 release?

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#2725]
## Avoid duplicates
* [X] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Question is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Question has not already been asked in another issue

## Your Question

My phone automatically updated overnight to CWA Android 1.15.2.

Will you follow up with a 1.15.2 release shown on https://github.com/corona-warn-app/cwa-app-android/releases ?

The latest shown there is currently [v1.15.2-RC0](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.15.2-RC0).

**Comment by harambasicluka** [comment]
@MikeMcC399 good catch! thanks :)

Here it is: https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.15.2
