### ISSUE TITLE
Current state of community-developed alternatives

### ISSUE THREAD

**Issue by fynngodau** [corona-warn-app/cwa-app-android#2837]
This issue aims to supersede #75 as discussed in https://github.com/corona-warn-app/cwa-website/pull/1070#discussion_r613822148 by providing clear and concise up-to-date information regarding alternative CWA-compatible clients developed by the community. I opened this issue in the Android repository because it discusses solutions specifically for the Android platform.

### End-user applications

This list displays installable Android client software. 

| Name | Repository | Website | License | Status | Additional information | Maintainers |
|---|---|---|---|---|---|---|
| Corona Contact Tracing Germany | https://codeberg.org/corona-contact-tracing-germany/cwa-android/ | | [Apache 2.0][cctg-license] | Active | Depends on microG EN libraries | @Bubu, @fynngodau |
||||||
| CoraLibre | https://github.com/CoraLibre/CoraLibre-android | https://coralibre.de | [Apache 2.0][coralibre-license] | [Not production-ready, discontinued][coralibre-discontinued] | Depends on `CoraLibre-android-sdk`, discussed in #75 | [cosee GmbH][coralibre-cosee] |

### Libraries

Here you can find all libraries that are aiming to provide a replacement to the proprietary Google EN library.

| Name | Repository | Website | License | Status | Additional information | Maintainers |
|---|---|---|---|---|---|---|
| microG | https://github.com/microg/GmsCore/ | https://microg.org | [Apache 2.0][microg-license] | Active | Modules `play-services-nearby-core` and `play-services-nearby-core-ui` contain the relevant code | @mar-v-in
|||||||
| `CoraLibre-android-sdk` | https://github.com/CoraLibre/CoraLibre-android-sdk | | [MPL 2.0][coralibre-sdk-license] | [Discontinued][coralibre-sdk-discontinued] | | [cosee GmbH][coralibre-cosee]

Please contact me (through this issue or otherwise) if any implementation that I am not aware of is missing here or if anything else is incorrect.

[cctg-license]: https://codeberg.org/corona-contact-tracing-germany/cwa-android/src/branch/main/LICENSE
[coralibre-license]: https://github.com/CoraLibre/CoraLibre-android/blob/master/LICENSE
[coralibre-discontinued]: https://github.com/CoraLibre/CoraLibre-android#note-on-development-status
[microg-license]: https://github.com/microg/GmsCore/blob/master/LICENSE
[coralibre-sdk-license]: https://github.com/CoraLibre/CoraLibre-android-sdk/blob/master/LICENSE
[coralibre-sdk-discontinued]: https://github.com/CoraLibre/CoraLibre-android-sdk#note-on-development-status
[coralibre-cosee]: https://ww2.cosee.biz/references/Enact.html

----
Internal Tracking ID: [EXPOSUREAPP-6497](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6497)

**Comment by heinezen** [comment]
@fynngodau 

Thank you. This is now tracked as [EXPOSUREAPP-6497](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6497)

----
Corona-Warn-App Open Source Team
