### ISSUE TITLE
Inaccuracy in privacy policy

### ISSUE THREAD

**Issue by fynngodau** [corona-warn-app/cwa-app-android#2841]
The latest (2.0) privacy policy states in number 5 (What data is processed), letter e (Entries in the contact journal):

https://github.com/corona-warn-app/cwa-app-android/blob/bae7bf74418c42fa45e79dc487262b16eb9662f9/Corona-Warn-App/src/main/assets/privacy_en.html#L305-L307

In German:

https://github.com/corona-warn-app/cwa-app-android/blob/bae7bf74418c42fa45e79dc487262b16eb9662f9/Corona-Warn-App/src/main/assets/privacy_de.html#L317-L319

However, the data is not actually encrypted on Android since the use of the Android keystore was abandoned in version 1.15.x.

I advice you to fix the privacy policy by removing the term "in encrypted form" and "verschlüsselt", respectively.

---

Additionally, I found this small typo in the German privacy policy in number 6 (Wofür werden Ihre Daten verarbeitet), letter a (Risiko-Ermittlung), second paragraph, second sentence:

https://github.com/corona-warn-app/cwa-app-android/blob/bae7bf74418c42fa45e79dc487262b16eb9662f9/Corona-Warn-App/src/main/assets/privacy_de.html#L459-L460

There's two dots there. **This has been fixed for version 2.1.**

---

Lastly, the wrong type of headline (`h3` vs. `h2`) is used here:

https://github.com/corona-warn-app/cwa-app-android/blob/bae7bf74418c42fa45e79dc487262b16eb9662f9/Corona-Warn-App/src/main/assets/privacy_en.html#L422-L425

**All headlines of this order are now `h3` since version 2.2.**

---

Best regards and good nerves during release.

----
Internal Tracking-ID: [EXPOSUREAPP-6664](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6664)

**Comment by heinezen** [comment]
@fynngodau Thank you for the hints. Tracked as [EXPOSUREAPP-6664](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6664).

----
Corona-Warn-App Open Source Team

**Comment by fynngodau** [comment]
The double-dots issue (`..`) was fixed with the latest update. The other issues are still there.

**Comment by heinezen** [comment]
@fynngodau 

All issues should be fixed by now. 

Regarding the encryption remark:

> However, the data is not actually encrypted on Android since the use of the Android keystore was abandoned in version 1.15.x.

The data is still encrypted in the app's private application storage on Android. The application sandbox is encrypted by the OS and can be only accessed by the system (or the app, respectively). 

----
Corona-Warn-App Open Source Team
