### ISSUE TITLE
QR code for event checkin is scrolled partially ouf of view with long description

### ISSUE THREAD

**Issue by Bubu** [corona-warn-app/cwa-app-android#2854]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Nexus 6X
- Android version: 8.1
- App version: 2.0.2

## Describe the bug

This is the default view when opening the organizer qr code view for an event with a long description:

![image](https://user-images.githubusercontent.com/105185/115065622-a30ee700-9eee-11eb-92c1-beb88d9943b4.png)

The problem here is that it's far from obvious that the QR code is scrolled partially out of view, making checkins impossible without scrolling down. Note: the problem isn't necessarily that you need to scroll but mainly that you'd normally only notice this after people tried checking in unsuccessfully.

## Steps to reproduce the issue

Pretty much the same as #2852

## Expected behaviour

QR code is fully visible as soon as you open the screen. Or it's at least *very* obvious that you'll have to bring the full QR code in view as an explicit step.

## Additional context

---
Internal Tracking ID: [EXPOSUREAPP-6541](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6541)

**Comment by MTRNord** [comment]
As a user myself I would instead of scrolling expect a touch action here which makes the thing full screen kinda like it does in messengers with images. That would also make it have enough spaces and in my opinion is the most obvious action I would expect.

**Comment by dsarkar** [comment]
@Bubu Many thanks. Internal Tracking ID: [EXPOSUREAPP-6541](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6541)

---
Corona-Warn-App Open Source Team

**Comment by fynngodau** [comment]
The code could be smaller so that it is fully displayed at all times, and then be enlarged when scrolled.

**Comment by dsarkar** [comment]
PR https://github.com/corona-warn-app/cwa-app-android/pull/3110

**Comment by heinezen** [comment]
Dear community,

This has been fixed in CWA release 2.3.

----
Corona-Warn-App Open Source Team
