### ISSUE TITLE
Some buttons have a cut-off shadow

### ISSUE THREAD

**Issue by fynngodau** [corona-warn-app/cwa-app-android#2856]
### Describe the bug

Throughout the app, some buttons have a shadow that is cut off. Here's a list of all those that I could find.

In the screenshots, I am holding down the button so you can notice the cut-off shadow better.

Screenshot | Description | Screenshot | Description
---|:---|---|:--
![Screenshot_1618679790](https://user-images.githubusercontent.com/16943720/115121149-6e179880-9fb1-11eb-8af5-84f2e4ac06df.png) | Create QR code card has a cut-off shadow |  ![Screenshot_1618679750](https://user-images.githubusercontent.com/16943720/115121116-54765100-9fb1-11eb-8940-6a1f1864f203.png) | Activate exposure logging button has a cut-off shadow
![Screenshot_1619261256](https://user-images.githubusercontent.com/16943720/115956115-47021f00-a4fb-11eb-96b1-039c48cedc60.png) | The Your Risk Status fragment's Activate Exposure Logging button and Update button are also affected. | ![Screenshot_1618680352](https://user-images.githubusercontent.com/16943720/115121394-d0bd6400-9fb2-11eb-8537-844ce7058976.png) | "Change prioritized background activity" card's button has a cut-off shadow
![Screenshot_1618679650](https://user-images.githubusercontent.com/16943720/115121087-1a0cb400-9fb1-11eb-82ae-70786d1cdf60.png) | All buttons in the error report screen are cut off at the sides. Best seen at the bottom-most one, which is also cut off downwards.
| | I don't have a screenshot for this, but I think the Turn On Exposure Check button on the reenable risk card is also affected. | | The same applies to the positive test result card.

### Steps to reproduce the issue

View one of the buttons. Touching and holding them increases their elevation, so you can see that the shadow is cut off.

### Expected behavior

The shadow should not be cut off. For example, these shadows are *not* cut off:

![Screenshot_1618680600](https://user-images.githubusercontent.com/16943720/115121497-5d682200-9fb3-11eb-95dc-49e1d2e5554b.png) | ![Screenshot_1618680623](https://user-images.githubusercontent.com/16943720/115121500-60631280-9fb3-11eb-8f80-d9a9c30ca149.png) | ![Screenshot_1618680606](https://user-images.githubusercontent.com/16943720/115121501-622cd600-9fb3-11eb-968b-e372a9a077fd.png)
---|---|---

### Possible Fix

This happens when the parent view has a padding. All child views are then cut off to this padding.

This does not happen if the parent's padding is removed and all children having a margin instead. In this case, the children are able to draw their shadows into the space around them correctly.

However, a better solution, which I had almost forgotten, is to apply `clipToPadding="false"` to each parent which should not clip its children in this way.

(Had I known how simple this is, I would have opened a PR much sooner. …)

### Additional context

Most buttons' shadows are not cut off, which is very satisfying.

---
Internal Tracking ID: [EXPOSUREAPP-6543](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6543)

**Comment by dsarkar** [comment]
@fynngodau Thanks. Internal Tracking ID: [EXPOSUREAPP-6543](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6543)

---
Corona-Warn-App Open Source Team

**Comment by fynngodau** [comment]
Closing in favor of #2988 due to https://github.com/corona-warn-app/cwa-app-android/pull/2942#issuecomment-826707455.
