### ISSUE TITLE
Create QR code card's image not clipped to padding

### ISSUE THREAD

**Issue by fynngodau** [corona-warn-app/cwa-app-android#2857]
### Describe the bug

The button's location in the QR code card does not depend on the image. This means that depending on screen width and font size, the background image can appear behind the button (in contrast to all other cards).

![image](https://user-images.githubusercontent.com/16943720/115121672-4a098680-9fb4-11eb-8e36-7d66d5794547.png)

### Steps to reproduce the issue

Set Font Size to small in the settings.

### Expected behaviour

There card should behave like the card that opens the dispatcher screen.

---
Internal Tracking ID: [EXPOSUREAPP-6544](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6544)

**Comment by dsarkar** [comment]
@fynngodau Thanks again. Internal Tracking ID: [EXPOSUREAPP-6544](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6544) 

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
@fynngodau FYI PR: https://github.com/corona-warn-app/cwa-app-android/pull/2910

**Comment by fynngodau** [comment]
Closing because 2.1 has been released and rolled out.
