### ISSUE TITLE
Add app shortcut to QR code scanner

### ISSUE THREAD

**Issue by fynngodau** [corona-warn-app/cwa-app-android#2858]
### Current Implementation

There is a shortcut to the contact journal as suggested in corona-warn-app/cwa-wishlist#295.

### Suggested Enhancement

There should also be a shortcut to the QR code scanner for the new check-in functionality.

### Expected Benefits

Users could open the scanner with lightning speed :zap:

### Additional context

A CCTG user asked for this here: https://chaos.social/@Kurt/106082036510232318

---
Internal Tracking ID: [EXPOSUREAPP-5414](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5414) Android
Internal Tracking ID: [EXPOSUREAPP-5593](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5593) iOS
PR iOS corona-warn-app/cwa-app-ios#2235
PR iOS https://github.com/corona-warn-app/cwa-app-ios/pull/4238

**Comment by dsarkar** [comment]
@fynngodau @Ein-Tim 
Thanks for proposal and comments.

Story exists already and is high priority Internal Tracking ID: [EXPOSUREAPP-5414](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5414) Android

iOS is completed:  Internal Tracking ID: [EXPOSUREAPP-5593](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5593) 
PR https://github.com/corona-warn-app/cwa-app-ios/pull/2235

Enjoy Sunday!
---
Corona-Warn-App Open Source Team

**Comment by dodekaphilist** [comment]
Is there someone working on this? Now that it's getting fall, there will probably be much more usage of this feature and a quick way to check-in would help tremendously 🙏

**Comment by fynngodau** [comment]
The new global scanner FAB requires less steps than previously, which is a good advancement for this issue.

**Comment by dsarkar** [comment]
@fynngodau FYI https://github.com/corona-warn-app/cwa-app-ios/pull/4238

**Comment by MikeMcC399** [comment]
@dsarkar 
- The PR #4685 which you mentioned is in draft status for version 2.22. I can't see any sign of the functionality in the CWA Android 2.20.3 release.

**Comment by MikeMcC399** [comment]
@dsarkar 

Would you like to remove the https://github.com/corona-warn-app/cwa-app-android/labels/Fix%202%2E20 label, as this functionality apparently was not added to CWA 2.20.

**Comment by MikeMcC399** [comment]
@dsarkar 
- PR #4685 is in draft status for version 2.23 and it is in the [2.23 milestone list](https://github.com/corona-warn-app/cwa-app-android/milestone/59). I guess we will have to wait and see whether it is going to be included. There are still some open tasks in the PR description.

**Comment by dsarkar** [comment]
@MikeMcC399 following short cuts should be available with R 2.23 
<img width="184" alt="image" src="https://user-images.githubusercontent.com/1409741/171439819-885d6f5b-e997-4b92-b24a-28955d333174.png">
