### ISSUE TITLE
Button overlapping

### ISSUE THREAD

**Issue by DerVogel2020** [corona-warn-app/cwa-app-android#2896]
## Technical details

- Device name: Samsung Galaxy A5 (2017)
- Android version: 8
- App version: 2.0.3

## Describe the bug

Button Jetzt auschecken overlaps the Duration counter.

## Steps to reproduce the issue

Check in to any location.
Click Check-in at the bottom of the main screen.
See attached Screen.

## Additional context

![Screenshot_20210421-164905_Corona-Warn.jpg](https://user-images.githubusercontent.com/65366950/115574387-dc19d380-a2c1-11eb-9168-2abcefd0ee38.jpg)

**Comment by MikeMcC399** [comment]
@DerVogel2020 

Could you check if this is the same as https://github.com/corona-warn-app/cwa-app-android/issues/2849?

You might have missed it, since the issue I'm referring to has been closed, although it will not be fixed until the 2.1 release.

**Comment by DerVogel2020** [comment]
Yes, it's the same.
