### ISSUE TITLE
What happens if someone meets 2 different people in different situations and both come to have covid?

### ISSUE THREAD

**Issue by pepintos** [corona-warn-app/cwa-app-android#2904]
## Avoid duplicates
* [ ] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Question is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Question has not already been asked in another issue

## Your Question

If someone has 2 different risks (or more) from different people, does the app sum the risks or just gets the higher?

And what if they have 2 different riks from the same person?

For example, 2 days ago I was with a person and I have middle risk because of that. But yesterday I was with another person because of whom I would get low risk. Do I have high risk or medium?

* Source File:
* Line(s):
* Question:

**Comment by Ein-Tim** [comment]
Hey @pepintos 👋

The FAQ entry https://www.coronawarn.app/en/faq/#encounter_19_calc says: 
"Ultimately, this means that several 'green' encounters (time windows) can result in a red status in total." 
This should answer your questions, or?
