### ISSUE TITLE
[Google Play Store] Outdated CWA App!?

### ISSUE THREAD

**Issue by Jo-Achim** [corona-warn-app/cwa-app-android#2911]
Hello,

version 2.03 of the CWA (Android) is currently released. Correct?

The CWA screenshots in the Google Play Store have been updated (to version 2.x), but according to further information, only version 1.15.2 is offered for download; see the compilation of the screenshots.

Also - maybe because of that (?) - there is apparently no CWA update from version 1.15.2 to 2.03 available.

![Outdated CWA in Google Play Store](https://user-images.githubusercontent.com/21124877/115711136-74bc5c00-a373-11eb-98c3-0db6ee5e20ec.jpg)

Best regards, Joachim.

Android 10 with Android security update: November 5st, 2020;
Google Play-Systemupdate: March, 1st, 2021.
GigaSet GS4, Build: E940-2795-00_10.0_V08_20201123
CWA version: 1.15.2
ENF: 18211213000
NetGuard Pro 2.295
Norton 360, v.5.7.0.5665

**Comment by MikeMcC399** [comment]
@Jo-Achim 

https://www.coronawarn.app/en/blog/2021-04-21-corona-warn-app-version-2-0/ says:

"Deutsche Telekom and SAP’s project team have released version 2.0 of the Corona-Warn-App, which will be available to users **within the next 48 hours**. "

The Google Play Store only shows the latest version to a user when your account has been scheduled for inclusion. You can see from the announcement text, which mentions 48 hours, that this must be a staged rollout, like many of the previous ones.

It is a bit frustrating to have to wait. In the past it has taken 48 hours (and a bit more) to get to me. For version 2.0.3 my account was scheduled a lot earlier. I don't like the way that Google does this, but unfortunately that is the way it is and there is no way for an individual to override it. You have to wait.

**Comment by Ein-Tim** [comment]
CWA version 2.0 is in staged rollout. It'll appear to all users in the next 24h.

**Comment by Jo-Achim** [comment]
> It is a bit frustrating to have to wait. In the past it has taken 48 hours (and a bit more) to get to me. For version 2.0.3 my account was scheduled a lot earlier. I don't like the way that Google does this, but unfortunately that is the way it is and there is no way for an individual to override it. You have to wait.

Thank you. 
Then everything is fine. I was aware that the update would take a while. The only thing that amazes me is that the old version is still available for download in the Google Play Store.

In contrast to the Apple App Store, where version 2.0.3 is available for download.

**Comment by fynngodau** [comment]
> In contrast to the Apple App Store, where version 2.0.3 is available for download.

Apple App Store is also doing a staged rollout, however it works differently, allowing users to manually choose to get the latest version by checking the app store's page. This may be a better system as it avoids confusion as you have experienced.

**Comment by MikeMcC399** [comment]
> The only thing that amazes me is that the old version is still available for download in the Google Play Store.

Given that Google has chosen to strictly queue up users for staged rollouts, with no manual jumping the queue, it would be bad for them to remove the previous version, because if somebody, who has not got to the front of the queue, wanted to install or re-install the app, they would not be able to do that.

**Comment by heinezen** [comment]
@Jo-Achim The rollout should be finished by now. You can close the issue later today or tomorrow. By then, everyone's Play store update should have gotten through.

----
Corona-Warn-App Open Source Team

**Comment by Jo-Achim** [comment]
Yes, I received the update today at noon.
