### ISSUE TITLE
UI/Display error with text at location enabling screen

### ISSUE THREAD

**Issue by rugk** [corona-warn-app/cwa-app-android#2940]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Fairphone 3 (FP3)
- Android version: 10 (Stock ROM)
- App version: 2.0.3

## Describe the bug
When the location services are disabled in Android system settings, the screen that asks the user to enable that has a display error with overlapping text.

## Steps to reproduce the issue

0. Disable location services completely.
1. On the home page click on “location services disabled” (”Standortdienste deaktiviert”)
2. You get to a screen titled with “risk assessment” (”Risikoermittlung”).
3. Up until the menu for other countries it looks all right. And further down the static explanation text (”Um zu erkennen…”) also looks ok. Only the big interactive part/prompt with the button for the user is absolutely distorted.

The texts “Ermittlungszeitraum aktivieren” (”enable detection period”) and “Standortverwendung erlauben” (”enable location access”) seem to overlay each other:

![promptGpsReenable](https://user-images.githubusercontent.com/11966684/115925905-36fa2900-a482-11eb-9e3a-3350b2dfdd4a.png)

BTW, the button works though. :)

(English translations are my guess, I have not double-checked whether these are

## Expected behaviour

If I had to guess, I’d say this has been introduced [with the latest update](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.0.3).
Using the app in German language.
Screen size [is according to Wikipedia](https://en.wikipedia.org/wiki/Fairphone_3):
5.65 in (144 mm)
1080×2160 px FullHD+
427 ppi

Reproducible in dark and light mode.

---
Also reproducible with CCTG v2.0.3: https://codeberg.org/corona-contact-tracing-germany/cwa-android/issues/120 (Same bug text copied to both issues, only images changed.)

---
Internal Tracking ID: [EXPOSUREAPP-6711](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6711)

**Comment by MikeMcC399** [comment]
This issue is also reproducible on:

Device name: Samsung Galaxy A5 (2017)
Android version: 8.0.0
App version: 1.15.2 and 2.0.3

It is a regression from version 1.14.3. In this version the display shown by tapping on "LOCATION SERVICES DEACTIVATED" is correct (with no text overwriting other text).

After updating by hand to 1.15.2 the "Period Logged" and "Allow location access" views on the Exposure Logging screen overwrite each other. This problem is unchanged by then updating to 2.0.3.

**Comment by dsarkar** [comment]
@rugk @MikeMcC399 Thanks for reporting. Internal Tracking ID: [EXPOSUREAPP-6711](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6711)

---
Corona-Warn-App Open Source Team

**Comment by Deepunkt** [comment]
This issue happens as well in version 2.0.4 with Fairphone 3 in Android 10.

**Comment by MikeMcC399** [comment]
@Deepunkt 
> This issue happens as well in version 2.0.4 with Fairphone 3 in Android 10.

2.0.4 is just a minor bug-fix on top of 2.0.3 to fix issue https://github.com/corona-warn-app/cwa-app-android/issues/2909 scanning QR codes, so I would not expect this issue (#2940) to have been fixed yet.

**Comment by fynngodau** [comment]
I opened a PR for this issue: #2947.

**Comment by vaubaehn** [comment]
There is a similar issue with the RAT information screen. I will create an issue as soon as I find some time.

**Comment by MikeMcC399** [comment]
@rugk

I checked with

Device name: Samsung Galaxy A5 (2017)
Android version: 8.0.0
App version: 2.2.1

that the issue is fixed. It would be good to hear back from you when you have the opportunity to check with the new version on your device as well.

**Comment by rugk** [comment]
Tested with v2.1⅕ (same device as in OP etc.): _Not_ fixed.

Gonna update… :upside_down_face:

**Comment by heinezen** [comment]
@rugk 

Can you confirm the fix in CWA release 2.2.? Thanks

----
Corona-Warn-App Open Source Team

**Comment by rugk** [comment]
I can confirm it’s fixed in v2.3.4. :slightly_smiling_face:
