### ISSUE TITLE
Could not check for risk assessment (related to same-device double checkin?)

### ISSUE THREAD

**Issue by rugk** [corona-warn-app/cwa-app-android#2941]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Fairphone 3 (FP3)
- Android version: 10 (Stock ROM)
- App version: 2.0.3

## Describe the bug

Yesterday (2021-04-22) at 22:15 (the message says), it could not seem to detect the changes.
I retried 23:12 as I did the screenshot and it still did not work.

Later on, also CCTG (installed on the same device and also active, which should [as per their FAQ](https://codeberg.org/corona-contact-tracing-germany/cwa-android/src/branch/main/FAQ_de.md#ich-habe-vorher-cwa-benutzt-m%C3%B6chte-jetzt-aber-zu-cctg-wechseln-was-muss-ich-tun) not be a problem) shows the same warning.

Now as I create this issue, both apps got back to normal apparently, but I still wanted to report it.
Maybe you can make sure it’s not just a server issue (was it temporarily down yesterday? And if so, is there a public status page/monitoring)?

## Steps to reproduce the issue

Yesterday go to the home screen.

I found this:
![grafik](https://user-images.githubusercontent.com/11966684/115926865-d0760a80-a483-11eb-93a2-6c8e008b7fd0.png)

> **Risikoüberprüfung fehlgeschlagen**
> Der Abgleich der Zufalls-IDs mit dem Server ist fehlgeschlagen. Sie können den Abgleich manuell neu starten.

However, it could be related to the new checkin functionality, as I did try that just before:
* I updated CWA. I played around with it (and maybe I already created the place, I don’t really remember the exact order). In any case, I also updated CCTG to v2.0.3.
* I created a _place_ (”another place”) with CWA.
* I checked in to that place with CWA after some time. Expiration: 2h.
* I checked in with the same device with CCTG some time later by scanning the QR code. Expiration: 2h.

I’m not sure when that issue happened, but it could well be after these 2h approximately.

My device has Google Play Services v21.12.13 (120408-367530751) and thus does use microg’s internal implementation of CCTG. As such [according to the CCTG FAQ](https://codeberg.org/corona-contact-tracing-germany/cwa-android/src/branch/main/FAQ_de.md#ich-habe-vorher-cwa-benutzt-m%C3%B6chte-jetzt-aber-zu-cctg-wechseln-was-muss-ich-tun) both apps use a different data set.

## Expected behaviour

No error. Never… :wink: 

## Possible Fix

In the future, maybe there should also be a button to report this problem to the devs (as you apparently do with crashes – I never had one, but I read about that) or at least show me the log/more debug information.

I never saw this issue before.

---

Also reported to CCTG here: https://codeberg.org/corona-contact-tracing-germany/cwa-android/issues/121

**Comment by Ein-Tim** [comment]
Was there an exception thrown after clicking on "ERNEUT STARTEN"? 

I didn't saw any problems on my iOS devices in this time, in fact my phone even did a risk check (although this could have used cached data). 

> In the future, maybe there should also be a button to report this problem to the devs (as you apparently do with crashes – I never had one, but I read about that) or at least show me the log/more debug information.

Version 2.2 will add the log upload to the app. 

> And if so, is there a public status page/monitoring)?

There is no public status page, but there's an enhancement request: https://github.com/corona-warn-app/cwa-wishlist/issues/134

**Comment by rugk** [comment]
> Was there an exception thrown after clicking on "ERNEUT STARTEN"?

No, nothing changed, IIRC. I.e. I still saw that message,

**Comment by fynngodau** [comment]
This sounds a bit similar to the issue where the call to compare the key package times out: https://github.com/corona-warn-app/cwa-app-android/issues/2880

**Comment by vaubaehn** [comment]
> This sounds a bit similar to the issue where the call to compare the key package times out: #2880

The issue here seems not directly related to #2880, see https://github.com/corona-warn-app/cwa-app-android/issues/2880#issuecomment-827754932

**Comment by vaubaehn** [comment]
@rugk 
I could replicate the issue last night with CWA 2.1.2. Pulling app to foreground, error card appeared. Pressing "Erneut starten" triggered CWA's downloading task ("Daten werden heruntergeladen") for one second, following "Prüfung läuft" for one second. After that, the error card stayed like it was before, and I could press "erneut starten" 6 or 7 times, until the green risk card came back.
Did you experience something similar lately, or is your app still working fine?

**Comment by DerVogel2020** [comment]
I experienced the same on Android 8, App 2.1.2.

I closed all apps and started CWA again to get rid of that message.

**Comment by rugk** [comment]
No, I did not actually encountered that issue again until I reported it.

**Comment by Spammed** [comment]
I have had this message appear since this morning. "Erneut Prüfen" or restart does not help.
What information would be helpful?
What can I do?
(Release 2.14.1 on SM-G99F, Android-6.01)

**Comment by Ein-Tim** [comment]
@Spammed

Do you have an active internet connection?

And, as this issue is about check ins, do you have a check in?

**Comment by Spammed** [comment]
@Tim
Yes, I have an internet connection and
No, I do not have check-ins
(The warning app has been in use for a long time, but I have no check-ins)

**Comment by Spammed** [comment]
"Aktualisiert: Heute, 06:26 Uhr"
So my problem probably arose between 6:26 and about 8:15

**Comment by Ein-Tim** [comment]
@Spammed 

Did you restart your device?

**Comment by Spammed** [comment]
I may have been mistaken about what the message meant. 
Anyway, my problem persists but now "Aktualisiert: Heute, 12:07" is reported.

**Comment by Spammed** [comment]
@Tim
Yes i've restarted my system (around 8:15am)

**Comment by Spammed** [comment]
The problem disappeared by itself and at an unknown time (everything is now working again as it should).

**Comment by rugk** [comment]
I also heard this appared once the server was down for some time see #4442

**Comment by rugk** [comment]
Anyway I guess this issue is not reproducible here, at least my original one, so I'll close this one here.

**Comment by Spammed** [comment]
The problem is, since a few days, back!
"Risiko-Überprüfungs fehlgeschlagen". 

"Erneut starten" failed but e.g. 'Aktualisiert: Heute 8:13'.

**Comment by Ein-Tim** [comment]
@Spammed

Please open a new issue or see https://github.com/corona-warn-app/cwa-app-android/issues/3093
