### ISSUE TITLE
Move Trace Location strings to event_registration_strings

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-android#2948]
## Avoid duplicates
* [X] This enhancement request has not already been raised before
* [X] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [X] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation
The most strings for the event registration are stored in https://github.com/corona-warn-app/cwa-app-android/blob/release/2.0.x/Corona-Warn-App/src/main/res/values-de/event_registration_strings.xml (German as example, also applies to all other languages). 
But there are also some strings that are stored in https://github.com/corona-warn-app/cwa-app-android/blob/release/2.0.x/Corona-Warn-App/src/main/res/values-de/strings.xml (see f.e. [Lines 1948 - 1994](
https://github.com/corona-warn-app/cwa-app-android/blob/de207de84a795dad78229913458509a3d5da8ae9/Corona-Warn-App/src/main/res/values-de/strings.xml#L1948-1994) in German strings).

## Suggested Enhancement
Move all event-registration related strings into `event_registration_strings.xml`.

## Expected Benefits
Cleaner code - things are easier to find.

----
Internal Tracking-ID: [EXPOSUREAPP-6993](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6993)

**Comment by heinezen** [comment]
@Ein-Tim 

Thank you. We have raised this internally: [EXPOSUREAPP-6993](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6993)

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@mtwalli

Hey Mohamed, maybe you could check this issue. If the team does not want to do that, please let us know and close this issue.

**Comment by Ein-Tim** [comment]
- PR #5541 addresses this issue

**Comment by mtwalli** [comment]
@Ein-Tim  I think this issue can be closed now, since this was mainly a dev task and it does not affect end users no need to wait until 2.27 is shipped . do you agree? You can refer to https://github.com/corona-warn-app/cwa-app-android/pull/5564 to see that other languages have updated too
