### ISSUE TITLE
More detailed error message when scanning qr code which is invalid for checkin

### ISSUE THREAD

**Issue by DerVogel2020** [corona-warn-app/cwa-app-android#2949]
## Avoid duplicates
* [x] This enhancement request has not already been raised before
* [x] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [x] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation
In https://github.com/corona-warn-app/cwa-app-android/pull/2919 the error message became human friendly for issue #2909.

## Suggested Enhancement
Explain that the qr code itself may be valid, but not for check in.
When I scan a valid qr code as a test-qr-code, there is a very detailed message, what can be wrong with the qr code.

## Expected Benefits
The user may have a valid qr code for a test (or something else) and will get an explanation what might be wrong with this qr code. He won't become confused.

----
Internal Tracking-ID: [EXPOSUREAPP-6761](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6761)

**Comment by Ein-Tim** [comment]
> The user may have a valid qr code for a test [...]

This has also been mentioned in https://github.com/corona-warn-app/cwa-app-android/issues/2909#issuecomment-824789923. 

The same issue applies to iOS, so I'd suggest to move it to either the wishlist or the documentation repository, depending on wether this is seen as a bug or as an enhancement request.

**Comment by DerVogel2020** [comment]
In https://github.com/corona-warn-app/cwa-app-android/issues/2909#issuecomment-825035414 you can see, that iOS users get a message, which says that the qr code cannot be used for check in (but might be valid itself).

**Comment by Ein-Tim** [comment]
@DerVogel2020 

Could you share a screenshot of the error message under Android?

**Comment by DerVogel2020** [comment]
> @DerVogel2020 
> 
> Could you share a screenshot of the error message under Android? 

No, not now. Linked to the strings.xml of the commit.

**Comment by Ein-Tim** [comment]
@DerVogel2020 

I agree that iOS is better than Android in this case. 
Let's keep this issue here and we can open a new one in the wishlist reg. the scanning of a test QR-Code with the event-registration scanner.

**Comment by DerVogel2020** [comment]
Here is now a screenshot of CWA 2.0.4
![Screenshot_20210425-191835_Corona-Warn.jpg](https://user-images.githubusercontent.com/65366950/116002675-26b98980-a5fb-11eb-8359-a35cf6fe4397.jpg)

**Comment by heinezen** [comment]
@DerVogel2020 

Thanks for the report. We have brought this to the attention of the development team.

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
Hey everyone,

We cannot do much about this unfortunately. There are many combinations of QR-code details which are not valid, but it's not really possible for CWA to give more reasonable info. Not within realistic effort at least.

Therefore, we will close this issue.

----
Corona-Warn-App Open Source Team

**Comment by DerVogel2020** [comment]
> but it's not really possible for CWA to give more reasonable info

OK. But what about the message from the iOS repo? Just created #3046.

**Comment by heinezen** [comment]
@DerVogel2020 Ah if it's about aligning the iOS and Android messages then it's probably fine. Sorry for the misunderstanding.

I will clear up the misunderstanding internally. Looks like your PR will be approved. Thanks again for contributing :)

----
Corona-Warn-App Open Source Team

**Comment by DerVogel2020** [comment]
@harambasicluka you may add the Fix2.2-tag.

**Comment by DerVogel2020** [comment]
Fixed in 2.2.1.
