### ISSUE TITLE
Different animations for different onboarding info screens

### ISSUE THREAD

**Issue by fynngodau** [corona-warn-app/cwa-app-android#2952]
### Describe the bug

The Check-In onboarding screen has an animation while the Contact Journal onboarding does not.

https://user-images.githubusercontent.com/16943720/115985591-cb60aa80-a5ac-11eb-9fad-fab905de90e2.mp4

### Steps to reproduce the issue

Open Check-In screen and Contact Journal screen on fresh installations.

### Possible Fix

Add animation to Contact Journal onboarding screen. #2954

----
Internal Tracking-ID: [EXPOSUREAPP-6763](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6763)

**Comment by fynngodau** [comment]
I'll close this issue since it is fixed by my PR #2954 for 2.1.

**Comment by heinezen** [comment]
@fynngodau Please do not close issues before the associated release has been published to avoid duplicates and let other people give feedback :)

However, release 2.1 has started to roll out just now, so we'll leave the issue closed.

----
Corona-Warn-App Open Source Team
