### ISSUE TITLE
Overlapping Text

### ISSUE THREAD

**Issue by ShowMeYourSkil** [corona-warn-app/cwa-app-android#2956]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Samsung a20e 
- Android version: 10
- App version: 2.0.4 (last version)

## Describe the bug

The information texts "Ermittlungszeitraum erlauben" and "Standort erweiterung erlauben" in the Corona warn app on risk determination overlap.

## Expected behaviour

The texts should be placed one below the other so that they can be read.

## Possible Fix

I suspect an error in your style file.

## Additional context

I have a screenshot for you to see the problem

![Screenshot_20210426-084356_Corona-Warn](https://user-images.githubusercontent.com/39274150/116041650-bdbf2980-a66d-11eb-837b-82cd1f61a594.jpg)

**Comment by Ein-Tim** [comment]
This has already been reported in #2940. A PR fixing this is #2947.

**Comment by ShowMeYourSkil** [comment]
> This has already been reported in #2940. A PR fixing this is #2947.

Oh thanks, i must have overlocked that. I will then close this issue again.

**Comment by Ein-Tim** [comment]
@ShowMeYourSkil 

Thank you anyways for reporting!

**Comment by dsarkar** [comment]
@ShowMeYourSkil In any thanks for contributing here. Best wishes, DS

---
Corona-Warn-App Open Source Team
