### ISSUE TITLE
Usage of sqlite

### ISSUE THREAD

**Issue by egandro** [corona-warn-app/cwa-app-android#30]
Please describe in great details why you decided to use sqlite.

According to the documentation and the expected data a simple json file can be used.

The CCC demonstrated in very simple steps, that SQLite can be used via SQL Statements to execute code.

Why add this level of possible vulnerability to the software - when there is really no need to use a database?

Please also describe in great details - why a specific version "2.0.x" was chosen by the gradle build files.

**Comment by tkowark** [comment]
Dear @egandro , thanks for all your activity and pointing out potential issues. 

Can we kindly ask you to just state your questions without always demanding "great details"? These additions always take away from the well-intended original purpose.

**Comment by egandro** [comment]
The vulnerability of specific Sqlite versions where shown at specific locations. CCC and Black Hat.

**Comment by tkowark** [comment]
The team uses Room (and consequently SQLIte) for the purpose described [here](https://github.com/corona-warn-app/cwa-app-android/blob/43412bdabe128dc674ec8a9ef8baa80d37292a3a/docs/architecture-overview.md#room).

As stated in the [Readme](https://github.com/corona-warn-app/cwa-app-android/blob/43412bdabe128dc674ec8a9ef8baa80d37292a3a/README.md#known-issues) this also might be subject to change.

If you know about vulnerabilities of the [concrete sqlite version used in this project](https://github.com/corona-warn-app/cwa-app-android/blob/43412bdabe128dc674ec8a9ef8baa80d37292a3a/Corona-Warn-App/build.gradle#L199), please let us [know](https://github.com/corona-warn-app/cwa-app-android/security/policy)!
