### ISSUE TITLE
Capitalize German locations

### ISSUE THREAD

**Issue by DerVogel2020** [corona-warn-app/cwa-app-android#3037]
## Technical details

- App version: 2.0.5

## Describe the bug

First letters are not writen as majuscile.

## Steps to reproduce the issue

1. Go to 'Startseite'
2. Click on 'QR-Code erstellen'
3. Click on '+ QR-Code'
4. Look at "öffentliches Gebäude", "anderer Ort", "private Feier" and "anderes Event"

## Expected behaviour

Capitalize the items from point 4.
https://github.com/corona-warn-app/cwa-wishlist/issues/491

**Comment by DerVogel2020** [comment]
Closed, because #3038 won't be merged for convention reasons.

**Comment by dsarkar** [comment]
@DerVogel2020 Thanks anyway for contributing here! Best, DS 

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
This has been implemented via #3177.

**Comment by DerVogel2020** [comment]
Then I reopen it and it should get the "Fix 2.3"-label.

**Comment by dsarkar** [comment]
@DerVogel2020 Thanks!
