### ISSUE TITLE
[Questions] Contact Diary: Wrong 'Time of period' (person) & Missing Start-Time to Time-Duration (place)...

### ISSUE THREAD

**Issue by Jo-Achim** [corona-warn-app/cwa-app-android#3039]
Hello, 

(I don't want to rule out not having understood something or not being up to date.) 

I have two questions about "Contact Diary":

**1. [Person]:** As far as I know, the Risk-Status-Calculation was changed from 15 minutes... to actually to 9 minutes (see: https://www.coronawarn.app/de/blog/2021-04-16-corona-warn-app-risk-calculation-further-improved/).
But if I edit / add a new person in / to my "Contact Diary" then I have two "15 Minutes" options! Is that correct? Or should the time span be (actually) 9 minutes?
To do (e.g.): Open CWA, select "Diary", select a date, select 'person', select 'a person' or '+ person'... 

![Screenshot_20210501-111219_Person](https://user-images.githubusercontent.com/21124877/116778412-04e45a80-aa72-11eb-8497-7c703898c287.jpg)

------------------

**2. [Place / Location]:** When I edit / define a new location, I can determine how long I've been in that location. But wouldn't the - missing - 'start of time', to which the duration refers, be just as important!?
To do (e.g.): Open CWA, select "Diary", select a date, select 'place', select 'a place' or '+ place'... 

![Screenshot_20210501-111447_Location](https://user-images.githubusercontent.com/21124877/116778638-6bb64380-aa73-11eb-8f6e-1ac79cac348c.jpg)

_Possible solution:_
(With a duration (as in the example of 23:45 [hh: mm]) the total time could be on the selected day (of the entry); but theoretically only 15 minutes on this day and 23 hours and 30 minutes on the following day.)

![Screenshot_20210501-111447_Location_2](https://user-images.githubusercontent.com/21124877/116778644-71ac2480-aa73-11eb-9087-da8fcf9fe47f.jpg)

Best regards, Joachim.

Android 10 with Android security update: April 1st, 2021
Nokia 7.1, Build: 00WW_4_15C_SP11
CWA version: 2.0.5
ENF: 18211515000
NetGuard Pro 2.295

**Comment by heinezen** [comment]
Hey @Jo-Achim 

Sorry for answering so late. This got buried by the new releases.

> But if I edit / add a new person in / to my "Contact Diary" then I have two "15 Minutes" options! Is that correct? Or should the time span be (actually) 9 minutes?

This is still correct. The time in the contact jourrnal relies more on user judgement, so that users can guess whether they were exposed long enough. So it doesn't have to be the same time as the app's exposure time threshold, it just has to be close.

> When I edit / define a new location, I can determine how long I've been in that location. But wouldn't the - missing - 'start of time', to which the duration refers, be just as important!?

Not necessarily. The duration is the most important variable, since that always determines how long someone is potentially exposed. The start time is not as useful as the *when* doesn't have as much impact on your risk as the *how long*. Currently, if you stay at a place for 2 consecutive days, you are supposed to make 2 entries for the 2 days.

----
Corona-Warn-App Open Source Team

**Comment by Jo-Achim** [comment]
@heinezen,

Thanks for the answers.

I'm not sure ... because in my opinion there are several aspects that suggest a change / addition.

**1. [Person]:**
If the calculation basis for a possible infection has now been changed to 9 minutes, then for good reason. And therefore it would be more correct to store this reason accordingly in the time grid - instead of suggesting that a time span of less than 15 minutes would be safe ’.

**2. [Place / Location]:**
Many people keep a 'real' calendar from which the respective 'contacts', 'places' etc. can be easily taken; in this respect, the calendar in the CWA would actually be superfluous.
As a reminder for those who tend not to keep a 'real' calendar, of course, in addition to the duration of the stay, the start of the stay is also included (I would never come up with the idea of ​​defining a duration without defining its start ;-)). After all, it might make a difference whether I was at a certain place on dd.MM.yyyy from 0:15 a.m. or at 11:30 p.m.

But, as I said, my questions should rather be an indication that something could be missing.
I also realize that there are more important things about the CWA at the moment - for example the subject of vaccination certificates / vaccination card.

In this sense, Joachim.

**Comment by mtwalli** [comment]
Person entry now show 10 min instead of 15 min. For places start time is not required
