### ISSUE TITLE
Navigation bar color is white in dark mode

### ISSUE THREAD

**Issue by binarynoise** [corona-warn-app/cwa-app-android#3041]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy S10e
- Android version: 10
- App version: 2.0.5

## Describe the bug

When dark/night mode is enabled, the navigation bar is still white. 

## Steps to reproduce the issue

1. Enable dark mode on your device, if not done already. 
2. Start the CWA
3. Look at your navigation bar 

![Screenshot_20210501-084430_Corona-Warn.jpg](https://user-images.githubusercontent.com/50302352/116774042-f5f1ae00-aa59-11eb-9465-301faaf55006.jpg)

## Expected behaviour

The navigation bar follows the theme and turns black. 

## Possible Fix

Include these items to the base styles in `values/styles.xml` 

```
<item name="android:navigationBarColor">?android:attr/colorBackground</item> 		
<item name="android:windowLightNavigationBar" tools:targetApi="o_mr1">@bool/isLightTheme</item>
```

The `isLightTheme` should be true by default overwritten to false in `values-night` 

----
Internal Tracking-ID: [EXPOSUREAPP-6991](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6991)

**Comment by heinezen** [comment]
Hello @binarynoise ,

Thanks for reporting the issue. We have notified the development team about this by creating a ticket in our internal Jira system [EXPOSUREAPP-6991](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6991). We will see if we can apply your fix and report back.

Alternatively, you can also create a PR with the fix and the dev team will review it.

----
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
FYI https://github.com/corona-warn-app/cwa-app-android/pull/3078

**Comment by binarynoise** [comment]
Thank you!

**Comment by MikeMcC399** [comment]
@binarynoise 
Did you have the opportunity to check whether this issue is fixed for you? It is flagged as fixed in version 2.3 and in the meantime version 2.5.1 has been released, so it ought to be fixed.

I tried to reproduce the original issue, but it seems that it is device specific and I don't have your device (Samsung Galaxy S10e). So it would be good if you could check in the same environment where you originally saw the issue.

**Comment by binarynoise** [comment]
@MikeMcC399 
Yes, the issue has been fixed for me, I'm very happy. I actually forgot to close this issue :sweat_smile:. I thought the PR would automatically close this when it gets merged.
Looks great now (same as the screenshots in the PR) and has also been mirrored to CCTG.

**Comment by dsarkar** [comment]
@binarynoise and everybody, thanks for the contributions. 


---
Corona-Warn-App Open Source Team
