### ISSUE TITLE
Text overlapping in risk detection ("Risiko-Ermittlung") with disabled Bluetooth and GPS

### ISSUE THREAD

**Issue by crusherd** [corona-warn-app/cwa-app-android#3060]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Sony Xperia XZ Premium
- Android version: 9
- App version: 2.1.2

## Describe the bug

When a user opens the risk detection ("Risiko-Ermittlung") with disabled Bluetooth and GPS the explanation texts are overlapping each other. This also happens, if the user is already on the risk detection ("Risiko-Ermittlung") and then disables Bluetooth and GPS. Please see pictures below.

## Steps to reproduce the issue

A user opens the in-app settings ("Einstellungen") via the burger menu on the top right and goes to risk detection ("Risiko-Ermittlung") with disabled Bluetooth and GPS. The user will see below picture:

![Screenshot_20210503-234505](https://user-images.githubusercontent.com/1702712/116967562-dacdab00-acb2-11eb-8d2e-7e22ec096253.png)

Same picture with enabled layout borders from developer options:
![Screenshot_20210504-082211](https://user-images.githubusercontent.com/1702712/116967626-08b2ef80-acb3-11eb-8c2c-a9ab91f5e359.png)

## Expected behaviour

Text is clearly readable without overlapping.

## Possible Fix

Set layout borders for location permission request ("Standort-Verwendung erlauben") to be above or below detection period ("Ermittlungszeitraum").

**Comment by MikeMcC399** [comment]
@crusherd 
I'm sorry you went to the effort of posting an excellent issue report, however this has already been reported in https://github.com/corona-warn-app/cwa-app-android/issues/2940, so yours is a duplicate.

**Comment by crusherd** [comment]
oh sorry, I went through the issue list (not deep enough, though), but could not find it and thought, it was not present yet.
Closing the ticket now.

**Comment by dsarkar** [comment]
@crusherd @MikeMcC399 Thanks for reporting and pointing out duplicate.

---
Corona-Warn-App Open Source Team
