### ISSUE TITLE
typo: Zufall-IDs

### ISSUE THREAD

**Issue by DerVogel2020** [corona-warn-app/cwa-app-android#3062]
## Technical details

- App version: 2.1.2

## Describe the bug

Yesterday I recceived a strange looking error message. I found out, that everywhere else, except in the sentence "Der Abgleich der Zufall-IDs mit dem Server ist fehlgeschlagen. Sie können den Abgleich manuell neu starten." the Zufalls-IDs are translated "Zufalls-IDs".

## Steps to reproduce the issue

Don't know. I got the error message yesterday, may be because of a failing internet connection.

## Expected behaviour

Use "Zufalls-IDs" instead.

---
Internal Tracking ID: [EXPOSUREAPP-7089](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7089)

**Comment by dsarkar** [comment]
@DerVogel2020 Thanks for the report. Internal Tracking ID: [EXPOSUREAPP-7089](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7089)

---
Corona-Warn-App Open Source Team

**Comment by DerVogel2020** [comment]
Fixed in 2.2.1.
