### ISSUE TITLE
Multiple entries in contact diary

### ISSUE THREAD

**Issue by lpralle** [corona-warn-app/cwa-app-android#3071]
## Technical details

- Device name: Motorola one
- Android version: 10
- App version: 2.1.2
- 

## Describe the bug
For one specific date, no tickmarks appear in the contact diary when a person is selected. Multiple attempts to add the tickmark results in multiple additions of the person to the contact list. See screenshot attached.
Issue was first mentioned in user feedback on Google play store, Apr 24th,  #2021.
![Screenshot_20210504-165410](https://user-images.githubusercontent.com/83657705/117025690-6a974780-acfb-11eb-987c-83d1452baf82.png)

**Comment by MikeMcC399** [comment]
@lpralle 

I don't know why the Contact Journal allows creating duplicate entries. It should probably be enhanced to constrain Person and Place entries to be unique. I thought this had been mentioned before, but I can't find any other reports on this subject. If anybody knows of a related request, please respond. The original release 1.10 which first introduced the Contact Journal also allowed duplicate contacts to be created.

You will probably want to delete the duplicate contact journal entries and you can find some general instructions on using the Contact Journal on https://www.coronawarn.app/de/blog/2020-12-28-corona-warn-app-version-1-10/ (German).

From Tagebuch (Kontakt-Tagebuch) tap the three-dot icon and select Personen bearbeiten. You can then use ALLE ENTFERNEN or tap the pencil icon on an individual entry then tap on the wastebasket icon to delete each unnecessary entry.

**Comment by Ein-Tim** [comment]
We have:

- https://github.com/corona-warn-app/cwa-documentation/issues/521 as a bug report and
- https://github.com/corona-warn-app/cwa-wishlist/issues/318 as an enhancement request

**Comment by MikeMcC399** [comment]
@Ein-Tim 
My memory was better than my searching skills today! Thanks very much for providing the links!

**Comment by MikeMcC399** [comment]
@lpralle 
Was the explanation clear? Did you manage to clean up the extra contact journal entries?
