### ISSUE TITLE
typos: Ok, Okay and Check-In in german translation

### ISSUE THREAD

**Issue by DerVogel2020** [corona-warn-app/cwa-app-android#3120]
## Describe the bug

I found a few more typos: Ok and Okay and Check-In in german translations.

## Expected behaviour

For conistency reasons it should be "OK" and "Check-in", like everywhere else.

## Possible Fix

Just change the texts.

---
Internal Tracking ID: [EXPOSUREAPP-7148](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7148)

**Comment by dsarkar** [comment]
@DerVogel2020 Thanks.

**Comment by dsarkar** [comment]
@DerVogel2020 Also here thanks for contributing!
