### ISSUE TITLE
Truncated text output (Data Sharing information)

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#3131]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Google Pixel 3a emulator
- Android version: 11
- App version: 2.1.2 (and 2.2.1-RC0 and 2.3.0-RC0)
Display font size and Display size both set to Default

## Describe the bug

In Share Data, "Detailed Information about This Data Processing and Data Protection Risks in the U.S. and Other Third Countries", "Detailed Information about Data Sharing" the string `onboarding_ppa_more_info_rki_data_point_5_text`

<string name="onboarding_ppa_more_info_rki_data_point_5_text">"Information about whether you received a positive or negative test result through the app."</string>

is displayed truncated in the app. Depending on the display size and settings, a truncated string such as "Information about whether you received a pos" may be output.

## Steps to reproduce the issue

1. Open CWA
2. Tap three-dot icon
3. Tap Settings > Share Data
4. Scroll down to bottom "Detailed Information about This Data Processing and Data Protection Risks in the U.S. and Other Third Countries" and tap on this string.
5. In "Detailed Information about Data Sharing" scroll down to section "To this end, the RKI collects the following data:" and further to sub-section "If you have retrieved a test result through the app:"
6. The next bullet point is displayed as "Information about whether you received a pos"

![Truncated 2 1](https://user-images.githubusercontent.com/66998419/117662958-6b6b2600-b1a0-11eb-8c3f-628eef31b44f.jpg)

## Expected behaviour

The full text of string `onboarding_ppa_more_info_rki_data_point_5_text` "Information about whether you received a positive or negative test result through the app." should be displayed.

## Possible Fix

Modify layout of Corona-Warn-App/src/main/res/layout/fragment_ppa_more_info.xml
TextView android:id="@+id/rki_data_point_5_text"

https://github.com/corona-warn-app/cwa-app-android/blob/595ab630dfad5ac1e29021c084c400054193a498/Corona-Warn-App/src/main/res/layout/fragment_ppa_more_info.xml#L324-L329

---
Internal Tracking ID: [EXPOSUREAPP-7202](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7202)

**Comment by dsarkar** [comment]
@MikeMcC399 
Thanks. Internal Tracking ID: [EXPOSUREAPP-7202](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7202)

**Comment by MikeMcC399** [comment]
PR #3136 opened.

If accepted, this should be fixed in version 2.3.

**Comment by MikeMcC399** [comment]
I verified the merged fix #3136 in the branch [release/2.3.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.3.x) and I plan to recheck after version 2.3 is released.

**Comment by MikeMcC399** [comment]
The paragraph "Information about whether you received a positive or negative test result through the app." is displayed completely in the released 2.3.2 app.

![image](https://user-images.githubusercontent.com/66998419/121526301-888e5100-c9f9-11eb-9e39-857fb4f21742.png)

Confirmed fixed, therefore closing this issue.
