### ISSUE TITLE
typos en: Check-In in english translation

### ISSUE THREAD

**Issue by DerVogel2020** [corona-warn-app/cwa-app-android#3132]
## Describe the bug

Sometimes Check-In is used instead of Check-in.
See also #3120 .

## Expected behaviour

For conistency and correctness reasons it should be "Check-in", like everywhere else.

## Possible Fix

Just change the texts.

**Comment by dsarkar** [comment]
FYI PR iOS https://github.com/corona-warn-app/cwa-app-ios/pull/2674
