### ISSUE TITLE
Missing arrow icon on creating rapid-test profile

### ISSUE THREAD

**Issue by kechtel** [corona-warn-app/cwa-app-android#3162]
## Avoid duplicates
* [x] This enhancement request has not already been raised before
* [x] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [x] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

The screen to register tests is composed of multiple profile cards that redirect to subsequent screens. To indicate the subsequent screens, arrow icons are used on all cards, except on the card to create the RAT profile.

![20210512_170631](https://user-images.githubusercontent.com/20854650/118007719-add16600-b34c-11eb-99b8-f29487bf4f0f.jpg)

## Suggested Enhancement

Add the arrow icon to the card for the creation of the RAT profile. See #3161

## Expected Benefits

¯\_(ツ)_/¯

----
Internal Tracking-ID: [EXPOSUREAPP-7269](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7269)

**Comment by Ein-Tim** [comment]
Please see https://github.com/corona-warn-app/cwa-app-android/pull/3161#issuecomment-839916617:

> Thanks for the PR , but the arrow is not missing. it is done as per design specs

In this case I recommend to either transfer this issue to the https://github.com/corona-warn-app/cwa-wishlist repository or opening a new issue there since the same applies to iOS.

**Comment by kechtel** [comment]
@Ein-Tim in the iOS version of the app, the arrow seems to be present: https://github.com/corona-warn-app/cwa-app-ios/pull/2559

**Comment by Ein-Tim** [comment]
@kechtel True, sorry, this was my mistake. In that case I recommend to [open a new enhancement request](https://github.com/corona-warn-app/cwa-app-android/issues/new?assignees=&labels=enhancement&template=02_enhancement.md) here.

Sorry again for the mistake. 😕

**Comment by kechtel** [comment]
> @kechtel True, sorry, this was my mistake. In that case I recommend to [open a new enhancement request](https://github.com/corona-warn-app/cwa-app-android/issues/new?assignees=&labels=enhancement&template=02_enhancement.md) here.
> 
> Sorry again for the mistake. 😕

@Ein-Tim No worries, I appreciate your suggestion! Not sure whether I got you right, but I thought as well that this issue should be seen as an enhancement, so I used the enhancement template when creating the issue. If there is any required information missing, feel free to let me know!

**Comment by MikeMcC399** [comment]
@kechtel 

I noticed that the screenshots on https://www.coronawarn.app/en/screenshots/ don't show version 2.2 where there should be the tile to (Create) Rapid Test Profile, so I opened https://github.com/corona-warn-app/cwa-website/issues/1257 for that point.

It would be good to have an official reference to the implementation on Android and iOS for version 2.2. and it seems there is an inconsistency regarding the arrow. I wonder if that inconsistency goes back to inconsistent design specs between the two operating systems? If so, the designers might like to explain why they chose to have different specs.

**Comment by Ein-Tim** [comment]
@kechtel No, there is nothing missing, everything is alright! 
Sorry seems like, I'm a bit lost today, thought this was a bug report.
I'll probably just go to bed now... 😴😅

**Comment by Ein-Tim** [comment]
@MikeMcC399 

>It would be good to have an official reference to the implementation on Android and iOS for version 2.2. and it seems there is an inconsistency regarding the arrow. 

Although this is not an official reference, here's a screenshot from version 2.2.1 on my iPhone 6s:

<img src="https://user-images.githubusercontent.com/67682506/118020478-67830380-b35a-11eb-9f71-a973321a9f71.PNG" width="300">
<img src="https://user-images.githubusercontent.com/67682506/118020489-69e55d80-b35a-11eb-8af0-e8145b443423.PNG" width="300">
