### ISSUE TITLE
Notification: "Google Play-Dienste aktualisieren: Corona-Warn wird nur ausgeführt, wenn du die Google Play-Dienste aktualisierst"

### ISSUE THREAD

**Issue by Diapolo** [corona-warn-app/cwa-app-android#3163]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Fairphone 2
- Android version: 10, LineageOS + microG version 0.2.19.211515
- App version: 2.2.1

## Describe the bug

I just tried to do the necessary steps for "Testergebnis abrufen" to learn any new workflows (I do this after each CWA update). When clicking on "Einverstanden" I now get an error message reading "Google Play-Dienste aktualisieren: Corona-Warn wird nur ausgeführt, wenn du die Google Play-Dienste aktualisierst". This was not the case with app version 2.1.2.

## Steps to reproduce the issue

![CWA1](https://user-images.githubusercontent.com/1419649/118021652-c1d09400-b35b-11eb-826e-b59f61ea12cf.png)
![CWA2](https://user-images.githubusercontent.com/1419649/118021666-c5641b00-b35b-11eb-901f-34574682dcf4.png)
![CWA3](https://user-images.githubusercontent.com/1419649/118021671-c72dde80-b35b-11eb-83f0-da1cf9fe8926.png)

## Expected behaviour

Open the QR-Code reader.

## Possible Fix

When tapping the error message the QR-Code reader opens. Not sure if registering a test would work, as I have none available to scan.

## Additional context

I'm using LineageOS for microG, microG version 0.2.19.211515 (https://github.com/microg/GmsCore/releases/tag/v0.2.19.211515)

For reference, this is the issue in the microG repo:
https://github.com/microg/GmsCore/issues/1469

----
Internal Tracking-ID: [EXPOSUREAPP-7264](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7264)

**Comment by fynngodau** [comment]
The cause might be the new and improved error handling: https://github.com/corona-warn-app/cwa-app-android/pull/2995

It might be helpful to have a look at the logs here.

**Comment by vaubaehn** [comment]
This reminds me on https://github.com/corona-warn-app/cwa-app-android/issues/75#issuecomment-810922200 : similar configuration, slightly different context.

**Comment by heinezen** [comment]
Hey @Diapolo ,

Can you make an error report while reproducing the issue ([see here for a How-To](https://www.coronawarn.app/de/blog/2021-05-12-corona-warn-app-version-2-2/)) and tell us the report ID? This will help us to investigate the problem quicker.

As the others have pointed out, having microG might be the cause of the problem here. We'll se what we can do about it.

----
Corona-Warn-App Open Source Team

**Comment by thomasaugsten** [comment]
It looks like the issue is your microG version is not supporting the preConsent authorization introduced by Google 2 month ago. A not available Google method will show this popup

**Comment by Diapolo** [comment]
> Hey @Diapolo ,
> 
> Can you make an error report while reproducing the issue ([see here for a How-To](https://www.coronawarn.app/de/blog/2021-05-12-corona-warn-app-version-2-2/)) and tell us the report ID? This will help us to investigate the problem quicker.
> 
> As the others have pointed out, having microG might be the cause of the problem here. We'll se what we can do about it. Tracking ID: [EXPOSUREAPP-7264](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7264)
> 
> Corona-Warn-App Open Source Team

I'd love to send an error report, but it seems you also require SafetyNet for sending error reports? I'm getting the message: "Etwas ist schiefgelaufen. Die Befragung kann aktuell nicht aufgerufen werden. Bitte versuchen Sie es später noch mal (Fehlercode ATTESTATION_FAILED)."

My phone is rooted and so doesn't pass SafetyNet...

**Comment by heinezen** [comment]
@Diapolo Ah I didn't think about that. Thanks for trying anyway. It does not work on microG currently, although we are thinking about alternative solutions: https://github.com/corona-warn-app/cwa-wishlist/issues/356

----
Corona-Warn-App Open Source Team

**Comment by fynngodau** [comment]
Just to make everyone else here aware of this too, @Diapolo has opened a corresponding issue for microG and @mar-v-in added a change that fixes this behavior in https://github.com/microg/GmsCore/issues/1469#issuecomment-840514152.

**Comment by Diapolo** [comment]
@heinezen Would be really nice to not enforce SafetyNet or implement alternative solutions :). At least the commit mentioned by @fynngodau fixed this issue here. So closing the ticket.
