### ISSUE TITLE
Multiple test?

### ISSUE THREAD

**Issue by Traciges** [corona-warn-app/cwa-app-android#3169]
Is it normal, that I can register multiple test?
![image](https://user-images.githubusercontent.com/37974148/118112890-e3765d80-b3e5-11eb-83bb-3aa2829f9c66.png)

**Comment by thomasaugsten** [comment]
You can register 1 PCR and 1 rapid test

**Comment by Traciges** [comment]
Alright

**Comment by heinezen** [comment]
Hey @Traciges,

Since your question seems to be answered, we'll close this issue now. 

----
Corona-Warn-App Open Source Team
