### ISSUE TITLE
Incompatibility warning after updating to version 2.2.1

### ISSUE THREAD

**Issue by Lu9Bro** [corona-warn-app/cwa-app-android#3170]
Yesterday, I updated to version 2.2.1. Since then I get an incompatibility warning 
![Screenshot_2021-05-12-21-15-53 crop2](https://user-images.githubusercontent.com/84101747/118177332-d92e8080-b432-11eb-9b42-2d087842f308.png)

With previous CWA versions, I did not get such a warning.

Is this warning function new and correct?
{Then older CWA versions might not have worked correct on my device, either, but this has never been detected.}
or 
Did this warning function exist the same way also in previous versions? 
{Then the behavior of the CWA 2.2.1 must have changed somehow such that it does not work any longer on my device.}

Turning Bluetooth off and on does not help.

**Technical details**
Device name: Samsung Galaxy S5 mini
Android version: 6.0.1
CWA version 2.2.1
ENF 18211515000
"Priorisierte Hintergrundaktivität" ON
16 GB total memory
1.13 GB free memory

---
Internal Tracking ID: [EXPOSUREAPP-7283](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7283)

**Comment by thomasaugsten** [comment]
This warning is new in 2.2.
Can you please provide the exact model number and Android security patch level

**Comment by Lu9Bro** [comment]
Model number SM-G800F
Android security patch level  "1. August 2017"

**Comment by thomasaugsten** [comment]
Build Date?

Thu, 26 Nov 2020

**Comment by Lu9Bro** [comment]
Build number
MMB29K.G800FXXU1CTK1

Where can I find the "build date", or is the number sufficient for you?

**Comment by thomasaugsten** [comment]
This is sufficient

**Comment by MikeMcC399** [comment]
- The icon on the top right of the error message links to the FAQ article https://www.coronawarn.app/de/faq/#incompatibility_warning.

- There is a discussion about the new compatibility-checking feature, introduced with the CWA Android 2.2.1 release, in the issue https://github.com/corona-warn-app/cwa-app-android/issues/688.

- The Samsung Galaxy S5 mini has been involved in other issues with Exposure Notifications previously. See https://github.com/corona-warn-app/cwa-app-android/issues/1817.

**Comment by fynngodau** [comment]
This list (last updated 2018) shows your device as incapable of Bluetooth peripheral mode: https://altbeacon.github.io/android-beacon-library/beacon-transmitter-devices.html

**Comment by MikeMcC399** [comment]
#688 points to the app [nRF Connect for Mobile](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp) which can be used to check if a device supports Bluetooth Low Energy, Peripheral Mode. (Thanks to @gizmo21!) Access menu item "Device information", then check Bluetooth Low Energy section.

**Comment by Lu9Bro** [comment]
Now I've performed this test, and as you expected, my device does not support BLE Peripheral Mode:
![Screenshot_2021-05-16-16-32-47 crop](https://user-images.githubusercontent.com/84101747/118401395-cfd92a00-b665-11eb-9880-5ddd2de90565.png)

So there is nothing to be done (except using a different device).

The reason why I suspected a bug initially (and posting it here) was that this "incompatibility warning" was new since CWA version 2.2.1.
Now I learned that CWA has never been fully compatible with my device  -  just I didn't know it before.

I don't  know if many other CWA users are affected and astonished as well.

From my point of view, this issue is solved. Thanks to all for your answers.

**Comment by fynngodau** [comment]
Maybe we should include the hint that this is new in the FAQ entry. I believe @Ein-Tim asked for this but we didn’t include it so far.

**Comment by MikeMcC399** [comment]
@fynngodau 
You are right that @Ein-Tim asked in https://github.com/corona-warn-app/cwa-website/pull/1211 whether the information should be included into the FAQ about when the functionality was introduced. At the time I was confused by the comment https://github.com/corona-warn-app/cwa-website/pull/1211#issuecomment-834141855 "This won't be delivered with CWA 2.2: corona-warn-app/cwa-app-android#3101 (comment)" as I didn't read it carefully. I thought the complete check was being delayed, not the enhancement to the check.

Let me open an issue for this, and then we can check about who can best implement it.

**Comment by MikeMcC399** [comment]
The FAQ articles

**[Google/Android] A card on my Start Screen is notifying me that my device is not or only partially compatible. What does this mean?**
https://www.coronawarn.app/en/faq/#incompatibility_warning

**[Google/Android] Auf meinem Hauptbildschirm werde ich gewarnt, dass mein Gerät nicht oder nicht vollständig kompatibel ist. Was bedeutet das?**
https://www.coronawarn.app/de/faq/#incompatibility_warning

have now been updated to include the information that the Bluetooth compatibility checks were added in version 2.2 of the app (currently the latest version).

**Comment by heinezen** [comment]
We have updated the FAQ entries for incompatibility warnings. There are now separate articles for each type of warning with a less ambiguous explanation. See https://github.com/corona-warn-app/cwa-website/pull/1291

----
Corona-Warn-App Open Source Team
