### ISSUE TITLE
Timestamp of shared error report uses UTC

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#3183]
## Avoid duplicates

* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] This report is for Android. iOS is not affected.
* [X] Bug is not already reported in another issue
Related to issue "CWA log filename contains characters reserved under Windows" https://github.com/corona-warn-app/cwa-app-android/issues/3158.

## Technical details

- Device name: Google Pixel 3a emulator
- Android version: 11
- App version: 2.2.1

## Describe the bug

The default filename used in "SHARE AND CONTINUE" of error reporting includes a UTC timestamp.

This is confusing because the name of a submitted error report uses the local time, which in Germany is never the same as UTC.

## Steps to reproduce the issue

1. In CWA Start Screen, tap three-dot icon
2. Tap "App Information", tap "Error Reports"
3. Tap "START"
4. Wait until "Recording Active" is shown
5. Tap "SHARE AND CONTINUE", note the name of the zip file
6. Select "Drive", tap "Save"
7. Tap "SEND ERROR REPORT"
8. Tap "AGREE AND SEND"
9. Tap ID History, note the time shown

---
Share filename shows UTC (currently CEST - 2 hours)
![image](https://user-images.githubusercontent.com/66998419/118394006-68f64980-b642-11eb-84b5-1709d5596970.png)

---
Submitted timestamp shows local time
![image](https://user-images.githubusercontent.com/66998419/118394112-fc2f7f00-b642-11eb-8179-b8ae83d7cf3a.png)

## Expected behavior

The filename for "SHARE AND CONTINUE" should be formed using the local time, not UTC time.

## Possible Fix

Convert UTC time to local time before forming the filename to be used in "SHARE AND CONTINUE".

----
Internal Tracking-ID: [EXPOSUREAPP-7298](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7298)

**Comment by Ein-Tim** [comment]
There is no such timestamp in the filename under iOS, it's just called `cwa-log`.

**Comment by heinezen** [comment]
@MikeMcC399 Thank you. We have reported it as [EXPOSUREAPP-7298](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7298)

----
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
FYI PR https://github.com/corona-warn-app/cwa-app-android/pull/3202

**Comment by MikeMcC399** [comment]
Thanks to @PhilippNowak96 for implementing #3202!

As mentioned in the original submission, the issue #3158 (Windows reserved character in log filename) is related - Internal Tracking-ID: [EXPOSUREAPP-7266](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7266) - and at this time remains open.

**Comment by PhilippNowak96** [comment]
@MikeMcC399 oh I didn't saw this one. I will have a look into it tomorrow I think

**Comment by MikeMcC399** [comment]
Confirmed fixed in the released version 2.3.2.

An example filename is now CWA Log 2021-06-10 14_24_58.681.zip where 14_24_58.681 represents the hours, minutes, seconds and decimal seconds, separated by the "_" character instead of ":".
