### ISSUE TITLE
Allow app installation without Bluetooth Low Energy from Google App Store

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#3186]
## Avoid duplicates
* [X] This enhancement request has not already been raised before
* [X] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

CWA Android targets distribution through the Google Play Store only (see https://www.coronawarn.app/en/faq/#apk) and if a user goes directly to https://play.google.com/store/apps/details?id=de.rki.coronawarnapp from a device without Bluetooth Low Energy (BLE) support, they will see the following:

![image](https://user-images.githubusercontent.com/66998419/118452609-9e5c6f00-b6f6-11eb-8f0b-bf2b545092a0.png)

The Android manifest declares `android.hardware.bluetooth_le` to be required, which causes the app to be blocked on Google Play Store if `bluetooth_le` is not available on the device.

https://github.com/corona-warn-app/cwa-app-android/blob/9ec222a431340917834e831cc60edd14fa062d27/Corona-Warn-App/src/main/AndroidManifest.xml#L9-L11

## Suggested Enhancement

Change Android manifest to set `bluetooth_le` to not required:

```
    <uses-feature
        android:name="android.hardware.bluetooth_le"
        android:required="false" />
```

According to https://developer.android.com/guide/topics/manifest/uses-feature-element 

"When you declare android:required="false" for a feature, it means that the application prefers to use the feature if present on the device, but that it is designed to function without the specified feature, if necessary."

## Expected Benefits

Although early versions of the app relied heavily on the availability of Bluetooth Low Energy (BLE) on the device, many functional enhancement to the app, which have been added over the lifetime of the app, do **not** need BLE to work:

- PCR Test registration
- Rapid Antigen Test registration
- Rapid Antigen Test profile
- Contact Journal
- Statistics
- Event QR code creation
- Event check-in
- Exposure notification from event

Removing the hard restriction for BLE would allow users of devices without BLE support to be able to use the other functions of the app. Older devices are the ones which may fall into this category. Also in conjunction with this enhancement request, the enhancement for support of Android 5.0 (Lollipop) https://github.com/corona-warn-app/cwa-app-android/issues/1799, could benefit from the relaxation of the hard BLE requirement in currently released versions.

Starting from the Android V2.2.1 release, the app itself performs Bluetooth Low Energy compatibility checks and informs the user about any issues. It is therefore no longer necessary to block installation if BLE support is missing on the device. The user will always be informed if any functionality is not available if the app is installed on a device without full or partial BLE support.

Also, according to https://developer.android.com/guide/topics/connectivity/bluetooth-le 

"Devices running Android 4.3 (API level 18) and higher have built-in platform support for Bluetooth Low Energy (BLE) in the central role."

CWA currently supports devices from API 23 onwards. If https://github.com/corona-warn-app/cwa-app-android/issues/1799 is implemented, then API 21 would be supported. Both API levels are later than API 18 quoted above.

---
Related to 
- Internal Tracking-ID: [EXPOSUREAPP-6359](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6359).
- Internal Tracking-ID: [EXPOSUREAPP-6594](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6594).

**Comment by Ein-Tim** [comment]
Related issues:
- https://github.com/corona-warn-app/cwa-wishlist/issues/443
- https://github.com/corona-warn-app/cwa-wishlist/issues/464

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Thanks for the links! I will add Internal Tracking-ID: EXPOSUREAPP-6594 to the main description.

**Comment by MikeMcC399** [comment]
On reflection, and based on https://developer.android.com/guide/topics/connectivity/bluetooth-le

"Devices running Android 4.3 (API level 18) and higher have built-in platform support for Bluetooth Low Energy (BLE) in the central role."

it probably has no benefit to implement this request on its own. So I defer to the other two requests which @Ein-Tim listed.

If there are any good arguments for keeping this as a separate request, let me know and I will re-open.
