### ISSUE TITLE
Invalid QR-Code dialog: Back button and cancel button have different actions

### ISSUE THREAD

**Issue by PhilippNowak96** [corona-warn-app/cwa-app-android#3203]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Pixel 4 XL
- Android version: Android 11 (API 30)
- App version: 2.2.1

## Describe the bug

When I try to scan a QR-Code of a recent test and it fails because the provider is not supported yet, the appearing dialog has different actions when using the cancel button of the dialog vs. using the back button of the device.
The dialog cancel button closes the scanning overlay so that the consent screen appears. The back button simply dismisses the dialog so the scanning overlay stays. The problem is that there is no possibility to scan the same code again or another code because scanning is disabled. So it makes no sense to stay on that screen.

## Steps to reproduce the issue

1. Scan an invalid QR-Code
2. Press cancel in the appearing dialog -> See the result
3. Do step 1 again
4. Press the device back button -> See the result

## Expected behaviour

The back button should have the same behaviour like the dialog cancel button.

## Possible Fix

I could imagine 3 different solutions. Which one fits best needs to be discussed.

- Adjust back button functionality
- Set cancelable of dialog to false
- Enable scanning after dialog was dismissed again

---
Internal Tracking ID: [EXPOSUREAPP-7341](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7341)

**Comment by dsarkar** [comment]
@PhilippNowak96 Thanks. Internal Tracking ID: [EXPOSUREAPP-7341](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7341)

---
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
Dear community,

This was fixed in CWA release 2.3 (PR: https://github.com/corona-warn-app/cwa-app-android/pull/3253)

----
Corona-Warn-App Open Source Team
