### ISSUE TITLE
Create Rapid Test Profile - Postal Code - Input field issues

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#3213]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Pixel 3a emulator
- Android version: 11
- App version: 2.2.1

## Describe the bug

The input field "Postal Code" for the Rapid Test Profile 
- does not display the prompt for the name of the field completely
- does not display the complete postal code during data entry

## Steps to reproduce the issue

Locale is English (United Kingdom)
Font size and display size: Default

1. In CWA Start Screen, tap "NEXT STEPS"
2. Tap Create Rapid Test Profile
3. View form and note that the field for Postal Code entry shows truncated text e.g. "Postal..."
4. Start entering the fictive 5-digit post code "12345"
5. Note that only three complete digits are shown during the data entry. Also the prompt now only shows "Pos...". If the font size is set to largest, then only "Po..." is shown.

![image](https://user-images.githubusercontent.com/66998419/118680931-74db3a80-b7ff-11eb-935c-dacc7b36e0e6.png)

![image](https://user-images.githubusercontent.com/66998419/118681404-d7343b00-b7ff-11eb-8ef1-b95d49ca2e45.png)

## Expected behavior

- With locale set to English (United Kingdom) the text "Postal Code" in Create Rapid Test Profile should be completely readable.
- During data entry of the Postal Code (assumed to be 5 digits for Germany) the whole 5 digits should be visible.

## Possible Fix

- The complete hint text in TextInputLayout view `id/zip_code_input_layout` with string `rat_profile_create_zip_code_hint` should be visible, also when the locale is not German (where the string "PLZ" is shorter).
- Increase the width of the view `id/zip_code_input_layout`

---
Internal Tracking ID: [EXPOSUREAPP-7318](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7318)

**Comment by Ein-Tim** [comment]
This is not an issue under iOS.

**Comment by MikeMcC399** [comment]
This is fixed in https://github.com/corona-warn-app/cwa-app-android/pull/3205 in branch [release/2.3.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.3.x) (EXPOSUREAPP-7318).

Unfortunately I missed noticing it in [v2.3.0-RC0](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.3.0-RC0-0).

**Comment by vaubaehn** [comment]
@MikeMcC399 Did you try the fix already in the emulator to see whether also the "Postal Code" hint is now displayed completely? In case it's still too small, could you recommend an abbreviation for zip code/postal code in analogy to PLZ?

**Comment by MikeMcC399** [comment]
@vaubaehn 

> Did you try the fix already in the emulator to see whether also the "Postal Code" hint is now displayed completely? 

With font size set to Default, the hint and the postcode itself is displayed completely in [v2.3.0-RC0](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.3.0-RC0-0). 

![image](https://user-images.githubusercontent.com/66998419/118699053-6138cf80-b811-11eb-8761-703b1b18f15d.png)

During input the full 5 digits are displayed, however the hint becomes truncated during input. I think that is acceptable.

If the font size is set to Large, then the hint becomes truncated to "Postal C..." in English.
If the font size is set to Largest, then the hint becomes truncated to "Postal..." in English.

> In case it's still too small, could you recommend an abbreviation for zip code/postal code as a string in analogy to PLZ?

In the UK it's called "postcode" - all one word, which would save three characters if changed. (See https://www.royalmail.com/find-a-postcode). However the other non-German languages would also need to be shorted as well:

![image](https://user-images.githubusercontent.com/66998419/118700239-bf19e700-b812-11eb-85fb-c32c8cbece89.png)

I think it is good enough in the release candidate for 2.3. It could of course be further optimized to show complete texts for all languages and all font sizes.

**Comment by vaubaehn** [comment]
@MikeMcC399 Thanks for all your testing!

**Comment by MikeMcC399** [comment]
@dsarkar 
Please add the Fix 2.3 label to this issue!

**Comment by MikeMcC399** [comment]
With font size set to Default, the hint and the postcode itself are displayed completely in the released version 2.3.2.

![image](https://user-images.githubusercontent.com/66998419/118699053-6138cf80-b811-11eb-8761-703b1b18f15d.png)

Closing this issue as resolved in 2.3.2.
