### ISSUE TITLE
Rapid Test: Date on start screen incorrect

### ISSUE THREAD

**Issue by haekelhexe** [corona-warn-app/cwa-app-android#3214]
## Avoid duplicates
* [ x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x ] Bug is not already reported in another issue

## Technical details

- Device name: OnePlus 6T
- Android version: 10.3.10
- App version: 2.2.1

## Describe the bug

The test result of the rapid test at the start page shows wrong test date. 

## Steps to reproduce the issue
Start screen:
![Screenshot_20210518-180629](https://user-images.githubusercontent.com/44695566/118687284-1dd86400-b805-11eb-9dbb-de2947147863.jpg)

Detail screen:
![Screenshot_20210518-180645](https://user-images.githubusercontent.com/44695566/118687290-1f099100-b805-11eb-833e-caf35b3f3e69.jpg)

The test result at the start screen is shown but gives a different date. When clicking on the panel, the detail page opens up and shows the correct date and time. Screenshots (German UI) are attached.

## Expected behaviour

Date of both screens should match.

Thanks for your great work! 

---
Internal Tracking ID: [EXPOSUREAPP-6895](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6895)

**Comment by Ein-Tim** [comment]
@haekelhexe Did you have a rapid test registered before the one from the 18.05.2021?

**Comment by vaubaehn** [comment]
I can cofirm this issue, but did not take the time to report yet.

Scenario:
You can register an appointment for a rapid test using the online portal maintained by netsyno.com for cooperating partners like "dm" and others. The rapid test can be up to 14 days into the future, but the registration link/QR code for CWA is provided immediately after taking the appointment. On the home screen card, CWA is showing the date, when the test was registered inside the app, not when the RAT was done.

### Quickfix
Replace the word "Durchgeführt" with "Registriert".

### "Nicer UI" Fix
* show the "Registriert am" also on the RAT home screen card, while the status is pending.
* when the status (pos/neg) could be polled successfully, exchange it with "Ausgestellt am" and the correct date of issuance.

**Comment by haekelhexe** [comment]
@Ein-Tim, I did but I deleted it before registering the new one.

**Comment by thomasaugsten** [comment]
Thanks for reporting this issue we aware of this problem and will try to fix this in the next version.

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-6895](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6895)

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
FYI PR https://github.com/corona-warn-app/cwa-app-android/pull/3220

**Comment by alexco2** [comment]
I had a similar issue. I scanned a covisa test result which I did 15 minutes prior. The app gave me the correct date and time of the test, but stated that the rest is ~97h old. After deleting the test, I was not able to scan the QR code again, since it was marked as already scanned

**Comment by heinezen** [comment]
Dear community,

This has been fixed in CWA release 2.3.

----
Corona-Warn-App Open Source Team
