### ISSUE TITLE
No notification symbol shown anymore if bluetooth is switched off

### ISSUE THREAD

**Issue by gitterman** [corona-warn-app/cwa-app-android#3237]
If Bluetooth is switched off, there used to be a notification symbol in the status bar.
A swipe down then brought up a text with a message that the corona-warn app could not work properly 
This symbol (a sun like circle with a corona) is not shown anymore, and thus there is also no message anymore.
I already uninstalled and re-installed the app and accepted all the default settings and I also added the app to be excepted from battery optimizations.
As I said it used to work on my phone, but currently I don't get the notification symbol anymore.
Without a reminder to turn on Bluetooth, the corona-warn app becomes quite useless.

## Technical details

- BQ Aquaris X5 plus
- Android 7.1.1
- App version: 2.1.1

## Describe the bug
If bluetooth is switched off I don't get a notification symbol in the status bar

## Steps to reproduce the issue
Just switch BT off and on and check if the notification symbol appears.

## Expected behaviour

If BT is off there should be a notification symbol in the status bar and a swipe down should show a message about disabled exposure logging.

![Screenshot_20210520-144756](https://user-images.githubusercontent.com/10762929/118982086-5d28c100-b97b-11eb-96d9-27cb0e091a92.jpg)
![Screenshot_20210520-144827](https://user-images.githubusercontent.com/10762929/118982090-5dc15780-b97b-11eb-805f-bbe10c376db1.jpg)

**Comment by MikeMcC399** [comment]
@gitterman 

The notification comes from Google and they changed it so it doesn't appear until after a 30 minute wait. See https://github.com/corona-warn-app/cwa-app-android/issues/2657#issuecomment-805822277.

Do you get a warning if you leave Bluetooth disabled for more than 30 minutes?

**Comment by gitterman** [comment]
I just talked to 2 friends and on their phones the icon in the notification bar appears instantly after they switch off Bluetooth.
Their phones run on Android 10 and Android 8 though.
![coronaWarn](https://user-images.githubusercontent.com/10762929/118992177-b0ebd800-b984-11eb-8828-78bebfda4e77.jpg)

**Comment by DerVogel2020** [comment]
> @gitterman 
> 
> The notification comes from Google and they changed it so it doesn't appear until after a 30 minute wait. See https://github.com/corona-warn-app/cwa-app-android/issues/2657#issuecomment-805822277.
> 
> Do you get a warning if you leave Bluetooth disabled for more than 30 minutes?

I get the warning after 30 minutes. Android 8,  Samsung Galaxy A5 (2017).

**Comment by gitterman** [comment]
You're right. On my phone the warning appears only after 30 minutes.
It seems that this crappy "feature" is either not yet activated on all android phones or that google changed it back to like it was.

**Comment by MikeMcC399** [comment]
@gitterman 
> I just talked to 2 friends and on their phones the icon in the notification bar appears instantly after they switch off Bluetooth.
Their phones run on Android 10 and Android 8 though.

I checked on a Samsung Galaxy A5 (2017) running Android 8.0.0 with ENS Version v1.8 (211515000) and this displays the warning after 30 minutes. Probably this is the same configuration as @DerVogel2020.

Google hasn't unfortunately documented any change in their release notes https://developers.google.com/android/exposure-notifications/release-notes , so we can only observe and compare notes about how our device behave.

I wonder what version of the Google Exposure Notifications System (ENS) your two friends are running? What version do you have?

You can view the ENS version through (Android) Settings > Google > COVID-19 Exposure Notifications then scroll down to the bottom of the page. Older versions of ENS will display something like 18210915000, where the first two digits 18 mean v1.8. The next two digits 21 represents the year 2021, then the next two digits e.g. 09 represent the week number of the release. Current versions split out the 18 and continue with the digits as before i.e. 211515000 is from year 2021, week 15.

**Comment by gitterman** [comment]
My version shows: v1.8 (211515000) which is exactly the same as with one of my friends.
On my phone there is the 30 minutes delay while on her phone the notification appears instantly.
Thus, there must be something else which is responsible for the different behavior.
