### ISSUE TITLE
Pending test result text overlapping

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#3286]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy A5 (2017) SM-A520F
- Android version: 8.0.0
- App version: 2.2.1

## Describe the bug

In the status waiting for a PCR test result there is an overlap of text between the bottom of "Your result is not yet available" and "Test added on dd/mm/yyyy".

## Steps to reproduce the issue

1. Set locale to English (United Kingdom)
2. In CWA Start Screen in tile "Register Your Test" tap "NEXT STEPS"
3. Tap "Test with QR Code"
4. Tap "ACCEPT"
5. Scan QR code of PCR test

![image](https://user-images.githubusercontent.com/66998419/119678423-c9099e80-be3f-11eb-9f70-ecd0cd977b1c.png)

## Expected behavior

There should be a visible gap between the text "available" and "Test added".

## Possible Fix

Add `app:layout_constraintTop_toBottomOf="@id/test_result_section_content"`
to `TextView android:id="@+id/test_result_section_registered_at_text"`

https://github.com/corona-warn-app/cwa-app-android/blob/9ec222a431340917834e831cc60edd14fa062d27/Corona-Warn-App/src/main/res/layout/view_test_result_section.xml#L47-L57

## Additional context

The issue is also present in the release/2.3.x branch.

It can also be seen on larger devices running Android 11 and with locale set to English (United Kingdom) or Deutsch (Deutschland). Just increase the font size.

---
Largest font size on Android 11. Locale English.

![image](https://user-images.githubusercontent.com/66998419/119694349-720ac600-be4d-11eb-8c4a-9a98c7238a1b.png)

----
Internal Tracking-ID: [EXPOSUREAPP-7539](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7539)

**Comment by MikeMcC399** [comment]
PR https://github.com/corona-warn-app/cwa-app-android/pull/3296 created.

**Comment by heinezen** [comment]
@MikeMcC399 Thank you

We have reported the issue in Jira. Your PR will be reviewed by the dev team. Thanks for contributing.

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
Please add Fix 2.4 label to this issue since PR https://github.com/corona-warn-app/cwa-app-android/pull/3296 has now been merged.

**Comment by MikeMcC399** [comment]
Confirmed fixed in CWA Android 2.4.2.

Device name: Samsung Galaxy A5 (2017) SM-A520F
Android version: 8.0.0

With CWA Android 2.3.4 and font size set to Huge, the text is overlapping.

After updating to CWA Android 2.4.2 there is no overlapping text after tapping in "PCR Test" tile on "DISPLAY TEST" button.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for contributing! Enjoy Saturday!
