### ISSUE TITLE
Build app for Android 11

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#3297]
## Avoid duplicates
* [X] This enhancement request has not already been raised before
* [X] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

The Android version of the Corona-Warn-App version 2.2.x is built with 
`targetSdkVersion 29`
equivalent to Android 10. This is true also for branches release/2.3.x ~~and release/2.4.x~~ intended for future releases.

## Suggested Enhancement

Update the Android CWA release to build against API 30 (Android 11).

## Expected Benefits

According to https://developer.android.com/distribute/best-practices/develop/target-sdk "Starting in November 2021, app updates will be required to target API level 30 or above and adjust for behavioral changes in Android 11." (Thanks to @PhilippNowak96 for this link.)

Since the release of the first version of CWA in June 2020, last year, Android has released Android 11. Apart from new devices being released with Android 11 from the beginning, also mid-range Android 10 devices such as Samsung Galaxy A50 devices, previously running Android 10, are being offered Android 11 firmware updates.

In addition Android 12 became available as a beta release in May 2021 (see https://developer.android.com/about/versions/12). The SDK is labelled "S Preview".

~~Advanced users may be migrating to Android 12 beta and observe compatibility problems if `targetSdkVersion 29` is not updated.~~ (Uncertain if this statement is true.)

**Comment by fynngodau** [comment]
Info: `targetSdkVersion` was increased to 30 in https://github.com/corona-warn-app/cwa-app-android/pull/2063, but then decreased to 29 again in https://github.com/corona-warn-app/cwa-app-android/pull/2087 because SAP internal pipelines didn't support 30 yet.

> Advanced users may be migrating to Android 12 beta and observe compatibility problems if targetSdkVersion 29 is not updated.

I believe we can't say this generally. Commonly, it is rather the other way round: compatibility modes apply to apps targeting older sdk versions in order to still support them, and increasing the targetSdkVersion without making any other changes may cause problems. Though I think here neither effect applies, as `targetSdkVersion 30` was already tested.

**Comment by MikeMcC399** [comment]
@fynngodau 
Thanks for the background information! I see that #2087 was from Jan 2021, so perhaps the SAP systems have progressed since then?

Do you see any benefit to migrating to `targetSdkVersion 30` or do you think it only introduces risk?

**Comment by PhilippNowak96** [comment]
One more thing to keep in mind: In November 2021 it will be necessary to target API 30 or no updates can be published anymore

https://developer.android.com/distribute/best-practices/develop/target-sdk

**Comment by MikeMcC399** [comment]
@PhilippNowak96 
> One more thing to keep in mind: In November 2021 it will be necessary to target API 30 or no updates can be published anymore
>
> https://developer.android.com/distribute/best-practices/develop/target-sdk

Thanks for that link! I will add the info to the main request.

There is a branch https://github.com/corona-warn-app/cwa-app-android/tree/dev/android-11 which suggests this enhancement request is effectively already being worked on.

**Comment by MikeMcC399** [comment]
PR https://github.com/corona-warn-app/cwa-app-android/pull/3310 has now merged
https://github.com/corona-warn-app/cwa-app-android/blob/36e77c9200e9b63ee65308025e4e2eadd82192ea/Corona-Warn-App/build.gradle#L30

into [release/2.4.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.4.x).

**Comment by MikeMcC399** [comment]
Closing, as this development issue has already been addressed in the [release/2.4.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.4.x) branch. App users should not notice any difference.
