### ISSUE TITLE
Close button not visible on RAT profile fullscreen QR code view

### ISSUE THREAD

**Issue by fynngodau** [corona-warn-app/cwa-app-android#3324]
## Technical details

- Android version: API 28
- App version: `release/2.3` (57b2d7a195b97e3bf77d59104fabae8a85b77984)

## Describe the bug

The Close (`X`) button is not visible on the RAT profile fullscreen QR code view, because it is white on white (for light theme). However, it *is* visible (black on white) on the event host fullscreen QR code view.

## Steps to reproduce the issue

1. Create RAT profile
2. Open RAT profile
3. Touch QR code to open its fullscreen view
4. Touch and hold in the top left corner → you will see the ripple effect below the white `X` like in this screenshot:

![Screenshot_1622357766](https://user-images.githubusercontent.com/16943720/120095257-4d507000-c125-11eb-83f0-0f97ff9af0f0.png)

## Expected behaviour

The `X` button should be visible (black on white, or the other way round when night theme is used).

----
Internal Tracking-ID: [EXPOSUREAPP-7593](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7593)

**Comment by heinezen** [comment]
@fynngodau 

Thank you for noticing the problem. I've created a Jira ticket to notify the devs. We will investigate the issue.

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@fynngodau 

I'm seeing a black cross on a white background (light mode) or a white cross on a black background (dark mode) for the full-screen rapid test profile QR code in CWA 2.19.2 so it seems this issue has been fixed.

Could you check yourself if you agree?

**Comment by fynngodau** [comment]
@MikeMcC399 Indeed, you are correct. Thanks, I will close the issue.
