### ISSUE TITLE
Border of the "quick note" buttons barely visible when in dark mode

### ISSUE THREAD

**Issue by daPhipz** [corona-warn-app/cwa-app-android#3338]
## Avoid duplicates
* [x] This enhancement request has not already been raised before
* [x] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

When the CWA is in dark mode, you can barely see the blue outlines around the active "quick note" buttons (less/more than 15min, with(out) mask, inside/outside) which are present when registering an encounter in one's diary. This impacts accessibility for visually impaired people - even I (who can see fine) find it difficult to distinguish active from inactive quick notes. **See screenshot below.** It is actually much worse on a physical device than on the screenshot... :see_no_evil: 

## Suggested Enhancement

Make the border a little bit thicker or make the whole button blue.

## Expected Benefits

Active quick notes are easier to distinguish from inactive ones when using the dark theme.

## Screenshot

![Screenshot_20210531-211355](https://user-images.githubusercontent.com/30795174/120234980-5f332f80-c259-11eb-9498-1d7405110eb6.png)

----
Internal Tracking-ID: [EXPOSUREAPP-7767](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7767)

**Comment by heinezen** [comment]
Hey @daPhipz ,

Thank you for the request. We have notified the development team. They will se what they can do about it.

----
Corona-Warn-App Open Source Team
