### ISSUE TITLE
duplicate rapid test registration - lost the test

### ISSUE THREAD

**Issue by Armin83** [corona-warn-app/cwa-app-android#3354]
I registered my test. (picture one)
I scanned the qr code with cwa app successfully. I had two test. the new rapid test and an old pcr test.
no result for 18 minutes ;)

![1](https://user-images.githubusercontent.com/19192087/120535447-43f42b80-c3e3-11eb-86ad-56eaa7f0485f.jpg)

Later i got a sms. you can see the result in cwa click the link (picture two)
I followed the link. I got the message test already registered.... i lost the test registration from the rapid test.
Only the old pcr test is still present.

![2](https://user-images.githubusercontent.com/19192087/120535441-435b9500-c3e3-11eb-806c-185e25beaf6a.jpg)

Should it work in this way ? Of course the test registration should only possible on one device, one time... but why it killed the old one with same id. It should not kill the same test registration. I heard from friend that it doesn't work for him. The result was uninstall the cwa app....

It's not the best behavior. 

---
Internal Tracking ID: [EXPOSUREAPP-7447](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7447)

**Comment by Ein-Tim** [comment]
Thank you for reporting this!

Just that we all get you right, you scanned a QR-Code linked to a PCR test, afterwards you scanned a QR-Code linked to a rapid test. Then you got a SMS which contained the link to register the rapid test result which you'd already added to the Corona-Warn-App when you scanned the QR-Code. 
You clicked on the link in the SMS, the Corona-Warn-App opened, you stepped through the screens in CWA, you did see the screen "Hinweis - Sie haben bereits einen Schnelltest registriert", clicked on "Weiter" and did get the pop up "QR-Code ist ungültig". You clicked on "Abbrechen" and the quick test was removed and only the PCR test was left?

**Comment by dsarkar** [comment]
@Armin83 Thanks for your report. 

Basically, as @Ein-Tim already asked:
I understand form your report that your rapid antigen test (RAT) disappeared. 
First you scanned RAT QR code, then you received as some point SMS where you pressed the link and with this the RAT was deleted. Please, confirm. I can confirm this behaviour on Android. iOS will not delete the test. Developers are informed about this issue.

Internal Tracking ID: [EXPOSUREAPP-7447](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7447)



---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
@Armin83 Another question: The link in your screenshot  (https://cov19.codes/cwa) opened directly the CWA or did it open another page and there was another link or a QR code? Thanks for your feedback.

**Comment by Armin83** [comment]
@dsarkar 
The link directly open the cwa app. (I click on the link, browser opens, automatically redirect to cwa app.)

> I understand form your report that your rapid antigen test (RAT) disappeared.
> First you scanned RAT QR code, then you received as some point SMS where you pressed the link and with this the RAT was deleted.

Yes, that's exactly what happened

**Comment by heinezen** [comment]
@Armin83

A fix is planned for the next release CWA 2.4.

----
Corona-Warn-App Open Source Team

**Comment by codejus** [comment]
FYI Problem is fixed with #3439

**Comment by d4rken** [comment]
Fixed with 2.4.x, should this still be an issue just re-open the ticket.
