### ISSUE TITLE
Creating Rapid Test Profile clears existing test results

### ISSUE THREAD

**Issue by bstrand** [corona-warn-app/cwa-app-android#3357]
## Description

Creating a Rapid Test Profile after registering test results clears the test result. 
Results cannot be re-registered due to #3354.

## Steps to reproduce the issue

1. Register a rapid test result in CWA by scanning QR code
2. Create "Rapid Test Profile" in CWA
3. Test result from 1. disappeared
4. Attempt to repeat 1. to re-register test result fails due to #3354
 
## Expected behaviour

Test results are retained until expiration unless explicitly deleted by user.

## Technical details

- Device name: Pixel 5
- Android version: 11 (build RQ2A.210505.003)
- App version: 2.2.1

---
Internal Tracking ID: [EXPOSUREAPP-7629](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7629)

**Comment by Ein-Tim** [comment]
Not reproducible under iOS.

**Comment by dsarkar** [comment]
@bstrand Thanks for your report. When you created the rapid test profile, you had received the test result already?


---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-7629](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7629)

**Comment by dsarkar** [comment]
@bstrand We are trying to reproduce but had no success so far in reproducing this issue. Could you provide more details information, please. We suspect it might depend on the exact timing:

- Date/Time: RAT registered
- Date/Time: RAT QR code scanned
- Date/Time: RAT done in test centre
- Date/Time: RAT result received vie CWA
- Date/Time: RAT profile created
- Date/Time: RAT result disappeared (what disappear? The test is completely gone?)

Thanks. Feedback very much appreciated. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by bstrand** [comment]
> When you created the rapid test profile, you had received the test result already?

Yes, I had received the test result and scanned its QR code with CWA.

Starting condition: No RAT profile exists. I had added 2-3 previous test results to CWA by scanning QR codes. As of June 4 all of them had expired (i.e. were >48 hours prior.)

> Date/Time: RAT registered
> Date/Time: RAT QR code scanned

1 June, 13:35 - Appointment made for 4 June at 'Corona Test Prenzlauer Berg' test center using the test vendor's website's user profile form. I did not have a CWA RAT profile at this time.

> Date/Time: RAT done in test centre

4 June, 13:40 - test done; 13:53 timestamp on test result received by email with QR code for loading results in CWA.

> Date/Time: RAT result received via CWA

NB: result was not received directly via CWA
QR code for results from test vendor was received via email 4 June 13:53 and scanned with CWA 4 June, ~15:30

> Date/Time: RAT profile created

4 June, ~15:35 (5 minutes after scanning test result QR code)

> Date/Time: RAT result disappeared (what disappear? The test is completely gone?)

After scanning the QR code, the test result was displayed as usual in a tile on the CWA main page. After I created the RTA Profile, this was replaced with the "Register Your Test" tile. Tapping it brought me to the Retrieve Test Result page, which offered "Test with QR Code", suggesting the test result had been cleared or deleted from phone/CWA. I thought, "No problem, I'll just scan the QR again," but this operation failed.

Perhaps after creating a RAT profile CWA expects / handles only results from tests that are associated with that RAT Profile? Or something like this?

> Did you register another test in the meantime?

No.

> Did you create the RAT profile for another test, which you then registered?

I created the RAT profile for future use, but did not (and have not) registered for a test with it yet.

I hope this helps!

**Comment by heinezen** [comment]
@bstrand Thank you.

We have forwarded this info to the developers. 

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
- According to https://github.com/corona-warn-app/cwa-app-android/issues/3357#issuecomment-855772764 from last year the developers were not able to reproduce the issue
- The Create Rapid Test Profile has been significantly reworked to include family members in the CWA 2.22 release (https://www.coronawarn.app/en/blog/2022-05-04-cwa-2-22/) released on May 4, 2022
- If there have been no further instances of this issue reoccurring since last year, I suggest to close the issue

**Comment by dsarkar** [comment]
@bstrand Please see [comment](https://github.com/corona-warn-app/cwa-app-android/issues/3357#issuecomment-1128608151)

**Comment by bstrand** [comment]
I never experienced it again. I hope this wasn't a red herring, thanks for your diligence with it.

I'll take this opportunity to give kudos to the dev team (for whatever that's worth from a random user.) The CWA's usability and functionality have improved steadily and considerably since launch. Well done. Thank you.

**Comment by dsarkar** [comment]
@bstrand Thanks for your feedback, and for contributing here. Feel free to open a new issue whenever necessary. Best wishes, DS

---
Corona-Warn-App Open Source Team
