### ISSUE TITLE
Cache test results on mobile data

### ISSUE THREAD

**Issue by HuiiBuh** [corona-warn-app/cwa-app-android#3360]
## Avoid duplicates
* [x] This enhancement request has not already been raised before
* [x] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [x] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation
Currently every time the App opens the app requests the test result again. It looks like you have to actively disable mobile data to use the cache of the app

## Suggested Enhancement
Cache the test result locally for ?24h?, to minimize network activity and enable the user to show the test in regions where not internet, or only expensive roaming, is available. 

## Expected Benefits
Less waiting time and access to the information even if no internet is available. 

----
Internal Tracking-ID: [EXPOSUREAPP-7774](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7774)

**Comment by HuiiBuh** [comment]
Nevermind.
It looks like you have to actively disable mobile data to use the cache of the app

**Comment by HuiiBuh** [comment]
Perhaps make this behavior a bit more user friendly...

**Comment by heinezen** [comment]
Hey @HuiiBuh ,

What aspect do you think should be more user-friendly? Do you propose caching the test rresult on a mobile connection too?

----
Corona-Warn-App Open Source Team

**Comment by HuiiBuh** [comment]
Yes caching would be nice.
You could update the view if the request succeeds, but until then the cached result would be nice.

**Comment by heinezen** [comment]
@HuiiBuh 

Thanks for the clarification. I've created an internal Jira ticket now. The devs will investigate the feature request.

----
Corona-Warn-App Open Source Team

**Comment by mtwalli** [comment]
Not planned
