### ISSUE TITLE
Status of version 2.3 release under Android

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-android#3380]
## Avoid duplicates
* [X] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Question is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Question has not already been asked in another issue

## Your Question
iOS version 2.3.2 was released in the App Store today. What is the status of the of the Android version 2.3 release? Is it already in staged roll out? Or is it not released to the Play Store yet?

**Comment by d4rken** [comment]
Android is in staged roll-out

**Comment by Ein-Tim** [comment]
Thank you @d4rken!

I'll close this. @MikeMcC399 feel free to follow up with an issue requesting a GitHub release.

Closing as answered.

**Comment by MikeMcC399** [comment]
@d4rken 
>Android is in staged roll-out

That is good news. Thanks. Congratulations to the team!

I assume that we will see the release shown on https://github.com/corona-warn-app/cwa-app-android/releases very soon in that case. The latest 2.3.x release showing up there is [v2.3.2-RC2](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.3.2-RC2).

**Comment by Ein-Tim** [comment]
FYI: Version 2.3.2 has been released to GitHub now: https://github.com/corona-warn-app/cwa-app-ios/releases/tag/v2.3.2

**Comment by MikeMcC399** [comment]
@Ein-Tim 
And to add the link for the CWA Android 2.3.2 release, this is https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.3.2 🙂.

**Comment by vaubaehn** [comment]
## Study on the effects of the onset of the announcement of CWA release on the emotions of the users



CWA staged rollout announced… | …at the very beginng | …after it finished
-- | -- | --
CWA user community   is… | Calm | Confused
Public is… | Confused | Calm



You probably never can do it right ;)

Have a nice night!

**Comment by vaubaehn** [comment]
I updated above "study" for the expected release of 2.4, as I can only talk for myself... 😉
