### ISSUE TITLE
VC_PREFIX_INVALID

### ISSUE THREAD

**Issue by RalfEs73** [corona-warn-app/cwa-app-android#3383]
I've already been vaccinated twice. Now I wanted to scan the QR code from the confirmation. The vaccination center is operated by Tresec GmbH and the certificate carries the required QR code. However, when I scan this one, I get the error message "VC_PREFIX_INVALID". Is the problem with me, or is this a bug?

![0](https://user-images.githubusercontent.com/6574078/121246135-1efb2f00-c8a1-11eb-97ca-5e7ef3bc2a7d.jpg)
![1](https://user-images.githubusercontent.com/6574078/121246142-202c5c00-c8a1-11eb-8060-c8e7df0ea8c0.jpg)

**Comment by thomasaugsten** [comment]
This is not valid EU certificate you can receive a valid certificate next week in pharmacies/Apotheken. 
Maybe you can scan the qr code in a qr code scan app and provide the anonymized content here

**Comment by RalfEs73** [comment]
Thanks.
