### ISSUE TITLE
No human-readable message when scanning wrong QR code with vaccine certificate scanner

### ISSUE THREAD

**Issue by Michael-635** [corona-warn-app/cwa-app-android#3394]
## Technical details

- Device name: Samsung Galaxy A70
- Android version: 11
- App version: 2.3.2

## Describe the bug

When scanning some random QR code which is not a vaccination certificate, you get an error message saying "Dieser QR-Code ist kein gültiges Impfzertifikat - VC_PREFIX-INVALID". When clicking on "Details", a StackTrace is shown (probably intentional). To me, a StackTrace containing lines like

     kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)

is an information disclosure which in my opinion is a vulnerability and should be avoided.

## Steps to reproduce the issue

1. Click on "Hinzufügen" for "Impfzertifikat hinzufügen"
2. Scan a random QR code which is not a valid vaccination certificate
3. In the resulting error message "Fehler - Dieser QR-Code ist kein gültiges Impfzertifikat" click on "DETAILS"
4. StackTrace will be shown:

![image](https://user-images.githubusercontent.com/67007492/121358955-4e5a7c00-c933-11eb-97f1-0d8bdfd7e6cc.png)

## Expected behaviour

A human readable explanation should be shown which does not disclose any implementation details.

----
Internal Tracking-ID: [EXPOSUREAPP-7709](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7709)

**Comment by Ein-Tim** [comment]
@Michael-635 Could you elaborate why this is a disclosure? The code is public on GitHub anyways. BTW AFAIK a StrackTrace like this is shown for all errors.

**Comment by Michael-635** [comment]
Well, ok, then I guess it's just my training to never ever show a StackTrace to a user, which of course might not be valid for open source apps.

But still, even if it's not a disclosure, is it acceptable from a user experience perspective to present messages like this without an explanation to an end user, even after pressing details?

**Comment by MikeMcC399** [comment]
@Michael-635 
I think you have a very valid point as the app is inconsistent in how it handles QR code scanning errors.

1. Scan an incorrect QR code with Register Your Test / Scan QR Code and the error message is "QR code is invalid" with **no** Details / Stack Trace.
2. Scan an incorrect QR code with Add Vaccination Certificate and the message includes the Details selection which shows the stack trace.

This could be considered an enhancement request to harmonize the error messages when an incorrect QR code is scanned.

There is a related, approved, wishlist item https://github.com/corona-warn-app/cwa-wishlist/issues/343 "Improve response to scanning non-CWA lab QR code".

**Comment by fynngodau** [comment]
> Well, ok, then I guess it's just my training to never ever show a StackTrace to a user, which of course might not be valid for open source apps.

True; implementation details can't be leaked, because they are already public ;) rather, a stacktrace is useful for debugging, not only for project members, but also for the general public, because they can also contribute fixes!

However, when a specific error is shown that only has one known cause (e.g. QR code incompatible) and is not expected to show up in unexpected places, then it is rather unnecessary to bother the user with this message which is cryptic to them.

**Comment by Ein-Tim** [comment]
FYI: This will be improved with a hot fix: https://github.com/corona-warn-app/cwa-app-android/pull/3400

To me it seems like the stack trace then will not be available to the user anymore.

**Comment by heinezen** [comment]
@Michael-635 

Showing the stack trace if fine as a fallback for now. As the other have pointed out, the code is already open, so nothing to worry about regarding information leakage.

The error will be caught in CWA hotfix 2.3.3 which should release soon. If you scan an invalid QR code it will show an explanation and link to an FAQ entry with an explanation.

----
Corona-Warn-App Open Source Team

**Comment by vaubaehn** [comment]
Hi, if the hotfix is not released yet, I'd propose to quickly add the same fix to the other error dialog, when scanning the SAME QR code again:
<img src="https://user-images.githubusercontent.com/68376758/121543989-a6fc4880-ca09-11eb-9c58-c41d752e085b.png" width="300" >
<img src="https://user-images.githubusercontent.com/68376758/121544054-b67b9180-ca09-11eb-9c03-46f9bb1d7059.png" width="300" >

/cc: @chiljamgossow @harambasicluka @mtwalli

**Comment by vaubaehn** [comment]
PS.: probably it's already enough to take out the "details" in this case here - imho no FAQ entry is needed
cross ref: #3400

**Comment by heinezen** [comment]
@vaubaehn Can you make a new issue for that? :)

**Comment by vaubaehn** [comment]
@heinezen 
I can do, eventhough it's only exchanging the word "wrong" with "same" from the title of this issue ;)
I just wanted to be quick, in case there is a chance to add a fix before 2.3.3 is released...

**Comment by heinezen** [comment]
@vaubaehn Thx :)

**Comment by vaubaehn** [comment]
@heinezen done: #3413

**Comment by MikeMcC399** [comment]
@Michael-635 
Would you like to check that this is fixed for you?

"Hot fix faq invalid vc (EXPOSUREAPP-7709)" PR https://github.com/corona-warn-app/cwa-app-android/pull/3400 was released with the [v2.3.3](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.3.3) Android update. In the meantime [v2.3.4](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.3.4) has also been released to fix other issues quickly.

If I select
1. Impfzertifikat hinzufügen
2. HINZUFÜGEN
using release 2.3.4, and I scan in a false code, I get the following screen shown:

![image](https://user-images.githubusercontent.com/66998419/121873166-6270f580-cd06-11eb-8e20-69052c1524b4.png)

The text "FAQ ZU IMPFZERTIFIKATEN" links directly to an explanation of the error message on https://www.coronawarn.app/de/faq/#vac_cert_invalid (or to https://www.coronawarn.app/en/faq/#vac_cert_invalid for English language users). There is no DETAILS option offered and no stack trace.

I think this resolves your concerns and it is definitely an important improvement in the app during the transition period when most vaccination QR codes are not yet compatible with CWA or the [CovPass-App](https://digitaler-impfnachweis-app.de/). As time goes on, more of the QR codes issued will be compatible and some pharmacies starting today have the capability to issue compatible certificates. (More detail is availble in the https://www.coronawarn.app/en/faq/#vac_cert_invalid quoted above.)

**Comment by Michael-635** [comment]
@MikeMcC399 
Yes, it's fixed for me and the issue can be closed.
Thank you!

**Comment by dsarkar** [comment]
@Michael-635 @MikeMcC399 @vaubaehn and community. Thanks for reporting and contributing. Closing this issue! Best wishes, DS

---
Corona-Warn-App Open Source Team
