### ISSUE TITLE
App language independence from system language setting

### ISSUE THREAD

**Issue by MimiComm** [corona-warn-app/cwa-app-android#3399]
Hi.

I know there is a very similar request in #22, but the title originally referred to an entirely different issue and I think was about iOS.
"Change language prior to giving consent to legal information"

I have my phone's system language set to English for various reasons. So far, every time I needed the app to e. g. send my employer a screenshot of a red status, I had to first set my phone to German before being able to do that. It wasn't a huge issue, but a bit of a hassle.

Now that the digital vaccination passport is about to launch, this issue becomes very pressing. I will need to be able to use the app on the go, possibly many times a day. Therefore the ability to choose an app language independently from the system setting is crucial.

Many locations might accept the digital passport presented in English, but surely some will (rightly so) insist on German. Not to mention other, less widely spoken languages many people have set their phones to.

I am asking you to consider making this a high priority, seeing as the digital passport will be an important part of daily life.

Thank you for reading!

**Comment by jucktnich** [comment]
You need to change #22 to https://github.com/corona-warn-app/cwa-wishlist/issues/22

**Comment by MimiComm** [comment]
I'm closing this now. I don't know how to change #22. I'm sorry for the incorrect post. I'm finding this board very confusing and lack the finesse to find my way around here.

**Comment by jucktnich** [comment]
You press the 3dot menu, than press edit and than delete the string #22 and replace it with "https://github.com/corona-warn-app/cwa-wishlist/issues/22"

**Comment by MimiComm** [comment]
Thank you. I can see no such option. I didn't originally create #22, if
that's why. Giving up on this for now for lack of time. Again, thank you!

**Comment by jucktnich** [comment]
No you should change your own post to link to the right issue

**Comment by heinezen** [comment]
Hey @MimiComm ,

We've changed you links, so that you are referring to the correct wishlist entry.

> Many locations might accept the digital passport presented in English, but surely some will (rightly so) insist on German. Not to mention other, less widely spoken languages many people have set their phones to.

The vaccine certificate is planned to be valid EU-wide and showing the vaccination proof should be language agnostic. Therefore, your concern won't be an issue, hopefully. You wouldn't need to change your language depending on your country of stay then.

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@MimiComm 
If you want a German language app for managing vaccination certificates, then you can use [CovPass-App](https://digitaler-impfnachweis-app.de/) which you can install in parallel with Corona-Warn-App (CWA).

If your Android phone is set to use English, then CWA will display in English and CovPass-App will display in German. (At least that is the way it is today. I installed CovPass-App on my Android device today and it only displays in German.)

**Comment by MimiComm** [comment]
Thank you for the replies!

**Comment by gitterman** [comment]
@MimiComm 
I don't understand why you did close this enhancement request.
It is still an open enhancement to me.
There are various reasons for having a different system language than the local country language.
Apps related to governmental sites or public transportation issues are mostly only related to the local country and thus should always allow to set the local language independently of the android system language.
I regard apps which support different system languages but NOT allow the user to select any of those languages independently of the system language as either lazily or ignorantly programmed.
An app like CWA which has so much man-power and budget support should definitely allow the user to individually select another supported language.
