### ISSUE TITLE
No human-readable message when scanning SAME QR code with vaccine certificate scanner

### ISSUE THREAD

**Issue by vaubaehn** [corona-warn-app/cwa-app-android#3413]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue - it's quite closely related to #3394  , but @heinezen wanted me to open a new issue ;)

## Technical details

- Device name: LG-G4 (LGH-815)
- Android version: 6.0
- App version: 2.3.2

## Describe the bug
When scanning the SAME vaccination QR code, you get an error message saying "Das Impfzertifikat ist bereits in Ihrer App registriert - VC_ALREADY_REGISTERED". When clicking on "Details", a stacktrace is shown.

screenshots:
<img src="https://user-images.githubusercontent.com/68376758/121543989-a6fc4880-ca09-11eb-9c58-c41d752e085b.png" width="100" > <img src="https://user-images.githubusercontent.com/68376758/121544054-b67b9180-ca09-11eb-9c03-46f9bb1d7059.png" width="100" >

## Steps to reproduce the issue

1. Scan a vaccination certificate.
2. Scan the same vc again.
3. See error

## Expected behaviour
A stacktrace for a known exception is superfluous and may confuse users. The stacktrace should not be displayed in this case, especially as the stacktrace's dialog does not contain any "ok" or "dismiss" button.

## Possible Fix
Remove "details" button.

## Additional context
related: #3400 , #3394

----
Internal Tracking-ID: [EXPOSUREAPP-7768](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7768)

**Comment by MikeMcC399** [comment]
@vaubaehn 
"overfluent" is not in my dictionary
but maybe "überflüssig" => "superfluous" or "unnecessary"?

**Comment by vaubaehn** [comment]
@MikeMcC399 thanks, I changed it accordingly.

**Comment by heinezen** [comment]
@vaubaehn Thank you.

Info is mirrored to Jira. It's tracked as an enhancement request, not as a bug though.

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@vaubaehn 
Your issue was already fixed in 2.7.1 and some corrections were also made in 2.8.0 (https://github.com/corona-warn-app/cwa-app-android/issues/3894).

In the meantime the code has been refactored however the issue remains resolved in the latest release 2.13.3.

Perhaps you could just cross-check and close this issue if it now works as you would like?

**Comment by vaubaehn** [comment]
@MikeMcC399 Thanks for taking care and keeping the repo tidy!

I cross-checked with CWA 2.13.3 and can confirm the issue is resolved.

Closing here - thanks everybody! ❤️
