### ISSUE TITLE
No content on home screen if started via logbook an navigated back twice (2.3.2/2.3.3 only)

### ISSUE THREAD

**Issue by nursoda** [corona-warn-app/cwa-app-android#3429]
## Technical details

- Device name: OnePlus 6T
- Android version: 10
- App version: 2.3.3

## Describe the bug

I use the direct link to the logbook every day to enter my contacts. Starting with 2.3.2 I noticed that "going back twice" leads to an empty home screen ("Startseite") if (and only if)

1. the app is started via the logbook direct link and
2. one navigates back twice (and does NOT tap the home symbol)

## Steps to reproduce the issue

https://user-images.githubusercontent.com/8425483/121754690-8ae5cd80-cb15-11eb-8b9e-81d0c9346cd5.mp4

**Comment by vaubaehn** [comment]
@nursoda 
This PR https://github.com/corona-warn-app/cwa-app-android/pull/3409 might fix your issue. Could you try with the latest hot fix from play store?

**Comment by nursoda** [comment]
I confirm that PR #3409 (released as 2.3.4) fixes the issue. Thanks :)
