### ISSUE TITLE
CWA allows addition of a vaccination certificate which CovPass rejects due to signature issue

### ISSUE THREAD

**Issue by jkrwdf** [corona-warn-app/cwa-app-android#3440]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name: Google Pixel 3 XL
- Android version: 11
- App version: 2.3.4

## Describe the bug

Scrolling of todays internet, I found a web page which shows a test vaccination certificate QR code. 
I attach a screenshot of the QR code to this ticket.

![image](https://user-images.githubusercontent.com/5329491/121910258-fbb40200-cd2e-11eb-9d4c-8237015e66a5.png)

CWA successfully scans and adds this QR code ("tester herr, born 4.5.1938"). 

When I try to do the same in CovPass or CovPassCheck, I get the message "Impfzertifikat enthält keine gültige Signatur - Möglicherweise wurde das Zertifikat von einer nicht autorisierten Einrichtung erstellt oder die App ist nicht auf dem aktuellen Stand...". 

## Steps to reproduce the issue

See above.

## Expected behaviour

Similar behavior, if applicable (if however the difference is that CWA is "just" a scanner/persistence/renderer, while CovPass really interacts with the certificate backend, then this is likely not applicable and the ticket can be closed).

**Comment by thomasaugsten** [comment]
duplicate  cwa-documentation/issues/634

**Comment by jkrwdf** [comment]
Roger. 

Edited initial description (especially "Bug is not already reported in another issue: TRUE --> FALSE") and closing with reference to the documented behavior. 

Thanks for the explanation therein.
