### ISSUE TITLE
[UI|UX] Indicate external URLs

### ISSUE THREAD

**Issue by IndianaDschones** [corona-warn-app/cwa-app-android#345]
## Current Implementation

The user cannot distinguish between content which will be shown inside of the app from content opening in e.g. a webbrowser.

![Screenshot_20200610-124724](https://user-images.githubusercontent.com/6652142/84259632-10a4f680-ab19-11ea-82db-7cf7b063c9d7.png)
![Screenshot_20200610-124732](https://user-images.githubusercontent.com/6652142/84259639-126eba00-ab19-11ea-8537-b763326873a5.png)

## Suggested Enhancement

Use a icon to indicate external urls/actions opening a webbrowser. Suggested icons:
- [Open in new](https://material.io/resources/icons/?search=new&icon=open_in_new&style=baseline)
- [Open in browser](https://material.io/resources/icons/?search=new&icon=open_in_browser&style=baseline)

## Expected Benefits

The user knows if some action (button-click) will open a webbrowser or is some in-app-action.

**Comment by marcmuschko** [comment]
Dear @IndianaDschones,

another good thought, thanks for reporting this! 
Visual external link indication will be included with #405.
Also thank you for the icon suggestion :)

I will close the issue when the PR is merged, please let me know if there seems to be something wrong afterwards. 

Best,
Marc
