### ISSUE TITLE
Vaccine certificate QR too small for the app scanner

### ISSUE THREAD

**Issue by aliendna51** [corona-warn-app/cwa-app-android#3452]
## Technical details

- Device name: Xiaomi Redmi Note 8 Pro
- Android version: 10
- App version: 2.3.4

## Describe the bug

The QR code of the standard sized vaccine sticker is too small for the frame to scan it on the app, making it impossible for the camera to focus. 

## Steps to reproduce the issue

1. Go to 'Add Vaccination Certificate'
2. Click on 'ADD'
3. Position the QR code in the frame
4. Camera cannot focus on the QR code

## Expected behaviour

The frame should be adjusted to fit the standard sized QR code for vaccines in Germany, which is very small.

## Possible Fix

- Apart from adjusting the frame, the option to either select from existing photos on the device or upload a document should be available. 
- Alternatively, the option to insert the data manually through a simple survey (date, type of vaccine, lot) could also be a solution. 

## Additional context

The standard sized stickers with the QR code for vaccines provided in Germany fit the International Certificate of Vaccination or Prophylaxis by WHO.

**Comment by MikeMcC399** [comment]
@aliendna51 
The small QR codes on the vaccine stickers are not designed to be scanned as vaccination certificates.

There is some background information on https://www.coronawarn.app/en/faq/#vac_cert_invalid.

If you have already had all your vaccinations, then you can go to a pharmacy to get a compatible certificate. If you are still planned for a second vaccination, then you can wait until this one and depending where you get it, and when, you may be issued with a compatible certificate (with big QR code) at that time.

**Comment by aliendna51** [comment]
Oh, it looks like I got the whole thing wrong then. Thanks for the super
fast response, the clarification and the extra info. I really appreciate
it!

**Comment by Jo-Achim** [comment]
Additional state-dependent note on the linked documentation from @MikeMcC399 above for the "digital vaccination certificate" - e.g. in Bavaria:

> Digital proof of vaccination
> People who received their second vaccination before June 10th should in future be able to submit their vaccination certificate in the form of a QR code (by email or post) via their existing BayIMCO account or by telephone via the call center of the vaccination center. 
Source: Paragraph "Digital Vaccination Certificate" / "Digitaler Impfnachweis" under https://www.stmgp.bayern.de/coronavirus/impfung/.

In addition, there is the following overview diagram for Bavaria: https://www.stmgp.bayern.de/wp-content/uploads/2021/06/2021_06_10_impfnachweis-1024x1024.png.

**Comment by MikeMcC399** [comment]
@Jo-Achim 
Thanks for sharing the Bavarian overview! Even though it is only for Bavaria it still gives a good idea of the possibilities which might also be similar in other German states.

**Comment by heinezen** [comment]
Some more background information: We've seen the digital vaccine certificate usually being printed on a piece of A4 paper. The QR code is 4.25cm x 4.25cm in size.

![Example](https://user-images.githubusercontent.com/66998419/121585483-f014c280-ca32-11eb-83b1-38ef4a74719b.jpg)

@aliendna51 Since your questions seem to be answered, I'll close your issue too. I hope you get the correct certificate soon and there are no further scanning issues with that one :)

----
Corona-Warn-App Open Source Team

**Comment by Jo-Achim** [comment]
> 
> 
> @Jo-Achim
> Thanks for sharing the Bavarian overview! Even though it is only for Bavaria it still gives a good idea of the possibilities which might also be similar in other German states.

Today, on June 25th, 2021, the download of the "EU DIGITAL COVID VACCINATION CERTIFICATE" / "EU DIGITALES COVIDIMPFZERTIFIKAT" is possible in Bavaria. Prerequisite you still have your 'vaccination registration account' at https://impfzentren.bayern/citizen/. The certificates can then be downloaded from the relevant person. 

In this sense, Jo-Achim.

**Comment by MikeMcC399** [comment]
@Jo-Achim 

> Today, on June 25th, 2021, the download of the "EU DIGITAL COVID VACCINATION CERTIFICATE" / "EU DIGITALES COVIDIMPFZERTIFIKAT" is possible in Bavaria. Prerequisite you still have your 'vaccination registration account' at https://impfzentren.bayern/citizen/. The certificates can then be downloaded from the selected person.

I found out from @Ein-Tim that it was already working yesterday, so I used it yesterday already.
