### ISSUE TITLE
Change language prior to giving consent to legal information

### ISSUE THREAD

**Issue by benekuehn** [corona-warn-app/cwa-app-android#3489]
Will the user be able to change the language during the first initial set-up? Maybe the user set the phone to German to learn it but would need the legal information, she is prompted with, in another language to understand the details.

-----------
Internal Tracking ID: [EXPOSUREAPP-2170](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-2170)

**Comment by heinezen** [comment]
@jucktnich 

Thanks for the hint. I've moved it to the Android repo.

----
Corona-Warn-App Open Source Team
