### ISSUE TITLE
Cannot save PDF from print layout, zero byte files created

### ISSUE THREAD

**Issue by mhaseneyer** [corona-warn-app/cwa-app-android#3527]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Nokia 6.1
- Android version: 10
- App version: 2.3.4

## Describe the bug

I created a QR codes for events that I organise, and want to export the code, so I can print it from another device (printer is USB only, not available through wifi). When using the print view and trying to save to the phone's storage, files are created but they are empty and have zero bytes.

## Steps to reproduce the issue

1. Create a new event
2. Open the printable version by tapping "show printable version" ("Druckversion anzeigen" in my app, language is German)
3. Tap the printer icon in the upper right corner.
4. Then select "Save to PDF" to create a PDF file on the phone's storage.
5. The file will be created, but has zero bytes.

I guess the app lacks permissions for accessing the device's storage. When using the "share" button in step 3, and providing it to a file manager app or Nextcloud, a valid PDF file will be stored to the device or uploaded to the cloud.

## Expected behaviour

I would expect a PDF file that can be opened with any PDF reader app, or copied from the phone to a different location. Obviously, a file with zero bytes are not valid PDF files.

## Possible Fix

Creating valid files succeeds when not using the "print" button but the "share" button in step 3 and handing over the data to an app that already has permissions to access the device's storage (or uploads the file to the Internet). So I assume it is a permission thing.

----
Internal Tracking-ID: [EXPOSUREAPP-8104](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8104)

**Comment by MikeMcC399** [comment]
@mhaseneyer 

I tried to reproduce your problem, but for me it worked.

I used a Pixel 3a emulator running Android 10 using the Deutsch (Deutschland) locale and the default print service (Standarddruckdienst)

1. Create an Einzelhandel event.
2. Three-dot symbol > "Druckversion anzeigen"
3. Tap printer symbol
4. Select printer "Als PDF speichern"
5. Tap print (to PDF) symbol
6. Tap "SPEICHERN" (into Downloads folder)
7. Open "Dateien" app
8. PDF file has non-zero size
9. Tap PDF file to open
10. PDF file (CHECKEN SIE EIN STOPPEN SIE DAS VIRUS with QR code) displays

- Which print service are you using? 
- Which folder are you saving the PDF file to? 
- Is the folder on the phone or on an SD card?

**Comment by mhaseneyer** [comment]
Doing exactly the same, just at step 8 I get size zero.

- I am using the default print service. Have never cared about printing from the device before, if there is a way of how I can be more specific about the print service, I am happy to learn how.
- Internal storage, "Download" folder. This is location proposed by the app and I guess it is the default.
- Phone. SD card exists but not used in this case.

**Comment by MikeMcC399** [comment]
@mhaseneyer 

I tried, also unsuccessfully, to reproduce the issue on a Samsung Galaxy Android 10 system.

Perhaps you could try the function "Als PDF speichern" outside the Corona-Warn-App, for instance by selecting, then printing a file (to PDF) listed in the Android file manager.

On the Android 10 emulator I'm using (Pixel 3a), the printer services are under:
Einstellungen > Verbundene Geräte > Verbindungseinstellungen > Drucken
On a Samsung device you need:
Einstellungen > Verbindungen > Weitere Verbindungseinstellungen > Drucken

If you haven't installed anything extra, like a print service from a printer vendor, it will probably list only "Standarddruckdienst".

**Comment by MikeMcC399** [comment]
@mhaseneyer 
If you enable "Error Reports" (App-Informationen > Fehlerberichte) in CWA you can view (Teilen und Fortsetzen) the logs which will contain print information if you attempt to print as PDF. You may find some clues to your issue there.

**Comment by heinezen** [comment]
@mhaseneyer 

Thank you for your report. We have informed the dev team and they will take a look at the problem now.

----
Corona-Warn-App Open Source Team

**Comment by mtwalli** [comment]
@mhaseneyer If I got your explanation right, you were able to see the following screen ,but when saving the file using `Save as PDF` it saves 0 bytes file , is that right?

- Few things to note:
1-  if you were able to share the file using the sharing method it means that the file is generated properly in CWA , we don't need to ask for storage permissions as the file is generated in the internal app directory.
2- The following screen is outside CWA App , it is from the system itself , you can try to print an email from Gmail you should see a similar screen

if you are not able to print using other Apps also, then it is probably some settings in your device that need to be adjusted.
if the issue is related to CWA only , it would be great if you can share a bug report from the App and send us the report ID? 
 
<img width="564" alt="Screenshot 2021-07-12 at 17 07 38" src="https://user-images.githubusercontent.com/25054729/125311716-e7feba00-e333-11eb-8483-c76d7289b6ae.png">

**Comment by mtwalli** [comment]
it is a CWA issue

**Comment by MikeMcC399** [comment]
@mtwalli 

> it is a CWA issue

Maybe you meant to write "it is **not** a CWA issue"? otherwise it doesn't make sense the close the issue.

**Comment by mtwalli** [comment]
> @mtwalli
> 
> > it is a CWA issue
> 
> Maybe you meant to write "it is **not** a CWA issue"? otherwise it doesn't make sense the close the issue.

@MikeMcC399  Yes, it mean it isn't a CWA issue, nothing we can do here
