### ISSUE TITLE
App shows full vaccination protection after setting clock time into future

### ISSUE THREAD

**Issue by samuelstein** [corona-warn-app/cwa-app-android#3532]
I discovered that you can fool the cw app by setting your system date into the future to transform your vaccination into a full vaccination status.
Is this already a known issue?

---
Internal Tracking-ID: [EXPOSUREAPP-7736](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7736)

**Comment by dsarkar** [comment]
@samuelstein Thanks for you report. This effect is know and does not constitute a problem. A verification requires a check with a verification app, in Germany that would be the CovPassCheck-App and a verification against a passport or another ID of the name and dat of birth.


---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
More information can be found in: https://github.com/corona-warn-app/cwa-documentation/issues/642

**Comment by svengabr** [comment]
I have just checked the linked Jira issue.

Jira Ticket is flagged as:
Resolution: `Wont Fix`
Status: `Obsolete`

Developer comment:
> Setting to obsolete. Proper verification of vaccination certificates requires use of CovPassCheck.
