### ISSUE TITLE
Subsequent DCCs: Matching of persons - which fields are used how?

### ISSUE THREAD

**Issue by vaubaehn** [corona-warn-app/cwa-app-android#3547]
## Avoid duplicates
* [x] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Question is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation) - iOS may handle it differently
* [x] Question has not already been asked in another issue -  I think so.

## Your Question
I found this in Google Play Store reviews today:

> Mein Nachname wurde auf dem Impfzertifikat 1.Impfung in kleinen Buchstaben und im Zertifikat der 2. Impfung mit grossem Anfangsbuchstaben geschrieben. Die App liefert eine Fehlermeldung beim Scan der 2.Impfung und akzeotiert dessen Zertifikat nicht. Was soll ich machen?

In case the error message results from a mismatch of different capitalization of the person's name throughout the issuing of the DCCs:
I was looking to a PR that was associated with person identifiers for certificate matching recently. For some reason I can't find it anymore. But when I was looking into the code, I was very certain that matching for the name is performed with standardized name, which means, the compared strings are all big caps and free of any non-Latin characters. I think @chiljamgossow was working on it, but I'm not sure. So, this user reported problem should not have happend.

**Is matching with standardized name introduced in a later release (>=2.4.x)? Or did something else went wrong?**

A kind of flexible matching of certifcates (with regard to persons' names) becomes crucial at the moment, when people take (further) vaccinations/tests in other countries as their home countries. Often medical staff in other countries can't use/type the special characters (like 'ä') used in persons' names on their keyboards when issuing certificates, so relying on the standardized name is important.

Edit: I found another, similar report:

> Leider erhalte ich beim Scan des elektr, 2. Impfzertifikates immer die Fehlermedung "Die persönlichen Daten des Impfzertifikates stimmen nicht mit denen der bereits registrierten Zertifikate überein. Sie können in der App nur Zertifikate einer Person registrieten". Die Zertifikate wurden offiziell durch d.Apotheke ausgegeben. Die App CovPass ordnet beide fehlerfrei für meine 1.und 2. Impfung zu. Nachtrag: Danke für.d.schnelle Hilfe; d.Namensdarstellung war tats. fehlerhaft. (Kleinschrift)

**Comment by d4rken** [comment]
DCCs are matched/grouped based on date of birth and first+lastname (standardized).

https://github.com/corona-warn-app/cwa-app-android/blob/c87daaa408abdcb0296fbc1b1a4933918746b2bf/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/CertificatePersonIdentifier.kt#L10

https://github.com/corona-warn-app/cwa-app-android/blob/c87daaa408abdcb0296fbc1b1a4933918746b2bf/Corona-Warn-App/src/test/java/de/rki/coronawarnapp/covidcertificate/common/CertificatePersonIdentifierTest.kt#L14

**Comment by vaubaehn** [comment]
@d4rken 

Hi Matthias, thanks for your answers!
Your pointers are referencing the code that I was thinking about when writing:
> I was looking to a PR that was associated with person identifiers for certificate matching recently. For some reason I can't find it anymore. But when I was looking into the code, I was very certain that matching for the name is performed with standardized name, which means, the compared strings are all big caps and free of any non-Latin characters.

Meanwhile we saw that successful matching certificates depends on how TSI & IBM/Ubirch beside other 3rd parties implement entry/generation of ICAO conformant names. And this is not optimal yet:
https://github.com/corona-warn-app/cwa-app-android/issues/3670
https://github.com/corona-warn-app/cwa-quick-test-frontend/issues/185

As the questions are answered, I'm closing here.
Have a nice day!
