### ISSUE TITLE
Typo in German certificate onboarding (ihre)

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#3555]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy A5 (2017) SM-A520F
- Android version: 8.0.0
- App version: 2.4.2-RC0

## Describe the bug

Typo of "ihre" instead of "Ihre" in certificate onboarding in German.

## Steps to reproduce the issue

1. Android locale is Deutsch (Deutschland)
2. Tap Zertifikate on the Startseite
3. Note text:
"Fügen Sie **ihre** digitalen COVID-Zertifikate in der App hinzu, um mit der App Ihren Impfschutz oder ein negatives Testergebnis nachweisen zu können."
4. If certificate onboarding has already taken place, then tap three-dot symbol and select "Information" to display the text.

## Expected behavior

Correct orthography.

## Possible Fix

https://github.com/corona-warn-app/cwa-app-android/blob/5549d03a471061e5ac7bd68b5a9d36299aa72962/Corona-Warn-App/src/main/res/values-de/vaccination_strings.xml#L108-L109

Change "ihre digitalen" to "Ihre digitalen" in `vaccination_consent_info_subtitle_text` of [Corona-Warn-App/src/main/res/values-de/vaccination_strings.xml](https://github.com/corona-warn-app/cwa-app-android/blob/release/2.4.x/Corona-Warn-App/src/main/res/values-de/vaccination_strings.xml) (capitalization of "ihre").

## Additional context

Typo was introduced with PR https://github.com/corona-warn-app/cwa-app-android/pull/3337. The text in the [Android release/2.3.x branch](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.3.x) is correct. Only the [Android release/2.4.x branch](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.4.x) is wrong.

**Comment by DerVogel2020** [comment]
I just tried to provide a PR for the 2.5-release, but there the text changed, the word "Ihre" was removed:
https://github.com/corona-warn-app/cwa-app-android/blob/f46bcbb78ed10d74520a77ac0a3d06fce9f931cf/Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml#L32

**Comment by heinezen** [comment]
Thanks @MikeMcC399 and thank you @DerVogel2020 for checking.

Looks like this will fix itself in 2.5. I'll leave the issue open in case it changes back to the old wording.

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@DerVogel2020 
Thanks for checking 2.5. I hadn't looked there because the strings for versions in development tend to be quite volatile.

@heinezen 
The unreleased 2.5 string file which @DerVogel2020 referred to https://github.com/corona-warn-app/cwa-app-android/blob/release/2.5.x/Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml has a similar grammatical error in a different place:

https://github.com/corona-warn-app/cwa-app-android/blob/c137952edf14f89b04e9dee38939f97d2c3f180a/Corona-Warn-App/src/main/res/values-de/covid_certificate_strings.xml#L75-L76

"Daher ist ihr Impfschutz  ..." should be
"Daher ist Ihr Impfschutz ..."

I understood that the Open Source Team doesn't want PRs to correct text issues in the app, so I will just report this here and check if it gets corrected by other means. Let me know though if you do want an PR from me.

**Comment by DerVogel2020** [comment]
@MikeMcC399 fixed in #3577

**Comment by MikeMcC399** [comment]
Grammatical German error reported in original post no longer appears, since the sentence has been reworded because of the ability to store certificates from multiple people.

The issue report is obsolete with the release of CWA Android 2.5.1, therefore closing.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks.
