### ISSUE TITLE
RAT proof feature: Does the counter change if the system time is changed?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-android#3557]
## Avoid duplicates
* [X] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Question is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Question has not already been asked in another issue

## Your Question
Does [the counter](https://www.coronawarn.app/assets/screenshots/2-4/de/android/rat_7.png), which is shown under Android when a RAT returns negative, change if the system time changes?
If yes, this would be a security flaw, since the user could always set the time back so that the result shows as valid (not yet older than 48h), although in reality it is.

--- 

## Related Issue
- https://github.com/corona-warn-app/cwa-wishlist/issues/543

**Comment by Ein-Tim** [comment]
@vaubaehn I See you have a test result in the CWA currently (https://github.com/corona-warn-app/cwa-app-android/issues/3559#issuecomment-877199316). Would you be so kind and check if you can manipulate the counter if you change the system time? 

Thank you!

**Comment by vaubaehn** [comment]
@Ein-Tim 
I created some screenshots for you.
I closed CWA and set system time one hour back in time. I opened CWA and was welcomed with this:
<img src="https://user-images.githubusercontent.com/68376758/125108300-2b61ea00-e0e2-11eb-82ac-59db45bc3081.jpg" width="200">

I looked to the test certificate:
<img src="https://user-images.githubusercontent.com/68376758/125108577-7ed43800-e0e2-11eb-812d-060f867f0e62.png" width="200">

I closed CWA again, and set system time to one hour into the future. I opened CWA. This time there was no error dialog that informed me about the wrong system time.

I looked to the test certificate:
<img src="https://user-images.githubusercontent.com/68376758/125108834-d83c6700-e0e2-11eb-926e-5662d4e0ff5a.png" width="200">

So, the timer shows the time with sc timestamp as reference and relative to the set system time.

By the way, only when the system time is set to the future, the sc time that is displayed below the certificate ("Ausgestellt am xxx um yyy") is American/English time format translated to German: 2:20 Nachm. Uhr 🤔 -> @mtwalli 

Did that help you?

**Comment by Ein-Tim** [comment]
@vaubaehn 

This did definitely help, thank you! 
I see a problem here, since you could always change your system time to the date of the issue and thus trick people who check for a valid certificate. 
Although there is the small text stating the "true", untrained people will always look at the big fat countdown and think the test result is valid.

One more reason to implement https://github.com/corona-warn-app/cwa-wishlist/issues/543.

I'll close this issue as answered but will open a new bug report which covers this. 

Thank you again @vaubaehn, have a nice evening!
