### ISSUE TITLE
Rename Information  to Informationen (German translation)

### ISSUE THREAD

**Issue by DerVogel2020** [corona-warn-app/cwa-app-android#3560]
## Avoid duplicates
* [x] This enhancement request has not already been raised before
* [x] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

Currently it says Information when you press the 3 dot button in the Zertifikate page.

CWA App Version: 2.4.2

## Suggested Enhancement

Rename to "Informationen " as it is in the Check in page.

----
See also #2944 for the Tagebuch page. That issue had the Internal Tracking-ID: [EXPOSUREAPP-6762](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6762)

**Comment by Ein-Tim** [comment]
@DerVogel2020 Could you tell me which other things you can do on the 3 dot menu - under iOS there is only the "i" icon in the top right corner.

**Comment by DerVogel2020** [comment]
@Ein-Tim nothing else
![Screenshot_20210627-132825_Corona-Warn.jpg](https://user-images.githubusercontent.com/65366950/123542756-a7a41700-d74b-11eb-80d0-19bbd6c58e20.jpg)

**Comment by DerVogel2020** [comment]
In release/2.5.x it seems to be fixed:
https://github.com/corona-warn-app/cwa-app-android/blob/f46bcbb78ed10d74520a77ac0a3d06fce9f931cf/Corona-Warn-App/src/main/res/values-de/green_certificate_strings.xml#L55
I will close this issue after the release of CWA-App 2.5.

**Comment by DerVogel2020** [comment]
Fixed in 2.5.1

**Comment by dsarkar** [comment]
@DerVogel2020 Thanks.
