### ISSUE TITLE
Test result certificate can't be downloaded

### ISSUE THREAD

**Issue by simontb** [corona-warn-app/cwa-app-android#3571]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Google Pixel 4
- Android version: 11
- App version: 2.4.2

## Describe the bug

Today I used the rapid test profile for the first time. The registration went smoothly and I got my negative result. However, the download of the test certificate fails.

<img src="https://user-images.githubusercontent.com/6491719/123688945-f5577700-d852-11eb-99f3-250772d52742.png" height="500">
<img src="https://user-images.githubusercontent.com/6491719/123688948-f5f00d80-d852-11eb-80dd-2f88be44c972.png" height="500">
<img src="https://user-images.githubusercontent.com/6491719/123688951-f5f00d80-d852-11eb-97ba-b1715a43cdf2.png" height="500">
<img src="https://user-images.githubusercontent.com/6491719/123688954-f688a400-d852-11eb-9fe2-0d6d5f9ad28f.png" height="500">

## Expected behaviour

I can download the certificate.

## Additional context

Test center was SAP (WDF01).

Here is the stacktrace that is shown in the details of the error dialog:

```
de.rki.coronawarnapp.covidcertificate.exception.TestCertificateServerException: Private key request failed.

de.rki.coronawarnapp.covidcertificate.exception.TestCertificateServerException: Private key request failed.
at de.rki.coronawarnapp.covidcertificate.test.core.server.TestCertificateServer$registerPublicKeyForTest$2.invokeSuspend(TestCertificateServer.kt:27)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
```

---
Internal Tracking ID: [EXPOSUREAPP-8162](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8162)

**Comment by thomasaugsten** [comment]
If the error comes up everytime can you please start the error report befor requesting the certificate again and then post the report id. This happens on every network?

**Comment by simontb** [comment]
Yes, this happens every time and on multiple networks (work and personal WiFi and mobile data). Internet connection works as I can use other sites and post this reply from my smartphone.

Thanks, didn't know the error report feature. ID is FCD2585A84B68E6F57AB

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-8162](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8162)

---
Corona-Warn-App Open Source Team

**Comment by Diapolo** [comment]
I also observed that erratic behaviour. Today I registered a RAT and tried to create/downliad a test certificate, which fails with the exact error message as posted by @simontb. Is there any additional information yet, what causes the error or is any more information needed to help fixing this? I can't create an error report, as I don't pass the SafetyNet check ;).

**Comment by Bubu** [comment]
I'm also experiencing this (via CCTG). I have an error log (but obviously can't submit it to the CWA team). (I can try out patches though.)

**Comment by dsarkar** [comment]
@Bubu @Diapolo Thanks for reporting, I updated the internal ticket with your reports.

**Comment by janhoffmann** [comment]
Here is another report: 4AFD74EDD4B14E9F821E
If you have questions regarding the teststation, I'm responsible for the station that generated my certificate, so I can try to help on both ends.

**Comment by dsarkar** [comment]
@janhoffmann Thank you very much.

**Comment by dsarkar** [comment]
FYU PR https://github.com/corona-warn-app/cwa-app-android/pull/3586

**Comment by Bubu** [comment]
The fix worked for me but with one caveat (this is possibly an unrelated problem but for everyone else affected I still want to mention it here):

When starting the new app version with the fix included the certificate went to "is being requested, this can take a few minutes". This was still showing >10 minutes later when I got impatient and closed the app by swiping it away from the recent apps and reopened it. The certificate was there immediately after the app start then.

**Comment by MikeMcC399** [comment]
I'm seeing [CWA Android 2.4.3](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.4.3) released and available in the [Google Play Store](https://play.google.com/store/apps/details?id=de.rki.coronawarnapp).

**Comment by codejus** [comment]
I can confirm that 2.4.3 fixed the issue. I was able to download a EU DCC for my last RAT, while I got an error before updating the app. :)

**Comment by heinezen** [comment]
@codejus Thanks for checking and confirming the fix!

We'll close the issue then.

----
Corona-Warn-App Open Source Team
