### ISSUE TITLE
Aqualand Check-In URL uses base64 encoding

### ISSUE THREAD

**Issue by PhilippNowak96** [corona-warn-app/cwa-app-android#3626]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Pixel 4XL
- Android version: 11
- App version: 2.4.3

## Describe the bug

The Aqualand in Cologne is promoting the event check-in via CWA. They use an own system with a qr code and on the result page there is a base64 encoded deeplink for the CWA. This deeplink does not work when trying to open it on Android.

Link:

https://e.coronawarn.app/?v=1#CAESOAgBEhZBcXVhbGFuZCBHbWJIICYgQ28uIEtHGhxNZXJpYW5zdHJhw59lIDEsIDUwNzY1IEvDtmxuGnYIARJggwLMzE153tQwAOf2MZoUXXfzWTdlSpfS99iZffmcmxOG9njSK4RTimFOFwDh6t0Tyw8XR01ugDYjtuKwjjuK49Oh83FWct6XpefPi9Skjxvvz53i9gaMmUEc96pbtoaAGhAmIP0ROe/na9NpzD6f8WImIgcIARABGPAB

Result:

![Screenshot_20210703-112840.png](https://user-images.githubusercontent.com/10376534/124366978-f540e800-dc53-11eb-9515-ff416a76708b.png)

## Steps to reproduce the issue

Simply try to open the link on an Android device.

## Expected behaviour

The link is working.

## Possible Fix

The base64 payload needs to be encoded as base64url.

## Additional context

On iOS it is working as expected:

![IMG-20210703-WA0004.jpg](https://user-images.githubusercontent.com/10376534/124367003-143f7a00-dc54-11eb-83cb-dc0ec395d2f5.jpg)

----
Internal Tracking-ID: [EXPOSUREAPP-8237](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8237)

**Comment by vaubaehn** [comment]
It looks like the deeplink is encoded in Base64 while CWA Android is decoding in Base64URL, hence the character '/' which is contained in the deeplink can't be resolved.
Does CWA iOS use Base64? Is there any caveat switching Android to Base64 also for encoding and decoding?

**Comment by thomasaugsten** [comment]
We cannot use base64 because the built in qr code decoder handle this as url. This cause encoding problem of url strings. 
Please forward the information the base64 needs to encoded as base64url

**Comment by vaubaehn** [comment]
@PhilippNowak96 
So if you just exchange '/' with '_' it results in a link encoded in Base64URL:
https://e.coronawarn.app/?v=1#CAESOAgBEhZBcXVhbGFuZCBHbWJIICYgQ28uIEtHGhxNZXJpYW5zdHJhw59lIDEsIDUwNzY1IEvDtmxuGnYIARJggwLMzE153tQwAOf2MZoUXXfzWTdlSpfS99iZffmcmxOG9njSK4RTimFOFwDh6t0Tyw8XR01ugDYjtuKwjjuK49Oh83FWct6XpefPi9Skjxvvz53i9gaMmUEc96pbtoaAGhAmIP0ROe_na9NpzD6f8WImIgcIARABGPAB

Which results in Android in:

<img src="https://user-images.githubusercontent.com/68376758/124382405-8bfabc80-dcc7-11eb-9eaa-5e59cf23c5d2.png" width="150">

**Comment by heinezen** [comment]
Thanks everyone. We have created a ticket for tracking the issue and will see what we can do about this by communicating the problem to the associated parties.

----
Corona-Warn-App Open Source Team

**Comment by PhilippNowak96** [comment]
Hey everyone,
thanks for the clarification! I wrote a support email to the recoverapp team (https://recoverapp.de/) describing the issue and added this issue as a link too. I will come back here again if I get any response of them.

@vaubaehn It was indeed very relaxing, thank you :)

**Comment by fynngodau** [comment]
The same issue was encountered here: https://github.com/corona-warn-app/cwa-website/pull/1130#issuecomment-825133260

I think one of the two clients should be changed so that they both behave the same.

**Comment by heinezen** [comment]
We have informed the involved parties and made it more clear in the specification that base64Url encoding should be used (not regular base64). This should hopefully solve the issue.

----
Corona-Warn-App Open Source Team

**Comment by PhilippNowak96** [comment]
I received an answer yesterday and they told me there needs to be a fix on some sort of interface. I'm not 100% sure if they mean their own one or something on CWA side. But they wanted to write me back as soon as they have a statement of one of their developers (first answer wasn't from a developer directly).
