### ISSUE TITLE
Harmonise the 3 Information screens (Zertifikate, Check-in, Tagebuch)

### ISSUE THREAD

**Issue by DerVogel2020** [corona-warn-app/cwa-app-android#3627]
## Current Implementation
See the 3 screenshots from Version 2.4.3

![Screenshot_20210704-152058_Corona-Warn.jpg](https://user-images.githubusercontent.com/65366950/124386724-02a1b500-dcdc-11eb-9ac2-cdedbced7f03.jpg)
![Screenshot_20210704-152046_Corona-Warn.jpg](https://user-images.githubusercontent.com/65366950/124386726-06353c00-dcdc-11eb-87f0-2fd0b09696f4.jpg)
![Screenshot_20210704-152028_Corona-Warn.jpg](https://user-images.githubusercontent.com/65366950/124386730-09c8c300-dcdc-11eb-867c-3191f041e3f9.jpg)

## Suggested Enhancement
- In the certificate information screen rename the Weiter Button and change the text of the hint to the Datenschutzerklärung.
- In the check-in information screen add a button which brings the user to the check-in page (similar to the Tagebuch-information screen) --- under iOS the button is called "Einverstanden" 

## Expected Benefits
More consistency between the 3 pages.
Easier usage when visiting the check-in information page.

---
Internal Tracking ID: [EXPOSUREAPP-12870](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12870)

**Comment by harambasicluka** [comment]
Hi @DerVogel2020, thanks for your feedback. I agree that these screens should be harmonised. I forwarded it to our UX colleagues, to get a decision. Thanks! :)

**Comment by Ein-Tim** [comment]
@DerVogel2020 

The screens are also different under iOS, do you wish that I (or you) open a new issue for this in the iOS repository or can we transfer this issue?

**Comment by DerVogel2020** [comment]
@Ein-Tim you can do it.

**Comment by fynngodau** [comment]
The Certificates tab onboarding is also missing a transition like here: https://github.com/corona-warn-app/cwa-app-android/pull/2954

**Comment by DerVogel2020** [comment]
> Hi @DerVogel2020, thanks for your feedback. I agree that these screens should be harmonised. I forwarded it to our UX colleagues, to get a decision. Thanks! :)

Hi, @harambasicluka did you get any feedback from the UX colleagues?
In Version 2.15 this inconsistency is still present.

**Comment by DerVogel2020** [comment]
@harambasicluka any news on this? In 2.20 it's still the same.

**Comment by Ein-Tim** [comment]
@dsarkar Do you have an update for us here?

**Comment by dsarkar** [comment]
@Ein-Tim @DerVogel2020 Will try to get some feedback from UX team.

**Comment by Ein-Tim** [comment]
Yeah I just wonder why the approved label is applied on this issue 🤔

**Comment by larswmh** [comment]
Thanks for your enhancement request @DerVogel2020. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-12870](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12870)

---
Corona-Warn-App Open Source Team

**Comment by DerVogel2020** [comment]
In 2.22 there is another new information page which is shown differently: "Schnelltest-Profile".
It's similar to the one for the check-ins, but the menu item is named in singular "Information".

**Comment by mtwalli** [comment]
No planned
