### ISSUE TITLE
Risiko-Ermittlung zeigt falsches Datum/aktualisiert nicht mehr nachdem Systemdatum verstellt wurde.

### ISSUE THREAD

**Issue by hd42** [corona-warn-app/cwa-app-android#3629]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [?] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy S10e
- Android version: 11 (Kernel 4.14.113-21644994)
- App version: 2.4.3

## Describe the bug

Meine Frau und ich hatten am gleichen Tag die Impfung, aber unterschiedliche Anzeigen wie lange es noch bis zur vollständigen Impfung dauerte (ich hatte noch Version 2.4.2, das war wohl der Grund). Bei der Suche nach dem Grund stolperte ich über einen Bericht zu  #3532 und probierte aus, mein Systemdatum auf den 1.8. zu stellen. Seit dem zeigt die Risikoermittlung "Aktualisiert: 1. Aug., 9:21". Ich bin nicht sicher, ob dennoch Aktualisierungen stattfinden oder ob ich jetzt 4 Wochen lang keine Aktualisierungen mehr erhalte.

## Steps to reproduce the issue

<img src="https://lh3.googleusercontent.com/pw/AM-JKLWv162F-HdF7G_nSNaitG5MfwmE4h7_wRtxVQwpAdeJ_aRhxu2q21-H3e1UE7yzM0t-G_VpdbFNfoAlaXxizyMUCYxUAgkqp7V1ek4Ln5GumFF7cBHVL4lkkeygIuRYKOccgLAkBuFmDcqaiPvEa7go_g=w459-h968-no" />

1. Change the system date to the future
2. Open the CWA
3. Wait for Risk assessment
4. Reset system data to update automatically
5. Open the CWA
6. Witness the future date still displayed as "Aktualisiert"
-->

## Expected behaviour

"Aktualisiert" should be updated even if current date is before a fictive last date from the future.

## Additional context

---
 Internal Tracking ID: [EXPOSUREAPP-10253](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10253)
Internal Tracking ID: [EXPOSUREAPP-9077](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9077)

**Comment by dsarkar** [comment]
@hd42 Danke fuer den Report. 

1. Eigentlich sollte eine Fehlermeldung (Geräteabhängig: nach etwa einer halben Stunde) erscheinen, dass das Datum und/oder Uhrzeit inkorrekt ist.
2. Ist das Gerät jetzt wieder auf die korrekt Zeit/Datum eingestellt?
3. Wenn ja, bitte beobachten og in etwa nach 4-6 Stunden (WIFI) oder nach einem Tag (Mobile DATA) die Risikoüberprüfung wieder anspringt, und hier bitte Feedback geben. 

Vielen Dank,
DS

---
Corona-Warn-App Open Source Team

**Comment by hd42** [comment]
Ich habe das Datum bereits gestern wieder aud "Datum un Uhrzeit automatisch stellen" zurückgestellt und befinde mich seitdem im WLAN. Eine Warnmeldung erscheint nicht.

**Comment by hd42** [comment]
Ich habe gestern Abend noch mal die Fehlermeldung gekriegt, das Limit sei erreicht:
<img src="https://lh3.googleusercontent.com/pw/AM-JKLUdn_Pl5MHIiH3yOlg5WN5gBdUutC7D3su_ai8PWf0E1VhRdGsyjfsskVR2NO2uOvSFuZACKcS0bkWQAOAn3n1BZT5P1MCqytU6efAYggeA-4Ht9M9xIUfCFzlnnN1l8IMl-RX2GNSaD1XuM0Xwy6y5NA=w459-h968-no" /> <img src="https://lh3.googleusercontent.com/pw/AM-JKLV0h_bwj2DiV9GPyuE_16Zr3HS6-caYPo_357cbRZ0Vp9YtmBv_luKE7KWxJF8rdtx-Q7P-5qfhng2XFR1HYhualUOK-aq18ffO5iS8QoGyPsWbRHs3xyvmf6mq1ffIZyI553T2mr_sDCsV4ra3HHKYnw=w459-h968-no" /> <img src="https://lh3.googleusercontent.com/pw/AM-JKLW2dS4NGd4xJB5wGGfRGULlqDhfZycAlti5xO3ZV0acJQB0MbfF2o7Ccz490eGwdTADii8IvasFZsSwR0BnZD7sDgP-jiwSExz6Opc4C4uRSuTl8aDnC0jpbJ3AuhyNBSpsFUFql9lY3Q3JNDExn5RkOg=w459-h968-no" />

**Comment by dsarkar** [comment]
@hd42 
OK, danke fuer das Feedack. Vorschlag: Die App einen Tag lang nicht aufmachen, dann bitte bei uns melden, ob alles wieder normal ist. 

- DE https://www.coronawarn.app/de/faq/#limit_reached
- EN https://www.coronawarn.app/en/faq/#limit_reached

Danke. VG, DS

---
Corona-Warn-App Open Source Team

**Comment by hd42** [comment]
Die Limit-Warnung kommt nicht mehr, das falsche Aktualisierungsdatum ist geblieben. Hatte also vermutlich nicht direkt miteinander zu tun.

**Comment by MikeMcC399** [comment]
@hd42 
Was zeigt 
Einstellungen > Google > COVID-19 Benachrichtigungen > Drei-Punkte Symbol > Überprüfung auf mögliche Begegnungen ?

Sind Einträge mit aktuellen Zeitstempel dort aufgelistet?

Die CWA-App zeigt noch: "Aktualisiert: 1. Aug., 09:21" an?

Wird "RISIKO-ERMITTLUNG AKTIV" noch angezeigt und hat das Gerät noch eine WLAN-Verbindung?

**Comment by MikeMcC399** [comment]
@hd42 
Ich konnte das Verhalten reproduzieren und warte jetzt ab, ob das Gerät sich wieder normalisiert. Evtl. müsste man die App zurücksetzen. Heute Nachmittag weiß ich mehr.

**Comment by MikeMcC399** [comment]
@hd42 
Ich benutze ein Samsung Galaxy A52 5G, mit Android 11, das das Problem zeigt.

Einstellungen > Google > COVID-19 Benachrichtigungen > Drei-Punkte Symbol > Überprüfung auf mögliche Begegnungen ?
zeigt bei mir, dass stündliche Überprüfungen heute gemacht wurden:
10:00, 10:13, 11:58, 13:03, 14:04, 15:08
Normalerweise im WLAN werden die Überprüfungen höchstens alle 4 Stunden durchgeführt.

Trotzdem, dass in der Google-Anzeige weiterschreitende Überprüfungen gemacht wurden, bleibt die CWA-Anzeige beharrlich auf den 1. Aug., 10:02

@dsarkar / @heinezen 
Can we get this logged with an Internal ID now?

**Comment by hd42** [comment]
In der Google-Übersicht sehe ich, dass bei mir stündliche Aktualisierungen bis einschließlich 3. Juli 20:03 Uhr stattfanden, dann am 01.08. um 9:22 Uhr, dazwischen nichts mehr.

**Comment by vaubaehn** [comment]
@hd42 
Vielleicht ist es einen Versuch wert, folgendes auszuprobieren:
Schalte Wifi am Telefon aus, bevor es 0:00 ist, und lass es bis morgen früh (mindestens bis 03:00) aus. Hintergrund: die Checks, wann neue Daten zur Überprüfung heruntergeladen werden und die Überprüfung angestoßen wird, sind ein klein wenig unterschiedlich in Abhängigkeit davon, ob das WLAN an ist. Eventuell kann die mobile Verbindung dabei helfen, die Überprüfung wieder anzuwerfen. Ob's aber tatsächlich funktioniert, würden wir erst morgen sehen...

**Comment by MikeMcC399** [comment]
@hd42 
Danke für die Google-Info! Dann ist die Risiko-Berechnung leider zurzeit effektiv inaktiv, wenn für den heutigen Tag keine Einträge vorhanden sind.

Ich hatte schon ausprobiert, ob folgendes hilft:
- Risiko-Ermittlung auf Gestoppt setzen
- Neustart des Telefons durchführen
- Auf RISIKO-ERMITTLUNG AKTIVIEREN tippen und aktivieren
- dann unter Risiko-Überprüfung fehlgeschlagen auf "ERNEUT STARTEN" tippen

Das hat bei mir nichts geändert. Ich probiere es morgen erneut aus.

**Comment by vaubaehn** [comment]
@MikeMcC399 
Ich habe zwar nicht in den Code geschaut, aber meine Hoffnung bei der Mobil-Verbindung ist, dass ```val = lastsuccess``` als Kriterium für den nächsten Download anders (weniger restriktiv) berechnet wird,

**Comment by MikeMcC399** [comment]
@vaubaehn 
Wir haben ja parallel zueinander geschrieben. Ich habe auch nicht in den Code geschaut, aber ähnliche Gedanken gehabt. Die Worker-Prozesse werden mit einem Neustart neu aufgesetzt. Ich befürchte, dass ein App-Reset notwendig sein wird, aber ein paar Versuche sind es Wert, bevor man das macht.

**Comment by vaubaehn** [comment]
@MikeMcC399 
Ich habe jetzt doch noch mal geschaut, und der Code hat sich seit meinem letzten Einblick vor einiger Zeit doch noch ganz schön verändert 😲 
Was aber immer noch gelten sollte, ist der forced download unter mobil... Allerdings scheinen im Code doch Abhängigkeiten zum letzten erfolgreichen Download-Datum bzw. package date zu bestehen - und wenn das tatsächlich mit 01.08.2021 abgespeichert ist, wird es schwierig. Allerdings schaffe ich es heute nicht mehr, dort tiefer einzusteigen, so verschachtelt und abstrakt wie der Code mittlerweilse ist 😱 

> Die Worker-Prozesse werden mit einem Neustart neu aufgesetzt. Ich befürchte, dass ein App-Reset notwendig sein wird, aber ein paar Versuche sind es Wert, bevor man das macht.

Genau, und falls @hd42 es ausprobieren möchte, sehen wir ja morgen, ob Erfolg oder nicht...
Hab ein gutes Wochenende!

**Comment by hd42** [comment]
WLAN ist aus, werde morgen über (Miss-)Erfolg berichten.

**Comment by hd42** [comment]
Hat leider nichts gebracht.

**Comment by MikeMcC399** [comment]
@hd42 
> Hat leider nichts gebracht.

Bei meinem Versuch auch nicht. 

Die Optionen sind dann:

- bis zum 1.8. warten, dann wird sich das wohl von alleine lösen. In der Zwischenzeit gibt es dann keine Überprüfungen.
- warten, ob sich das Open Source Team zum Problem meldet und eine Lösung vorschlägt. Das kann aber auch dauern und bedürfte vielleicht auch eine neue Version der App. Ich habe auch separat https://github.com/corona-warn-app/cwa-app-android/issues/3677 gemeldet und eine Rückmeldung dazu ist bisher nicht erfolgt.
- die App zurücksetzen (Drei-Punkte-Symbol > Einstellungen > Anwendung zurücksetzen). Es dauert dann noch bis zum Tageswechsel bis eine Überprüfung stattfindet. Zufalls-IDs werden trotzdem schon ausgetauscht, weil sie von Google gespeichert werden.

Ich würde wahrscheinlich in den sauren Apfel beißen und die App zurücksetzen.

**Comment by hd42** [comment]
Für mich sieht
DownloadDiagnosisKeysTask#hasRecentDetectionAndNoNewFiles so aus, dass dort geprüft wird, ob die letzte erfolgreiche Prüfung mehr als 24h her ist - bei mir ist das natürlich ein negativer Zeitraum. Die Logs sehen auch entsprechend aus:
`[...]
2021-07-10T02:48:47.505Z W/DownloadDiagnosisKeysTask: Aborting. Last detection is recent (<24h) and no new keyfiles.
2021-07-10T03:56:51.846Z W/DownloadDiagnosisKeysTask: Aborting. Last detection is recent (<24h) and no new keyfiles.
2021-07-10T05:20:57.294Z W/DownloadDiagnosisKeysTask: Aborting. Last detection is recent (<24h) and no new keyfiles.
2021-07-10T06:00:10.602Z W/DownloadDiagnosisKeysTask: Aborting. Last detection is recent (<24h) and no new keyfiles.
2021-07-10T06:10:04.046Z W/DownloadDiagnosisKeysTask: Aborting. Last detection is recent (<24h) and no new keyfiles.
2021-07-10T07:18:15.214Z W/DownloadDiagnosisKeysTask: Aborting. Last detection is recent (<24h) and no new keyfiles.
2021-07-10T08:26:44.222Z W/DownloadDiagnosisKeysTask: Aborting. Last detection is recent (<24h) and no new keyfiles.
`

Ich würde hier einen zusätzlichen Check vorschlagen, ob `nextForcedDetectionAt?.isBefore(now)`.

**Comment by MikeMcC399** [comment]
@hd42 
I can't judge if your PR #3683 will technically fix the issue, but I hope so!

Organizationally, your PR won't get accepted in that form though.

You need to make the changes in a new branch of your fork https://github.com/hd42/cwa-app-android, where the branch is named according to guidelines in
https://github.com/corona-warn-app/cwa-app-android/blob/main/.github/pull_request_template.md

The pull request should be based on a future unreleased branch and it should request a merge into that future unreleased branch. That would be either [release/2.5.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.5.x) or [release/2.6.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.6.x). Since [release/2.5.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.5.x) is very close to release probably [release/2.6.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.6.x) would be more appropriate. The developers will advise you on this. 

It's also good to get an internal ID first (which I requested in https://github.com/corona-warn-app/cwa-app-android/issues/3629#issuecomment-877212905).

**Comment by hd42** [comment]
Thanks for the hints, @MikeMcC399. I'm leaving on a two week vacation tomorrow morning. If none of the internal devs has picked this up till then, I'll try and create a formal pull request.

**Comment by vaubaehn** [comment]
Interesting side note: I just stumbled upon @hd42's screenshot above, showing 7 successful (?) provisions of diagnosis keys to the ENF API, what should not have been possible: https://developers.google.com/android/exposure-notifications/exposure-notifications-api#modes

ENF hick-up?

**Comment by MikeMcC399** [comment]
@vaubaehn 
It's strange that it didn't stop at 6.

@hd42 
I had to uninstall and reinstall the app to get it to work again. Resetting the app for some reason didn't solve the issue. My app may have been in a different state to yours, so that may not apply to you. Good luck anyway and I hope you enjoy your vacation!

**Comment by d4rken** [comment]
The [mentioned routine](https://github.com/corona-warn-app/cwa-app-android/issues/3629#issuecomment-877606317) targeted in PR #3683 should be seen as an extra case to proceed, not as an extra check to prevent proceeding.

https://github.com/corona-warn-app/cwa-app-android/blob/2943eff83e919812f9dffd0df2d6644898fa59e1/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/DownloadDiagnosisKeysTask.kt#L166-L180

"Abort if there are no new keyfiles, but it's weird if there are no new keyfiles after 24h, so in that case still go ahead."

Do the logs show why it is not downloading new key files?

**Comment by MikeMcC399** [comment]
@d4rken 
Could you possibly look at https://github.com/corona-warn-app/cwa-app-android/issues/3677 since this is a similar reproducible case? That might be easier to diagnose and fix, which could provide a better foundation to look at this one (#3629).

**Comment by vaubaehn** [comment]
@d4rken 

> Do the logs show why it is not downloading new key files?

To be honest, I feel there could be even more problems for workers/tasks depending on timestamps/other conditions that themselves depend on other conditions/timestamps... for example when being on metered connection
> `Duration(now, nextDetectionAt)` in `DownloadDiagnosisKeysTask.kt` is negative most of the time, as `nextDetectionAt` does not seem to be calculated correctly. `NextDetectionAt` is `lastDetection` plus 4 hours, but if only one detection per day takes place (because of metered connection), then this value would become negative, and I don't know what `fun wasLastDetectionPerformedRecently` is returning in that case...

(https://github.com/corona-warn-app/cwa-app-android/issues/2880#issuecomment-843065085)

Is there an _easy way_ to build a model of all workers and their dependent values, and to validate them in a simulation that cycles through all possible use cases (metered/non-metered, current time, future, past, changing forth and back...)? Something we could maybe do as a community effort?

**Comment by vaubaehn** [comment]
@d4rken 
For example:
` val nextForcedDetectionAt = lastSuccessfulDetection?.startedAt?.plus(Duration.standardDays(1))`
There is no need to make `nextForcedDetectionAt` dependent on `lastSuccessfulDetection` - it could always be the next day after 0:00 UTC. Every first detection of a day could be a forced detection.

**Comment by Ein-Tim** [comment]
@hd42 Did the app start working again on 01.08.2021?

**Comment by MikeMcC399** [comment]
@Ein-Tim 
The equivalent reproducible case https://github.com/corona-warn-app/cwa-app-android/issues/3677 does not show any record of a fix yet. I have not checked on more recent versions if this is still reproducible however.

**Comment by hd42** [comment]
> @hd42 Did the app start working again on 01.08.2021?

Yes, it works fine again.

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-10253](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10253)

**Comment by svengabr** [comment]
I have just checked the linked Jira issue.

Jira Ticket is flagged as:
Resolution: `Wont Fix`
Status: `Obsolete`

Unfortunately, no additional information was added to this Jira ticket.

This ticket will be closed in favor of https://github.com/corona-warn-app/cwa-app-android/issues/5183
