### ISSUE TITLE
Invalid QR code error when scanning EU test certificate 

### ISSUE THREAD

**Issue by gferon** [corona-warn-app/cwa-app-android#3635]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Google Pixel 5
- Android version: SPB2.210513.011
- App version: 2.4.3

## Describe the bug

I got a EU test certificate result today and I'm unable to add it to the Corona Warn app. I'm not sure how to provide any helpful information that doesn't contain private data.

Here's how the certificate looks:

![Screenshot_20210705-143753.png](https://user-images.githubusercontent.com/420581/124474476-db60eb80-dda0-11eb-953a-c243500f2217.png)

Note: I'm not scanning the French 2D-Doc QR code which I know is not interoperable, but the code on the top right of the document.

If that helps, I can definitely send the document to somebody privately.

## Steps to reproduce the issue

1. Go to "Next steps" under "Register steps"
2. Scan code
3. Invalid QR code error

## Expected behaviour

The test certificate should successfully scan and appear.

**Comment by Ein-Tim** [comment]
You cannot add a digital covid test certificate in the Corona-Warn-App at the moment, please use the CovPass app.

Starting with version 2.5 you can add your test certificate in the app, at the moment you can only request a certificate if your test has been transferred through the app.

**Comment by gferon** [comment]
Awesome, thanks for insanely fast answer! Looking forward to the next iteration of the app and thanks for your work :)

**Comment by thomasaugsten** [comment]
You could scan test certificates. recovery certificates will be added in 2.5
Can you provide the qr-code via email
thomas.augsten@sap.com

**Comment by Ein-Tim** [comment]
@thomasaugsten Could you please elaborate where one could scan a digital certificate for a negative corona test in the app?

**Comment by thomasaugsten** [comment]
This was a mistake from my side. You can create a test certificate but scanning is possible in 2.5 which should be released in the next week.
