### ISSUE TITLE
VC_NAME_MISMATCH error upon adding second vaccination certificate

### ISSUE THREAD

**Issue by raeior** [corona-warn-app/cwa-app-android#3645]
## Technical details

- Device name: Moto g6 plus
- Android version: 9
- App version:  2.4.3

## Describe the bug

When trying to add the second vaccination certificate the app shows a VC_NAME_MISMATCH error. Both documents containing the QR code show the same name. The only difference I can see is that the date of birth is formatted differently: YYYY-MM-DD vs DD.MM.YYYY. It is also possible that this is related to handling of a Dr. title as part of the name, but at least on the certificates both are written identically.  The same certificates are accepted without problem by the CovPass App. I could work around this by deleting the first certificate from the app and just adding the second one but the behavior is still strange.

## Steps to reproduce the issue

1. Add first vaccination certificate (It does not matter for the occurrence of the bug if it is from the first or second vaccination)
2. Add the second vaccination certificate
3. See error

## Expected behavior

Both certificates should be added without error, as happens in the CovPass App.

## Possible Fix

Looking at the printed data on the sheets I would expect it to be related to either the different date format or some minor difference in how the Dr. title is written.

**Comment by vaubaehn** [comment]
A response here could likely also answer #3547

**Comment by raeior** [comment]
Huh, no idea how I missed that report. Name capitalization is the same for both certificates in my case.

**Comment by dsarkar** [comment]
@raeior Thanks for reporting. 

Workaround: Delete all vaccination certificates and just scan the second one. IMMUNTY should be displayed  after 14 days of the second vaccination.


---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@raeior 

In the [announcement for version 2.13](https://www.coronawarn.app/en/blog/2021-11-03-cwa-version-2-13/) of the Corona-Warn-App it describes an enhancement which might have solved your issue:

"In addition, the project team has improved the algorithm when assigning certificates to people. The Corona-Warn-App now assigns certificates with spelling errors in the name to the same person.

Previously, errors such as a different number of spaces between a person's first and last name caused the Corona-Warn-App to assign these certificates to two different people. This changes with version 2.13. For this reason, a certificate may no longer be displayed in the overview under the "Certificates" tab. However, the certificate has not disappeared, but is then displayed in the certificates section under the name of the corresponding person. Users can access it by tapping on their name under "Certificates"."

**Comment by MikeMcC399** [comment]
The error code `VC_NAME_MISMATCH` no longer exists in current versions of the app, so it would be impossible for it to appear.

This is from the old 2.4 version:
https://github.com/corona-warn-app/cwa-app-android/blob/25403e0e90c2ca1534a198a84380afdbb65c7672/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/exception/InvalidHealthCertificateException.kt#L31

Since the error can no longer occur, this issue should be closed.
