### ISSUE TITLE
Digital Proof of Vaccination: highlighted certificate is not the one with the latest expiration date

### ISSUE THREAD

**Issue by LorenzNickel** [corona-warn-app/cwa-app-android#3653]
## Technical details

- Android version: 11
- App version: 2.4.3

## Describe the bug

Having multiple "Proof of Vaccination"s for the same person for the same vaccination can cause an issue where the "main certificate" (shown above the detailed list of vaccinations and the name and birth-date) is not the certificate for the 2nd vaccination with the latest expiration date.

## Steps to reproduce the issue

1. Generate 2 vaccination records for the same person for each of the two vaccinations (so you end up with 4 QR codes) with different expiration dates
2. Import the vaccination records. I did this in the following order: 1st vac (later expiration date), 2nd vac (later expiration date), 1st vac (earlier expiration date), 2nd vac (earlier expiration date) (though I'm not 100% sure about that)
3. Go to the certificates in the app
4. The Digital Proof of Vaccination shown now (without the QR code at this moment) has the earlier expiration date of the 2nd vac. (unexpected)
5. Click on this Proof of Vaccination to see the QR code
6. The Vaccination record at the top has the earlier expiration date of the 2nd vac. (unexpected)
7. If you click on each of the vaccinations now individually, you can see the correct expiration dates and are able to find the certificate with the later expiration date.

## Expected behavior

The certificate for a second vaccination with the latest date should be used in both overviews.

## Possible Fix

I guess you always show the most recent imported certificate for a second vaccination. However, ideally you would compare them and show the one with the latest expiration date.

## Additional context

To explain why I have 4 certificates, I got 2 from my pharmacy and later also received 2 from my vaccination center. However, they do have different expiration dates for each vaccine. Maybe this is also the issue and this should never be allowed to happen and both certificates should have the same expiration date for each vaccination.
Let me know if you need further information or testing from my side.

----
Internal Tracking-ID: [EXPOSUREAPP-8327](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8327)

**Comment by heinezen** [comment]
Hey @LorenzNickel 

Thanks for reporting! For clarification, I would like to ask a few follow-up questions:


* Both certificates with the earlier expiration date were issued by the same authority, correct? From your text, I assume this was the pharmacy

* I will label the certificates from now on, so we can distinguish them better. Please correct me if I'm wrong:
    * `VAC1_EARLY`: vacc shot 1, received from pharmacy, early certificate expiration date
    * `VAC2_EARLY` : vacc shot 2, received from pharmacy, early certificate expiration date
    * `VAC1_LATE` : vacc shot 1, received from vacc center, late certificate expiration date
    * `VAC2_LATE` : vacc shot 2, received from vacc center, late certificate expiration date

* The details (your name, date of birth, vaccine type) on all certificates is the same?
* The QR code that is shown in the app for the proof of vaccination is the same QR code that is shown on `VAC2_EARLY`s printout?



----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
@LorenzNickel 

Also a few general remarks:

> However, they do have different expiration dates for each vaccine. Maybe this is also the issue and this should never be allowed to happen and both certificates should have the same expiration date for each vaccination.

The expiration date refers to the certificate only, not the vaccine. Our certificates expire for security reasons which has nothing to do with the effectiveness of your vaccination.

Vaccination certificates currently expire 1 year after the certificate was issued (which may be some time after you are vaccinated). Recovery certificates expire 180 days after they were issued. The expiration date actually does not matter that much right now because it only indicates when you'd have to renew your certificate. The date of your vaccination (which is a separate entry in the certficate) is much more important at the moment because it shows whether you have full vaccination status.

What that means is that you can actually use both sets of certificates without issues. They are both valid proofs of your vaccination status. However, you are still correct in that the app should probably be able to figure out which of these certificates it should show as the proof. That's what we'll try to figure out.

----
Corona-Warn-App Open Source Team

**Comment by LorenzNickel** [comment]
Hey @heinezen 

yes your summary is in general correct.

Yes, the details on VAC1_EARLY and VAC1_LATE are the same and the details on VAC2_EARLY and VAC2_LATE are the same (except for expiration dates).

Tbh from my feeling all of the certificates in the app look a bit different to those on paper, so that's kind of hard to say. But from comparing the certificate numbers in the app itself and then with the paper version I would say that yes, I can see VAC2_EARLY as the main QR code (which would also make sense with the expiration dates).

**Comment by heinezen** [comment]
@LorenzNickel 

Thanks for confirming. I'll notify the dev team, so they can handle the issue. 

----
Corona-Warn-App Open Source Team

**Comment by d4rken** [comment]
Is this still an issue with 2.5.3 @LorenzNickel ?

**Comment by LorenzNickel** [comment]
As it seems like the "Valid through" text has been removed from the certificate information, it's a bit hard to tell now (which also fixes the problem party imo) but I think the "Currently used certificate" is now the one with the later expiration date, so thanks for fixing.
