### ISSUE TITLE
Own vaccination certificate highlighting is dependent on system time

### ISSUE THREAD

**Issue by sikupe** [corona-warn-app/cwa-app-android#3657]
Hi guys,

I think I have discovered a minor issue:

Scenario:
I have both vaccination certificates added to the CWA, but my second vaccination was just a few days ago. Therefore I am not counted as fully vaccinated because of the 14-day-period after the second vaccination.
If you now change your system time in android to a future date after the 14-day-period, your own certificate is shown as "fully vaccinated".
This can be an issue if the counterpart is **not** scanning the barcode (because of laziness, lack of smartphone, etc.) and instead is "proofing" the certificate only by looking into the app.

Issue:
The highlighting as "fully vaccinated" or "fully vaccinated in XX days" of the own certificate is dependent on the system time of the own smartphone.
This does not bother the security if the QR code is validated by the counterpart, but still is an issue if it is only validated by "looking over it". 

Possible mitigation:
Fetch the time within the app from a trusted timeserver, therefore the user can't make it look like he/she is vaccinated within the own app by changing the system time.

**Comment by DerVogel2020** [comment]
@sikupe this was already discussed in #3532
