### ISSUE TITLE
Exposure check failed and not recoverable if installation date wrongly in future

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#3677]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue
This follows on from https://github.com/corona-warn-app/cwa-app-android/issues/3629 and is related to this issue.

## Technical details

- Device name: Samsung Galaxy A52 5G (SM-A526B/DS)
- Android version: 11
- App version: 2.8.0

## Describe the bug

App does not stop exposure check taking place when date incorrectly set to future before installation. After correcting the date the exposure check still shows failure.

## Steps to reproduce the issue

1. Set date to tomorrow
2. Uninstall CWA (if already installed)
3. Install CWA
4. Open CWA
5. Tap "LET'S GET STARTED"
6. Tap "NEXT"
7. Tap "ACTIVATE EXPOSURE LOGGING"
8. Tap "Turn on"
9. Tap "NEXT", tap "NEXT"
10. Tap "DO NOT SHARE"
11. Tap "OK"
12. Tap "DO NOT ALLOW", tap "OK"
13. Note "Exposure check failed, with timestamp Today"
14. Tap "RESTART"
15. Note that this does not change the status
16. Leave CWA open and set the date correctly to today (or automatic)
17. Tap "RESTART"
18. Note "Exposure check failed, with timestamp of previously set future day"

## Expected behavior

- The app should prevent an exposure check from taking place if the date does not match the server date.
- With the "Exposure check failed" status an error message should be shown that the reason for this failure was an incorrectly set time.
- Also, if an exposure check is allowed to happen, then the app should recover and start carrying out exposure checks when the date is corrected.

## Additional information
- Recovery is possible by resetting the app
- The risk card does however show "Installed -x days ago" where -x is a negative number 

----
Internal Tracking-ID: [EXPOSUREAPP-8389](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8389)

**Comment by heinezen** [comment]
@MikeMcC399 

Thanks for checking. We've informed the dev team by creating an internal ticket.

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@dsarkar 

It may be worth linking:

Internal Tracking ID: [EXPOSUREAPP-10253](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10253) from:
- [ ] https://github.com/corona-warn-app/cwa-app-android/issues/4303
- [ ] https://github.com/corona-warn-app/cwa-app-android/issues/3629

together with:

Internal Tracking-ID: [EXPOSUREAPP-8389](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8389)

from this issue.

**Comment by MikeMcC399** [comment]
@dsarkar 

Please ignore the previous suggestion (https://github.com/corona-warn-app/cwa-app-android/issues/3677#issuecomment-956069534)!

I tried the repro steps with CWA 2.12.2 and the app gives no error from exposure logging if it was installed with tomorrow's date. I will close this issue now, since the problem description no longer fits the current app version.

**Comment by MikeMcC399** [comment]
- re-opened in #5183 due to minor UI changes in steps to reproduce
