### ISSUE TITLE
RAT proof feature: Countdown changes if system time is changed

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-android#3682]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: I assume any
- Android version: I assume any
- App version: I assume any since 2.1

## Describe the bug

As @vaubaehn answered in https://github.com/corona-warn-app/cwa-app-android/issues/3557#issuecomment-877307785, the countdown of the rapid test proof feature changes if the user changes his/her system time.

## Steps to reproduce the issue

1. Open the Corona-Warn-App
2. Register a RAT in the app 
3. Go and take the swap - to continue with step 4 you have to be tested negative
4. See the countdown 
5. Change your system time to the past - see negative numbers
6. Change your system time to the future - see that the numbers went up

## Expected behaviour

The countdown should not change if the system time is changed, because of https://github.com/corona-warn-app/cwa-app-android/issues/3557#issuecomment-877365769.

## Possible Fix

Align the RAT proof feature to the implementation under iOS: https://github.com/corona-warn-app/cwa-wishlist/issues/543.

## Additional context

This is a follow up to #3557.

----
Internal Tracking-ID: [EXPOSUREAPP-8390](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8390)

**Comment by vaubaehn** [comment]
> ## Possible Fix
> 
> Align the RAT proof feature to the implementation under iOS: [corona-warn-app/cwa-wishlist#543](https://github.com/corona-warn-app/cwa-wishlist/issues/543).

But I like my countdown? 😲 


😉

**Comment by Ein-Tim** [comment]
There is no countdown in the Android app anymore since version 2.21 / 2.22. It was aligned to iOS, thus this bug report is obsolete.
