### ISSUE TITLE
App shortcut does not adapt to change in locale

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#3685]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Google Pixel 3a emulator
- Android version: 11
- App version: 2.4.3 (and 2.6.0-RC2)

## Describe the bug

The app shortcut label does not adapt to a change in the system locale. If the app is installed on a device with locale set to English and the locale is subsequently changed to German, then the shortcut is still labelled "Add Entry".

## Steps to reproduce the issue

1. Set locale to English (United Kingdom)
2. Install CWA
3. Complete onboarding
4. Tap and hold CWA icon
5. Note shortcut "Add Entry"
![image](https://user-images.githubusercontent.com/66998419/125247179-f4aeee00-e2f2-11eb-9d1b-1e45ed7020e4.png)

6. Change locale to Deutsch (Deutschland)
7. Tap and hold CWA icon
8. Note that shortcut still says "Add Entry"

## Expected behavior

The label for the shortcut entry should match the current locale, for English this is "Add Entry" and for German "Eintrag hinzufügen".

## Additional context

I could only cause the shortcut label to change language by using the Reset App function (which removed the shortcut) and running through onboarding again (which added the shortcut using the active locale language). 

----
Internal Tracking-ID: [EXPOSUREAPP-8391](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8391)

**Comment by heinezen** [comment]
@MikeMcC399 

Thanks for findings this one. We ave created an internal ticket to address the problem.

----
Corona-Warn-App Open Source Team

**Comment by marcauberer** [comment]
Bug fixed in pr #3789

**Comment by MikeMcC399** [comment]
Could we get the [Fix 2.7](https://github.com/corona-warn-app/cwa-app-android/labels/Fix%202.7) label added to this issue if the fix in #3789 is part of the [2.7.0 milestone](https://github.com/corona-warn-app/cwa-app-android/milestone/41)?

**Comment by marcauberer** [comment]
The bugfix for this was rolled out in the latest release. Please re-open if the bug occurs again.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for reporting this issue.
