### ISSUE TITLE
No fake Diagnosis Key submissions triggered randomly by the app

### ISSUE THREAD

**Issue by mh-** [corona-warn-app/cwa-app-android#371]
## Describe the bug

In several places, the requirement to generate random "fake" network traffic to specific endpoints is stated (e.g. [here](https://github.com/corona-warn-app/cwa-documentation/blob/master/pruefsteine.md): "This attack surface is mitigated by random fake messages that are indistinguishable from valid ones. This way, key submission and the retrieval of test results are indistinguishable from the system's background noise, creating plausible deniability for users even if network traffic is observed.")

However, I do not find source code that creates such fake key submissions.
[asyncSubmitKeysToServer()](https://github.com/corona-warn-app/cwa-app-android/search?q=asyncSubmitKeysToServer&unscoped_q=asyncSubmitKeysToServer) has a parameter `faked`, but I do not see calls to the function where the parameter is set to `true`.

## Expected behaviour

The app should randomly (e.g. about once per day) trigger the same sequence of network traffic (marked as 'fake' in the encrypted data), which would happen if the user is infected.

**Comment by ChristopherSchmitz** [comment]
@mh- thanks for your feedback.
This functionality will be activated and delivered with v.1.1.

**Comment by mh-** [comment]
@ChristopherSchmitz Is it correct to assume that you will publish V1.0 on the Google Play Store without this advertised security/privacy feature? Will other security/privacy features be missing from V1.0? And when do you plan to publish V1.1?
(Sorry, I didn't find a release plan in the documentation.)

**Comment by SebastianWolf-SAP** [comment]
We can confirm this - we also made our [FAQ](https://www.coronawarn.app/en/faq/) more precise with respect to this question.

As we are working in a very dynamic setup, we can't provide any release plans for upcoming versions. Thank you for your understanding.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
