### ISSUE TITLE
Digital COVID certificates should look different if they aren't valid yet

### ISSUE THREAD

**Issue by jankna** [corona-warn-app/cwa-app-android#3801]
If you have scanned an EU vaccination certificate QR code and just open the 'Certificates' tab in CWA, the certificate looks as if it was already valid. It uses the same shade of blue and it doesn't say "Valid from" anywhere unless you tap on it.
Compare this to CovPass, where it not only shows the date of validity but also uses a lighter shade of blue to signal that the certificate is not valid yet.
In the Corona Warn-App, I'd suggest the use of a grey color to signal the same, the date should also show right in the Certificates tab without further user interaction.

**Comment by Ein-Tim** [comment]
Hi @jankna 

This issue seems to be the same as https://github.com/corona-warn-app/cwa-wishlist/issues/586.

If you think so too, I'd ask you to close this issue and monitor https://github.com/corona-warn-app/cwa-wishlist/issues/586 instead.

Thank you and have a nice weekend!

**Comment by jankna** [comment]
Yeah, I didn't see that one, but it's the same. Thank you for pointing this out.
