### ISSUE TITLE
[INFO / Bug]: Update problem after smartphone was switched off?

### ISSUE THREAD

**Issue by Jo-Achim** [corona-warn-app/cwa-app-android#3802]
Hello,

I currently have an additional smartphone on which the CWA is installed. However, this smartphone is often switched off for several days.

After switching on the smartphone and starting the CWA, an update takes place immediately, which takes a 'little longer' (several minutes) - so far ok. The result, however, is unlikely to be correct as there was no update. (An error message was not displayed.)

_Specific example:_ CWA was updated on 07/21/2021 6:18 p.m.:

![Screenshot_20210721-182506](https://user-images.githubusercontent.com/21124877/126963726-c7854b90-7fe8-48fe-a77d-0e6e0c0a9f02.jpg)

Then the smartphone was switched off.

On July 25th if it was switched on again and after CWA had carried out the 'little longer' update, CWA shows data from the last update before the smartphone was switched off (i.e. again from 07/21/2021 6:18 pm instead of 07/25 or 'today'):

![Screenshot_20210725-111056](https://user-images.githubusercontent.com/21124877/126962971-a5431c11-97b9-4b32-ac44-d380283dab3b.jpg)

If the smartphone remains switched on for a longer period of time, it will obviously be updated correctly; for example on 07/26/2021 3:07 am:

![Screenshot_20210726-071947](https://user-images.githubusercontent.com/21124877/126963045-1a05eb30-58b6-422a-bff3-db10ff7d3798.jpg)

I don't know whether the above behavior is correct after the first update!? Shouldn't the first update already update to 'today' after switching on? 

Best regards, Joachim.

GigaSet GS4, Build: E940-2795-00_10.0_V10_20210602
Android 10 with Android security update: May 5st, 2021;
Google Play-Systemupdate: June, 1st, 2021.
CWA Version: 2.5.1
ENF: 18212116000 / 18212418000

----
Internal Tracking-ID: [EXPOSUREAPP-9074](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9074)

**Comment by mtwalli** [comment]
Comment from investigator:
> This is the behaviour of the app. The calculation is done with the files that are already there, at the same time the download of new files is started. Those new files are only processed with the next calculation.
