### ISSUE TITLE
Placeholder in empty certificates tab may be cropped off

### ISSUE THREAD

**Issue by fynngodau** [corona-warn-app/cwa-app-android#3824]
### Technical details

- Device name: "Galaxy Nexus" Android Emulator template
- Android version: API 23
- Font size: normal

### Describe the bug

The placeholder which is shown when no certificates are displayed may be cropped off. See images below.

### Steps to reproduce the issue

* Use emulator template as described above
* Open Certificates tab and remove any certificates

The placeholder is then cropped off as seen in the image below.

### Expected behaviour

Enough space is available that the layout could be shown in full.

### Possible Fix

* Use available space.
* If not enough space is available, no cropped-off text should be displayed, instead the text should be removed completely.

However I don't know a good way to instruct the layout to do that in a satisfying way.

### Additional context

The layout's bottom, plus a `48dp` margin, aligns to the top of the "+ Certificate" FAB.

This is not the case for the Check In tab, where the placeholder layout aligns only to its parent's top and bottom. However, this may cause the FAB to be displayed over the placeholder text. This can also be seen in the images.

### Screenshots

"Show layout bounds" is enabled in the system's Developer options, thus the pink space around a layout indicates its margin.

Certificates tab | Check In tab
|---|---|
![Screenshot_1627468679](https://user-images.githubusercontent.com/16943720/127309761-a380ef57-fedd-40cf-a7a4-3f01c66425e0.png) | ![Screenshot_1627468689](https://user-images.githubusercontent.com/16943720/127309757-2c7b4e21-acac-4815-b05e-7a22b3cf18d0.png)

---
Internal Tracking ID: [EXPOSUREAPP-8721](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8721)

**Comment by MikeMcC399** [comment]
The screenshots look like they are from CCTG, rather than CWA, however I can reproduce this issue on CWA 2.7.0-RC0 and the 4.65_720p_Galaxy_Nexus_API_23 emulator.

The device has a small screen and the contents of the display do not fit and are not scrollable.

I'm also seeing the issue on the My Check-Ins screen which has truncated text and is not scrollable.

**Comment by dsarkar** [comment]
@fynngodau @MikeMcC399 Thanks. Internal Tracking ID: [EXPOSUREAPP-8721](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8721)

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
FYI PR https://github.com/corona-warn-app/cwa-app-android/pull/3842

**Comment by marcauberer** [comment]
The bugfix for this was rolled out in the latest release. Can this be closed?

**Comment by dsarkar** [comment]
@fynngodau Thanks for reporting the issue.
