### ISSUE TITLE
Validity check for Netherlands doesn't work 

### ISSUE THREAD

**Issue by error401de** [corona-warn-app/cwa-app-android#3847]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Galaxy S9
- Android version: 10
- App version: 2.6.1

## Describe the bug

Validity check with Netherlands doesn't work, I'm getting the attached warnings which I can't interpret.
It's working fine with every country but the Netherlands. Also the official dutch app (https://play.google.com/store/apps/details?id=nl.rijksoverheid.ctr.verifier) shows a green status for my certificate.

![Screenshot_20210730-161546_Corona-Warn](https://user-images.githubusercontent.com/34032466/127667672-4394877e-1b7b-4aea-aafe-3b63421b3d46.jpg)
![Screenshot_20210730-161539_Corona-Warn](https://user-images.githubusercontent.com/34032466/127667678-c063c78d-51d2-46a4-894b-e4bbfae543f9.jpg)
![Screenshot_20210730-161530_Corona-Warn](https://user-images.githubusercontent.com/34032466/127667684-18d9424f-b871-475d-b854-eb8d87364b3b.jpg)

## Steps to reproduce the issue

To me issue occurs on each try to check with new validity check functionality for Netherlands.

## Expected behaviour

Show green status

**Comment by Ein-Tim** [comment]
Hi @error401de 

I think this is a duplicate of https://github.com/corona-warn-app/cwa-documentation/issues/671, or?

**Comment by error401de** [comment]
Yep, thanks for the hint, I only searched in this repo.

**Comment by MikeMcC399** [comment]
@error401de 

Maybe you have the possibility to get your certificate re-issued, so that it uses the schema 1.3.0?

**Comment by error401de** [comment]
I need to check if I can reissue it.
Still I don't understand why CWA tells me I need schema 1.3.0 while the official dutch app tells me my certificate is fine though.

**Comment by thomasaugsten** [comment]
The Dutch app is not checking the acceptance rules it is only checking the signature like the CovPass app

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-8786](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8786)
