### ISSUE TITLE
Uniform / identical number format for the 7-day incidences

### ISSUE THREAD

**Issue by Jo-Achim** [corona-warn-app/cwa-app-android#3849]
CWA startpage:
The "7-day incidence" - nationwide - is in the number format xx,y. The "local 7-day-incidences", that can be added, are shown in the format xx.

It would be desirable to use a uniform number format here as well - namely xx,y.

Thank you.

PS: Even if it is a trifle - a sorting of the order of all information ("Local 7-day-incidences", "7-day-incidence (nationwide)", "Confirmed new infections", ..., "Vaccination doses administered") would be desirable .

Verification: Start CWA, scroll down and look to the informations.

Samsung Galaxy Note 10, SM-N970F / DS
Android 11 (One UI 3.1) with Android security update: July 01, 2021
Google Play system update: June, 1st, 2021.
CWA version: 2.6.1
ENF: 18212418000
NetGuard Pro 2.296
Norton 360, v.5.14.0.210726005

----
Internal Tracking-ID: [EXPOSUREAPP-8514](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8514)

**Comment by Ein-Tim** [comment]
@Jo-Achim 

I can't confirm this: 

Bundesweit:
![image](https://user-images.githubusercontent.com/67682506/127694122-67bd5024-ff79-4db3-b5fa-516e5c9b44dc.jpeg)

Local (Bavaria): 
![image](https://user-images.githubusercontent.com/67682506/127694131-e2b478fe-3a9d-4687-9afc-76e9082d59f9.jpeg)

Local (Munich): 
![image](https://user-images.githubusercontent.com/67682506/127694138-93e4915e-2f64-4fd6-bb72-1935a9dc64a4.jpeg)l

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Are your screenshots from iOS or from Android?
On Android I am seeing 26, not 26,1 for München (Stadt).

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Oh, I'm so sorry, I thought this issue was in the documentation repository. Yes, these are screenshots from iOS. So seems like this is a Android exclusive bug. 
Sorry again.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
You might have made a mistake, but you gave good information that this is only an Android issue and that the data is available with a decimal place digit on iOS.

Hopefully it will be easy to align the Android display to be the same as the iOS display.

**Comment by Jo-Achim** [comment]
Hello,

it's a Android-problem: Android 11 (One UI 3.1) with Android security update: July 01, 2021.

![Screenshot_Corona-Warn_Inzidenzen](https://user-images.githubusercontent.com/21124877/127732873-5d6a1fde-bd85-445a-aba7-eba28a5f8fc2.jpg)

Best regards, Joachim.

**Comment by PhilippNowak96** [comment]
If I am not mistaken this is already fixed with 2.7.0:

https://github.com/corona-warn-app/cwa-app-android/commit/2bba003970827f8618b40ed0f0abef79d43be57a

**Comment by MikeMcC399** [comment]
@PhilippNowak96 

> If I am not mistaken this is already fixed with 2.7.0: [2bba003](https://github.com/corona-warn-app/cwa-app-android/commit/2bba003970827f8618b40ed0f0abef79d43be57a)

You're right
PR https://github.com/corona-warn-app/cwa-app-android/pull/3820
[EXPOSUREAPP-8514](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8514).

Confirmed fixed in current Android branch [release/2.7.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.7.x). See screenshot below:

![image](https://user-images.githubusercontent.com/66998419/127734682-b593f8c2-ce23-4fa2-97eb-c48b80076fdc.png)

So this issue should have the [Fix 2.7](https://github.com/corona-warn-app/cwa-app-android/labels/Fix%202.7) label added to it.
