### ISSUE TITLE
[Test certificates]: exact to the minute vs. exact to the day...

### ISSUE THREAD

**Issue by Jo-Achim** [corona-warn-app/cwa-app-android#3878]
Hello,

when testing a vaccination certificate for validity in different countries, I noticed that the validity check takes place to the minute instead of to the day. With the result: see screen shot below.
iOS: not tested.

**_Example:_**
A certificate validation will be performed at **8:05** pm.
With "CHECK FOR ANOTHER COUNTRY", however, it is **8:06** pm and the result:

![Screenshot_20210804-200629_Corona-Warn_2](https://user-images.githubusercontent.com/21124877/128325457-18734976-e094-4566-93c6-8e1c96eede94.jpg)

**_Steps to reproduce the issue:_**
1. Open CWA
2. Select "Certificates"
3. Select a certificate
4. "CHECK VALIDITY"
5. Select country (or leave default "Germany")
6. "CHECK" (certificate ok)
7. **Wait a minute!**  (The smartphone time must have gone one minute further.)
8. "CHECK FOR OTHER COUNTRY"
9. The screen of point 5 is now displayed (with the current / last selected country), however, in the form of a screen shot with the red note: "The specified time is in the past ...".

10. If you choose another country, if necessary, and repeat step 6 ("CHECK"), you will get the test result for the country you have now selected.
11. Repetitions of step 8 lead to the same result (9): "The specified time is in the past ..." according to the screen shot. It is no longer necessary to repeat step 7.

_Note on step 7_: It can also be between steps 4 and 6.

**_Questions / Solutions:_**
• Wouldn't it be sufficient here, instead of checking for date _and_ time, just checking for date?
_or (possible better)_
• To update (date and) time with each “CHECK FOR ANOTHER COUNTRY”? Just as CWA does with execution “CHECK VALIDITY” (step 4). But see "_Note on step 7_". 

Best regards, Joachim.

Samsung Galaxy Note 10, SM-N970F/DS
Android 11 (One UI 3.1) with Android security update: 01. Juli 2021
Google Play-Systemupdate: June, 1st, 2021.
CWA Version: 2.6.1
ENF: 18212418000

**Comment by MikeMcC399** [comment]
@Jo-Achim 
An example rule that @vaubaehn posted is
https://distribution.dcc-rules.de/rules/DE/dde2fb1ce39f854c8818ea56385d796ef84bd5573547aa12999f1239c38e04ef
which shows am example rule validity 
  "ValidFrom": "2021-07-03T00:00:00Z",
  "ValidTo": "2030-06-01T00:00:00Z",

and those are exact points in time, so just using the day to compare will not necessarily produce the right results.

**Comment by Jo-Achim** [comment]
@MikeMcC399 
thanks for the hint. I'm not that far on the subject, but could there be a misunderstanding?

The information "ValidFrom": "2021-07-03T00:00:00Z" and "ValidTo": "2030-06-01T00:00:00Z" in connection with "vaccination" seem to relate more to the general validity of the certificate, i.e. from when the present certificate is valid and until when.

The above-mentioned 'certificate check with regard to entry requirements' of the various countries is 'only' intended to check whether the currently available and valid certificate is valid and recognized in the destination country. Right? (I assume that an invalid / invalid certificate could not be checked in this regard.)

But I close this issue.
On the one hand, because I may have used the function in a somewhat unrelated way and, on the other hand, it may actually not be ruled out in the future that entry regulations could change within a day.
One can only hope that the data source for the CWA is up-to-date enough.
