### ISSUE TITLE
Scanned vaccination certificate has first name and last name swapped

### ISSUE THREAD

**Issue by bluezed** [corona-warn-app/cwa-app-android#3881]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Xiaomi Mi Note 10 Lite
- Android version: 11
- App version: 2.6.1

## Describe the bug

After scanning the vaccination certificate the first name and last name appear swapped around in the app.

## Steps to reproduce the issue

Scan a vaccination certificate then check the name as it appears on the print out and compare to the app.

## Expected behaviour

The name should appear the correct way around.

## Additional context

I tested with the CovPass App and there the name appears in the correct order.

**Comment by Jo-Achim** [comment]
Is it possibly the same as here "Vaccination Details Screen: Firstname Surname in wrong order": https://github.com/corona-warn-app/cwa-app-android/issues/3692#issue-942150955 ?

**Comment by bluezed** [comment]
@Jo-Achim yes, looks like the same issue. Sorry I didn't find it when searching...

**Comment by Jo-Achim** [comment]
No problem, I think...

If you want, you can close this issue.

**Comment by bluezed** [comment]
Duplicate  #3692
