### ISSUE TITLE
Cannot remove vaccination certificates

### ISSUE THREAD

**Issue by edeso** [corona-warn-app/cwa-app-android#3895]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Describe the bug

looked all over the Android app but couldn't find a way apart from cleaning storage and scanning new. the documentation actually only mentions removing test certs but ommits the same for vax certs altogether. why is that?

before someone asks. i scanned some vax certs for travellers without smartphone that i didn't need later anymore and wanted to clean up.

**Comment by Ein-Tim** [comment]
I'll leave the steps how to do it under iOS here, maybe Android is the same: 

1. Click on the tab "Certificates"
2. Click on the person you want to remove the certificate from
3. Scroll down to the very bottom
Click on "Vaccination Certificate"
4. Click on "Delete Vaccination Certificate"

Hope that helps, if Android is different I'll hide this comment.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Android is different. The remove is hidden under the three-dot symbol. Instructions in next post.

**Comment by MikeMcC399** [comment]
@edeso 
I'm sorry to hear that you're having difficulty removing a vaccination certificate. Let me help you.

1. Tap on the "Certificates" tab. If you have a vaccination certificate stored it will show as<br>EU<br>Digital COVID Certificate<br>name<br>QR code.
2. Tap on the certificate, now it shows<br>EU Digital COVID Certificate<br>QR code<br>Vaccination Certificate<br>vaccinated on dd.mm.yy
3. Scroll down to<br>Vaccination Certificate<br>Vaccination m of n<br>vaccinated on dd.mm.yy. It may also say "Currently used certificate".
4. Tap on the above from step 3.
5. On the top right of the screen, tap on the three-dot symbol and then on "Remove".

**Comment by edeso** [comment]
@MikeMcC399 just tried. properly hidden, but works! thanks! maybe time to document that :)

any reason why it ain't in the first sandwich menu (on 2. above)? it's not intuitively clear that one can dive even more into details on the certs on the bottom.

**Comment by MikeMcC399** [comment]
@edeso 

> properly hidden, but works! thanks! maybe time to document that :)

This should be considered as an FAQ item at least. In the app itself, the Information menu item (also three-dot symbol at the top level) only deals with adding certificates, not with removing them.

> any reason why it ain't in the first sandwich menu (on 2. above)? it's not intuitively clear that one can dive even more into details on the certs on the bottom.

I don't know why the UI was designed this way. There have been similar usability issues with the contact journal where users couldn't find how to delete entries. (see https://github.com/corona-warn-app/cwa-wishlist/issues/334).

If you want to suggest a UI improvement, you could open a new item in https://github.com/corona-warn-app/cwa-wishlist/issues.

**Comment by MikeMcC399** [comment]
@edeso 

New FAQ articles have been written and published:

https://www.coronawarn.app/en/faq/#eu_dcc_remove "How do I remove a certificate from the Corona-Warn-App?"
https://www.coronawarn.app/de/faq/#eu_dcc_remove "Wie kann ich ein Zertifikat aus der Corona-Warn-App entfernen?"

There is also a new wishlist item https://github.com/corona-warn-app/cwa-wishlist/issues/608 "Improve usability for removing a certificate" created.
