### ISSUE TITLE
Keine Kameraauswahl beim Scan vom QR Code

### ISSUE THREAD

**Issue by Cino2424** [corona-warn-app/cwa-app-android#3905]
Ich habe hier gerade ein Android Smartphone gehabt welches beim scannen des QR Codes die falsche Linse angewählt hat.
Somit war ein scannen nicht möglich.

Es muss dringends eine Funktion eingebaut werden in welches man die Kameras durchschalten kann. Das Gleiche bei Covpass

**Comment by MikeMcC399** [comment]
@Cino2424 
Kannst Du bitte mit folgenden Infos Dein Post ergänzen:
- Device name:
- Android version:
- App version:

Welches war die "falsche Linse" und warum war sie für Dich falsch? War sie vielleicht kaputt?

Welcher QR-Code wolltest Du scannen? z. B.: PCR-Test / Schnelltest / Impfzertifikat

CovPass wird nicht in dieser Organisation/Repository behandelt. Du findest die Issues für die CovPass-App auf https://github.com/Digitaler-Impfnachweis/covpass-android/issues.

**Comment by Julian1203** [comment]
@MikeMcC399 Ich denke, Cino2424 meint wahrscheinlich, dass die App die Frontkamera statt die Rückkamera auswählt und dies nicht geändert werden kann.

**Comment by MikeMcC399** [comment]
@Julian1203 
> Ich denke, Cino2424 meint wahrscheinlich, dass die App die Frontkamera statt die Rückkamera auswählt und dies nicht geändert werden kann.

Wir können nur Vermutungen anstellen, wenn @Cino2424 nicht antwortet. Ich habe es aber persönlich nie erlebt, dass CWA über die Frontkamera einen QR-Code einzuscannen versucht. Daher wäre es gut zu wissen, ob das tatsächlich der Fall gewesen ist, und ob irgendetwas spezielles an dem Gerät von @Cino2424 gewesen ist. Deswegen auch die Frage zum Geräte-Modell bzw. OS-Version.

**Comment by MikeMcC399** [comment]
@dsarkar 
Since there has been no further feedback from @Cino2424 I would suggest to close this issue. There have been no similar reports that I am aware of, and without additional information we cannot troubleshoot the problem further.

**Comment by Ein-Tim** [comment]
@dsarkar Will this issue be mirrored to JIRA? Which further input is necessary?

**Comment by dsarkar** [comment]
Hi @Cino2424 CC @Ein-Tim, kannst du uns bitte mehr Details geben bitte? Siehe https://github.com/corona-warn-app/cwa-app-android/issues/3905#issuecomment-896632406. Vielen Dank!

**Comment by MikeMcC399** [comment]
@dsarkar 

This does not seem to be a general problem. @Cino2424 has not responded since their initial post in Aug 2021, so we do not have any more details. The CCTG issue was reported by one user in July 2021.

Also, since there is a workaround available of scanning from a file from CWA 2.11 and later from October 2021 onwards, I would suggest to close this issue.

**Comment by dsarkar** [comment]
Hi @Cino2424, and dear community, 

We will close this issue since it became stale and there are workarounds mentioned by the community here. Feel free to reopen the issue or open a new issue if necessary. Thanks for contributing here! Best wishes, DS

---
Corona-Warn-App Open Source Team
