### ISSUE TITLE
Impfzertifikat wird als "in Italien gültig" angezeigt, obwohl dort auch 14 Tage Wartezeit gelten

### ISSUE THREAD

**Issue by DooMMasteR** [corona-warn-app/cwa-app-android#3922]
## Technical details

- Device name: Xiaomi Mi 10T Pro
- Android version: Android 11
- App version: 2.6.1

## Describe the bug
Wenn ich die Gültigkeit meines Zertifikates prüfe, wird für Deutschland korrekterweise "Invalid" angegeben, wenn ich als Land Italien auswähle jedoch "Valid" obwohl die 14 Tage Wartezeit nach der Impfung dort genauso gelten wie hier.

## Steps to reproduce the issue

Impfzertifikat, jünger als 14 Tage importieren und prüfen ob es in Italien aktuell gültig ist.

## Expected behaviour

Es sollte nicht gültig sein.

## Possible Fix

Regeln korrekt hinzufügen.

---
Internal Tracking ID: [EXPOSUREAPP-8826](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8826)

**Comment by MikeMcC399** [comment]
@DooMMasteR 
Steht vielleicht unterhalb von:

"Ihr Zertifikat ist im gewählten Land gültig"

noch der Satz:

"Für diesen Zertifikattyp sind derzeit keine Einreiseregeln für das gewählte Land und den gewählten Zeitpunkt vorhanden. Bitte beachten Sie die folgenden Hinweise:"
(`validation_no_rules_available_valid_text`)

**Comment by MikeMcC399** [comment]
@DooMMasteR 
Die Seite ist aus meiner Sicht auch problematisch. Ich habe dazu eine generelle Fehlermeldung auf English (Projektsprache) in #3925 erfasst.

**Comment by DooMMasteR** [comment]
Sehr gut, hätte ich ggf. auch machen können, aber so umso besser.

**Comment by MikeMcC399** [comment]
Ich habe https://github.com/corona-warn-app/cwa-documentation/issues/678 übersehen, wo das Problem bereits erfasst war.

**Comment by dsarkar** [comment]
@DooMMasteR Thanks for reporting. As @MikeMcC399 already mentioned, this is a duplicate. We track this issue as well in Internal Tracking ID: EXPOSUREAPP-8826

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
CWA 2.8 was released today - see https://www.coronawarn.app/en/blog/2021-08-25-cwa-version-2-8/. Android users may have to wait up to 48 hours before Google Play Store makes it available to any individual account (staged rollout).

**Comment by Ein-Tim** [comment]
@dsarkar Could you close this issue?
