### ISSUE TITLE
Misleading status "Certificate is Valid" when country has no rules

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#3925]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue
Bug has been reported for a specific case (Italy) in https://github.com/corona-warn-app/cwa-app-android/issues/3922

## Technical details

- Device name: Samsung Galaxy A5 (2017) SM-A520F
- Android version: 8.0.0
- App version: 2.6.1

## Describe the bug

If there are no Business Rules defined for a certain Country of Arrival and any certificate is stored in CWA then "CHECK VALIDITY" always succeeds with the message:

"Your certificate is valid in the selected country"
(`validation_rules_result_valid_result_title`)

Although this is followed by the text
"There are currently no entry rules for the selected country and selected time for this certificate type. Please note the following:"
`validation_no_rules_available_valid_text`

the title is in bold case and larger case than the following text, so the title may be wrongly interpreted that the certificates were validated successfully, even though there was nothing to validate them against.
    
## Steps to reproduce the issue

1. Tap the Certificates tab, tap "+ CERTIFICATE"
2. Scan in a valid 1/2 vaccination certificate (i.e. for a vaccination of an incomplete series)
3. Tap "CHECK VALIDITY"
4. Select a country which does not yet have Business Rules defined, e.g. Italy
5. Tap "CHECK"
6. Note the message **"Your certificate is valid in the selected country"** followed by "There are currently no entry rules for the selected country ..."

![image](https://user-images.githubusercontent.com/66998419/129364122-8d5bb211-76e4-41a9-9310-a7dee2fe2225.png)

## Expected behavior

If there are no Business Rules available for a Country of Arrival then the app should not claim that the certificate is valid, since there is no proof of this being the case.

## Possible Fix

Output a different status message when checking certificate validity when no Business Rules are available for a certain Country of Arrival, such as:

**"Your certificate could not be validated for the selected country"**

## Additional information

If this issue also occurs on iOS it should be transferred to the [cwa-documentation](https://github.com/corona-warn-app/cwa-documentation) repository.

**Comment by Ein-Tim** [comment]
Closely related to https://github.com/corona-warn-app/cwa-documentation/issues/678

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Not only closely related. It's a duplicate. Thanks for your input. Now closing!

**Comment by MikeMcC399** [comment]
This (duplicate) issue is resolved by CWA 2.8, see announcement https://www.coronawarn.app/en/blog/2021-08-25-cwa-version-2-8/

"... In addition, the project team has adapted the EU certificate check. If a country has not provided any entry rules that the Corona-Warn-App can use for checking, the certificate check will state that the certificate cannot be validated. The countries that are listed under the certificate check in the Corona-Warn-App generally recognize the certificates. However, depending on the country and the applicable rules, the relevant certificate (on its own) may not authorize entry.

Previously, the app indicated in this case that the certificate is valid in the selected country. In the text below, however, it was pointed out that there are currently no entry rules available for the selected country. With version 2.8, users can clearly see that the certificate's validity could not be checked because the relevant country has not defined any entry rules."

**Comment by heinezen** [comment]
Indeed, this was fixed in 2.7.

----
Corona-Warn-App Open Source Team
