### ISSUE TITLE
Vaccination Certificate Android 2.6 incorrect screenshots

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#3926]
## Where to find the issue

https://www.coronawarn.app/en/screenshots/#android_screenshots
Section: Vaccination Certificate

and
https://www.coronawarn.app/de/screenshots/#android_screenshots
Section: Impfzertifikat

for Version 2.6

## Describe the issue

1. The background color blue at the top does not correspond to the app which uses grey (at least on Android 11).
2. The QR code is not from a digital COVID vaccination certificate. It starts with `https://www.coronawarn.app/E1` It should start with `HC1:`. 
3. The format of the example date of birth 01.02.1976 is incorrect. It should be YYYY-MM-DD, so 1976-02-01.

![VaccinationDetailsFragment_immune](https://user-images.githubusercontent.com/66998419/129439444-1e6d5abe-9172-41c3-afcd-f4220f177880.png)

## Suggested change

Replace the screenshots
- https://www.coronawarn.app/assets/screenshots/2-6/en/android/VaccinationDetailsFragment_immune.png
- https://www.coronawarn.app/assets/screenshots/2-6/en/android/VaccinationDetailsFragment_immune_2.png

with correct screen shots for CWA Android 2.6, like this one:

![VaccinationDetailsFragment_2 6 1](https://user-images.githubusercontent.com/66998419/129439402-9a17fdf2-223b-4b6b-9949-af32b412ba8b.png)

---
Internal Tracking ID: [EXPOSUREAPP-8987](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8987) Incorrect Name & Date

**Comment by dsarkar** [comment]
@MikeMcC399 Yep, I moved it to Android-repo. Actually I am a bit surprised about the grey background on Android. I will test tomorrow on an Android phone. I rescanned the one shown on iPhone, it is blue:

<img width="850" alt="image" src="https://user-images.githubusercontent.com/1409741/129450219-10603e56-351d-4836-9120-d101f7f8f8ff.png">

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-8987](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8987) Incorrect Name & Date

**Comment by MikeMcC399** [comment]
@dsarkar 
> I moved it to Android-repo. 

Thank you!

> Actually I am a bit surprised about the grey background on Android. I will test tomorrow on an Android phone. I rescanned the one shown on iPhone, it is blue:

The Max Mustermann QR code from https://www.coronawarn.app/assets/screenshots/2-6/en/android/VaccinationDetailsFragment_immune.png is not valid, so you can't scan this one in.

The Andrea Schneider QR code from https://www.coronawarn.app/assets/screenshots/2-6/en/ios/iPhone%2011%20Pro-screenshot_first_vaccination_certificate_details_part1.png in the section "Check certificates for validity before a trip" is a 1 of 2 (incomplete certificate). 

It seems in Android 2.6.1 the details view of a vaccination certificate shows with a grey background for an incomplete certificate, but only if there is no 2 of 2 (complete certificate) also stored. I'm not sure if that is the way it is supposed to be! Let me check in the 2.7 RC and if it looks strange there I will submit a separate issue to clarify.

**Comment by MikeMcC399** [comment]
#3927 submitted as separate issue.

**Comment by MikeMcC399** [comment]
@dsarkar 
Re: Your https://github.com/corona-warn-app/cwa-app-android/issues/3926#issuecomment-898903846

Can you confirm that the vaccination certificate you scanned is a 1 of 2 certificate and that you do not also have a 2 of 2 vaccination certificate for the same person stored on your iOS device?

**Comment by dsarkar** [comment]
@MikeMcC399 

> Can you confirm that the vaccination certificate you scanned is a 1 of 2 certificate and that you do not also have a 2 of 2 vaccination certificate for the same person stored on your iOS device?

Affirmative, see: 

<img width="854" alt="image" src="https://user-images.githubusercontent.com/1409741/129453496-212a50d0-bb7a-4788-84d4-5974b886c2e1.png">

**Comment by MikeMcC399** [comment]
According to https://github.com/corona-warn-app/cwa-website/issues/1660#issuecomment-909960309 screenshot issues will not be fixed in previous versions.

From the original issue:

1. The background color blue at the top does not correspond to the app which uses grey (at least on Android 11) - Not seeing this any more with 2.8.0.
2. The QR code is not from a digital COVID vaccination certificate. It starts with `https://www.coronawarn.app/E1` It should start with `HC1!`.  - Will open a new issue.
3. The format of the example date of birth 01.02.1976 is incorrect. It should be YYYY-MM-DD, so 1976-02-01. - This is fixed by PR https://github.com/corona-warn-app/cwa-app-android/pull/3987 in future version 2.10.x.

**Comment by MikeMcC399** [comment]
Issues from this one (#3926) are covered in issue #3927 & #4021 and PR #3987, so closing this issue since it is now duplicate.
