### ISSUE TITLE
[Bug? / question]: Screenshots of certificates and security...

### ISSUE THREAD

**Issue by Jo-Achim** [corona-warn-app/cwa-app-android#3949]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
  - iOS not checked / unknown.
* [X] Bug is not already reported in another issue

## Technical details

- Android version: 11
- App version: 2.7.1

## Describe the bug / question

It is very helpful to create screenshots in CWA, for example for documentation, reports etc. 

But shouldn't screenshots of saved certificates be prevented?
Cross-reference: Screenshots are not possible in the CovPass app (e.g. v1.28.7).

## Steps to reproduce the issue

See, for example, Screenshots in: [Vaccination Certificate Android 2.6 ... screenshots #3926](https://github.com/corona-warn-app/cwa-app-android/issues/3926)

1. Start CWA
2. Select 'Certificates'
3. Select a certificate
4. Make a screenshot

## Additional context

Note: However, I do not know whether it is possible in Android / iOS to allow / prevent screenshots for certain screens. 

Best regards, Joachim.

**Comment by Ein-Tim** [comment]
@Jo-Achim Any reasons why screenshots should be disabled?

**Comment by Jo-Achim** [comment]
@Ein-Tim, 
> Users are very unhappy that CovPass restricts screenshots, ...
>
I know.

> Any reasons why screenshots should be disabled?
> 
Maybe to avoid the use of 'stolen' certificates?
Maybe the developers of CovPass have good reasons to forbid screenshots!?

But I don't want to finally clarify the question myself - only ask.
With regard to the screenshots, which are not possible under CovPass, I only remember arguments regarding security, avoidance of unauthorized use (e.g. by copying the scanned certificates) etc.

**Comment by Ein-Tim** [comment]
IHMO disabling screenshots for the certificates tab does not add an additional layer of security, since if you intended to share your certificate, you can still just take a photo of the paper you got.

Additionally, CWA 2.9 will add an export feature, so user can export their certificates.

**Comment by vaubaehn** [comment]
The basic idea behind the certificates is, that they're only valid when
a) the person presenting also shows its ID
b) the digital signature is validated with a verifier app like CovPassCheck.
When these points are handled correctly, then abuse of the certificate is not possible. Hence, screenshots are not a security risk in this regard.
Unfortunately, this is not the case yet...

Screenshots can even introduce a layer of security to the certificate holders: In case app breaks, or papers get lost, they still have one additional source...

**Comment by Jo-Achim** [comment]
@Ein-Tim, @vaubaehn,

then it's very simple... thank you for information. 
And I am closing.
