### ISSUE TITLE
Can not read EU Digital Covid Vaccination Certificate

### ISSUE THREAD

**Issue by luxalpa** [corona-warn-app/cwa-app-android#3962]
## Technical details

- Device name: Samsung Galaxy S7 Edge
- Android version: 8.0.0
- App version: 2.7.1

## Describe the bug

When using the App on my Samsung Galaxy S7 Edge to make a picture of the Covid certificate on the paper that I got from the pharmacy it simply does not recognize the QR code (no error, it simply doesn't do anything). I tried it in different lighting setups, rotations, zoom levels, with patience, etc and also scanned the paper into my computer and tried scanning it from the monitor.

The only way I got it to work was to scan it in the Luca App (which had no problem with the code either way), and then make a screenshot of the code in the Luca App (which looks very different and also smaller) and then scan that screenshot (opened on my monitor) with the Corona Warn App.

## Steps to reproduce the issue

I would love to put a picture of the QR code but I think that's not allowed.

**Comment by Ein-Tim** [comment]
Hi @luxalpa 👋

This is a know issue and it's tracked in #3514. 
I suggest you add your observations to #3514 through an comment. 

> I would love to put a picture of the QR code but I think that's not allowed.

The QR code contains your personal information (name & date of birth) as well as information on your vaccination. So I would recommended not to share it here, publicly, on GitHub. 

Thank you and have a nice Sunday & stay safe!

**Comment by luxalpa** [comment]
@Ein-Tim 

Thanks a lot! This one can be closed then!
