### ISSUE TITLE
Inconsistent formatting of dates in app

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#3963]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue
See also https://github.com/corona-warn-app/cwa-app-android/issues/3830

## Technical details

- Android version: 11
- App version: 2.9.0

## Describe the bug

The format used to display dates in CWA in numerical format is inconsistent. In some places the user's preference which has been set via the devices locale settings is used, in other places the format is hard-coded to dd.mm.yy or dd.mm.yyyy, with 2-digit and 4-digit year formats being used on the same screen.

With the locale set to English (United States) the following different formats are found:

Section | Format | Example
--- | --- | ---
Certificates - date of birth | dd.mm.yyyy | PersonDetailsFragment_cwa_2.png
Certificates - vaccination | dd.mm.yy | PersonDetailsFragment_cwa_2.png
Certificates - test | dd.mm.yyyy | PersonDetailsFragment_cwa_2.png
Rapid Test Profile - date of birth | dd.mm.yyyy | RATProfileQrCodeFragment.png
PCR Test | dd.mm.yy | HomeFragment_test_positive.png
Contact Journal | mm/dd/yy | ContactDiaryDayFragment_locations_data.png

![PersonDetailsFragment_cwa_2](https://user-images.githubusercontent.com/66998419/130360147-480ff209-711f-41aa-b0ee-a1a1a2f3a4dc.png)

![RATProfileQrCodeFragment](https://user-images.githubusercontent.com/66998419/130360161-81ef5c51-88e7-4488-a25d-3102c251388f.png)

![HomeFragment_test_positive](https://user-images.githubusercontent.com/66998419/130360178-6b7ee42b-ef66-4442-a2e3-289411ed81b1.png)

![ContactDiaryDayFragment_locations_no_data](https://user-images.githubusercontent.com/66998419/130360188-dd4d8755-32a9-4788-89f2-6eb7ccf8716f.png)

## Steps to reproduce the issue

1. Settings > System > Languages and input > Languages<br>set to English (United States)
2. Settings > System > Date & time<br>select "Use locale default"/ disable "Use 24-hour format"
3. Connect mobile device to Android Studio
4. In Android Studio Build > Select BuildVariant deviceForTestersDebug
5. run src/androidTest/java/de/rki/coronawarnapp on emulator
6. View > Tools Windows > Device File Explorer
7. Go to /data/data/de.rki.coronawarnapp.test/screenshots
8. View screenshots and note discrepancies in the way that the date is shown

## Expected behavior

The display of dates in numerical format in CWA should be consistent and preferably the locale format should be used.

## Possible Fix

Standardize date output across the app.

---
Internal Tracking ID: [EXPOSUREAPP-9127](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9127) Android
Internal Tracking ID: [EXPOSUREAPP-9220](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9220) Design
Internal Tracking ID: [EXPOSUREAPP-9238](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9238) iOS

**Comment by Ein-Tim** [comment]
iOS:

Section | Format (under Android) | Same as Android?
-- | -- | -- 
Certificates - date of birth | dd.mm.yyyy | **No** - Format is mm/dd/yy
Certificates - vaccination | dd.mm.yy | **No** - Format is mm/dd/yy
Certificates - test | dd.mm.yyyy | **No** - Format is mm/dd/yy
Rapid Test Profile - date of birth | dd.mm.yyyy | **No** - Format is month as abbreviation (e.g Dec for December) dd, yyyy
PCR Test | dd.mm.yy | **No** mm/dd/yy
Contact Journal | mm/dd/yy | **Yes**

Additionally:

PCR Test pending: month as abbreviation (e.g Dec for December) dd, yyyy

I noticed way more inconsistencies in the format of dates when the region & language was set to German.

@MikeMcC399 Please decide how you want to continue with this issue? Move to documentation repo or leave it in the Android repo?

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Thank you for your notes about iOS. I saw from the screenshots on https://www.coronawarn.app/en/screenshots/ that there are quite some differences between Android and iOS, so I believe it is better to keep the Android and iOS issues separate. If you feel that changes should be made to iOS then I suggest you open a separate iOS issue. You can mention this issue in the iOS one.

I am more concerned with numerical dates like 04.08.21 where especially with English (United States) the month and day are written in a different order e.g. 08/04/21. I am less concerned with months displayed alphabetically like December, where the date is clearly understandable independently of the order of day and month.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks. Internal Tracking ID: EXPOSUREAPP-9127

**Comment by MikeMcC399** [comment]
PR https://github.com/corona-warn-app/cwa-app-android/pull/3987 is now merged into [release/2.10.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.10.x)

@marcauberer 
PR https://github.com/corona-warn-app/cwa-app-android/pull/3987 however has introduced a regression concerning inconsistent formatting regarding dates of birth.

The date of birth in PersonDetailsFragment_cwa.png in release 2.10 should use the same order of month day year according to the English (United States) locale which is used in the date of sample on the same screen.

Instead of showing the date of birth as 1981/03/20, it should be shown as 03/20/1981. 

I made a note of this in https://github.com/corona-warn-app/cwa-app-android/pull/3987#issuecomment-911518738 but since the PR is merged it may have been overlooked.

---
PersonDetailsFragment_cwa from [release/2.10.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.10.x)

![PersonDetailsFragment_cwa_2 10_dates](https://user-images.githubusercontent.com/66998419/131891755-45dcb0d2-f75f-478e-a830-d09efd4a8409.png)

---
PersonDetailsFragment_cwa from [screenshots 2.8](https://www.coronawarn.app/assets/screenshots/2-8/en/android/PersonDetailsFragment_cwa.png) for comparison. In this version the date formats were fixed and did not use the device's locale settings.

![PersonDetailsFragment_cwa_2 8_dates](https://user-images.githubusercontent.com/66998419/131892032-0f4f0db1-fb25-428e-bac3-75b77f411e12.png)

**Comment by marcauberer** [comment]
@MikeMcC399 since the internal ticket was closed, it maybe would be better if you could open a new issue for that ...

**Comment by MikeMcC399** [comment]
@marcauberer 

>  since the internal ticket was closed, it maybe would be better if you could open a new issue for that ...

Please see new issue https://github.com/corona-warn-app/cwa-app-android/issues/4014.

**Comment by MikeMcC399** [comment]
**Verified fixed**

Screenshots which are generated from `androidTest` from [tag/v2.10.1](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.10.1) in Android Studio use consistent date formats with locale set to English (United States).

Screenshots for the released Android version CWA 2.10.1 published to 
https://www.coronawarn.app/en/screenshots/#android_screenshots have not all been generated from 2.10.1 (e.g. https://www.coronawarn.app/assets/screenshots/2-10/en/android/check_in_attendee_view_contact_journal.png) or even from Android (e.g. https://www.coronawarn.app/en/screenshots/#android_invalid_certificate) so the screenshots section is not a reliable source to verify this fix without comparing to screenshots generated directly from 2.10.1 Android.

The screenshot [PersonDetailsFragment_cwa_2.png](https://www.coronawarn.app/assets/screenshots/2-10/en/android/PersonDetailsFragment_cwa_2.png) which previously showed short (2 digit) and long (4 digit) years on one screen now shows only short years displayed. This is correct.

**Comment by MikeMcC399** [comment]
Closing as fixed! Thanks to @marcauberer!

**Comment by MikeMcC399** [comment]
There is an inconsistency in date formatting in certificates in 2.10.1 with locale set to English (United Kingdom). The problem does not affect English (United States) nor Deutsch (Deutschland).

I will open a separate new issue for this remaining date formatting problem.

**Comment by MikeMcC399** [comment]
New issue https://github.com/corona-warn-app/cwa-app-android/issues/4112 open for the regression of date-of-birth formatting in certificates in version 2.10.1 with locale set to English (United Kingdom).
