### ISSUE TITLE
Rapid Test Profile onboarding not shown after app reset

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#3964]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy A5 (2017) SM-A520F
- Android version: 8.0.0
- App version: 2.7.1 (also in 2.9.0-RC0)

## Describe the bug

After resetting the app no Rapid Test Profile onboarding screen is shown if a profile was created before the app was reset.

## Steps to reproduce the issue

1. Uninstall CWA if already installed.
2. Install CWA
3. Tap "LET'S GET STARTED", tap "NEXT"
4. Tap "DO NOT ACTIVATE" and confirm, tap "NEXT", tap "NEXT"
5. Tap "DO NOT SHARE"
6. Tap "OK"
7. Tap "DO NOT ALLOW" and "OK"
8. Tap "Manage Your Tests"
9. Scroll down and tap on "Create Rapid Test Profile"
10. Note that onboarding appears "You can create a profile ..." (see screenshot below)
11. Tap "CONTINUE"
12. Enter "A" in field "First Name", tap "SAVE"
13. Tap "X", tap "X"
14. Tap three-dot icon > Settings > Reset App and confirm
15. Repeat onboarding steps 3 - 7
16. Repeat steps 8 and 9 to Create Rapid Test Profile
17. Notice this time that no onboarding screen appears. Instead a blank Rapid Test Profile is immediately presented.

![image](https://user-images.githubusercontent.com/66998419/130362788-379c7af5-6979-4dca-a349-9a0ffa9129da.png)

## Expected behavior

After resetting the app the Create Rapid Test Profile onboarding screen should always be shown when accessing this function for the first time after the app is reset.

## Possible Fix

Ensure that resetting the app causes the status of the Create Rapid Test Profile onboarding to be cleared so that it is shown.

**Comment by marcauberer** [comment]
FYI: This issue is addressed by #3970

**Comment by MikeMcC399** [comment]
@marcauberer 

Unfortunately Google has not yet allowed me to access the final 2.9 build from Google Play Store yet, due to the staged rollout. I'm happy in general to verify with the Google Play Store build and then close the issue when I've done so.

In this case you got there before me.

**Comment by MikeMcC399** [comment]
Successfully verified with CWA 2.9.0 on device name: Samsung Galaxy A5 (2017) SM-A520F, Android version: 8.0.0, therefore confirming closure of this issue.

## Steps to verify

1. Uninstall CWA if already installed.
2. Install CWA
3. Tap "LET'S GET STARTED", tap "NEXT"
4. Tap "DO NOT ACTIVATE" and confirm, tap "NEXT", tap "NEXT"
5. Tap "DO NOT SHARE"
6. Tap "OK"
7. Tap "DO NOT ALLOW" and "OK"
8. Tap "Manage Your Tests"
9. Scroll down and tap on "Create Rapid Test Profile"
10. Note that onboarding appears "You can create a profile ..."
11. Tap "CONTINUE"
12. Enter "A" in field "First Name", tap "SAVE"
13. Tap "X", tap "X"
14. Tap three-dot icon > Settings > Reset App and confirm
15. Repeat onboarding steps 3 - 7
16. Repeat steps 8 and 9 to Create Rapid Test Profile
17. Note that onboarding screen correctly appears, as in step 10.

**Comment by dsarkar** [comment]
@MikeMcC399 @PhilippNowak96 Thanks for contributing.
