### ISSUE TITLE
Rapid Test Profile shows mixed languages after change in locale

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#3972]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Google Pixel 3a emulator
- Android version: 11
- First reported on App version: 2.7.1
- Confirmed still present on App version: 2.29.x

## Describe the bug

If the device language is changed, the Rapid Test Profile input view does not  refresh the field prompts.

## Steps to reproduce the issue

(Updated for 2.29.x on Pixel 3a API 33 (Android 13))
1. Settings > System > Languages and input > Languages, set English (United Kingdom)
2. In CWA Status screen, tap "Manage Your Tests"
3. Tap "Rapid Test Profile" (tap Continue if necessary), tap "+ Rapid Test Profiles"
4. Note that all text is in English
5. Without closing CWA, repeat step 1 and change preferred language to Deutsch (Deutschland)
6. View CWA again and note the mixture of languages
7. Tap back arrow
8. Tap "+ Schnelltest-Profil"
9. Now all text, including the field prompts are in German

App at step 6:

![Rapid test profile mixed languages](https://user-images.githubusercontent.com/66998419/130596383-6ccbcd25-9e11-4631-9121-d2101e356fda.png)

## Expected behavior

Android apps are expected to immediately respond to language changes. At step 6 in the steps to reproduce, the app should show only German text as in the following screen shot.

![Rapid Test Profile all German](https://user-images.githubusercontent.com/66998419/130596621-11dbe86c-d0f3-461c-86f2-a046a78a6ae1.png)

## Additional information

Thanks to feedback from @PhilippNowak96 who identified that this is an issue of TextInputLayout in the Material Components, see: issue material-components/material-components-android#2075. 

The Material Components issue is now closed through https://github.com/material-components/material-components-android/commit/051410b7efc089e50e7f83db9a922258e2ba359e. Material Components for Android [1.7.0](https://github.com/material-components/material-components-android/releases/tag/1.7.0) is supposed to fix this issue.

---
Internal Tracking ID: [EXPOSUREAPP-9151](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9151)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks. Internal Tracking ID: EXPOSUREAPP-9151

@Ein-Tim Actually I can observe something similar on iOS. The country list when checking a DCC is in English, although the phone locale is set to DE. No way to get it to German back. iPhone 6s.

**Comment by MikeMcC399** [comment]
@dsarkar 
> Actually I can observe something similar on iOS. The country list when checking a DCC is in English, although the phone locale is set to DE. No way to get it to German back. iPhone 6s.

That is an entirely different problem. Perhaps you should submit an issue in the iOS repository? It doesn't belong here at all. I checked by the way on Android, and Android correctly provides the list of countries in German, but this is not related to the Rapid Test Profile in any way.

**Comment by Ein-Tim** [comment]
@dsarkar 

I will open an issue regarding this!

**Comment by PhilippNowak96** [comment]
This seems to be an issue of TextInputLayout in the Material Components, see: https://github.com/material-components/material-components-android/issues/2075

**Comment by MikeMcC399** [comment]
@PhilippNowak96 

Thanks for uncovering that issue (https://github.com/material-components/material-components-android/issues/2075)!

The standard Android elements `TextView` and `Button` refresh correctly. Everything else (which doesn't refresh correctly) is from `com.google.android.material.textfield` 😞.

**Comment by MikeMcC399** [comment]
- The underlying issue https://github.com/material-components/material-components-android/issues/2075 still has the label "Needs Investigation"
- This issue is a corner case because most users will not be changing the phone locale with CWA active

Closing as low impact and unsolved, due to the external component [Material Components for Android (MDC-Android)](https://github.com/material-components/material-components-android).

**Comment by MikeMcC399** [comment]
https://github.com/material-components/material-components-android/issues/2075 is now closed with a fix, however there is not yet a new release of [Material Components for Android (MDC-Android)](https://github.com/material-components/material-components-android) containing this fix.

The upcoming CWA release 2.24.x is configured with
`implementation 'com.google.android.material:material:1.6.0'`

Judging by the progress in the https://github.com/material-components/material-components-android/ repository, the fix looks like it might be released with a `material` 1.7.x version.

**Comment by MikeMcC399** [comment]
Material Components for Android [1.7.0-alpha03](https://github.com/material-components/material-components-android/releases/tag/1.7.0-alpha03) addresses this issue. 

[1.7.0-alpha03](https://github.com/material-components/material-components-android/releases/tag/1.7.0-alpha03) requires a minimum `compileSdkVersion` and `targetSdkVersion` version 32 which makes it currently incompatible with [release/2.25.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.25.x). The CWA Android 2.25.x branch is currently on version 31 of `compileSdkVersion` and `targetSdkVersion`. The app builds successfully after updating to version 32.

Updating `implementation 'com.google.android.material:material:1.6.0'` to `implementation 'com.google.android.material:material:1.7.0-alpha03'` however produces fatal build errors, which would need investigation.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks, forwarded to internal ticket.

**Comment by MikeMcC399** [comment]
Re-opening this issue, since it still occurs and an official fix is now available.

[Material Components for Android (MDC-Android)](https://github.com/material-components/material-components-android) has now made [Release 1.7.0](https://github.com/material-components/material-components-android/releases/tag/1.7.0) available which enables this CWA issue to be resolved without using an `alpha` or `rc` release.

Perhaps there is scope in a future CWA version to incorporate this fix?

The official prerequisites however still include:
`compileSdkVersion and targetSdkVersion 32` 

This is not currently met by the 2.29 branch:
https://github.com/corona-warn-app/cwa-app-android/blob/f13b188160970d5553038befc2aaa3a47e345272/Corona-Warn-App/build.gradle#L30-L35

**Comment by dsarkar** [comment]
Good morning @MikeMcC399! I will re-open the internal ticket and forward your findings! Thanks!

**Comment by dsarkar** [comment]
@MikeMcC399 FYI PR https://github.com/corona-warn-app/cwa-app-android/pull/5668

**Comment by MikeMcC399** [comment]
- I tested PR #5668 and it solves the issue 👍🏻

**Comment by MikeMcC399** [comment]
@dsarkar 

Is it still planned to have a 2.29 release? It seems that the 2.29.x milestone has been renamed to 3.0.x.

**Comment by MikeMcC399** [comment]
The label https://github.com/corona-warn-app/cwa-app-android/labels/Fix%203%2e0 has been edited, however the text hasn't been changed, so it is out of sync.

![image](https://user-images.githubusercontent.com/66998419/206541822-dba8f03e-a394-4dd7-ae85-24845552ff6f.png)

Please check and correct in the https://github.com/corona-warn-app/cwa-app-android/labels list.

**Comment by larswmh** [comment]
@MikeMcC399 

> The label [ Fix 3.0](https://github.com/corona-warn-app/cwa-app-android/labels/Fix%203%2e0) Fix is planned for 2.29 has been edited, however the text hasn't been changed, so it is out of sync.
> 
> ![image](https://user-images.githubusercontent.com/66998419/206541822-dba8f03e-a394-4dd7-ae85-24845552ff6f.png)
> 
> Please check and correct in the https://github.com/corona-warn-app/cwa-app-android/labels list.

The label description has been changed now, thanks for the hint
