### ISSUE TITLE
Transposed "Max, Mustermann" in screenshots

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#3994]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue
This issue is partially mentioned in https://github.com/corona-warn-app/cwa-app-android/issues/3926.

## Technical details

- Device name: Samsung Galaxy A52 5G SM-A526B/DS
- Android version: 11
- App version: 2.7.1, 2.8.0, 2.9.0-RC1 (pre-release)

## Describe the bug

Screenshots generated by
`RecoveryCertificateDetailFragmentTest.kt` and 
`VaccinationDetailsFragmentTest.kt`
render the example name as "Max, Mustermann", where Name and First Name are transposed.

![max mustermann](https://user-images.githubusercontent.com/66998419/131213846-2fa5bc75-f451-427d-9e29-97816a49f765.png)

for example:
`RecoveryCertificateDetailsFragment_recovered.png`
- https://www.coronawarn.app/assets/screenshots/2-7/en/android/VaccinationDetailsFragment_immune.png
- https://www.coronawarn.app/assets/screenshots/2-8/en/android/VaccinationDetailsFragment_immune.png

`VaccinationDetailsFragment_expired.png`
- https://www.coronawarn.app/assets/screenshots/2-7/en/android/RecoveryCertificateDetailsFragment_recovered.png
- https://www.coronawarn.app/assets/screenshots/2-8/en/android/RecoveryCertificateDetailsFragment_recovered.png

Incorrect screenshots are currently also contained in the draft PR https://github.com/corona-warn-app/cwa-website/pull/1668 "Android Screenshots for Version: 2.9.0" for later publishing to https://www.coronawarn.app/en/screenshots/ when 2.9.x is released.

## Steps to reproduce the issue

In CWA:
1. Tap "Certificates" tab on Start Screen (tap "CONTINUE" if prompted)
2. Tap "+ CERTIFICATE"
3. Scan a valid vaccination certificate
4. Check that the name under "Name, Vorname / Name, First Name" is rendered in that order

In Android Studio:
1. Run RecoveryCertificateDetailFragmentTest.kt
2. Run VaccinationDetailsFragmentTest.kt
3. View > Tools Windows > Device File Explorer
4. Go to /data/data/de.rki.coronawarnapp.test/screenshots
5. Note that example name is incorrectly rendered as "Max, Mustermann"

## Expected behavior

From CWA Android 2.7 onwards the formatting of the name was corrected for  regular app usage, so screenshots should show the example name as "Mustermann, Max".

## Possible Fix

In `RecoveryCertificateDetailFragmentTest.kt` and in `VaccinationDetailsFragmentTest.kt`

change
`every { fullNameFormatted } returns "Max, Mustermann"`
to
`every { fullNameFormatted } returns "Mustermann, Max"`

## Additional context

Issue https://github.com/corona-warn-app/cwa-app-android/issues/3692 "Vaccination Details Screen: Firstname Surname in wrong order" was fixed through PR https://github.com/corona-warn-app/cwa-app-android/pull/3826 which fixed the issue in CWA Android 2.7. for:
- Recovery Certificates
- Test Certificates
- Vaccination Certificates

---
Internal Tracking ID: [EXPOSUREAPP-9233](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9233)

**Comment by MikeMcC399** [comment]
Please let me know if you would like a PR to correct this issue.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks. I Will get back to about the PR. Internal Tracking ID: EXPOSUREAPP-9233

**Comment by dsarkar** [comment]
@MikeMcC399 Feedback from dev: 

> "That is fine, we can accept such PR "

**Comment by MikeMcC399** [comment]
Draft PR #3997 is created. I want to add screenshots before submitting for review.

**Comment by MikeMcC399** [comment]
Screenshots of changed files now added to PR #3997 for verification.

**Comment by MikeMcC399** [comment]
PR https://github.com/corona-warn-app/cwa-app-android/pull/3997 
"Correct to "Mustermann, Max" in certificate screenshots (EXPOSUREAPP-9233) (COMMUNITY)"  is merged and included in [v2.9.0-RC1](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.9.0-RC1), ready for release with version 2.9.

**Comment by dsarkar** [comment]
@MikeMcC399 Thank you for the contribution!

**Comment by MikeMcC399** [comment]
The issue has been corrected for Android screenshots for CWA 2.9 published today, Sept 8, 2021, for example:

- https://www.coronawarn.app/assets/screenshots/2-9/en/android/VaccinationDetailsFragment_immune.png
- https://www.coronawarn.app/assets/screenshots/2-9/en/android/RecoveryCertificateDetailsFragment_recovered.png

and for future version screenshots.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for confirming the fix. Forwarded to internal ticket.
