### ISSUE TITLE
Regression in date of birth formatting

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#4014]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue
Follow on report from https://github.com/corona-warn-app/cwa-app-android/issues/3963#issuecomment-911924812 and https://github.com/corona-warn-app/cwa-app-android/pull/3987

## Technical details

- Android version: 11
- App version: 2.10.0-RC2 (pre-release version)

## Describe the bug

PR https://github.com/corona-warn-app/cwa-app-android/pull/3987 has introduced a regression concerning inconsistent formatting regarding dates of birth.

For example, the date of birth in PersonDetailsFragment_cwa.png in release 2.10 should use the same order of month day year according to the English (United States) locale which is used in the date of sample on the same screen.

Instead of showing the date of birth as 1981/03/20, it should be shown as 03/20/1981. 

---
[PersonDetailsFragment_cwa from release/2.10.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.10.x)

![PersonDetailsFragment_cwa_2 10_dates](https://user-images.githubusercontent.com/66998419/131891755-45dcb0d2-f75f-478e-a830-d09efd4a8409.png)

---
[PersonDetailsFragment_cwa from screenshots 2.8](https://www.coronawarn.app/assets/screenshots/2-8/en/android/PersonDetailsFragment_cwa.png) for comparison. In this version the date formats were fixed and did not use the device's locale settings.

![PersonDetailsFragment_cwa_2 8_dates](https://user-images.githubusercontent.com/66998419/131892032-0f4f0db1-fb25-428e-bac3-75b77f411e12.png)

## Steps to reproduce the issue

1. Settings > System > Languages and input > Languages<br>set to English (United States)
2. Settings > System > Date & time<br>select "Use locale default"/ disable "Use 24-hour format"
3. Connect mobile device to Android Studio
4. In Android Studio Build > Select BuildVariant deviceForTestersDebug
5. run `src/androidTest/java/de/rki/coronawarnapp` on emulator
6. View > Tools Windows > Device File Explorer
7. Go to `/data/data/de.rki.coronawarnapp.test/screenshots`
8. View screenshots and check the formatting of all dates of birth

## Expected behavior

Dates of birth should be formatted according to the device's locale setting, except in certificates where a field label indicates formatting using YYYY-MM-DD. 

---
Internal Tracking ID: [EXPOSUREAPP-9297](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9297)

**Comment by MikeMcC399** [comment]
@marcauberer 
This is the new issue, as you requested.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for opening a separate issue: Internal Tracking ID: [EXPOSUREAPP-9297](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9297).

**Comment by marcauberer** [comment]
@MikeMcC399 new pr is open.
Would be nice, if you could take a look at the screenshots and report back to me if the bug is solved. Thank you!

**Comment by MikeMcC399** [comment]
@marcauberer 
I'll be happy to check the screenshots, however currently on this branch and on release/2.10.x screenshot generation fails at PersonDetailsFragmentTest.kt 
`io.mockk.MockKException: no answer found for: TestCertificate(#41)`

I will try to find out if I can go back to a commit in release/2.10.x where it still works.

**Comment by mtwalli** [comment]
it is already verified by @MikeMcC399  and can be closed

**Comment by MikeMcC399** [comment]
Successfully verified in branch [release/2.10.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.10.x) at commit https://github.com/corona-warn-app/cwa-app-android/commit/b2a35fbef27c2c9f2b6870a0592ad031d9e5a10e.

## Steps to verify

Pixel 3a API 30 (Android 11) emulator

1. Settings > System > Languages and input > Languages<br>set to English (United States)
2. Settings > System > Date & time<br>select "Use locale default"/ disable "Use 24-hour format"
3. Connect mobile device to Android Studio
4. In Android Studio Build > Select BuildVariant deviceForTestersDebug
5. run `PersonDetailsFragmentTest.kt` on emulator
6. View > Tools Windows > Device File Explorer
7. Go to `/data/data/de.rki.coronawarnapp.test/screenshots`
8. View screenshots and check the formatting of all dates of birth in PersonDetailsFragment*.png

![image](https://user-images.githubusercontent.com/66998419/132659809-4d218784-72fa-4f77-9f88-54e3cfa57561.png)


Now closing, since the regression was only present in an unreleased version and the issue is fixed.

**Comment by MikeMcC399** [comment]
@marcauberer 
PR https://github.com/corona-warn-app/cwa-app-android/pull/4036 did not fix formatting the date-of-birth in certificates for locale English (United Kingdom). At the time that I closed this issue (https://github.com/corona-warn-app/cwa-app-android/issues/4014) I only verified on locale English (United States).

Since PR https://github.com/corona-warn-app/cwa-app-android/pull/4036 has been released and CWA 2.10.1 has been released I have opened a new issue https://github.com/corona-warn-app/cwa-app-android/issues/4112 to follow up on this regression.

I will not re-open (https://github.com/corona-warn-app/cwa-app-android/issues/4014).

**Comment by dsarkar** [comment]
@MikeMcC399 I forwarded your comment into the new internal ticket.
