### ISSUE TITLE
Implausible screenshot certificate technical expiration dates

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#4018]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device: Android Tablet for screenshot capture
- First reported on App version: 2.9.0 
- Reviewed as not yet fixed in App version: 2.26.0-RC1
- Android version: 11

## Describe the bug

Certificate screenshots shown on https://www.coronawarn.app/en/screenshots/ use implausible and expired technical expiry dates in the past.

https://www.coronawarn.app/en/screenshots/#android_test_certificate:

- [TestCertificateDetailsFragment__2.png](https://www.coronawarn.app/assets/screenshots/2-25/en/android/TestCertificateDetailsFragment__2.png) shows a Technical Expiration Date of 5/12/21, 7:00 PM

https://www.coronawarn.app/en/screenshots/#android_vaccination_certificate:

- [VaccinationDetailsFragment_immune_2.png](https://www.coronawarn.app/assets/screenshots/2-25/en/android/VaccinationDetailsFragment_immune_2.png) shows a Technical Expiration Date of 5/15/21, 5:00 PM

https://www.coronawarn.app/en/screenshots/#android_recovery_certificate:

- [RecoveryCertificateDetailsFragment_recovered_2.png](https://www.coronawarn.app/assets/screenshots/2-25/en/android/RecoveryCertificateDetailsFragment_recovered_2.png) shows a Technical Expiration Date of 6/22/22, 7:13 AM

Edit: Links and dates/times updated for CWA 2.25.0

## Steps to reproduce the issue

(Set device to small font to capture complete certificate)

1. In Android Studio 
2. Run TestCertificateDetailsFragmentTest.kt
3. Run VaccinationDetailsFragmentTest.kt
4. Run RecoveryCertificateDetailFragmentTest.kt
5. View > Tools Windows > Device File Explorer
6. Go to /data/data/de.rki.coronawarnapp.test/screenshots
7. View screenshots

## Expected behavior

According to https://www.coronawarn.app/en/faq/#eu_dcc "Currently, in Germany, the digital vaccination, test and recovery certificates of the EU are usually issued with a technical validity of one year from the date of issue."

EU Digital COVID Certificates were not introduced until mid 2021 (see https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/safe-covid-19-vaccines-europeans/eu-digital-covid-certificate_en#timeline), so if the technical validity is one year, then none of the certificates can have a technical expiration date before mid 2022.

Pharmacies started to issue vaccination certificates on Monday, June 14, 2021 (see https://www.abda.de/aktuelles-und-presse/pressemitteilungen/).

Although the published screenshots do not show other certificate details, if screenshots are captured on a tablet with small font size, it can be seen that the expiration date is also inconsistent with the corresponding event.

Dates and times below from 2.26.0-RC1:

File | Event | Technical Expiration | Duration of Validity
--- | --- | --- | ---
TestCertificate | 12.05.2021 19:00 | 5/12/21, 7:00 PM | 0 minutes!
VaccinationCertificate | 2021-02-18 | 5/16/21, 2:00 AM | 3 months!
RecoveryCertificate | 2021-05-24 |  Current date and time | > 1 year!

## Possible Fix

Ensure that the technical expiration date for certificate screenshots corresponds to real use certificates.

----
Internal Tracking-ID: [EXPOSUREAPP-9299](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9299)

**Comment by heinezen** [comment]
Hey @MikeMcC399 ,

Thank you for your report. We have notified the dev team about the issue. They will look into it now.

----
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@MikeMcC399 This issue seems fixed. Non of the screenshot paragraphs you mention still show a screenshot with a technical expiration date.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> This issue seems fixed. 

The issue only looks fixed if you inspect the current screenshots on the website, however these screenshots do not show the whole of the certificate so the problem is still there, but it is hidden.

The way to check for the underlying problem is to go through the steps to reproduce with a tablet for instance.

The test certificate date and time of expiry is exactly the same as the date and time of sample collection. This is an implausible example because the test certificate is never valid if the length of time of validity is 0 minutes.

![TestCertificateDetailsFragment_expired_2](https://user-images.githubusercontent.com/66998419/175236693-baaa40e3-2d87-43ed-87ab-b00c6fb79f21.png)

**Comment by MikeMcC399** [comment]
- PR #5461 resolves this issue. Each of the certificate screenshots has a [technical validity](https://www.coronawarn.app/en/faq/results/#glossary_technical_validity) of one year:

Dates and times below from 2.27.0-RC0 (https://github.com/corona-warn-app/cwa-app-android/commit/7710cc9c73593716952e9f9143699bae72147194):

File | Event | Technical Expiration | Duration of Validity
--- | --- | --- | ---
TestCertificate | 12.05.2021 19:00 | 5/12/22, 7:00 PM | 1 year
VaccinationCertificate | 2021-02-18 | 2/18/22, 3:00 PM | 1 year
RecoveryCertificate | 2021-05-24 | 5/24/22 3:00 PM | 1 year

**Comment by MikeMcC399** [comment]
This issue has been fixed, so any related screenshots which are generated in advance for the 2.27 should be correct. Closing therefore.
