### ISSUE TITLE
Test certificate screenshot wrong content

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#4019]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Google Pixel 3a emulator
- Android version: 11
- App version: 2.9.0-RC2 (and 2.10.0-RC2)

## Describe the bug

The screenshot [TestCertificateDetailsFragment.png](https://github.com/corona-warn-app/cwa-website/blob/admin/Android-screenshots-for-version-2.9.0/src/assets/img/screenshots/en/android/TestCertificateDetailsFragment.png) included in PR https://github.com/corona-warn-app/cwa-website/pull/1668 and website branch [admin/Android-screenshots-for-version-2.9.0](https://github.com/corona-warn-app/cwa-website/tree/admin/Android-screenshots-for-version-2.9.0) is missing the actual test certificate. In fact it is not a screenshot from the Certificates tab, but appears to be from "Planning an event?" / "CREATE QR CODE".

![TestCertificateDetailsFragment 2 9 0-RC2](https://user-images.githubusercontent.com/66998419/132124481-54d95a9a-b216-4512-839b-33b926a79998.png)

If the full `androidTest` set is run the screenshot is incorrect. If however the individual `TestCertificateDetailsFragmentTest.kt` test module is run, then the screenshot is generated correctly.

This is a regression from CWA version 2.8.0.

### View existing certificates

1. Open [TestCertificateDetailsFragment.png](https://github.com/corona-warn-app/cwa-website/blob/admin/Android-screenshots-for-version-2.9.0/src/assets/img/screenshots/de/android/TestCertificateDetailsFragment.png) for CWA Android 2.9.0-RC2 (see above screenshot)
2. Compare to published [TestCertificateDetailsFragment.png](https://www.coronawarn.app/assets/screenshots/2-8/en/android/TestCertificateDetailsFragment.png) for CWA Android 2.8.0.

![TestCertificateDetailsFragment 2 8 0](https://user-images.githubusercontent.com/66998419/132123854-96c7d882-32c0-4fcb-aaf7-d73cdec538f8.png)

### Regenerate screenshot

1. In Android Studio
2. Run complete `src/androidTest/java/de/rki/coronawarnapp`
3. View > Tools Windows > Device File Explorer
4. Go to `/data/data/de.rki.coronawarnapp.test/screenshots`
5. Open `TestCertificateDetailsFragment.png` and note that certificate is missing
6. Run single test module `TestCertificateDetailsFragmentTest.kt`
7. View > Tools Windows > Device File Explorer
8. Go to `/data/data/de.rki.coronawarnapp.test/screenshots` and Synchronize
9. Open `TestCertificateDetailsFragment.png` and note that certificate is present including a QR code

## Expected behavior

[TestCertificateDetailsFragment.png](https://github.com/corona-warn-app/cwa-website/blob/admin/Android-screenshots-for-version-2.9.0/src/assets/img/screenshots/de/android/TestCertificateDetailsFragment.png) for CWA Android 2.9.0-RC2 should show a certificate with QR code like [TestCertificateDetailsFragment.png](https://www.coronawarn.app/assets/screenshots/2-8/en/android/TestCertificateDetailsFragment.png) for CWA Android 2.8.0 when the complete `androidTest` set is run to generate all screenshots for the app.

----
Internal Tracking-ID: [EXPOSUREAPP-9302](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9302)

**Comment by heinezen** [comment]
Thanks for checking @MikeMcC399 . I've brought this to the attention of the dev team.

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
The issue is being fixed in PR #4026. Knowing the solution, here are simplified steps to reproduce:

### Steps to reproduce

In release/2.9.x

1. In Android Studio
2. Run single test module `TestCertificateDetailsFragmentTest.kt`
3. View > Tools Windows > Device File Explorer
4. Go to `/data/data/de.rki.coronawarnapp.test/screenshots`
5. Open `TestCertificateDetailsFragment.png` and note that certificate is present including a QR code
6. Run single test module `TraceLocationsFragmentTest.kt`
7. View > Tools Windows > Device File Explorer
8. Go to `/data/data/de.rki.coronawarnapp.test/screenshots` and synchronize
9. Open `TestCertificateDetailsFragment.png` and note that contents have been incorrectly overwritten. The screenshot shows "My QR Codes" at the top

**Comment by mtwalli** [comment]
it can be closed, it is already fixed

**Comment by MikeMcC399** [comment]
Successfully verified in branch [release/2.10.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.10.x) at commit https://github.com/corona-warn-app/cwa-app-android/commit/b2a35fbef27c2c9f2b6870a0592ad031d9e5a10e.

## Steps to verify

Use physical Android 11 smartphone

1. In Android Studio
2. Run complete `src/androidTest/java/de/rki/coronawarnapp`
3. View > Tools Windows > Device File Explorer
4. Go to `/data/data/de.rki.coronawarnapp.test/screenshots`
5. Open `TestCertificateDetailsFragment.png` and check that it contains an image of a test certificate

![image](https://user-images.githubusercontent.com/66998419/132668425-e56701a5-5fa0-4616-9420-7ac2ab11fd22.png)

This issue is fixed and does not affect the app installed by end-users. It only has an influence on the screenshots on https://www.coronawarn.app/en/screenshots/, so now closing.
