### ISSUE TITLE
UpdateChecker - Update forced if signature incorrect

### ISSUE THREAD

**Issue by SecJoe** [corona-warn-app/cwa-app-android#402]
## Current Implementation
In UpdateChecker.kt at line 28-37 there are two exceptions which can occur while checking if an update is needed from the CDN-Server. 
* The first general Exception can be triggered almost all cases,ie. if the zip-config can not be extracted, networking error. In this case, the user will not be forced to update.
* The second exception will be triggered if the signature file in the zip file is not correct (hasInvalidSignature==true). In this case the user will be **forced to update** because the function which catches the ApplicationConfigurationCorruptException returns true.

Also insecure TLS versions are used for this CDN-Connection (TLS 1-0 - 1.3). In my opinion all public TLS attacks (BEAST, POODLE; FREAK...) only affect the confidentiality of an packet, but in case if an attacker can also tamper with the integrity of an packet (breaking the TLS MAC protection) resulting of an invalid signature, an **update force loop** can be achieved. Then a user follows the PlayStore link but can not find any new version if he has already the current version. So this (i know very theoretical) attack can make the app unusable for some time. Also the same problem occurs if the signature on the CDN server is calculated incorrect because of some technical/administration problem on the server.

## Suggested Enhancement
Change line 33 to false

## Expected Benefits
App is more stable and secure.

Additional Question: There is a comment in the ServiceFactory (getCDNSpecs) that TLS 1.0 - 1.3 and all Cipher Suites are enabled for compatibility reasons. If a t-online server is used as CDN, could you adapt it to the current BSI TLS recommendations?

Internal Tracking ID: EXPOSUREAPP-1869

**Comment by mtwalli** [comment]
Not planned
