### ISSUE TITLE
Android certificate screenshots have non-certificate QR codes

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#4021]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device: Tablet
- First reported on App version: 2.8.0
- Reviewed as not yet fixed in App version: 2.17.2
- Android version: 11

## Describe the bug

Android certificate screenshots shown on https://www.coronawarn.app/en/screenshots/, for instance [Android Vaccination Certificate](https://www.coronawarn.app/en/screenshots/#android_vaccination_certificate) show QR codes which are not EU digital COVID certificate QR codes and which cannot therefore match the details of the screenshot.

![image](https://user-images.githubusercontent.com/66998419/132088521-e0e177a9-203e-4b81-a91a-78c94e188601.png)

### Generate screenshots

(Set device to small font to capture complete certificate)

1. In Android Studio 
2. Run `TestCertificateDetailsFragmentTest.kt`
3. Run `VaccinationDetailsFragmentTest.kt`
4. Run `RecoveryCertificateDetailFragmentTest.kt`
5. View > Tools Windows > Device File Explorer
6. Go to `/data/data/de.rki.coronawarnapp.test/screenshots`
7. View screenshots

### Scan screenshots

Scan from [website](https://www.coronawarn.app/en/screenshots/) for the current CWA version. For future versions scan from generated screenshots (see above).

1. Using another device, open CWA
2. Tap scan button
3. Scan QR Code from [TestCertificateDetailsFragment.png](https://www.coronawarn.app/assets/screenshots/2-15/en/android/TestCertificateDetailsFragment.png)
4. Note error "No Suitable QR Code"
5. Repeat for [VaccinationDetailsFragment_immune.png](https://www.coronawarn.app/assets/screenshots/2-15/en/android/VaccinationDetailsFragment_immune.png) and for [RecoveryCertificateDetailsFragment_recovered.png](https://www.coronawarn.app/assets/screenshots/2-15/en/android/RecoveryCertificateDetailsFragment_recovered.png)

## Expected behavior

Certificate screenshots should include a QR code which has the correct structure of a EU digital COVID certificate and which matches the details of the certificate displayed, even if the certificate is not signed.

## Possible Fix

Modify [ScreenshotCertificateTestData.kt](https://github.com/corona-warn-app/cwa-app-android/blob/main/Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/ScreenshotCertificateTestData.kt) to provide correct QR codes instead of using wrong identical dummy data for recovery, test and vaccination certificates.

----
Internal Tracking-ID: [EXPOSUREAPP-9301](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9301)

**Comment by mtwalli** [comment]
@MikeMcC399  This is intended, why do you need to a certificate QrCode ? at the end this is just screenshot for demonstration.

**Comment by MikeMcC399** [comment]
@mtwalli 
> This is intended, why do you need to display a certificate QrCode ? at the end this is just screenshot for demonstration.

That is a valid question. The app should try to achieve consistency between Android and iOS including the screenshots. Seemingly arbitrary differences in the development on the two platforms make providing support and writing FAQ articles more complicated. For instance, the example vaccination certificate screenshot on Android for Max Mustermann is not shown completely whereas on iOS it is for Andrea Schneider and it is shown completely. See https://github.com/corona-warn-app/cwa-app-android/issues/4017.

It is true though that the iOS QR code https://www.coronawarn.app/en/screenshots/#ios_vaccination_certificate can't be read successfully in CWA 2.7 onwards, since it is not a signed certificate. On Android the QR code can't be read because it is just not a certificate at all. So there may not be any practical benefit to adding proper certificate QR codes to Android if they won't be signed and therefore can't be read by current app versions.

I will leave this issue open for comment for the moment. If the Open Source Team considers it not worth fixing then please add the [wontfix](https://github.com/corona-warn-app/cwa-app-android/labels/wontfix) label and close it.

**Comment by heinezen** [comment]
@MikeMcC399 I've made a Jira ticket just in case, so the issue doesn't get lost.

----
Corona-Warn-App Open Source Team

**Comment by mtwalli** [comment]
Intended behaviour
