### ISSUE TITLE
Abuse Covid Test Verification

### ISSUE THREAD

**Issue by horbix28** [corona-warn-app/cwa-app-android#4051]
I noticed that you can easily abuse the function of storing a negative Covid 19 test in the app.  Apparently, after the test has been added, the test validity is only set to the Android system time.  Thus, the time can be set as you like, which was probably not intended that way. I don't know how this can be solved but I've think this should not be possible this way.

**Comment by Ein-Tim** [comment]
Same as #3682?

**Comment by horbix28** [comment]
Okay sorry didn't nocticed that. Thanks for the information.
