### ISSUE TITLE
Datenspende Einverständnis deutsch with toggle wrong text

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#4056]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug affects Android only (assumed)
* [X] Bug is not already reported in another issue
Related to closed issue "Mismatch between Consent legal text and "Share Data" button" https://github.com/corona-warn-app/cwa-documentation/issues/538.

## Technical details

- Device name: Pixel 3a Emulator
- iOS/Android version: Android 11
- Reported on App version: 2.9.0
- Validated not yet fixed on App version: 2.10.1 and [release/2.11.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.11.x) (commit https://github.com/corona-warn-app/cwa-app-android/commit/8eeb2f79b3f6c7cf7c92c7d370480041c02b1034 2.11.0-RC2)

## Describe the bug

When accessing "Datenspende" through "Einstellungen" the help text is for onboarding, where there is a button called "Einverstanden" available. There is no button called "Einverstanden" available after onboarding has taken place so in that case the text which refers the button "Einverstanden", which isn't shown, is wrong. This affects the German UI. The English UI is correct.

## Steps to reproduce the issue

Set language to Deutsch (Deutschland)

1. Install and open CWA
2. Start onboarding "LOS GEHT'S"
3. During onboarding at "Datenspende" select "NICHT EINVERSTANDEN"
4. Complete onboarding selections
5. Tap three-dot symbol, tap "Einstellungen"
6. Tap "Datenspende"
7. Note the toggle switch "Datenspende" coupled with the text "Durch Antippen von "Einverstanden", willigen Sie ein:"

![image](https://user-images.githubusercontent.com/66998419/133096457-7e62f484-2c70-4ebc-91a6-643562354df9.png)

## Expected behavior

The text displayed when "Datenspende" is selected from "Einstellungen" after onboarding has taken place should refer to the toggle switch shown.

## Possible Fix

In release/2.9.x https://github.com/corona-warn-app/cwa-app-android/blob/8e44a7e1b674902282ff093be88c5879a097dbeb/Corona-Warn-App/src/main/res/values-de/legal_strings.xml#L92-L93

"Durch Antippen von „Einverstanden“, willigen Sie ein: ..."

is incorrect. 

The English text in 
https://github.com/corona-warn-app/cwa-app-android/blob/8e44a7e1b674902282ff093be88c5879a097dbeb/Corona-Warn-App/src/main/res/values/legal_strings.xml#L91-L92

"By enabling “Share Data” above, you consent to the following: ..."

is however correct, so if this text is translated to German and placed in 
`<string name="ppa_settings_privacy_information_body">` of https://github.com/corona-warn-app/cwa-app-android/blob/main/Corona-Warn-App/src/main/res/values-de/legal_strings.xml the issue would be solved.

---
Internal Tracking ID: [EXPOSUREAPP-9657](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9657)

**Comment by Ein-Tim** [comment]
> Bug affects Android only (assumed)

Confirm, this is not a problem under iOS.

**Comment by MikeMcC399** [comment]
@dsarkar 
This problem has not been fixed in 2.10.1.
Perhaps the text could be corrected in time for the 2.11 release?

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-9657](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9657)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for reporting. @Ein-Tim Thanks for confirming iOS not being affected.

**Comment by dsarkar** [comment]
@MikeMcC399 FYI PR is created  https://github.com/corona-warn-app/cwa-app-android/pull/4126

**Comment by MikeMcC399** [comment]
@dsarkar 
> FYI PR is created #4126

Thanks for the heads-up! I've checked it out and it solves the issue.

**Comment by MikeMcC399** [comment]
Confirmed fixed in CWA Android 2.11.2 released version.
