### ISSUE TITLE
Math.random is deprecated 

### ISSUE THREAD

**Issue by MarcSchoenefeld** [corona-warn-app/cwa-app-android#406]
According to [1] the use of Math.random, such as in [2]  is deprecated. 
[1] https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.js/-math/random.html

[2] https://github.com/corona-warn-app/cwa-app-android/blob/970e8b859cff3c8beeca83ac83e9ed534927107a/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/WebRequestBuilder.kt#L183

**Comment by jakobmoellersap** [comment]
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.js/ please be aware that this is the JS based kotlin

**Comment by jakobmoellersap** [comment]
https://developer.android.com/reference/java/lang/Math since we use this Math implementation that is not deprecated to my knowledge I will close this issue.

**Comment by LostMekka** [comment]
Just a question following up: `Math.random().toInt().toString()` is always `"0"`. What is the point of this line?

**Comment by LostMekka** [comment]
Since this question is not directly related to the issue discussed here, I created a separate question issue :)
