### ISSUE TITLE
Offer creation of a start screen link to a specific certificate

### ISSUE THREAD

**Issue by lintux** [corona-warn-app/cwa-app-android#4070]
When a specific Certificate within the App is displayed, offer the creation of a start screen link to this certificate.
Tapping on this Link, the referenced certificate will be directly opened and shown in the app.
Benefit is that this shortcut saves several steps, when the Certificate needs to be shown for verification:
Open the App --> Tap on the Certificate Button --> Scroll to the right certificate (if you have more than your own on the mobile) --> open the certificate.

**Comment by pljakobs** [comment]
+1
Extra points for a start screen widget showing the certificate.
I guess it would be good if the certificate would only. E displayed once tapped so it cannot be "stolen" by photographing the phone

**Comment by crosser** [comment]
A possible (simpler?) alternative is to add a static shortcut that opens the "active" certificate.

**Comment by silas229** [comment]
Amy updates? It should be easy to implement the [shortcut](https://developer.android.com/guide/topics/ui/shortcuts) mentioned by @crosser. A shortcut to add a journal entry already exists.

**Comment by mtwalli** [comment]
Not planned
