### ISSUE TITLE
RKI misspelled in RecoveryCertificate screenshots

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#4071]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Tablet
- Android version: 11
- App version: 2.9.0 and 2.10.0-RC1 pre-release version

## Describe the bug

Screenshots 
- `RecoveryCertificateDetailsFragment_recovered_2.png` and
- `RecoveryCertificateDetailsFragment_recovered_expired_2.png`

contain the misspelled authority name "Robert-Koch-Institut" in the field "Zertifikataussteller / Certificate Issuer".

Note that the error is not apparent on https://www.coronawarn.app/en/screenshots/#android_recovery_certificate because the screenshots only show the top and bottom of the certificate, not the middle.
    
## Steps to reproduce the issue

In Android Studio
1. Connect to larger display, such as a tablet
2. Run `RecoveryCertificateDetailFragmentTest.kt`
3. View screenshots in `/data/data/de.rki.coronawarnapp.test/screenshots`

![RecoveryCertificateDetailsFragment_RKI_misspelling](https://user-images.githubusercontent.com/66998419/133304621-b15ddcfe-6ac5-465e-bad0-77eee4e25cab.png)

## Expected behavior

The authority should be spelled
"Robert Koch-Institut" with only one hyphen.

The website https://www.rki.de/DE/Service/Impressum/impressum_node.html is the reference location for the correct spelling of "Robert Koch-Institut" (RKI)

## Possible Fix

In https://github.com/corona-warn-app/cwa-app-android/blob/127889b390ef00228a619afb7573c5da724a1a6e/Corona-Warn-App/src/androidTest/java/de/rki/coronawarnapp/covidcertificate/recovery/ui/RecoveryCertificateDetailFragmentTest.kt#L125
correct spelling to "Robert Koch-Institut".

---
Internal Tracking ID: [EXPOSUREAPP-9452](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9452)

**Comment by MikeMcC399** [comment]
I can submit a PR for this change if you tell me to.

**Comment by marcauberer** [comment]
@MikeMcC399 feel free to do so 👍🏼

**Comment by MikeMcC399** [comment]
PR #4073 submitted.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks!

**Comment by MikeMcC399** [comment]
PR #4073 is now merged for release/2.10.x.

Since the issue is not visible for regular users we do not need to wait for app release before closing.

Closing now.
