### ISSUE TITLE
Rapid Test Profile translation issues in English prompts 

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#4075]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Google Pixel 3a emulator
- Android version: 11
- First reported on app version: 2.9.0 
- Also reproducible on:  2.10.1

## Describe the bug

The English language text "You can create a profile with your personal data, which you can **submit** via QR code to **every** participating testing point." displayed in relation to creating a Rapid Test Profile contains some issues compared to the German text "Legen Sie ein Profil mit Ihren persönlichen Daten an, das Sie per QR-Code bei jeder teilnehmenden Teststelle vorlegen können."

- "submit" sounds like it is a remote process rather than personally showing the code at the testing point
- "**every** participating ..." together with "submit" makes it sound like the rapid test profile is sent simultaneously to **all** testing points in German instead of individually presented to the one testing point being visited.

## Steps to reproduce the issue

1. Set locale to English (United Kingdom)
2. On "Start Screen" tap "Manage Your Tests"
3. If "Create Rapid Test Profile" appears, tap this tile and view onboarding text, tap "CONTINUE", view text at top of edit screen
4. If no onboarding text appears, then enter "A" in First Name field, tap "SAVE", tap three-dot symbol, select "Information" to view onboarding text
5. If at step 3 "Rapid Text Profile" appears (because one has already been created) then tap this
6. Tap three-dot symbol, select "Information" to view onboarding text, tap "X"
7. Tap three-dot symbol, select "Edit Rapid Test Profile" to view edit prompt

![Rapid Test Profile English prompt wording](https://user-images.githubusercontent.com/66998419/133411551-265b3044-f6de-4d23-9890-013c492eda3d.png)

## Expected behavior

The English language onboarding and edit prompt for creating a Rapid Test Profile should be better aligned to the German texts.

## Possible Fix

https://github.com/corona-warn-app/cwa-app-android/blob/127889b390ef00228a619afb7573c5da724a1a6e/Corona-Warn-App/src/main/res/values/antigen_strings.xml#L140-L141

https://github.com/corona-warn-app/cwa-app-android/blob/127889b390ef00228a619afb7573c5da724a1a6e/Corona-Warn-App/src/main/res/values/antigen_strings.xml#L156-L157

For English language strings 
- `rat_profile_create_card_subtitle`
- `rat_profile_create_description`

Change strings from:

"You can create a profile with your personal data, which you can submit via QR code to every participating testing point."

to:

"You can create a profile with your personal data, which you can present via QR code at any participating testing point."

---
Internal Tracking ID: [EXPOSUREAPP-9502](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9502)

**Comment by Ein-Tim** [comment]
Just FYI, this is the implementation under iOS, maybe it makes sense to align Android to iOS?

<img src="https://user-images.githubusercontent.com/67682506/133829892-63062993-9208-40b0-8d94-915b039041bf.png" width="300">

**Comment by dsarkar** [comment]
@MikeMcC399 @Ein-Tim Thanks. Internal Tracking ID: [EXPOSUREAPP-9502](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9502)

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Thank you for the screenshot from iOS and for pointing out the different texts between iOS and Android.

The iOS text "Save your personal data as a QR code to speed up registration at testing points." would be fine to use on Android. That would probably mean replacing all the equivalent translations on Android though.

That might be a better solution than simply tweaking only the English text I suggested. Unfortunately I can't judge about the accuracy of translation into other languages (Bulgarian, Polish, Romanian & Turkish). It could be that the translations from the German "Legen Sie ein Profil mit Ihren persönlichen Daten an, das Sie per QR-Code bei jeder teilnehmenden Teststelle vorlegen können." are also problematisch.

**Comment by dsarkar** [comment]
@MikeMcC399 I forwarded your suggestion and comment to the internal ticket. Thanks.

**Comment by Ein-Tim** [comment]
PR: https://github.com/corona-warn-app/cwa-app-android/pull/4103

**Comment by MikeMcC399** [comment]
Need to wait for translations including English to be applied following on from German language text change in https://github.com/corona-warn-app/cwa-app-android/pull/4103 

"Legen Sie Ihre persönlichen Daten als QR-Code ab, um die Registrierung an der Teststelle zu beschleunigen."

**Comment by MikeMcC399** [comment]
The strings are now updated in [release/2.11.x](https://github.com/corona-warn-app/cwa-app-android/blob/release/2.11.x) for English and German at least. (Commit status https://github.com/corona-warn-app/cwa-app-android/commit/4c2f79e199c840aa17d81e3362b211708e35f739). So this issue should be fixed when 2.11 is released.

https://github.com/corona-warn-app/cwa-app-android/blob/4c2f79e199c840aa17d81e3362b211708e35f739/Corona-Warn-App/src/main/res/values/antigen_strings.xml#L140-L141

https://github.com/corona-warn-app/cwa-app-android/blob/4c2f79e199c840aa17d81e3362b211708e35f739/Corona-Warn-App/src/main/res/values/antigen_strings.xml#L156-L157

https://github.com/corona-warn-app/cwa-app-android/blob/4c2f79e199c840aa17d81e3362b211708e35f739/Corona-Warn-App/src/main/res/values-de/antigen_strings.xml#L141-L142

https://github.com/corona-warn-app/cwa-app-android/blob/4c2f79e199c840aa17d81e3362b211708e35f739/Corona-Warn-App/src/main/res/values-de/antigen_strings.xml#L157-L158

**Comment by marcauberer** [comment]
@MikeMcC399 can you confirm the fix? Can we close this one?

**Comment by MikeMcC399** [comment]
@marcauberer 
> can you confirm the fix? Can we close this one?

Sure. I will check when Google Play Store gives me access to the 2.11 release. So far I am still only seeing the previous version 2.10.1. For the 2.10 release it took 49 hours between announcement and download availability on my Google account.

I'm not anticipating any problem with the fix though.

**Comment by MikeMcC399** [comment]
This issue was fixed in 2.12.2 through PR https://github.com/corona-warn-app/cwa-app-android/pull/4212.
