### ISSUE TITLE
Print version of vaccination certificate: Member state of vaccination rendered in phone language (in my case Japanese)

### ISSUE THREAD

**Issue by IllDepence** [corona-warn-app/cwa-app-android#4175]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)  
    → I don't own a iOS device with which I could verify this
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Google Pixel (first generation)
- Android version: 9
- App version: 2.10.1

## Describe the bug

When I generate a print version of vaccination certificates, the resulting PDF document is almost completely in English and German, but the member state of vaccination is rendered in Japanese (the language my phone is set to).

The affected section of the document therefore reads:

Mitgliedstaat der Impfung:　‌　‌　ドイツ
Member State of vaccination:

## Steps to reproduce the issue

Generate a print version of a vaccination certificate on a phone that's set to Japanese.

## Expected behaviour

I would expect the member state to be rendered in English. Given that “ドイツ” is probably not recognizable to mean anything for most people.

## Possible Fix

Don't rely on the phone's language settings to render the state name in the PDF.

## Additional context

\-

---
Internal Tracking ID: [EXPOSUREAPP-9863](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9863)

**Comment by dsarkar** [comment]
FYI PR https://github.com/corona-warn-app/cwa-app-android/pull/4629

**Comment by MikeMcC399** [comment]
@IllDepence 
Perhaps you could let us know if this issue has been resolved for you? Hopefully you no longer see Japanese characters in a certificate print-out!

**Comment by IllDepence** [comment]
@MikeMcC399 
Thank you for the ping. Just checked an yes, the previously affected section of the document now reads:

Mitgliedstaat der Impfung:　‌　‌　Germany
Member State of vaccination:

**Comment by MikeMcC399** [comment]
@IllDepence 

It's good to hear that this issue is fixed! Could you now close it? You should see a button at the bottom to do this.

**Comment by dsarkar** [comment]
@IllDepence Thanks for reporting and your feedback. Best wishes, DS

---
Corona-Warn-App Open Source Team
