### ISSUE TITLE
Vaccination certificate confusing color use

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#4200]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only - TBD
* [ ] Bug is not already reported in another issue
Issue is mentioned also in https://github.com/corona-warn-app/cwa-app-android/issues/3927#issuecomment-940199373

## Technical details

- Device name: Samsung Galaxy A5 (2017) SM-A520F
- Android version: 8.0.0
- First reported on App version: 2.12.0-RC0
- Also present on App version: 2.14.1

## Describe the bug

In the certificate overview the color blue is used to denote the currently used certificate. Other certificates are grey.

In the certificate detailed view the color blue is used to denote full vaccination series, whereas grey means incomplete vaccination series.

Overview blue means selected. Detailed view blue means complete. Color is therefore used with different meanings in different, but closely related contexts. The use of color is not documented and because of its different meanings it is also not intuitive.

## Steps to reproduce the issue

Scan in 1/2 and 2/2 certificates and experiment with how they are shown in the overview and detailed view.

### Overview

Incomplete | Complete
--- | ---
![Vaccert12overview](https://user-images.githubusercontent.com/66998419/136908450-e30e4ddd-f283-4959-956a-e18507569716.jpg) | ![Vaccert22overview](https://user-images.githubusercontent.com/66998419/136908488-6b123f54-d7bb-4e6f-8209-a5a6ec222123.jpg)

### Detailed View

Incomplete | Complete
--- | ---
![Vaccert12detail](https://user-images.githubusercontent.com/66998419/136908231-9ffca4a7-40f5-4ef7-9194-68efb04619ed.jpg) | ![Vaccert22detail](https://user-images.githubusercontent.com/66998419/136908278-693afdcc-6064-46bc-985a-917db0b63dd3.jpg)

## Expected behavior

The use of color and symbols for vaccination certificates should be consistent and intuitively understandable.

## Possible Fix

Use a different color for a selected incomplete (1/2) vaccination certificate in the overview. This is the shield symbol half filled. (The shield symbol with a tick is used for a complete vaccination certificate.)

This is a screenshot of the currently displayed color:

![Vaccert12overview_selected](https://user-images.githubusercontent.com/66998419/136909386-25c45a48-8526-46bd-aa94-ca8f15034cff.jpg)

## Additional information

CovPass-App shows a selected 2/2 (complete) vaccination certificate in the overview with dark blue color. It shows a selected 1/2 (incomplete) vaccination certificate in the overview with light blue color.

---
Internal Tracking ID: [EXPOSUREAPP-9975](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9975)
Internal Tracking ID: [EXPOSUREAPP-9950](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9950)

**Comment by dsarkar** [comment]
@MikeMcC399 

Below a description of the expected behaviour:

- the blue indicates the currently selected and therefore most valid certificate (unless it is invalid) and has no other meaning
- The detail screens should always have the color of the list entry on the overview screen. So if I click on a blue certificate in the list I end up on a blue detail screen. If I click on a grey certificate in the list I end up on a grey detail screen.

**Comment by dsarkar** [comment]
There was a bug fixed in R 2.16 related to this issue: 
Internal Tracking ID: [EXPOSUREAPP-9950](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9950)

**Comment by MikeMcC399** [comment]
Thanks for the hint. I agree that it is fixed.

- PR #4544 fixed the issue.
