### ISSUE TITLE
"Certificate Verification by Third Parties" title truncated

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#4202]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Google Pixel 3a emulator
- Android version: 11
- First reported in App version: 2.11.2
- Also present in App version: 2.15.1

## Describe the bug

The title of the view "Certificate Verification by Third Parties" may be displayed truncated, for example, as "Certificate Verification by Third..."

![CovPassInfoFragment](https://user-images.githubusercontent.com/66998419/136943119-25ea7230-b099-4cba-a152-92288c2ff9e9.png)

### Physical device

1. On physical device scan certificate and tap i next to text "This QR code can be verified reliably with the CovPassCheck app."
2. Note truncated title

### Emulator

On Pixel 3a emulator:

1. Settings > Display > Font size > Default
2. Settings > Display > Display size > Default
3. Language English (United States)

In Android Studio:

1. Run `CovPassInfoFragmentTest.kt`
2. View file `/data/data/de.rki.coronawarnapp.test/screenshots/CovPassInfoFragment.png` with Device File Explorer
3. Note truncated title "Certificate Verification by Third..."

## Expected behavior

The title "Certificate Verification by Third Parties" should be completely displayed, whatever the screen geometry, wrapping to subsequent lines if necessary.

## Possible Fix

Review layout `fragment_cov_pass_info.xml`

string `cov_pass_info_title`
"Certificate Verification by Third Parties"
from `covid_certificate_strings.xml` is used in `fragment_cov_pass_info.xml`

---
Internal Tracking ID: [EXPOSUREAPP-10175](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10175)

**Comment by larswmh** [comment]
@MikeMcC399 FYI: PR #4658

**Comment by MikeMcC399** [comment]
@larswmh 
Thanks for the link to #4658! I was able to verify that the fix works.

Would you like to add the label [Fix 2.16](https://github.com/corona-warn-app/cwa-app-android/labels/Fix%202.16) to this issue, since the PR is on the [2.16.0 milestone](https://github.com/corona-warn-app/cwa-app-android/milestone/52) list?

**Comment by MikeMcC399** [comment]
This issue is confirmed fixed in CWA Android 2.16.2.
