### ISSUE TITLE
"Certificate Verification by Third Parties" image overlaps title

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#4203]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue
Issue https://github.com/corona-warn-app/cwa-app-android/issues/4202 relates to the same layout

## Technical details

- Device name: 8" Fold-out emulator
- Android version: 11
- First reported on App version: 2.11.2
- Also reproducible in App version: 2.19.2 and pre-[release/2.26.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.26.x) 

## Describe the bug

The image in the view "Certificate Verification by Third Parties" may overlap the title on larger devices.

![CovPassInfoFragment_8inch](https://user-images.githubusercontent.com/66998419/136943392-880fecfe-424a-4ff7-8b60-9dc86d163bf2.png)

### Physical device

1. On physical device scan certificate and tap i next to text "This QR code can be verified reliably with the CovPassCheck app."
2. Note image and title overlap on larger devices

### Emulator

On 8" Fold-out emulator in fold-out mode:

1. Settings > Display > Font size > Default
2. Settings > Display > Display size > Default

In Android Studio:

1. Run `CovPassInfoFragmentTest.kt`
2. View file `/data/data/de.rki.coronawarnapp.test/screenshots/CovPassInfoFragment.png` with Device File Explorer
3. Note overlap of image and the title "Certificate Verification by Third Parties"

## Expected behavior

The image underneath the title "Certificate Verification by Third Parties" should not overlap with the title.

## Possible Fix

Review layout `fragment_cov_pass_info.xml`

---
Internal Tracking ID: [EXPOSUREAPP-10268](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10268)

**Comment by MikeMcC399** [comment]
@dsarkar 
Please mirror this issue to Jira.
I checked with the latest release/2.14.x build and the issue still occurs.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks. Internal Tracking ID: [EXPOSUREAPP-10268](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10268)

**Comment by MikeMcC399** [comment]
- This issue is also related to the enhancement request https://github.com/corona-warn-app/cwa-app-android/issues/4309

**Comment by MikeMcC399** [comment]
- with PR #5514 the issue is no longer reproducible on an 8" Fold-out emulator (as in the steps to reproduce)

**Comment by MikeMcC399** [comment]
This issue should have the label https://github.com/corona-warn-app/cwa-app-android/labels/Fix%202%2E27 applied.
