### ISSUE TITLE
Twitter Report: "PCR-Test Fehler" after update to version 2.11.2

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-android#4217]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Xiaomi Redmine Pro 9
- Android version: 11
- App version: 2.11.2

## Describe the bug

After the update to version 2.11.2 (from version 2.10.1) the app shows this error:

<img src="https://user-images.githubusercontent.com/67682506/137182887-ca9f2d17-4337-4a61-ab46-a69db3a5287c.jpeg" width="300">
<img src="https://user-images.githubusercontent.com/67682506/137182877-9694924b-99c9-470c-be8c-0760c013d75d.jpeg" width="300">

## Steps to reproduce the issue

1. Register a PCR test in the app on version 2.10.1
2. Update the app to version 2.11.2
3. See the error

## Expected behaviour

No error.

## Additional context

1. The PCR test is still in the app
2. The PCR test was registered in the app on 20.09.2021
3. This is an informational report, it should be investigated by the devs why this happens and it should be made sure that something like this doesn't happen again in the future.
4. This bug report is based on the information shared with me on Twitter: https://twitter.com/blubi89387383/status/1448224772630908931?s=20

---
Internal Tracking ID: [EXPOSUREAPP-10035](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10035)

**Comment by dsarkar** [comment]
@Ein-Tim @vaubaehn Thanks for reporting. I will forward this!

**Comment by dsarkar** [comment]
FYI PR https://github.com/corona-warn-app/cwa-app-android/pull/4594

**Comment by Ein-Tim** [comment]
Closing as fixed in version 2.16.
