### ISSUE TITLE
[Bug] Missing information on 'Extension statistics' ...

### ISSUE THREAD

**Issue by Jo-Achim** [corona-warn-app/cwa-app-android#4250]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only **[?]**, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name:  Samsung Galaxy Note 10, SM-N970F/DS
- Android version:  Android 11 (One UI 3.1) with Android security update: 01. Oktober 2021
- App version:  2.12.1
- ENF:  18213614000

## Describe the bug

In the new 'Extended Statistics' there are no corresponding information to...

- "7-day hospitalization incidence" / "7-Tage-Inzidenz Hospitalisierung"    _and_
- "People with COVID-19 in intensive care units" / "COVID-19-Erkrankte auf Intensivstationen".

under "Key figures - Explanation of the statistics" / "Kennzahlen - Erklärung der Statistiken".

## Steps to reproduce the issue

Add the relevant information. 

---
Internal Tracking ID: [EXPOSUREAPP-9837](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9837)

**Comment by MikeMcC399** [comment]
It looks like it is covered by PR https://github.com/corona-warn-app/cwa-app-android/pull/4209 "Update info screen for statistics (EXPOSUREAPP-9837)".
