### ISSUE TITLE
App hangs at splash screen with no network

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#4263]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue
Mentioned also in https://github.com/corona-warn-app/cwa-website/issues/1950

## Technical details

- Device name: Samsung Galaxy A52 5G SM-A526B/DS
- Android version: 11
- App version: 2.11.2

## Describe the bug

If the CWA Android previous version 2.11.2 is started and there is currently no network connection, then the app hangs at the splash screen (start-up screen showing only the CWA logo) and provides no user accessible function.

## Steps to reproduce the issue

1. Install CWA 2.10.1 from apk
2. Complete onboarding
3. Exposure Logging is active
4. In Google Play Store
5. Open Manage apps and device
6. If updates available, tap on See details
7. Update all apps except Corona-Warn-App
8. Close Google Play Store
9. Enable flight mode
10. Install CWA 2.11.2 from apk
11. CWA opens at splash screen and hangs (> 5 minutes at least)
12. Disable flight mode (still no change to hang)
13. Exit and re-start CWA
14. Note message "Corona-Warn needs an update" appearing
15. Tap "UPDATE" to update to CWA 2.12.1

**Splash screen (which hangs)**

![Splash screen](https://user-images.githubusercontent.com/66998419/138462175-ac3c47ab-606a-4984-a016-c21b2ca014e2.jpg)

**Update message**

![CWA needs an update](https://user-images.githubusercontent.com/66998419/138462181-b337d693-e3e9-4c83-8ad6-824111ca8d9b.jpg)

## Expected behavior

The app should not hang if there is no network available.

## Possible Fix

Do not depend on network availability to be able to start app.

## Workaround

If CWA hangs at the splash screen:
1. Ensure there is network connectivity
2. Open Google Play Store
3. Update CWA to latest version (currently 2.12.1)

If there is a temporary workaround for the situation that currently no network is available, it would be good to know about this.

**Comment by MikeMcC399** [comment]
If there will be a fix for this issue I would leave it open, otherwise I will close it.

I hope in any case that if an auto-update to a newer app version is used in any future version it would not cause an app hang and would be tolerant towards network availability.

Additionally it would be worth considering whether a forced auto-update is necessary or whether a soft auto-update could be used, with a grace-period for update, followed by a forced auto-update (if absolutely necessary) after a certain deadline has passed.

**Comment by dsarkar** [comment]
@MikeMcC399 

> Additionally it would be worth considering whether a forced auto-update is necessary or whether a soft auto-update could be used, with a grace-period for update, followed by a forced auto-update (if absolutely necessary) after a certain deadline has passed.

Indeed, we have an internal ticket for this proposal: Internal Tracking ID: [EXPOSUREAPP-10201](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10201)

**Comment by MikeMcC399** [comment]
@dsarkar 
Good morning to you!

Thank you for the information. I will leave it to your internal tickets in that case and close this issue.
