### ISSUE TITLE
Who is "Fff"?

### ISSUE THREAD

**Issue by beceha** [corona-warn-app/cwa-app-android#4266]
(1)

I made a check-in today, the place + address is noted correctly in the diary, above it is written as "person": Fff. 
If you click on it, you get something like "under 10 min", "with mask", etc.
I have no idea what "Fff" is and where you could change it.

(2)

Then I discovered, that on other days in the diary, where I have NOT made a check-in anywhere, when you click on a date, then it opens this date, you sea a tab "Personen" (persons) and a tab "Orte" (places).
At the tab "Personen" (persons) is listed a "person" (?) called "Fff", and when you click on that, the dialogue mentioned above is openend.

But who the heck is "Fff", where does this come from and where can I change that?

Screenshot 1: https://imgur.com/uAha99n
Screenshot 2: https://imgur.com/undefined

Android 10
Corona Warn App: Version 2.12.1

**Comment by MikeMcC399** [comment]
@beceha 
We didn't hear back from you. Is this issue now fixed for you?

**Comment by MikeMcC399** [comment]
I suggest to close this issue as there was no further feedback from @beceha.

**Comment by mtwalli** [comment]
As suggested
