### ISSUE TITLE
Latest issued Vaccination 3/3 does not have highest priority

### ISSUE THREAD

**Issue by pc-coholic** [corona-warn-app/cwa-app-android#4269]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Huawei VOG-L29 (P30 Pro)
- Android version: 10
- App version: 2.12.1

## Describe the bug

Upon adding proof of a 3rd/booster vaccination to the app, the 2nd DCC is still displayed as the certificate currently in use.

This seems to be similar to #4123, #4000, #3838 and #3653 - although those have all been marked as resolved in earlier versions.

## Steps to reproduce the issue

1. Import booster DCC in addition to existing 1st and 2nd DCC

## Expected behaviour

The 3rd vaccination/booster DCC should be flagged as "Currently used certificate" and not the older ones.

## Additional context

The very same certificated, imported on iOS (CWA 2.12.1) behave correctly - so this seems an Android-related issue.

I have two sets (persons) where the problem is the same; Vaccination dates on both sets are the same, TED is the same except for the time).

- 1st
  * Vaccination: 2021-02-14
  * Technical Expiration Date: 19/06/2022 09:20
  * Issued: 99% pharmacy
- 2nd:
  * Vaccination: 2021-03-07
  * Technical Expiration Date: 19/06/2022 09:21
  * Issued: 99% pharmacy
- 3rd:
  * Vaccination: 2021-10-23
  * Technical Expiration Date: 23/10/2022 14:17
  * Issued: BayIMCO

I'll be happy to provide the barcodes of the DCCs directly by eMail.

---
Internal Tracking ID: [EXPOSUREAPP-10182](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10182) duplicates
Internal Tracking ID: [EXPOSUREAPP-9982](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9982)
Internal Tracking ID: [EXPOSUREAPP-9443](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9443)

**Comment by pc-coholic** [comment]
This seems to have been fixed in 2.13.2 :-)

**Comment by MikeMcC399** [comment]
@pc-coholic 
Did you also consider that your third vaccination certificate is now more than 14 days old? That may be the reason, rather than the new app version.

> 3rd:
> * Vaccination: 2021-10-23
> * Technical Expiration Date: 23/10/2022 14:17
> * Issued: BayIMCO

**Comment by pc-coholic** [comment]
I did not think about this... Good catch - that might perhaps be the case...

**Comment by Ein-Tim** [comment]
FYI: PR: https://github.com/corona-warn-app/cwa-app-android/pull/4343

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Thank you very much for the link to PR #4343, which has a lot of interesting detail to read! It is still open, so the changes are not in the 2.13.x release yet.

**Comment by svengabr** [comment]
I have just checked the linked Jira issue.

Jira Ticket is flagged as:
Resolution: `Wont Fix`
Status: `Obsolete`

Developer comment:
> Hey, this issue is already covered with https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-9982. I would set this ticket to obsolete.

> removed blocked and set to confirmed because successfully implemented/tested with 2.13 hotfix + 2.14
