### ISSUE TITLE
"Create Rapid Test Profile" tile delayed reset after profile delete

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#4271]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Pixel 3a emulator
- Android version: 11
- First reported on App version: 2.12.1
- Confirmed still present on App version: 2.13.2

## Describe the bug

After creating then deleting a Rapid Test Profile the "Create Rapid Test Profile" tile is not immediately shown in "Manage Your Tests". Instead the tile "Rapid Test Profile" with the blue background is still shown. A restart of the app is necessary before the correct "Create Rapid Test Profile" tile is shown again.

This is a regression from Google Play Store release 2.9.0. The issue is apparent in 2.10.1 and 2.12.1 from Google Play Store. It is however not reproducible on DeviceDebug builds. 

## Steps to reproduce the issue

1. Open CWA
2. Tap "Manage Your Tests"
3. Scroll down and tap on "Create Rapid Test Profile"<br>
![Create Rapid Test Profile](https://user-images.githubusercontent.com/66998419/138599208-1fb7746c-f3c0-4850-9390-081b73b6f0e5.png)
4. Tap "CONTINUE" if necessary
5. Enter "A" in field "First Name", tap "SAVE"
6. Tap three-dot icon, tap "Delete Rapid Test Profile", tap "DELETE"
7. Note that tile "Rapid Test Profile" is still shown, even though there is now no RTP stored<br>
![Rapid Test Profile tile](https://user-images.githubusercontent.com/66998419/138599213-8314ab4f-765a-421b-9b2d-4a60b907b603.png)

8. Close CWA through recent apps icon (square bottom right)
9. Re-open CWA
10. Tap "Manage Your Tests"
11. Scroll down and note that "Create Rapid Test Profile" is shown again<br>
![Create Rapid Test Profile](https://user-images.githubusercontent.com/66998419/138599208-1fb7746c-f3c0-4850-9390-081b73b6f0e5.png)

## Expected behavior

After deleting an existing Rapid Test Profile, the tile "Rapid Test Profile" in "Manage Your Tests" should be reset immediately to show "Create Rapid Test Profile" again. It should not require stopping and restarting the app in order to get the correct tile to appear.

---
Internal Tracking ID: [EXPOSUREAPP-10183](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10183)

**Comment by MikeMcC399** [comment]
No longer reproducible on CWA Android 2.15.1, so closing.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks, forwarded internally.
