### ISSUE TITLE
Help for Key Figures / Trends shows "1%%" and "5%%" in text 

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#4280]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy A5 (2017) SM-A520F
- Android version: 8.0.0
- App version: 2.12.2

## Describe the bug

The percentage symbol (%) shown under Key Figures / Trends is displayed twice in succession (%%).

This is a regression from version 2.12.1.

It affects at least the locales English (United States) and Deutsch (Deutschland).

## Steps to reproduce the issue

With locale set to English (United States)
1. Open CWA
2. Scroll down to 7-Day Incidence
3. Tap on i icon
4. In Key Figures scroll down to Trend
5. Note the text<br>
"The arrow direction indicates whether the trend is increasing, decreasing, or remaining steady – that is, demonstrates a deviation of less than 1%% compared to the previous day or 5%% compared to the previous week (taking decimal places into account)."

![Key_Figures_Trend-2 12 2](https://user-images.githubusercontent.com/66998419/138845570-680d4103-21c6-41b9-979a-994b9388c2eb.jpg)

## Expected behavior

Only one % percentage symbol should be displayed at a time.

Compare to screenshot from 2.12.1 where this was correctly shown:

![Key_Figures_Trend-2 12 1](https://user-images.githubusercontent.com/66998419/138845600-adeaa5ed-82ab-4bc2-8b17-e520ee5e16db.jpg)

## Possible Fix

The text comes from string `statistics_explanation_trend_text`.

Review code in 2.12.2:
https://github.com/corona-warn-app/cwa-app-android/blob/1f3a4685332c8f9eb9a35094c8ff957f7b9a2dc4/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/StatisticsExplanationFragment.kt#L34-L38
which has changed from 2.12.1 which used the following lines:
https://github.com/corona-warn-app/cwa-app-android/blob/6677a18c5b6e96d07bf707c88a4216d13eec407d/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/statistics/ui/StatisticsExplanationFragment.kt#L34-L38

## Additional context

Related to new release [tag/v2.12.2](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.12.2) posted by @kaddaSz  containing Fix: Strings double percentage #4278 from @AlexanderAlferov.

---
Internal Tracking ID: [EXPOSUREAPP-10203](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10203)

**Comment by MikeMcC399** [comment]
@dsarkar 
Do you want to add the Fix 2.13 label here?

The fix "Double percentage (EXPOSUREAPP-10214)" https://github.com/corona-warn-app/cwa-app-android/pull/4289 is in the [2.13.0 milestone](https://github.com/corona-warn-app/cwa-app-android/milestone/48).

**Comment by MikeMcC399** [comment]
Confirmed fixed in Android 2.13.2. (I didn't receive 2.13.1 before the roll-out was abandoned, so I had no opportunity to test on this release.)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for the CONFIRM, forwarded to internal ticket.

**Comment by MikeMcC399** [comment]
@dsarkar 
> Thanks for the CONFIRM, forwarded to internal ticket.

You're welcome! Hope you have a nice day!
