### ISSUE TITLE
QR-Icon in the middle of the screen after TAN input

### ISSUE THREAD

**Issue by raeulein** [corona-warn-app/cwa-app-android#4302]
## Technical details

- Device name: Samsung Galaxy S10
- Android version: 11
- App version: 2.12.2

## Describe the bug

If you go to the TAN-input-screen and back to the start screen, the QR-Icon is placed in the center of the screen

## Steps to reproduce the issue

1. Click on "Sie lassen sich testen" - "Weiter"
2a. Click on "TAN für PCR-Test eingeben"
2b. Or: Click on "TAN für PCR-Test anfragen" and then on "TAN EINGEBEN"
3. Go back to the start screen with the android navigation back button

![Screenshot_20211031-180004_Corona-Warn](https://user-images.githubusercontent.com/75761640/139594182-e5f154f0-6a27-4b64-b9a3-cee7726faac3.jpg)

4. If you do the steps a second time, the button is in the right place again

## Expected behaviour

The button should be next to the bottom menu above the "Scannen" text

---
Internal Tracking ID: [EXPOSUREAPP-10254](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10254) duplicate of
Internal Tracking ID: [EXPOSUREAPP-10250](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10250)

**Comment by MikeMcC399** [comment]
@raeulein 
I can reproduce this if I use the Android navigation back button at the bottom of the screen to return from the Enter TAN screen to the Status screen.

If instead I use the "X" button at the top-left of the screen to return to the Status screen it is not reproducible.

It's good that you caught this bug!

**Comment by MikeMcC399** [comment]
Reproducible on 
Android 11 (API 30) Pixel 3a emulator
Android 12 (API 31) Pixel 3a emulator

not reproducible on
Android 10 (API 29) Pixel 3a emulator

**Comment by dsarkar** [comment]
Hi @raeulein and @MikeMcC399, 

Thanks for reporting. Best, DS 

---
Corona-Warn-App Open Source Team
Internal Tracking ID: [EXPOSUREAPP-10254](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10254)

**Comment by Ein-Tim** [comment]
FYI: PR: #4305 merging into `release/2.13.x`

**Comment by dsarkar** [comment]
@raeulein  FYI PR https://github.com/corona-warn-app/cwa-app-android/pull/4305

**Comment by dsarkar** [comment]
@Ein-Tim ;-) ok, you are faster!

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-10250](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10250)

**Comment by MikeMcC399** [comment]
I can't reproduce the issue any more on CWA Android 2.13.2 which I received yesterday. It looks like the issue was successfully fixed.

**Comment by MikeMcC399** [comment]
@raeulein 

Would you like to confirm that the issue is fixed for you now? On top of 2.13.2 where the issue was fixed, there was a follow-on release today: 2.13.2.
