### ISSUE TITLE
Risk Warning stops after checking future dates

### ISSUE THREAD

**Issue by heinrich26** [corona-warn-app/cwa-app-android#4303]
## Technical details

- Device name: Google Pixel 4a
- Android version: 12
- App version: 2.12.2

## Describe the bug

Basically, when your device time has been set forward and back again, the APP might run a risk check during while in the "future". Now, when going back, the APP won't run any checks until you're behind the future checks. This causes the app to never check your contacts again, if you for example went to 2037 and 
back because of some reason.

## Steps to reproduce the issue

On Android:

1. Go to `Settings` → `System` → `Date & Time` → toggle `Set Time automatically` & change your date

2. Wait at least til the next risk check in the APP, then you can reactivate `Set Time automatically`. (Or set your date to an earlier day)
3. From now, the app doesn't run anymore checks!

## Expected behaviour

No more risk checks until the 'newest' check.
Another behavior might be that the app is checking but only showing the one with the greatest date

## Possible Fix

If this is handled in the app itself, It might be as simple as instead of checking for greater than the newest check to look if the timestamp is in a range
If its checking but showing the wrong data, the app should check for the most recent check

## Additional context
Here you can see that the app is not showing the current check, but the newest.
![Screenshot_20211031-184447](https://user-images.githubusercontent.com/65970327/139598443-f7c7472e-befc-4ed2-a1cf-46d387396167.png)

---
 Internal Tracking ID: [EXPOSUREAPP-10253](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10253)

**Comment by MikeMcC399** [comment]
@heinrich26 
This is the same as the issue https://github.com/corona-warn-app/cwa-app-android/issues/3629. Unfortunately there doesn't seem to have been any development attention to the issue so far.

**Comment by vaubaehn** [comment]
ping @chiljamgossow 
Are there any plans to solve this problem?
(Nice to see you back in the team)

**Comment by dsarkar** [comment]
@heinrich26 @MikeMcC399 @vaubaehn Thanks for reporting: Internal Tracking ID: [EXPOSUREAPP-10253](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10253)

**Comment by MikeMcC399** [comment]
On Nov 1 I changed the device's date to Nov 2, let it do an exposure check, then I set the date back to Nov 1.

Today Nov 2, the device's date and time is correct and is now several hours after the future time set yesterday. New exposure checks are now being carried out. These were not happening during the time that the device was catching up.

So, at least if there is a short time travel to the future, like in my example, just one day, CWA does recover.

It would be advantageous if the app would recover from a massive time travel like the one described here to the year 2037. I didn't try this out lately, but in previous versions the only ways to recover were either to reset the app or to uninstall and reinstall it.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks. I forwarded your comment to the internal ticket.

**Comment by tueksta** [comment]
So without fixes happening, it means I have to wait until the future date is reached until I can do exposure checks again? Meanwhile my app floods the servers with requests that all fail? Any hotfix incoming?

**Comment by MikeMcC399** [comment]
@tueksta 
According to your issue
- #4660

you set your device time to one month in the future.

It would certainly be good to have some feedback from the developers. 

In the meantime the only workaround I know of is to reset the app. As the name suggests, you lose all your data if you do this, however at least you would get exposure logging working again immediately for the future (not the past).

**Comment by ndegendogo** [comment]
@tueksta *of course I don't know the reasons why you do setup a future date.*

If you are an app developer and are using your device for testing, you can consider to deactivate cea / exposure detection temporarily during such tests. Then at least you can avoid to run into such issues again.

**Comment by tueksta** [comment]
yeah, that's good advice for the future.

**Comment by svengabr** [comment]
I have just checked the linked Jira issue.

Jira Ticket is flagged as:
Resolution: `Wont Fix`
Status: `Obsolete`

Developer comment:
> issue closed, pop-up should prevent such issue, probably edge case.
