### ISSUE TITLE
App remembers the certificate which was selected as the "favorite" one after deleting the certificate and importing it again

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-android#4316]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Huawei P Smart 2019
- Android version: 10
- App version: 2.12.2

## Describe the bug

The Android app remembers the certificate which the user selected as the favorite one (shown on top of the certificates list), even after the certificate was deleted and then imported again. 
iOS does not remember the certificate which was selected as the favorite one if the certificate is deleted. 

## Steps to reproduce the issue

1. Open the universal QR code scanner
2. Scan the QR code of an EU digital COVID-19 certificate
3. Click on the arrow in the top left corner
4. Click on the "Certificate" tab
5. Click on the Person from whom you just imported the certificate
6. Scroll down a bit
7. Turn on the the switch ("Please turn on this switch...")
8. Click on the certificate at the very bottom
9. Click on the 3 dots in the top right corner
10. Click on "Remove Certificate"
11. Click on "REMOVE"
12. Open the universal QR code scanner
13. Scan the QR code you scanned in step 2
14. Click on the arrow in the top left corner
15. Click on the "Certificate" tab
16. Click on the Person from whom you just imported the certificate
17. Scroll down a bit
18. See that the switch you activated in step 7 is still activated

## Expected behaviour

The app should not remember the certificate which was selected as the favorite one if the certificate gets deleted.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
I can reproduce your issue on the version you reported it on: 2.12.2. It seems to remember the person's name who was selected, not so much the actual certificate itself.

I could however no longer reproduce the issue in 2.13.2. I expect that introduction of the recycle bin in this version has made the difference.

Could you try again with 2.13.2?

In your steps to reproduce for the 2.13.2 version the certificate will offered to be restored from the recycle bin when you try to scan it a second time after deleting it.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Yes, I can confirm that this issue has been fixed in version 2.13.2. I also guess that this is due to the newly introduced recycle bin. 

Closing as fixed in version 2.13.2.
