### ISSUE TITLE
"Delete All Permanently" for single certificate in Recycle Bin

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#4323]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Android version: 11
- First reported on App version: 2.13.1-RC1
- Confirmed still present on App version: 2.13.2

## Describe the bug

The options for a certificate in the Recycle Bin are:

- "Restore"
- "Delete All Permanently"

For reference see screenshot https://www.coronawarn.app/assets/screenshots/2-13/en/android/RecyclerBinOverviewFragment_full_2.png.

The word "All" does not make sense in this context because selecting this option deletes only one certificate, not all certificates.

To remove all certificates there is a separate option available at the top-level of the Recycle Bin which is labelled "Remove All".

## Steps to reproduce the issue

1. Scan in two certificates
2. Remove both certificates
3. Go to the Recycle bin
4. For one certificate select "Delete All Permanently"
5. Note that only one certificate has been deleted from the recycle bin, not all certificates

## Expected behavior

The menu text for a single certificate should only apply to the one certificate.

## Possible Fix

Change the text in string `recycle_bin_remove_permanently`
from "Delete All Permanently" to "Delete Permanently"

https://github.com/corona-warn-app/cwa-app-android/blob/5ea5c9c329e3ae31598bd476716e1348e6d44169/Corona-Warn-App/src/main/res/values/recycler_bin_strings.xml#L35-L36

---
Internal Tracking ID: [EXPOSUREAPP-10407](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10407)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks. Internal Tracking ID: [EXPOSUREAPP-10407](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10407)

**Comment by dsarkar** [comment]
@MikeMcC399 FYI PR https://github.com/corona-warn-app/cwa-app-android/pull/4324

**Comment by MikeMcC399** [comment]
@dsarkar 
Good morning to you and thank you! PR #4324 should solve the issue. Of course it also needs to be translated like all text changes.
I see it is going into release/2.13.x so perhaps there will be a bug fix version released?

**Comment by dsarkar** [comment]
@MikeMcC399 FYI PR https://github.com/corona-warn-app/cwa-app-android/pull/4330

**Comment by MikeMcC399** [comment]
@dsarkar 
Thanks for the correction.
I see there is now https://github.com/corona-warn-app/cwa-app-android/pull/4332 for 2.14.x

**Comment by MikeMcC399** [comment]
This has been a little confusing due to some changes being reverted, however in the pre-release version [v2.13.3-RC2](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.13.3-RC2) the issue is fixed:

---

https://github.com/corona-warn-app/cwa-app-android/blob/ea8aa803f226d3a079ca27c7c5b45e81b71b639f/Corona-Warn-App/src/main/res/values/recycler_bin_strings.xml#L35-L36

Fixed by PR https://github.com/corona-warn-app/cwa-app-android/pull/4379.

---

https://github.com/corona-warn-app/cwa-app-android/blob/ea8aa803f226d3a079ca27c7c5b45e81b71b639f/Corona-Warn-App/src/main/res/values-de/recycler_bin_strings.xml#L36-L37

Fixed by PR https://github.com/corona-warn-app/cwa-app-android/pull/4372

---

So probably the fix 2.13.3 label could be added.

**Comment by MikeMcC399** [comment]
Verified fixed in today's release 2.13.3:

EN: "Delete Permanently"
DE: "Endgültig entfernen"

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for the feedback, forwarded the CONFIRM to the internal ticket.
