### ISSUE TITLE
Add labels for local statistics for screenreader users

### ISSUE THREAD

**Issue by WestphalDenn** [corona-warn-app/cwa-app-android#4333]
Problem: 
If any number of locations are added to monitor the local corona numbers, there is absolutely no way to know which number belongs to which location. The location names are not read out by screen readers. So blind people only get the numbers, "151" for example. 

Solution: 
Add the location name to the numbers. It could look like "Berlin - 7-day incidence of 151". That way, it is possible to monitor multiple locations in CWA even if you are blind. 

If you need more information, I am happy to help to the best of my ability. 

---
 Internal Tracking ID: [EXPOSUREAPP-10650](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10650)

**Comment by marcauberer** [comment]
@WestphalDenn this issue is addressed by pr #4427

**Comment by MikeMcC399** [comment]
@WestphalDenn 

Could you check this is fixed for you? I tried on CWA 2.21.1 using TalkBack on a Local 7-Day Incidence tile for Bavaria and it read me back the name "Bavaria".

If all is well, then you could close the issue.

**Comment by WestphalDenn** [comment]
Yes everything works well now. Thanks for asking.

**Comment by dsarkar** [comment]
@WestphalDenn Thanks for participating here and your feedback. Best wishes, DS

---
Corona-Warn-App Open Source Team
