### ISSUE TITLE
Landkreis and Bundesland does not fit together

### ISSUE THREAD

**Issue by Aschroet** [corona-warn-app/cwa-app-android#4346]
When do "Lokale 7-Tage-Inzidenz hinzufügen" -> Thüringen -> Ilm-Kreis, the app shows the "Hospitalisierungen in Baden-Würtemberg" which is wrong because Ilm-Kreis is located in Thuringia (and not Baden-Wurtemberg).

![Screenshot_20211108-112207_Corona-Warn](https://user-images.githubusercontent.com/19612739/140757387-0d9c6f09-7688-4ebc-a1d5-b80bfd6843e8.jpg)

Please fix!

**Comment by marcauberer** [comment]
Duplicate of #4327

**Comment by MikeMcC399** [comment]
@dsarkar 
Since this is a duplicate it could be closed in favour of the other issue (of #4327).

(@Aschroet - you could also close your issue.)

**Comment by dsarkar** [comment]
@Aschroet we close this issue in favour of #4327. Thanks for reporting. Will be fixed soon.

**Comment by MikeMcC399** [comment]
@Aschroet 
Would you like to check with the version 2.13.3 which is now in the Google Play Store?

**Comment by Aschroet** [comment]
@MikeMcC399 works now.

![Screenshot_20211123-155653_Corona-Warn](https://user-images.githubusercontent.com/19612739/143048678-3d971cee-33a4-4247-a334-6e889190f219.jpg)

**Comment by dsarkar** [comment]
Hi @Aschroet, thanks for your feedback.

---
Corona-Warn-App Open Source Team
