### ISSUE TITLE
App still informs about booster vaccination

### ISSUE THREAD

**Issue by DerVogel2020** [corona-warn-app/cwa-app-android#4353]
## Technical details

- Device name: Samsung A5 (2017)
- Android version: 8.0
- App version: 2.13.2

## Describe the bug

After importing the certificate of a booster vaccination, the app still informs about the missing booster vaccination.
Only the number of dates differs since the last vaccination differs to this screenshot
https://www.coronawarn.app/assets/img/blog/2021-11-04-booster-notifications/benachrichtigung-johnson.png

## Steps to reproduce the issue

1. Get vaccinated with Johnson
2. Import the certificate
3. Get vaccinated with Comirnaty
4. Import the certificate

## Expected behaviour

The information about the missing bosster vaccination should go away

## Additional context

May be related to #4269 #4343 #4334

---
Internal Tracking ID: [EXPOSUREAPP-10232](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10232)

**Comment by mlenkeit** [comment]
@DerVogel2020 thanks for raising this. The text should disappear within 24 hours. For several technical reasons, this logic is currently only checked once a day and unfortunately not when a new certificate is registered in the app. We're working on it...

**Comment by DerVogel2020** [comment]
> Same as #4334?

@Ein-Tim Almost, since there the comirnaty vaccination did not become valid immediately. Here the validity and priority etc  is fine, only the info text should disappear.

**Comment by DerVogel2020** [comment]
> @DerVogel2020 thanks for raising this. The text should disappear within 24 hours. For several technical reasons, this logic is currently only checked once a day and unfortunately not when a new certificate is registered in the app. We're working on it...

@mlenkeit thanks. Now (after less than 16 hours) the message is gone and replaced by "Sie haben nun alle derzeit geplanten Impfungen erhalten. Ihr Impfschutz ist vollständig."

**Comment by SoftwareApe** [comment]
Still getting the message, even 19 days later

**Comment by laundmo** [comment]
This issue also occured for my mother, who had Biontech Comirnaty all 3(!) times. She gets the booster notification even though she was boostered 74 days ago, which is 3/3 vaccinations for her.

![signal-2021-12-19-14-26-36-478](https://user-images.githubusercontent.com/24855949/146676846-88ce7b24-8784-403d-9217-b111ba539454.jpg)
![signal-2021-12-19-14-25-33-209](https://user-images.githubusercontent.com/24855949/146676848-82722890-312a-4625-8544-aac60d84874b.jpg)

(images were shared with her full consent)

**Comment by MikeMcC399** [comment]
@laundmo 
The fix for this issue is showing up in [pre-release version v2.15.0-RC0](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.15.0-RC0).
Cancel booster indication (EXPOSUREAPP-10232) #4383

Version 2.15 has not yet been released.

**Comment by MikeMcC399** [comment]
There was an announcement this morning for the release of CWA 2.15. See https://www.coronawarn.app/en/blog/2021-12-20-cwa-2-15/.

**Comment by DerVogel2020** [comment]
I closed this now, because 2.15 is available.
