### ISSUE TITLE
Howto register official positive test from another country in the app?

### ISSUE THREAD

**Issue by demogit-code** [corona-warn-app/cwa-app-android#4386]
How can i register an official positive test from another eu country (=not germany) in the app,
so others can get warned about it?

**Comment by Ein-Tim** [comment]
Hey @demogit-code 

Please take a look at this FAQ entry, as it answers exactly your question: https://www.coronawarn.app/en/faq/#test_in_other_country

If any questions remain, please let us know here.

**Comment by dsarkar** [comment]
@demogit-code Thanks for the question. If you consider that @Ein-Tim answered your doubts, please, close this issue. If you should have any further questions, please don't hesitate to ask them here. 

Best wishes, DS

---
Corona-Warn-App Open Source Team
