### ISSUE TITLE
Vaccination Certificate Travel verification: France can't validate manufacturer Biontech on Android

### ISSUE THREAD

**Issue by Lalaluka** [corona-warn-app/cwa-app-android#4387]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy S21 5G, Samsung Galaxy A40, iPhone Xr
- Android version: 11
- App version: 2.13.2

## Describe the bug

Trying to validate vaccination certificates for entry to France (13 rules present) on Android phones leads to the message "Ihr Zertifikat konnte nicht vollständig geprüft werden". With the information that the Manufacturer "Biontech Manufacturing GmbH" can not be validated by the Rule **VR-FR-0009 (1.0.0)**. But the same validation for the same certificates succeeds on IOS, suggesting it's an Android-specific issue.
I tested it on two different Android Phones with two different Certificates (both 2x Biontech).

The Issue I'm reporting is the difference between IOS and Android behavior. I don't actually know if my certificates are faulty or the Android App. But I opted to report this Issue in the Android App Repo since the french "TAC Verif" App for the validation of vaccination certificates also correctly validates the certificate like he IOS App does.

## Steps to reproduce the issue

1. Go to 'Zertifikate'
2. Click on the Certificate to check
3. Click on 'GÜLTIGKEIT PRÜFEN'
4. Select France as the Country an click 'PRÜFEN'

Result on Android:

<img src="https://user-images.githubusercontent.com/26364692/141743123-627e3cd7-b14e-494b-a4e8-70d9b9fc30c7.jpeg" width="400">

Result on IOS:
<img src="https://user-images.githubusercontent.com/26364692/141743092-5aac7219-2f4d-4042-b4e3-7f43506c4249.jpeg" width="400">

## Expected behaviour

I expect the validation to either fail on both Android and IOS or to validate the certificate in both cases.

## Additional context

I currently only had vaccine certificates with 2x Biontech available to test with. I don't know how the rule behaves for other manufacturers.

**Comment by Ein-Tim** [comment]
According to @thomasaugsten this issue will be fixed in the next version, see https://github.com/eu-digital-green-certificates/dgc-certlogic-ios/issues/49#issuecomment-963252820.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Following your link (https://github.com/eu-digital-green-certificates/dgc-certlogic-ios/issues/49#issuecomment-963252820) leads to PR https://github.com/corona-warn-app/cwa-app-android/pull/4344 "Remove white space that breaks cert logic (EXPOSUREAPP-10455)" included in [pre-release v2.13.3-RC0](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.13.3-RC0).

**Comment by Ein-Tim** [comment]
#4344 is included in https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.13.3, the latest release.

**Comment by Lalaluka** [comment]
Ah, thanks.
So I guess I wasn't fast enough to report the issue ;)

If it's okay I will close the Issue since it's already part of the latest release.

**Comment by MikeMcC399** [comment]
@Lalaluka 
It would be great if you could just check that the issue no longer occurs with the new release!

**Comment by Lalaluka** [comment]
Hi, 
Sry for the late response @MikeMcC399 
Just tested it with the 2.13.3 from the Play Store and the app now validates VR-FR-0009 (1.0.0) ✌️
