### ISSUE TITLE
'Ausgestellt' timestamp of Rapid Antigen Test shows the timestamp the test was booked

### ISSUE THREAD

**Issue by hschildberg** [corona-warn-app/cwa-app-android#4402]
## Technical details

- Device name: Samsung S9
- Android version:  10
- App version: 2.13.3

## Description

I added the test result of a Rapid Antigen Test in CWA. The validity counter of the test result uses the time I booked the test in a test center instead of the time the test was actually conducted.

## Expected behaviour

Actually use the time the test was conducted.

## Additional context

See the JSON that was part of the URI `https://s.coronawarn.app/?v=1#...`. At least it includes the correct time in the `timestamp` field.
The antigen test was booked more than a day before it was conducted, so when I added the test result the validity counter already contained more than 24 hours on its clock.

```
{
	"fn": "<removed by intention>",
	"ln": "<removed by intention>",
	"dob": "<removed by intention>",
	"timestamp": 1637153662,
	"testid": "<removed by intention>",
	"salt": "<removed by intention>",
	"hash": "<removed by intention>"
}
```

**Comment by MikeMcC399** [comment]
@hschildberg 
There is a long discussion in https://github.com/corona-warn-app/cwa-documentation/issues/661 "RAT proof feature: Countdown uses registration time instead of time of test result as starting point".

Perhaps you could check if your issue is already covered there?

**Comment by hschildberg** [comment]
Hi @MikeMcC399, thanks for the prompt response. This is the very same issue I encountered. I overlooked the original one somehow.
