### ISSUE TITLE
Hospitalisierungs-Index für Bundesland Niedersachsen falsch

### ISSUE THREAD

**Issue by heide60** [corona-warn-app/cwa-app-android#4403]
Device name: Samsung Galaxy S10 (und andere)
Android version: current (afaik Android 11), status: official (unrooted)
App version: 2.13.3 and prior

Bug:
Hospitalisierungen für Bundesland Niedersachsen wird in der CWA stets falsch ausgewiesen:
- Aktuell in der App ausgewiesen: 2.2 ("bis gestern")
- Tatsächlicher Hospitalisierungen für Bundesland Niedersachsen: 4.6 (laut offizieller Internet-Seite des Bundeslandes)

Verifikation:
- Beliebigen Landkreis aus Niedersachsen (z. B. Emsland) zur lokalen 7-Tages-Inzidenz hinzufügen
- 7TI wird korrekt ausgeweisen (aktuell hier 198,8)
- Hospitalisierung wird mit 2,2 ausgewiesen
- Tatsächlicher Hospitalisierungen für Bundesland Niedersachsen: 4,6 (laut offizieller Internet-Seite des Bundeslandes)- 

Gegenprobe für NRW
- Beliebigen Landkreis aus NRW (z. B. Köln) zur lokalen 7-Tages-Inzidenz hinzufügen
- 7TI wird korrekt ausgeweisen (aktuell 280,4)
- Hospitalisierung wird mit 3,6 ausgewiesen, das stimmt überein mit den Angaben der Internet-Seite des Bundeslandes NRW

**Comment by Ein-Tim** [comment]
"2,2" is also shown under iOS.
Thus a community manager should transferred this to the documentation repo.

**Comment by MikeMcC399** [comment]
The statistics figures in the app come from the Robert Koch Institute. The RKI site has a separate link from [COVID-19 (Coronavirus SARS-CoV-2)](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/nCoV.html) to https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland.

So the question is: why is the number in https://raw.githubusercontent.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland/master/Aktuell_Deutschland_COVID-19-Hospitalisierungen.csv different from the one on https://www.niedersachsen.de/Coronavirus/aktuelle_lage_in_niedersachsen/niedersachsen-und-corona-aktuelle-leitindikatoren-203487.html?

```
Datum,Bundesland,Bundesland_Id,Altersgruppe,7T_Hospitalisierung_Faelle,7T_Hospitalisierung_Inzidenz
2021-11-17,Niedersachsen,03,00+,178,2.22
```

Perhaps somebody closer to the data-processing can help? @GisoSchroederSAP maybe?

**Comment by heide60** [comment]
@MikeMcC399: You're right, I just detected this as well.

According to the following NDR report

https://www.ndr.de/nachrichten/info/Hospitalisierungsrate-zeigt-nur-noch-die-Haelfte-der-Corona-Patienten,hospitalisierungsrate102.html

this is due to a severe data quality issue with the Hospitalisierungsrate in general due to massive delays in reporting towards RKI. Which is shocking tbh.
The data the state Niedersachsen itself is reporting is not based on the RKI data but on Niedersachsens own reporting. And thus reflects the reality (4,6).

So this is not a CWA issue unfortunately (because this could be fixed pretty easily).

**Comment by heide60** [comment]
At this point I'll close this issue because this is not a CWA bug but rather a data junk issue with the RKI Hospitalisierungrate - garbage in, garbage out.

**Comment by GisoSchroederSAP** [comment]
All, 
We enforced an in-depth investigation together with RKI about the significant difference of both numbers. First result: Both numbers are from different sources: 
While the website is based on locally aggregated numbers leveraging a local approach called: _Interdisziplinärer Versorgungsnachweis IVENA eHealth_  , the statistics within the CWA consumes data aggregated by the RKI from the various health authorities. Yes, there are delays, so the numbers that are shown today (referring to yesterday's date) become slightly adjusted during the following days. However, the are not at all linked to the IVENA numbers.

As much as we dislike this deviation, there is no way to "fix" something here, except: I just emphasized this inconsistency and asked if is can be addressed directly to the respective department of the federal state of Niedersachsen. Let's see if somebody feels responsible there.

**Comment by Ein-Tim** [comment]
@GisoSchroederSAP 

Something also related to the statistic tiles, "Ludwigslust-Parchim" (Mecklenburg-Vorpommern) shows 0,0 as local 7-day incidence, this is also what they [report to the RKI](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Fallzahlen_Kum_Tab.html). 
Could you check what's going on there?

**Comment by heide60** [comment]
@GisoSchroederSAP

I think we all agree the deviation in numbers is not a CWA issue, this i why I closed the CWA bug report. Thanks for your comment on this.

So if you or RKI wants to know why Niedersachsen relies on IVENA instead of some RKI numbers, please see
https://www.niedersachsen.de/Coronavirus/aktuelle_lage_in_niedersachsen/niedersachsen-und-corona-aktuelle-leitindikatoren-203487.html
and why Niedersachsen is convinced that the IVENA hospitalisation numbers give a more realistic figure than the RKI numbers.

If you track some "slight adjustments" in the RKI hospitalisation counters, you will rather see substantial corrections in the aftermath.
For example take the date 2021-11-01: The RKI hospitalisation index for Niedersachsen for that specific day was announced to be 1.9 (on 2021-11-01), and had to be corrected by RKI almost each and every day in the aftermath. Today (2021-11-20), the corrected RKI hospitalisation index for Niedersachsen on 2021-11-01 is at 3.31.
(https://github.com/robert-koch-institut/COVID-19-Hospitalisierungen_in_Deutschland/tree/master/Archiv)
And even that might not be the last word.

A correction from 1.9 to 3.31 in the aftermath is not a "slight adjustment".
