### ISSUE TITLE
[Small Bug]: Missing information in High-Risk-Status-Field ... 

### ISSUE THREAD

**Issue by Jo-Achim** [corona-warn-app/cwa-app-android#4407]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] **Unknown:** Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name:  Samsung Galaxy Note 10, SM-N970F/DS
- Android version:  Android 11 (One UI 3.1) with Android security update: 01. November 2021
- App version:  2.13.3

## Describe the bug

Since today (11/18/2021 around midnight) there is no information in the high risk status field; see Screenshots: 

![Screenshot_20211118-063600_Corona-Warn](https://user-images.githubusercontent.com/21124877/142365736-12cc2d83-a856-4041-88bc-7762294de70c.jpg)

![Screenshot_20211118-063609_Corona-Warn](https://user-images.githubusercontent.com/21124877/142365746-9f5f6f26-cc0d-4f53-83bd-1d6bc805d843.jpg)

The problem was cleared up with a "CWA: There is news" - information and subsequent update at around 7:00 am: 

![Screenshot_20211118-072747_Corona-Warn](https://user-images.githubusercontent.com/21124877/142365759-fab44fa6-d590-48c7-838a-7cfb371ec382.jpg)

## Steps to reproduce the issue

1. Start CWA ...

## Additional context

I assume that the whole thing is self-explanatory. 

---
Internal Tracking ID: [EXPOSUREAPP-10666](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10666)

**Comment by dsarkar** [comment]
@Jo-Achim Thanks for reporting. Internal Tracking ID: [EXPOSUREAPP-10666](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10666)

**Comment by fynngodau** [comment]
This looks similar to a CCTG issue we are having: https://codeberg.org/corona-contact-tracing-germany/cwa-android/issues/159

We also opened a related microG issue: https://github.com/microg/GmsCore/issues/1614

@Jo-Achim Are you using CWA with microG?

**Comment by MikeMcC399** [comment]
@fynngodau 

I noticed in your linked issues there was a comment about how many days of exposure details are used.

I was in touch with Google one year ago (through exposure-notifications-feedback@google.com) about the number of days of exposure logs that are retained by the Google COVID-19 Exposure Notifications System, which can be up to 16 days. This doesn't fit what their UI says (Random IDs are automatically deleted after 14 days). They told me that there is a daily task which runs to remove older entries. They also said they were going to look at whether the retention period was right and then unfortunately they stopped responding. There is a history on the closed issue https://github.com/corona-warn-app/cwa-app-android/issues/1020 "Exposure check history retained for more than 14 days". 

I don't know if this is helpful, but I thought I would mention it.

**Comment by larswmh** [comment]
@fynngodau @MikeMcC399 good morning! Thanks for the additional information. We've forwarded it to the internal ticket

**Comment by Jo-Achim** [comment]
> 
> @Jo-Achim Are you using CWA with microG?

@fynngodau, no, I am not using microG.

**Comment by Ein-Tim** [comment]
Hi, just wanted to add this here:
A Twitter user is reporting the same issue, the exposure was more than 14 days ago & is not shown in the contact journal anymore, but under "Status" his app shows this:

<img src="https://user-images.githubusercontent.com/67682506/143744327-d35442ef-fc90-4451-b2e6-1a0d63ed9b48.jpeg" width="300">

Should I ask for any details? Maybe the user can upload an error log? 

Just let me know!

**Comment by Jo-Achim** [comment]
Hi @Ein-Tim, 
I am the wrong person to answer, but if someone can and wants to provide a log, it certainly doesn't do any harm.
Regardless of how far the internal troubleshooting has progressed.

**Comment by Ein-Tim** [comment]
The Twitter user captured the moment when the app switched from red (without date shown on increased risk card) to green in the error log with the ID: 34FEFBD1B1E47DD0CA1D

**Comment by dsarkar** [comment]
@Ein-Tim Thanks, we will forward this to the internal ticket.

**Comment by dsarkar** [comment]
@Ein-Tim Do you know if this user is using 2.14?

**Comment by Ein-Tim** [comment]
@dsarkar 

Yes, confirm 2.14.1 on Android 10.

**Comment by dsarkar** [comment]
@Ein-Tim thanks

**Comment by deesnook** [comment]
> This looks similar to a CCTG issue we are having: https://codeberg.org/corona-contact-tracing-germany/cwa-android/issues/159
> 
> We also opened a related microG issue: [microg/GmsCore#1614](https://github.com/microg/GmsCore/issues/1614)
> 
> @Jo-Achim Are you using CWA with microG?

I can confirm the issue using microG. See https://github.com/corona-warn-app/cwa-app-android/issues/4586

**Comment by Jo-Achim** [comment]
@deesnook,

> > @Jo-Achim Are you using CWA with microG?
> 
> @fynngodau, no, I am not using microG.

**Comment by swekkx** [comment]
I have the same issue. Don't know if it's helpful. The information also missing after another refresh.

Send Error Report
2021.12.26 - 14:14:18
ID E515DB03B060915E1054 


![Screenshot_20211226-092426_Corona-Warn](https://user-images.githubusercontent.com/96697098/147415949-a643b5b0-8e5c-4a6a-8e42-a53a6c4f4ec2.jpg)

CWA Version 2.15.1

**Comment by Jo-Achim** [comment]
Thank you.
I think all informations are important in order to better find the bug.

**Comment by dsarkar** [comment]
@Jo-Achim @swekkx @deesnook @Ein-Tim @fynngodau 
FYI PR https://github.com/corona-warn-app/cwa-app-android/pull/4618

**Comment by Ein-Tim** [comment]
This issue has the https://github.com/corona-warn-app/cwa-app-android/labels/Fix%202.16 label applied to it but is still open. Was someone able to confirm that this is fixed? 

@dsarkar I guess the internal ticket is set to fixed?

**Comment by svengabr** [comment]
I have just checked the linked Jira issue.

Jira Ticket is flagged as:
Resolution: `Completed`
Status: `Fixed`
Fix Version/s: `Release 2.16`

Developer comment:
> Likely cause: Latest calculation still included the encounter, but at current time the encounter is more than 14 days old. With the next calculation the result is consistent again

> PR :https://github.com/corona-warn-app/cwa-app-android/pull/4618
