### ISSUE TITLE
Test Result not obtainable without google play

### ISSUE THREAD

**Issue by NikoBergemann** [corona-warn-app/cwa-app-android#4419]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Huawei P40 lite
- Android version: 10 EMUI 10.1.0.364
- App version: 2.13.2

## Describe the bug

When checking for my test result ("TEST ANZEIGEN"), I get a pop-up thanking me for sharing my result ("Einverständnis 'Andere warnen' erteilt").
When giving consent to that ("WEITER"), the app seems to get stuck while retrieving my result ("Datenabruf").
After a while, I get an error, which indicates that the app relies on google play for whatever reason and will not show me my results.

## Steps to reproduce the issue

1. Have a mobile phone without google play
2. Click on "TEST ANZEIGEN"
3. Click on "WEITER"
4. Seems to be stuck
![e6e6626a-14ac-4724-9c90-e359fcd864d0](https://user-images.githubusercontent.com/36935332/142756667-c7f4e8d9-6454-4a1d-a1d3-0550694c4ca4.jpg)
5. See error
![a1299547-a620-4475-a5ba-8429a7f82582](https://user-images.githubusercontent.com/36935332/142756657-a3b744a6-418c-4571-974a-8951269b842a.jpg)
![149e85bf-43df-4809-b7d5-bad507b5224d](https://user-images.githubusercontent.com/36935332/142756659-272a63d7-dd20-4556-8623-432dceb3bb20.jpg)

## Expected behavior

At least a workaround to get my test results online via some website or per mail.

**Comment by thomasaugsten** [comment]
What is happening when you decline the consent.

The fastest solution is to install Google Apps/Google Play services on your phone

**Comment by MikeMcC399** [comment]
@NikoBergemann 
You might find the thread https://github.com/corona-warn-app/cwa-app-android/issues/2117 useful for your device.

**Comment by fynngodau** [comment]
It seems a bit silly to me to query a preconsent once the test result is already available if the result is not positive. In this case the preconsent will not be needed.

**Comment by Jo-Achim** [comment]
Even if the causes may be different, I would like to insert a cross-reference here: https://github.com/corona-warn-app/cwa-app-android/issues/4338#issue-1046748620.

**Comment by mtwalli** [comment]
As a workaround , you can register tests under family tests, it is not required to share your keys in this case, but if it is a personal test it is still required to share the keys
