### ISSUE TITLE
Android 11 Beta 1

### ISSUE THREAD

**Issue by testus3r-ui** [corona-warn-app/cwa-app-android#442]
API ist auf dem Pixel 3 vorhanden

Android Version: 11 Beta 1

Build-Nummer: RPB 1200504018

-------------------------------------------------------------

Habe die Apk installiert, bekomme aber folgende Fehlermeldung.

URSACHE: 9002 Etwas ist schief gelaufen.

17: API:

Nearby. EXPOSURE NOTIFICATION API

is not available on this device.

Connection failed with:

ConnectionResult{statusCode=UNKNOW N_ERROR_CODE(39507), resolution=null, message=null}

**Comment by IXArcanumXI** [comment]
Bist du von Google denn überhaupt gewhitelistet, also konntest du die APK mit den offiziellen Keys signieren? Ansonsten ist das Verhalten so gewollt, denn nur korrekt signierte APKs dürfe auf die API zugreifen. Allen anderen wird der Zugriff verweigert, was dann in dieser Fehlermeldung mündet.

**Comment by marcmuschko** [comment]
Hello @testus3r-ui,

thanks for reaching out! This is a [known issue](https://github.com/corona-warn-app/cwa-app-android/blob/master/README.md) and it occurs when a device is missing the necessary whitelisting within GMS. 
For further information please have a look [here](https://github.com/corona-warn-app/cwa-documentation/issues/214), our community managers will share updates if this status changes.
As this is very similar to the referenced issue, I am closing this one.

Hope this helps!
Best regards,
Marc

**Comment by KPJ24** [comment]
Hallo,
die App aus Italien läuft bei mir Wunderbar. Lediglich die Deutsche nicht. 
Bei ist die selbe Fehlermeldung (unter Details, wenn die kommt), nur die Nummer hat sich mit dem Update von 9002 auf 3 geändert.
Was kann ich tun um das Problem zu beheben?
LG KPJ24

**Comment by IXArcanumXI** [comment]
KPJ: Du müsstest von Google gewhitelisted werden. Das wird zu 99% nicht passieren. Sobald die App final draußen und im Play Store erhältlich ist, brauchst du das nicht mehr - dann wird sie funktionieren,

**Comment by niklas88** [comment]
I just installed the app via the Play Store and I'm getting this error.
This is on a stock and up to date Android 10 Pixel 3A, Bluetooth is on, Location Services and Location History is on, I'm in Germany (though the OS language is English) and there are absolutely zero special OS interfering Apps like anti virus or such.

**Comment by kollokollo** [comment]
I just got the same error (9002). About 5 Minutes after installation. I wanted to make a screenshot, but this did not work (screenshot not permitted for this screen). I got it only once. Unfortunately I cannot reproduce it. Further: Al though I can switch the switch "exposure logging", but independently of the position of that switch it always shows "stopped". HUAWEI Phone, Android 9, not rooted.

**Comment by lafluedecologne** [comment]
Ich hänge mal den Screenshot rein. Vielleicht hilfts ja.

![550ca2bd-55f4-4d2b-9237-aec005e75177-1](https://user-images.githubusercontent.com/3999726/84789560-a5fc2b00-aff0-11ea-805e-97fcb06dbb5a.jpg)

**Comment by niklas88** [comment]
Somehow this issue solved itself for me, I did reinstall the app and it still happened but then yesterday evening I checked again and suddenly it worked. Maybe this was some weird roll out glitch.

**Comment by niklas88** [comment]
> Ich hänge mal den Screenshot rein. Vielleicht hilfts ja.
> 
> ![550ca2bd-55f4-4d2b-9237-aec005e75177-1](https://user-images.githubusercontent.com/3999726/84789560-a5fc2b00-aff0-11ea-805e-97fcb06dbb5a.jpg)

That looks like an unrelated issue to me, actually at a wild guess that looks like a file corruption.

**Comment by derfasthirnlosenick** [comment]
Ich habe die App seit vorgestern auf meinem Pixel 3a mit der Android 11 Beta 1 (bzw. jetzt 1.5) laufen - bisher ohne Probleme.
Von daher vllt. eher ein lokales Problem?

**Comment by Aehtna** [comment]
> Ich hänge mal den Screenshot rein. Vielleicht hilfts ja.
> 
> ![550ca2bd-55f4-4d2b-9237-aec005e75177-1](https://user-images.githubusercontent.com/3999726/84789560-a5fc2b00-aff0-11ea-805e-97fcb06dbb5a.jpg)

I have this pop up on my screen too. Is there a solution?
