### ISSUE TITLE
502 Bad Gateway during Exposure Check

### ISSUE THREAD

**Issue by Lionfox2** [corona-warn-app/cwa-app-android#4442]
## Technical details

- Device name: Google Pixel 6
- Android version: 12
- App version: 2.14.1

## Describe the bug

When I want to check for positive encouters I get during download the Error Message: Cause 4000: Something went wrong. Your Internet Connection may have been lost. Please ensure that you are connected to the Internet.

I already restarted the device, tried it again via WiFi and Mobile Data, and the error still continues. The device itself has an internet connection without problems.

Via click on details I get this error:

`Ursache:de.rki.coronawarnapp.exception.http.BadGatewayException: Error during web request: code=502 message=Bad Gateway body=<html><head><title>502 Bad Gateway</title></head><body bgcolor="white"><center><h1>502 Bad Gateway</h1></center><hr><center>nginx</center></body></html>'	at de.rki.coronawarnapp.http.HttpErrorParser.intercept(HttpErrorParser.kt:14)	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)	at de.rki.coronawarnapp.http.interceptor.RetryInterceptor.intercept(RetryInterceptor.kt:3)	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:4)	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)	at de.rki.coronawarnapp.http.interceptor.WebSecurityVerificationInterceptor.intercept(WebSecurityVerificationInterceptor.kt:3)	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:25)	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:12)	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)	at java.lang.Thread.run(Thread.java:920)`

## Expected behaviour

Encouter Check

**Comment by Ein-Tim** [comment]
Also reported in https://github.com/corona-warn-app/cwa-server/issues/1614

**Comment by Alexispap** [comment]
Got the same problem on a Samsung S10+.

**Comment by Ein-Tim** [comment]
@Alexispap This issue affects all users as it's server side. Thanks anyways for confirmation

**Comment by dsarkar** [comment]
@Lionfox2 @Alexispap @Ein-Tim Thanks for reporting, should work again now. 


---
Corona-Warn-App Open Source Team
