### ISSUE TITLE
where I can find the app

### ISSUE THREAD

**Issue by riwad17** [corona-warn-app/cwa-app-android#4443]
Hello, I'm new here and still a beginner. can someone please explain to me where I can find the app

**Comment by MikeMcC399** [comment]
@riwad17 
> where I can find the app

The simple answer to the question is that the Android Corona-Warn-App is published and available on the [Google Play Store](https://play.google.com/store/apps/details?id=de.rki.coronawarnapp).

You can also search on your mobile Android device for `corona-warn-app` in Google Play Store.

The pre-requisites are listed on https://www.coronawarn.app/en/faq/#availability, for Android, this is Android version 6 or higher and Google Play services must also be installed.

In addition, if your Google account is not linked to Germany, you can only access the app if your account country is on the list on https://www.coronawarn.app/en/faq/#international, which basically includes Germany and other European countries.

Assuming that your device fulfills the pre-requisites, another way to find the app is through
Settings > Google > COVID-19 Exposure Notifications
then tap "Select your region" > Germany > Continue 
which finds "Corona-Warn-App" and allows you to install it.

**Comment by dsarkar** [comment]
Hi @riwad17,

Thanks for the question. We appreciate that you want to install the app. Your question was answered by @MikeMcC399. Did you have success in installing the app or do you have more questions? 

Best, DS


---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@dsarkar 
This issue should be closed. The question is answered and there was no further response from @riwad17.
