### ISSUE TITLE
The app displays a wrong vaccination date if the OS language is set to english

### ISSUE THREAD

**Issue by v0lkc** [corona-warn-app/cwa-app-android#4454]
## Avoid duplicates
* [*] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [*] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [*] Bug is not already reported in another issue

## Technical details

- Device name: Google Pixel 4XL
- Android version: 12
- App version: 2.14.1

## Describe the bug

The default language of my device is set to english and imho the app displays vaccination dates in a wrong format. It seems to use "dd/MM/yyyy" but it should use "MM/dd/yyyy" instead (which is btw. also used for displaying the birth date).

![Screenshot_20211130-110612](https://user-images.githubusercontent.com/78809837/144028477-3648342e-b7a5-4cfb-baaf-c1fab16ae22a.png)

## Steps to reproduce the issue

1.) set device language to english
2.) Open the "Certificates" view
3.) Open an already registered vaccination certificate

## Expected behaviour

Vaccination dates should be displayed with the right format (Imho "MM/dd/yyyy") and be consistent with the format used for displaying the birth date. If this is not possible for whatever reasons, the format should be shown to the user.

## Possible Fix

See above

**Comment by MikeMcC399** [comment]
@v0lkc 
The default format for date in Android depends on exactly which English locale you choose. English (United States) is not the same as English (United Kingdom), for instance.

Which exact English locale have you set on your device?

There are two related open issues:

- https://github.com/corona-warn-app/cwa-documentation/issues/710
- https://github.com/corona-warn-app/cwa-app-android/issues/4112

**Comment by v0lkc** [comment]
@MikeMcC399 But why is it then different to the birthdate? Android set it to "English (Germany)" automatically

**Comment by MikeMcC399** [comment]
@v0lkc 
If your locale is set to English (Germany) then any dates displayed in numeric format should use "dd/MM/yyyy" format.

So the vaccination date format is correct and the birthday date format is incorrect (similar to issue https://github.com/corona-warn-app/cwa-app-android/issues/4112).

If you want dates displayed with the month first, then you can change the locale of your device to English (United States) as a workaround.

**Comment by v0lkc** [comment]
Ok thank you. I'm closing this ticket then
