### ISSUE TITLE
note text is confusion in Print-PDF

### ISSUE THREAD

**Issue by iseries** [corona-warn-app/cwa-app-android#4468]
## Current Implementation
Currently, a PDF is created for the proof of vaccination certificate using the print function, with a note next to the QR code. This text is extremely confusing, as it is not clear when you need the "Corona Warn App" and when you need the "CovPass App". It should be avoided that people who just want to check a vaccination certificate use the "Corona Warn App".

![image](https://user-images.githubusercontent.com/6272363/144573066-cb38ecd3-bc0e-4e36-baa5-c08f47022e8a.png)

## Suggested Enhancement
Separate the use cases in the note text. When do you have to scan with the "Corona Warn App" and when with the "CovPass App"

## Expected Benefits
More clarity about which app should be used for which usecase to scan the QR code

**Comment by Ein-Tim** [comment]
Neiterh CovPass nor the Corona-Warn-App are intended to be used to check certificates. Only CovPassCheck can check certificates. 
CovPass and the Corona-Warn-App are simply wallet apps and store the certificate.

**Comment by mlenkeit** [comment]
@iseries thanks for opening the issue!

The templates are synchronized between Corona-Warn-App and CovPass. The leading version is available under https://github.com/Digitaler-Impfnachweis/certification-apis/tree/master/templates. 

Would you mind opening the issue there?

Generally, I think the note itself is correct: you can scan the QR code with the Corona-Warn-App or CovPass App _to carry a digital version with you_. To verify the authenticity and validity of the QR code/certificate, you should use the CovPassCheck App.

Is this the differentiation that you are missing here on the print version?

**Comment by iseries** [comment]
@mlenkeit You got it right to the point. Thanks for the feedback! I will create an issue in the mentioned repository.

**Comment by mtwalli** [comment]
Issue for CovPass has been addressed and from CWA side no changes are required here
