### ISSUE TITLE
CWA does not carry out risk checks, not even in foreground

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-android#4472]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Huawei P Smart 2019
- Android version: 10
- App version: 2.14.1

## Describe the bug

The CWA does not carry out a risk check when opened, even though I'm connected to the internet via WLAN and the last risk check is older than 4h:

<img src="https://user-images.githubusercontent.com/67682506/144643500-20683d45-8400-43d5-805d-a355546169c2.jpg" width="300">

## Steps to reproduce the issue

No really clear, open the app and see that no new risk checks are carried out.

## Expected behaviour

Risk checks should be carried out reliably, especially in foreground. 

## Possible Fix

Not sure.

## Additional context

I reported this bug some days ago at CCTG: https://codeberg.org/corona-contact-tracing-germany/cwa-android/issues/196

---
Internal Tracking ID: [EXPOSUREAPP-11063](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11063)

**Comment by DeadBytes1990** [comment]
Can confirm this just happened on my OnePlus 8 Pro.
* WiFi Connected
* Risk checks had been conducted at 2:34 and 6:34 according to Google Play Services
* No risk check was conducted at 10:34, no keys were downloaded according to Google Play Services, nor did CWA perform any checks. The app was active in the foreground at that time
* OygenOS 11, CWA 2.14.1

**Comment by svengabr** [comment]
Internal Tracking ID: EXPOSUREAPP-11063

**Comment by svengabr** [comment]
@Ein-Tim @DeadBytes1990 thanks for your reports! I created a ticket and assigned it accordingly.

**Comment by dsarkar** [comment]
@DeadBytes1990 @Ein-Tim Is this issue reproducible?  Also, does a risk check start eventually? I understand you expect it about every 4 h being connected to wifi. What is the frequency you observe?

**Comment by Ein-Tim** [comment]
@dsarkar 

This issue is not easily reproducible, there is no clear pattern when and when not this happens. However, I have this issue min. once per day. 

The problem is that even if the last risk check happened more than 4h ago, you open the app in foreground & are connected to the internet with WLAN, there is no new risk check carried out, for some reason.

**Comment by dsarkar** [comment]
@DeadBytes1990 @Ein-Tim ok, thanks for the feedback. We would appreciate an error report, should you be able to reproduce this issue.

**Comment by vaubaehn** [comment]
> We would appreciate an error report, should you be able to reproduce this issue.

Means, you will need to activate error logging in any case, and then submit the error report after a delayed/for an unexpected long time not carried out risk check.
@DeadBytes1990 please then provide the error report id here in this issue.

**Comment by DeadBytes1990** [comment]
> @DeadBytes1990 @Ein-Tim Is this issue reproducible? Also, does a risk check start eventually? I understand you expect it about every 4 h being connected to wifi. What is the frequency you observe?

The last time I noticed this an update occured at 11.39, so roughly an hour after the expected time. However that was also when I decided to force close and restart the app.

**Comment by dsarkar** [comment]
@DeadBytes1990 @Ein-Tim Thanks for coming back. So eventually, there is a risk check, and the delay is about an hour. I will check with the dev team, however, I think this is within the expected behaviour.

**Comment by Ein-Tim** [comment]
@dsarkar 

Are you sure that it is the intended behavior of the app to not carry out risk checks in foreground, even though connected to WLAN and 4h since the last check was done?

**Comment by dsarkar** [comment]
@Ein-Tim The app should do carry out risk checks in foreground. However, if it does it after about 5 h instead of 4 h, I think is still within the expected behaviour. Did you observe that the app stopped completely carrying out risk checks when in the foreground?

**Comment by Ein-Tim** [comment]
@dsarkar 

I saw e.g. yesterday that the last update was at 12:38 & when I opened the app at around 20:30, there was no risk check carried out.

**Comment by dsarkar** [comment]
@Ein-Tim Ok, thanks, I will raise the topic tomorrow internally.

**Comment by dsarkar** [comment]
@Ein-Tim Your observations refer to Android only?

**Comment by Ein-Tim** [comment]
@dsarkar Confirm, Android only. I'll try to reproduce it today, but at the moment, it seems to work reliably. 

Interesting side note: This mostly happened when the phone was not connected to the internet for a longer period of time, is then connected to the internet & CWA is opened. Maybe something with the network availability check?

**Comment by dsarkar** [comment]
@Ein-Tim ok, thanks for the info

**Comment by dsarkar** [comment]
@DeadBytes1990  @Ein-Tim can you create an error log, please? Log should cover a larger time span without carrying out the risk checks. Thanks.

**Comment by dsarkar** [comment]
@DeadBytes1990 @Ein-Tim Any updates here? Could you reproduce the issue and generate an error log?

**Comment by Ein-Tim** [comment]
@dsarkar 

I'm currently monitoring the situation under 2.15, it seems to have improved drastically. Will update you soon!

**Comment by dsarkar** [comment]
@Ein-Tim ok, thanks for the feedback...standing by.

**Comment by Ein-Tim** [comment]
I can't reliable reproduce this bug anymore, thus closing this issue.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for the feedback. For the moment we will close the internal ticket. As usual, if necessary, re-open, please.

**Comment by Ein-Tim** [comment]
So, here we go.

It's currently 17:07, CWA last carried out a risk check at 12:54 and the next risk check should be carried out at 16:54. 
However, CWA still shows this, as of now:

<img src="https://user-images.githubusercontent.com/67682506/147953062-64ad2bc1-3c44-45e1-8056-44387bfa14b4.jpg" width="300">

**Comment by Ein-Tim** [comment]
I think this whole topic is very complex, including some timeouts which may happen. 
E.g. last risk check was at 12:00h, next risk check is done at 16:30h in the background but times out, thus the app falls back to the last successful risk check and when the user opens the app at 18:00h it still shows 12:00h and does not attempt to carry out a risk check as 4h did not pass since the last risk check which counts into the rate limit (at 16:30h).

**Comment by Ein-Tim** [comment]
@dsarkar I'm still experiencing this issue on 2.16.2: 
<img src="https://user-images.githubusercontent.com/67682506/151223754-6bac459d-11c1-4734-9abd-1b4e4e8c92e2.jpg" width="300">

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Are you still experiencing this issue?

Do you have "Prioritized Background Activity" switched on?
(Dreipünktchensymbol > Einstellungen > "Priorisierte Hintergrundaktivität" in German)

Did you activate and take a look at an error report to see if there are any reasons to be found there?

**Comment by Ein-Tim** [comment]
@MikeMcC399 

> Are you still experiencing this issue?

Yes, sometimes. But it is not possible to reliable reproduce this. I made a guess in https://github.com/corona-warn-app/cwa-app-android/issues/4472#issuecomment-1013785617 why I think this happens.

> Do you have "Prioritized Background Activity" switched on?

Yes.

> Did you activate and take a look at an error report to see if there are any reasons to be found there?

I tried this but as I can't reproduce this reliable the logs get so long that it's really complicated to find relevant things in it. Are there any keywords I could search for?

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> Are there any keywords I could search for?

I made a list of keywords I found in https://github.com/corona-warn-app/cwa-app-android/issues/4740#issuecomment-1022388959 which were:

```
TracingStateProvider
TracingRepository
RiskLevelStorage
DownloadDiagnosisKeysTask
RiskLevelTask
DefaultRiskLevels
```

It would be good to have a log analyzer scraper script to pull these out. I wonder if anybody has written anything like that?

**Comment by Ein-Tim** [comment]
Thank you @MikeMcC399 

I will start logging again and should I notice the issue, I will analyze the log file using the keywords!

**Comment by dsarkar** [comment]
@Ein-Tim https://github.com/corona-warn-app/cwa-app-android/issues/4472#issuecomment-1022472377 So, no risk check for 4 days?

**Comment by dsarkar** [comment]
@MikeMcC399 Does this help you? Bash script find your keywords (case insensitive -i) and prints one line before and one line after the matched line.

```
cat "application.log" | grep -i -B1  -A1'TracingStateProvider\|TracingRepository\|RiskLevelStorage\|DownloadDiagnosisKeysTask\|RiskLevelTask\|DefaultRiskLevels'
```

**Comment by Ein-Tim** [comment]
> So, no risk check for 4 days?

@dsarkar No, I posted this comment on a later date, there was no risk check for at 18:50 for some reason and also when I opened the app at 19:24 no check was done.

**Comment by MikeMcC399** [comment]
@dsarkar 
Thanks for the script! That might help to narrow down the information to scroll through, although it is still quite a difficult manual process to find an actual issue.

**Comment by dsarkar** [comment]
@Ein-Tim So, for how long there was no risk check? Did the risk check eventually happen? All day on WIFI I assume.

**Comment by Ein-Tim** [comment]
@dsarkar In https://github.com/corona-warn-app/cwa-app-android/issues/4472#issuecomment-1022472377 I posted a screenshot I took at 19:24h. The last risk check which was carried out was at at 14:50h. However, there was no new check at 18:50h and also not when I opened the app at 19:24h.

**Comment by swekkx** [comment]
Adding my comments from another post:

 I am facing the same issue again.

Error report
ID 8A16FD407C2934A7D7B3

No update since 9 am today. Already restarted my phone.

![Screenshot_20220202-200457_Corona-Warn](https://user-images.githubusercontent.com/96697098/152222797-c52307f0-b635-4400-82e7-0c9f8cdca300.jpg)


I am connected to wifi and tried to update the whole day. My phone has android 12 with the most current patches.

It searches for 1 sec and then just show the status view.

**Comment by Andiadm** [comment]
I have a status of 18:14 CET. What happened to me once is that I did not have enough memory on my cellphone. The CWA is now up to 190MB in memory (due to the huge ammount of positively tested users) and that can create problems.
Maybe it would be a smart idea to move the database to the SD card automatically if available to prevent such shortfalls.

**Comment by MikeMcC399** [comment]
@Andiadm 
>  What happened to me once is that I did not have enough memory on my cellphone. 

Did you get an error message when your phone ran out of space or did it die quietly?

**Comment by Andiadm** [comment]
There was a message in Android when you swipe top bottom in the OS. Of course in the morning, between EMails, News Services and Social Media you have 20 of those and you tend to not see them.
Would be much better to alert on low memory - which in essence prevents the App from doing its job - not by OS notification but within the App itself IMHO.

**Comment by Ein-Tim** [comment]
Again: CWA could carry out a risk check, but it does not: 

<img src="https://user-images.githubusercontent.com/67682506/152856951-70d32dab-9314-466d-a040-0d6bdd58f715.jpg" width="300">

**Comment by dsarkar** [comment]
@Ein-Tim You are also low on memory? I guess not....

**Comment by Ein-Tim** [comment]
@dsarkar 

No, more than 40 GB are free.

**Comment by vaubaehn** [comment]
> @Ein-Tim You are also low on memory? I guess not....

@dsarkar Low memory is not necessarily the problem. Like now discussed in the other issue, we found out, that CWA is providing the full bunch of Diagnosis Keys to ENS what it can access. In the real world example here https://github.com/corona-warn-app/cwa-app-android/issues/4732#issuecomment-1031683118 it was 119MB per call.
When ENS picks up the call, it's copying all files from CWA's cache directory to ENS directory, then extracting all zipped files, then validating the "white listed health authority signature" (which _might_ need a network call, but I'm not sure on this one), then comparing all single TEKs of the files with already stored TEKs in a db... this takes some time... the question is, why nothing happens... Either CWA can't access the server to download more DKs, or it already had recent DKs and wanted to provide them to ENS, but ENS did not "pick up the (API) call"... It picked up the call, but did not sent back a proper response that CWA can work with... Maybe ENS just needs more time to respond to CWA because of system load... Or the UI just got stuck (did not update like necessary)...

**Comment by vaubaehn** [comment]
@Andiadm The issue you reported is tracked in #4732

**Comment by Ein-Tim** [comment]
A Twitter user reported that she has experienced this issue on 3 separate phones all with latest CWA and either on Android 11 or Android 10 installed.

[Link to Twitter](https://twitter.com/NinaEichinger/status/1492263798199177218?s=20&t=fRQQMfQ2qhtvpO9NwFDqXQ)

**Comment by Ein-Tim** [comment]
@dsarkar 

Version 2.19.0 of CWA and I am currently (17.03.22 - 14:00h) seeing this: 
<img src="https://user-images.githubusercontent.com/67682506/158813925-bc832535-005c-4dd9-abe8-674fb727a521.jpg" width="300">

**Comment by Ein-Tim** [comment]
@thomasaugsten / @mlenkeit 

I'd appreciate if someone could take a look at this log. It captured when the app shortly showed "Prüfung läuft..." but then abandoned the check again. 

The log has the ID 46D50109902D0943421E.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for reporting, forwarded to internal ticket.

**Comment by Ein-Tim** [comment]
@dsarkar 

Same issue today, last check yesterday at 19:36, app's in foreground but still does not carry out a check.

I think version 2.19 drastically worsened this problem.

**Comment by lukaschristmann** [comment]
> It captured when the app shortly showed "Prüfung läuft..." but then abandoned the check again.

I just now (16.03.2022 7:30) noticed the same issue, restarting the app leads to a short "check" ( less than 2 seconds total ), then back to "Updated: Yesterday, 11:26) - i did not yet force quit cwa or restart the phone.

**Comment by Ein-Tim** [comment]
@thomasaugsten or @mtwalli 

Please, take a look at the log or try to reproduce the problem yourself. This seems to affect most users and isn't and Edge case anymore.

**Comment by mlenkeit** [comment]
We found something in the error report that might explain why 2.19 releases are affected by this and we are checking if this can be fixed via a server-side change.

**Comment by mlenkeit** [comment]
The server change was rolled out and devices on 2.19 will recover automatically, although this may take up to 24 hours. If users open the app, recovery may start earlier.

Root case was unfortunate combination of events: a new configuration parameter on the server was not set. The client doesn't use the parameter at the moment, but the absence of the parameter caused the parsing of the configuration to fail. As a result, the client falls back to a previous configuration or a default one. In case the default configuration is used (which was the case for the device that send the error report), the risk calculation is only executed once a day instead of six times a day. 

The default is deliberately set to `1` to be more cautious/pessimistic in such cases. This is something that we are re-evaluating now.

**Comment by vaubaehn** [comment]
@mlenkeit 
Thanks for your detailed repsonse! ❤️ Very much appreciated, as community also learns much about how CWA is processing data - and that may help us to better assist other users, or to hunt bugs with you together, and make life hopefully a bit easier also for you in future cases.

**Comment by Ein-Tim** [comment]
I can confirm the fix on my Huawei P Smart 2019.

I will leave this issue open to see whether the originally reported issue will still occur in 2.19.

**Comment by Ein-Tim** [comment]
@mlenkeit 

Sadly I have to revoke my confirmation of the fix.

I am encountering this issue again, last risk check on my device is at 12:44h today and although I'm connected to the Internet via WLAN the app does not carry out a new risk check.

I have logged this in the error log with the ID 248D404EEAA41D18F47E.

**Comment by thomasaugsten** [comment]
Can you please double check if there is also no check in the Google Settings

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Confirm, last entry in the Google Settings 12:44h.

**Comment by Andiadm** [comment]
2.19 was delivered to my Android around 17:00. Last Check 19:13 - 2:20 ago. All running fine here, seems not to be a general problem.

**Comment by Ein-Tim** [comment]
@Andiadm 

It could be too early for this problem to take effect if you only installed the update some hours ago.

I'm currently getting in touch with other Android users who could confirm/not confirm this issue.

**Comment by NKarolak** [comment]
For me, the check issue that was introduced with 2.19 seems to be fixed.

**Comment by Ein-Tim** [comment]
Risk checks are again running for me, I'm continuing to monitor the situation.

**Comment by swekkx** [comment]
My app did not execute any checks since 12 hours.

ID 14082D4521F144CC8D5B 

![Screenshot_20220409-231605_Corona-Warn](https://user-images.githubusercontent.com/96697098/162593244-b8582923-b8b2-4651-a48a-986ac57b8f77.jpg)

**Comment by dsarkar** [comment]
@swekkx Thanks for reporting. During the mentioned 12 hours you have been on Wifi or mobile data? Thanks for your feedback. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by swekkx** [comment]
> @swekkx Thanks for reporting. During the mentioned 12 hours you have been on Wifi or mobile data? Thanks for your feedback. Best wishes, DS
> 
> Corona-Warn-App Open Source Team

I was mostly on wifi. There wasn't a midnight check too. Now there is a check running indefinitely.

ID BC49CEB093E9C35EE350

**Comment by swekkx** [comment]
> > @swekkx Thanks for reporting. During the mentioned 12 hours you have been on Wifi or mobile data? Thanks for your feedback. Best wishes, DS
> > Corona-Warn-App Open Source Team
> 
> I was mostly on wifi. There wasn't a midnight check too. Now there is a check running indefinitely.
> 
> ID BC49CEB093E9C35EE350

After 36 hours still no update on my S21

**Comment by dsarkar** [comment]
@swekkx Thanks again, we will forward your report.

**Comment by dsarkar** [comment]
@Ein-Tim @swekkx Is this still an issue with CWA 2.22? Thanks for your feedback.

**Comment by Ein-Tim** [comment]
@dsarkar I continue to monitor this and will when I'm sure that this is not a problem anymore.

**Comment by Ein-Tim** [comment]
I'm currently in contact with a user on Twitter who is affected by this problem. His environment is:

- Android 9
- CWA 2.24.2
- Samsung Galaxy S8+

I will try to get an error report.

**Comment by dsarkar** [comment]
@Ein-Tim Any luck with obtaining an error report?

**Comment by Ein-Tim** [comment]
@dsarkar Not yet...

**Comment by Ein-Tim** [comment]
Okay, I did not receive an error report and I'm not able to reproduce this issue myself. Thus I'm closing this issue as fixed now.

**Comment by Ein-Tim** [comment]
@mlenkeit / @thomasaugsten 

I've got another report reg. This bug on Twitter.
Here's the error report I requested from the user: ID D22ACB53BA7C6F48A536
