### ISSUE TITLE
Ursache 2001 app funktioniert nicht 

### ISSUE THREAD

**Issue by steffi85** [corona-warn-app/cwa-app-android#4481]
Meine App funktioniert nicht mehr 

---
Internal Tracking ID: [EXPOSUREAPP-10936](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10936)

**Comment by vaubaehn** [comment]
This is a duplicate of https://github.com/corona-warn-app/cwa-app-android/issues/968 - please close here an follow in #968.
Dies ist ein Duplikat von Issue https://github.com/corona-warn-app/cwa-app-android/issues/968 - bitte hier schließen und in #968 weiter folgen.
Thanks/Danke!

**Comment by dsarkar** [comment]
@steffi85 Thanks everybody for reporting! Internal Tracking ID: [EXPOSUREAPP-10936](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10936)
