### ISSUE TITLE
Incident: All Android App users are seeing "URSACHE 20001"

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-android#4482]
# Details follow ASAP

## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name:
- Android version:
- App version:

## Additional context

Error Report: ID 2F87B1F31E3EF5177507

**Comment by vaubaehn** [comment]
I do not see Error 2001 currently (CWA 2.6.1, only one outdated RAT registered)

**Comment by vaubaehn** [comment]
This is a duplicate of https://github.com/corona-warn-app/cwa-app-android/issues/968 - please close here an follow in #968.
Dies ist ein Duplikat von Issue https://github.com/corona-warn-app/cwa-app-android/issues/968 - bitte hier schließen und in #968 weiter folgen.
Thanks/Danke!

**Comment by RidculIy** [comment]
> This is a duplicate of #968 - please close here an follow in #968. Dies ist ein Duplikat von Issue #968 - bitte hier schließen und in #968 weiter folgen. Thanks/Danke!

Hallo vaubaehn, 

bitte nochmal prüfen. Die Fehlermeldung mag identisch zu #968 sein, das Verhalten weicht jedoch ab:

Auf zwei unterschiedlichen Android-Geräten tritt diese Meldung unabhängig voneinander auf.
Beide Nutzer haben sich heute testen lassen.
Die App an sich funktioniert, was doch ein erheblicher Unterschied zu #968 darstellt.
Sobald jedoch der Test abgerufen werden soll, erfolgt Ursache 2001

**Comment by dsarkar** [comment]
Thanks everybody for reporting! Internal Tracking ID: [EXPOSUREAPP-10936](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10936)

**Comment by RidculIy** [comment]
Hi @vaubaehn


danke für das Feedback. Im Augenblick tritt die Fehlermeldung nicht mehr auf.

**Comment by Ein-Tim** [comment]
This problem seems fixed, but there is a new problem reported as https://github.com/corona-warn-app/cwa-documentation/issues/772 now. 

Closing this issue.
