### ISSUE TITLE
Abruf PCR Test funktioniert nicht (Ursache 2001)

### ISSUE THREAD

**Issue by mm1711** [corona-warn-app/cwa-app-android#4483]
Seit heute Nachmittag kommt beim Öffnen der App die Fehlermeldung "URSACHE: 2001 ..."
Das Sicherheitszertifikat ist aktiviert. Daran liegt es also nicht.

---
Internal Tracking ID: [EXPOSUREAPP-10936](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10936)

**Comment by d3nn15U** [comment]
Same here.

**Comment by rbccrvn** [comment]
Bei mir auch...

**Comment by KyrAir** [comment]
Seit 1 stunde kommt beim Öffnen der App die Fehlermeldung "URSACHE: 2001 ..."
Das Sicherheitszertifikat ist aktiviert. Daran liegt es also nicht. Wie kommt man nun an sein PCR Ergebnis

**Comment by Kris7684** [comment]
Das gleiche auch bei mir

**Comment by vaubaehn** [comment]
This is a duplicate of https://github.com/corona-warn-app/cwa-app-android/issues/968 - please close here an follow in #968.
Dies ist ein Duplikat von Issue https://github.com/corona-warn-app/cwa-app-android/issues/968 - bitte hier schließen und in #968 weiter folgen.
Thanks/Danke!

**Comment by dsarkar** [comment]
@Kris7684 @mm1711 @KyrAir Danke für die Berichte! Wir gehen dem nach. Ansonsten, bitte @vaubaehn's Hinweis folgen. 

---
Corona-Warn-App Open Source Team

**Comment by mm1711** [comment]
Ich glaube nicht dass es ein Duplikat ist. Die Lösung unter FAQ hat damit nichts tun. Der genannte Thread ist auch vom August. Bei mir kam der Fehler bis heute Nachmittag nicht.

Am 6. Dezember 2021 17:24:42 MEZ schrieb vaubaehn ***@***.***>:
>This is a duplicate of https://github.com/corona-warn-app/cwa-app-android/issues/968 - please close here an follow in #968.
>
>Dies ist ein Duplikat von Issue https://github.com/corona-warn-app/cwa-app-android/issues/968 - bitte hier schließen und in #968 weiter folgen.
>
>Thanks/Danke!
>
>
>
>-- >
>You are receiving this because you authored the thread.
>
>Reply to this email directly or view it on GitHub:
>
>https://github.com/corona-warn-app/cwa-app-android/issues/4483#issuecomment-986935214
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by rbccrvn** [comment]
[#968](https://github.com/corona-warn-app/cwa-app-android/issues/968) durchgegangen, aber keine sinnhafte Verbindung zu dem aktullen Problem gefunden. Problem wie oben von mm1711 beschrieben besteht weiterhin.

**Comment by mm1711** [comment]
Bei funktioniert die Verbindung wieder. Allerdings wird der PCR Test vom letzten Freitag immer mit "Ergebnis liegt noch nicht vor" angezeigt. Das ist falsch, ich habe das Ergebnis bereits am Samstag Abend direkt vom Labor als PDF  
angerufen

Am 6. Dezember 2021 18:12:30 MEZ schrieb rbccrvn ***@***.***>:
>[#968](https://github.com/corona-warn-app/cwa-app-android/issues/968) durchgegangen, aber keine sinnhafte Verbindung zu dem aktullen Problem gefunden. Problem wie oben von mm1711 beschrieben besteht weiterhin.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/corona-warn-app/cwa-app-android/issues/4483#issuecomment-986978439
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Ein-Tim** [comment]
I can't register new tests under iOS or Android at the moment, fails with no internet connection error message.

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-10936](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10936)

**Comment by Ein-Tim** [comment]
Habe den Fehler in https://github.com/corona-warn-app/cwa-documentation/issues/772 gemeldet, da er unter iOS und Android auftritt.

**Comment by vaubaehn** [comment]
Hi @mm1711 und @rbccrvn ,

doch, das von euch beobachtete Problem ist in der Tat ein Duplikat von #968 - zumindest in dem Sinne, dass in #968 dieselbe Fehlermeldung (2001) mit _3_ unterschiedlichen Fehlerursachen in Verbindung stehen, und die Corona-Warn-App leider nicht genügend differenziert (obwohl sie es theoretisch könnte). Eine dieser 3 Fehlerursachen trifft auch auf das Problem heute zu.
Das was ihr erlebt, liegt wahrscheinlich daran, dass die Telekom (TSI) ein Update für den Testresult-Server mitten am Tag "deployed" hat, und hierbei leider etwas schiefgegangen ist. Hier hab ich etwas mehr dazu geschrieben: https://github.com/corona-warn-app/cwa-app-android/issues/4482#issuecomment-986955454

Sicher bin ich mir auch deshalb, weil ein User diesen Stacktrace https://github.com/corona-warn-app/cwa-app-android/issues/968#issuecomment-986905244 geteilt hat, der Aufschluss darüber gibt, dass die verschlüsselte Verbindung "abreißt". Genau diesen Fehler hatten wir auch in #968 dokumentiert.
In der Zwischenzeit haben Nutzer andere, aber ähnliche Fehlmeldungen/Stacktraces geteilt, die zwar "eine andere Nummer" haben (9002), aber auf das selbe Grundproblem hinweisen.

Es macht deshalb Sinn, das heutige Problem in #968 weiter zu verfolgen, dort nachzuhaken, was der Auslöser für die Probleme war, wie sie in Zukunft vermieden werden können, und darum zu bitten, die CWA soweit zu erweitern, dass Fehlermeldungen zukünftig differenzierter dargestellt werden.

Vielen Dank!

**Comment by rbccrvn** [comment]
Danke für die Erklärung, so kann ich das nachvollziehen! Und danke für die Arbeit die du/ihr da reinsteck(s)t!

**Comment by svengabr** [comment]
I have just checked the linked Jira issue.

Jira Ticket is flagged as:
Resolution: `Wont Fix`
Status: `Obsolete`

Developer comment:
> Not an app issue. Related to the outage in PROD yesterday. Outage is resolved. Setting this to complete.

> Setting it to obsolete as it's not an app issue.
