### ISSUE TITLE
Fetching Diagnosis Keys not frequent enough

### ISSUE THREAD

**Issue by kbobrowski** [corona-warn-app/cwa-app-android#451]
## Describe the bug

Diagnosis Keys are downloaded only every 24 hours, and only ["days" endpoint is queried](https://github.com/corona-warn-app/cwa-app-android/blob/98218c7c01feb1cb0644e3032841157c59dcab40/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/CachedKeyFileHolder.kt#L97), which means that worst-case delay in exposure notification introduced by this design is 48 hours.

## Expected behaviour

App should synchronize Diagnosis Keys more frequently, and also use "hours" endpoint for fetching Diagnosis Keys published on current day.

## Possible Fix
2 hour interval for fetching was already specified in a documentation, but it was changed to 24 hours in [this pull request](https://github.com/corona-warn-app/cwa-app-android/pull/293/files#diff-b41019e95dac8464382703f8ec968662R106).

As for fetching hours for current day, this functionality existed but was removed in [this pull request](https://github.com/corona-warn-app/cwa-app-android/pull/185).

## Additional context

It should be possible to simply follow iOS app approach, where [Diagnosis Keys are fetched every 2 hours](https://github.com/corona-warn-app/cwa-app-ios/blob/6c7878166df0aeb16fac019730007ecf64e479ff/src/xcode/ENA/ENA/Source/Models/Task%20Scheduling/ENATaskScheduler.swift#L28), and "hours" endpoint is called during current day (function definition [here](https://github.com/corona-warn-app/cwa-app-ios/blob/6c7878166df0aeb16fac019730007ecf64e479ff/src/xcode/ENA/ENA/Source/Client/Client.swift#L216), called from [here](https://github.com/corona-warn-app/cwa-app-ios/blob/6c7878166df0aeb16fac019730007ecf64e479ff/src/xcode/ENA/ENA/Source/Services/Exposure%20Transaction/ExposureDetectionExecutor.swift#L60))

I've opened the issue [in documentation](https://github.com/corona-warn-app/cwa-documentation/issues/236), but this seems to be more an issue with Android implementation.

**Comment by SebastianWolf-SAP** [comment]
Let's restrict this discussion to a single issue. As this behavior needs to be consistent across all clients, we will only provide updates regarding this question in https://github.com/corona-warn-app/cwa-documentation/issues/236

Thanks for your understanding!

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
