### ISSUE TITLE
Unhelpful error message when trying to find testing center when no browser or maps app installed.

### ISSUE THREAD

**Issue by miku86** [corona-warn-app/cwa-app-android#4525]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Moto E LTE
- Android version: 10 (LineageOS 17.1)
- App version: 2.11.2.0 (from F-Droid)

## Describe the bug

I actually don't know if it is a bug or a really rare case.

When I want to find a testing center, I get the error:
```
CAUSE: 10
Something went wrong
...
```

The actual thrown exception is:

```
de.rki.coronawarnapp.exception.ExternalActionException:
Error during external navigation, likely due to bad target / action not available at
de.rki.coronawarnapp.util.ExternalActionHelper.openUrl(ExternalActionHelper.kt:90)
...
```

This seems plausible, because I don't have any browser or maps app installed.

## Steps to reproduce the issue

0. Have no browser and maps app installed
1. Go to 'Manage Your Tests"
2. Click on 'Continue'
3. Click on 'Find Testing Center'

## Expected behaviour / Possible Fix

The reason seems to be that there is no handler to open the URL for finding the testing center,
because I have no browser or maps app installed.

I expect to see some sort of better error message including a way how to solve this,
e.g. "Can't open URL, please install a browser."

Greetings
Michael

---
Internal Tracking ID: [EXPOSUREAPP-11013](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11013)

**Comment by dsarkar** [comment]
@miku86 Thanks for the report: Internal Tracking ID: [EXPOSUREAPP-11013](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11013)
Best wishes, DS 

---
Corona-Warn-App Open Source Team
