### ISSUE TITLE
Why is it not possible to scan QR codes from password protected files under Android? 

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-android#4528]
## Avoid duplicates
* [X] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Question is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Question has not already been asked in another issue

## Your Question
A Twitter user asked me why it is possible to scan QR codes from password protected files under iOS (pop up asks for entering the password) but not under Android ("Die gewählte Datei ist möglicherweise beschädigt oder passwortgeschützt und konnte daher nicht gelesen werden. Bitte wählen Sie eine geeignete Datei.")?

**Comment by dsarkar** [comment]
Hi @Ein-Tim,  Will come back to you. Did this user receive the QR code in a protected file?

**Comment by dsarkar** [comment]
@Ein-Tim For the moment maybe you can forward this message:

**DE**
Ab der Version 2.11 der CWA können QR-Codes aus Bilddateien und PDFs in die App importiert und ausgelesen werden. Die App kann jedoch keine QR-Codes aus passwortgeschützten Dateien auslesen. Wir empfehlen in diesem Fall, die Datei außerhalb der CWA zu öffnen, einen Screenshot des QR-Codes zu machen und anschließend den Screenshot zu importieren.

**EN**
Starting with version 2.11 of the CWA, QR codes from image files and PDFs can be imported into the app and read out. However, the app cannot read QR codes from password-protected files. In this case, we recommend opening the file outside the CWA, taking a screenshot of the QR code, and then importing the screenshot.

**Comment by Ein-Tim** [comment]
@dsarkar 

> Did this user receive the QR code in a protected file?

Yes.

I will forward the text, thank you!

**Comment by Ein-Tim** [comment]
@svengabr 

My question was not answered, if I haven't overlooked anything. 

While the text shared by @dsarkar says that the app can't scan QR-Codes from password protected files, this is obviously not true under iOS, see https://github.com/corona-warn-app/cwa-app-ios/pull/3589.

**Comment by dsarkar** [comment]
@Ein-Tim As far I understand: In iOS the functionality is already implemented on iOS level. That is the reason why it works on iOS but not on Android devices.

**Comment by Ein-Tim** [comment]
@dsarkar 

Ah okay. So under Android the app would have to handle this all by itself?

**Comment by dsarkar** [comment]
@Ein-Tim Yes, I think, it would require "a mayor" effort to implement this feature this for Android devices. Is there a related wishlist item already?

**Comment by Ein-Tim** [comment]
@dsarkar 

Ah, okay. AFAIK there is no wishlist item regarding this yet. I will first transfer the answer to the user on Twitter & then, depending on the feedback, open an issue.

Thank you for answering & enjoy the evening!

**Comment by dsarkar** [comment]
@Ein-Tim Thanks also to you, for relaying info between twitter and GH forth and back! ;-)
