### ISSUE TITLE
[UX] Increase touch target for switches

### ISSUE THREAD

**Issue by IndianaDschones** [corona-warn-app/cwa-app-android#455]
![switches (3)](https://user-images.githubusercontent.com/6652142/84580153-a4561b80-add4-11ea-9809-48d58a3314f5.png)

## Current Implementation

Currently if the user wants to change a setting that includes a `switch` he has to click **on the switch** (see red rectangel in the picture)

## Suggested Enhancement

From a usability/user experience point of view it would be better to "just tap somewhere where the text is" (green rectangle). This behaviour can be seen in the android settings or the Google Play Stores _Notifications_ settings. So the user knows (and maybe also expects) this behaviour

## Expected Benefits

Easier and more convenient way of "switching" some settings.

**Comment by tomjschwanke** [comment]
I have fixed this in #466, it just needs to be reviewed and merged
