### ISSUE TITLE
Add quick ref to certificates for pixel feature "quick tab"

### ISSUE THREAD

**Issue by nilsdohms** [corona-warn-app/cwa-app-android#4551]
## Avoid duplicates
* [x] This enhancement request has not already been raised before
* [x] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation
At the moment the only possibilitys for quick tab & quick acces via click and hold the app icon are
* Open the app
* Add entry to your contact diary

## Suggested Enhancement
I would propose that most users use the app to show their covid certificate so a qucik access would be really nice and save time especially when traveling, going in tio shops, you name it...

## Expected Benefits
Benefits:
* Save time
* Relatively easy to add (Copy and paste from "add entry")
* Makes life easier

**Comment by Ein-Tim** [comment]
Hi @nilsdohms 👋

Thanks to you for proposing this, however, we already have a quite similar request in our central wishlist repo: https://github.com/corona-warn-app/cwa-wishlist/issues/504

Please check whether this separate issue is really necessary or if it can be closed in favour of https://github.com/corona-warn-app/cwa-wishlist/issues/504.
