### ISSUE TITLE
Some Luca QR codes show "undefined" as location name after being scanned

### ISSUE THREAD

**Issue by smares** [corona-warn-app/cwa-app-android#4552]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Google Pixel 6 Pro
- Android version: 12
- App version: 2.14.1

## Describe the bug

Some QR codes for the Luca app when scanned with CWA display "undefined" as location. The same code scanned with the Luca app displays the correct location name. I cannot test if this is specific to the Android version or if it affects iOS too. I will post a QR code later today if it's needed.

**Comment by MikeMcC399** [comment]
@smares 
There are some other postings relating to this issue.

- https://github.com/corona-warn-app/cwa-documentation/issues/741
- https://github.com/corona-warn-app/cwa-wishlist/issues/679

**Comment by smares** [comment]
Sorry, you're right. Closing then.
