### ISSUE TITLE
Wrong link to "4 Exposure Notification Google API" inside wiki and README.md

### ISSUE THREAD

**Issue by derhelge** [corona-warn-app/cwa-app-android#457]
## Where to find the issue & description of the issue
Within the table of contents on the [wiki page](https://github.com/corona-warn-app/cwa-app-android/wiki) and inside README.md the link to "4 Exposure Notification Google API" is wrong.

## Suggested change
Both links should be set to:
`https://github.com/corona-warn-app/cwa-app-android/wiki/4-Google-Exposure-Notifications-API`
and not
`https://github.com/corona-warn-app/cwa-app-android/wiki/4-Exposure-Notification-Google-API`

**Comment by SebastianWolf-SAP** [comment]
[Wiki ToC](https://github.com/corona-warn-app/cwa-app-android/wiki) is fixed.

**Comment by mynchau** [comment]
Closing this issue as fixed. Thanks for the hint, @derhelge ! 
MC
Your Corona Warn-App Open Source Team
