### ISSUE TITLE
Exposure Notifications - matches removed between checks

### ISSUE THREAD

**Issue by ruimbribeiro** [corona-warn-app/cwa-app-android#4576]
## Tech Details
Device: OnePlus 5t, Android 10
CWA Version: 2.14.1
ENF Version: 18214516000

## Question

Recently I have been checking the exposure checks and I noticed that for the last 14 days the following happened:
- At a certain check on a specific day I can have a matchcount of 1
- At the same day at another check this value goes to zero
- In the 3rd check, same day or after the matchesCount goes again to 1

You can easly see this in the json for today (16th December).

At the same time the app always reported only 1 encounter, on 10th December (check screenshot below).

Is this an expected behaviour? 
- Are the number of matches removed/reduced other than by the 14 day timeframe rule?
- Does CWA remove a match if it is considered too short (in time) or too far away (in distance)?
- Are these different encounters? If so shouldnt the log have at least 1 encounter constantly (at least until 14 days after 10th December)?

## Exposure json

Please find the exposures json in the [following GIST](https://gist.github.com/ruimbribeiro/7ed20cf67a38008541b426e59fb4f12f)

## CWA App Screenshot
![Screenshot_20211216-162237](https://user-images.githubusercontent.com/6974807/146401583-841e5055-cd5a-4adf-97ac-82832377a3a2.jpg)

---
Internal Tracking ID: [EXPOSUREAPP-11075](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11075)

**Comment by dsarkar** [comment]
@ruimbribeiro Thanks for reporting. We will have a look at it.


Internal Tracking ID: [EXPOSUREAPP-11075](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11075)

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Hi @ruimbribeiro,

I got feedback from the dev team:
Does CWA remove a match if it is considered too short (in time)? -> yes

Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by alexsr** [comment]
I also experienced this behaviour, but with a high risk encounter instead. Could you maybe specify when matches are removed?

**Comment by MikeMcC399** [comment]
@alexsr 

> Could you maybe specify when matches are removed?

A match is removed when it has occurred more than 14 days ago. See for instance https://www.coronawarn.app/en/faq/#encounter_deletion which describes a low risk encounter. The same applies though to high risk encounters as well.

On Android you can check also in 
Settings > Google > COVID-19 Exposure Notifications
Three-dot symbol > Exposure checks

Each individual log entry has a field "Number of matches" so you can step back in time to see how the matches changed. You can also export the log as a json file.

**Comment by alexsr** [comment]
Sorry, I should have been more specific. These incidents I am referring to happened less than 14 days ago.

[strange-all-exposure-checks.txt](https://github.com/corona-warn-app/cwa-app-android/files/7873649/strange-all-exposure-checks.txt)

As you can see from the logs, it is switching from 1 to 0 to 2, back to 0 and so on.
Now @dsarkar specified that these matches might be removed in case the match is low risk. However, in my case, the app shows that there was a high risk encounter on the 9th of January. I just find the way matches behave very confusing. It also does not match the descriptions I have read in other issues so far.

**Comment by svengabr** [comment]
I have just checked the linked Jira issue.

Jira Ticket is flagged as:
Resolution: `Wont Fix`
Status: `Obsolete`

Developer comment:
> Setting to obsolete as the original question should be answered. If not: plz re-open.
