### ISSUE TITLE
Unclear risk report tile

### ISSUE THREAD

**Issue by deesnook** [corona-warn-app/cwa-app-android#4586]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: OnePlus 8T
- Android version: 11 (Lineage OS 18.1-20211205-microG-kebab)
- App version: 2.14.1

## Describe the bug
A red risk warning should disappear 14 days after exposure. However, in the current version the risk tile remains red and still shows the date of exposure on day 15 after exposure. The number count of risky exposures disappears though. On day 16 after exposure the tile goes back to green (if there haven't been any other exposures). 

Example screenshot: Exposure Dec 4th 2021. Time of screenshot: Dec 19th 2021. On Dec 18th, the first line in the risk tile still showed "1 exposure with high risk". Since Dec 19th, the first line is empty: 

![Screenshot_20211219-095615_Corona-Warn](https://user-images.githubusercontent.com/17967431/146678545-abd93895-eccd-4838-a6df-eedd405db945.png)

## Steps to reproduce the issue
Have a red risk warning and wait until day 15 after exposure.

## Expected behaviour
The risk tile either turns green on day 15 or remains red and keeps the number of risky exposures. The current behavior is confusing for users since you don't know for sure whether there still is a risk or not. The color suggests there is, but the text suggests there isn't. This should be unequivocal

## Possible Fix
No idea :)

**Comment by Ein-Tim** [comment]
Hi @deesnook 👋

This seems to be a duplicate of #4407, or? 

Please check and close this issue if you also think it's a duplicate (-:

Thank you & have a nice Sunday!

**Comment by deesnook** [comment]
You're absolutely right, it is a duplicate. I somehow overlooked the other issue. Sorry!
