### ISSUE TITLE
Is this a bug? Exposure warning coming 6 days too late

### ISSUE THREAD

**Issue by Matthirocks** [corona-warn-app/cwa-app-android#4587]
My understanding of the corona-warn-app is that it will try to warn contacts AS EARLY AS POSSIBLE.
So is this a bug?  The following has happened:

On December 12th a group of six people met indoor in a room for more than one hour.
One of them had a covid-19 infection only 2 weeks ago, his positive test had been registered in his cwa app on November 29th. So on December 12th he was already out of quarantine, but in the warn app he was still "red".

All other members of the group got no warning on December 12th, 13th, 14th, 15th, 16 th, 17th. But on December 18th and 19th ALL members of the group got a warning of a high risk contact for December 12th. 

Why would the app "wait for 6-7 days" before it warns other people. This seems to be a bug. Or is it a feature? Am I missing out something?

Was the cwa warning service ever "interrupted" due to LOG4J issues ?

**Comment by thomasaugsten** [comment]
The app was not waiting it will publish keys after 2h waiting period. Sometimes it took some until the infectious person recognize the symptoms, take a PCR test and share the keys with other CWA user.

After submitting the keys then also other person 6 days in the past get warned, depending on the onset of symptoms.

**Comment by Ein-Tim** [comment]
There seems to be a basic misunderstanding on how the app works here.

If a user enters their positive test in the app, the app warns all contacts who were met in the last 14 days. But the app does not warn the contacts which were met after the positiv test was entered into the app.

Thus, the increased risk warning you received wasn't from the person who registered their infection in the CWA on 29.11.21.

**Comment by Ein-Tim** [comment]
Can this issue be closed?

**Comment by Matthirocks** [comment]
Yes it can be closed. Thanks to everyone.
