### ISSUE TITLE
I have 3 vaccinations but only 2 show

### ISSUE THREAD

**Issue by botoxparty** [corona-warn-app/cwa-app-android#4588]
I have scanned in 3 vaccination certificates but 2 appear. Not my most recent one.

**Comment by Ein-Tim** [comment]
What happens if you try to scan the most recent one again?

**Comment by botoxparty** [comment]
It says it has already been scanned into the App

**Comment by Ein-Tim** [comment]
@botoxparty 

And you searched all of the certificates tab (scroll down, etc.)?

**Comment by botoxparty** [comment]
Of course

**Comment by Ein-Tim** [comment]
@botoxparty 

Okay that's really strange. As I'm mainly an iOS user, I can't really help you any further here. I'm sure somebody from the dev team will come back to you soon.

**Comment by botoxparty** [comment]
@Ein-Tim can you assign the ticket to an Android dev?

**Comment by Ein-Tim** [comment]
@botoxparty I'm only a community member (not from the dev team), so I can't do this, sorry.

**Comment by thomasaugsten** [comment]
@botoxparty  Can you please retest this with the CWA v2.15 if this available for you in the next days

**Comment by dsarkar** [comment]
Hi @botoxparty, thanks for the report. 

For the moment I would suspect that your third certificate was issued with a slightly different name.
1. Can you confirm that your name on all your printed certificates are written exactly the same way?
2. Also, is the date of birth on all certificates the same?
3. Would you mind to send screenshots from the certificate tab? If you do so, make sure that your private data (name, , qr code etc) is unreadable

**Comment by botoxparty** [comment]
@thomasaugsten 1 person is registered (myself)

@dsarkar 
1. Ahhh i see, they have mixed my first name and last name!
2. DOB is the same

I'll get the certificate re-issued with the correct name and report back

**Comment by dsarkar** [comment]
@botoxparty Thanks for the feedback. So I assume you can't see therefore all three certificates in de "detail screen", see here for example: https://www.coronawarn.app/en/faq/#vac_booster_basics

Can you confirm that on the certificate tab, there is only one person, **one card**? Scroll down... see screenshots 3 and 4  https://www.coronawarn.app/en/screenshots/#ios_certificates


Thanks for the feedback.

**Comment by botoxparty** [comment]
There is 2, but one is my name backwards.

**Comment by dsarkar** [comment]
@botoxparty ok, so all together there are all of your certificates, i.e. 3 of them. But they are not grouped together, i.e. the app cannot recognize them belonging to the same person due to the issue with the spelling. So, I am afraid that the issuer will have to re-issue your certificate. Let us know if then your problem is solved.

**Comment by botoxparty** [comment]
Had it reissued and it solved the problem. Thanks!

**Comment by dsarkar** [comment]
@botoxparty Thanks for your feedback, and happy to hear that your issue has been resolved I suggest you close this issue now. Anytime, should you experience another issue, or you have a suggestion, etc, open a new issue here. 

Best wishes, stay safe, and a happy new year! DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
Can this issue be closed?
