### ISSUE TITLE
Open device settings fails on pre-Oreo devices

### ISSUE THREAD

**Issue by friedger** [corona-warn-app/cwa-app-android#461]
## Describe the bug
Clicking on "Open device settings" button in settings on pre-Oreo device shows a message that this action can't be performed
![Screenshot from 2020-06-15 00-10-40](https://user-images.githubusercontent.com/1449049/84605384-0f6b2500-ae9d-11ea-8cfc-fc08d1556aa6.png)
![Screenshot from 2020-06-15 00-10-54](https://user-images.githubusercontent.com/1449049/84605383-0e39f800-ae9d-11ea-8144-3bed71736b53.png)

## Expected behaviour

Clicking on the button should open the app settings

## Steps to reproduce the issue
1. enable tracking
2. click Settings -> Notifications
3. click on Open device settings

## Technical details

pre-Oreo Android device

## Possible Fix

set correct intent action

**Comment by PhilippNowak96** [comment]
I would like to fix this and will provide a PR soon.

**Comment by marcmuschko** [comment]
Closing the issue as the corresponding PR was merged.
