### ISSUE TITLE
Test reservation series ignores all but one test

### ISSUE THREAD

**Issue by openmindculture** [corona-warn-app/cwa-app-android#4626]
After booking a test appointment, e.g. using no-q.info, users are offered to register the test in the Corona Warn App.

This works for me when registering only one appointment. However, when I register a series of upcoming tests, by repeating the same procedure after each new appointment, only the first registration shows in CWA.

After deleting this test in CWA, no other upcoming tests are displayed.

Software version:
cwa-android 2.15.1

Google Exposure Notification:
182114516000

Android 12
Security patch 5 December 
Kernel 4.14.243

ENF version

**Comment by dsarkar** [comment]
Hi @openmindculture 

Thanks for your comment. Please see the FAQ article:
- EN https://www.coronawarn.app/en/faq/#rat_multiple_rat
- DE https://www.coronawarn.app/de/faq/#rat_multiple_rat

---
Corona-Warn-App Open Source Team

**Comment by openmindculture** [comment]
Thanks for the links! I was not even sure if I should label it as a bug.
It might be helpful to warn the users when trying to add a second test in a row.
But then again, maybe I'm an edge case as a curious developer.

**Comment by Ein-Tim** [comment]
@openmindculture There is a warning when adding a new test if another test is already registered.

**Comment by openmindculture** [comment]
> @openmindculture There is a warning when adding a new test if another test is already registered.

I was not consciously aware of the warning, but as I suspected the actual behavior, I probably skimmed and understood nevertheless.

**Comment by dsarkar** [comment]
@openmindculture Anyway thanks for your question. Next time you try to register a second test, check if get a notification before adding the second test. Is should say that the other register test will be deleted. If you don't see such a notification, please report back here.


Also, did you check the recycle bin? Are the test in the recycle bin?

**Comment by openmindculture** [comment]
P.S. I tried to check again, but ran into another problem (QR code seemingly invalid, which always happens with results from that specific pharmacy. I will try to follow-up with another issue after taking another test there).
