### ISSUE TITLE
Error at offline-usage with registered test

### ISSUE THREAD

**Issue by marty2022** [corona-warn-app/cwa-app-android#4628]
## Describe the bug

When a test is registered and the app is started while beeing offline a big error-message
is shown over the complete screen that the test result can not be downloaded.

## Steps to reproduce the issue

1. start app
2. register test
3. quit app
4. go offline
5. start app
6. see error-message

## Expected behaviour

Download of test result should be deferred.

## Possible Fix

Delete the test.

---
Internal Tracking ID: [EXPOSUREAPP-10746](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10746)

**Comment by dsarkar** [comment]
@marty2022 Thanks for the report. 

1. Could you provide a screenshot of the error notification
2. Caution: Please, do not delete the test. It can only be scanned once!

**Comment by Ein-Tim** [comment]
This looks like a duplicate of #4338 to me, or am I mistaken?

**Comment by dsarkar** [comment]
@Ein-Tim Yes, looks like it, thanks for pointing out.
@marty2022 see comment above, and please,  confirm if issue #4338 describes your problem.

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-10746](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10746)

**Comment by dsarkar** [comment]
@Ein-Tim Do you know if with iOS the behaviour is different?

**Comment by Ein-Tim** [comment]
@dsarkar

I have a PCR registered in my app and I don't have any problems viewing the test result when offline.

**Comment by dsarkar** [comment]
@Ein-Tim Ok, that seems much more convenient, and does not cause the confusion as for Android user.

**Comment by marty2022** [comment]
@dsarkar I can not provide a screenshot as I deleted the test, but I can confirm that it is the same problem as #4338.
Haven't found that issue before, so I'm closing this one.

**Comment by dsarkar** [comment]
@marty2022 ok, thanks again for the report and feedback.

**Comment by dsarkar** [comment]
PR https://github.com/corona-warn-app/cwa-app-android/pull/5223
