### ISSUE TITLE
Change capitalization of "<Name>, Geboren <DoB>" to "<Name>, geboren <DoB>" in the RAT result test screen

### ISSUE THREAD

**Issue by jkrwdf** [corona-warn-app/cwa-app-android#4630]
## Avoid duplicates
* [X] This enhancement request has not already been raised before
* [?] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [X] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation
In the CWA there are two locations where the word "Geboren" is used. 

One is in the display of certificates, and one is in the display of a RAT test. 
Both seem to share the same text element in the software. 

With issue https://github.com/corona-warn-app/cwa-documentation/issues/715 I annotated that the usage of lower-case "geboren" in the certificate section is not good, and it was changed to upper case (green cirle):

![image](https://user-images.githubusercontent.com/5329491/147732948-df3084cf-60f6-41fd-acd6-71707ccd9447.png)

Unfortunately, this change caused a collateral damage in the RAT test screen, where it now also went upper-case (red circle)

![image](https://user-images.githubusercontent.com/5329491/147732997-7d556f75-c602-4509-b70c-f0b3c7ba7dac.png)

At THIS location, lower-case it better because it is an inline sentence with preceding comma.

## Suggested Enhancement
Change to lower-case "geboren" in the RAT result screen. 

To avoid a Stehaufmännchen in the "Certificates" section, a second text element must be created for this.

## Expected Benefits
Better visual appearance.

---
Internal Tracking ID: [EXPOSUREAPP-11159](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11159)

**Comment by dsarkar** [comment]
Alternative suggestion: In RAT screen: First line name, second line DoB, keeping upper-case.

**Comment by jkrwdf** [comment]
This is an elegant and consistent proposal.

**Comment by larswmh** [comment]
Hi @jkrwdf, thanks for your report. We have created an internal ticket and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-11159](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11159)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
PR: https://github.com/corona-warn-app/cwa-app-android/pull/4645

**Comment by jkrwdf** [comment]
CWA 2.16.2

![image](https://user-images.githubusercontent.com/5329491/150149263-062997b1-b932-4cb4-9485-9fefc1d1639c.png)

Thank you. 

And bonus: The "Geboren" in the display of a certificate is still upper case! Yessssssss!

Closing.
