### ISSUE TITLE
Invalid QR Code of registered test from No-Q Link

### ISSUE THREAD

**Issue by openmindculture** [corona-warn-app/cwa-app-android#4632]
As an end-user, I have registered an upcoming test, booked via No-Q/testbuchen.de, in the Corona Warn App on my Android smartphone. After having received the test result, the no-q web app offers a "Corona Warn-App Test Registration" with a scannable QR code and an alternative link to tap if CWA is installed on the same device.

Such a link looks as follows: 

https://s.coronawarn.app/?v=1#eyJ...[TOKEN]...==

I can share the full link, or the actual QR code, or I can take further action to evaluate if the token is invalid or not.
Please tell me how to provide more information, if required.
I also have access to my phone's logs via ADB.

Tapping the link opens CWA which requests confirmation to request the test result ("Testergebnis abrufen" ... "Jeder Test kann nur einmal gescannt werden. Die App kann maximal einen Schnelltest und einen PCR-Test gleichzeitig verwalten."). After confirmation, the next step in CWA has a button to request a certificate ("Testzertifikat anfordern").

At this moment, the current test may or may not be registered in CWA, as I had tried to register a series of upcoming tests prior to taking them, as discussed in [#4626](https://github.com/corona-warn-app/cwa-app-android/issues/4626). But I don't think the issue is related to the series, as I have seen the exact same messages and warnings before when I had only one test on one day.

After tapping the request certificate button, CWA informs me that the QR code is invalid. ("Der QR-Code ist ungültig oder wurde bereits auf Ihrem Smartphone registriert.") The wording is confusing, as I did not scan a QR code, but instead followed a link, and there are two possible reasons in one sentence, and no helpful call-to-action what the user should do at that point.

When I repeat the procedure but instead of following the link, this time scanning the QR-Code (displayed on another device), the dialogs and error messages are exactly the same.

This has happened many times before, always when using No-Q, and mostly (maybe all of the time, but I am not sure) at the same testing lab at a local pharmacy.

When I open the test result as a PDF document, everything looks legit, and those test certificates have been accepted by humans looking at them.

CWA Version 2.15.1
Android 12 on Google Pixel 4a

Screenshots attached
![No-Q Screenshot](https://user-images.githubusercontent.com/6377941/147814869-748dc0cf-9d8b-4948-82ae-913adfd93e66.png)

![CWA Screenshot_20211231-095713](https://user-images.githubusercontent.com/6377941/147814949-fbc449ea-ca34-4735-9c4c-cd2f795fda59.jpg)

![CWA Screenshot_20211231-095729](https://user-images.githubusercontent.com/6377941/147814955-c4106e1f-46b0-4a98-967b-3a7778f0f148.jpg)

![CWA Screenshot: invalid message](https://user-images.githubusercontent.com/6377941/147814971-7623f335-fc96-42a7-8599-d681d94ba162.jpg)

**Comment by Ein-Tim** [comment]
@openmindculture 

This sounds like an implementation error by the testing site. 

Could you share some information where you got tested. 

> The wording is confusing, as I did not scan a QR code, but instead followed a link, and there are two possible reasons in one sentence, and no helpful call-to-action what the user should do at that point.

Could you open a separate enhancement request for this? These are very valid points and should be discussed.

**Comment by openmindculture** [comment]
> @openmindculture
> 
> You say you have already registered the test in the app before the link was send to you via Mail. Then it makes sense that you can't register the test again, as it is already in your app.

But when it's already in the app, it should display there automatically?

Anyway, for tracing potential implementation errors at third parties:
all aforementioned tests have been registered and processed by No-Q.
Recent testing station was mentioned as notification sender as "Rats-Apotheke via NO-Q Digital Customer Queueing".

> > The wording is confusing, as I did not scan a QR code, but instead followed a link, and there are two possible reasons in one sentence, and no helpful call-to-action what the user should do at that point.
> 
> Could you open a separate enhancement request for this? These are very valid points and should be discussed.

Done: [Missing / confusing call-to-action when warning about invalid QR Code or test already registered #4633](https://github.com/corona-warn-app/cwa-app-android/issues/4633)

**Comment by Ein-Tim** [comment]
> But when it's already in the app, it should display there automatically?


Yes exactly, the test result should be displayed in the app without any further action, if you have already registered it before the test was carried out.

**Comment by openmindculture** [comment]
I will continue my test in January.
Thanks for your help and have a happy new year!

**Comment by openmindculture** [comment]
Happened again. "No Suitable QR Code" / "Thew QR code is not supported by the Corona-Warn-App. Please select a suitable QR code." when trying to scan a code issued by [nohttps://github.com/corona-warn-app/cwa-app-android/issues/4632](https://github.com/corona-warn-app/cwa-app-android/issues/4632) and no link to register the test result in the app.

![image](https://user-images.githubusercontent.com/6377941/166196388-293ea1c1-5573-4e16-bab8-bf7ae88e9bee.png)

**Comment by dsarkar** [comment]
@openmindculture Thanks for reporting this issue, will forward it.

**Comment by MikeMcC399** [comment]
@openmindculture 

I don't understand about your https://github.com/corona-warn-app/cwa-app-android/issues/4632#issuecomment-1114553613. The graphic you posted shows a QR code starting with `https://verify.no-q.info/result/eyJ....`. The Corona-Warn-App is not able to handle this QR code, so the error message "No Suitable QR Code" is expected if you try to scan this code with CWA.

What was your expectation? Did I misunderstand something?

**Comment by dsarkar** [comment]
@openmindculture yes, actually I have some for questions for you:
- You did the rapid test in the pharmacy shown in the screenshot?
- Did you book the test online and was there an option to choose to obtain the result via the Corona-Warn-App?
- If there was no online booking of the test, at the test site have you been ask if you want to obtain the result also via the  Corona-Warn-App?

Thanks for the feedback! Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@openmindculture 

Did you clarify with the pharmacy if they still support transmission of test results to CWA?

**Comment by MikeMcC399** [comment]
@openmindculture 

Following on from @Ein-Tim's question
> Did you clarify with the pharmacy if they still support transmission of test results to CWA?

https://www.rats-apotheke-duesseldorf.de/ shows

![image](https://user-images.githubusercontent.com/66998419/166236291-ac4bf77c-5483-4929-86fe-787402ae872e.png)

so the first place to check about the current process would be the pharmacy, followed by https://app.no-q.info/rats-apotheke-duesseldorf-gerresheim/checkins/#/service/antigen which shows

![image](https://user-images.githubusercontent.com/66998419/166236478-a424008c-eed3-4004-8899-4e0e799f2c3c.png)

at the bottom, which links indirectly to an FAQ document https://www.no-q.info/wp-content/uploads/2021/07/No-Q_FAQs_TestV_CWA_EU-DCC.pdf. I cannot say how up-to-date this document is.

The question about the process needs to go to the Apotheke in any case in the first step.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for investigating.
@openmindculture It seems it is possible to book test and receive the results via the app. Maybe you missed that step accidentally? 
<img width="785" alt="image" src="https://user-images.githubusercontent.com/1409741/166240362-533494b8-6ec9-40cf-93bb-551c8d001bb3.png">

**Comment by openmindculture** [comment]
> @MikeMcC399 Thanks for investigating. @openmindculture It seems it is possible to book test and receive the results via the app. Maybe you missed that step accidentally? <img alt="image" width="785" src="https://user-images.githubusercontent.com/1409741/166240362-533494b8-6ec9-40cf-93bb-551c8d001bb3.png">

yes, I did not see that step during regiatration, but maybe I overlooked and it waa no technical defect. Still, why wouldn't I be able to scan it afterwards anyway?

**Comment by MikeMcC399** [comment]
@openmindculture 

> Still, why wouldn't I be able to scan it afterwards anyway?

It seems that the process is not designed for you to be able to change your mind after you have booked a test.

**Comment by MikeMcC399** [comment]
@openmindculture 

I don't think that there is anything that the app could do differently in this situation. If you want to follow up about the ability to get a test result and / or a certificate through CWA after you (apparently) declined it, you would need to get in contact with your pharmacy or perhaps the IT provider https://www.no-q.info/kontakt/. Since the [result of a negative RAT test is generally valid for only 24-48 hours](https://www.zusammengegencorona.de/faqs/testen/schnelltest/#id-623d2122-6a1d-5d39-bd11-d89b03b7519b), the issue resolves itself relatively quickly.

**Comment by openmindculture** [comment]
Okay, so it works as designed, and it's designed to be as German as can be. Nevermind.

**Comment by dsarkar** [comment]
@openmindculture Thanks for participating here. Just for clarification: It is up to the test center to provide you with a link or QR code, that is compatible to the Corona-Warn-App (CWA). If the test center is willing to provide you retroactively with a QR code or URL, the CWA will able to register your test. Best wishes, DS

---
Corona-Warn-App Open Source Team
