### ISSUE TITLE
Scan malfunction

### ISSUE THREAD

**Issue by Lacquerdream** [corona-warn-app/cwa-app-android#4634]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name:
- Android version:
- App version:

**Comment by dsarkar** [comment]
@Lacquerdream See

DE https://www.coronawarn.app/de/faq/#scan_tips
EN https://www.coronawarn.app/en/faq/#scan_tips

and discussion in issue https://github.com/corona-warn-app/cwa-app-android/issues/3514


Thanks, DS

---
Corona-Warn-App Open Source Team

**Comment by Lacquerdream** [comment]
Hi, I tried all these things and still not working. I also read the threat sent but I can't find a solution. I have an android and the I tried to scan from another screen, from paper, uploading a photo, rotating, regulating contrast etc

**Comment by Ein-Tim** [comment]
@Lacquerdream 

Good News: Version 2.16 will improve the QR-Code scanner. Which QR-Code are you trying to scan?

**Comment by Lacquerdream** [comment]
a test

**Comment by Ein-Tim** [comment]
PCR oder Rapid Antigen Test?

**Comment by Lacquerdream** [comment]
PCR

**Comment by Lacquerdream** [comment]
I had a positive PCR a while ago and I am trying to scan it so I can get the certificate

**Comment by dsarkar** [comment]
@Lacquerdream for positive test no EU digital COVID certificate is issue.

**Comment by dsarkar** [comment]
@Lacquerdream If you received your result via different means, i.e. not vie the Corona-Warn-App, but still want to share the positive result via the app, see https://www.coronawarn.app/de/faq/#qr_test

**Comment by Lacquerdream** [comment]
ok, how/where can I get the certificate then?

**Comment by Ein-Tim** [comment]
If you want to get a certificate of recovery, you have to go to a pharmacy with an ID document and the documentation of the last positive test. 

Your certificate of recovery will be valid 28 days after the last positive PCR test.

**Comment by Lacquerdream** [comment]
Thank you so much for the information. Have a nice day :)

**Comment by dsarkar** [comment]
@Ein-Tim Actually good point! One cannot get a test certificate but probably a recovery certificate!

@Lacquerdream Same to you, enjoy the day and a happy 2022!

**Comment by MikeMcC399** [comment]
@Lacquerdream 

There is some more detailed information in https://digitaler-impfnachweis-app.de/en/faq/#current-most-frequently-asked-questions 
- Current most frequently asked questions 
    - I have had COVID-19 and have recovered. How can I prove that I have full immunity?

or in German https://digitaler-impfnachweis-app.de/faq#current-most-frequently-asked-questions 
- Die aktuell häufigsten Fragen 
    - Ich war an COVID-19 erkrankt und bin genesen. Wie kann ich einen vollständigen Immunschutz nachweisen?

This is not covered in the CWA FAQs.
