### ISSUE TITLE
Version 1.0.1. Kommunikations Problem

### ISSUE THREAD

**Issue by ClemenzM** [corona-warn-app/cwa-app-android#464]
API ist auf dem Honor 6x vorhanden

Corona Warn App Version 1.0.1
Android Version: 7.0

Habe die Apk installiert, bekomme aber folgende Fehlermeldung.

URSACHE: 3 Etwas ist schief gelaufen.
Fehler bei der Kummunikation mit Google API (17)

Nearby. EXPOSURE NOTIFICATION API

is not available on this device.

Connection failed with:

ConnectionResult{statusCode=UNKNOW N_ERROR_CODE(39507), resolution=null, message=null}

**Comment by SebastianWolf-SAP** [comment]
Bitte warten Sie auf die offizielle Version. Selbst kompilierte Builds oder APKs aus inoffiziellen Quellen beinhalten nicht das Entitlement von Google, um auf die Exposure Notification API zugreifen zu können.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by ClemenzM** [comment]
ok, verstanden, danke dann abwarten ;-)
