### ISSUE TITLE
HC_CBOR_DECODONG_FAILED

### ISSUE THREAD

**Issue by Identitaet** [corona-warn-app/cwa-app-android#4641]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/) Yup
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation) On my dads android it also won't work on my mums iPhone it's working
* [ ] Bug is not already reported in another issue
Looks similar to #3417 but that one's solved and the issue is not identical
## Technical details

- Device name:Xaiomi Note 9S
- Android version:MiUi Global 12.5.2
- App version:2.15.1

## Describe the bug

I try to get my EU certificate but instead I get:
![IMG_20220103_183318](https://user-images.githubusercontent.com/58372210/147961835-f40abf44-b3f1-451d-ab81-6b9294ee23d3.jpg)

## Steps to reproduce the issue

Have a certificate which magically has the problem (I don't know what it is) (previous certificates worked)(also doesn't work on my dads device)

## Expected behaviour
I get my Eu certificate

## Possible Fix

🤷
## Additional context
Test was made with CovStopp and DreHo GmbH

Jira
https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11148

**Comment by Ein-Tim** [comment]
So just for the record, you getting this as an error for the request of a test certificate?

**Comment by Identitaet** [comment]
Yes exactly

The little green thing which says you've gotten a test works fine

**Comment by Ein-Tim** [comment]
This is strange, sounds like the certificate was issued wrong. 

@thomasaugsten Could you take a look at this?

**Comment by thomasaugsten** [comment]
This is not a valid EU certificates. It is more likely a Test QR-Code at the moment you receive an EU certificate when you request this via CWA.

**Comment by Identitaet** [comment]
> This is not a valid EU certificates. It is more likely a Test QR-Code at the moment you receive an EU certificate when you request this via CWA.

I haven't scanned anything directly for this, and I'm pressing the requested certificate button and for my mum (iOS) it's working and she's got the EU certificate

**Comment by thomasaugsten** [comment]
Can you please give details about your request flow.
Where exactly make you the RAT or PCR test.
Did you request a eu certificate while scanning the test qr code?
Is the test negative?
Where exactly you receive this error on which screen do you see any qr code?

**Comment by Identitaet** [comment]
Yes it was a rapid test
I did request a certificate when scanning the code

https://youtu.be/GM-cOkfLFjs

**Comment by thomasaugsten** [comment]
Ok we need details about the rapid test provider. We will inform him about the miss-formed eu certificate

**Comment by Identitaet** [comment]
KiComed Testcenter West

Am Konzertgarten West
Strandpromenade 19

Kostenloser Bürgertest.

Ohne Termin, nur einmalige Registrierung unter 
www.mv-schnelltest.de.

Oh yeah it says certificate not valid

**Comment by thomasaugsten** [comment]
Please provide me this certificate via mail
thomas.augsten@sap.com

**Comment by thomasaugsten** [comment]
The provider fixed this issue you can retest this if you need a new rapid test at this location.

**Comment by dsarkar** [comment]
@Identitaet see comment above. Thanks.

**Comment by Ein-Tim** [comment]
@thomasaugsten 

I have a user on Twitter reporting the same issue for the test station https://www.teststation-mahlsdorf.de.

He shared a screenshot with me: 

<img src="https://user-images.githubusercontent.com/67682506/151677912-fa96371e-b002-43dd-86c3-4ab752b50c5f.jpeg" width="300">

Can you contact the test station and let them know about this issue?

**Comment by thomasaugsten** [comment]
I will forward this

**Comment by Ein-Tim** [comment]
Thank you so much & enjoy the weekend!

**Comment by thomasaugsten** [comment]
It would be helpful to have the test certificate to guide the test provider directly to the problem

**Comment by Ein-Tim** [comment]
@thomasaugsten You mean the QR code to the test? Because the user can't get the test certificate because of the issue.

**Comment by thomasaugsten** [comment]
Sorry my mistake

**Comment by Ein-Tim** [comment]
@thomasaugsten Okay let me know what you need, I'll forward it.
