### ISSUE TITLE
Switching date break exposure check

### ISSUE THREAD

**Issue by tueksta** [corona-warn-app/cwa-app-android#4660]
For testing reasons I had to set my date one month to the future. After setting it back, I can't check exposure anymore, all I get is "Exposure check failed". Samsung Galaxy S10 with Android 11

**Comment by Ein-Tim** [comment]
Hi @tueksta 👋

Please take a look at #4303. 

Thanks.

**Comment by tueksta** [comment]
Ah thanks. I searched for it but couldn't find it.
