### ISSUE TITLE
CWA does not recognize QR-Code of booster (i.e. 3rd) certificate, but the CovPass app does

### ISSUE THREAD

**Issue by 6riah** [corona-warn-app/cwa-app-android#4668]
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Don't know whether Bug is specific for Android only
* [ ] Bug is not already reported in another issue, I checked

## Technical details

- Samsung Tab A
- Android version: 8.1.0
- App version: 2.15.1

## The bug

The CWA does not recognize the QR-Code on my last (3rd) COVID certificate, but the CovPass app does.

The CWA did not read the QR-codes on the 1st two certificates either but I was able to create files using a separate reader and then read those into the CWA. The same workaround was not successful with the 3rd COVID certificate as all readers I tried could not read that QR-code either, or rather, recognized only text

---
Internal Tracking ID: [EXPOSUREAPP-8028](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8028)
Internal Tracking ID: [EXPOSUREAPP-10502](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10502)

**Comment by MikeMcC399** [comment]
@6riah 
Are you asking for help or did you just want to report a bug?

The next version of the Android app 2.16. is planned to use different scanning software. See https://github.com/corona-warn-app/cwa-app-android/pull/4590. That may help you when it is released.

Officially tablets are not supported by CWA (see https://www.coronawarn.app/en/faq/#smartwatch), however I checked on my own Samsung Galaxy Tab A (SM-T510) running Android 11 and CWA Android 2.15.1 and I was able to successfully scan a booster certificate.

Just for reference the scan FAQ is https://www.coronawarn.app/en/faq/#scan_tips.

**Comment by thomasaugsten** [comment]
This is correct, the scanning on Android will be significant improved with 2.16, the release is planned in ~10days

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-8028](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8028)
Internal Tracking ID: [EXPOSUREAPP-10502](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10502)

**Comment by 6riah** [comment]
Can confirm that with Rev 2.16 I was able to scan the booster QR-Code no problem

**Comment by dsarkar** [comment]
@6riah Thanks for your feedback! 

Best wishes, DS

---
Corona-Warn-App Open Source Team
