### ISSUE TITLE
possibility to instant get update from server

### ISSUE THREAD

**Issue by viisauksena** [corona-warn-app/cwa-app-android#4669]
make it possible to instantly trigger reload warnings (red warning) from server, 
for example by clicking on the green warning.
many people wonder why their mates get early warnings and they get them only half a day later.

it would be great if these people could retrigger an early download (instead of the enforced 4h after last update - only if you use wifi, 24h if you use mobile data)
worst case would be: these people wait for pcr test appointments (they have to somehow wait for red warnings in germany to get them for free) - and loose up to a day or more until testing.

**Comment by Ein-Tim** [comment]
Please keep in mind that the app has a rate limit for risk checks. It can only carry out risk checks 6 times in 24h.

**Comment by zpfvo** [comment]
> worst case would be: these people wait for pcr test appointments (they have to somehow wait for red warnings in germany to get them for free) - and loose up to a day or more until testing.

I'm exactly in this position right now. Hoping the update will happen soon so I can get my test.

**Comment by thomasaugsten** [comment]
In emergency cases you can set your device clock 2h in the future to enforce a check but this can cause issue with future checks of the day

**Comment by parttimehorse** [comment]
I think it would be nice if one could exert more influence on update intervals when on mobile data. When I was on vacation a while back, I was trying to keep a close eye on the app and found it a little frustrating not being able to get the app to download keys as often as when I'm home and with Wi-Fi. It's not a huge deal but if it were possible, it would be nice being able to get 6 updates a day on mobile data, too. (I assume it's not set to behave like that for mobile data usage reasons?)

At least in my view, that'd make the efficacy more robust for people temporarily or permanently without Wi-Fi. In any case, this app has warned me reliably, effectively and accurately in the past few weeks so - thanks!

**Comment by mtwalli** [comment]
it might be improved by #5510 ,but due to daily quota we can't request calculation often.
