### ISSUE TITLE
When sharing TEK history, stuck on "Datenabruf"

### ISSUE THREAD

**Issue by Elsensee** [corona-warn-app/cwa-app-android#4678]
Hey, unfortunately I do not have the capability of testing and debugging this, but I wanted to share a finding nonetheless.

Due to no IDE or debugging environment with testing infrastructure, I cannot reproduce the bug anymore, but I hoped my description is thorough enough, so that you maybe can.

## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Pixel 4a (5G)
- Android version: 12 (December 2021 Patch)
- App version: 2.15.1

## Describe the bug

Probably after giving permission on a running PCR test to share TEK history and then entering a positive PCR with a TeleTAN, the submit process will work, but won't give clear indication that it was successful by displaying the modal "Datenabruf ..." with a forever spinning circle.

## Steps to reproduce the issue

I must assume that entering a PCR test, giving permission to share, entering a TeleTAN and trying to submit, will result in the bug.

## Expected behaviour

A success message is displayed.

## Additional context

About a week ago I was tested positive and had entered the PCR test into the app, including giving permission to share my TEK history. I received a mail from the lab with the result but they didn't enter the result into the CWA. (They did so in the past, not sure what happened there) So, I got a TeleTAN, overwriting with it the old "unfinished PCR test". It showed me then a positive PCR and asked me to share my TEK history. I accepted (again), asked me what check-ins to share and about my symptoms. After entering no symptoms and clicking "finish" a blocking modal appeared with "Datenabruf ..." - at the same time, Google Play Services told me via notification, my TEK were being requested. The modal stayed there for two minutes until I decided to close the app, wanting to try it maybe again. It didn't work, it didn't let me re-do the process.

(After waiting whether on the next refresh a close person of me would get a red warning - she didn't - I requested another TeleTAN. It hung again at the same point with the modal "Datenabruf ...", spinning forever, though this time without a Google notification)

At no point was there a success dialog or clear indication that the submit process worked. The app of my close friend eventually turned red after about 12 hours. (which is a surprisingly long time, I thought the CWA is supposed to warn much, much faster)

---
Internal Tracking ID: [EXPOSUREAPP-11254](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11254)

**Comment by Ein-Tim** [comment]
This is definitely not the intended behavior as you can see here: https://www.coronawarn.app/de/screenshots/#android_registertest

**Comment by Elsensee** [comment]
Thank you, @Ein-Tim! I've changed the title to be more precise.

Off-Topic: I've since learned that the servers wait 120 minutes after the rolling period ended. There probably also is a bit of caching involved, but.. that wasn't supposed to be the topic of this issue. :)

**Comment by larswmh** [comment]
Thanks for your report @Elsensee. We have created an internal ticket and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-11254](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11254)

---
Corona-Warn-App Open Source Team

**Comment by mtwalli** [comment]
Comment from Investigator:
>Concluding from the description, this is likely fixed with other bug tickets https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13178 and https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13477
I tried to reproduce, but was unable
