### ISSUE TITLE
I have three vaccinations and CWA shows a red warning 14 days long

### ISSUE THREAD

**Issue by coder66** [corona-warn-app/cwa-app-android#4690]
I have three vaccinations and the CWA app still shows a high risk detection during a 14-day period. This is too long and should be shortened. Also, for people who are had a booster, CWA should show a "low risk" green warning as quarantine is not required by law.

**Comment by Ein-Tim** [comment]
@coder66 Please take a look at https://www.coronawarn.app/en/faq/#vac_cert_risk_assesment.

**Comment by coder66** [comment]
Thank you. Due to the changed parameters of the pandemic, this now causes confusion. Perhaps this part can be improved.

**Comment by Ein-Tim** [comment]
@coder66 

There is an enhancement request for this:
- https://github.com/corona-warn-app/cwa-wishlist/issues/488

**Comment by vaubaehn** [comment]
@Ein-Tim 
While the enhancement request focuses on taking information about the user into account (in terms of vaccinations etc.), I think it does not make much sense to have a dispay period for the red tile of 14 days, while the quarantine/isolation-period is now to reduced to max. 10 days (or 7 with test).

@dsarkar @larswmh is the reduction of the display period of the red tile (i.e. to 10 days) something that is already in the backlog?
In general I think it would be helpful to transfer as much of such values to the (remote-)appconfig to be able to adjust them also with changes in the future (e.g. a new variant causes extension or further reduction of display period).

**Comment by Ein-Tim** [comment]
@vaubaehn 

Just a very little comment, which suggest that something is planned here: Hi, this might be of your interest for WAC: https://github.com/corona-warn-app/cwa-website/pull/2177#discussion_r782365338
Seems like there is an update in planning to only use the last 10 days and leave days 11-14 out.
No more information on this yet, besides of this comment.

**Comment by vaubaehn** [comment]
@Ein-Tim Cool, thanks! 👍

**Comment by Ein-Tim** [comment]
Can this issue be closed?

**Comment by MikeMcC399** [comment]
@coder66 

With the release of CWA 2.20 on March 30, 2022 the risk detection period was reduced from 14 days to 10 days. Does this meet your expectations?

![image](https://user-images.githubusercontent.com/66998419/165350330-a638347d-a2a4-4712-b332-f7da2781f565.png)

**Comment by coder66** [comment]
Yes, thank you. Although, the general incubation time is somewhere between 5-7 days. Let's hope people do not deactivate CWA because of the red warning being there “constantly”. 26.04.2022, 18:41, "Mike McCready" ***@***.******@***.*** the release of CWA 2.20 on March 30, 2022 the risk detection period was reduced from 14 days to 10 days. Does this meet your expectations?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by MikeMcC399** [comment]
@coder66 

I understood that your expectations have been met for this issue, so would you like to close it now? You should be able to that yourself if you use the GitHub web interface or the GitHub App.
