### ISSUE TITLE
Status Page not Red despite having increased risk in second space 

### ISSUE THREAD

**Issue by deepdigger** [corona-warn-app/cwa-app-android#4695]
## Avoid duplicates
* [ x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ x] Bug is not already reported in another issue (that I've seen)

## Technical details

- Device name: Poco X3 NFC 128GB
- Android version: 11
- App version: 2.15.1

## Describe the bug

My smartphone has a "second space" mode, where I can add a separate space for eg work (kinda like a second account, but still different). 
In the second space, the Exposure logging doesnt work. ("Covid-19 Exposure Notifications System is not available on your ...."). 
However, thats not the bug.

The Problem is, that I still use the CWA to log in into Restaurants. 
Then, sometimes I get an notification from the CWA.

If i go to the CWA I can see from the Journal Tab, that I have increased Risk based on my Restaurant visit.
In my "Status" page I can see also, that I have an increased Risk. However, the is not red how it should be and as it is with my partners phone. 
I suspect, that this problem arises because I dont have exposure logging active.
However, Im also not quite sure if it is intended behaviour.

## Steps to reproduce the issue

![Screenshot_2022-01-17-18-16-22-746_de rki coronawarnapp](https://user-images.githubusercontent.com/32137458/149813221-96706f44-3742-4d8e-8154-216b040d8e15.jpg)
![Screenshot_2022-01-17-18-16-13-469_de rki coronawarnapp](https://user-images.githubusercontent.com/32137458/149813240-3fe80bcc-6a0d-4bcf-a41b-7414e00accf3.jpg)

## Expected behaviour
 I expected the Status Page to turn Red as I have an increased risk status. 

## Additional context
This could cause more problems, because in some Bundesländer you can make an PCR with a "red CWA app warning". 
In my case, it is not completely clear if i am elidigble to make an PCR test or not.

**Comment by Ein-Tim** [comment]
See also: https://github.com/corona-warn-app/cwa-documentation/issues/773

**Comment by deepdigger** [comment]
ok, I didn't find that. I guess my Issue can be closed then. Thanks!
