### ISSUE TITLE
Status in 2.16.2 not correct

### ISSUE THREAD

**Issue by rhaener** [corona-warn-app/cwa-app-android#4697]
## Technical details

- Device name:
- Android version: 12
- App version: 2.16.2

## Describe the bug

Although the first vaccination was not registered with a QR-Code (was not possible at that time), my second and third vaccinations have been identified correctly with their number. However, my status is 2G

## Steps to reproduce the issue

- First vaccination with the QR-Code not provided
- Second and Booster with QR-Code, correctly identified by number
- Certificate shows correct number: 3
- Status is "2G"

## Expected behaviour

Correct Status independent of number of QR-Codes

## Additional context

---
Internal Tracking ID: [EXPOSUREAPP-11401](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11401)

**Comment by Ein-Tim** [comment]
This is correct at the moment, see: https://www.coronawarn.app/de/faq/#admission_policy

**Comment by dsarkar** [comment]
Hi @rhaener,

- See FAQ:
  - DE https://www.coronawarn.app/de/faq/#admission_policy
  - EN https://www.coronawarn.app/e/nfaq/#admission_policy
  - **DE** 
   > Wird bei 2G+ meine Auffrischimpfung berücksichtigt? 
   Laut Beschluss der Gesundheitsminister*innen von Bund und Ländern müssen Geimpfte oder Genesene, die eine Auffrischimpfung (Boosterimpfung) erhalten haben, bei einer 2G+-Regelung momentan keinen aktuellen Test vorlegen. Die Corona-Warn-App berücksichtigt diese Regelung in der Statusanzeige derzeit noch nicht. Bei vorhandenem Impf- oder Genesenenzertifikat und Zertifikat der Auffrischimpfung zeigt sie nicht den Status 2G+ an, sondern 2G. Das Projektteam arbeitet bereits daran, dass die Corona-Warn-App in Zukunft Zertifikate von Auffrischimpfungen entsprechend einbezieht.
  - **EN** 
  > Will 2G+ take my booster vaccination into account?
  > According to a decision by the federal and state health ministers, vaccinated or recovered persons who have received a booster vaccination are currently not required to submit a current test in the case of a 2G+ regulation. The Corona-Warn-App does not currently reflect this regulation in the status display. If a vaccination or recovery certificate and booster vaccination certificate are available, it will not display a 2G+ status, but will display 2G. The project team is already working on ensuring that the Corona-Warn-App will include certificates of booster vaccinations accordingly in the future.

- See also the blog article:
  - DE https://www.coronawarn.app/de/blog/2022-01-17-cwa-2-16/
  - EN https://www.coronawarn.app/en/blog/2022-01-17-cwa-2-16/
  - EN
  >2G+ with booster vaccination: According to the decision of German federal and state health ministers, vaccinated or recovered people who have received a booster vaccination do not have to provide a test certificate under a 2G plus arrangement. The CWA does not yet take this rule into account in the status display. This means that if a user has a vaccination or recovery certificate and a booster vaccination certificate, it does not display the status 2G+ yet. The project team is already working to ensure that the CWA includes booster vaccination certificates accordingly in the future.
  - DE
  >2G+ mit Auffrischimpfung: Geimpfte oder Genesene, die eine Auffrischimpfung (Boosterimpfung) erhalten haben, müssen laut Beschluss der Gesundheitsminister*innen von Bund und Ländern bei einer 2G-Plus-Regelung momentan keinen aktuellen Test vorlegen. Die CWA berücksichtigt diese Regelung in der Statusanzeige derzeit noch nicht. Das heißt, bei vorhandenem Impf- oder Genesenenzertifikat und Zertifikat der Auffrischimpfung zeigt sie noch nicht den 2G+-Status an. Das Projektteam arbeitet bereits daran, dass die CWA in Zukunft Zertifikate von Auffrischimpfungen entsprechend einbezieht.

Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by rhaener** [comment]
OK, understood 👍
