### ISSUE TITLE
Combined test and vaccination certificates are not displayed.

### ISSUE THREAD

**Issue by Maxilogi95** [corona-warn-app/cwa-app-android#4705]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ x ] Bug is not already reported in another issue

## Technical details

- Device name: Samsung S8
- Android version: 9
- App version: 2.16.2

## Describe the bug
The two types of certificates are displayed as separate certificates, as for different persons.
The two first names, last name and date of birth are the same for the test and vaccination certificate.

## Steps to reproduce the issue
1. Add three vaccination certificates with two first names, name and birthday
2. Add test certificate with same names and birthday
3. Now, in my case two separate certificates will be shown and not a combined one mit tabs.

## Expected behaviour
I expect a combined view of test and vaccination certificate for the same person.

## Possible Fix
-

## Additional context
-

**Comment by Ein-Tim** [comment]
Is the standardized name of the certificates the same?

**Comment by Maxilogi95** [comment]
How can I see the standardized name in the app? Is it possible, that this is a problem with deinestadttestet.de ? I wrote in "Vorname" both first names and in "Nachname" my last name.

**Comment by Ein-Tim** [comment]
@Maxilogi95 

Take a look at [Corona-Warn-App version 2.8 displays names in certificates in standardized characters](https://www.coronawarn.app/en/blog/2021-08-25-cwa-version-2-8/).

**Comment by Maxilogi95** [comment]
You are right! 
The test certificate shows a standardized name: SECONDFIRSTNAME<LASTNAME<<FIRSTFIRSTNAME.
The vaccination certificate shows: LASTNAME<<FIRSTFIRSTNAME<SECONDFIRSTNAME.

Should I contact the test station operator?

**Comment by Ein-Tim** [comment]
@Maxilogi95 

Yes but if you entered both your firstname and your secondfirstname into the firstname field of the testing station, the system probably did everything right. 

Anyways this is not an issue with the CWA so I recommend to close this issue.

**Comment by Maxilogi95** [comment]
@Ein-Tim 
Thanks for your help!
