### ISSUE TITLE
2G für Dritimpfung

### ISSUE THREAD

**Issue by ghost** [corona-warn-app/cwa-app-android#4712]
Gerade das neue Updatet bekommen. Bei meiner dritten Impfung vom 21.12.21 rechts oben vom QR-Code steht 2G. Müsste da nicht 2G+ stehen. 

---
Internal Tracking ID: [EXPOSUREAPP-11401](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11401)

**Comment by Ein-Tim** [comment]
Hi, @cannothing 

Das ist momentan so korrekt, schau mal bitte hier: https://github.com/corona-warn-app/cwa-app-android/issues/4707#issuecomment-1017289523

Schließe dann bitte diesen Issue.

**Comment by vaubaehn** [comment]
Hi @thomasaugsten (or @dsarkar / @larswmh ),

I hope you're ok, if I hijack this issue for a related 
question:

Do you already have something in your backlog to remote-administrate admission rules (2G+/2G/3G+/3G) in a way, that they can be changed remotely on the fly when there are changes in legislation (e.g., shorter or longer validity periods, additional or less criteria...) _without_ the necessity of an app-update?

If no, I would work on a proposal for the wishlist. I have something in mind that could be implemented with medium effort.

If yes, I won't waste time on the proposal.

Thanks a lot in advance for your response!

**Comment by thomasaugsten** [comment]
We already implementing this for mid of Feb
https://github.com/corona-warn-app/json-functions-swift

**Comment by vaubaehn** [comment]
Thanks, @thomasaugsten , it seems that is exactly what I was thinking about. Will IBM. Be aligned (especially CovPassCheck)?
I highly recommend to open source the Exkursion rules that you're going to implement, as the community could help out in implementing timely changes (as we see, BMG is sometimes fast and Les communicative...). That may even allow to brake down rules on levels of federal states. And supporting work from the community could reduce the work load for the team in charge.

**Comment by thomasaugsten** [comment]
We have  no influence on the CovPass Backlog.
We will use JSON Function for CWA
All components and rules are open source.

**Comment by tasomaniac** [comment]
What about displaying the number of vaccinations? Right now all restaurants and cafes require us to hold our phone, scroll to the bottom to see 3 vaccinations. This makes QR code and contactless verification pretty much useless.

I heard that on iOS, the QR code can be extracted to the iPhone's wallet app where it displays "3/3" and restaurants actually started to accept this sign already.

**Comment by Ein-Tim** [comment]
@tasomaniac 

There is no "Import to Apple Wallet" feature under iOS with CWA.

**Comment by tasomaniac** [comment]
I am not sure how that is done but a restaurant recommended it to me.

Anyways, that's not my point.

**Comment by Ein-Tim** [comment]
@tasomaniac 

We could show the number of vaccinations but for what? The user should not present this information during a check process, but only the QR code should be scanned.
CovPassCheck will receive an update to check 2G+ in a version which will be released on the beginning of February.

**Comment by tasomaniac** [comment]
Let's see if anything changes in Feb. I'm afraid that by then the rules will change again and it will not be enough.

At the moment, shop owners have to scroll down and see that number. There is literally no other way. And I'm afraid millions of people are already getting used to doing so.

**Comment by Ein-Tim** [comment]
@tasomaniac Yeah I know but if we would start implementing this feature in the CWA now it would also only be rolled out to in the beginning of February.

**Comment by Ein-Tim** [comment]
@dsarkar 

Please apply the `Fix 2/18` label here.

@ALL please check back with version 2.18, see: [CWA 2.18: Improving the display of the G status in the Corona-Warn-App](https://www.coronawarn.app/en/blog/2022-02-23-cwa-2-18).

**Comment by ckujau** [comment]
This request to show 2G+ for booster vaccinations comes up [again](https://github.com/corona-warn-app/cwa-app-android/issues/4697) and [again](https://github.com/corona-warn-app/cwa-app-android/issues/4707) and often the [FAQ](https://www.coronawarn.app/e/nfaq/#admission_policy) is cited to respond:

> The project team is already working on ensuring that
> the Corona-Warn-App will include certificates of 
> booster vaccinations accordingly in the future.

So, that's great that this is being worked on, but: what's the tracking bug for this work? And is there an ETA when this will be [released](https://youtu.be/DtRNg5uSKQ0)?

**Comment by MikeMcC399** [comment]
On CWA Android 2.18.1 I see a Proof of Status `2G+` with only a 3/3 vaccination certificate loaded. With only a 2/2 vaccination certificate loaded, the app displays Proof of Status `2G`. This is correct.

@cannothing 
Would you check that this is working for you now? If yes, then you could close the issue. The FAQ article [What does the 2G+ status proof mean in concrete terms?](https://www.coronawarn.app/en/faq/#admission_policy_2gplus) describes each case which should lead to a `2G+` display.  (In German: [Was bedeutet konkret der 2G+-Status-Nachweis?](https://www.coronawarn.app/de/faq/#admission_policy_2gplus).)

By the way, there is a typo in the title. It should be "Drittimpfung".

**Comment by tasomaniac** [comment]
It worked for me. I haven't had a chance to show it to a restaurant or shop. I'm curious if this will be enough for them or will they still ask us to open it and scroll to bottom to see vaccination count. Even though the apps says not to do that, it is now a common practice

**Comment by Ein-Tim** [comment]
@cannothing What about you? Does the app show 2G+?

**Comment by cannothing** [comment]
No. Because there is no update.

Am 25. Februar 2022 13:55:48 MEZ schrieb Tim ***@***.***>:
***@***.*** What about you? Does the app show 2G+?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/corona-warn-app/cwa-app-android/issues/4712#issuecomment-1050829438
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- 
Viele Grüße
Stephan Zitzmann

**Comment by MikeMcC399** [comment]
@cannothing 
Did you check on https://play.google.com/store/apps/details?id=de.rki.coronawarnapp for an update?

**Comment by MikeMcC399** [comment]
@cannothing 
Did you have an opportunity to check with the current 2.18.1 version?

**Comment by riQQ** [comment]
See also [corona-warn-app/cwa-wishlist/#763](https://github.com/corona-warn-app/cwa-wishlist/issues/763).

**Comment by dsarkar** [comment]
Dear @cannothing,
Dear community,

Thanks everybody for contributing here. We will close this issue as fixed. Feel free to create a new issue should it be needed. Thanks. Best wishes, DS

---
Corona-Warn-App Open Source Team
