### ISSUE TITLE
Corona Warn App Cause 3: something went wrong  NOT SOLVED!

### ISSUE THREAD

**Issue by Codaxx** [corona-warn-app/cwa-app-android#4714]
HI.

i cannot activate my exposure logging on my phone. A screenshot of the problem is below. 

Phone Type: Xiaomi 9 (bought in China)
System: MIUI 12.5.6 stable (Android 10)

I have also enabled all permissions for the app but it didnt change anything. 

![e98de3d1afc79604dfb660312d9ae00](https://user-images.githubusercontent.com/76975278/150396907-e8aaae03-ea43-442a-834e-dd883b864e9a.jpg)

**Comment by thomasaugsten** [comment]
I looks like the device has no Google Play Services installed

**Comment by Codaxx** [comment]
if i look up in th settings for google i can find this 

It is not that detailed as you listed but im sure i have google on my phone 

![76fddc79a67ccbc14e5f9a34fe70981](https://user-images.githubusercontent.com/76975278/150400372-9c0ff197-a927-4840-b725-e0ceacb421cc.jpg)

**Comment by MikeMcC399** [comment]
@Codaxx 

Your phone needs to show COVID-19 support under Google, otherwise CWA cannot work.

There is an alternative app which does not need Google published through F-Droid called CCTG. That might be your best option.

**Comment by Codaxx** [comment]
@MikeMcC399 

so it it a system problem which cannot be fixed? Then i will give CCTG a try.

thx
