### ISSUE TITLE
Provide more helpful crash/error messages for troubleshooting

### ISSUE THREAD

**Issue by corneliusroemer** [corona-warn-app/cwa-app-android#472]
The app is live and the first crash reports are circulating on Twitter.

There seem to be issued with Xiaomi as expected due to lack of PlayServices. But someone also reported an issue with a recent Motorola phone.

It would be great if there was a troubleshoot article somewhere on the website with steps on how to find out if an issue is fixable and how, or if it's impossible due to OS limitations.

Right now, simply getting "Cause 3: Problem with ExposureAPI " is maybe helpful for developers but not for the general public.

So ideally, the error messages contain a link to the website which is to be created.

Please do so quickly. You will have only one shot with most people.

See this Tweet: https://twitter.com/saxokalypse/status/1272668057484300288?s=19

**Comment by tkowark** [comment]
In the latest version of the app, these error messages have been enhanced and now also contain a link to the FAQ. This should hopefully give people a much simpler way of figuring out, what the real issue is and how they might be able to circumvent it.
