### ISSUE TITLE
Incorrect duration in journal after check out

### ISSUE THREAD

**Issue by DerVogel2020** [corona-warn-app/cwa-app-android#4724]
## Technical details

- Device name: Samsung Galaxy A5 2017
- Android version: Android 8.0
- App version: 2.16.2 (Bug occurs also at least in 2.15)

## Describe the bug

After check out after 40 Minutes the duration in the journal is 45 Minutes. Editing the duration is possible, but only with changing the duration.

## Steps to reproduce the issue

For example (without waiting 40 Minutes):
1. Create a qr code for an event
2. Check in to that event
3. Change the time on the smartphone to +40 minutes
4. Check out
![Screenshot_20220124-104655_Corona-Warn](https://user-images.githubusercontent.com/65366950/150760872-f69eb42f-eb9a-4f24-9d1d-68d3482032cd.jpg)

5. See journal
![Screenshot_20220124-104642_Corona-Warn](https://user-images.githubusercontent.com/65366950/150760816-fe66ce09-dce3-4884-a8d0-0c40b53eb97d.jpg)

6. Try editing the duration in the journal
![Screenshot_20220124-104723_Corona-Warn](https://user-images.githubusercontent.com/65366950/150760920-a9f67dff-51f5-4457-a01d-33ff165dddca.jpg)

## Expected behaviour

Duration in journal should be 40 minutes.

## Possible Fix

May be this is because the default check out durations  are in 15 minutes steps. I assume that the duration steps in event-handling were not modified when the duration steps in the journal changed from 15 minute steps to 10 minute steps (I couldn't find the corresponding issue).

## Additional context

I don't know if this is also a problem under iOS.

---
Internal Tracking ID: [EXPOSUREAPP-11549](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11549)

**Comment by larswmh** [comment]
Thanks for your report @DerVogel2020. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-11549](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11549)

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
FYI - Will be fixed with https://github.com/corona-warn-app/cwa-app-android/pull/5245

**Comment by MikeMcC399** [comment]
@dsarkar 

- If PR #5245 was not merged in 2.24 and it is https://github.com/corona-warn-app/cwa-app-android/labels/on-hold, then presumably the https://github.com/corona-warn-app/cwa-app-android/labels/Fix%202%2E24 label should be removed.

**Comment by MikeMcC399** [comment]
- https://github.com/corona-warn-app/cwa-app-android/pull/5371 has the same internal ID as this issue and it is targeted for 2.26.
