### ISSUE TITLE
Ursache 3 nix geht 

### ISSUE THREAD

**Issue by NS1982** [corona-warn-app/cwa-app-android#4729]
Hallo.... Ich musste leider einen pcr test machen u wollte diesen mit der warn app abrufen. Doch bei mir kommt nur Ursache 3 und nix geht
Anbei mal Screenshot vom Fehler.. Hoffe es kann jemand helfen
Lg
![Uploading Screenshot_20220124_203507_de.rki.coronawarnapp.jpg…]()

!--
Thanks for submitting your question 🙌 ❤️

Before opening a new issue, please make sure that we do not have any duplicates already open. You can ensure this by searching the issue list for this repository. If there is a duplicate, please close your issue and add a comment to the existing issue instead. Also, please, have a look at our FAQs and existing questions before opening a new question.
-->

## Avoid duplicates
* [ ] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Question is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Question has not already been asked in another issue

## Your Question

* Source File:
* Line(s):
* Question:

**Comment by MikeMcC399** [comment]
@NS1982 
> Anbei mal Screenshot vom Fehler..

The screenshot is not appearing here.

An alternative channel for technical support is the hotline 0800 7540001. See https://www.coronawarn.app/en/faq/#international_phone_numbers.

**Comment by MikeMcC399** [comment]
@NS1982 
Do you need any more help with this? We didn't hear back from you.

It would also be helpful for you to mention your configuration, as well as supply the screenshot you mentioned:

- Device name:
- Android version:
- App version:

**Comment by Ein-Tim** [comment]
Can this issue be closed?

**Comment by MikeMcC399** [comment]
@dsarkar / @larswmh 

Please close this issue as the author of the question is no longer responding, so no progress can be made.

**Comment by larswmh** [comment]
Closing this issue because the author is no longer responding.

---
Corona-Warn-App Open Source Team
