### ISSUE TITLE
Explain why you need all the different permissions

### ISSUE THREAD

**Issue by corneliusroemer** [corona-warn-app/cwa-app-android#473]
There are people wondering what all the different permissions are needed for.

Please explain why you need every one of them. There will always be paranoid Germans.

Some of them sound like something they are not. For example pairing isn't really needed, but this is what Google calls the permission, etc.

All of this should help, but please make it explicit. There's no harm.

Sample tweets asking these questions:
https://twitter.com/ScotlandIlove/status/1268085279082020866?s=19
https://twitter.com/ClemensPrill/status/1272155729110196225?s=19
https://twitter.com/bendrath/status/1272659854235250690?s=19

App permissions

Version 1.0.0 may request access to

Camera
take pictures and videos

Other
• run foreground service
 • have full network access view network connections
• prevent phone from sleeping
 • Pair with Bluetooth devices
 • run at startup

**Comment by dan-nkl** [comment]
It looks like some phones will ask for location access to use Bluetooth. People are wondering and giving 1 star ratings on the play store.

**Comment by bjoerrrrn** [comment]
> Camera
> take pictures and videos

The camera permission will be requested if a user wants to scan a TAN. It's not a default permission request.

> Other
> • run foreground service
> • have full network access view network connections
> • prevent phone from sleeping
> • Pair with Bluetooth devices
> • run at startup

Don't you think these are self-explanatory permissions for the task of the app?

**Comment by SebastianWolf-SAP** [comment]
As the questions were already answered and especially the location services aspect already covered in #262, we will close this issue.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by corneliusroemer** [comment]
@SebastianWolf-SAP What do you mean by question is answered? I wasn't asking a question. I know why the camera is asked for.

Just thousands of people out there don't. I'm asking so you don't loose them. But you don't seem to care.

It's not a technical question, it's about communication to skeptical people.
