### ISSUE TITLE
It's not easy to find the Corona-Warn-App in the Google Play Store for an installation

### ISSUE THREAD

**Issue by jensplixplox** [corona-warn-app/cwa-app-android#474]
Having opened the Google Play Store, and trying to find the Corona-Warn-App by typing in certain search words in that field at the top of the GUI of the Google Play Store, results in 0 hits regarding the possibility to install the Corona-Warn-App.

Searching with these key words does not result in the possibility to install the Corona-Warn-App:

corona warn app deutsch
corona warn app deutschland
corona app
corona-warn-app
corona warn app

Searching with these key words **does** result in the possibility to install the Corona-Warn-App:

corona-warn-app pepp-pt (Note: an average user does not know anything about the meaning of "pepp-pt")
corona-warn-apps

The Corona-Warn-App should be provided with more and simpler keywords in the Google Play Store in order to enable users to find that app for an installation, to increase the use of the Corona-Warn-App by persons located in Germany.

**Comment by dan-nkl** [comment]
Google seems to show selected apps for some keywords like "corona".
Searching for "coron-warn" will show the app.

**Comment by jensplixplox** [comment]
> Google seems to show selected apps for some keywords like "corona".
> Searching for "coron-warn" will show the app.

An average user will not search for the string "corona-warn" in the Google Play Store.

An average user will search for "corona", "corona app" or "corona warn app".

I had to visit bundesregierung.de on my laptop to find out that the Corona-Warn-App is called "Corona-Warn-App" in the Google Play Store (but once installed, it is called "Corona-Warn") - the web site bundesregierung.de contains a link to the Apple and Google Play Store for downloading the Corona-Warn-App. 

But searching for "Corona-Warn-App" in the Google Play Store does not result in the possibility to install the Corona-Warn-App. Instead, searching for among others things "Corona-Warn-App**s**" gives you the possibility to install the Corona-Warn-App, which seems to be illogic according to me if you look at the result of such a search.

**Comment by dan-nkl** [comment]
I understand you. The typo in "coron-warn" was on purpose. You can even search for "coron" and the app will show up in the search results along other apps that won't show up searching for "corona".

It really is a problem but it seems like Google is filtering here.

**Comment by IT-Cru** [comment]
Maybe the keyword corona or corona virus (not coronavirus) and official + german(y) should included as a short clear description at top of text in all stores for this app.

After this start with "The Robert Koch Institute (RKI) as the ..." with a new paragraph.

Also other suggested corona apps should investigated for good keywords and clear descriptions.

**Comment by WilliamReed2004** [comment]
![Screenshot_20200616-081133](https://user-images.githubusercontent.com/29880819/84737990-55151400-afa9-11ea-8d97-5d091c3a6a4d.png)

I did not have any problem finding the App. I searched for Corona, Corona-Warn, Corona-Warn-App, Corona Warn App, Corona-App, Corona App and every search gave me a result just like in the Screenshot attached

**Comment by dan-nkl** [comment]
![Screenshot_20200616-081637](https://user-images.githubusercontent.com/26377301/84738193-c5239a00-afa9-11ea-909b-911827922e8c.jpg)
This is how it looks for me. But you can clearly see that this are not regular search results!

**Comment by JonahKr** [comment]
This is very true. I searched for quite some while until I found it. My trick was searching for Robert Koch Institute, which released 2 apps so far with corona-warn being one of them. I assume however that Google will include this app into the selection in the near future.

**Comment by WilliamReed2004** [comment]
I think it could also have somthing to do with the localization settings. I have my phone set to German, the rest of my family has it set to English and they had problems finding it. or Maybe Google ist still rolling the app out in some weird way. I would even consider clearing Google Play Cache before Searching.

**Comment by dan-nkl** [comment]
I've already checked that and of course with clearing cache. This had not effect, besides the different language :laughing:

**Comment by leorbs** [comment]
I had the same problem with localisation / country today.
Play Store -> Swipe Left -> Account -> Scroll down 
and make sure you are currently logged in with an account where the Country is set to "Germany". There are also options to change.

**Comment by kreincke** [comment]
(Un)fortunately, I have to state, that the description and the solution in this issue is valid with respect to the time 2020-06-16T08:45

**Comment by kreincke** [comment]
Just redone the test on my second tablet: even the search string "corona-warn-app" does not deliver the intended hit. Only the addendum pepp-t helps

**Comment by 4rz0** [comment]
Same issue here.
I and people I know have to use the exact string "corona-warn-app pepp-t" to find the app.

**Comment by mynchau** [comment]
Thanks for raising this issue. Multiple keywords have been added to the app but unfortunately it takes a while until the search results are synchronized on all devices. While Apple has been made aware of this issue, the app is appearing as sponsored app in the meantime. 
Best regards, 
MC Your Corona Warn-App Open Source Team

**Comment by mynchau** [comment]
Here is a selection of keywords that have been added: _Covid, Covid-19, tracing, Robert Koch, Corona, rki, deutschland, tracking, Corona Warn, 19, Bundesregierung_
In some cases it has been reported that the keyword _Corona App_ has shown the app as first result.
Best regards,
MC Your Corona Warn-App Open Source Team

**Comment by kreincke** [comment]
Just now, I've redone the test: On my Android mobile phones I find the app in the Android store simply by using the search word "corona": it is placed at the top of the list (4,7 stars). Hence, everything seems to be fine.

**Comment by daimpi** [comment]
One more thing which would probably grant the app more visibility and appeal: you could get the "Empfehlung der Redaktion" ribbon in the play store. 

Dunno whether you have a direct line to Google, but it would certainly make sense for them to give you this banner as this app is the sole authorized tracing app for Germany with access to their Exposure Notification api.

**Comment by mynchau** [comment]
Thanks all, Google and Apple are aware and have featured the app. Closing this issue as it's fixed. 
Best regards
MC
Your Corona Warn-App Open Source Team
