### ISSUE TITLE
Faking contact (red warning)

### ISSUE THREAD

**Issue by d3tr0id** [corona-warn-app/cwa-app-android#4756]
Hi together,

I heard from a companion that he went to the pharmacy with the app and showed the red warning so that he was contact person (or also infected who knows?) of an approved COVID case. This was enough to receive an official "recovered-from-covid"-Certificate. 

My question now is: Isn't this a political fault due to the fact someone can easily hack their way to the red warning in the app? Is there an easy way to force the app to show the red warning without even having real contact to someone?

I'm just really curious, because if this is so easy, I will take this to a court.

**Comment by d3tr0id** [comment]
Sorry my fault. The guy also had a letter from the officials that he was contact person of a COVID case. I guess this combined with the status in the app got him the certificate.

**Comment by Ein-Tim** [comment]
A recovery certificate is only issued with a positive PCR test which is older than 14 days.
See https://ec.europa.eu/info/live-work-travel-eu/coronavirus-response/safe-covid-19-vaccines-europeans/eu-digital-covid-certificate_en which says:
![image](https://user-images.githubusercontent.com/67682506/151694379-d0a94816-ce97-4e1a-a7b7-06565758235a.jpeg)
