### ISSUE TITLE
Usage of Personal "Du"-Addressing in Test Registration Process

### ISSUE THREAD

**Issue by jkrwdf** [corona-warn-app/cwa-app-android#4759]
The CWA generally uses the German "Sie" form to address the user. 

Examples: 
"Sie lassen sich testen?"
"Finden Sie Teststellen..."
"Ihre Zertifikate erfüllen die..."

However, in this dialog (appears when registering a test) the "Du"-form is used:

![image](https://user-images.githubusercontent.com/5329491/151751961-1872145e-475f-4499-bc96-97fd05d3d0d3.png)

---
Internal Tracking ID: [EXPOSUREAPP-11614](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11614)

**Comment by larswmh** [comment]
Thanks for your report @jkrwdf. We have moved this issue to the Android repository as suggested above. Additionally, we have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-11614](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11614)

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
I'd like also to mention that Google itself uses both "du" and "Sie". It seems that on-device messages use "du" whereas website instructions use "Sie". I don't know if that is Google's general style guide though.

### Example on-device with "du"

Einstellungen > Google > COVID-19-Benachrichtigungen
"**Einstellungen des Smartphones:** Nachdem du die COVID-19-Benachrichtigungen aktiviert hast, beginnt dein Smartphone damit, über Bluetooth auf sichere Weise die Zufallserkennungen an diese weiterzugeben."

### Example on web with "Sie"

now tip on the link [Weitere informationen](https://support.google.com/android/answer/9888358?hl=de) and the following page appears:

"**COVID-19-Benachrichtigungssystem auf Ihrem Android-Smartphone aktivieren**

Wenn Sie wissen möchten, ob Sie mit einer Person Kontakt hatten, die positiv auf COVID-19 getestet wurde und dies freiwillig gemeldet hat, können Sie COVID-19-Benachrichtigungen aktivieren und eine entsprechende App installieren."

**Comment by dsarkar** [comment]
I thinks there is little we can do about this, and is also a minor issue. Google uses "du" and mixes it up sometimes. CWA uses consistently "SIe", as does our FAQ. 

@jkrwdf We suggest closing this issue. 

@MikeMcC399 and @Ein-Tim  Thanks for further investigation and analysis! 

Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by jkrwdf** [comment]
Closing as suggested. 

Eventually someone from the CWA team working on a regular basis with their Google counterparts on the technical side of the house could at least mention this issue. With a certain probability, the Googler then simply says: "Oh, we did not know that, no problem".
