### ISSUE TITLE
GPS wird von der APp eingefordert

### ISSUE THREAD

**Issue by cannothing** [corona-warn-app/cwa-app-android#476]
Als ich die Googleschnittstelle für die App aktieveren wollte, musste ich einwilligen, dass Google meine Standortdaten verarbeiten darf.

Als ich die App installiert habe, wurde GPS und BT angeschaltet. Also habe ich GPS abgeschaltet. Da wurde ich angemeckert, die App könne so nicht funktionieren. 

Wenn ich dann GPS anschalte, solle ich noch die Standortermittlung verfeinern.

In dem den Medien wurde kommuniziert es geht nur mit BT. 

Abgesehen vom Datenschutz. GPS frisst mir einfach zu viel Strom. 

S7 mit Android 8

**Comment by SebastianWolf-SAP** [comment]
Es handelt sich hier um eine Besonderheit des Betriebssystems Android, die nicht umgangen werden kann und auch nicht umgangen werden darf. Bluetooth kann immer nur zusammen mit Standortinformationen eingeschaltet werden. Details dazu sind in der [Android Bluetooth Entwickler-Dokumentation](https://developer.android.com/guide/topics/connectivity/bluetooth) erklärt.

In unserer FAQ und allen damit zusammenhängenden Kommunikationskanälen erklären wir jedoch deutlich, dass wir kein GPS verwenden, z.B. hier: https://www.coronawarn.app/de/faq/

Weitere Details dazu und zu einer vorherigen Diskussion finden Sie unter #262.  Vielen Dank für Ihr Verständnis!

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
