### ISSUE TITLE
APK release assets

### ISSUE THREAD

**Issue by freakatzz** [corona-warn-app/cwa-app-android#477]
Hello, 
Why don't you provide APK files as asset for releases, so not everybody who want to use the app needs a Google account.

Kind regards, 
freakatzz

**Comment by bjoerrrrn** [comment]
The APK is already on the well known mirror pages like apkpure → https://apkpure.com/de/corona-warn-app/de.rki.coronawarnapp

User who use android without a Google account know such sources. But I agree: an APK Release and/or an F-Droid Release are a good idea.

**Comment by SebastianWolf-SAP** [comment]
We already clarified very early that we can't provide APKs and/or F-Drof releases. Please see https://github.com/corona-warn-app/cwa-documentation/issues/5 for details.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by joergi** [comment]
> The APK is already on the well known mirror pages like apkpure → https://apkpure.com/de/corona-warn-app/de.rki.coronawarnapp
> 
> User who use android without a Google account know such sources. But I agree: an APK Release and/or an F-Droid Release are a good idea.

The version is not up to date. I would not do it.

**Comment by joergi** [comment]
> We already clarified very early that we can't provide APKs and/or F-Droid releases. Please see [corona-warn-app/cwa-documentation#5](https://github.com/corona-warn-app/cwa-documentation/issues/5) for details.
> 
> Mit freundlichen Grüßen/Best regards,
> SW
> Corona Warn-App Open Source Team

@SebastianWolf-SAP  - I understand, why you will not provide it on other stores like F-Droid.
But I don't see any reason, why you are not building the app and provide it here as an APK. (of course without support, if it will fail because people are not having Google Play services (like #507)

**Comment by DE-Max-42** [comment]
If you only need the .apk you can extract it from your device with ADB:

`adb shell pm path de.rki.coronawarnapp`

`adb pull /data/app/com.example.someapp-2.apk path/to/desired/destination`

_source: https://stackoverflow.com/questions/4032960/how-do-i-get-an-apk-file-from-an-android-device_

**Comment by joergi** [comment]
> If you only need the .apk you can extract it from your device with ADB:

@DE-Max-42 people want to download the apk, so they can install it

**Comment by DE-Max-42** [comment]
@joergi 
Yes but if someone wants to make sure that he installs the official app from Google play he can extract the _.apk_

Of course that requires a second device. But I'am always very curious about any third-party that offer the apps to download.  

This makes only sense if you want to install the app but don't want to login with a Google account on the other device.
 
I think I misunderstood the conversation above a bit and not read carefully.
_Sorry that was my mistake._

**Comment by tdollenb** [comment]
Can't you build it from source?

**Comment by joergi** [comment]
Developers can do. but "non developers" who have no glue about technical stuff, but who don't have a google account to download it, can then download it easily here.

**Comment by corneliusroemer** [comment]
> Can't you build it from source? 

No! You need to sign with special secret key to allow the app to interface with ExposureAPI.

**Comment by corneliusroemer** [comment]
> We already clarified very early that we can't provide APKs and/or F-Droid releases. Please see https://github.com/corona-warn-app/cwa-documentation/issues/5 for details.
> 
> Mit freundlichen Grüßen/Best regards, 
> SW
> Corona Warn-App Open Source Team

Dear maintainers (@SebastianWolf-SAP @tkowark @jakobmoellersap )

The referenced issue talks about something very different, in fact the referenced issue deals with multiple issues at once.

You explain there why you can't do some of the things asked for, but not, why you can't publish the APK here.

It's literally just uploading a file. What stops you from doing so?

The referenced issue is also closed. It makes sense to have some place where people can voice their justified views on this topic.

**Comment by assert-not-singularity** [comment]
Besides supporting other stores, there is also another point I want to mention:

I've read that people although living (or just staying) in Germany are not able to install the app if the store is not set to German. They state that changing the region to German is restricted to one time in a year and prevents access to contents bought in another region. I did not fact-check this, though.

Anyway, this could be a scenario where some people could not use the app despite having access to the Play Services. Releasing the APK built by your CI here would them enable to do so.

**Comment by corneliusroemer** [comment]
I think after this issue here got closed I reopened it under #514 
That issue is still open!

**Comment by SebastianWolf-SAP** [comment]
Referenced issue now moved to cwa-wishlist: https://github.com/corona-warn-app/cwa-wishlist/issues/57

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by falkorichter** [comment]
> If you only need the .apk you can extract it from your device with ADB:

```
VERSION=$(adb shell dumpsys package de.rki.coronawarnapp | grep versionName=| cut -d '=' -f 2)
adb pull `adb shell pm path de.rki.coronawarnapp | cut -d':' -f2` de.rki.coronawarnapp-store$VERSION.apk
```

**Comment by joergi** [comment]
@falkorichter it's not about this, but it's also for people, who are visiting germany,.
There Play store country is not set to Germany, so they will not be able to get the App from the Play store

**Comment by falkorichter** [comment]
@joergi I know. But please honor the script I shared which includes the version number!!!

**Comment by rugk** [comment]
BTW raised a very similar issue about this again, because since June the situation has changed and (IMHO) needs to be reconsidered: See https://github.com/corona-warn-app/cwa-app-android/issues/1483.
