### ISSUE TITLE
"2G+"-function shows vaccination certificate although "Test Certificate" is highlighted

### ISSUE THREAD

**Issue by jkrwdf** [corona-warn-app/cwa-app-android#4771]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only (in fact, I do not know as I have no iOS with CWA; maybe this Q could be removed or answered differently)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Google Pixel 3 XL
- Android version: 12
- App version: 2.16.2

## Describe the bug

I currently have for the same user a valid vaccination certificate and a valid rapid test certificate. 
CWA then shows the toogle mode between the two for 2G+ verification. 

Under circumstances which I cannot yet reproduce (I assume they are related to display-off/display-on), the "Test Certificate" is still highlighted, but the QR code shown is the vaccination QR code. 

I demonstrate this in the following screenshot showing the situation:

![image](https://user-images.githubusercontent.com/5329491/152161796-41266cc0-b2c3-4bd5-b805-c18b0608f788.png)

Trust me: When I scanned this QR code, CovPassCheck shows a vaccination, not a test. 

I can proof it a little bit by the following screenshot which shows what happened when I then tapped on "2G-Certificate".

![image](https://user-images.githubusercontent.com/5329491/152162001-6cb7beb5-f71b-45af-a81c-0e037c2510d9.png)

The QR code is exactly the same. 

As final screenshot, here what I get when I then tap back to "Test Certificate": 

![image](https://user-images.githubusercontent.com/5329491/152162221-322d5b22-2976-49d8-9b13-4007ca75ffc0.png)

You can see the QR code is obviously different now. 

## Steps to reproduce the issue

Not yet found out. Will update when I manage.

## Expected behaviour

Always show the right thing.

Internal Tracking ID: [EXPOSUREAPP-12158](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12158)

**Comment by jkrwdf** [comment]
Update: I can reproduce the issue quite reliably (4 of 5 attempts) by the following sequence:

1. Switch to "Test certificate"
2. Return to home screen
3. Start a couple of other apps which were not yet loaded
4. Start CWA by its icon

Seems to be related to a displacement of the CWA by Android and later wake-up

**Comment by jkrwdf** [comment]
Issue still existing in version 2.18.1 and on another device (Google Pixel 4a (5G))

**Comment by dsarkar** [comment]
@jkrwdf OK, Thanks for reporting. We will create an internal ticket shortly.

**Comment by larswmh** [comment]
Thanks for your report @jkrwdf. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-12158](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12158)

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
@jkrwdf  It was not possible to reproduce this on Samsung Galaxy S5 Mini, 2.19.0-RC3

**Comment by jkrwdf** [comment]
The two devices on which I can reproduce it were already mentioned. 

I made a screen recording and uploaded it to YouTube with a private link. If I get a secure drop zone, I can pass it along. As it contains sensitive data, it cannot be posted here in public.

**Comment by dsarkar** [comment]
@jkrwdf ok, thanks, standby.

**Comment by jkrwdf** [comment]
FYI: In one of my previous issues I got a mail address of an SAP employee to drop something directly. 
It was Max...L... I can use the same here if appropriate.

**Comment by dsarkar** [comment]
FYI PR https://github.com/corona-warn-app/cwa-app-android/pull/5085

**Comment by dsarkar** [comment]
FYI PR https://github.com/corona-warn-app/cwa-app-android/pull/5392

**Comment by jkrwdf** [comment]
After receiving 2.26.0 on my device, I cannot reproduce the effect any more. 

The certificate selection ("2G-Zertifikat" / "Testzertifikat") is now stable and always matches the QR code shown in the area above. 

Confirming fix. Closing.
