### ISSUE TITLE
Twitter report: Text in root Information pop up can't be scrolled (App is unusable)

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-android#4777]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy A5 (2017)
- Android version: 8.0.0
- App version: 2.16.2

## Describe the bug

The text in the root information pop up can't be scrolled. This leaves some apps unusable, as the buttons to continue are not reachable. 

## Steps to reproduce the issue

1. Root your device
2. Start the app
3. See the pop up and try to scroll the text down
4. Notice that this does not work

## Expected behaviour

The text should be scrollable. 

## Additional context

This report is based on feedback I received on Twitter: https://twitter.com/RchMichele/status/1488434394092220417?s=20&t=4hDpPxnYTpYNOlVRxlitdw

---
Internal Tracking ID: [EXPOSUREAPP-11676](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11676)

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-11676](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11676)

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for forwarding this issue. Could you suggest maybe this workaround: Decrease font size in system settings, click away the notification, and then the user can increase font size again. Might help(?)

**Comment by Ein-Tim** [comment]
@dsarkar 

I have transferred the suggestion!

**Comment by Ein-Tim** [comment]
I think this is the fasted fix ever, #4778 fixes this and merges into `release/2.17.x`, so this will be part of the version 2.17.2 hot fix!

Thank you @mtwalli!!
