### ISSUE TITLE
400 BadRequestException on opening the app

### ISSUE THREAD

**Issue by maricn** [corona-warn-app/cwa-app-android#4790]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Sony xz2c (xz2 compact)
- Android version: LineageOS 17.1 (Android 10) _with MicroG (it worked flawlessly for many months in this setup)_
- App version: CCTG 2.14.1.3

## Describe the bug

On opening of the app, an error dialog is shown stating there was a bad request exception (HTTP status code 400). Dismissing it and continued use of the app is possible, but on closing the app and reopening, the dialog will reappear.

## Steps to reproduce the issue

The app worked without this issue up to today, for over a year on the same phone with the same OS. I updated the CWapp recently but i've also used it afterwards, and this error only appeared this morning.

1. Open the CoronaWarnApp
2. Notice the error dialog

The full error test is:
```java
de.rki.coronawarnapp.exception.http.BadRequestException: Error during web request: code=400 message= body='

de.rki.coronawarnapp.exception.http.BadRequestException: Error during web request: code=400 message= body='
 at de.rki.coronawarnapp.http.HttpErrorParser.intercept(HttpErrorParser.kt:80)
 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
 at de.rki.coronawarnapp.http.interceptor.RetryInterceptor.intercept(RetryInterceptor.kt:15)
 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
 at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:154)
 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
 at de.rki.coronawarnapp.http.interceptor.WebSecurityVerificationInterceptor.intercept(WebSecurityVerificationInterceptor.kt:11)
 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
 at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
 at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:919)
```

Screenshots:
<div>
<img src="https://user-images.githubusercontent.com/3995223/152780620-0a49bb4d-1cb7-4417-8292-858d5f7377fd.jpg" width="300px"/>
<img src="https://user-images.githubusercontent.com/3995223/152780635-4946ef2a-1ba0-4d02-8fdb-8604268b1724.jpg" width="300px"/></div>

## Expected behaviour

The app opens without showing any errors

## Possible Fix

Dismissing the dialog will hide it, but it will come back after reopening the app.

## Additional context

I have registered certifications in the app and rapid test profile. I keep the exposure notifications always on.

**Comment by vaubaehn** [comment]
Hi @maricn , could it be that your PCR test registered with CWA is now 21/22 days old?

**Comment by MikeMcC399** [comment]
@maricn 
This is actually the repository for the Corona-Warn-App and from the screenshots you are using CCTG,

**Comment by maricn** [comment]
@vaubaehn yes! that is exactly the case.. do you want me to keep it there for debugging purposes, or is it a known issue and i can proceed with removing the PCR test to circumvent the bug?

@MikeMcC399 yes, exactly..

**Comment by MikeMcC399** [comment]
@maricn 

Sorry for not being clearer. This is not the place to report issues with CCTG or to get help on the app. 
I believe that CCTG has an active issue tracker on https://codeberg.org/corona-contact-tracing-germany/cwa-android/issues which you should probably be using.

**Comment by vaubaehn** [comment]
@MikeMcC399 
For some issues it is useful to have a problem reported here, as CCTG is the fork of CWA and uses the _same_ backend infrastructure. This issue reported here would also occur in CWA, and there was already something similar...
Will dig for the original issue now...

@maricn Thanks for reporting - give me one momoent to respond to your question - need to look up something before.

**Comment by vaubaehn** [comment]
Hi @maricn , I found it out now: it's an old issue with CWA, which should now be fixed with v.2.16.x...
So if you have the chance to update to the latest CCTG version that is also >=2.16.x, then the error should disappear.
You may erase your test then and close the issue, as it has been solved recently.
Thanks for stepping by!

FYI: PR https://github.com/corona-warn-app/cwa-app-android/pull/4594

**Comment by dsarkar** [comment]
@vaubaehn Nice, thanks for assisting here!

**Comment by vaubaehn** [comment]
@dsarkar You're welcome.
What does the label "read-to-close" mean - will the issue close itself after everyone read it? 😉

**Comment by Ein-Tim** [comment]
There is a correct label: https://github.com/corona-warn-app/cwa-app-android/label%3Aready-to-close

Good night everyone!

**Comment by dsarkar** [comment]
@vaubaehn So, I will leave it to the author @maricn of this issue to smile (since his issue was fixed e.g. or many other reasons) and close this issue. I definitely had to smile!
