### ISSUE TITLE
It is suspected that the CWA is responsible for mobile phone crashes (Android 12, OneUI 4).

### ISSUE THREAD

**Issue by diibify** [corona-warn-app/cwa-app-android#4795]
## Technical details

- Device name: Samsung Galaxy A52 (SM-A525F/DS)
- Android version: 12 (One UI 4), security patch 1 January 2022
- App version: 2.17.2

## Describe the bug

After updating to Android 12, my phone crashes regularly (every few hours). As reported in many forums, the problems occur on many Samsung devices that have recently been updated to Android 12 (incl. OneUI 4). These restarts could usually be (reproducibly) prevented by deleting the CWA. 

## Additional context

There was speculation that the problem was with the Google Contact Tracking API. Unfortunately, I cannot provide any further information. 

---
Internal Tracking ID: [EXPOSUREAPP-11762](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11762)

**Comment by MikeMcC399** [comment]
@diibify

I'm sorry to hear that your phone is crashing. That must be really annoying.

I am running CWA Android 2.17.2 on a Samsung Galaxy A52 5G SM-A526B/DS and (thankfully) I am not seeing any crashes. I didn't see any with previous version of CWA either.

I have the security patch level 1 January 2022 installed.
One UI version: 4.0
Android version: 12

Could the Open Source Team let us know if crashes are showing up on the Google Play Store console for Android 12?

**Comment by Ein-Tim** [comment]
There is a FAQ entry reg. this: https://www.coronawarn.app/en/faq/#various_device_problems

It suggest to contact the device manufacturer.

**Comment by nitelow** [comment]
I'm running CWA on the same model as @MikeMcC399 with the same software versions. 
This device is a slight increment of the model @diibify uses.

I bought it a week ago and installed the Android 12 update before installing any apps (including CWA).
Maybe that's the difference?

**Comment by szerner** [comment]
I'm having this issue on my Samsung phone, too. Same device model and software config as the one of @diibify.

As long as I have the CWA installed, my phone first freezes, then suddenly restarts every few hours. If I uninstall the CWA, I have no crashes any more. This issue began after upgrading to Android 12 and Samsung OneUI 4.0. Uninstalling and reinstallation of the CWA didn't help, "wiping the cache partition" and "app repairing" in recovery mode either.

I've filed this issue to the Samung support, together with a system protocol for better analysis.

**Comment by dsarkar** [comment]
Hi @diibify and @szerner,

Thanks for reporting here.

Internal Tracking ID: [EXPOSUREAPP-11762](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11762)


Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
It's good that @szerner has reported the issue to Samsung.

Here is the Android FAQ:
[Fix an Android device that's restarting or crashing](https://support.google.com/android/answer/7664448?hl=env)
just for reference, although I don't really expect it will help in this case, but you never know ...!

**Comment by szerner** [comment]
> Is there any pattern about which specific Samsung models are affected?

@MikeMcC399 in the [EU Samsung community forum](https://eu.community.samsung.com/t5/galaxy-a-serie/bd-p/galaxy-a-de) there are multiple users of current Samsung Galaxy A-series devices (A52 4G/5G, A72), who are complaining about this sort of crashes (freezes, restarts). Some posts there also show an obvious relationship between the issue and the CWA installed on the problematic phones.

**Comment by Ein-Tim** [comment]
@diibify & @szerner 

Would you maybe give it a try and install another app using the ENF, e.g. Immuni (Italian app), to see if this also lets the device crash?

**Comment by domdus** [comment]
Can confirm freezes followed by crashes/soft-reboot on my A52 4G after Android 12 Update, I have CWA installed still.

Security patch level 1 January 2022
One UI version: 4.0
Android version: 12

People report uninstalling CWA fixed the issue for them.

[Post in EU Samsung community forum](https://eu.community.samsung.com/t5/galaxy-a-serie/samsung-galaxy-a52-nach-software-update-immer-neustart/m-p/4722462#M17955) 

[Post in Android-hilfe.de forum](https://www.android-hilfe.de/forum/samsung-galaxy-a52.3913/abstuerze-des-galaxy-a52-nach-dem-update-auf-android-12.996584.html)

**Comment by dsarkar** [comment]
@domdus Thanks for you report, will be forwarded to the internal ticket.

Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Hi @szerner, do you have any news regarding using other tracing apps? Thanks. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by szerner** [comment]
Hi @dsarkar, as mentioned 4 days ago I first uninstalled the CWA and then installed the Immuni app for Italy and assured, that the "Service" (COVID-19 Notification) is up and running.

Since then i had **no issues** with my phone, no freezing and no unwanted restarts. My Android didn't get any system updates during that time.

Unfortunately I didn't get any results from Samsung about this issue since, they only replied the analysis of my error report might take some time.

Now I go uninstalling Immuni again, install CWA back and drink a cup of coffee...

**Comment by szerner** [comment]
About 5 hours after the installation of the CWA, I had a sudden freeze and restart of the UI. But until now (16 hours later) this was the only one.

**Comment by dsarkar** [comment]
@szerner Thanks for your feedback! Will forward it to the internal ticket.

**Comment by szerner** [comment]
I just received a feedback from Samung: Please restet you Galaxy A52 to factory defaults. Which I won't do at the moment.

So in uninstalled the CWA for now in favor of the CovPass app. Sorry for the CWA-team that I couldn't be of a better help with this issue.

**Comment by dsarkar** [comment]
@szerner Thanks for your feedback and all the info provided. All very much appreciated. Please, should you have further new Information regarding this issue, let us know.

Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by ferox-81** [comment]
Had the same problem with my wifes and mine a52 too. Repeated sudden restarts of the phone.   After uninstalling the cwa and restarting the phone, the problem didn't occur again. Switched to CCTG and had no problems with restarts since.

**Comment by diibify** [comment]
Am I the only one affected who has lost the reboots at the moment? I kept installing the CWA and no updates came from Samsung, but I haven't had any reboots for a few days now. Is it just a coincidence?

**Comment by dsarkar** [comment]
@ferox-81 @diibify Thanks for reporting, forwarded to internal ticket.

**Comment by powerzone3000** [comment]
> Am I the only one affected who has lost the reboots at the moment? I kept installing the CWA and no updates came from Samsung, but I haven't had any reboots for a few days now. Is it just a coincidence?

I think I can confirm that.  I haven't had any crashes for at least two days.  Apparently without installinh any update from Samsung or CWA.  Maybe an update for the ENF via Google Play Services?

**Comment by dsarkar** [comment]
@domdus @szerner @ferox-81 Can you confirm that the issues disappeared? Thanks.

**Comment by szerner** [comment]
@dsarkar Yes, I've reinstalled the CWA on my phone about 5 days ago and didn't experience this issue again.

**Comment by MikeMcC399** [comment]
@diibify 
It sounds like the unexpected reboots are no longer happening. Perhaps this issue could be closed now?
There haven't been any new reports in the last two weeks it seems.

**Comment by diibify** [comment]
Sorry for the late reply. I was about to suggest closing the issue. I think the problem is fixed for everyone. Thank you for your efforts!

**Comment by dsarkar** [comment]
Dear @diibify,

Thanks for reporting and your feedback.

Best wishes, DS

---
Corona-Warn-App Open Source Team
