### ISSUE TITLE
Shared link from android app returns HTTP 504

### ISSUE THREAD

**Issue by ulrichstark** [corona-warn-app/cwa-app-android#480]
## Describe the bug

You are able to share, that you are using the android app with the share icon in the top right.
The URL that gets shared (`https://www.corona-warn-app.de`) is unavaible and returns HTTP 504 status code right now.

## Expected behaviour

Shared link should lead to website/google play page

## Steps to reproduce the issue

1. Click on Share-Icon in the top right
2. Use any app, that accepts the shared text
3. Try to open the shared URL

## Technical details

Tested on Android

## Possible Fix

https://github.com/corona-warn-app/cwa-app-android/blob/cacf64a4611c37bb062e7ee4d08822f9ba9d2662/Corona-Warn-App/src/main/res/values-de/strings.xml#L205

change `https://www.corona-warn-app.de` to `https://www.corona-warn.app` in this file and in respective strings.xml in values and values-en folder

**Comment by SebastianWolf-SAP** [comment]
The app has not yet been officially presented, it may take some time until the respective site are live and running... Thank you in advance for your patience!

Mit freundlichen Grüßen/Best regards,
SW
Corona Warn-App Open Source Team

**Comment by ulrichstark** [comment]
Many people are already downloading the app from the Play Store, since it is already launched there.
And some of them use the share-feature to attract more people.
But these people wont find the app, because the shared link is not working...

why not just use the https://corona-warn.app as shared URL?

**Comment by crstnbr** [comment]
+1 Have hit this as well when my brother tried to share the link with me. While I understand the "websites will come online" argument, this definitely doesn't help the spread of the app in the crucial early stage.
