### ISSUE TITLE
Latest test certificate not displayed 

### ISSUE THREAD

**Issue by Thomas1664** [corona-warn-app/cwa-app-android#4805]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation) I don't know because I only have an Android device
* [x] Bug is not already reported in another issue
 Related: #4804

## Technical details

- Device name: Galaxy A50
- Android version: 11
- App version: 2.17.2

## Describe the bug
I am vaccinated (3x) and have a negative test certificate. All 3 vaccination certificates are displayed and have exactly the same name and date of birth. The current and the previous one (Monday) test certificates are missing. But in the contact diary, the latest test certificate is displayed. After I registered my latest certificate, CWA reported that there is an existing valid test certificate, but let me finish the registration.
I selected "personalized test certificate for CWA".
When I try to scan the QC-code again, the app displays the following error "code invalid or already registered on this device". 
I only see 1 certificate in the overview.
Consequently, in the certificates page I only get the status 2G instead of 2G+

## Steps to reproduce the issue
Register 3 vaccinations and 1 negative test

## Expected behaviour
Having 2G+
See the latest test certificate

## Possible Workaround
Issue is gone after I restarted the device. Note that once I opened CWA after the restart, the phone hang for a few seconds.

**Comment by Ein-Tim** [comment]
Do you have a test result (shown in the contact journal and on the "Status" tab) or a test certificate (shown on the "Certificates" tab)?

**Comment by Thomas1664** [comment]
> Do you have a test result (shown in the contact journal and on the "Status" tab) or a test certificate (shown on the "Certificates" tab)?

Now - after restart - I have both. Before the restart I could only see the test result in the contact journal.

**Comment by Ein-Tim** [comment]
@Thomas1664 So there is also a certificate with a QR code shown on the "Certificates" tab? 

YES: If your test certificate and the vaccination certificate have the same date of birth and exact same name, they are grouped together and show 2G+

NO: 2G+ is only shown if a test **certificate** is stored in the app.

**Comment by Thomas1664** [comment]
No, but:
- On the Home page of the app I can see my current test result
- On the certificate page - where a previous (04.02.) test certificate and my vaccination certificates are shown - I can't find the new test certificate. Consequently, my status is 2G because this page thinks that I don't have a valid test certificate (as described in FAQ). Test and vaccination certificates are grouped together.
- The contact diary shows all test results: The one from today, the result from Monday, that I attempted to "overwrite" by adding todays result, and all previous tests

**Comment by Ein-Tim** [comment]
@Thomas1664 

Does the testing center you went to offer the creation of EU digital COVID test certificates? Not all test stations offer this service (sadly).

**Comment by Thomas1664** [comment]
> @Thomas1664
> 
> Does the testing center you went to offer the creation of EU digital COVID test certificates? Not all test stations offer this service (sadly).

Yes

**Comment by Thomas1664** [comment]
I have more information:
The last test certificate that I could register was at 04.02. before I updated to CWA 2.17.2. Since then I was at multiple test sites but I was only able to get a test result although I requested each time a test certificate. Note that I have multiple surnames. Before the update I had no problem with my second surname.

**Comment by Ein-Tim** [comment]
@Thomas1664 Were the test sites able to issue test certificates? It's not enough for you to request a test certificate in the app, the testing sites need to support this.

**Comment by Thomas1664** [comment]
I think this was the test site's problem as other sites are working
