### ISSUE TITLE
Typo: "ihrer" should be "Ihrer"

### ISSUE THREAD

**Issue by w-flo** [corona-warn-app/cwa-app-android#481]
https://github.com/corona-warn-app/cwa-app-android/blob/c3416440e644a918f4001489de85f203c7681099/Corona-Warn-App/src/main/res/values-de/strings.xml#L341

"erfahren Sie, ob in den letzten 14 Tagen Corona-positiv getestete Personen in **ihrer** Nähe waren"

This is basically the "welcome" display, so it should be fixed soon because everybody will see it right after installing the app. Most probably won't notice the typo though.

**Comment by tomjschwanke** [comment]
Changes to text / translations (strings.xml) go into #332

**Comment by marcmuschko** [comment]
@w-flo 
Thanks for pointing it out! As it is already part of #332, I will close this issue to avoid duplicates.
