### ISSUE TITLE
Fake green pass that are considered valid

### ISSUE THREAD

**Issue by ale5000-git** [corona-warn-app/cwa-app-android#4821]
There are some fake green pass that are considered valid.
The Italian app has a blacklist that download every day.

Example of fake green pass:
![Adolf Hitler 1](https://user-images.githubusercontent.com/15793015/153474530-61cc3ad8-0881-41ce-b4c5-c9a033331913.jpg)
![Adolf Hitler 2](https://user-images.githubusercontent.com/15793015/153474574-98e31eed-40f6-4de3-a1f8-d115f88b0d54.png)
![Adolf Hitler 3](https://user-images.githubusercontent.com/15793015/153474591-0772b75b-e498-4947-8d0a-72d5a1a83213.jpg)
![Mickey Mouse](https://user-images.githubusercontent.com/15793015/153474605-06c6df9c-61b1-4a76-9e8d-f92dcd0ca85a.png)
![Rokotepassieu](https://user-images.githubusercontent.com/15793015/153474618-ccd79600-e2bf-46ef-9eff-8ce6ed337de8.png)
![Spongebob](https://user-images.githubusercontent.com/15793015/153474625-4c1adabd-53d1-4276-b245-209e65e0b505.png)

**Comment by thomasaugsten** [comment]
The CWA is waiting for the EU revocation service
https://github.com/eu-digital-green-certificates/dgca-revocation-distribution-service
A reliable fake check can only provided by the CovPassCheck App because the revocation in the wallet apps can be disabled. The specific issue for the Check App are already mentioned

**Comment by thomasaugsten** [comment]
Yes the service is still in progress

**Comment by Ein-Tim** [comment]
Can this issue be closed?

**Comment by Ein-Tim** [comment]
@dsarkar Please close this issue. The author does not seem to respond anymore.
