### ISSUE TITLE
"0 keys" loaded in Google Logs

### ISSUE THREAD

**Issue by vanMacG** [corona-warn-app/cwa-app-android#4834]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Xiaomi Mi A3
- Android version: 11
- App version: 2.17.2
- Google Play Service: v1.8 (214815000)

## Describe the bug

First of all, the error seems to be mentioned in the [FAQ](https://www.coronawarn.app/de/faq/?search=schl%C3%BCssel+0#keys0) and there was an issue: #744 . But the Google Play version is much newer than in the FAQ, and the issue is closed.

The Google Log says that 0 keys are downloaded, and this seems reasonable: The affected device is from my dad, and my mother reported a positiv test lately. The devices are nearby realy often and CWA showed no risk at dad's phone at all.

## Steps to reproduce the issue

Go to Settings - Google - Covid-Tracing - 3-dot-menue - click on any date/time.
The dates and times seemed reasonable (every 4 h in Wifi, 12h on mobile data)

![IMG_20220209_214108_](https://user-images.githubusercontent.com/8269814/153922970-62ca6d52-09ba-4ae9-a4b2-07bceb7b4718.jpg)

![IMG_20220209_214353_](https://user-images.githubusercontent.com/8269814/153922986-3faa0322-b33d-4920-86bd-c67452455c55.jpg)

## Additional context

- In the setting, all options are enabled ("Risiko-Ermittlung", "Mitteilungen" & "Priorisierte Hintergrundaktivität")
- Internal memory: 32,89 GB of 128 GB used

**Comment by vanMacG** [comment]
I was able to capture a debug log today.
Is there a way to share it with the devs without uploading it to this public issue?

**Comment by vanMacG** [comment]
Ok, 3 weeks now without any response... 😞
Does anyone from the devs want to look into this? Otherwise I would try to reinstall the app or factory reset the phone.

**Comment by MikeMcC399** [comment]
@vanMacG 

You might like to refer to https://github.com/corona-warn-app/cwa-app-android/issues/1752#issuecomment-904754931 for a list of situations which can cause 0 "Anzahl der Schlüssel" / "Number of keys".

To share a debug log with the Open Source Team you just need to upload the Error Report and share the ID here. That is only helpful though if there is somebody on the Open Source Team available to look at the log. The community (of which I am part) has no access to uploaded Error Reports. You can find more details in the FAQ [Wie erstelle ich einen Fehlerbericht?](https://www.coronawarn.app/de/faq/#error_log).

If you want to look at the log yourself, you could search for `ExposureNotification`.

**Comment by vanMacG** [comment]
@MikeMcC399 
Thank you for your answer. None of the points in your referenced issue apply to this device. (The device of my mother is exactly the same and works, reboots were performed, OS is stock ROM)

Here are the lines with `ExposureNotification`, maybe this helps:
```
2022-02-16T19:00:57.121Z V/SignatureValidation: # de.rki.coronawarnapp.server.protocols.external.exposurenotification.TemporaryExposureKeySignatureList$TEKSignature@4ca891b9
2022-02-16T19:00:57.126Z V/SignatureValidation: 1 valid signatures found
2022-02-16T19:00:57.127Z D/SignatureValidation: Valid signatures found.
2022-02-16T19:01:02.381Z V/SignatureValidation: # de.rki.coronawarnapp.server.protocols.external.exposurenotification.TemporaryExposureKeySignatureList$TEKSignature@3e5ec071
2022-02-16T19:01:02.382Z V/SignatureValidation: 1 valid signatures found
2022-02-16T19:01:02.451Z V/SignatureValidation: # de.rki.coronawarnapp.server.protocols.external.exposurenotification.TemporaryExposureKeySignatureList$TEKSignature@b028c20a
2022-02-16T19:01:02.452Z V/SignatureValidation: 1 valid signatures found
2022-02-16T19:01:02.453Z D/SignatureValidation: Valid signatures found.
2022-02-16T19:01:10.226Z D/ExposureStateUpdateReceiver: onReceive(context=android.app.ReceiverRestrictedContext@502076f, intent=Intent { act=com.google.android.gms.exposurenotification.ACTION_EXPOSURE_NOT_FOUND flg=0x10 pkg=de.rki.coronawarnapp cmp=de.rki.coronawarnapp/.receiver.ExposureStateUpdateReceiver (has extras) })
2022-02-16T19:01:10.226Z V/ExposureStateUpdateReceiver: Looking up action: com.google.android.gms.exposurenotification.ACTION_EXPOSURE_NOT_FOUND
2022-02-16T19:01:10.227Z W/ExposureStateUpdateReceiver: Received unknown token from ENF: TYZWQ32170AXEUVCDW7A
2022-02-16T19:01:10.227Z I/DefaultExposureDetectionTracker: finishExposureDetection(token=null, result=NO_MATCHES)
2022-02-16T19:01:10.228Z I/ExposureStateUpdateReceiver: Finished processing broadcast.
```

**Comment by MikeMcC399** [comment]
@vanMacG 
> The device of my mother is exactly the same and works, reboots were performed, OS is stock ROM

You might want to check if there are any firmware updates which have not yet been installed on your dad's device. Apart from if there is a hardware issue on your dad's device, it's hard to know why one should be working and the other not working, given that they are supposed to be identical.

**Comment by vanMacG** [comment]
Yeah, that's why I created this issue and captured logs...
I will check for firmware updates, otherwise I have to reinstall the app or factory reset the phone, as said.
Thanks for your help!

**Comment by vaubaehn** [comment]
Anyway, a dev should look into this:
> 2022-02-16T19:01:10.227Z W/ExposureStateUpdateReceiver: Received unknown token from ENF: TYZWQ32170AXEUVCDW7A

I didn't check my old logs whether that is a "normal" repsonse from the app, but CWA should be able to recognize the token.
Actually, no token at all should be provided to ENF anymore, but probably for compatibility reasons this is still the case (migrating to non-token provision could be tricky).
But when CWA does not recognize the token sent back from ENF, maybe something was going wrong when intializing and setting up token for `provideDiagnosisKeys()` ?

FYI: @mtwalli

**Comment by vaubaehn** [comment]
the token
> TYZWQ32170AXEUVCDW7A

is then constant value of TOKEN_A: https://developers.google.com/android/reference/com/google/android/gms/nearby/exposurenotification/ExposureNotificationClient?hl=de#public-static-final-string-token_a

So it's to use Exposure Window mode with the legacy method: https://developers.google.com/android/exposure-notifications/exposure-notifications-api#modes
Then this token should be the same across all CWA users, and the log line is probably misleading.

**Comment by MikeMcC399** [comment]
I get the log file line
`2022-03-10T17:23:45.621Z W/ExposureStateUpdateReceiver: Received unknown token from ENF: TYZWQ32170AXEUVCDW7A`
on a working device, so it is probably irrelevant for this issue.

**Comment by vaubaehn** [comment]
@MikeMcC399 
> so it is probably irrelevant for this issue.

Think so, too, now

**Comment by vanMacG** [comment]
Either an update of CWA (2.17.2 --> 2.18.1) or Google ENF (214815000 --> 220618000) has fixed the problem. At least the value of keys is >0 now.

![IMG_20220319_104826_](https://user-images.githubusercontent.com/8269814/159353747-7873f367-facf-4822-b5d7-777b072a8930.jpg)
![IMG_20220319_104748_](https://user-images.githubusercontent.com/8269814/159353768-4fa65d68-0ec9-4c7d-ba3a-f8f6464d8124.jpg)

**Comment by MikeMcC399** [comment]
@vanMacG 

You say that your dad's device is showing non-zero keys (Anzahl der Schlüssel) now. Can we regard this issue as resolved in that case?
