### ISSUE TITLE
Doesn't work without Google Play Service

### ISSUE THREAD

**Issue by ikreb7** [corona-warn-app/cwa-app-android#484]
Hello, I get the error: 

    URSACHE:3
    Etwas ist schief gelaufen
    Fehler bei Kommunikation mit Google API(17).

I get this error message because I haven't installed the Google Play Service. It would be nice if you could offer also an alternative solution without Google Play Service.

I use GrapheneOS together with Aurora App Store.

**Comment by tomjschwanke** [comment]
This App only works with the API provided by Google Play Services. Without it, the app won't work.

A replacement is unlikely, as _most_ users have Google Play Services available.

Should there be a 3rd party API that's compatible with the implementation from Google and Apple, I'm sure this app could be changed to support it too.

For now, it's out of scope though.

**Comment by PetersOtto** [comment]
I have the same problem with LineageOS and the Aurora App Store.

**Comment by SebastianWolf-SAP** [comment]
Please see the pinned issue #477 

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by ikreb7** [comment]
I use the Aurora Play Store. So this is not a problem with a missing F-Droid or APK-Release.

I think this is a very important issue. Maybe all new Huawei smartphones will have this problem soon too.

**Comment by modzilla99** [comment]
Even though I'm not using a custom ROM or anything, I still get this message! Google Play Services are installed and up to date!

**Comment by modzilla99** [comment]
Btw I'm using a OnePlus 7 Pro

![Screenshot_20200616-092335__01](https://user-images.githubusercontent.com/32171364/84744215-3b78ca00-afb3-11ea-97fc-a593bf678d22.jpg)
