### ISSUE TITLE
Get FC

### ISSUE THREAD

**Issue by ruben2000de** [corona-warn-app/cwa-app-android#486]
Getting constant FC after activation of the app.
Android crash log: https://del.dog/lomamyrell
Running Android 10, custom rom with root possibility.
Also using a pebble time steel and a jabra headset as usb devices.

**Comment by tomjschwanke** [comment]
`decryption failed` --> this looks like it failed to read from the encrypted shared preferences.

Did you try to clear the app's data? Via Settings, Apps, Corona-Warn, Storage, Clear App-data.
Or just re-install it.

Then try setting it up again.

**Comment by tomjschwanke** [comment]
You mentioned you're running a custom rom, do you have Google Play Services installed? Without those, the app won't work (that'd give you an error message though instead of FC'ing)

**Comment by ruben2000de** [comment]
Hello Tom,
clearing app-data already did it.
Thank you. Case closed.
