### ISSUE TITLE
Cannot enable exposure logging on Redmi 4X

### ISSUE THREAD

**Issue by CosmicGans** [corona-warn-app/cwa-app-android#487]
## Describe the bug
After installing the app and getting to the "Enable Exposure Logging" screen, clicking on the blue button for "Activate Exposure Logging" does nothing (neither moving ahead to the next screen, nor produce any message). Moving to the next screen is only possible with clicking on the refuse option. 

In the Main view of the app at the top, the app tells me that "Exposure Logging Stopped". Clicking on this, I get to the "Exposure Logging" screen, the one that says "This is how exposure logging works". It has a switch for exposure logging, which I can click on and see the switch turn from grey to blue. However, it still tells me that Exposure Logging is stopped.  
I am using the App in English, if that changes anything.

## Expected behaviour

Exposure Logging should work.

## Steps to reproduce the issue

1)Download the App on the Play Store on an Redmi 4X. 
2)Open it and go the second screen, the "Enable Exposure Logging" Screen. 
3) Click on "Activate Exposure Logging"

## Technical details

Xiaomi Redmi 4X 
MIUI Version:11.0.2 
Android Version: 7.1.2 N2G47H

**Comment by otaviopachecol** [comment]
I'm using an iPhone 11 and can't do it either, same problem, i tick the accept button but it doesn't work. My phone is managed by my company, not sure if that affects aanything

**Comment by jakobmoellersap** [comment]
Hey there, thanks for your issue @CosmicGans !

Do you have the Google Play Store installed? If so, would you be able to share the version with us?

**Comment by CosmicGans** [comment]
Hi Jakob, thank you for your reply! 
Yes, I have the Play Store installed, the version is 20.4.19-all [0][PR] 314396108 
When I click on the version, I get a pop up saying that the version is up-to date.

**Comment by jakobmoellersap** [comment]
can you confirm the issue still persists? Does reinstalling solve the problem for you? There are still certain edge cases in which a GMS Update might cause this behaviour.

**Comment by otaviopachecol** [comment]
reinstalling worked

**Comment by CosmicGans** [comment]
After updating the Google Play Services (not the App Store) the app works. Thanks for looking into it!
