### ISSUE TITLE
Compatibility issues with older phones

### ISSUE THREAD

**Issue by PXAV** [corona-warn-app/cwa-app-android#489]
## The problem
I tried downloading the App from Google Play Store, but it said my phone is not compatible with the required version (I am using Android `5.1`). 

## Your Question
Why is the minimum version of the app set so "high"? Android 5, for example, is actually still a very common version, which is supported by most apps and App SDKs like Flutter. I mean my phone is just 3 years old.

I think, when the App should be used by the majority of people in Germany and probably other countries, compatibility should have the highest priority - after privacy of course. There won't be any success or effect by this App when such high requirements are set to use it.

So is it possible to change the SDK version in this stage of development or does the App rely on features only available in newer versions?

**Comment by SebastianWolf-SAP** [comment]
No, this is unfortunately not possible. The minimum version set by Google is Android 6 - and hardware-wise of course Bluetooth Low Energy must be supported. See also https://github.com/corona-warn-app/cwa-app-android/issues/165

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by JamesR404v2** [comment]
You can also try to install the app via your phone, you may see a different error message there such this one; https://github.com/corona-warn-app/cwa-app-android/issues/478
