### ISSUE TITLE
No Exposure Overview with positive Rapid Test & missing test details

### ISSUE THREAD

**Issue by swekkx** [corona-warn-app/cwa-app-android#4905]
## Your Question
Hi all,

I got a positive Rapid test today and added it to the app. I've never had a positive test, therefore I assumed I would still be able to see the exposure overview. This would be helpful in gathering information on the source of the infection and warn others.

Why is the exposure overview hidden?
![Screenshot_20220304-174735_Corona-Warn](https://user-images.githubusercontent.com/96697098/156810054-0869b1f9-ca06-4ce3-87d0-60a6b00dd191.jpg)

The only way would be deleting the test.

Furthermore I cannot see any details of the test results like (my) name, testing center name or test manufacturer. I can see these details in the app when I was tested negative. I gave full consent to personalized transmission. 

Is this intended?

If you need more information, please let me know.

Smartphone Samsung S21
Android Version 12
CWA Version 2.18.1
Thanks.

**Comment by Ein-Tim** [comment]
Just to quickly answer your question:

Yes, the behavior you observe, as well as no name on the test result & no risk-card is intended.

**Comment by dsarkar** [comment]
@swekkx Thanks for reporting, this behaviour is intended. You can still see in the journal tab, when the date of a high risk encounter, should you have had one.


Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by mtwalli** [comment]
@swekkx  this is coming in the next release `2.20.x` See https://github.com/corona-warn-app/cwa-app-android/pull/4893
