### ISSUE TITLE
Wrong name and very private information of another user in the app instead of some information

### ISSUE THREAD

**Issue by luisoos** [corona-warn-app/cwa-app-android#4907]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation) → Only saw this in the Android-App
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Redmi Note 10 5G
- Android version: 12.5.1.0
- App version: 2.18.1

## Describe the bug

As you can see in the screenshots, the wrong name and birthday (maybe also the QR-Code) are shown in the app. It seems like this is data if another person. A friend of mine could approve that he also already saw something like this. 

## Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/81855420/156986322-f3231df3-a701-460f-8b62-bf6de160c1c5.jpeg)
![image](https://user-images.githubusercontent.com/81855420/157012852-3c669692-871a-487c-a062-a0b94ba2c7a9.jpeg)

1. Go to 'Certificate-Tab'
2. See error
3. Click on the QR-Code
4. Scroll down to the detailed informations of the user
5. See error

## Expected behaviour

Possible bug like described before. 

## Additional things

This is a very important bug. I could not find any other issues reporting this problem. If there is one, I apologise.

**Comment by thomasaugsten** [comment]
Please check with the owner of the phone when he scan vaccination certificate and check with data on the paper.
Please contact the creator of the vaccination certification paper and inform him about the issue

**Comment by luisoos** [comment]
I think this is a server issue.

**Comment by Ein-Tim** [comment]
Did you use the CWA to validate certificates from others?

**Comment by thomasaugsten** [comment]
@luisoos There is no server communication while scanning and saving certificates

**Comment by MikeMcC399** [comment]
@luisoos 

You should delete the unwanted certificate from your device. See https://www.coronawarn.app/de/faq/#eu_dcc_remove for instructions.

Possibly you accidentally scanned a certificate of another person whilst you were waiting in a queue, like to enter a restaurant, event, teaching facility, etc.? The scanner is now very fast! You only need to accidentally touch the scan button on the CWA screen and if the phone's camera sees a nearby QR code it will scan it.

**Comment by vaubaehn** [comment]
@luisoos 
Could it be that you accidentally scanned the QR code from an image source on a web page in internet or from a newspaper? The owner seems to be a journalist.

@thomasaugsten @dsarkar 
Could you please delete the second screenshot from OP, this still contains a clear name.
Thanks.

**Comment by luisoos** [comment]
The owner is no journalist or some.

**Comment by luisoos** [comment]
> Did you use the CWA to validate certificates from others?

No

**Comment by mtwalli** [comment]
@luisoos  do you still have the paper or the QrCode that you scanned in CWA ? if so , could you please scan it with another App such as `CovPass` and let us know if you see the "right" name of yours? 

Note: We `don't` `change`, `alter`, `randomise` names from the certificates , we `JUST` display what is encoded in the QrCode

**Comment by luisoos** [comment]
> @luisoos  do you still have the paper or the QrCode that you scanned in CWA ? if so , could you please scan it with another App such as `CovPass` and let us know if you see the "right" name of yours? 
> 
> 
> 
> Note: We `don't` `change`, `alter`, `randomise` names from the certificates , we `JUST` display what is encoded in the QrCode 
> 
> 

It works in CovPass. 
Moreover I know that you don't change that.

**Comment by luisoos** [comment]
> > It works in CovPass.
> 
> 
> 
> You mean when you scan the QR code from the certificate of the person you posted the screenshot above CovPass shows your name? 

Yes, in the CovPass App is the real name. The same certificate was scanned in Corona-Warn, where this wrong name popped up...

**Comment by thomasaugsten** [comment]
@luisoos This is technical not possible. Can you please remove the certificates from the apps and rescan the certificate

**Comment by MikeMcC399** [comment]
@luisoos 
Have you now been able to delete the certificate of Claudia I***-U**** from the Corona-Warn-App and successfully scanned in your own certificate into Corona-Warn-App?
