### ISSUE TITLE
Stats for Nerds

### ISSUE THREAD

**Issue by nohn** [corona-warn-app/cwa-app-android#492]
## Feature description

We'd like to see stats for nerds. How many tokens have been received? How many devices are nearby etc.?

## Problem and motivation

Feed the nerds.

## Is this something you're interested in working on

Yes

**Comment by kbobrowski** [comment]
Information about number of tokens received / how many devices nearby won't be possible to get in CWA since this is handled by Play Services layer, but you can write another Android app which displays this information.

**Comment by corneliusroemer** [comment]
What should be possible though is: How many positive test reports and through what channels.

This may be possible to glean from the positiven key report. broadcasts

**Comment by nohn** [comment]
> What should be possible though is: How many positive test reports and through what channels.
> 
> This may be possible to glean from the positiven key report. broadcasts

OK. But this would be something better suited for corona-warn-app/cwa-website then, I guess?

**Comment by nohn** [comment]
> Information about number of tokens received / how many devices nearby won't be possible to get in CWA since this is handled by Play Services layer, but you can write another Android app which displays this information.

If it is not possible for CWA, how is it possible for another Android app?

**Comment by SebastianWolf-SAP** [comment]
Previous comments already mentioned that - this is neither supported by the API nor on list of planned features.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by nohn** [comment]
Not supported by API? OK. But why ask for feature requests if they are closed because they are not on the list of planned features? 

Nevermind.

**Comment by s-martin** [comment]
> Not supported by API? OK. But why ask for feature requests if they are closed because they are not on the list of planned features?
> 
> Nevermind.

The Exposure Notification API is provided by Apple/Google and therefore feature requests for that API cannot be solved here.
