### ISSUE TITLE
GPS seems required for some versions of Android

### ISSUE THREAD

**Issue by SeJV** [corona-warn-app/cwa-app-android#493]
Even though the missing need for location data should be a big feature, on some Devices it is required to activate GPS in order the app to work. 

Tested on:
- Android 7.1.1, Sony Xperia Z5 compact
- Android 8.0.0, Samsung A5 (2017)
- Android 9.x.x, Galaxy A7 (2018)

**Comment by SebastianWolf-SAP** [comment]
Please see #262. 

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by chrjsorg** [comment]
Unfortunately BLE needs the tracking services. There are already some issues concerning the lack of communication of this fact. So far the problem has unfortunately not been addressed within the app.

See https://github.com/corona-warn-app/cwa-app-android/issues/262
