### ISSUE TITLE
App not visible in App list of all luncher

### ISSUE THREAD

**Issue by servicemensch** [corona-warn-app/cwa-app-android#494]
App is not shown in every launcher app list

e.G. in "Launcher 10" the app is not shonw in the "all apps list". After switching to default launcher app is shown.

## Technical details testdevice
Device: Samsung  SM-G960F (Galaxy S9)
OS: Android 10 - security patch level May 2020
Launcher:
 - not Working: "Launcher 10" - Version 2.6.6 - com.nfwebdev.launcher
 - Working: "One UI Startscreen" - Version 11.0.72.31 - com.sec.android.app.launcher

**Comment by tomjschwanke** [comment]
I just tried it and the app shows up in "All Apps" for me

**Comment by servicemensch** [comment]
Device reboot fixed the issue.
