### ISSUE TITLE
Difficulty dismissing UQS scanner pop-up

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#4940]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Google Pixel 3a emulator
- Android version: 12
- App version: 2.19.0 (also pre-[release/2.20.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.20.x))

## Describe the bug

The Universal QR code Scanner (UQS) button displays a pop-up after app installation to inform new users about its capabilities. Other pop-ups displayed during on-boarding prevent dismissing the UQS pop-up until they have been dismissed causing a sub-optimal user experience.

## Steps to reproduce the issue

Set font size to "Small"

1. Clean install of Corona-Warn-App
2. Tap "LET'S GET STARTED"
3. Tap "NEXT"
4. Tap "DO NOT ACTIVATE" and confirm
5. Tap "NEXT", tap "NEXT"
6. Tap "DO NOT SHARE"
7. Tap on X of QR Code Scanner pop-up and note that nothing happens

![QR code scanner pop-up](https://user-images.githubusercontent.com/66998419/158596693-5dfadbad-fff8-4d33-bc77-9fc1be168fd3.jpg)

9. Dismiss other pop-ups (OK), (DO NOT ALLOW) & (OK)
10. Tap again on X of QR Code Scanner pop-up and note that this time the pop-up is dismissed

## Expected behavior

If the QR Code Scanner pop-up is shown with an X to dismiss it, then it should always be possible to dismiss the pop-up by tapping on the X.

## Possible Fix

Remove the pop-up from being displayed. Users no longer need to be specially informed about this function which was introduced several versions ago.

## Additional context

The Universal QR code Scanner (UQS) was introduced in October 2021 with CWA version 2.12. See blog post [Corona-Warn-App version 2.12 enables central access to QR code scanner and expands statistics area](https://www.coronawarn.app/en/blog/2021-10-19-cwa-version-2-12/). This is now 5 months ago.

- Issue https://github.com/corona-warn-app/cwa-app-android/issues/4400 also concerns a problem with the UQS pop-up which would be solved by removing it.

---
Internal Tracking ID: [EXPOSUREAPP-12295](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12295)

**Comment by larswmh** [comment]
Thanks for your report @MikeMcC399. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-12295](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12295)

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@dsarkar 

- Thank you for the cross-reference to PR https://github.com/corona-warn-app/cwa-app-android/pull/5366!

This PR does not resolve the issue. I will follow up in the PR itself.

**Comment by MikeMcC399** [comment]
@dsarkar 

- PR #5366 has been re-worked and merged into [release/2.26.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.26.x)
- The situations in which the UQS tooltip is shown have been very much reduced (see https://github.com/corona-warn-app/cwa-app-android/pull/5366#issuecomment-1191344207). This means that the steps to reproduce which described the tooltip appearing after a clean install of the app no longer apply.
- I consider this issue as planned to be fixed with the release of 2.26. There should then be no interference between the onboarding pop ups and the UQS tooltip. 👍🏻

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for your feedback!
