### ISSUE TITLE
App not working on Honor Device (Honor View 20) WITH latest Google Play-Dienste

### ISSUE THREAD

**Issue by heinosahling** [corona-warn-app/cwa-app-android#495]
Start the app, "Los geht's" --> "Weiter".
Message "Google Play-Dienste aktualisieren" appears.
If I activite this, Google Play does not give me the chance to update.
This is because the latest version is already installed (20.18.17).

Sometimes the message does not appear (tried to wipe cache (this app, Google Play-Dienste and Play Store) and "Risiko-Ermittlung aktivieren" does not show any reaction (Case 2).

Sometimes "Ursache 9002 Etwas ist schief gelaufen." appears (Case 3)

Cannot reproduce when one of these 3 cases appears.

Please inform me how I can help with this issue.

**Comment by heinosahling** [comment]
Same stacktrace as in https://github.com/corona-warn-app/cwa-app-android/issues/499
(I was not able to take a screenshot)

**Comment by MichaeIDietrich** [comment]
I got the same device and the identical error.

**Comment by MichaeIDietrich** [comment]
I followed the comments from #499 and tried several steps to fix the issue.

The steps that seemed to make it work for me were:
1. Corona-warn-app is installed
2. Close all open apps
3. Disable wifi and bluetooth
4. Go to settings > apps
5. Clear both, data and cache, for both, Google Play Store and Google Play Services
6. Enable wifi and bluetooth again
7. Open Google Play Store and check for updates (probably nothing new to see here)
8. Start the Corona-warn-app

Now I was able to finish the setup. Maybe the essential point was disabling/enabling the hardware.

**Comment by heinosahling** [comment]
> I followed the comments from #499 and tried several steps to fix the issue.
> 
> The steps that seemed to make it work for me were:
> 
> 1. Corona-warn-app is installed
> 2. Close all open apps
> 3. Disable wifi and bluetooth
> 4. Go to settings > apps
> 5. Clear both, data and cache, for both, Google Play Store and Google Play Services
> 6. Enable wifi and bluetooth again
> 7. Open Google Play Store and check for updates (probably nothing new to see here)
> 8. Start the Corona-warn-app
> 
> Now I was able to finish the setup. Maybe the essential point was disabling/enabling the hardware.

Yes! That helped for me too! Thank you for that!
So where is the bug?
App? Or the devices software?!?

Heino Sahling

**Comment by jakobmoellersap** [comment]
Since the issue seems to be resolved now, I will close here. For more reference towards Google API Issues please look into #499

**Comment by corneliusroemer** [comment]
@jakobmoellersap Not sure this should simply be closed. That a workaround works doesn't mean it's done with - others less tech savvy may not know about the workaround. The workaround should at least be added to a list of workarounds, maybe in the FAQs.
#IssueClosurePolicy
