### ISSUE TITLE
Wrong warning about disabled bluetooth

### ISSUE THREAD

**Issue by Bastian** [corona-warn-app/cwa-app-android#496]
## Describe the bug

The app tells me that bluetooth is disabled even though it is not.

## Expected behaviour

The app should not show me a wrong warning.

## Steps to reproduce the issue

I don't know.

## Technical details

- Tested on a OnePlus 6T. See screenshot for more details.

![Screenshot_20200616-100233](https://user-images.githubusercontent.com/5033001/84748173-906b0f00-afb8-11ea-8e77-fc94038af6eb.jpg)

## Additional context

![20200616085938__MG_0005](https://user-images.githubusercontent.com/5033001/84748206-9a8d0d80-afb8-11ea-81b5-9bacbe5f9ef4.JPG)
![20200616085959__MG_0006](https://user-images.githubusercontent.com/5033001/84748228-a11b8500-afb8-11ea-8288-18c503c9ebde.JPG)
![Screenshot_20200616-095605](https://user-images.githubusercontent.com/5033001/84748306-bb556300-afb8-11ea-8bf6-b172a41c7cdc.jpg)

At first it displayed it correctly. After opening the app again later, the warning appeared. Disabling and re-enabeling Bluetooth fixed the issue. I'll report if it re-appeares after a while.

---
Internal Tracking ID: EXPOSUREAPP-1965

**Comment by tomjschwanke** [comment]
I had that too, disabling and re-enabling tracing worked for me.

**Comment by FEWI999** [comment]
if the Trick from @tomjschwanke doesn't work you just have to deinstall the app and restart your phone. I had this Problem too.

**Comment by Bastian** [comment]
While there may be many tricks to circumvent the issue, this shouldn't happen in the first place and could cause confusion for less tech-savvy users. In the worst case, the user might not even notice the issue and thinks that the app is collecting data even though it isn't.

**Comment by corneliusroemer** [comment]
Same issue here. OnePlus 6T A6013, but Oxygen OS 10.3.4

Reproducible. So this is a big thing that needs to get investigated asap!

**Comment by MaikWagner** [comment]
Same here! Perhaps a OnePlus related bug?!

![Screenshot_20200617-093405](https://user-images.githubusercontent.com/7701966/84869356-36348180-b07e-11ea-93df-77869972898f.jpg)

**Comment by GPclips** [comment]
Hello @Bastian and community,

to follow up, I like to ask if the error still occurs?

Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by Bastian** [comment]
No, the error did not occur again. 
It probably only happens on the first install.

**Comment by svengabr** [comment]
I assume this issue got fixed in a previous update. I will close this issue, for now, to keep the board clean.

Best regards,
SG

Corona-Warn-App Open Source Team
