### ISSUE TITLE
Spracheinstellung

### ISSUE THREAD

**Issue by gitterman** [corona-warn-app/cwa-app-android#4980]
Warum kann man die Sprache in der Corona Warn App für Android nicht unabhängig von der Betriebssystemsprache auf Deutsch einstellen?
Mein Smartphone ist berufsbedingt Englisch ich möchte die Warn App aber auf Deutsch.
Andere Apps wie z.B. myHomeFIT haben so eine Einstellmöglichkeit.

**Comment by MikeMcC399** [comment]
@gitterman 
- Es gibt bereits ein Enhancement Request zu diesem Thema unter https://github.com/corona-warn-app/cwa-app-android/issues/3489.

**Comment by MikeMcC399** [comment]
Ich kann nicht für die Entwickler sprechen, aber folgende Punkte sind mir eingefallen:

- Die Android Corona-Warn-App (CWA) ist eng mit der Google Exposure Notifications System (ENS) verknüpft. Manche Meldungen, die scheinbar von der CWA kommen, stammen tatsächlich vom ENS. Wenn CWA eine andere Sprache benutzen würde, als im Systemlocale eingestellt, würde der Benutzer u.U. Meldungen zu Exposures in zwei verschiedene Sprachen sehen, einmal von CWA und einmal von ENS. Das wäre verwirrend und weniger optimal.
- Das Betriebssystem Android ist nicht dafür ausgelegt, dass Anwendungen selber bestimmen, in welcher der programmierten Sprache sie erscheinen. Es wird davon ausgegangen, dass das Systemlocale ausschlaggebend ist. Siehe https://developer.android.com/training/basics/supporting-devices/languages.
- Wenn die App auf die Sprachumschaltung durch Android verzichten würde, würde ein signifikater Mehraufwand entstehen. Ich kann mir vorstellen, dass manch der eingesetzten third-party Module nicht mehr geeignet wären.

**Comment by gitterman** [comment]
Hmm.
Die Verwendung von Third Party Modulen ist vielleicht eine Erklärung.
Das würde auch dazu passen, dass Ein-Mann Entwickler eher verschiedene Sprachen unterstützen als große Gruppen, da erstere evtl. mehr selbst programmieren.
In dem angegebenen Developer Link steht aber ja auch, dass Anwendungen verschiedene Sprachen unterstützen können.
Was macht z. B. ein Franzose in Deutschland. Der wird doch wohl sein Smartphone auf Französisch lassen. Bekommt der dann die Warn App auf Englisch? Wenn ja, dann kann man offenbar doch auch eine andere Sprache als das Betriebssystem und dann sollte auch Deutsch möglich sein.

**Comment by MikeMcC399** [comment]
@gitterman 

CWA Android unterstützt:
- Deutsch
- Englisch
- Türkisch (ab Version 1.1.1)
- Bulgarisch (ab Version 1.2.0)
- Polnisch (ab Version 1.2.0)
- Rumänisch (ab Version 1.2.0)

wie in der FAQ https://www.coronawarn.app/de/faq/#available_languages beschrieben. Die defaultmäßige Sprache ist Englisch. 

In dem Beispiel mit einem Smartphone mit locale auf Französisch gesetzt, werden die CWA-Texte auf Englisch erscheinen.

Welche Sprache erscheint, wenn es keine Übereinstimmung zwischen Smartphone locale und in der App vorhandenen Sprachen, wird von den Texten in https://github.com/corona-warn-app/cwa-app-android/tree/main/Corona-Warn-App/src/main/res/values bestimmt, die auf Englisch abgelegt sind.

Mit locale auf Deutsch gesetzt, erscheinen alle Texte auf Deutsch.

**Comment by gitterman** [comment]
Danke für die Aufklärung.
Das heißt aber auch, dass ein Franzose, Spanier oder Italiener, der in Deutschland lebt und arbeitet, neben seiner Heimatsprache und der des deutschen Gastlandes auch noch Englisch sprechen muss, wenn er die Corona Warn App verstehen will.
Das ist für nicht gerade ein benutzerfreundliches Design.

**Comment by MikeMcC399** [comment]
@gitterman 
- Sorry, dass ich nicht weiter helfen kann. Wie ich sehe, warst Du schon in #3489 vor einem Jahr aktiv. 

- Evtl. kann das Open Source Team hier oder in #3489 Feedback geben.

**Comment by MikeMcC399** [comment]
- I have opened a related enhancement request #5468 since there is a new facility in Android 13 which can be used to set an app language independently of the system language.

**Comment by MikeMcC399** [comment]
This probably cannot be realized now due to the project ramp-down.

See:
- https://github.com/corona-warn-app/cwa-app-android/issues/5469#issuecomment-1371936091
- https://github.com/corona-warn-app/cwa-app-android/issues/5468
