### ISSUE TITLE
CCL config - different versions

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#4993]
## Avoid duplicates
* [X] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Question is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Question has not already been asked in another issue

## Your Question
On different Android devices I can see
- [CCL 1.1.0](https://github.com/corona-warn-app/cwa-app-ccl/releases/tag/v1.1.0) (release date Mar 14, 2022)
- [CCL 1.2.1](https://github.com/corona-warn-app/cwa-app-ccl/releases/tag/v1.2.1) (release date Mar 23, 2022)

being shown through CWA "App Information". The devices have been updated to CWA Android 2.19.2.

1. What triggers a CCL config update on CWA Android?
2. Is it expected that different devices will be using different CCL versions?

https://github.com/corona-warn-app/cwa-app-ccl#readme says "The logic in CCL is described in JSON format. An engine processes the logic on the client against a defined input structure (e.g. the set of DCCs) and can expect a defined output structure. The client can update the JSON regularly from a server. This facilitates updates to CCL independent of client releases, e.g. in order to respond to legal or regulatory pandemic-related changes on short notice."

**Comment by Ein-Tim** [comment]
FYI: https://github.com/corona-warn-app/cwa-app-ccl/issues/49#issuecomment-1077683566 from @mlenkeit says:
"It might take up to 24 hours until all devices have updated to the new version of CCL."

**Comment by mlenkeit** [comment]
@MikeMcC399 Android usually updates CCL once a day, randomly distributed to avoid load peaks. After 24 hrs, all devices should be on 1.2.1 (provided they have a network connection).

**Comment by MikeMcC399** [comment]
@mlenkeit 
Thank you very much for the explanation. Indeed, by this morning the two devices which were still on 1.1.0 are now on 1.2.1.

I will close this now that the question has been answered. I wonder though if there shouldn't be some documentation somewhere which describes this.
