### ISSUE TITLE
Fix dark-mode colors

### ISSUE THREAD

**Issue by m1ga** [corona-warn-app/cwa-app-android#50]
## Current Implementation

The app has a dark-mode theme but the background color of the TAN input is not changed so the fields are not visible.
Same for the option selection: the background makes it hard to read the font

## Suggested Enhancement

Adding `tanInputBackground` to the night/colors and set a correct color.

Use `colorGreyLight` for `dispatcher_card_header`.

## Expected Benefits

User can see the TAN input fields in dark-mode and is able to read the text inside the option cards:

After changes:
![app_cards2](https://user-images.githubusercontent.com/4334997/83354274-cae97080-a357-11ea-9a0f-0040be9a9fc4.png)
![83351983-aafe8080-a348-11ea-94e9-a4012887781b](https://user-images.githubusercontent.com/4334997/83354281-d9378c80-a357-11ea-9779-d74d6fad3282.png)

**Comment by marcmuschko** [comment]
Dear @m1ga ,
 
thank your very much for your contribution! The project team is working tirelessly on getting the app ready in time and working on many backlog items in parallel. This also means that some implementations cannot be done, yet, as we are, for example, waiting for final decisions from the design team.
 
Therefore, we unfortunately have to reject your corresponding PR for now.
 
To avoid this situation in the future, please open an issue for your fixes, and wait until the team assigns you to the issue. We will further create issues with the community label, which you can claim by commenting on them and don't have to wait for the assignment.
 
Thank you for your understanding!

**Comment by m1ga** [comment]
@marcmuschko no problem! But please don't forget to fix it. You've closed the issue so I hope it won't get lost. The current master still has the dark-mode problems and I don't see a PR at the moment. Just make sure you'll test it before releasing :-)

**Comment by marcmuschko** [comment]
@m1ga You are right the issue is closed, but be assured that dark mode will be tested as intensively as the light mode before release! 
I personally enjoy dark mode very much, and once we are done with reworking the final styles, the dark mode should be quite stunning :)
