### ISSUE TITLE
Missing test certificate under "Certificates" tab...

### ISSUE THREAD

**Issue by Jo-Achim** [corona-warn-app/cwa-app-android#5000]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [?] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [?] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy Note 10
- Android version: Android 12 (One UI 4.0)
- App version: 2.19.2

## Describe the bug

A test certificate should also be displayed under "Certificates", as described:

![Screenshot_20220329-125327_Corona-Warn](https://user-images.githubusercontent.com/21124877/160597642-cdb19282-3183-470d-a599-f863e6b66964.jpg)

This is not the case; **a new quick test certificate** is missing under "Certificates" tab.

Is the description wrong / outdated? Or has something changed?

In the current version 2.19.2, the text is also displayed under „Ihr Testergebnis“ / „Schnelltest“ / „Nachweis-Funktion“: „Das Zertifikat finden Sie auch im Bereich „Zertifikate“." (See: "Your test result" / "Quick test" / "Verification function": "You can also find the certificate in the "Certificates" area. (See: figure above.) 

## Steps to reproduce the issue

Register a new rapid test
Open rapid test
Read proof function
Go to Certificate
If necessary, select the right person
Check under Certificates to see if the rapid test result is there.

## Expected behaviour

I only see **one** old PCR test certificate from November 2021 next to the vaccination certificates - but that shouldn't be the problem, right?
Thus, the missing quick test certificate should also be displayed under the „Certificate“ tab.

**Comment by mtwalli** [comment]
@Jo-Achim I'm confused, you say Rapid Test ,but the screenshot says: 
`Your PCR diagnosis` and the certificate is for `PCR` , How Rapid Test is related ?

**Comment by Jo-Achim** [comment]
@mtwalli, sorry my mistake. I had copied the wrong screenshot.
It's about a **new rapid test**.

**Comment by Ein-Tim** [comment]
If there was no certificate issued (e.g. because you declined the creation of a certificate or because the testing site is not able to create DCCs), the text does not apply. You will only find a certificate on the certificates tab if you also see the certificate in this screen (like with the PCR test).

**Comment by Jo-Achim** [comment]
> You will only find a certificate on the certificates tab if you also see the certificate in this screen (like with the PCR test).

In this screen?

![Screenshot_20220329-125327_Corona-Warn](https://user-images.githubusercontent.com/21124877/160597642-cdb19282-3183-470d-a599-f863e6b66964.jpg)

If the text is not applicable, should a different wording be chosen? Or this passage of text is not displayed?

**Comment by mtwalli** [comment]
Might be improved , but the beginning of the paragraph states:
>  If you requested a digital test certificate when
you registered your test and the testing point
supports the issuing of digital certificates, 

and then states where to find it , also in this case there is no direct link to the certificate ,but the paragraph explains just in case Dcc was requested. 

So , no issue ,right ?

**Comment by Jo-Achim** [comment]
> So , no issue ,right ?

I'm not sure, otherwise I wouldn't have opened the topic. However, the word usage is not always correct / complete.
The registration at this [Test Station](https://tzm-plattling.covidservicepoint.de/anmeldung) says "**Corona quick test including certificate**". 
And 
![grafik](https://user-images.githubusercontent.com/21124877/160601971-f68dfc5d-fc95-489c-8f9a-4a9f572fe096.png)

It's possible that I'm not remembering correctly - but I think I've already seen a quick test (of this test station) under "Certificates". But unfortunately I can't find any screenshots that prove this.

So if necessary and helpful, the text "Might be improved".
And if it is actually not an issue - even considering the above information regarding the test station - then I will close the topic again.

**Comment by vaubaehn** [comment]
> @Jo-Achim I'm confused, you say Rapid Test ,but the screenshot says: `Your PCR diagnosis` and the certificate is for `PCR` , How Rapid Test is related ?

Hi @mtwalli , there is also an issue with the display of the erroneously copied PCR-test: when you use the "edites" button in the OP, you'll see that the test tile refers to a test added on 4 Mar 2022, but the certificate referred to in the same screen was obviously issued in May 2021?

**Comment by Jo-Achim** [comment]
Sorry, after my incorrectly chosen image from https://www.coronawarn.app/de/screenshots/ in the first post, I corrected it later - and hereby correct it again!

It is now the snapshot of my smartphone from today (about an hour ago).

PS: If it is useful for clarification, the URL of the quick test certificate starts with: https://s.coronawarn.app?v=1

**Comment by mtwalli** [comment]
@vaubaehn  Screenshots have dummy dates ;)

@Jo-Achim , Did you see this screen while registering your test?
<img src="https://user-images.githubusercontent.com/25054729/160609021-eeb7c4c9-df1a-48c0-9f10-cb9238aa49eb.png" width="350"/>


Do you remember what choice you clicked?

Note: this screen is not presented while registering the test if the QrCode does not have `isDccSupportedByPoc` flag in it

**Comment by mtwalli** [comment]
Possible, I would suggest to close this issue and create a new one for that ?

**Comment by Jo-Achim** [comment]
@mtwalli,
ok, i will close this issue and open a new one: [Text correction needed: Test certificate not in the "Certificates" tab...](https://github.com/corona-warn-app/cwa-app-android/issues/5002#issue-1184927003) 
I hope that I have correctly summarized my findings and statements here. 
On that note, thank you.

**Comment by vaubaehn** [comment]
@mtwalli 
> @vaubaehn Screenshots have dummy dates ;)

Oooops... Tricky! 😉 

@Jo-Achim 
That was a fast issue for the #5000-anniversary-issue 😉 

👋

**Comment by Jo-Achim** [comment]
If only all problems could be solved so quickly and hopefully successfully in the next step.
