### ISSUE TITLE
"This item is not compatible with your device." error

### ISSUE THREAD

**Issue by Daniel-Mietchen** [corona-warn-app/cwa-app-android#503]
## Describe the bug

When trying to install the app on a Samsung GT-I9195, I am getting a ```This item is not compatible with your device.``` error.

## Expected behaviour

I would expect the app to be installable, just the way it is on the Fairphone 2.

## Steps to reproduce the issue

<img width="545" alt="Screen Shot 2020-06-16 at 04 29 42" src="https://user-images.githubusercontent.com/465923/84751001-0b690100-af8a-11ea-8577-90f172e50d78.png">

## Technical details

- Host Machine OS (Windows/Linux/Mac):

**Comment by markusmarkusz** [comment]
Have you tried installing the app from the phone directly? I've often had problems on the website, that's why I prefee the Play Store app.

**Comment by tomjschwanke** [comment]
Google's tracing API is only available on Android 6 or higher

**Comment by jeyemwey** [comment]
Hi,

the Samsung Galaxy S4 Mini does not support Bluetooth Low Energy and is on Android 4.4.2 according to its [Wikipedia article](https://en.m.wikipedia.org/wiki/Samsung_Galaxy_S4_Mini). Android 4.4.2/[KitKat](https://en.m.wikipedia.org/wiki/Android_KitKat) has been discontinued for almost 5 years.

I'm afraid, your phone is too old for this app.

**Comment by Daniel-Mietchen** [comment]
Yes, this phone is running on Android 4.4.2, and when trying to install from the phone directly, the app is simply not listed. Thanks all for checking.

**Comment by Daniel-Mietchen** [comment]
Closing as duplicate of #489 .
