### ISSUE TITLE
Upon clicking notification nothing is displayed

### ISSUE THREAD

**Issue by tasomaniac** [corona-warn-app/cwa-app-android#5030]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Pixel 6
- Android version: Android 12
- App version: 2.18.1

## Describe the bug

When I received the notification that says that there is a message, nothing happens after I click. The app opens with exactly same exposure state.

This happened at least 5+ times and that's why I decided to open this report. 

## Steps to reproduce the issue

1. Remember the date of last exposure
2. Received notification
3. Click notification
4. Observe app is open with the same last exposure date without any changes. 

## Expected behaviour

Once I click the notification, I should see changes on the app or a message.

**Comment by MikeMcC399** [comment]
@tasomaniac 

- It sounds like you are experiencing the same issue as reported in https://github.com/corona-warn-app/cwa-app-android/issues/4211. Would you like to check if it is the same?

**Comment by MikeMcC399** [comment]
@tasomaniac 

You write that you are using the version 2.18.1.

The latest version is however 2.20.3, so I would recommend that you check in the [Google Play Store](https://play.google.com/store/apps/details?id=de.rki.coronawarnapp) and update to this latest version.

**Comment by tasomaniac** [comment]
Sounds definitely similar report but for me it was not after 2 hours. I got them in different days.

I will update and report back if I see it still. My "red" Status is recently turned into green, so I may not see it anymore. Let's see

**Comment by Ein-Tim** [comment]
@tasomaniac 

> Sounds definitely similar report but for me it was not after 2 hours. I got them in different days.

If you scroll down in the issue, this is also what most users are experiencing. The OP was just what one Twitter user reported.

I think this definitely can be closed in favor of https://github.com/corona-warn-app/cwa-app-android/issues/4211.

**Comment by tasomaniac** [comment]
Yep. Sounds good. Thanks for the reply
