### ISSUE TITLE
High risk removed from contact journal

### ISSUE THREAD

**Issue by DerVogel2020** [corona-warn-app/cwa-app-android#5031]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name:
- Android version: 8
- App version: 2.20

## Describe the bug

I had a red tile in the app. Today it is gone, because the risk calculation only considers 10 days now.
But I expect this contacts still to be shown in the journal because there are still 15 days shown.

## Steps to reproduce the issue

1. Have a contact
2. Wait 11 days
3. See the contact journal

## Expected behaviour

The entry at e.g. Tuesday 2 weeks ago was there and should stay there as long as the days is shown in the journal.

**Comment by MikeMcC399** [comment]
@DerVogel2020 

- It would probably make sense to implement https://github.com/corona-warn-app/cwa-wishlist/issues/815 so that the period of consideration for risk checks and for the Contact Journal are the same.
- This should be standardized across both Android and iOS, so I suggest the moderators movie this issue to the [cwa-documentation issue list](https://github.com/corona-warn-app/cwa-documentation/issues).

**Comment by DerVogel2020** [comment]
Thanks. I looked for the first one, but in the wrong repositories.😉

**Comment by MikeMcC399** [comment]
@DerVogel2020 
> Thanks. I looked for the first one, but in the wrong repositories.😉

I used the search field in the top left of GitHub and typed `org:corona-warn-app is:issue is:open journal in:title` to find it. It's quite tricky sometimes with all the different repositories.

**Comment by mtwalli** [comment]
I can't reproduce this issue, High risk is not removed from contact diary after 11 days, please provide error log if you can re-produce it ? 
see recording: 

https://user-images.githubusercontent.com/25054729/189894340-a1deae80-b6a9-4a32-8657-1d1860ec79f6.mp4

**Comment by Ein-Tim** [comment]
@mlenkeit Did the device perform a new risk check on 23/09/2022 (i.e. do you still see the red encounter on the "Status" tab or only the failed card)?

**Comment by mtwalli** [comment]
> @mlenkeit Did the device perform a new risk check on 23/09/2022 (i.e. do you still see the red encounter on the "Status" tab or only the failed card)?

@Ein-Tim I think you mean me.It did not. I see failed risk card. do you think future calculations matter in this occasion?. as far as I know when high risk is reported from ENS or ChecksIns it is saved in contact diary database independently from risk calculation

**Comment by Ein-Tim** [comment]
@mtwalli I guess if the app would turn green again the contact would also be removed from the contact journal, maybe you could test that? 

Because AFAIK the current implementation, at least under iOS, is that risk encounters are removed from the contact journal after they are not displayed anymore on the "Status" tab.

**Comment by DerVogel2020** [comment]
@mtwalli started error logging and will check in a few days.

**Comment by DerVogel2020** [comment]
@mtwalli this still occurs.
The error log is ID 6A10B254EB600F352CBE

**Comment by mtwalli** [comment]
@DerVogel2020 You are right that the risk disappears from contact journal after 10 days (atm). There was an intended change in `v2.20` to restrict exposure history to specific age (configurable from AppConfig) at the moment it is 10 days. 
Change in the app meant:
> for ENF, when obtaining Exposure Windows, they are filtered by age against a parameter from the app config before any other processing (risk calculation, PPA, contact journal, etc.)
for event registration, check-ins are filtered by age against a parameter from the app config. Therefore it is not a bug, however I see that this can be still confusing to the user and Contact Journal might be restricted to  configurable age too. 
Fortunately there is a swishlist request for that https://github.com/corona-warn-app/cwa-wishlist/issues/815

**Comment by mtwalli** [comment]
As I mentioned earlier, this is working as designed and no plan to change it in the future.
