### ISSUE TITLE
After certificate update: Vaccination 2 of 1

### ISSUE THREAD

**Issue by nhnb** [corona-warn-app/cwa-app-android#5032]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* ? Bug is specific for Android only (I don't own an Apple phone, so I cannot test that)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: S9
- Android version: 10
- App version: 2.20.3

## Describe the bug

My second vaccination certificate is shown as "Impfung 2 von 1".

## Steps to reproduce the issue

- get vaccinated with Johnson&Johnson
- get vaccinated with Moderna
- get infected
- agree to renewal of certificate
 
![cwa](https://user-images.githubusercontent.com/364184/161510699-5bac2c6d-84d1-4768-9ea9-7946ac3cba4b.jpeg)

## Expected behaviour

"Impfung 2 von 2"

**Comment by dsarkar** [comment]
@nhnb Thanks for asking. The notation "2/1" is now correct one. See e.g. https://ec.europa.eu/commission/presscorner/detail/en/ip_21_6837

Best wishes, DS

---
Corona-Warn-App Open Source Team
