### ISSUE TITLE
Request TAN for PCR Test - service times wrong

### ISSUE THREAD

**Issue by coogor** [corona-warn-app/cwa-app-android#5049]
On the above page (in CWA 2.14), service times for Hotline is Mo-Sun, 24h
This is in between reduced to 8-20h. Not sure if all days, still

**Comment by MikeMcC399** [comment]
@coogor 

- It sounds like you may be using the CCTG version as the current CWA version is now 2.20.3. See https://github.com/corona-warn-app/cwa-app-android/issues/2837.

- According to the CWA 2.20.3 version the TAN hotline hours are now:<br>
Daily (including weekends) 7 am - 8 pm (CET)

You can view this in CWA by Manage Your Tests > Request TAN for PCR Test

You can check this also on the FAQ page:
https://www.coronawarn.app/en/faq/results/#international_phone_numbers

Did you receive information somewhere that the service hours of the TAN Hotline start at 8 am not 7 am?

**Comment by coogor** [comment]
Hello Mike,
Am Dienstag, 5. April 2022, 15:03:26 CEST schrieb Mike McCready:

> - It sounds like you may be using the CCTG version as the current CWA
> version is now 2.20.3. See
> https://github.com/corona-warn-app/cwa-app-android/issues/2837.

Correct, I'm using CCTG

> Did you receive information somewhere that the service hours of the TAN
> Hotline start at 8 am not 7 am?

That was out of my head from 2 weeks ago - verified today that start time is
0700

Last night an update of CCTG arrived that fixed the service hours.
So I think we can close the ticket.
Sorry for the noise....

**Comment by coogor** [comment]
closing

**Comment by MikeMcC399** [comment]
@coogor 

Thanks for closing the loop! It's also good to know that CCTG has been updated, even though this isn't the repository for the CCTG fork.
