### ISSUE TITLE
Wo ist die JSON-Schnittstelle für die Reptiloiden-NWO?

### ISSUE THREAD

**Issue by Muku784** [corona-warn-app/cwa-app-android#505]
Ich finde die irgendwie nicht. Kann mir jemand helfen? Frage für Attila Hildmann. Und nein, es ist keine Scherzfrage, denn AH hat ziemlich lange Physik studiert.

**Comment by SebastianWolf-SAP** [comment]
Eine solche Schnittstelle ist im Moment nicht geplant. Bitte wenden Sie sich für solche Feature-Anfragen an die Bundesregierung... 

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by godofdream** [comment]
Wenn wir schon die Reptiloiden Schnittstelle nicht kriegen, wäre es dann zumindest möglich die Corona Warn-App als Modul auf dem Bill-Gates Impfchip laufen zu lassen? möchte nicht immer mein Smartphone mit mir rumtragen.

**Comment by Muku784** [comment]
Der Bill-Gates-Impfchip ist ein Hoax. Könnte mir aber ein Neuralink-Modul vorstellen, das Deine Gehirnwellen zukünftig auf Querdenken scannt und Dich gleich einer U̶m̶e̶r̶z̶i̶e̶h̶u̶n̶g̶s̶l̶a̶g̶e̶r̶ Klinik zuweisst, falls positiv. Denn die Volksgesundheit geht vor allem, der einzelne zählt nicht.
