### ISSUE TITLE
App crasht auf Geräten ohne Google Play Dienste

### ISSUE THREAD

**Issue by Diapolo** [corona-warn-app/cwa-app-android#507]
## Describe the bug

Nach Bestätigung der Datenschutzerklärung crasht die App vor der Aktivierung der Risiko-Ermittlung. URSACHE: 3 - Fehler bei der Kommunikation mit Google API(17).

## Expected behaviour

Alles läuft, Impfstoff wird gefunden, App überflüssig ;).

## Steps to reproduce the issue

- App starten
- "Risiko-Ermittlung aktivieren" anklicken

## Technical details

- Android 10 (LineageOS 17.1 ohne Google Play Dienste)
- Fehler: EXPOSURE_NOTIFICATION_API is not available on this device.

## Possible Fix

Vielleicht keiner, bis Google die Tracing-API in ihr Base-OS integriert hat, aber ihr könntet eine Warnung auswerfen, dass die App ohne Google Play Dienste nicht lauffähig ist und nicht einfach stumpf crashen ;).

**Comment by rugk** [comment]
Looks very similar to/like a dupe of https://github.com/corona-warn-app/cwa-app-android/issues/506

**Comment by tomjschwanke** [comment]
See #477

**Comment by uschindler** [comment]
Nevertheless I can confirm: App works perfectly on LineageOS 16 or 17 if Google Services are installed (using OpenGApps installer).

**Comment by SebastianWolf-SAP** [comment]
In addition to the already posted comments, please see https://github.com/corona-warn-app/cwa-documentation/issues/5 for details. Closing as duplicate...

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
