### ISSUE TITLE
Error while sending error report -- so this is an error report about the error report

### ISSUE THREAD

**Issue by diablodale** [corona-warn-app/cwa-app-android#5089]
Error reporting has error when sending an error report.
![image](https://user-images.githubusercontent.com/679350/163442943-5e2ddea0-f1fc-4e99-bdb2-2b0f31a0856d.png)

## Avoid duplicates

* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
[documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* Unknown, I have only an Android phone.
* [X] Bug is not already reported in another issue

## Technical details

- Device name:  realme x50 pro 5g
- Android version:  11
- App version:  2.20.4

## Steps to reproduce the issue

1. Notice errant behavior of the app
2. menu -> app information
3. click error reports
4. start recording
5. reproduce errant behavior in app
6. menu -> app information
7. error reports
8. click send error report
9. agree and send

## Result

```
Something went wrong.
The error report cannot be sent right now. Please try again later.
```

Repeating the steps fails. Repeated sending fails with same error.
I have sent many month ago an error report. Reporting worked once many months ago.

## Expected behaviour

No error. Report to be sent. And to receive a tracking id for the report.

**Comment by MikeMcC399** [comment]
@diablodale 

Same for me. If you use "SHARE AND CONTINUE" you can look into the log file.

```
2022-04-14T17:44:20.886Z E/DebugLogUploadViewModel: de.rki.coronawarnapp.exception.http.UnauthorizedException: Error during web request: code=401 message= body={"timestamp":"2022-04-14T17:44:20.846+00:00","status":401,"error":"Unauthorized","path":"/api/logs"}'
	at de.rki.coronawarnapp.http.HttpErrorParser.intercept(HttpErrorParser.kt:35)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
	at de.rki.coronawarnapp.http.interceptor.RetryInterceptor.intercept(RetryInterceptor.kt:3)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:4)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:14)
	at 
```

**Comment by Ein-Tim** [comment]
Same under iOS, please move to the documentation repository.

**Comment by Ein-Tim** [comment]
@dsarkar & @larswmh PRIO item IMO, please mirror ASAP.

Ping @thomasaugsten

**Comment by Ein-Tim** [comment]
I can access https://logupload.coronawarn.app via a browser, so there is no complete outage of this part.

**Comment by MikeMcC399** [comment]
Maybe it's a coincidence but https://logupload.coronawarn.app seems to have a new SSL certificate issued today
Valid from April 14, 2022 to April 18, 2023

**Comment by Ein-Tim** [comment]
FYI: I opened https://github.com/corona-warn-app/cwa-log-upload/issues/30

**Comment by Ein-Tim** [comment]
FYI: https://github.com/corona-warn-app/cwa-log-upload/issues/30#issuecomment-1099534510

The team's on it.

**Comment by MikeMcC399** [comment]
@diablodale 

- https://github.com/corona-warn-app/cwa-log-upload/issues/30 is now resolved, although there is no comment in that issue what caused the outage

- I was able to successfully submit a dummy error report this morning. It looks like the site has reverted to an older SSL certificate
Valid from April 13, 2021 to April 18, 2022
which however expires in 3 days.

**Comment by diablodale** [comment]
Unfortunately, it is not successful. Same 9 repro steps as in OP.

###  Result

No confirmation of upload.
No ID listed in history.
No status.
The error analysis section at the bottom continues to show `Recording Active` and has three buttons under it.
![image](https://user-images.githubusercontent.com/679350/163587724-a358d912-0b6c-4205-841b-c22adde7b8e7.png)

**Comment by diablodale** [comment]
Nice to hear it works for you. Doesn't here as in the OP.

**Comment by Ein-Tim** [comment]
@diablodale Are you sure that there is no new ID created? Did you restart the app and retried?

**Comment by diablodale** [comment]
The screenshot above shows no IDs under "ID History". Please see https://github.com/corona-warn-app/cwa-app-android/issues/5089#issuecomment-1100166783

I received no dialog box or other UI element which gives me an ID so I can copy/paste that ID into the other CWA bug that I have reported.

As you requested, I force-stopped the CWA app. Opened the app. Menu, error reporting...
No IDs are listed under "ID history". It writes "IDs of the error analyses shared so far" and then provided no IDs..

**Comment by MikeMcC399** [comment]
@diablodale 
> It writes "IDs of the error analyses shared so far" and then provided no IDs..

Did you tap on the item: "IDs of the error analyses shared so far"?

It does not show the IDs unless you do that.

**Comment by diablodale** [comment]
hahaha, yes, IDs are listed after I click the hidden action.
Thanks for the hack. 👍

I'll open a separate bug on the hidden ID list UI.
