### ISSUE TITLE
false statement: rapid test no longer valid more than 21 days; test is only 14 days old

### ISSUE THREAD

**Issue by diablodale** [corona-warn-app/cwa-app-android#5090]
Main app UI writes false statement
```
Rapid Test
No longer Valid
Your test is more than 21 days old and...
```

Last test is listed in app Journal on 1 April 2022 -- therefore it is 14 days old.
Yes, the test itself is invalid. The false count is 21.

## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* Unknown, I have only Android phone.
* [X] Bug is not already reported in another issue

## Technical details

- Device name: realme x50 pro 5g 
- Android version: 11
- App version: 2.20.4

## Steps to reproduce the issue

1. Open corona warn app

## Result

False statement on main UI.
![image](https://user-images.githubusercontent.com/679350/163449455-364bd1e8-c21d-4885-ac7a-7a448faac0bc.png)

***Click*** to go to Journal. Scroll down to newest test. Test was on 1 April.
![image](https://user-images.githubusercontent.com/679350/163449258-d8599d33-e58f-41a5-b67f-60db46fda061.png)

Unable to sent error report due to bug #5089

## Expected behaviour

True statement: The test is invalid and is 14 days old.

**Comment by Ein-Tim** [comment]
Did you ever change the time on your device?

**Comment by diablodale** [comment]
I did not.
Checking the Android settings, the time and timezone are `set automatically`

Germany changed the time compared to UTC on 27 March 2022; but that was before the 1 April test.

**Comment by diablodale** [comment]
error report id:  0DEB64CA239A409A4AC5

**Comment by mtwalli** [comment]
Text has been updated  in 2.26 https://github.com/corona-warn-app/cwa-app-android/pull/5377, does this fix the issue for you ?

**Comment by diablodale** [comment]
I can not verify any fix/changes at this time. I will be able to look again at this in November.

**Comment by MikeMcC399** [comment]
@diablodale

> I can not verify any fix/changes at this time. I will be able to look again at this in November.

The number of days is hardcoded as "2" into the text string in 2.26, for example:

https://github.com/corona-warn-app/cwa-app-android/blob/ef2b8c3905ce2200352b824df785d9e452b9aace/Corona-Warn-App/src/main/res/values/antigen_strings.xml#L38-L39

I suggest to close the issue based on code inspection.

**Comment by mtwalli** [comment]
@diablodale closing it for now, feel free to reopen if you can reproduce it
