### ISSUE TITLE
Error reports: UI hides actions and does not follow UI standards

### ISSUE THREAD

**Issue by diablodale** [corona-warn-app/cwa-app-android#5091]
The error reporting UI hides links and actions for `ID History` and `privacy notice`
The user does not know what can be clicked or activated.

## Avoid duplicates

* [X] This enhancement request has not already been raised before
* Unknown if apple problem. I have only an Android phone. I did look and there is no similar bug in the `documentation` repo.

## Current Implementation

1. menu -> app information
2. click error reports
3. scroll to bottom of UI

Only the `Start` button is clickable. Nothing else is visually clickable or actionable.
There are 8+ paragraphs of text on this UI. The UI must follow UI standards to indicate what is clickable/actionable.

![image](https://user-images.githubusercontent.com/679350/163596970-c5d24f7e-bca6-47a5-b088-556dbdc022c6.png)

## Suggested Enhancement

1. menu -> app information
2. click error reports
3. scroll to bottom of UI
4. ID History uses the "further indicator" to lead the user to activate it for a list of IDs
5. Privacy notice is underlined indicating a link to content.

Good examples...

![image](https://user-images.githubusercontent.com/679350/163597280-0252d376-e9f1-4a45-9977-b7c69aab2b5f.png)

![image](https://user-images.githubusercontent.com/679350/163597515-5f9a768c-ad2f-4d06-8880-589ed1dc8c9c.png)

## Expected Benefits

* Less user confusion. A user in this section of the app wants to help. But the lack of standard UI guidelines hides functionality and leads to user confusion and/or abandon.
* Faster turnaround/escalation. When the functionality is not hidden, then the user can quickly report the error. Since this is a live service related to country-wide healthcare, timely reporting of problems is relevant.
* Less support resources/humans. Escalation to support/github because of the hidden functionality consumes further human resources.

---
Internal Tracking ID: [EXPOSUREAPP-12854](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12854)

**Comment by Ein-Tim** [comment]
Not a problem under iOS, there's an arrow which makes it clear that this is clickable: 

<img src="https://user-images.githubusercontent.com/67682506/163598370-de65a5d4-0e15-4203-a86e-2f52e1d9131e.jpeg" width="300">

**Comment by MikeMcC399** [comment]
@diablodale 

Thanks for reporting this issue. I have been confused by this myself!

The UI should pop up the ID for a new error report submission. As it is implemented in the 2.20 release it doesn't automatically scroll to the ID history section, nor does it indicate that there is a history hidden which needs a tap. So you were not alone in wondering:
a) was the report submitted?
b) where is the ID if it was submitted?

I wrote several other suggestions concerning error reports, however they have not been addressed so far:

- https://github.com/corona-warn-app/cwa-documentation/issues/614
- https://github.com/corona-warn-app/cwa-documentation/issues/612
- https://github.com/corona-warn-app/cwa-wishlist/issues/521

**Comment by Ein-Tim** [comment]
In https://github.com/corona-warn-app/cwa-wishlist/issues/523 I included the following sentence under "Suggested Enhancement":

> Stop the error report after sending it and point out to the ID-history where he/she can find the relevant ID.

**Comment by larswmh** [comment]
Thanks for your enhancement request @diablodale. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-12854](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12854)

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
- see PR https://github.com/corona-warn-app/cwa-app-android/pull/5588
