### ISSUE TITLE
There is no way (at least no obvious one) to report my infection without leaving my home. 

### ISSUE THREAD

**Issue by alexander-n8hgeg5e** [corona-warn-app/cwa-app-android#5092]
I'm pretty sure I'm infected, I made a rapid test at home and I have strong symptoms.
To break the infection chain it is important to be able to immediately warn the other CWA-users about the increased risk.
Sure there could be false reports, but there is no question about that there is an increased risk.
This risk should be used in the risk calculation.

**Comment by MikeMcC399** [comment]
@alexander-n8hgeg5e 

I'm sorry to hear that you are sure that you are infected!

- The app recommends getting in touch with your family doctor in this case. You can see the screenshots of the various recommendations from the app on https://www.coronawarn.app/en/screenshots/#android_cards

- Also the website of the Bundesministerium für Gesundheit (BMG) has some additional instructions in German [Ich habe ein positives Selbsttestergebnis. Was muss ich tun?](https://www.zusammengegencorona.de/faqs/testen/selbsttest/#id-f0e8c996-fc61-5965-9019-f5c8ebbe3d13).

- There is a good argument at this stage in the pandemic for being able to pass on the results of a self-test. There is already a wishlist item https://github.com/corona-warn-app/cwa-wishlist/issues/374 submitted on this topic.

All the best to you for a speedy recovery!

**Comment by Ein-Tim** [comment]
> Sure there could be false reports, but there is no question about that there is an increased risk.

The question is how should a feature to warn with positive rapid antigen self tests be implemented. As you can read in https://github.com/corona-warn-app/cwa-wishlist/issues/374, there is always a valid concern that someone might easily fool the system.
I suggest to continue the discussion in https://github.com/corona-warn-app/cwa-wishlist/issues/374.

And same for me: A speedy recovery!

**Comment by mtwalli** [comment]
Closing as duplicate
