### ISSUE TITLE
Wrong FAQ link for VC_ALREADY_REGISTERED error

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#5099]
## Technical details

- Device name: Samsung Galaxy A52 5G SM-A526B/DS
- Android version: 12
- First reported on App version: 2.20.4
- Reviewed as unfixed in App version: 2.24.0

## Describe the bug

When scanning a certificate which has already been stored in CWA the pop-up error message links to "FAQ FOR CERTIFICATES" using the URLs:

- https://www.coronawarn.app/en/faq/#eu_dcc
- https://www.coronawarn.app/de/faq/#eu_dcc

The anchor `#eu_dcc` links to the topic "Certificates" in the "App Features" section of the FAQs. This section does **not** contain the FAQ for `VC_ALREADY_REGISTERED`.

## Steps to reproduce the issue

1. Open CWA and tap the "Scan" button
2. Scan a certificate
3. Scan the same certificate again
4. Tap on "FAQ FOR CERTIFICATES"

![VC_ALREADY_REGISTERED](https://user-images.githubusercontent.com/66998419/164062087-2a13a876-6feb-43ed-8375-7facac85e1a5.jpg)

There is nothing helpful in the FAQ section shown:

![image](https://user-images.githubusercontent.com/66998419/164405787-d5880e89-25b6-46a3-b8c5-247a371ba8c6.png)

(Screenshot above: updated Apr 21, 2022, 09:48.)

## Expected behavior

The link "FAQ FOR CERTIFICATES" in the pop-up error dialog should provide useful information.

Since the restructuring of the FAQs took place, there is a separate location for "Certificates" in the "Troubleshooting" section of the FAQs (not the same as the  "App Features" section). The "Troubleshooting" section has the anchor `#support` with URLs:

- https://www.coronawarn.app/en/faq/results/#support "Troubleshooting"
- https://www.coronawarn.app/de/faq/results/#support "Troubleshooting"

Within the "Troubleshooting" section, the FAQ article specifically dealing with the error `VC_ALREADY_REGISTERED` has the anchor `#hc_already_registered` and the URLs are:

- https://www.coronawarn.app/en/faq/results/#hc_already_registered "Error 'VC_ALREADY_REGISTERED', 'TC_ALREADY_REGISTERED' or 'RC_ALREADY_REGISTERED'"
- https://www.coronawarn.app/de/faq/results/#hc_already_registered "Fehlermeldung 'VC_ALREADY_REGISTERED', 'TC_ALREADY_REGISTERED' oder 'RC_ALREADY_REGISTERED'"

## Possible Fix

The anchor in the URL should be changed from `#eu_dcc` to `#hc_already_registered`

The link to the FAQ is defined in
https://github.com/corona-warn-app/cwa-app-android/blob/c7292d5f93348b69ef335237a7e6d8d7ed622b5b/Corona-Warn-App/src/main/res/values/links.xml#L25-L26
and
https://github.com/corona-warn-app/cwa-app-android/blob/c7292d5f93348b69ef335237a7e6d8d7ed622b5b/Corona-Warn-App/src/main/res/values-de/links.xml#L15-L16

and these are the two files which need changing.

After this change the following FAQ is shown after tapping "FAQ FOR CERTIFICATES" in the error dialog for `VC_ALREADY_REGISTERED`:

![FAQ VC_ALREADY_REGISTERED](https://user-images.githubusercontent.com/66998419/164062689-46240654-cb56-4e46-932d-0fd5296407ca.jpg)

---
Internal Tracking ID: [EXPOSUREAPP-13218](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13218)

**Comment by Ein-Tim** [comment]
JFYI: The iOS app does not have separate links for errors with certificates, but only one general link. I like the Android solution much more and will open an enhancement request for this.

**Comment by MikeMcC399** [comment]
- This issue is related to the discussion https://github.com/corona-warn-app/cwa-website/issues/2792

**Comment by MikeMcC399** [comment]
@dsarkar 

Do you see a problem going ahead with the suggested resolution for this issue under Android? I think this can be handled independently of any changes for iOS.

The string `error_dcc_already_registered_faq_link` is only used in one place, so there should not be any undesired side-effects of changing the link target from `#eu_dcc` to `#hc_already_registered`.

https://github.com/corona-warn-app/cwa-app-android/blob/aa450b97e701f6481019681cc6f5a03b7dcc6e86/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/qrcode/ui/ScannerExtensions.kt#L36-L38

**Comment by MikeMcC399** [comment]
Will the Open Source Team respond to this issue?

**Comment by dsarkar** [comment]
@MikeMcC399 Yes, sorry for late reply, we will have a look at the FAQ link issues.

**Comment by MikeMcC399** [comment]
@dsarkar 

It would be quite simple to correct the URL for this situation, for instance, in the [release/2.23.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.23.x) branch, however I do not want to go ahead with a PR unless I get feedback that you want a PR. Also, at the moment, the issue has not been logged in Jira.

**Comment by MikeMcC399** [comment]
@dsarkar 
>  we will have a look at the FAQ link issues.

I guess it is probably too late now for the 2.23 release and the issue still seems not to be mirrored to Jira.

The list of articles in the FAQ section [#eu_dcc](https://www.coronawarn.app/en/faq/#eu_dcc) will be even longer when 2.23 is released and the answer to the problem of a vaccination certificate already registered will still not be found in that section. [#hc_already_registered](https://www.coronawarn.app/en/faq/results/#hc_already_registered) is the article which specifically deals with this issue.

**Comment by dsarkar** [comment]
@dsarkar Thanks for pinging.

**Comment by MikeMcC399** [comment]
@dsarkar 
It seems that nobody has looked at this since your last response a month ago.

**Comment by MikeMcC399** [comment]
- PR https://github.com/corona-warn-app/cwa-app-android/pull/5310 submitted to resolve this issue.

**Comment by MikeMcC399** [comment]
- Due to the planned used of the FAQ anchor link `#hc_already_registered` PR https://github.com/corona-warn-app/cwa-website/pull/3004 is submitted to add the link to the website test suite.

**Comment by MikeMcC399** [comment]
- PR #5310 is now merged into [release/2.25.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.25.x), so the https://github.com/corona-warn-app/cwa-app-android/labels/Fix%202%2E25 label can be added to this issue.

**Comment by MikeMcC399** [comment]
The fix [Correct FAQ link hc_already_registered (EXPOSUREAPP-13218)](https://github.com/corona-warn-app/cwa-app-android/pull/5310) #5310 is included in the pre-release Android version [v2.25.0-rc.1](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.25.0-rc.1).

**Comment by MikeMcC399** [comment]
I missed checking this issue, since there was no https://github.com/corona-warn-app/cwa-app-android/labels/Fix%202%2E25 label applied to it.

The issue was resolved with the CWA Android 2.25.0 release.
