### ISSUE TITLE
Mention changes in release commits (Best practice)

### ISSUE THREAD

**Issue by corneliusroemer** [corona-warn-app/cwa-app-android#511]
You're not abiding by best practices when you're not mentioning changes in your release commits.

Please mention:
- Which bugs were fixed
- Which new features are enabled
- other noteworthy points

Otherwise public testers won't be able to verify fixes and test new features before they go live, swamping you with error reports.

<img width="1076" alt="Screenshot 2020-06-16 at 11 17 12" src="https://user-images.githubusercontent.com/25161793/84756529-31f75e00-afc3-11ea-95ac-cd61528853dd.png">

**Comment by tkowark** [comment]
Hi @corneliusroemer , thanks for the suggestion. We'll discuss with the dev team. In the meantime, could you kindly select the enhancement template for suggestions? Just makes searching for us a bit easier. Thanks a lot in advance!

**Comment by corneliusroemer** [comment]
Thanks!
And it'd be great if you also considered adding apk's for releases, so that we, the tech public, can help you spot problems early on, before rollout.

**Comment by tkowark** [comment]
You mean like the ones mentioned in #514 ? (just making the link explicit ;) )

**Comment by corneliusroemer** [comment]
For example, or the location permission issue that has led to misunderstandings. Or we could have a list of incompatible devices ready so that people don't waste time trying and get frustrated. And have troubleshooting information ready for various error messages.

**Comment by corneliusroemer** [comment]
If I see it correctly, version bump 1.0.3 was again not accompanied by any meaningful commit message. I thought providing meaningful commit messages/changelogs was Git101 - why don't you implement it? https://github.com/corona-warn-app/cwa-app-android/pull/663

**Comment by jakobmoellersap** [comment]
Release Notes provided in https://github.com/corona-warn-app/cwa-app-android/releases/tag/1.0.3

**Comment by tkowark** [comment]
Since release notes are now provided in the release description, we're going to close this issue. Of course, if future releases deviate from that best practice again, we are thankful for a friendly reminder. Thank you very much for spotting such seemingly small issues that make a large difference with regards to transparency.
