### ISSUE TITLE
problem with unofficial ROM based on microG

### ISSUE THREAD

**Issue by ralxxx** [corona-warn-app/cwa-app-android#5112]
- Device name: FP3 - Fairphone 3
- Android version: none - ungoogled /e/ v0.23-q based on Android 10
- App version: CWA v2.21.1

## Describe the bug

I am running the Corona-Warn-App on an ungoogled phone based on the Android 10.
The system is called /e/OS,  a Lineage derivative with nicroG replacing the Google Framework. 

MicroG services is used in version v0.2.24.214816.1

Since the latest update of Corona-Warn-App I am notified that my system is rooted (which is not the case). There must be a misperception. The system is not rooted but not running Google's Android.
  
## Steps to reproduce the issue

- Install /e/OS v.023 from https://doc.e.foundation/devices on any compatible device
- Install CWA 2.21.1 from the built-in appstore

## Expected behaviour

...CWA is running in a flawless manner as on any officially "googled" Andoid deivces 

![316-CWA-isnotrooted](https://user-images.githubusercontent.com/36100882/164784285-76de4a66-3152-4577-a7e5-3a69cf7b3c9b.jpg)

**Comment by ralxxx** [comment]
Issue reported as well to microG: https://github.com/microg/GmsCore/issues/1709

**Comment by MikeMcC399** [comment]
@ralxxx 

According to https://github.com/scottyab/rootbeer/issues?q=is%3Aissue+is%3Aopen+%2Fe+fairphone there is a known issue (147 - "detect non rooted device as rooted device") with [RootBeer](https://github.com/scottyab/rootbeer/) reporting root on Fairphone 3 with "/e/OS". There is also a proposed solution in (PR 192 - "checkForDangerousProps: only return true if both props have a bad value") in that repository.

If you tap on "Meldung bis zum nächsten Update unterdrücken" in CWA you will not be bothered by the message until the next update. The "Sicherheitshinweis" is just a warning. It does not block any functions of the app.

> Issue reported as well to microG: [microg/GmsCore#1709](https://github.com/microg/GmsCore/issues/1709)

@bubu wrote in https://github.com/microg/GmsCore/issues/1709#issuecomment-1106919470 that this is not a microG issue. He also mentioned the above RootBeer issue.

**Comment by MikeMcC399** [comment]
- This topic was also mentioned in https://github.com/corona-warn-app/cwa-app-android/issues/4268#issuecomment-962694162

**Comment by tcecyk** [comment]
what release channel are you on, dev or stable?

/e/ is doing userdebug builds on "dev" (it gets debated now and then), just like LineageOS. The userdebug builds offer a root option via adb (what rootbeer is tripping up on in the prefs). So technically it is rooted, as you can get a root shell.
