### ISSUE TITLE
Does CWA support Material You?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-android#5118]
A Twitter user asked whether CWA support Material You with the latest version 2.21 on Android 12.
He expected that e.g. the buttons turn to the accent color, but they staid blue.
So the question was: "Does CWA support Material You, if yes, how can I turn the support on?"

**Comment by dsarkar** [comment]
@Ein-Tim Will come back to you.

**Comment by MikeMcC399** [comment]
App Information > New Features on 2.21.1 says;

"**Android 12 and Material Design 3**

"The Corona-Warn-App has been optimized to run on Android 12. It now also supports Material Design 3."

https://m3.material.io/ covers Material Design 3
https://material.io/blog/announcing-material-you announces Material You

It looks like the CWA colours are hard-coded in https://github.com/corona-warn-app/cwa-app-android/blob/main/Corona-Warn-App/src/main/res/values/colors.xml


It would be interesting to know what visual changes can be expected in the app when it is running under Android 12 using Material Design 3. Perhaps this should be a separate question?

**Comment by mtwalli** [comment]
@Ein-Tim I think the user means  `dynamic themes`. and the answer is no CWA does not support dynamic themes. Our UX theme decided to keep the static look and feel of CWA

**Comment by Ein-Tim** [comment]
@MikeMcC399 Thanks for the feedback! Relaying this information.
