### ISSUE TITLE
Visual changes for Android 12 / Material Design 3

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#5119]
## Avoid duplicates
* [X] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Question is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Question has not already been asked in another issue<br>follows on from https://github.com/corona-warn-app/cwa-app-android/issues/5118

## Your Question

App Information > New Features on 2.21.1 says;

"Android 12 and Material Design 3

"The Corona-Warn-App has been optimized to run on Android 12. It now also supports Material Design 3."

What are the expected visual changes in CWA when it is running under Android 12 using Material Design 3?

## References

https://m3.material.io/ covers Material Design 3

**Comment by mtwalli** [comment]
Coloring and typography did not change much, but here what you can notice: 
1- Bottom nav bar has been adapted except that FABs are kept circular
2- Dialogs are rounded 
3- Button are rounded 
4- Dialogs and overflow menus backgrounds have slightly different colors 
5- The upgrade came with some fixes also such as 
   1. switches in Dark mode
   2. Date input dialogs in edit mode
6- Toolbar is a little bit different in light mode

Some UI elements have still MD2 style based on UX team input and this can be notices in:
1- FABs
2- Cards shadows
3- Button toggle groups
4- Toolbar height 
5- Typography 

Again we don’t support dynamic themes

**Comment by MikeMcC399** [comment]
@mtwalli 

Thank you for the detailed answer about the UI changes! 👍🏻 

It would be helpful if the Android screenshots for version 2.21 on https://www.coronawarn.app/en/screenshots/#android_screenshots were actually all from this version. Some screenshots, like https://www.coronawarn.app/en/screenshots/#android_cards don't show the UI from 2.21. There are even screenshots from iOS shown in the Android section.

Closing this issue, as the question has been answered.
