### ISSUE TITLE
rapid test result does not display any name/date of birth

### ISSUE THREAD

**Issue by xenel** [corona-warn-app/cwa-app-android#5136]
- App version: 2.21.1

## Describe the bug
Since one of the last updates, the app does not show any personal data with the test result. It only shows the result "negative". In addition to that the timestamp (increasing timer counting up from the time of transmission) is missing. - It also shows some strange text indicating something with a "PCR" test was done, even though it's a rapid test.

The test result was transmitted with the rapid test portal (schnelltestportal.de).
The option "Testergebnis in CWA anzeigen (Namentlicher Testnachweis) (...)" was selected and the QR code was scanned successfully by the user.

Screenshots (not showing name, date of birth, timestamp):

(please pay attention to the app showing some text like "Ihr PCT-Test wurde hinzugefügt". Its a rapid test.)

![photo5429627502063632206](https://user-images.githubusercontent.com/18738322/165826749-af19fe30-912e-4198-afbe-9fb0187293c1.jpg)
![photo5429627502063632207](https://user-images.githubusercontent.com/18738322/165826754-6b27fadd-8dbf-4b43-9d1c-509c9a226d62.jpg)
![photo5429627502063632205](https://user-images.githubusercontent.com/18738322/165826755-76b5e64e-e21c-445e-bc07-d1dc7cb1d21e.jpg)

## Expected behaviour

We would expect to see the name of the user as well as the date of birth.
Also some kind of indication how "old" the rapid test is has been there in the past.

**Comment by xenel** [comment]
The help for the selection option in the rapid test portal (schnelltestportal.de) is also claiming what we expect to see:

Der Getestete willigte außerdem in die Übermittlung von Name und Geburtsdatum an die App zur Anzeige des Testergebnisses in der App als namentlicher Testnachweis ein. Dem Getesteten wurden Hinweise zum Datenschutz ausgehändigt.

**Comment by Ein-Tim** [comment]
Will be fixed in the next version: https://github.com/corona-warn-app/cwa-app-android/pull/5132

**Comment by xenel** [comment]
Thanks a lot for that hint! I don't understand everything technically, but I hope the new version will be released soon. I will close this one, apparently its a duplicate (didnt recognize #5132 when searching for 'name', 'timer', ...).
