### ISSUE TITLE
Stop preventing Screenshots

### ISSUE THREAD

**Issue by MrKrisKrisu** [corona-warn-app/cwa-app-android#517]
Your Question

* Source File: https://github.com/corona-warn-app/cwa-app-android/blob/master/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt
* Line(s): 101
* Question: Why do you actively prevent Android Users from taking Screenshots from the App? I don't think it's necessary.

**Comment by Lucurus** [comment]
Possibly related to #41

**Comment by uschindler** [comment]
Siehe #77 für eine Lösung.

**Comment by MrKrisKrisu** [comment]
Same question, but 2 minutes earlier created. 
See #41 and #77
