### ISSUE TITLE
Simple Testfunction

### ISSUE THREAD

**Issue by JProof** [corona-warn-app/cwa-app-android#518]
## Current Implementation

It is not quite clear if the app is recording. For a better feedback "Yes, the app is running and recording" I can imagine that counter or similar
"you met *n smartphones with the app installed".

Es ist nicht ganz klar ersichtlich ob die die App aufzeichnet. Für ein besseres Feedback "Ja, die App läuft und zeichnet auf" kann ich mir vorstellen, dass counter oder ähnliches
"du hast *n smartphones mit installierter App getroffen".

## Suggested Enhancement
I would like to have an indication/test function that I was just in contact with another Corona App user smartphone.

This function can be limited in time. This means
* Test button [Test record]
* Note to user "The Smartphone user in your area must also have activated the button on his Smartphone".
* Afterwards a short averaging to both smartphones "You have recognized each other, the recording of the contacts works".
* Test function switches off
* or switches off automatically after 3 minutes

Ich möchte gern eine Anzeige/Testfunktion, dass ich gerade in Kontakt mit einem anderen Corona-App-Benutzer-Smartphone war.

Diese Funktion kann gern zeitlich begrenzt werden. Das bedeutet
* Test-Button [Test-Record]
* Hinweis an User "Der SmartphoneBenutzer in deiner Nähe muss auf seinem Smartphone den Button auch aktiviert haben"
* Danach erfolgt eine kurze Mittelung an beide Smartphones "Ihr habt euch erkannt, die Aufzeichnung der Kontakte funktioniert".
* Test-Funktion schaltet sich ab
* oder schaltet sich automatisch nach 3 Minuten ab

## Expected Benefits
Background is that I am allowed to install this app at several neighbours.
To check that the app is recording, I would like to hold my smartphone against the smartphone of the neighbour.
I would like to be able to tell the neighbour, yes is installed, yes works, look at it records.

Maybe this option for more technically minded people ..not to scare normal users.

Hintergrund ist der, dass ich diese App bei diversen Nachbarn installieren darf.
Um zu überprüfen, dass die App aufzeichnet, möchte ich gern mein Smartphone an das Smartphone des Nachbarn halten.
Dem Nachbarn möchte ich sagen können, ja ist installiert, ja funktioniert, sieh her es zeichnet auf.

Vielleicht diese Option für eher technisch interessierte Personen ..um keine normal-anwender zu erschrecken.

**Comment by tomjschwanke** [comment]
Die Zahl der begegneten Geräte kann nicht abgerufen werden #492

**Comment by JProof** [comment]
Okay, danke!

Die Testfunktion halte ich dennoch für sinnvoll ;-)

**Comment by corneliusroemer** [comment]
Good point and useful in conjunction with my "logging" feature request.

**Comment by tobidwest** [comment]
> Die Zahl der begegneten Geräte kann nicht abgerufen werden, da die API das nicht hergibt #492

Vielleicht kann die App stattdessen einfach anzeigen, ob mindestens eine Begegnung in den letzten X Zeiteinheiten stattgefunden hat?

**Comment by JProof** [comment]
@tobidwest 
Das ist eine gute Idee, dann würde der Anwender auf Dauer feststellen können, dass die App seinen Dienst tut.

Vielleicht sollte man den "Marketing-Aspekt" hier nicht ganz außer Acht lassen. Haben mehrere Leute die App in der Hand "Schau mal, meins geht" : "..ja, meins auch".

Natürlich ist die CWA kein App zum herumspielen, jedoch sorgt die spielerische Benutzung (gimmicks) der App für mehr Akzeptanz.

This is a good idea, then the user would be able to see in the long run that the app does its job.

Maybe the "marketing aspect" should not be completely ignored here. If several people have the app in their hands "Look, mine works" : "..yes, mine too".

Of course, the CWA is not an app to play around with, but the playful use (gimmicks) of the app will increase acceptance.

**Comment by mueslo** [comment]
I agree. Something like "Last encounter: 5 minutes ago" would help people see that it is working properly. 

The stats nerd in me would even love to see a time-resolved statistics page. Maybe you would see that you got on the tram this morning and had lots of encounters. While you cannot identify others, and hence cannot count how many other devices you encountered, just plotting the amount of other devices' public keys you got over time will still tell you how "vulnerable" you were, and when.

**Comment by mtbsteve** [comment]
@JProof you may try Beacon Scope https://play.google.com/store/apps/details?id=com.davidgyoungtech.beaconscanner&hl=de
it will show the exchanged IDs of all devices running the app around you and you can see if the app works.

**Comment by JProof** [comment]
Vielen dank für deine Antwort und deinen Vorschlag!

Deine vorgeschlagene App habe ich soeben auf 2 Geräten getestet.  Der Beacon-Tester arbeitet in einem Gerät, in dem anderen Gerät eben nicht.

Ich schlüpfe hier in die Rolle eines "Verbrauchers".  Und möchte nur sicherstellen, dass die CWA wirklich läuft und aufzeichnet! 
Der Anwendungsfall den ich Eingangs beschrieb: 
Ich installiere die App bei den Nachbarn oder wem auch immer aus dem Bekanntenkreis. Sie erwarten eine Aussage "Ja, läuft alles". Diese Aussage kann ich im Augenblick nicht treffen. Es fehlt mir und wenn ich die anderen Tickets lese,  weiteren Personen ein Feedback von der App "zeichnet auf..."

Noch einmal zusammengefasst ohne auf alle anderen Tickets zu referenzieren.

Ein Feedback aus der App heraus: 
* "zeichnet auf" 
* "hat vorhin aufgezeichnet"
* "gestern auch.."

oder der thread #532 in dem sinngemäß zur Sprache kam "Meldung im Display, app läuft nicht richtig"

Thank you very much for your answer and suggestion!

I have just tested your proposed app on 2 devices.  The Beacon Tester works in one device but not in the other.

I take on the role of a "consumer" here.  And I just want to be sure that the CWA really runs and records! 
The use case I described at the beginning: 
I install the app at the neighbours or whoever from my family and friends. They expect a statement, "Yes, everything is going well." I can't make that statement right now. I miss it and when I read the other tickets, more people get feedback from the app "records on..."

Summarized once again without referencing all other tickets.

A feedback from the app: 
* "is recording" 
* "has recorded earlier"
* Yesterday, too... *

or the thread #532 which said "Message on display, app not running properly"

**Comment by tkowark** [comment]
Just to keep the repository more manageable and discuss ideas only in one place, I'd like to point future discussions on that enhancement idea to corona-warn-app/cwa-documentation#270.

I hope that's ok for everybody. Since this idea would be an addition for both apps, the discussion is also moved to the central documentation repository.

**Comment by corneliusroemer** [comment]
@tkowark Alright, but we should try to not loose the very valid points raised in discussions. So we will now not only read the original issue report but also the referenced issues.

**Comment by JProof** [comment]
Yes, thats ok for me.
Thank you 

Am June 17, 2020 11:50:30 AM UTC schrieb Cornelius Roemer <notifications@github.com>:
>@tkowark Alright, but we should try to not loose the very valid points
>raised in discussions. So we will now not only read the original issue
>report but also the referenced issues.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/corona-warn-app/cwa-app-android/issues/518#issuecomment-645326640

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by corneliusroemer** [comment]
> @JProof you may try Beacon Scope https://play.google.com/store/apps/details?id=com.davidgyoungtech.beaconscanner&hl=de
> it will show the exchanged IDs of all devices running the app around you and you can see if the app works.

This is extremely helpful for testing that a Beacon is sent. Thanks for the suggestion @mtbsteve

**Comment by yorickreum** [comment]
Interesting showcase: https://twitter.com/merlinchlosta/status/1273293511803244546 (sadly in German). I would really like to see a feature like this. For me, the live accumulated number of received beacons from other devices would be enough (to monitor the functionality). This should be possible even if the API does not support it (yet), just by monitoring Bluetooth directly.

**Comment by JProof** [comment]
@tkowark i can not find  corona-warn-app/cwa-documentation#270 
is it possible to send me the url of that ticket?

**Comment by JProof** [comment]
okay, found under https://github.com/corona-warn-app/cwa-wishlist/issues/5

**Comment by tkowark** [comment]
sorry about that. I thought that Github redirects these links automatically 😒
