### ISSUE TITLE
No more exposure checks are possible, limit is already reached

### ISSUE THREAD

**Issue by Emi220** [corona-warn-app/cwa-app-android#5182]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name: Galaxy A40
- Android version: 11
- App version: 2.22.1
- ENF version: 18221514000

## Describe the bug

Hey!
A couple of days ago I opened the app after a long time of not using it. It now shows me that my last update was in June and whenever its trying to update I get a message about how i already reached the limit. This issue persisted over the last 3 days.
I also have discovered that I dont have the Google option under Settings > Google > ...   so I dont know how to send an exposure log.

Kind regards
Emi220

**Comment by MikeMcC399** [comment]
@Emi220 

The FAQ https://www.coronawarn.app/en/faq/results/#API39508 discusses the problem, but it probably won't help you much.

You may need to reset the app. If it is saying the last update was in June, that is almost one year ago. It might be helpful if you could add a screenshot. Also check that the phone is currently showing the correct date/time.

I see that you also reported this problem in https://github.com/corona-warn-app/cwa-app-android/issues/1459#issuecomment-1126905868.

> I also have discovered that I dont have the Google option under Settings > Google > ... so I dont know how to send an exposure log.

I'm not sure what you mean by this. Are you saying that there is no Google option under Settings? There is not a second option under "Google" which is also labelled "Google" . There should however be a "COVID-19 Exposure Notifications" option. Is that what you mean is missing? Normally you should be able to view the exposure checks through:
(Android) Settings > Google > COVID-19 Exposure Notifications > three-dot menu > Exposure checks

**Comment by Emi220** [comment]
Heres the message I get when trying to update:
![Screenshot_20220515-115459_Corona-Warn](https://user-images.githubusercontent.com/105585214/168474262-ff1daa9e-ba8f-40ae-8554-53c58417bb33.jpg)
 The details:
![Screenshot_20220515-115503_Corona-Warn](https://user-images.githubusercontent.com/105585214/168474281-7be5b5c6-f863-4c18-837e-080c5df7625c.jpg)

The date and time on my phone are set automatically.

I finally found out where to acess these exposure checks! Seems like I misunderstood the whole thing.
Here they are:
[all-exposure-checks.txt](https://github.com/corona-warn-app/cwa-app-android/files/8695008/all-exposure-checks.txt)

**Comment by MikeMcC399** [comment]
@Emi220

Thank you very much for the further details. That is very helpful.

Your [Exposure checks](https://github.com/corona-warn-app/cwa-app-android/files/8695008/all-exposure-checks.txt) log file shows one entry:

`[{"timestamp":"26 June 2022, 18:37","keyCount":45898,"matchesCount":0,"appName":"Corona-Warn","hash":"\/Ax09xygNDVolr0LVCVxO+kOwPJ2pu+vRtx5slyhHM0="}]`

The time stamp is 26 June 2022. That means that at some point your phone was running with an incorrect future date. This is known to cause a problem.

There is an open issue reported https://github.com/corona-warn-app/cwa-app-android/issues/4303 "Risk Warning stops after checking future dates" with the version 2.12.2 in October 2021.

Resetting the app is your best option at this time.

**Comment by Ein-Tim** [comment]
When you reset the app please note that all your stored certificates, as well as contact journal entries, registered test results and check ins will be deleted!

**Comment by MikeMcC399** [comment]
- The problem is also described in the open issue https://github.com/corona-warn-app/cwa-app-android/issues/3629

**Comment by MikeMcC399** [comment]
To remove the exposure check with the wrong time-stamp you need to uninstall and re-install the app. I'm not sure if this is completely necessary to get working again, but it is the only clean solution.

We are still waiting for feedback from the developer team on these related issues.

**Comment by Emi220** [comment]
Yep resetting the app works
Thanks guys!
