### ISSUE TITLE
Multi-tenancy / multi-user support for business use cases

### ISSUE THREAD

**Issue by motmot80** [corona-warn-app/cwa-app-android#520]
## Feature description
Having multi-tenancy support would enable multi-user scenarios on shared devices. F.e. mobile production devices.

## Problem and motivation
Business or production devices used by multiple users could not contribute reliable data. 
It should be possible having multiple users per device - like having multiple apps on multiple devices.

## Possible implementation
Intent and user interface to change active users. 
For example with anonymous user ids.

1. Inform the user having used the device during a possible infection time window 
2. Inform all users having used the device if one user was possible affected

**Comment by RAnders00** [comment]
Doesn't android have a built-in functionality to switch user accounts that can be used for this?

**Comment by tobidwest** [comment]
> Doesn't android have a built-in functionality to switch user accounts that can be used for this?

It does. 

@motmot80 You can check [this guide](https://support.google.com/nexus/answer/2865483?hl=en), it applies to most (stock) android devices.

**Comment by tobidwest** [comment]
> Inform all users having used the device if one user was possible affected

Doesn't this violate the user's privacy and their right to informational self-determination?

**Comment by tkowark** [comment]
Thanks for the proposal. 

As @tobidwest already noted sharing that information without the user's consent would violate the users' rights.

As for the general multi-user approach, this is not planned to be implemented in Corona-Warn-App but should be handled automatically through the multi-user capabilities of the respective devices (thanks @tobidwest @RAnders00 ).

Therefore, I would close this issue.

Best regards,
TK
Corona-Warn-App Open Source Team
