### ISSUE TITLE
Explaining why android phones require location access

### ISSUE THREAD

**Issue by EikeStein** [corona-warn-app/cwa-app-android#524]
I noticed that quite a few reviews are complaining about the access to location services (Standortzugriff) prompt they receive when opening the app. I know that the prompt is misleading, as the API-Access is probably required for accessing blutooth or Wifi state, but this should be clearly stated somewhere (FAQ, App description in the Play Store, inside the App before the prompt appears,...). Otherwise people might think the App does use GPS or other precise location mechanisms after all.

**Comment by kurthuwig** [comment]
Location access is required for Bluetooth LE access. IIRC it is to emphasize that you can locate devices because there are means BLE beacons with known locations.

**Comment by EikeStein** [comment]
@kurthuwig I know, but this should be explained to the users, otherwise they may think the app tracks their location after all (the prompt they receive through android is misleading)

**Comment by EikeStein** [comment]
Sorry duplicate

**Comment by corneliusroemer** [comment]
No, don't be sorry! You're raising a valid point that SAP is refusing to address (thus far). 

It got closed because maintainer doesn't realise it's a communication issue rather than a technical one.
But yes, let's have a canonical open issue at #519 and reopen if that one gets closed.
