### ISSUE TITLE
Android app does not offer to reissue certificate while iOS app does

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-android#5261]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: iPhone 6s / Huawei P Smart 2019
- OS version: iOS 15.5 / Android 10
- App version: 2.23.2 / 2.23.1 

## Describe the bug

I have imported [this](https://github.com/denysvitali/covid-cert-analysis/blob/master/RESULTS.md#samplesbrandenburgtesttxt) test certificate into the iOS & Android CWA apps.
While the iOS app, as intended, offers me the possibility to reissue the certificate, the Android app doesn't give me this possibility. 

## Steps to reproduce the issue

1. Import a technically expired certificate into the iOS & the Android CWA apps
2. Observe that the iOS app offers to reissue the certificate, while the Android app does not

## Expected behaviour

I'd say the behavior of the iOS app is intended & the one of the Android app faulty. That's why I am opening this issue here in the Android repo. 

## Screenshots

| iOS | Android |
|---|---|
| ![IMG_0181](https://user-images.githubusercontent.com/67682506/172056016-8224936e-5463-4dca-88e0-49810190dba6.JPG) | ![IMG_0183](https://user-images.githubusercontent.com/67682506/172056019-ea0cb354-e580-4222-8265-94be8cae2de4.JPG) |

**Comment by MikeMcC399** [comment]
@Ein-Tim 

How long did you wait after installing CWA 2.23?

It seems that there may be a delay after the installation / upgrade to CWA 2.23 Android before it offers to renew a certificate.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

I added the certificate instantly after updating to version 2.23 of CWA.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

I suggest you check back after waiting 24 hours.

**Comment by Ein-Tim** [comment]
@MikeMcC399 I will. Even if I see the option after 24 hours, I'd still consider this as a bug and would follow up in another issue.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

CWA 2.22 uses CCL version 2.1.4
If you update to CWA 2.23 it initially stays at the same CCL version 2.1.4. Within 24 hours, CCL updates to version 3.0.1.

If you do a clean install of CWA 2.23 then it immediately uses CCL 3.0.1 and it will immediately offer to reissue a certificate.

(See https://github.com/corona-warn-app/cwa-app-ccl/issues/49#issuecomment-1077683566 for reference to 24 hour delay.)

I don't think that this is a bug, however there is no reference to the delay in any FAQs.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

You're right, I remember! I wonder why the behavior under Android differs to the one under iOS.

**Comment by Ein-Tim** [comment]
@MikeMcC399 As you said, now the app offers me to reissue the certificate. Very strange. But probably intended.
