### ISSUE TITLE
Certificate Reissuing Consent Screen has no "Further Data" indicator for "Additionally transferred certificates"

### ISSUE THREAD

**Issue by jkrwdf** [corona-warn-app/cwa-app-android#5264]
## Avoid duplicates
* [X] This enhancement request has not already been raised before
* [X] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [X] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation
In the screen to reissue expiring/expired certificates, there is an information about additionally transferred certificates. 
In the Android version, it is just a line with a text (in German for example "Zusätzlich übermittelte Zertifikate". This line does not have any indication that it is tappable and behind it there is more data to show.

![image](https://user-images.githubusercontent.com/5329491/172373357-7733ca0f-b60d-4b21-be80-5aefe3b8fb2b.png)

## Suggested Enhancement
At other locations in the Android version, and at that same location in the iOS version, CWA shows the "Arrow symbol" to indicate that more data is present. 

## Expected Benefits
I personally believed that the actual visualization means "There are no additional certificates to transfer" (I considered the text as header of an empty list). With the arrow symbol, I would have tapped.

---
Internal Tracking ID: [EXPOSUREAPP-13313](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13313)

**Comment by larswmh** [comment]
Thanks for your enhancement request @jkrwdf. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-13313](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13313)

---
Corona-Warn-App Open Source Team

**Comment by svengabr** [comment]
We are currently using this pattern in several places in the app (Link to Data Privacy Statement, ...) and we are now looking into a solution that's consistent throughout the app.

**Comment by jkrwdf** [comment]
Thanks you.

For a completeness of my report, I present two screenshots which show the indicator:

First the same location on the Apple iOS platform:

![image](https://user-images.githubusercontent.com/5329491/172772636-1870b38b-3c86-40dc-8d5d-ec36656d3658.png)


Second another location in the Android version:

![image](https://user-images.githubusercontent.com/5329491/172772604-5b320f6b-f707-497e-a025-6964518a1acc.png)

**Comment by svengabr** [comment]
@jkrwdf 

The UX team has already prepared something where I think we should be fine to move on. There is a scribble already available for preview but the final implementation could be a bit different.

Just a heads up that the team is already on it.

![2022-06-09 12_33_12-COVID19_Master_2 20 – Figma](https://user-images.githubusercontent.com/4686874/172827527-82f7d1d8-62b7-4a75-9843-8e82231e6ccb.png)

**Comment by mtwalli** [comment]
PR: https://github.com/corona-warn-app/cwa-app-android/pull/5544
