### ISSUE TITLE
Using back/forward buttons when registering manual PCR test crashes app

### ISSUE THREAD

**Issue by pief** [corona-warn-app/cwa-app-android#5274]
When manually registering a PCR test result using a TAN, if AFTER the screen where the begin of symptoms was specified one uses the phone's back button and then the forward button, the app crashes with an IllegalStateException "No valid test available to authorize submission".

---
Internal Tracking ID: [EXPOSUREAPP-13368](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13368)

**Comment by pief** [comment]
![Screenshot_20220611-093906_Corona-Warn](https://user-images.githubusercontent.com/2843983/173179576-1852d4fb-11a9-4a84-a829-38fff0c57639.jpg)

**Comment by larswmh** [comment]
Thanks for your report @pief. We have created an internal ticket for it and will raise this topic internally. Can you provide us the information about the following?
- Device name
- OS version
- App version

Thank you!

Internal Tracking ID: [EXPOSUREAPP-13368](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13368)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
- PR #5323

**Comment by Ein-Tim** [comment]
FYI PR https://github.com/corona-warn-app/cwa-app-android/pull/5338 reverts the PR mentioned above.

**Comment by mtwalli** [comment]
This issue should have be fixed by #5474

**Comment by mtwalli** [comment]
@pief  The issue has been resolved in 2.25, could you please check and close the issue ?

**Comment by pief** [comment]
I'd love to, but I'd need a TAN to be able to do so...

**Comment by mtwalli** [comment]
I will close it for now, feel free to re-open it, if you experience it again
