### ISSUE TITLE
Risikostatus seit vorgestern Abend nicht mehr aktualisiert

### ISSUE THREAD

**Issue by Insider6787** [corona-warn-app/cwa-app-android#5275]
Siehe oben. Ich habe die aktuellste Version der CWA, an meinen Smartphone-Einstellungen (Samsung, Android) habe ich ebenfalls nichts verändert.
Die Empfehlungen aus den FAQ haben das Problem genau so wenig gelöst wie ein Neustart des Smartphones.

Bitte um Hilfe.

---
Internal Tracking ID: [EXPOSUREAPP-11805](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11805)

**Comment by Ein-Tim** [comment]
Hey, wie bist du mit dem Internet verbunden?

**Comment by Insider6787** [comment]
Wenn ich zu Hause bin, über WLAN. Ansonsten mobil.

**Comment by Ein-Tim** [comment]
@Insider6787 Hast du schon mal versucht, die App neu zu starten wenn du im WLAN bist? Hilft das?

**Comment by Insider6787** [comment]
Leider nein.

**Comment by Insider6787** [comment]
Sorry, dass ich mich jetzt erst melde. Inzwischen funktioniert die Status-Aktualisierung wieder, das Issue hat sich also erledigt. Danke allen für die Hilfe.

**Comment by Ein-Tim** [comment]
Please close this issue @larswmh / @dsarkar.

**Comment by dsarkar** [comment]
Guten Morgen @Insider6787, ok, vielen Dank für die Rückmeldung! Wir schliessen damit das GitHub-Issue, und sollte das Problem wieder auftauchen bitte das Ticket wieder öffnen; oder wenn Sie ein anderes Problem berichten oder eine Idee mitteilen möchten, usw, würden wir es begrüssen, wenn Sie hier auf GitHub ein entsprechendes Issue öffnen. Vielen Dank, dass Sie hier mitmachen, Viele Grüsse, DS


---
Best wishes, DS

---
Corona-Warn-App Open Source Team
