### ISSUE TITLE
Twitter Report: "Fertig" button on selecting onset of symptoms does nothing

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-android#5276]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Samsung S10e
- Android version: Android 12 with OneUI 4.1
- App version: 2.23.1

## Describe the bug

The button on the screen shown in the screenshot below doesn't have any action when clicked on it after entering the onset of symptoms into the calendar view. 

<img src="https://user-images.githubusercontent.com/67682506/173206035-71876e58-ded5-40bb-b0d6-d6b8cc6ea793.jpeg" width="300">

## Steps to reproduce the issue

1. Register a positive RAT in the app
2. Step through the warn others process until you see the screen which asks to enter onset of symptoms
3. Enter the onset of symptoms
4. Click on "Fertig" and notice that nothing happens

## Expected behaviour

The button "Fertig" should have an action and continue to the next screen.

## Additional context

This bug report is based on the feedback I received from a user via Twitter DM.  

---
Internal Tracking ID: [EXPOSUREAPP-13369](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13369)

**Comment by larswmh** [comment]
Thanks for forwarding this Twitter report @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-13369](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13369)

---
Corona-Warn-App Open Source Team

**Comment by Ein-Tim** [comment]
@mlenkeit Yep, you're right. Thanks!
