### ISSUE TITLE
installer hangs on Linageos 17.1/Android10

### ISSUE THREAD

**Issue by schonma** [corona-warn-app/cwa-app-android#528]
## Describe the bug

Installation hangs on Android10/Linageos17.1

## Expected behaviour

Install or at least display an error message 

## Steps to reproduce the issue

LinageOS 17.1 on Samsung S5NeoLTE

## Technical details
Android 10, Linageos 17.1

**Comment by makepanic** [comment]
It works fine on a ONEPLUS A3003 with LineageOS 17.1 (June 4, 2020).

Have you tried different things like rebooting the phone before trying to install it?

**Comment by tkowark** [comment]
We officially only support Android versions with installed Google Play services and installation via Google Play Store (see [FAQ](https://www.coronawarn.app/en/faq/#application)). Please refer to #75 for a community driven initiative for removing that dependency.

Best regards,
TK
Corona-Warn-App Open Source Team

**Comment by uschindler** [comment]
I can also confirm that the App installs perfectly from Google Play Store on LineageOS 16 and 17. As noted already you need Google Play Services, but that's what Lineage's option to install Gapps are for.
