### ISSUE TITLE
Direct apk Download from Webpage or Fdroid

### ISSUE THREAD

**Issue by schonma** [corona-warn-app/cwa-app-android#529]
it would be nice to see the cwa-app-andoird in the fdroid store

**Comment by tomjschwanke** [comment]
see #477

**Comment by tkowark** [comment]
As noted by @tomjschwanke , this is a duplicate of #477 and corona-warn-app/cwa-documentation#5. Please refer to these issues for further explanation.

**Comment by corneliusroemer** [comment]
I invite @schonma to contribute to this current issue #514 

The reasons given for not hosting apks on Github so far have not been satisfactory from a community viewpoint.
