### ISSUE TITLE
Strange time format on ID history screen

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-android#5296]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Huawei P Smart 2019
- Android version: 10
- App version: 2.23.2

## Region specific settings

<img src="https://user-images.githubusercontent.com/67682506/175134215-10b2478e-aff4-4f58-85d4-7990f9a886cf.jpg" width="300">

<img src="https://user-images.githubusercontent.com/67682506/175134225-47cdabcf-6520-4397-a740-a21ae6e5f76a.jpg" width="300">

## Describe the bug

The dates on the "ID-Historie" (ID history) screen are really formatted in a strange way, which is normal not used to format times in Germany.

<img src="https://user-images.githubusercontent.com/67682506/175134382-ee555f1a-3bfc-499b-b78d-0c40ea4c6f11.jpg" width="300">

## Steps to reproduce the issue

1. Open CWA
2. Click on the 3 dots in the top right corner
3. Click on "App-Informationen"
4. Click on "Fehlerberichte" 
5. Scroll down and tap on "ID-Historie"
6. See the strangely formatted dates

## Expected behaviour

Formatting of the dates as in the contact journal:

<img src="https://user-images.githubusercontent.com/67682506/175134697-2fd1f63a-5e37-4c71-8bae-f70bfb7707b2.jpg" width="300">

---
Internal Tracking ID: [EXPOSUREAPP-13442](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13442)

**Comment by Ein-Tim** [comment]
I'm really an Android noob, so let me should this be something that is user definable.

**Comment by thorbenkuro** [comment]
@Ein-Tim Thank you for reporting this issue. We created an internal ticket for it.
Internal Tracking ID: [EXPOSUREAPP-13442](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13442)

@MikeMcC399 Thank you for your input on this topic!

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> I'm really an Android noob, so let me should this be something that is user definable.

The format is fixed and it is independent of any user settings:

https://github.com/corona-warn-app/cwa-app-android/blob/82acaf03775bebf24e18d6adac3ad4a43d0914d1/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/ui/upload/history/HistoryItemAdapter.kt#L64

**Comment by Ein-Tim** [comment]
Thank you for the clarification @MikeMcC399!

**Comment by MikeMcC399** [comment]
- PR https://github.com/corona-warn-app/cwa-app-android/pull/5480 changes the format to
https://github.com/corona-warn-app/cwa-app-android/blob/2c614650537abfbc3adc3313f61c355698a7a42c/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/bugreporting/debuglog/ui/upload/history/HistoryItemAdapter.kt#L64

In other words the day and year exchange their previous positions.

**Comment by Ein-Tim** [comment]
@MikeMcC399 Thanks for the update!

@mtwalli Feel free to apply the `Fix 2.27` label to this issue.

**Comment by sapcoder123** [comment]
@MikeMcC399 @Ein-Tim Thanks for the contribution! Should be fixed in the mentioned PR in release 2.27

**Comment by MikeMcC399** [comment]
@Ein-Tim 

I checked in the released 2.27.2 and this issue is fixed.

**Comment by MikeMcC399** [comment]
It's probably too late to fix this, but I am now seeing old timestamps in the ID History

20.01.1970 - 03:26:06

with CWA Android 3.1.1 on Android 11
Locale set to English (United States) or Deutsch (Deutschland)

The year 1970 doesn't make sense.

A new error report sent today had the right timestamp

10.03.2023 - 14:42:25
