### ISSUE TITLE
App is incompatible with Samsung Galaxy J3/Android 5.1.1

### ISSUE THREAD

**Issue by Phoenix616** [corona-warn-app/cwa-app-android#530]
App can't be installed on a Samsung Galaxy J3 (2016) with Android 5.1.1 (the playstore shows incompatible device).

Please find a way to make this app compatible with more older versions/devices as it's not too uncommon for people to not have the latest device and software...

**Comment by s-martin** [comment]
Google provides the API only for version 6 or later (see https://static.googleusercontent.com/media/www.google.com/de//covid19/exposurenotifications/pdfs/Android-Exposure-Notification-API-documentation-v1.3.2.pdf), so the App will not work on Android 5.

**Comment by tomjschwanke** [comment]
see #165

**Comment by Phoenix616** [comment]
There needs to be a workaround for this, unfortunately there are still thousands if not millions of people stuck on older Android versions due to the phone producers not providing updates anymore. Risking their health just because of this is not acceptable.

**Comment by s-martin** [comment]
There is no workaround, only Google can fix provision of the API in earlier versions.

**Comment by tkowark** [comment]
Yes, as stated above, this is a limitation the we cannot work around. Thanks everybody for answering the questions so quickly.

**Comment by Phoenix616** [comment]
Well then that would be the workaround? Surely it's not too hard for Google to fix it...

Also please don't close issues that aren't resolved (especially if they put people's health at risk), that will just lead to more issues of the same kind to pop up as people look for open ones first and people looking for potential issues to work on to not find it as easily.
