### ISSUE TITLE
Missing padding/margin on certificate expiration date. 

### ISSUE THREAD

**Issue by d4rken** [corona-warn-app/cwa-app-android#5300]
Just a small cosmetic issue. Text is missing margins, padding depending on element visibility.

![Screenshot from 2022-06-24 16-21-45](https://user-images.githubusercontent.com/1439229/175555478-91a90d84-3180-4d6f-9677-7bb32e1431b7.png)

## Technical details

- Device name: Pixel 5
- Android version: Android 12
- App version: v2.23.2

## Possible Fix

#5301

---
Internal Tracking ID: [EXPOSUREAPP-13459](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13459)

**Comment by larswmh** [comment]
Thanks for your report and PR @d4rken. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-13459](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13459)

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
Release [v2.25.0](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.25.0) should have resolved this issue according to PR "Remove margin (EXPOSUREAPP-13459)" https://github.com/corona-warn-app/cwa-app-android/pull/5305.
