### ISSUE TITLE
Es werden keine IDs mehr gesammelt

### ISSUE THREAD

**Issue by Flieger-Horst** [corona-warn-app/cwa-app-android#5319]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy A5 (SM-A520F)
- Android version: 10 (Lineage OS 17.1)
- App version: 2.18.1.0

## Describe the bug

Ich benutze die App seit dem Erscheinen der Open Source Version ohne für mich erkennbare Probleme auf diesem Gerät. Vor ein paar Wochen fiel mir auf, dass die App mitteilte, dass ich seit mehreren Tagen keine IDs mehr gesammelt hätte. Das ist mehr als unwahrscheinlich. Ich habe das Ganze eine Weile beobachtet. Es kamen aber offenbar keine neuen IDs dazu.

Ich habe die App deinstalliert und neu installiert. Für 3 Tage habe ich wieder IDs gesammelt. Inzwischen seit 2 Wochen keine mehr. Tägliche Neuinstallation erscheint mir keine Lösung zu sein. Darum dieser Bugreport.

## Steps to reproduce the issue

Ich habe alle angefragten Berechtigungen erteilt. Auch die priorisierte Hintergrundaktivität habe ich erlaubt. Allerdings scheint die Erlaubnis mit jedem Neustart des Telefons zu erlöschen. Ob das allerdings mit den nicht gesammelten IDs in Verbindung steht, kann ich nicht sagen.

Siehe auch https://github.com/corona-warn-app/cwa-app-android/issues/1884

## Expected behaviour

Gesammelte IDs.

**Comment by Ein-Tim** [comment]
@Flieger-Horst 

Nutzt du CCTG von F-Droid?

**Comment by Ein-Tim** [comment]
@Flieger-Horst 

Hier auf GitHub geht es nur um Fehler mit der offiziellen Corona-Warn-App.

Wenn du ein Problem mit CCTG hast, öffne bitte in Zukunft hier einen Issue: https://codeberg.org/corona-contact-tracing-germany/cwa-android

---

In deinem Fall kann ich dir empfehlen mal folgendes zu versuchen:

- Bluetooth aus & wieder anschalten 
- "Risiko-Ermittlung" aus & wieder anschalten.
- Das Gerät neustarten

Es gibt auch auf Codeberg einen FAQ-Eintrag dazu: https://codeberg.org/corona-contact-tracing-germany/cwa-android#my-encounters-page-shows-no-ids-even-though-exposure-logging-is-enabled-what-can-i-do

Generell ist dieser Fehler bekannt, ist aber kaum zu beheben. Siehe diese Issues: https://codeberg.org/corona-contact-tracing-germany/cwa-android/issues?labels=14536

**Comment by Flieger-Horst** [comment]
@Ein-Tim 
> Wenn du ein Problem mit CCTG hast, öffne bitte in Zukunft hier einen Issue: https://codeberg.org/corona-contact-tracing-germany/cwa-android

Ah. Die Seite nannte sich "Open Source Projekt ..." ich dachte, das wäre die F-Droid-Version. Mein Fehler.

> Generell ist dieser Fehler bekannt, ist aber kaum zu beheben.

Schade. Komisch ist nur, dass es so lange problemlos funktioniert hat. Wenn das Problem bekannt ist, macht ein neuer issue wohl keinen Sinn.

Dann mach ich hier zu und probier ich noch ein Weilchen rum. Danke für die schnelle Antwort.
