### ISSUE TITLE
Abschalten von Bluetooth: Unvollständige Anzeige der Benachrichtigung ist irreführend

### ISSUE THREAD

**Issue by Haertma** [corona-warn-app/cwa-app-android#532]
## Describe the bug
Ich beziehe mich auf das deutschsprachige UI, getestet mit Samsung Galaxy S10, Android 10.

Beim Abschalten von Bluetooth erhalte ich eine Benachrichtigung mit dem Text 

_"Benachrichtigungen zu möglicher Begegnung mit Infizierten sind..
Wenn du diese Funktion verwenden möchtest, aktiviere Bluetooth"_

Bei Verwendung von großer (seniorengerechter) Schrift, kann man allerdings nur folgendes lesen:

_"Benachrichtigungen zu möglicher..
Wenn du diese Funktion verwenden möc"_

Wenn man darauf tippt, landet man bei den Einstellungen von Bluetooth mit dem Text

_"Bluetooth einschalten, um Verbindung mit Geräte in der Nähe herzustellen."_

Für ungeübte Benutzer ist m. E. völlig unklar, dass man damit die Kernfunktionalität der Corona-Warn-App deaktiviert.

## Expected behaviour / Possible Fix

Es wäre sinnvoll, wenn die Notification mit einem eindeutigeren Text _beginnen_ würde, der auf jeden Fall angezeigt wird, z. B.

_"Achtung: Corona-Warn-App-Benachrichtigungen zu möglicher Begegnung.."_

**Comment by tomjschwanke** [comment]
Diese Nachricht wird von den Google Play Diensten generiert und kann hier nicht geändert werden

**Comment by uschindler** [comment]
Sehr einfach zusehen, so sieht die Notifcation aus:

![20200616_120929](https://user-images.githubusercontent.com/1005388/84770226-74c33100-afd7-11ea-9eef-b6ab89fc43a3.jpg)

Und wenn man drauf bleibt sieht man woher die kommt - eben nicht von der Corona Warn App und das issue hier ist daher nicht im Aufgabenbereich der App, das müsste man Google melden:

![20200616_120848](https://user-images.githubusercontent.com/1005388/84770239-78ef4e80-afd7-11ea-859a-3b1d2d85a52b.jpg)

**Comment by DE-Max-42** [comment]
Vielleicht währe eine zusätzliche Benachrichtigung der App sinnvoll.
da man so nicht auf die Benachrichtigung von den Google Play Diensten abhängig ist.

Nachteil: Doppelte Nachnichten können auch verwirren.

**Comment by DE-Max-42** [comment]
> Und wenn man drauf bleibt (Finger draufhalten), sieht man sehr schnell woher die kommt

Ja stimmt und es wird klarer was die Benachrichtigung aussagen soll, verständlich ist dies leider nicht. Und auf die Idee lange auf die Benachrichtigung zu tippen kommen erfahrene Nutzer auch nicht unbedingt.

**Comment by uschindler** [comment]
> > Und wenn man drauf bleibt (Finger draufhalten), sieht man sehr schnell woher die kommt
> 
> Ja stimmt und es wird klarer was die Benachrichtigung aussagen soll, verständlich ist dies leider nicht. Und auf die Idee lange auf die Benachrichtigung zu tippen kommen erfahrene Nutzer auch nicht unbedingt.

Trotzdem ist daher dieser Issue durch die netten Kollegen der Corona Warn App in keiner Weise zu berichtigen. Die könnten aber Ihren Kollegen bei Google einen Tipp geben. Wir Enduser können das gar nicht.

Daher ist es gut, dass es das Issue hier gibt! Ich hoffe das Problem wird ordentlich mit Google kommuniziert.

**Comment by uschindler** [comment]
Das gleiche trifft auch für die ähnliche Meldung zu, dass Standortdienste aktiviert werden müssen:

![20200616_120929](https://user-images.githubusercontent.com/1005388/84771816-4e52c500-afda-11ea-94c6-a90829ebcd5f.jpg)

**Comment by DE-Max-42** [comment]
Eine recht gute Möglichkeit ist meiner Meinung nach eine dauerhafte Benachrichtigung zu nutzen die dann eventuelle Probleme oder den Status benutzerfreundlich anzeigt. 

Ähnlich wie @ChillerSargant es in Issue #535 Vorgeschlagen hat.
//github.com/corona-warn-app/cwa-app-android/issues/535#issue-639603307

**Comment by uschindler** [comment]
Ich würde es bevorzugen, wenn bei Problemen eine Notifcation kommen würde durch die App.

Man kann Notifications für Apps disablen. Eine _permanente_ würde dazu führen, dass User genau das tun.

**Comment by Phoenix616** [comment]
> Ich würde es bevorzugen, wenn bei Problemen eine Notifcation kommen würde durch die App.
> 
> Man kann Notifications für Apps disablen. Eine _permanente_ würde dazu führen, dass User genau das tun.

Eine App kann selber entscheiden welches Level eine Benachrichtigung haben kann, für eine permanente würde sich eines anbieten welches kein Icon zeigt und die Benachrichtigung im untersten Bereich der Liste wo sie nicht stört. Dann wird sie auch keiner abschalten.

Optional könnte man dafür auch einfach eine Option in der App selber machen und es dem Nutzer überlassen ob (und wie) die Benachrichtigung angezeigt wird. Das machen eigentlich alle anderen so die permanente Notifications anbieten und halbwegs vernünftig designed sind.

Allerdings sollte sowas wie schon erwähnt in #535 diskutiert werden.

**Comment by DE-Max-42** [comment]
Stimmt, daran daran muss gedacht werden. Auf alle fälle müsste die Permanente Benachrichtigung in einer anderen "Kategorie" seien als die anderen Benachrichtigungen.
 
Wichtig ist halt dass die nur die Permanente Benachrichtigung von dem Nutzer abgeschalten wird. und nicht die anderen. 
Dies stellt sich wahrscheinlich als schwierig heraus da einige dann die Benachrichtigungen für die gestammte App deaktivieren.
Daher wäre es sinnvoll wen die Permanente Benachrichtigung optional ist und Standardmäßig deaktiviert bleibt.

**Comment by DE-Max-42** [comment]
@Phoenix616 Bitte entschuldige ich habe die nachnicht erst gesehen kurz nachdem ich sie gesendet habe.
_**Sorry**_

**Comment by Bbommel** [comment]
Ich hätte ebenfalls einen Änderungswunsch zu dieser Benachrichtigung, die in eine leicht andere Richtung geht. Mir geht es nicht um die Schriftgröße, sondern ich möchte die Benachrichtigung zu fehlendem Bluetooth gar nicht sehen - sonst bekomme ich nämlich immer nachts, wenn ich das Handy auf offline schalte, eine Warnung (vermeintlich) von der Warn-App. 

Die Benachrichtigungskategorie "Benachrichtigung zu möglichen Begegnungen..." in den Play-Diensten möchte ich aber natürlich nicht abschalten, denn wenn es mal einen echten Alarm gibt, dann soll er ja angezeigt werden. Vielleicht kann man das hier noch etwas besser differenzieren - falls das außerhalb der Möglichkeiten der Entwickler der Warn-App liegt, dann sollten die das mit Google klären - ich hoffe, man hat da aktuell einen guten Draht.

Ich kann dafür aber auch ein eigenes Issue aufmachen, wenn ihr meint, dass das zu sehr von der ursprünglichen Frage weg ist.

**Comment by kilianhann** [comment]
Noch ein anderer Aspekt, der ebenfalls diese Benachrichtigung betrifft: 
Als ich beim schnellen aufs Handy schauen "Benachrichtigung zu möchlicher Begegnung mit Infiziert..." gelesen hatte war ich kurz etwas panisch, bereits einen Kontakt gehabt zu haben. 
Das war bei genauerem durchlesen natürlich schnell geklärt (allerdings war die Meldung zwischenzeitlich verschwunden, da ich den Flugmodus ausgeschaltet habe). 
Trotzdem kann ich mir gut vorstellen, dass dies andere Personen beunruhigt.

Eventuell kann man auch das an Google rückmelden und die Benachrichtigung umformulieren.

**Comment by bobatsar** [comment]
Mir ist aufgefallen, dass diese Benachrichtigung nicht immer angezeigt wird, sie aber extrem hilfreich ist. Auf meinem Motorola Telefon kommt sie sofort, wenn ich Bluetooth deaktiviere oder den Flugzeugmodus aktiviere. Das ist vermutlich das gewünschte Verhalten. 
Auf einem Samsung A50 kam keinerlei Benachrichtigung. Ist das abhängig von der Android Version? Soll ich ein neues Issue aufmachen?

**Comment by uschindler** [comment]
Diese Meldung kommt nicht von der App sondern von Google über dessen Play Services (siehe die Bilder oben), daher kann in der App dazu weder was geändert werden noch Auskünfte erteilt werden, weil das bei Google nachgefragt werden müsste.

Ich kann nur raten: Wahrscheinlich wurden irgendwann in der Vergangenheit Benachrichtigen der Google Play-Dienste auf dem einem Telefon abgeschaltet. Daher unter den Benachrichtigen im Smartphone unter erweitert bei den "Google Play Diensten" schauen und dort wieder aktivieren.

**Comment by bobatsar** [comment]
Ja das war es. Die Benachrichtigungen der Google Play Dienste waren, warum auch immer, unbeabsichtigt deaktiviert. Jetzt funktioniert es wie erwartet.

Vielen Dank für die schnelle Rückmeldung.

**Comment by SebastianWolf-SAP** [comment]
Seitens Google haben wir Signale erhalten, dass diese Meldung(en) in einem der kommenden Google Play-Updates verbessert bzw. deutlicher gemacht werden. Sobald wir hier genauere Details haben, werden wir uns nochmal melden und lassen das Issue solange selbstverständlich geöffnet.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by BenjaminRueth** [comment]
![Screenshot_20200729-192140_Firefox](https://user-images.githubusercontent.com/5740604/88832251-d4188180-d1d0-11ea-8c48-4103ed6821aa.jpg)

Auf meinem Smartphone sieht nun alles gut aus. Kann der Issue geschlossen werden?

**Comment by uschindler** [comment]
Ja ich denke auch. Google hat das mit dem letzten Google Play Dienste Update verbessert.

**Comment by SebastianWolf-SAP** [comment]
Vielen Dank für die Rückmeldungen. Wir schließen dann dieses Issue. 

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
