### ISSUE TITLE
Twitter Reports: App spams notifications 

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-android#5324]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue - Similar but probably not same as #4211

## Technical details

- Device name: Oneplus 6/9
- Android version: 11 / 12
- App version: seems to only appear with version 2.24

## Describe the bug

Under unknown circumstances the app spams notifications. This should not happen. I'm in contact with two users who reported this issue via Twitter. See the links to Twitter below. 

Here's a screenshot from [this](https://twitter.com/tantegreta1/status/1544256046235111426?s=20&t=9E8nF6YBqLPnrvpwPpPpGg) Twitter report: 

<img src="https://user-images.githubusercontent.com/67682506/177344117-27aae8aa-5016-434b-8719-3e11a4433c09.jpeg" width="300">

## Steps to reproduce the issue

Currently unclear - trying to clear the situation up.

## Expected behaviour

The app shouldn't spam the user with notifications. 

## Additional context

This issue is based on Twitter reports:

- https://twitter.com/Fem_Lea/status/1543545152534450181?s=20&t=HEz5FuU3js66jxBVhxOPww
- https://twitter.com/Ich_halt_/status/1543567371742453765?s=20&t=Txynlpp7OCopueNuDSxfrw
- https://twitter.com/tantegreta1/status/1544256046235111426?s=20&t=9E8nF6YBqLPnrvpwPpPpGg

---
Internal Tracking ID: [EXPOSUREAPP-13503](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13503)

**Comment by Ein-Tim** [comment]
Answers from one user on Twitter:

- At this time the app shows an increased risk
- positive PCR test from 27.01.22 as well as one neg. RAT from 15.12.21 are stored in the app
- 2 vaccination certificates are in the app - booster certificate is not yet in the app, thus I assume 1/2 & 2/2 are the certificates currently stored
- The certificates are valid until 02.09.22
- No red dot on any tab
- He uses a Oneplus 6 with Android 11 and on a Oneplus 9 with Android 12 the same behavior is observed

I asked him if he could provide an error report.

**Comment by Ein-Tim** [comment]
@dsarkar / @mlenkeit 

Here's the error log the user created over the last ca. 16 hours:

**ID 6374FB6F8681D5055A83**

**Comment by dsarkar** [comment]
@Ein-Tim Many thanks

**Comment by mlenkeit** [comment]
@Ein-Tim thanks for obtaining the error log, we have some initial pointers based on the log.

**Comment by dsarkar** [comment]
FYI PR https://github.com/corona-warn-app/cwa-app-android/pull/5326

**Comment by Ein-Tim** [comment]
@dsarkar @mlenkeit @samureikek

Thank you for the good cooperation between the community and the devs here. This way the issue could be fixed quickly! Appreciate it!

**Comment by thomasaugsten** [comment]
The fixed version 2.24.2 is released and in a 99% rollout. 
Tomorrow it will go in 100%
Also with a 99% rollout maybe not all user can see the update immediately, because of the internal Google rollout

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Thanks for the info, will there be a GitHub release soon?

**Comment by Ein-Tim** [comment]
I'm currently waiting for confirmation of the fix from the user who provided the error report.

**Comment by Ein-Tim** [comment]
Fix confirmed. Closing.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for the feedback, forwarded to internal ticket.
