### ISSUE TITLE
Using the Android app without Google Play Services

### ISSUE THREAD

**Issue by Zeus1605** [corona-warn-app/cwa-app-android#533]
## Current Implementation

It seems like Google Play Services is required to run the app properly

## Suggested Enhancement

Make app not reliant on Google Play Services

## Expected Benefits

People with Phones that do not have Google Play Services installed can use the app.
Also it might fix the problem that some chinese phones have
see issue #510

**Comment by tkowark** [comment]
Thanks for the suggestion. This is mostly a duplicate of #75 and we'd like to keep the non-Play Services discussion focused on a single thread.
