### ISSUE TITLE
Missing 2.24.2 GitHub release

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-android#5332]
Version 2.24.2 has been rolled out to all users, but there is still no GitHub release. Please create a GitHub release for version 2.24.2.

**Comment by Ein-Tim** [comment]
@dsarkar I think you assigned the iOS team for an Android problem :D

**Comment by schauersbergern** [comment]
Created Release v2.24.2
https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.24.2
