### ISSUE TITLE
App shows new features note after each patch update

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-android#5334]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Huawei P Smart 2019
- Android version: 10
- App version: 2.24.2

## Describe the bug

The app currently shows the "New Features" screen after each update, regardless if the update is a patch one or the one to the next minor version. I consider this as a bug, as it annoys the user, who doesn't want to see the same information multiple times. 

## Steps to reproduce the issue

1. Install version 2.24.0
2. See new features screen
3. Close the screen
4. Update to version 2.24.1
5. See the new features screen again, although you already saw & closed it before
6. Close the screen
7. Update to version 2.24.2
8. See the new features screen for the third time, although you already saw it & closed it twice before

## Expected behaviour

As under iOS, the new features screen is only shown one time (and only shows [major_version_number].[minor_version_number] and not as under Android [major_version_number].[minor_version_number].[patch_version_number]). 

## Possible Fix

Change the logic.

---
Internal Tracking ID: [EXPOSUREAPP-13581](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13581)

**Comment by larswmh** [comment]
Thanks for your report @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-13581](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13581)

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
FYI PR https://github.com/corona-warn-app/cwa-app-android/pull/5353

**Comment by Ein-Tim** [comment]
I can't verify the fix but I assume the bug is successfully fixed.
