### ISSUE TITLE
Twitter Report: Scanning positive RAT QR code leads to `Generated hash doesn't match QRCode hash` error

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-android#5336]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Pixel 4a
- Android version: 12
- App version: 2.24.2

## Describe the bug

I have a user on Twitter who has a positive RAT test QR code (https://s.coronawarn.app?v=1#...) which, when scanned with the CWA or with a normal QR-Code scanner leads to this error: 
![FXX6EN0XgAEPlxu](https://user-images.githubusercontent.com/67682506/178259677-997c2adb-6c39-4fe8-b0d3-470582878c66.jpeg)

## Steps to reproduce the issue

Not clear what causes this issue. 

## Expected behaviour

No error. 

## Possible Fix

No idea if this is a CWA problem or a problem with the QR code. 

## Additional context

QR code was sent to @thomasaugsten via Mail. I'd appreciate feedback ASAP, the user wants to warn via the CWA.

**Comment by Ein-Tim** [comment]
@dsarkar / @larswmh Could you please mirror this item to JIRA. It would be good to make sure this is no general problem but an edge case.

**Comment by thomasaugsten** [comment]
The error is correct the test center is generating the hash incorrect
it is the
sha256(timestamp#salt)
in this case
16616728bdb4b1b0d29e38c1a37763c077895b59077f2a7bf1036b805afdccf3

The user has no possibility to warn, but he should inform the test center provider or provide the test center to correct their hash calculation

**Comment by Ein-Tim** [comment]
@thomasaugsten Thanks so much for the quick feedback, I will forward this information to the user.

**Comment by Ein-Tim** [comment]
Forwarded. Nothing can be done here on CWA side. Closing.
