### ISSUE TITLE
The app crashes on devices without Google services 

### ISSUE THREAD

**Issue by electronic-fellows** [corona-warn-app/cwa-app-android#534]
## Describe the bug

If you install the app via APK and open it for the first time you see an error message before you reach the third page of the wizard. The error message is "Fehler bei der Kommunikation mit Google API(17)"

## Expected behaviour

I would expect the app to work without Google services.

## Steps to reproduce the issue

1. Take an Android Phone without google services
2. Install the App via native APK installer
3. Start app for the first time
4. Hit "Los Geht's"
5. Hit "Weiter"
6. See the error message

## Technical details

- Device: ONEPLUS A6003
- Android Version: 10
- OS: LineageOS 17.1

**Comment by tkowark** [comment]
Dear @electronic-fellows , as noted in the [FAQ](https://www.coronawarn.app/en/faq/#application) the app only works with Google Play Services. Please watch #75 for a discussion around a community driven solution to this issue.

Best regards,
TK
Corona-Warn-App Open Source Team

**Comment by s-martin** [comment]
Currently the Exposure Notification API is part of Google Play Services.

So the app won’t work without Google Play.

There were discussions, if Google will integrate the API at a later point in stock Android, but I wouldn’t expect that to happen anytime soon.
