### ISSUE TITLE
Allow user to chose display language

### ISSUE THREAD

**Issue by agsfbm6** [corona-warn-app/cwa-app-android#536]
## Current Implementation
Observed on a Xiaomi 9T Pro, MIUI Global 11.0.4, stock Android, not rooted, English localization.

When starting the Corona-Warn App I was greeted by a lengthy English language text with no possibility to switch to another language (currently German). After the initial App setup there is still no option for the user to switch to her preferred language and the App defaults to the OS language.

## Suggested Enhancement
Use the OS language / localization setting as a hint for the primary display language but provide the user with the option to switch to his preferred language during the initial setup and under 'Settings' in the main App.

## Expected Benefits
The user will be able to understand the texts / options that he will be presented with even though his (potentially employer provided) mobile phone is configured with a different language / localization.

**Comment by corneliusroemer** [comment]
I agree, I use my phone in English, but in this case I would prefer to see it like the majority of users - in German. So that I can explain things more easily and don't have a translation barrier and potentially inaccurate translations.

**Comment by tkowark** [comment]
Since this enhancement proposal affects both apps, we'd like to track it centrally in the documentation repo. I would therefore close this one here and redirect discussions about that topic to: corona-warn-app/cwa-documentation#153.

Best regards,
TK
Corona-Warn-App Open Source Team
