### ISSUE TITLE
v2.25.0-RC2 is tagged as "Lates" but should be "Pre-Release"

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-android#5368]
https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.25.0-rc.2 was released as the latest version although it is a RC. Please change to "Pre-Release".

**Comment by mtwalli** [comment]
@Ein-Tim  Thanks for reporting it, I marked it as pre-release now
