### ISSUE TITLE
Exported certificate folding cross vertically displaced

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#5369]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue
Refer also to https://github.com/corona-warn-app/cwa-app-android/issues/5350, which is marked with label https://github.com/corona-warn-app/cwa-app-android/labels/Fix%202%2E25.

## Technical details

- Device name: Pixel 3a emulator
- Android version: 12
- App version: pre-release [2.25.x - 2.25.0-RC2](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.25.x) in addition to previously reported 2.24.2.
Regression from CWA 2.23.2.

## Describe the bug

The folding guide cross on an exported EU certificate is not vertically in the center of the paper, although horizontally it is centered. The cross is vertically displaced about 4.5 mm.

Distances in mm from edge to center cross

App Version | left | right | top | bottom | comment
--- | --- | --- | --- | --- | ---
2.23.2 | 104.55 | 104.55 | 147.76 | 148.99 | correctly centered
2.25.0-RC2 | 104.76 | 104.78 | 144.15 | 152.90 | vertically displaced
Expected | 105 | 105 | 148.5 | 148.5 | dimensions for center of DIN A4

## Steps to reproduce the issue

On Desktop

1. Use Android Studio Device File Explorer to transfer German EU vaccination certificate PDF to the emulator

In CWA App

2. Tap Scan
3. Tap Open File
4. Navigate to vaccination certificate in File app and tap on file, tap "Continue"
5. Tap three-dot symbol
6. Select Display Print Version, tap "Next"
7. Tap Share symbol
8. Tap Drive symbol
9. Tap Save

On Desktop

10. Open Drive https://drive.google.com/drive/my-drive
11. Download
12. Open saved PDF with Adobe Acrobat DC
13. Zoom to page level
14. Click Tools > Measure > Measuring Tool
15. Use mouse to measure from edges to center cross

## Expected behavior

The folding cross should be in the center of the document. [DIN A4](https://en.wikipedia.org/wiki/DIN_A4) has the standard dimensions 210 x 297 mm, so the cross should be at 105 and 148.5 mm from the respective paper edge.

---
Internal Tracking ID: [EXPOSUREAPP-13667](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13667)

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for reporting. Internal Tracking ID: [EXPOSUREAPP-13667](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13667). Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
- See PR https://github.com/corona-warn-app/cwa-app-android/pull/5427

**Comment by MikeMcC399** [comment]
- PR #5427 is included in [v2.26.0-rc.1](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.26.0-rc.1) so if anybody is handling the labels here, then https://github.com/corona-warn-app/cwa-app-android/labels/Fix%202%2E26 could be applied to this issue.
