### ISSUE TITLE
Blacklist second device of the same person

### ISSUE THREAD

**Issue by lab-at-nohl** [corona-warn-app/cwa-app-android#537]
## Current Implementation
App does not distinguish between possible contacts/phones. 

## Suggested Enhancement
Blacklist devices shown in a list of surrounding bluetooth counterparts. 

## Expected Benefits
I usually have two phones with me during the day. Hence, most communication will be between my devices (which are more than 15 minutes near to each other, of course). 

- Chain more than one device of a single user together (UI dialog?)
- Not sure about the consequences but it seems reasonable to me
- Maybe also useful for other issues

**Comment by uschindler** [comment]
This is impossible if you respect privacy.

**Comment by corneliusroemer** [comment]
You can only report on one device. You can receive on two devices. So you're not harming yourself by having the app on two devices, but it's not really beneficial either.

Just have the app on the main device you're using.

Other requests re changing are out of scope for the time being.

**Comment by tkowark** [comment]
Thanks for your answers @uschindler and @corneliusroemer 

This issue was also discussed in, e.g., corona-warn-app/cwa-documentation#82

We will not blacklist second devices as there is really now way of knowing that they are second devices without compromising on privacy questions.

**Comment by lab-at-nohl** [comment]
@uschindler and @tkowark, I assumed because the bluetooth identifier is derived of an App/Device identifier, you could exchange the latter key (QR code?) to synchronize two apps such that they recognize each other in a secure way.
