### ISSUE TITLE
http link to RKI STIKO

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#5378]
## Technical details

- App version: 2.25.x and 2.26.x

## Describe the bug

CWA Android links to http://www.rki.de/stiko using `http` not `https` protocol.

https://github.com/corona-warn-app/cwa-app-android/blob/1fe10adf9807ad48dc01b7af90fca58bb8947cb6/Corona-Warn-App/src/main/res/values/links.xml#L70-L71

Normally http://www.rki.de/stiko redirects to https://www.rki.de/stiko (HTTP 307 Internal redirect) however this might cause an issue with certain Android client security settings.

## Expected behavior

CWA Android should link to https://www.rki.de/stiko, not to http://www.rki.de/stiko, using `https` protocol.

## Additional information

- The link was added to CWA Android 2.25.x by PR https://github.com/corona-warn-app/cwa-app-android/pull/5342

- For comparison CWA iOS uses https://www.rki.de/stiko (with `https`) as expected https://github.com/corona-warn-app/cwa-app-ios/pull/4687

---
Internal Tracking ID: [EXPOSUREAPP-13687](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13687)

**Comment by dsarkar** [comment]
Good morning @MikeMcC399! Thanks fro reporting. Internal Tracking ID: [EXPOSUREAPP-13687](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13687). Enjoy your weekend!

**Comment by MikeMcC399** [comment]
Good morning @dsarkar! I noticed this issue due to the work being done on checking the links in the website PR https://github.com/corona-warn-app/cwa-website/pull/2968. Have a good weekend yourself!

**Comment by MikeMcC399** [comment]
- This issue is addressed by PR #5398.
