### ISSUE TITLE
Sonar Cloud crashes on External PRs

### ISSUE THREAD

**Issue by tkowark** [corona-warn-app/cwa-app-android#539]
## Describe the bug

When running Sonar Cloud for external PRs, the CircleCI build crashes as information about the branches is not properly handed over by (most likely) SonarCloud.

## Expected behaviour

Sonar Cloud should be skipped for external PRs o SonarCloud should fail silently (as it does for, for example, cwa-server)

## Steps to reproduce the issue

https://github.com/corona-warn-app/cwa-app-android/pull/515

## Possible Fix

https://github.com/corona-warn-app/cwa-app-android/pull/373

**Comment by pr1metine** [comment]
It looks like SonarCloud still crashes on community PRs, see #655 #692 .

**Comment by tkowark** [comment]
It seems that your .circle/config.yml differs from the one in master and dev of the cwa-app-android repo. In particular, [this line](https://github.com/corona-warn-app/cwa-app-android/blob/4906bd3b16959b1bca336c081a3718ac06f928c4/.circleci/config.yml#L43) is missing, which prevents sonar-scanner from running on external PRs. Could you please fetch all upstream changes from the repo?

**Comment by pr1metine** [comment]
Hmm, I see.

Someone else did that for me. Now I am unauthorized to do anything after I tried to commit changes, see #695 .
