### ISSUE TITLE
Support Material You themed icons

### ISSUE THREAD

**Issue by thoweber** [corona-warn-app/cwa-app-android#5396]
## Avoid duplicates
* [X] This enhancement request has not already been raised before
* [X] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [x] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

The default CWA icon is shown on the home screen 

## Suggested Enhancement

When themed icons are activated, a themed version should be displayed.
```xml
<adaptive-icon>
  ...
  <monochrome android:drawable=""/>
  ...
</adaptive-icon>
```

## Expected Benefits

Improves the overall UX for users of Material You. Should not be too difficult to implement, but is of course of low priority

**Comment by Ein-Tim** [comment]
- Related issue: https://github.com/corona-warn-app/cwa-app-android/issues/5118

**Comment by MikeMcC399** [comment]
@thoweber 

- Are you are referring to [Themed app icons](https://developer.android.com/about/versions/13/features#themed-app-icons) available with Android 13 beta?

- You mentioned also [Material You](https://material.io/blog/announcing-material-you), which is equivalent to [Material Design 3](https://m3.material.io/). For Material You there are some comments in https://github.com/corona-warn-app/cwa-app-android/issues/5119 concerning what was implemented for CWA Android 2.21.

**Comment by thoweber** [comment]
@MikeMcC399 yes, I am referring to themed app icons only, as the design team already decided against using color themes in the app

**Comment by MikeMcC399** [comment]
@thoweber 

I guess this might also mean that CWA would need to explicitly support Android 13. https://developer.android.com/about/versions/13 says: "Beta 4 is the last update before the official Android 13 release, coming in the weeks ahead."

**Comment by thoweber** [comment]
@MikeMcC399 

This will only work with Android 13 and up, but as far as I have understood things, it is a matter of amending the app's adaptive icons (CWA has already defined adaptive icons in [https://github.com/corona-warn-app/cwa-app-android/tree/main/Corona-Warn-App/src/main/res/mipmap-anydpi-v26])...
But I am not an Android dev though


https://developer.android.com/about/versions/13/features#themed-app-icon-specs

**Comment by MikeMcC399** [comment]
- Dependent on enhancement request https://github.com/corona-warn-app/cwa-app-android/issues/5469

**Comment by mtwalli** [comment]
Please see https://github.com/corona-warn-app/cwa-app-android/issues/5469#issuecomment-1371936091
