### ISSUE TITLE
Hinweis zur Auffrischimpfung Benachrichtigung kommt jeden Tag

### ISSUE THREAD

**Issue by julius-fpl** [corona-warn-app/cwa-app-android#5400]
## Technical details

- Device name: Huawei P30 lite New Edition
- Android version: 10
- App version: 2.25.0

## Describe the bug

3 Monate bevor das 2. Impfzertifikat von Biontech abläuft sendet die CWA täglich eine Benachrichtigung zum Hinweis einer Auffrischimpfung. 

## Steps to reproduce the issue

Man braucht ein Impfzertifikat von der 2. Impfung Biontech, welches in 3 Monaten abläuft.

Benachrichtigung führt zu Zertifikat > das Zertifikat, welches abläuft > Hinweis zur Auffrischimpfung

Nach anschauen der Benachrichtigung verschwindet diese, aber kommt nach einem Tag wieder.

## Expected behaviour

Nach einmaligem Anschauen, sollte man gefragt werden ob man diese Benachrichtigung wieder erhalten möchte oder nicht. 

## Possible Fix

Bitte fügen Sie eine Funktion hinzu um nach einmaligem sehen diese Benachrichtigung nicht mehr zu erhalten / nicht mehr Erinnern.

---
Internal Tracking ID: EXPOSUREAPP-10906

**Comment by MikeMcC399** [comment]
@julius-fpl 

Erscheint noch ein roter Punkt neben dem Text "Hinweis zur Auffrischimpfung"?

Wenn ja, wenn man auf  "Hinweis zur Auffrischimpfung" tippt, dann auf "X" bei der Detailmeldung (vermutlich zu der Regel DE-BNR-0110) ist der rote Punkt wieder verschwunden?

**Comment by julius-fpl** [comment]
Ja, ein roter Punkt ist da neben dem Button Hinweis zur Auffrischimpfung und wenn man darauf klickt und auf das x drückt ist er weg, bis am nächsten Tag die CWA wieder die Benachrichtigung schickt.

**Comment by thomasaugsten** [comment]
@julius-fpl  Könntest du unter Appinformation den Fehlerbericht aktivieren und den Bericht übermitteln wenn die Benachrichtigung erneut auftritt und dann uns die ID mitteilen.

**Comment by julius-fpl** [comment]
Habe ich gestartet und sobald die Benachrichtigung wieder kommt schickd ich ihn ab. Soll ich dann die ID hier in die Comments posten?

**Comment by Ein-Tim** [comment]
@julius-fpl Die ID kannst du einfach hier in die Comments posten, den zugehörigen Fehlerbericht kann nur das Entwicklungs-Team einsehen.

**Comment by julius-fpl** [comment]
Hallo, 
hier die ID zum Fehlerbericht: F2B16E163E9BE5016306

**Comment by thomasaugsten** [comment]
Der Fehlerbericht wurde leider nicht korrekt gestartet er wurde
Es wurde erst heute 22:30 gestartet.

**Comment by julius-fpl** [comment]
Oh, Entschuldigung! Ich habe gesehen, dass der nicht mehr lief, hatte aber die Hoffnung, dass er das trotzdem aufgezeichnet hat. Hat die CWA vielleicht durch ein Neustart des Smartphones aufgehört aufzunehmen?
Ich habe den Fehlerbericht gestartet und lasse das Smartphone mal an und schicke die ID morgen nochmal.

**Comment by MikeMcC399** [comment]
@julius-fpl 

Es wird nur aufgezeichnet, wenn unter "Fehlerberichte" der Text "Aufzeichnung läuft" angezeigt wird.
Normalerweise hört die Aufzeichnung nur auf, wenn auf "Stoppen und löschen" getippt wird. Beim Neustart des Smartphones wird die Aufzeichnung fortgesetzt.

**Comment by MikeMcC399** [comment]
@julius-fpl 

Tritt das Problem noch auf? Ist es gelungen, einen vollständigen Fehlerbericht zu erzeugen?

**Comment by julius-fpl** [comment]
Der Fehlerbericht läuft noch, aber die Benachrichtigung kam jetzt nicht mehr. (Vorher war sie 2 Wochen fast täglich da). Ich schreib die FehlerID hier rein sobald die Benachrichtigung wieder kommt.

**Comment by julius-fpl** [comment]
Gestern kam wieder die Benachrichtigung, aber der Fehlerbericht lief nicht mehr. Vor 2 Tagen hatte ich noch nach geschaut ob er noch läuft und da lief er und hatte ca. 15 Mb Daten gesammelt. Ich habe den Fehlerbericht erneut gestartet und hoffe das es jetzt klappt.

**Comment by julius-fpl** [comment]
Okay, vielen Dank! Ich probiere mal den App Cache zu leeren und die App Daten zu löschen und importier dann wieder mein Impfzertifikat rein und schaue ob es hilft.
(Verfügbare updates von Android/Huawei und von der CWA sind alle installiert.)

**Comment by MikeMcC399** [comment]
@julius-fpl 

> Ich probiere mal den App Cache zu leeren und die App Daten zu löschen und importier dann wieder mein Impfzertifikat rein und schaue ob es hilft.

Es gibt auch die Möglichkeit einer App-Reset zu machen. Siehe https://www.coronawarn.app/de/faq/results/#in_app_reset.

**Comment by julius-fpl** [comment]
Es scheint so als wäre das Problem behoben. Soll ich noch warten oder den Issue schließen?

**Comment by MikeMcC399** [comment]
@julius-fpl 

> Es scheint so als wäre das Problem behoben. Soll ich noch warten oder den Issue schließen?

Wenn das Problem nicht mehr auftritt, kann das hier geschlossen werden. Falls es doch wieder auftritt, würde trotzdem die Möglichkeit bestehen, es wieder zu eröffnen.

**Comment by MikeMcC399** [comment]
@julius-fpl 

Es sollte unten ein Button "Close issue" in der Webansicht https://github.com/corona-warn-app/cwa-app-android/issues/5400 angezeigt werden, mit dem Du selber den Issue schließen kannst, wenn das in Deinem Sinne ist.

**Comment by julius-fpl** [comment]
Okay, bisher trat der Fehler nicht mehr auf, dann schließe ich den Beitrag. Vielen Dank für die Hilfe.

**Comment by Ein-Tim** [comment]
Ich bin aktuell mit einem Nutzer auf Twitter in Kontakt, der diesen Fehler hat. Ich kläre gerade Details ab und versuche einen Fehlerbericht zu bekommen. 

cc @thomasaugsten

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Workarounds for this issue:

1. Restart the device
2. Reset the Corona-Warn-App
3. Depending on the Android version it may also be possible to disable `Corona-Warn`/ `Certificates` notifications selectively in Android

Otherwise I suggest to open a new issue with screenshots and other details.

**Comment by Ein-Tim** [comment]
@MikeMcC399 Okay, agreed! I will open a new issue if the user provides me with more details.

**Comment by MikeMcC399** [comment]
- Also, the app booster notifications are currently not in-line with the most recent STIKO recommendations. See [Epidemiologisches Bulletin 3 2022](https://www.rki.de/DE/Content/Infekt/EpidBull/Archiv/2022/Ausgaben/33_22.pdf?__blob=publicationFile) and https://github.com/corona-warn-app/dcc-rule-translation/issues/10.
