### ISSUE TITLE
Missing guidance about the choice of branch for PR submitters

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#5404]
The [CONTRIBUTING](https://github.com/corona-warn-app/cwa-app-android/blob/main/CONTRIBUTING.md) guide and the linked [pull_request_template](https://github.com/corona-warn-app/cwa-app-android/blob/main/.github/pull_request_template.md) do not mention how to choose a branch when submitting a PR.

## Suggestion

Add some guidance about how to choose the most appropriate branch when submitting a PR.

**Comment by MikeMcC399** [comment]
- For some reason the guidance was removed in PR #https://github.com/corona-warn-app/cwa-app-android/pull/1386 in Oct 2020.

**Comment by Ein-Tim** [comment]
@MikeMcC399 I think the problem was that the instruction was to branch from the dev branch, which existed in the early phase of this project, but was later replaces by the release branches. I wonder why the statement wasn't corrected but the whole checklist removed.

**Comment by mtwalli** [comment]
PR: https://github.com/corona-warn-app/cwa-app-android/pull/5554
