### ISSUE TITLE
Re-implementation of Bluetooth contact tracing

### ISSUE THREAD

**Issue by schildbach** [corona-warn-app/cwa-app-android#541]
The current method of using Google Play Services (GPS) has many issues:

- Vendor lockin, meaning it only works on phones with a Google license. E.g. users of LineageOS, Amazon and Huaweii devices are left behind.
- GPS isn't open source, so the most sensitive part of this app (contact tracing) can't be code reviewed.
- Due to Google-owned signature whitelisting baked into GPS, we cannot build and install this app from source. Google blocks self-signed versions. This is against the idea of free software, blocks improvements by third parties and renders code reviews worthless.

I suggest we re-implement the Bluetooth contact tracing part and get rid of the Google dependencies.

**Comment by jlnprssnr** [comment]
This is already discussed in #75
