### ISSUE TITLE
Import of recovery certificate

### ISSUE THREAD

**Issue by dumbpie** [corona-warn-app/cwa-app-android#5426]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name:
- Android version:
- App version:

**Comment by dumbpie** [comment]
Hi, 

I had Covid in Poland, now I have a "polish" recovery certificate, only as a sms send, not on paper available for me.
The QR-Code-Scanner says:
"Fehler Dieser QR-Code ist kein gültiges Zertifikat
Weitere Informationen zum Erhalt Ihres Zertifikats finden Sie in den FAQ. (HC_JSON_SCHEMA_INVALID)"

The FAQ only talks about certificates, issued after "14.06.2021", well, 08/2022 is after 06/2021.

Does anybody else have problems with "non-german" certificates too?
Workaround? Should I ask for a new certificate in germany?

With the app "Binary Eye" i was able to read the barcode: 
EU Digital Covid Certificate Verifiable QR (https://github.pathcheck.org/debug.html) 
Test says: 
{
  "status": "verified",
  "contents": {
    "Map": [
      [ 4, 1713601395 ],
      [ 6, 1659465909 ],
      [ 1, "PL" ],
      [
        -260,
        {
          "Map": [
            [
              1,
              {
                "r": [
                  {
                    "du": "2023-01-29",
                    "co": "PL",
                    "ci": "URN:UVCI:01:PL:3/ECB9C0AB24394B73875F08279178FDFA",
                    "is": "Centrum e-Zdrowia",
                    "tg": "840539006",
                    "fr": "2022-08-02",
                    "df": "2022-08-13"
                  }
                ],
                "v": [],
                "t": [],
                "nam": {
                  "fnt": "xxxx",
                  "fn": "xxxx",
                  "gnt": "yyyy",
                  "gn": "yyyy"
                },
                "ver": "1.0.0",
                "dob": "1989-02-07"
              }
            ]
          ]
        }
      ]
    ]
  },
  "issuer": {
    "displayName": { "en": "Gov of Poland" },
    "entityType": "issuer",
    "status": "current",
    "credentialType": [ "r" ],
    "validFromDT": "2022-04-21T08:23:16.000Z",
    "validUntilDT": "2024-04-20T08:23:15.000Z",
    "didDocument": "-----BEGIN CERTIFICATE-----CENSORED FOR DATA PRIVACY REASONS-----END CERTIFICATE-----"
  },
  "raw": {
    "tag": 18,
    "value": [
      { "Map": [ [ 4, "Z/cybJ0GUUU=" ], [ 1, -7 ] ] },
      {},
      {
        "Map": [
          [ 4, 1713601395 ],
          [ 6, 1659465909 ],
          [ 1, "PL" ],
          [
            -260,
            {
              "Map": [
                [
                  1,
                  {
                    "r": [
                      {
                        "du": "2023-01-29",
                        "co": "PL",
                        "ci": "URN:UVCI:01:PL:3/ECB9C0AB24394B73875F08279178FDFA",
                        "is": "Centrum e-Zdrowia",
                        "tg": "840539006",
                        "fr": "2022-08-02",
                        "df": "2022-08-13"
                      }
                    ],
                    "v": [],
                    "t": [],
                    "nam": {
                      "fnt": "xxxx",
                      "fn": "xxxx",
                      "gnt": "yyyy",
                      "gn": "yyyy"
                    },
                    "ver": "1.0.0",
                    "dob": "1992-11-11"
                  }
                ]
              ]
            }
          ]
        ]
      },
      "88DUInpAVCQy0MNlwhktgv+kQmCi5tye/m1AkypuzJHMlMSw6kqx36F25MavsH5U+/EIeT6JHQMfTGoDtye8BQ=="
    ]
  },
  "qr": "CENSORED FOR DATA PRIVACY REASONS"
}

Signature Verified  but Schema has errors [{"instancePath":"/v","schemaPath":"#/properties/v/minItems","keyword":"minItems","params":{"limit":1},"message":"must NOT have fewer than 1 items"}]


I tried it on recent versions of CTTG and CWA (today). (Android 9.1)
On daughters iOS, it seems, the certificate can be read, we interupted after the question (more or less) "Are you allowed to use this certificate?"

Is the version for iOS more "tolerant" against errors in the certificate?

Thanks a lot in advance!

**Comment by Ein-Tim** [comment]
For reference, downstream CCTG issue: https://codeberg.org/corona-contact-tracing-germany/cwa-android/issues/273

@thomasaugsten Could you please have a look (and censor data in the comment which could be used to create the certificate)? 

Thanks!

**Comment by thomasaugsten** [comment]
The schema violation from poland QR-codes are accepted with 2.26
https://github.com/corona-warn-app/cwa-app-android/pull/5383
