### ISSUE TITLE
New resetted Android 6.0.1 can't continue on "Risk identification"

### ISSUE THREAD

**Issue by gizmo21** [corona-warn-app/cwa-app-android#545]
On a newly resetted Android 6.0.1, when Playstore is[](https://user-images.githubusercontent.com/29229062/84778555-74309780-afe3-11ea-975e-9e7511add8fc.jpeg)  updated and app is installed, on appstart you can confirm ""privacy statement", but on "Risiko-Ermittlung Aktivieren" the button is pressed but nothing happens - no feedback. 
After a while URSACHE: 9002 Etwas ist schiefgelaufen" apears with details: 
```
k0.b.a.a.c.k.k. Missing c {name=nearby_exposure_notification,version=2}
at k0.b.a.a.k.l.e.handleMessage(com.google.android.gms:play-services-base@@17.3.0.27)
...
android.os.HandlerThread.run(HandlerThread.java:61)
```

In background I see notification:
"Google play-Dienste aktualisieren: Corona-Warn wird nur ausgeführt wenn Du die google Play-Dienste aktualisierst", but pressing on this notification shows the playservices but nothing to update there.
So it seems it updated somehow in background but the app can't use these new functions instantly

_Perhaps a simple message (not error) should be shown In-App too, so that enduser knows what 9002 means and one has to update playstore/Play-Services prior to continue and perhaps close the app at this point._

* Android 6.0.1
* wifi activated
* bluetooth off (has not been asked by app at this point)
* location service off (has not been asked by app at this point)

Update: After a while without updateing manually and NOT closing the app (just going back-and-forth) , the button "Risiko-Ermittlung Aktivieren" works and the next message "Benachrichtigungen zu mögl. Begegnungen...." apears.

**Comment by tkowark** [comment]
We'll note that as a bug but also as an example for more helpful error messages (linking #472 )

**Comment by jakobmoellersap** [comment]
Hi, thanks for your issue report! Does the issue still persist? Can you replicate?

**Comment by gizmo21** [comment]
Well as I wrote, it was a factoryresetted 6.0.1  phone, that just updated the Google services after/while first start of the app. So replication is not really what I(!) want atm :)
And as I wrote in "update:", it worked after a while without leaving the app.

I guess it was due to Google service not already been updated, or app did not straight recognise the already available APIs. Both is also mentioned in other threads. 

My recommendation would be to check for API availability straight at app-start perhaps even prior to showing privacy policy (at least NOT as late as on pressing the RISK-Button)
Then in errorcase give the enduser a meaningful message to update the g-servcies, perhaps even link to the updateable play services app and close the CW-app afterwards or have the API check done better, to manage a parallel-install of services update in background.
My case (factoryreset) could be rare but 

Well as I wrote, it was a factoryresetted 6.0.1  phone, that just updated the Google services after/while first start of the app. So replication is not really what I(!) want atm :)
And as I wrote in "update:", it worked after a while without leaving the app.

I guess it was due to Google service not already been updated, or app did not straight recognise the already available APIs. Both is also mentioned in other threads. 

My recommendation would be to check for API availability straight at app-start perhaps even prior to showing privacy policy (at least NOT as late as on pressing the RISK-Button)
Then in errorcase give the enduser a meaningful message to update the g-servcies, perhaps even link to the updateable play services app and close the CW-app afterwards or have the API check done better, to manage a parallel-install of services update in background. 

My case (factoryreset on 6.0.1) could be rare but service not updated could be the case quite often.

That's my 2cents on it.

**Comment by gizmo21** [comment]
Btw. My stacktrace looked very similar top this one https://user-images.githubusercontent.com/29229062/84778555-74309780-afe3-11ea-975e-9e7511add8fc.jpeg 
from that issue 
https://github.com/corona-warn-app/cwa-app-android/issues/543

But my root cause line was 61 not 65 and I always had an google account in that phone.

**Comment by jakobmoellersap** [comment]
We hope that this issue will fade out as new devices will automatically already include the GMS required to run the App. This should thus only be temporary. We will not be able to fix this bug on our own as the issue relies on GMS Updates that we do not control.

As such I will close the issue.
