### ISSUE TITLE
Entered TAN numbers cannot be removed in some case

### ISSUE THREAD

**Issue by KevCui** [corona-warn-app/cwa-app-android#546]
## Describe the bug

I'm using Gboard as soft keyboard on my phone. When swiping space bar left/right, the navigation function will be triggered.  If I swiped space bar by accident meanwhile entering TAN, in case I need to correct some wrong numbers, I'm not able to remove the entered TAN numbers anymore.

## Expected behaviour

The space bar navigation should be ignored when inputting TAN numbers. All entered TAN can be removed and reentered.

## Steps to reproduce the issue

- Go to TAN entry screen, Gboard appears
- Enter some TAN numbers
- Swipe space bar to left
- Tap backspace to remove entered numbers

<img src="https://user-images.githubusercontent.com/14293537/84781380-0e460f00-afe7-11ea-80b5-3c85443daed3.gif" width="256">

In the gif above, there are 3 cases:

1. Entering TAN and then do not touch space bar, removing entered TAN without issue :heavy_check_mark: 

2. Entering TAN and then tap on space bar, removing entered TAN without issue :heavy_check_mark: 

3. Entering TAN and then swipe on space bar, in this case, removing entered TAN is not possible :heavy_multiplication_x:

**Comment by BjoernPetersen** [comment]
The issue seems to be that swiping left on the keyboard sets the cursor to the far left of the input. Pressing backspace at that position naturally doesn't remove anything. Swiping right should work for now, but the app could force the cursor to be always at the rightmost position.
