### ISSUE TITLE
No warning on Android 12 for wrong time

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#5463]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* Related to https://github.com/corona-warn-app/cwa-app-android/issues/5183

## Technical details

- Device name: Samsung Galaxy A52 5G (SM-A526B/DS)
- Android version: 12
- App version: 2.25.0

## Describe the bug

App does not stop exposure check taking place when date incorrectly set to future before installation on Android 12.

On Android 8 an error message is output and no exposure check takes place.

## Steps to reproduce the issue

On Android 12:

1. Set device date to two days into the future
2. Uninstall CWA (if already installed)
3. Install CWA
4. Open CWA
5. Tap "Let's Get Started"
6. Tap "Next"
7. Tap "Activate Exposure Logging"
8. Tap "Turn on"
9. Tap "Next", tap "Next"
10. Tap "Do Not Share"
11. Tap "OK"
12. Tap "Allow", disable optimized battery usage for Corona-Warn (device specific)
13. Dismiss QR Code Scanner pop-up by tapping on "X"
14. Note "Exposure check failed, with timestamp Today"<br>![Exposure check 1](https://user-images.githubusercontent.com/66998419/168478373-571760ea-705d-4f54-9078-6005a5c5d4e2.jpg)

Repeat the steps 1 - 11 on Android 8:

At step 11, Android 8 already shows an error message:

12. Tap OK for message "Exposure Check Not Possible"
![Exposure Check Not Possible](https://user-images.githubusercontent.com/66998419/185084167-d4161980-0885-4e0f-b687-032b419bd204.jpg)
13. Tap "Allow", disable optimized battery usage for Corona-Warn (device specific)
14. Dismiss QR Code Scanner pop-up by tapping on "X"
15. Note "Encounters have not yet been checked."
![Encounters not yet checked](https://user-images.githubusercontent.com/66998419/185084207-ed1e2f8f-64f7-4b09-a787-d1d262a13990.jpg)

## Expected behavior

- On Android 12 the app should prevent an exposure check from taking place if the date does not match the server date. It should output the same error message "Exposure Check Not Possible" as displayed on Android 8 under the same conditions.

---
Internal Tracking ID: EXPOSUREAPP-9077

**Comment by sapcoder123** [comment]
@MikeMcC399 Thank you for reporting the issue which is fixed with #5183

**Comment by MikeMcC399** [comment]
@sapcoder123 

> the issue ... is fixed with https://github.com/corona-warn-app/cwa-app-android/issues/5183

- #5183 is another related issue. The resolution is supposed to be in PR #5465.

**Comment by MikeMcC399** [comment]
I successfully tested this issue with `Corona-Warn-App-2.27.0-RC0-deviceForTesters-release.apk` so I am now closing it.
