### ISSUE TITLE
Enable app-dependent language setting (Android 13)

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#5468]
## Avoid duplicates
* [ ] This enhancement request has not already been raised before
See below for related requests
* [X] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

CWA Android is built for API 31 (Android 12) and uses the device's language setting (locale).

### Screenshots

Android 13 screenshots with CWA installed showing (as expected) that App Language selection is not available in CWA Android 2.25.0:

![App Languages](https://user-images.githubusercontent.com/66998419/185187212-dbdbc954-0c9b-4e80-968c-e2fa4efa2773.png)

![App Languages](https://user-images.githubusercontent.com/66998419/187133940-c0403964-e982-4b87-8b8f-c40c49e316f0.jpg)

## Suggested Enhancement

Adapt the CWA Android app to target API 33 (Android 13) and implement [Per-app language preferences](https://developer.android.com/about/versions/13/features#app-languages).

## Expected Benefits

More flexible language selection for users in a multi-lingual environment. iOS already has this capability (see https://github.com/corona-warn-app/cwa-app-android/issues/3489#issuecomment-824746939 from @Ein-Tim).

Note that if this is implemented, and there is no change to the [Google Exposure Notifications API](https://developers.google.com/android/exposure-notifications/exposure-notifications-api), then it could mean that messages from the Google API would be output in a different language to the ones output by the CWA app. This might not be a desirable configuration.

## Related requests

- https://github.com/corona-warn-app/cwa-app-android/issues/2905
- https://github.com/corona-warn-app/cwa-app-android/issues/3489
- https://github.com/corona-warn-app/cwa-app-android/issues/4980

**Comment by MikeMcC399** [comment]
- Dependent on enhancement request https://github.com/corona-warn-app/cwa-app-android/issues/5469

**Comment by gitterman** [comment]
Even Google Maps (from GOOGLE!) can be set to a different language other than the system language, and even on older android versions.
So it is strange to me, why the corona warn app doesn't allow this.
I suppose that the developers follow more some user unfriendly guidelines than usability.
If an app which is only available in a non-English language is installed on a phone that is set to English as system language, it runs with its own non-English language.
So I see not reason why an app which supports multiple languages must "auto-magically" use the system language.
Let the user decide, not an automatic!

**Comment by MikeMcC399** [comment]
There is a [YouTube video](https://www.youtube.com/watch?v=DUKnNWwcNvo) (5:30 duration) published on Sep 3, 2022 which explains the user story behind the need for in-app language preferences and the steps to implement in Android 13 (Codename: Tiramisu / API 33) and previous Android versions.

**Comment by MikeMcC399** [comment]
Some commits in https://github.com/corona-warn-app/cwa-app-android/tree/feature/13779-Android-13 reference this issue (which does not mean that it will be released though).

**Comment by MikeMcC399** [comment]
Since the pre-requisite of Android 13 support is not planned (see https://github.com/corona-warn-app/cwa-app-android/issues/5469#issuecomment-1371936091), then this enhancement can also not be planned.
