### ISSUE TITLE
Target Android 13 (API 33)

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#5469]
## Avoid duplicates
* [X] This enhancement request has not already been raised before
* [X] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

The latest CWA Android pre-release 2.29.x is built for API 32 (Android 12L (Sv2)). See https://github.com/corona-warn-app/cwa-app-android/blob/7763a16374d8b76543dc7714b4a9c7a49eaf0a34/Corona-Warn-App/build.gradle#L35

## Suggested Enhancement

Adapt the CWA Android app to target API 33 (Android 13). See https://developer.android.com/about/versions/13. Android 13 is in AOSP (Android Open Source Project) as of August 15, 2022.

## Expected Benefits

Take advantage of new features offered by Android 13. See https://developer.android.com/about/versions/13.

This is only a benefit if the CWA app is considered to have an active lifetime into 2023. Android 13 is currently rolling out to Pixel devices and it is expected to roll out to other devices later in 2022 and in early 2023.

---
Internal Tracking ID: EXPOSUREAPP-13779

**Comment by MikeMcC399** [comment]
See https://github.com/corona-warn-app/cwa-app-android/tree/feature/13779-Android-13

**Comment by mtwalli** [comment]
> See https://github.com/corona-warn-app/cwa-app-android/tree/feature/13779-Android-13

@MikeMcC399 this is only to try it and list potential issues,please don't take it for granted?

**Comment by MikeMcC399** [comment]
@mtwalli 

Thanks for the clarification that Android 13 and other functionality in that branch is not approved. I hadn't assumed it was approved.

**Comment by MikeMcC399** [comment]
Samsung Galaxy A52 5G is now receiving a One UI 5 Upgrade (Android 13)

**Comment by MikeMcC399** [comment]
@mtwalli 

Do you expect to support Android 13 at any time in the future?

Currently I see only 
`targetSdkVersion 32`
in 3.0 and 3.1.

**Comment by mtwalli** [comment]
@MikeMcC399  I hope so. I requested it some time ago ,but unfortunately there is final decision yet

**Comment by MikeMcC399** [comment]
@mtwalli 

Thanks for the update. If it is still not decided, then I will leave this issue open. Please feel free to close it if there is a decision made **not** to support it.

**Comment by MikeMcC399** [comment]
@mtwalli 

Thanks for the update! I completely understand the decision.
