### ISSUE TITLE
Incorrect localization resolution

### ISSUE THREAD

**Issue by krin-san** [corona-warn-app/cwa-app-android#547]
## Describe the bug

When the 1st system language is not supported by app, other system language are not taken into account.

## Expected behaviour

Application displays localised string in one of the system languages, before falling back to English.

## Steps to reproduce the issue

- In System settings configure the following list of Languages:
  - Russian _(or any other unsupported locale)_
  - German
- Run application

## Technical details

- OS: Android 10
- Model: Pixel 3a
- Build: QQ3A.200605.002

## Possible Fix

[Improvements to resource-resolution strategy](https://developer.android.com/guide/topics/resources/multilingual-support#postN) section suggests to store resources in specifically named folders to **speed up** resource resolution. [Resource folders](https://github.com/corona-warn-app/cwa-app-android/tree/master/Corona-Warn-App/src/main/res) seems to be named correctly, but resource-resolution doesn't work as described in guide.

## Additional context

Follow-up to https://github.com/corona-warn-app/cwa-app-android/issues/483#issuecomment-644687479

**Comment by duchampdev** [comment]
I'll have a look at this right now, there seems to be a quite easy solution for Android >= 7 (API level 24), i.e. only API level 23 would not benefit from it.

**Comment by duchampdev** [comment]
@krin-san My PR for this problem has been merged today, so the issue should be solved with the next version.

**Comment by jakobmoellersap** [comment]
Will be closed as it will be included in the next release.

**Comment by tkowark** [comment]
We just received a new issue regarding that functionality via email.
Model: Samsung Galaxy S8 SM-G950F, Android 9
Languages: French and German
App Version: Corona-Warn version 1.0.4, installiert am 30. Juni ca 23 Uhr.

The app still displays in English.

**Comment by duchampdev** [comment]
This PR was merged after the 1.0.4 version bump and will first be included in the upcoming version 1.0.5.

**Comment by tkowark** [comment]
Then let‘s close it again :-) thanks for the info!

**Comment by duchampdev** [comment]
@harambasicluka Unfortunately, I still see the previous behaviour with the just released version 1.0.5. Due to the restrictions for the ENS, I could not test this PR on my real device but could verify that it works with an app I developed myself. Furthermore, I guess it was tested at SAP as well. So I'd suspect that something in the build process prevented the change from being effective in the release build. Can you have a look at this or give me a hint on how to further investigate?
