### ISSUE TITLE
Allow (encrypted) app backups e.g. via SeedVault

### ISSUE THREAD

**Issue by Diapolo** [corona-warn-app/cwa-app-android#5479]
I'd like to propose a change in the app to allow CWA to be backedup via encrypted backups.

## Avoid duplicates
* [X] This enhancement request has not already been raised before
* [X] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation
Current CWA app doesn't allow encrypted backups via SeedVault (backup App for Android, integrated in LineageOS or CalyxOS, see https://calyxinstitute.org/projects/seedvault-encrypted-backup-for-android).

## Suggested Enhancement
Allow encrypted app backups :).
See https://github.com/seedvault-app/seedvault/wiki/FAQ#why-do-some-apps-not-allow-to-get-backed-up for a description of the problem and see this sample how Transport (Android app for public travel) implemented it: https://github.com/grote/Transportr/commit/4dc38f429f75909a088d8bd8a5b3b5ddd8030f71

## Expected Benefits
Allows a secure and easy app backup and restore including certificates.

---
Internal Tracking ID: EXPOSUREAPP-10053

**Comment by Ein-Tim** [comment]
Related issues:

- https://github.com/corona-warn-app/cwa-wishlist/issues/8
- https://github.com/corona-warn-app/cwa-wishlist/issues/500

**Comment by sapcoder123** [comment]
@Diapolo Thank you for reporting the issue!

Related issue is https://github.com/corona-warn-app/cwa-app-android/issues/4582

**Comment by mtwalli** [comment]
Not planned
