### ISSUE TITLE
Obsolete information regarding "whitelisting" for testers

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#5481]
In [README: Known Issues](https://github.com/corona-warn-app/cwa-app-android#known-issues) the first paragraph is outdated:

"The Exposure Notification API is going to block you from successfully testing the Application unless you are whitelisted inside GMS; **Shoutout to @pocmo for working on a demo mode to test unreleased app versions in advance without whitelisting (issue [#321](https://github.com/corona-warn-app/cwa-app-android/issues/321))**, if you want to contribute you can reach out [here](https://github.com/pocmo/cwa-app-android) for the time being - thank you!"

- It is true that it is not possible to test the CWA Android app exposure notification functions unless the Google account in use is allowlisted by Google, however many other functions of the app can be tested without being allowlisted.
- The issue #321, referenced by the README text, from @pocmo was closed on June 13, 2022 by @svengabr as obsolete.
- The CWA Android fork https://github.com/pocmo/cwa-app-android referenced by the README text was last updated in June 2020, which is more than 2 years ago.

The paragraph should be replaced by up-to-date information for testers.

**Comment by mtwalli** [comment]
@MikeMcC399  Do you suggest to keep only the sentence "The Exposure Notification API is going to block you from successfully testing the Application unless you are whitelisted inside GMS" ?

**Comment by MikeMcC399** [comment]
@mtwalli 

> Do you suggest to keep only the sentence "The Exposure Notification API is going to block you from successfully testing the Application unless you are whitelisted inside GMS" ?

It does seem that the text "Shoutout to @pocmo for working on a demo mode to test unreleased app versions in advance without whitelisting (issue https://github.com/corona-warn-app/cwa-app-android/issues/321), if you want to contribute you can reach out [here](https://github.com/pocmo/cwa-app-android) for the time being - thank you!" should be removed.

Leaving only "The Exposure Notification API is going to block you from successfully testing the Application unless you are whitelisted inside GMS" is only partially helpful. It should probably be added that whitelisting is only available for certain people and not for the community. Also, as I wrote in the OP, you don't need to be whitelisted in GMS to test functions which don't rely on the Exposure Notification API.

I can suggest a text for this if you want.

**Comment by mtwalli** [comment]
@MikeMcC399  Please add your suggestion? or if you want you can open a PR directly?

**Comment by MikeMcC399** [comment]
@mtwalli 

- I have submitted https://github.com/corona-warn-app/cwa-app-android/pull/5543 for your consideration

**Comment by mtwalli** [comment]
PR merged
