### ISSUE TITLE
Test result not available yet 4 days later

### ISSUE THREAD

**Issue by openmindculture** [corona-warn-app/cwa-app-android#5503]
## Technical details

- Device name: Pixel 4a
- Android version: 13
- App version: 2.25.0

## Describe the bug,  Steps to reproduce the issue

I got examined for a PCR test 4 days ago, on 25th August, got a QR code to scan in CWA which, since then, keeps showing "Test result not available yet". Today is 29 August. 

Tapping the "Update" button shows a spinning animation, then it returns to the same view, same message as before. No result, no information when to expect the result etc. I can't even be sure the app got any updated status information at all.

![Screenshot_20220829-094244](https://user-images.githubusercontent.com/6377941/187150746-b268b7dd-ec67-49bc-966b-13cbce1edc0d.png)

## Expected behaviour:
- provide test results in a timely manner
- add helpful information like expected result date or a contact phone number.

## Possible Fix, Additional context

Possibly also fix the root cause being that the current German government does not take COVID seriously enough anymore?!

**Comment by Ein-Tim** [comment]
Hey @openmindculture,

thanks for opening this issue!

I recommend you take a look at https://www.coronawarn.app/en/faq/results/#qr_test, the FAQ entry on exactly your problem.

The CWA team can't help you get access to the test result, so I recommend to contact the testing station which performed the test.

**Comment by MikeMcC399** [comment]
See also https://www.coronawarn.app/en/faq/results/#test_result_issues.

PCR results are expected to be delivered within 48 hours.

**Comment by openmindculture** [comment]
> See also https://www.coronawarn.app/en/faq/results/#test_result_issues.
> 
> PCR results are expected to be delivered within 48 hours.

Thanks! That information and contact option should best be integrated in the app.

**Comment by openmindculture** [comment]
And thanks support team for you quick intervention! The test result has finally arrived in my app.

**Comment by Ein-Tim** [comment]
@openmindculture 

Nice to hear that the result is now available! Could you please close this issue now?

**Comment by openmindculture** [comment]
> @openmindculture
> 
> Nice to hear that the result is now available! Could you please close this issue now?

Hi Tim, shouldn't I rather change its title? Information and contact options are still missing in the app, so that, apart from this single test result, the problem still exists!

**Comment by Ein-Tim** [comment]
@openmindculture I recommend to open a new issue in the https://github.com/corona-warn-app/cwa-wishlist repository. There is also a related issue from @vaubaehn open: https://github.com/corona-warn-app/cwa-wishlist/issues/795

**Comment by MikeMcC399** [comment]
@openmindculture 

> And thanks support team for you quick intervention! The test result has finally arrived in my app.

That is good! I doubt if anybody from the support team actually affected the delivery of your individual test result. It is more likely that the lab had not previously delivered the test result to the CWA Test Result Server (see [Solution Architecture](https://github.com/corona-warn-app/cwa-documentation/blob/main/solution_architecture.md)). Only the lab could report back about that though.

You can see on https://www.coronawarn.app/en/analysis/ that there were many PCR test results delivered every day (Test results provided) and that users were able to warn other users every day (Sharing behaviour).

**Comment by openmindculture** [comment]
The unresolved aspects are are covered by this existing issue:
[[PCR Test Result] Notify User to Retrieve Test Result from Testing Site when Test Result is not available in CWA after +48hrs #795](https://github.com/corona-warn-app/cwa-wishlist/issues/795) so I am closing this issue as a duplicate.

**Comment by MikeMcC399** [comment]
@openmindculture 

Did you intend to click on the close button?

**Comment by openmindculture** [comment]
> @openmindculture
> 
> Did you intend to click on the close button?

Yes I did, but fooled by the complex UI! Sorry I still suffer from COVID. But now I will actually close the issue. Thanks for pointing out!
