### ISSUE TITLE
Missing server component -- Trying to understand the apps behaviours

### ISSUE THREAD

**Issue by niklaslrks** [corona-warn-app/cwa-app-android#551]
Hi there,

I am currently trying to understand how the contact duration with other users influences the risk score. I got as far that the risk score is calculated with three different weights (among other factors) for three different types of durations. 
The sum of all durations 
... below the lower threshold
... equal or greater than the lower threshold
... equal or higher the the high threshold

The sum of those durations is provided and categorized by the ExposeureSummary of the GoogleAPI. The thresholds are initially set in de.rki.coronawarnapp.service.applicationconfiguration.ApplicationConfigurationService
However, the values that are used for the thresholds are referenced to a local object named attenuationDuration, which is not defined or declared anywhere. I assume the object is of the type AttenuationDuration, which is based in de.rki.coronawarnapp.server.protocols.ApplicationConfigurationOuterClass
The problem being: The server component is missing from the repository completely. My question obviously is, why is it missing, and furthermore, what are the values that are used for the attenuation thresholds for the lower and higher limit?

Thanks in advance and BR!

**Comment by markusmarkusz** [comment]
You probably mean that? https://github.com/corona-warn-app/cwa-server
(Or did I just misunderstand you there?)

**Comment by niklaslrks** [comment]
No, within the Android App the Package de.rki.coronawarnapp.server.protocols is referenced several times. However among packages like de.rki.coronawarnapp.risk or de.rki.coronawarnapp.services no package de.rki.coronawarnapp.server coexists. That particular component ist completely missing from the source code and I wonder why and what the content is (especially the threshold values).

**Comment by markusmarkusz** [comment]
@niklaslrks 
> de.rki.coronawarnapp.server.protocols.ApplicationConfigurationOuterClass

https://github.com/corona-warn-app/cwa-app-android/blob/master/Server-Protocol-Buffer/src/main/proto/applicationConfiguration.proto ?
(I'm not that familiar with protobuf and Kotlin, but this should be the "class" you're searching for?)

**Comment by corneliusroemer** [comment]
Related issue where I'm asking for precise values of the constants - rather than formula with variables that need to be set: https://github.com/corona-warn-app/cwa-documentation/issues/257

**Comment by niklaslrks** [comment]
> 
> 
> @niklaslrks
> 
> > de.rki.coronawarnapp.server.protocols.ApplicationConfigurationOuterClass
> 
> https://github.com/corona-warn-app/cwa-app-android/blob/master/Server-Protocol-Buffer/src/main/proto/applicationConfiguration.proto ?
> (I'm not that familiar with protobuf and Kotlin, but this should be the "class" you're searching for?)

This seems to be the file, thank you! Although the interpretation of the value 1 for the lower and 2 for the upper threshold is another task. But I will open another issue for that, this one is cleared up now. Thanks!
