### ISSUE TITLE
Impact of bluetooth visibility towards functionality

### ISSUE THREAD

**Issue by pheinz95** [corona-warn-app/cwa-app-android#553]
Android allows to set the visibility of the device. As a standart setting, it is set to invisible and I generally only set it to visible, when first connecting to another device.
Does this setting have any impact on the functionality of the app or can the phone still be contacted by other devices through the app?

**Comment by DE-Max-42** [comment]
As far as I know, the device does not have to be set to visible/discoverable. In addition, the device does not pair but only uses the bluetooth beacon funktion.

_Correct me if I'm wrong.
 I'm not 100% sure_

**Comment by pheinz95** [comment]
I assume the same, but this should explicitly be stated in the documentation/FAQ to avoid misunderstandings.

**Comment by tomjschwanke** [comment]
This setting should not impact the functionality of the app, since the app uses Google's API, which is in turn bases on Bluetooth LE (Low Energy). LE and classic Bluetooth are different technologies, so the visibility for classic BT shouldn't matter.

**Comment by heinezen** [comment]
This was answered a very long time ago, so I think we can close this.

----
Corona-Warn-App Open Source Team
