### ISSUE TITLE
Using OnePlus Slate Font displays Ä,Ö and Ü incorrectly

### ISSUE THREAD

**Issue by MagnificentMagician** [corona-warn-app/cwa-app-android#554]
OnePlus's OxygenOS lets users decide which font they want to use at device setup. They offer Roboto (AOSP's default one) and OnePlus Slate (OnePlus's default one). Having OnePlus Slate enabled when using CWA shifts the dots of ä,ö and ü clockwise in some cases.

For instance "Häufige Fragen" at the main screen is displayed correctly. It seems to me like only exactly the font and font size which is being used underneath in the app it is affected.

Picture - highlighted three examples: https://postimg.cc/WhmFJgTM

CWA 1.0.0
OnePlus 7 Pro
OxygenOS 10.0.6.GM21BA
OnePlus/OnePlus7Pro_EEA/OnePlus7Pro:10/QKQ1.190716.003/2005132200:user/release-keys

---
Internal Tracking ID: EXPOSUREAPP-1964

**Comment by tomjschwanke** [comment]
Cam confirm for my OnePlus 7 Pro running OxygenOS Beta 15

**Comment by NMisko** [comment]
The umlauts that are displayed incorrectly are vowels + diaresis:
e.g. `ü` (`u&#776;`) is displayed incorrectly
but a regular `ü` is displayed correctly.

Easiest way of fixing this is simply replacing them with the correct version.

**Comment by tomjschwanke** [comment]
Maybe propose that to #332 which is for changing text

**Comment by designrDevelopr** [comment]
Maybe I can give some additional information, as this problem hit me in several past projects: it seems to happen when the developer copies text from a PDF (offered by the customer) into a code editor. So this problem may return whenever legal texts get copied in the future.

**Comment by dsarkar** [comment]
Hi @MagnificentMagician, and community, could you please check and give us some feedback, if this issue still persists with CWA version 1.9.1. Many thanks. Best, DS

---
Corona-Warn-App Open Source Team

**Comment by Myer** [comment]
Does not happen on a colleague's OnePlus 6T with OnePlus Slate enabled:

CWA Version: 1.9.1, ENF Version: 18204516000

Modell: ONEPLUS A6013
Android-Version: 10
OxygenOS-Version: 10.3.7
Build: ONEPLUS A6013_41_201116
Kernel-Version: 4.9.179-perf+
#1 Mon Nov 16 20:02:42 CST 2020

**Comment by dsarkar** [comment]
@Myer, many thanks for the feedback. We will close this issue. Re-open if necessary, please. Best wishes, DS

---
Corona-Warn-App Open Source Team
