### ISSUE TITLE
App wird nur im "deutschen" Appstore angeboten

### ISSUE THREAD

**Issue by stephankn** [corona-warn-app/cwa-app-android#555]
App wird nur im "deutschen" play-store angeboten.

Das Handy meiner Frau ist noch auf einen "ausländischen" Play-Store eingestellt und der Download der App wird verweigert.

Das ist technisch unnötig und schränkt die Verwendungsmöglichkeit unnötig ein.
Bitte die Länderbeschränkung im Play-Store aufheben und/oder die apk-Datei zur Installation auf der Webseite oder alternativen Stores wie fdroid anbieten.

**Comment by Ich5003** [comment]
Duplicate of #478

**Comment by corneliusroemer** [comment]
Duplicate of #478 but good reminder that this issue is of highest priority and needs to be sorted asap. We haven't heard about it for 12hr. 

If a journalist reads this: you should be asking Bundesregierung, RKI and SAP about it, asap.

**Comment by Ich5003** [comment]
> Duplicate of #478 but good reminder that this issue is of highest priority and needs to be sorted asap. We haven't heard about it for 12hr.
> 
> If a journalist reads this: you should be asking Bundesregierung, RKI and SAP about it, asap.

#478 ist already a pinned issue, I think they already noticed this is a high priority issue.

**Comment by stephankn** [comment]
Sort of missed the pinned issue. I considered closing this as a duplicate, but as long as #478 is only a "question" and not a bug I prefer to not close it yet.

**Comment by corneliusroemer** [comment]
@stephankn Good point, I brought this to the attention of the person who created issue 478.

**Comment by SebastianWolf-SAP** [comment]
@stephankn Of course, #478 can get the bug label, just assigned it. Hereby closing this one as duplicate.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
