### ISSUE TITLE
Twitter Report: Booster recommendation push notification is sent every day

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-android#5557]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Samsung A3 (2016)
- Android version: 7.0
- App version: 2.26.0

## Describe the bug

The CWA sends a push notification reminding the user of the booster recommendation every day instead of just once.

## Steps to reproduce the issue

Not really clear when this happens.

## Expected behaviour

The app should only send one push notification and not one every day.

## Additional context

I asked the user to create an error log. 

## Internal Ticket 
[EXPOSUREAPP-13503
](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13503
)

**Comment by MikeMcC399** [comment]
@Ein-Tim 

- This problem has occurred before. See https://github.com/corona-warn-app/cwa-app-android/issues/5400 (which you were also involved in), so an error log may help identify underlying issues. Also screenshots would be helpful.

- The workarounds listed in https://github.com/corona-warn-app/cwa-app-android/issues/5400#issuecomment-1229159015 were as follows:

    1. Restart the device
    2. Reset the Corona-Warn-App
    3. Depending on the Android version it may also be possible to disable Corona-Warn/ Certificates notifications selectively in Android app settings. This should be available for Android 8.0+. The category only appears in the app settings after the app has already sent a Certificates notification. (Probably this will not work if the problem occurs on Android 7.0).
    4. Possibly also scan in a booster certificate if a booster vaccination has taken place.

**Comment by MikeMcC399** [comment]
Title typo: "is send" => "is sent"

**Comment by mtwalli** [comment]
@Ein-Tim  Thanks for reporting, Yes pls an error log would be appreciated.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Is your user still seeing this notification every day? Can you get screen-shots and an error log? If not, then perhaps this issue should be marked as stale, since it should only need one or two days to collect the information.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

- Perhaps PR https://github.com/corona-warn-app/cwa-app-android/pull/5576 is related to this issue?

**Comment by Ein-Tim** [comment]
@MikeMcC399
