### ISSUE TITLE
Is it intended that CWA does not display anything "special" if random-IDs have been deleted by the user in the Google settings?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-android#5559]
## Avoid duplicates
* [X] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Question is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Question has not already been asked in another issue

## Your Question
I deleted the collected Random-IDs in the Google settings to test something and wondered if it is intended that CWA does not seem to notice this change? The app displayed the same green risk card to me as it did before I deleted the random IDs.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

This is the way it has always been. There is no indication of what is stored by the Exposure Notifications System. In the past only users with rooted devices could find out manually what data was there.

**Comment by Ein-Tim** [comment]
@MikeMcC399 But do you know if CWA has some way to tell (from the API answers) that random-IDs have been deleted? I assume not, right?

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> But do you know if CWA has some way to tell (from the API answers) that random-IDs have been deleted? I assume not, right?

The RPIs are hidden. 

https://github.com/corona-warn-app/cwa-documentation/blob/main/solution_architecture.md#risk-calculation says:

"The app itself does not have access to the collected exposures, i.e. the Rolling Proximity Identifiers, and neither is it informed if a new one has been collected by the framework."

Logically, the app is also not informed if an RPI has been deleted either.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

I knew that the app can't access RPIs but I thought maybe the API informs the app about the user-initiated removal off data. 

Thanks for your answers!
