### ISSUE TITLE
Smartwatch Support

### ISSUE THREAD

**Issue by marfranke** [corona-warn-app/cwa-app-android#557]
## Feature description

Falls technisch möglich:
Unterstützung für Wear OS und andere Betriebsysteme für Smartwatches.
Das muss ja nicht den vollen Funktionsumfang der App betreffen. Aber zumindest die Erfassung der Begegnungen wäre eine wohl sinnvolle Ergänzung.

## Problem and motivation
Auch wenn heutzutage viele Menschen ihr Smartphone überall mitnehmen: Das betrifft nicht alle und nicht jede Gelegenheit. Zu meinen anfänglichen Bedenken bei dieser App gehörte auch, dass ich damit jetzt besser das Smartphone überall mit hin nehmen "muss"/"sollte", auch wenn's nur z.B. kurz in den Supermarkt ist. Aber grade an solchen Orten würde sich das volle Potential dieser App entfalten: Wenn Familienmitglieder oder Freunde erkranken, erfährt man das ja auch so über andere Kanäle als diese App, aber überall wo man auf Fremde trifft, ist so eine Lösung natürlich von Vorteil und deswegen ist möglichst häufige Mitnahme wichtig. Und die Unterstützung für Wearables könnte diese erhöhen.
Ein anderes Beispiel Outdoor Sport: Grade aufgrund der Tracking Fähigkeiten der meisten Smartwatches halte ich es für nicht unwahrscheinlich, dass einige anstelle des Smarphones lieber stattdessen zur Smartwatch greifen.

**Comment by tens0rfl0w** [comment]
Out of scope, that feature is up to Apple and Google as the „Corona-Warn-App“ only implements the given EN framework from the vendors that controls the Exposure tracking. So the devs have no control over the bluetooth interface/tracking process.

**Comment by jakobmoellersap** [comment]
Hi @marfranke , currently Exposure Detection via smartwatch is not planned. The only way to support this would be if Google enhanced its Framework with WearOS support. Right now, the only thing you can do is have your smartphone with you and receive notifications on your smartwatch.
