### ISSUE TITLE
Risk status not shown anymore

### ISSUE THREAD

**Issue by error401de** [corona-warn-app/cwa-app-android#5581]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy S21
- Android version: 12
- App version: 2.26.0

## Describe the bug

I can't see the status banner anymore (the green/red box that shows me if I had risk contacts in the last days or not.
This morning I saw that the last sync was yesterday afternoon, which is unusual. Therefore I stopped the app and started it again 2 or 3 times to trigger a fresh sync, which usually works. Instead, the status banner just disappeared.
I might be worth mentioning that there currently is a positive PCR result in my app.
Rebooting the device and wiping cache did not work.

## Steps to reproduce the issue

I don't know if it's possible to replicate

Can anybody help?

**Comment by Ein-Tim** [comment]
The box will come back
a) 7 days after registering the positive test
b) if you have an increased risk encounter

This is not a bug but the intended behaviour.

**Comment by error401de** [comment]
I see, thanks for the info!
So it vanished because my risk encounter is now > 10 days old.

Do you know why it is implemented like this? As you can see this is causing confusion.

**Comment by Ein-Tim** [comment]
@error401de

> So it vanished because my risk encounter is now > 10 days old.

Yes

> Do you know why it is implemented like this?

I can only assume that this was implemented in this way as the risk status is irrelevant if you are positive.

**Comment by error401de** [comment]
Yeah, I assumed this as well. To me, this is really counterproductive as
- it is confusing UX-wise
- It hides a very important learning: It is possible to get Covid without captured risk contacts. This should be clear for the majority of the people, but it's always good to get this visualised again.

I will leave this ticket open for a couple of days, maybe there will be an official statement.

**Comment by Ein-Tim** [comment]
@error401de 

I suggest you open an enhancement request reg. this in the https://github.com/corona-warn-app/cwa-wishlist repository.
From there, the team will take care of your issue (asses it, etc.).

**Comment by error401de** [comment]
Good hint, thanks!

**Comment by mtwalli** [comment]
@error401de As @Ein-Tim  already mentioned ,that is intended behaviour. if risk card is not `high` and you have a valid positive test in the app, risk card will be hidden, but the calculation will keep running in the background which means if the latest calculation turned into high in the mean time it will show up again. it does not make sense to show you that you are in `low` risk while you have a positive test in the app. Also after the test validity period is outdated the risk card will show up again

**Comment by error401de** [comment]
@mtwalli I do understand it wouldn't make sense to show "low risk" while being positive. Still it's confusing to just remove the box, especially after there is a high risk warning for a couple days. Which also doesn't make any sense to be shown, as it's obviously not just a risk anymore. So you can see: The way it's implemented now is not implied.

**Comment by mtwalli** [comment]
@error401de  Feel free to submit a wishlist request?  maybe that can highlighted in a better way

**Comment by error401de** [comment]
As announced I took care ;)  https://github.com/corona-warn-app/cwa-wishlist/issues/860
