### ISSUE TITLE
Availability of the APK outside of the play store

### ISSUE THREAD

**Issue by cellardoor27** [corona-warn-app/cwa-app-android#563]
Good evening,

I'm using a google app free android OS (LineageOS), is it possible to obtain the app somewhere else? I do not have, nor do I want the google play store on my phone, yet I would like to keep people safe.

Thanks and bye

**Comment by MikeJayDee** [comment]
Do you have Google Play Services? That would be required in any case. I guess there are some apk mirrors that have the apk.

**Comment by tomjschwanke** [comment]
APK availability outside the playstore isn't there, have a look at #477

Without Google Play Services, the app won't run, as it uses Google's API, see #75

**Comment by anetz89** [comment]
You may use Aurora Store (https://auroraoss.com/) to download Playstore-Apps without a Google Account, but you will also need Google Play Services (which can be installed on LineageOS as well) to get the app running.

**Comment by jhackenberg** [comment]
Though you need Google Play Services, it would be nice to have the app in other stores like F-Droid as well.

**Comment by SirBenG** [comment]
F-Droids [inclusion policy](https://f-droid.org/en/docs/Inclusion_Policy/) says that apps using Google Play Services are not allowed. If you need to download a play service dependent app without using the play store, Aurorastore, an apk mirror website or building from source are your best options. A FLOSS fork of the app that could be allowed in f-droid is being discussed in another issue.

**Comment by jakobmoellersap** [comment]
Hi @cellardoor27 , unfortunately as of now, we will only provide the application inside the official Google Play Store. Please also refer to #477 for more information regarding the APK topic.
