### ISSUE TITLE
PDF-Mass-Export sorts Certificates based on "Name/First Name", not on "Standardized Name/First Name"

### ISSUE THREAD

**Issue by jkrwdf** [corona-warn-app/cwa-app-android#5652]
## Avoid duplicates
* [X ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [?] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Google Pixel 4a (5G)
- Android version: 13
- App version: 2.27.2

## Describe the bug

When I export my certificates altogether into PDF, the order in which the pages are created seems to depend on the "name" field in the certificate instead of the "standardized name". 

Situation in which I observed this: 

I had 3 certificates issue to "Günter Maier" (name made up). 
Yesterday, I received a fourth one, but by accident, it was issued to "Guenter Maier". 

The standardized name is the same for all, and CWA shows the certificates nicely as a single tile, and in that tile, all 4 certificates are nicely ordered like the organ pipes (from bottom to top: 1/2, 2/2, 3/3, 4/4). 

But when I export the PDF, the certificates appear in this order: 

4/4, 1/2, 2/2, 3/3

Obviously, the sorting order here used the "Guenter" before "Günter" instead of "GUENTER" same as "GUENTER". 

Why is this an issue?

Of course it is only optical, but maybe this here is more convincing: 

In CovPass, there is a "mass-import", and processing my PDF there then produces my certificates in the obviously wrong order (4/4 at the bottom, followed by 1/2, ...). 

Again: No real issue, just optics (it "picks" the 4/4 of course). 

## Steps to reproduce the issue

See above.

## Expected behaviour

The order in which CWA displays the certificates in the app itself is also reflected in the PDF (from oldest to newest).

---
Internal Tracking ID: [EXPOSUREAPP-14161](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14161)

**Comment by dsarkar** [comment]
Dear @jkrwdf, thanks for opening this issue. However, the feedback we got is that this works as designed - certificates are sorted by name and first name.

Closing this issue. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by jkrwdf** [comment]
Hello @dsarkar ,

I hope this still reaches you although you already closed the issue. 

Thanks for your communication with the developers, but I fear from the given response that there was some information loss in either direction of this communication. 

I therefore shall try to explain my issue in other words in the hope that this convinces them there is an issue. 

The CWA has (at least) two situations in which the certificates of the users are grouped and ordered: 

1. In the "Certificates" tab, users are grouped (blue boxes) by the **standardized** name, and inside each box, the certificates of this users are ordered by the sequence number of the vaccination. 
2. In the PDF export of all certificates, the emission order is a sorting by **non-standardized** name and sequence number of the vaccination. 

Let me construct an example why this is suboptimal. 

Assume a family has two sons, Günther and Gunther. Both currently have a certificate for the vaccination 3/3, and the one for Günther has been issued to "Günther" (standardized: GUENTHER). 

The PDF output will contain:

1. Gunther (3/3)
2. Günther (3/3)

This order results from the fact that "ü" is higher than "u" for the Java-Code of the CWA.

Now, Günther gets his fourth vaccination, and this certificate is by accident issued to "Guenther". 

In the blue boxes, all is still fine, but the PDF now contains:

1. Guenther (4/4)
2. Gunther (3/3)
3. Günther (3/3)

You see that the certificates of Günther are now spread around in the PDF. 

This could be avoided by using the standardized name for the PDF sorting also. 

Best regards,
@jkrwdf
