### ISSUE TITLE
Mistakes in the German Terms of Service (Nutzungsbedingungen)

### ISSUE THREAD

**Issue by Julian1203** [corona-warn-app/cwa-app-android#566]
- Links aren't clickable
- "App" is capitalized at "1. Welche Funktionen hat die APP?"
- "Corona-Warn-App" sometimes isn't hyphenated ("Corona Warn App")
- "Open Source-Lizenzen" should be "Open-Source-Lizenzen" (hyphenated)
- Closing brackets are missing at "(transmission risk"
- One link still is a placeholder "[...] und Android finden Sie unter [Link]."
- There's no dot at the end of the sentences "Sie müssen immer die aktuelle Version der App verwenden", "Sie benötigen aktuelle Versionen von Android bzw. iOS", "Sie benötigen eine Datenverbindung" and "Die App muss auf dem Endgerät laufen und eingeschaltet sein"
-  "Open Source-Lizenzhinweise" should be "Open-Source-Lizenzhinweise" (hyphenated)
- "CWA- Dienste" should be "CWA-Dienste" (no space)
- "US Embargos" should be "US-Embargos" (hyphenated)

Also, in my opinion the the sub-headlines should be highlighted in some way to improve readability.
By sub-headlines, I mean things such as "Kein Anspruch auf bestimmte Funktionalität" and "Keine Verfügbarkeitszusage" under section 10.

**Comment by tomjschwanke** [comment]
Text, especially legal text, has to go through the team. Please report it's in #332

**Comment by marcmuschko** [comment]
@Julian1203 thanks for pointing this out!
Referencing this PR in #332 (thank you @tomjschwanke!), I am closing it here since our text and translation team has to verify the changes first and have them approved as well.
Best,
Marc
