### ISSUE TITLE
Suggestion to change "Rechtliche Hinweise" to "Open-Source-Lizenzen"

### ISSUE THREAD

**Issue by Julian1203** [corona-warn-app/cwa-app-android#568]
## Current Implementation
Under "App-Informationen", you can press a button called "Rechtliche Hinweise".

## Suggested Enhancement
Change the name to "Open-Source-Lizenzen" or something similar.

## Expected Benefits
It's less confusing to users who expect to find something else there or are confused by the fact that it's a long text in English.

**Comment by tomjschwanke** [comment]
Text changes go into #332

**Comment by marcmuschko** [comment]
@Julian1203 thanks for pointing this out!
Referencing this PR in #332 (thanks @tomjschwanke !), I am closing it here since our text and translation team has to verify the changes first and have them approved as well.
Best,
Marc
