### ISSUE TITLE
Low Risk display shows after one day of usage: "1 of days active" : wrong english

### ISSUE THREAD

**Issue by schmitti73** [corona-warn-app/cwa-app-android#569]
Better / correct english: 

1 day(s) of activity

**Comment by tomjschwanke** [comment]
Changes to in-app text go into #332

**Comment by bocops** [comment]
I'm seeing the same. This was apparently fixed in #446 already.

**Comment by jakobmoellersap** [comment]
Fixed in 1.0.2
