### ISSUE TITLE
Statistic of contacts

### ISSUE THREAD

**Issue by NiBurhe** [corona-warn-app/cwa-app-android#570]
## Feature description

Show a statistic in the risk status how many contacts did you have. Maybe you can click on it to get a detailed statistic for each of the previous 14 days. Statistics are created locally, so nobody else know them. 

## Problem and motivation
No really is any problem, but I find the information interesting and it could be interesting for others too. So it makes the app more attractive and not collecting any more data, just using the hidden existing one. 

## Is this something you're interested in working on

No

**Comment by tomjschwanke** [comment]
AFAIK, this is currently not possible with the API, see #492

**Comment by NiBurhe** [comment]
Thanks for the info
