### ISSUE TITLE
What you have to clarify for DAU or average users

### ISSUE THREAD

**Issue by cannothing** [corona-warn-app/cwa-app-android#572]
> What does this mean, the Spiegel article does not help ...
> 
> Can I savely ignore that message and the app still works as expected?

> 
> 
> Here's an article by Spiegel summarising. I think that's very good to know and could be linked in the FAQs potentially to give an independent position and assuage concerns.
> https://www.spiegel.de/netzwelt/apps/corona-warn-app-wieso-muessen-android-nutzer-den-standortzugriff-aktivieren-a-7f372aea-25e9-49f7-9ae3-9568cf526c04

This article do not help. This article repeat what the developer are saying. The app do not use Standortinformationen. The issue is,, which is not clarified by this article, I have to allow google to use Standortinformationen, if I activate two of three possible settings. The third option is GPS. Google is not allowed to use this informations, but this need much more energy.
In a pragmatic view, you have to allow google to use Standortinformation, to use the app, because you don't want run out off energy.

I made a [screenvideo ](https://drive.google.com/file/d/1Gep_p3x46ST_H7CpEH4fqoCivyGoFvFG/view?usp=sharing) trying to avoid GPS. No way, if I refuse to transmit information to google.

Phone is a S7 with Android 8.

My problem and the problem of https://github.com/corona-warn-app/cwa-app-android/issues/262#issuecomment-645015568 have to be clarified.

1. Works the app with switched off Standort
2. If I have to switch on Standortermittlung, 

- what data gets google
- how to save energy because of running gps, to avoid transmission of data to google.

There is a third issue, is cwa working, if I am using energysaving of my phone or using energysaving apps.

I have got answers, which where not useful for an average user.

Und deswegen auf Deutsch weiter.

Ein Vorschlag für die FAQ.

Muss ich die Standortfunktion aktiviert haben.
Ja/Nein

Wenn ich die Standortfunktion aktiviere, werden Daten an Google übertragen.
Ja/Nein/Herumgeeiere, dass es nur anonymisierte sind

Wenn ich die Standortfuntion aktiviere, erhöht sich mein Energieverbauch durch die Aktivität des GPS-Sensors
Ja/Nein

Muss ich meine Energiesparfunktion/App abschalten
Ja/Nein/Kommt darauf an

Und bitte den Mitarbeiter auswechseln, der auf solch einfache Normalonutzeranfragen, so antwortet:
> 
> 
> es handelt sich hier um eine Besonderheit des Betriebssystems Android, die nicht umgangen werden kann und auch nicht umgangen werden darf. Bluetooth kann immer nur zusammen mit Standortinformationen eingeschaltet werden. Details dazu sind in der Android Bluetooth Entwickler-Dokumentation (https://developer.android.com/guide/topics/connectivity/bluetooth) erklärt.
> 
> In unserer FAQ und allen damit zusammenhängenden Kommunikationskanälen erklären wir jedoch deutlich, dass wir kein GPS verwenden, z.B. hier: https://www.coronawarn.app/de/faq/
> 
> Weitere Details dazu und zu einer vorherigen Diskussion finden Sie unter https://github.com/corona-warn-app/cwa-app-android/issues/262. Vielen Dank für Ihr Verständnis!
> 
> Mit freundlichen Grüßen/Best regards,
> SW
> Corona Warn-App Open Source Team

**Comment by tkowark** [comment]
I hope it's ok that we'll concentrate these discussions on #491 
Alls answers given there will then be condensed in the FAQs and be made as explicit as we can to not confuse users about this topic.

**Comment by cannothing** [comment]
I hope it is okay, I am uninstalling the app. I am pissed off to gt a simple answer to simple questions. I do not have to read a lot of english stuff, as a German for a  German app paid by the German Goverment.

 

 

 

Von: Thomas Kowark <notifications@github.com> 
Gesendet: Mittwoch, 17. Juni 2020 12:02
An: corona-warn-app/cwa-app-android <cwa-app-android@noreply.github.com>
Cc: cannothing <ich@stephan-zitzmann.de>; Author <author@noreply.github.com>
Betreff: Re: [corona-warn-app/cwa-app-android] What you have to clarify for DAU or average users (#572)

 

I hope it's ok that we'll concentrate these discussions on #491 <https://github.com/corona-warn-app/cwa-app-android/issues/491> 
Alls answers given there will then be condensed in the FAQs and be made as explicit as we can to not confuse users about this topic.

**Comment by tkowark** [comment]
Hallo @cannothing ,

Sie müssen sich nicht seitenweise englische Kommentare durchlesen. Wie oben geschrieben arbeiten wir daran die FAQs zu konkretisieren, wir müssen nur bis dahin zusehen auch bei den vielen Github Issue Dopplungen zu vermeiden.

Und auch wenn wir ihren Ärger verstehen können, bitten wir sie unsere [Code of Conduct](https://github.com/corona-warn-app/cwa-documentation/blob/master/CODE_OF_CONDUCT.md) zu beachten und weder um die Entlassung einzelner Mitarbeiter bitten, noch die hier nicht wiederholte Sprache aus ihrer letzten Antwort zu benutzen. 

Viele Grüße,
TK
Corona-Warn-App Open Source Team

**Comment by cannothing** [comment]
Ich übersetze, wir haben da eine App in die Welt gesetzt, bei der wir nicht wissen, wie sich die Googleschnittstelle verhält, ob die Daten weitergibt oder ob sie Energie verbrät. So etwas kann man sich früher überlegen.

 

Auch wenn man Opensource macht, muss man nicht die schlechte Angewohnheit von Opensource übernehmen, sich vom Nutzer die Probleme hintertragen lassen und das noch als Akt der Gnade betrachten. 

 

Von: Thomas Kowark <notifications@github.com> 
Gesendet: Mittwoch, 17. Juni 2020 12:50
An: corona-warn-app/cwa-app-android <cwa-app-android@noreply.github.com>
Cc: cannothing <ich@stephan-zitzmann.de>; Mention <mention@noreply.github.com>
Betreff: Re: [corona-warn-app/cwa-app-android] What you have to clarify for DAU or average users (#572)

 

Hallo @cannothing <https://github.com/cannothing>  ,

Sie müssen sich nicht seitenweise englische Kommentare durchlesen. Wie oben geschrieben arbeiten wir daran die FAQs zu konkretisieren, wir müssen nur bis dahin zusehen auch bei den vielen Github Issue Dopplungen zu vermeiden.

Und auch wenn wir ihren Ärger verstehen können, bitten wir sie unsere Code of Conduct <https://github.com/corona-warn-app/cwa-documentation/blob/master/CODE_OF_CONDUCT.md>  zu beachten und weder um die Entlassung einzelner Mitarbeiter bitten, noch die hier nicht wiederholte Sprache aus ihrer letzten Antwort zu benutzen.

Viele Grüße,
TK
Corona-Warn-App Open Source Team
