### ISSUE TITLE
URSACHE: 9002 - Failed to connect to svc90.main.px.t-online.de/:::443

### ISSUE THREAD

**Issue by DodoTheDuck** [corona-warn-app/cwa-app-android#574]
## Describe the bug

I setup the app without any problem, and did use it for one day. Today, it tells me

"URSACHE: 9002 - Failed to connect to svc90.main.px.t-online.de/:::443"
Can't screenshot you the stacktrace, because for whatever reason, I am not allowed to make screenshots inside the app.

## Expected behaviour

The problem not to popup 😄 

## Steps to reproduce the issue

Opening the app is enough. Clearing the cache might help, but this will (I think), get rid of my data collected, which is contraproductive. 

## Technical details

Android 10 (Buildnumber QQ3A.200605.001)
Google Pixel 4 XL

## Possible Fix

Never seen the port annotation /:::443

## Additional context

Why are screenshots not allowed? There should be either the possibility to make screenshot on Android (on iOS its allowed) or at least have a stacktrace export in case of an error. 

From my Java experience, here are some files and lines with the problems (not gonna type every last line):
java.net.ConnectionException: Failed to connect to svc90.main.px.t-online.de/:::443
RealConnection.kt:23
ExchangeFinder.kt:143
ExchangeFinder.kt:1
ConnectInterceptor.kt:16
RealInterceptorChain.kt:14
CacheInterceptor.kt:197
RealInterceptorChain.kt:14
BridgeInterceptor.kt:36
RealInterceptorCHain.kt:14
RetryAndFollowUpInterceptor.kt:31

**Comment by jakobmoellersap** [comment]
Thanks for your issue report! Can you kindly give us some more details or tell us if the issue still persists? Especially the first few lines of the details of the error dialog would help a lot in this case!

**Comment by MikeJayDee** [comment]
Just as an aside: Clearing the cache or even all data should not be a problem in my view; the received rolling proximity identifiers, and the daily tracing keys used to calculate the sent rolling proximity identifiers are not stored by the app, but by the API.

Would be good if someone could confirm.

The only disadvantage might be that the app would then incorrectly state that it has only been active for a day, but that's just a minor inconvenience (I had the Latvian app installed for two weeks or so, so in principle the CWA should show "14 of 14 days active" for me, but as the app does not have this information, it only shows "1 of 14 days active").

**Comment by jakobmoellersap** [comment]
Hey @MikeJayDee ! For us, it would greatly help our efforts in maintaining our issues if you could open up a separate issue with this exact question in mind. This helps us keep topics separated.

**Comment by DodoTheDuck** [comment]
@jakobmoellersap clearing the cache didn't help. Clearing the memory content actually did help. Sorry I tried that before talking an actual photo of the error. If the error reappears, I will take a photo of the stacktrace. For now I can only provide the photo attached. I will keep you posted.
![WhatsApp Image 2020-06-17 at 07 07 02](https://user-images.githubusercontent.com/30998176/84877383-b829a800-b088-11ea-8c24-4f0d391fba45.jpeg)

**Comment by jakobmoellersap** [comment]
The error suggests an error during the buildup of the TLS Handshake and should be very uncommon as this would indicate an error before the real Handshake even happens (which would be caught by a different Error in the Transport Layer of OkHTTP). 

Could you please ensure that you can replicate somehow? Otherwise, the error is extremely hard to reproduce.

**Comment by DodoTheDuck** [comment]
I know that feel. Give me a day or two, and I will let you know if I was able to reproduce it.

**Comment by trololo9000** [comment]
Hm maybe  there is a bug in the manifest? The app doesn't request any network access permissions.
Way down in the details it says:
.....
java.net.Socket.connect(Socket.java:621) at m0.p0.h.e (Platform.kt:1) at m0.p0.g.i.e(RealConnection.kt:16)
... 23 more
Caused by: android.systemErrnoException: connect faileed: EACCES (Permission denied) at libcore.io.Linux.connect(Native Method)
.....

**Comment by jakobmoellersap** [comment]
@trololo9000 Regarding your suggestion:
`<uses-permission
        android:name="android.permission.INTERNET"
        android:required="true" />`

Snippet from the Manifest would suggest otherwise.

**Comment by trololo9000** [comment]
I can confirm the suggestion, must be another cause. :-/
![Screenshot_2020-06-18-15-10-33-092_com google android permissioncontroller](https://user-images.githubusercontent.com/67066643/85024324-39129d80-b176-11ea-81e0-861b889b3837.jpg)

**Comment by DodoTheDuck** [comment]
@jakobmoellersap can not reproduce it. It just appears. But i managed to make a screenshot of the stacktrace. I will not clear my cache, let me know if you need anything else.
![2020_06_18_16 24 11](https://user-images.githubusercontent.com/30998176/85032710-6fedb100-b180-11ea-956d-24bfb574c119.jpg)

**Comment by jakobmoellersap** [comment]
You have a connection refused error. Do you tamper with the connection by any chance?

**Comment by DodoTheDuck** [comment]
I messed around with my private DNS. t-online was blocked there. Disableing it was the solution. Sorry for the confusing and timeconsumption.

**Comment by jakobmoellersap** [comment]
No worries, thanks for updating us about this issue! It will hopefully also help out other community members in the future!
