### ISSUE TITLE
Projekt verschwendet Steuergeld

### ISSUE THREAD

**Issue by stefpb** [corona-warn-app/cwa-app-android#5740]
220 Millionen Euro wäre besser woanders aufgehoben. Bitte die Entwicklung sofort einstellen, die App wird nicht mehr benötigt.

https://www.zeit.de/gesundheit/2022-12/gesamtkosten-corona-warn-app-gesundheit-millionen

https://www.tiktok.com/@ralph.frefat/video/7172973321670233350

**Comment by brianebeling** [comment]
Closed as not development related
