### ISSUE TITLE
Provide a solution for older Android

### ISSUE THREAD

**Issue by rhaschke** [corona-warn-app/cwa-app-android#577]
Obviously the app is designed to work only on the latest Android versions.
It's completely unclear to me, how we want to achieve a high usage across Germany's population, if this app essentially requires many people to buy a new phone! All 5 phones in our family are not supported. Did the developers think about this at all?
IMHO, such an app should target phones as old as 5 years - or even older, definitely everything which is still supported by popular apps like WhatsApp.
I understand that you wanted to use the latest OS features for highest security, but if that renders the app unusable for most of the people, this is defeating the idea of the app.
Maybe think about another version for older Android system, that in turn relaxes some security concerns (of course informing the users about that fact).

**Comment by bersbersbers** [comment]
I feel you should provide more information on your unsupported devices. I need to guess you are using Android < 6.0, since the app is compatible with Android "6.0 and up" [1]. The COVID-19 Exposure API by Google is only available for these newer Android versions [2]:
> For your app to work on a device, the device must be running Android version 6.0 (API
version 23) or higher.

As far as I can see, there is no way for the developers to use this API on Android < 6.0. 


[1] https://play.google.com/store/apps/details?id=de.rki.coronawarnapp
[2] https://static.googleusercontent.com/media/www.google.com/en//covid19/exposurenotifications/pdfs/Android-Exposure-Notification-API-documentation-v1.3.2.pdf, page 3

**Comment by rhaschke** [comment]
I am using Android 4.4.2. Corresponding phones are still sold nowadays, e.g. [Sony Xperio Z1](https://www.amazon.de/Sony-Compact-Smartphone-Touch-Display-Speicher-Pink/dp/B00HQDV7P6/ref=pd_lpo_107_img_0/257-2919459-4814218?_encoding=UTF8&pd_rd_i=B00HQDV7P6&pd_rd_r=6e759a05-31f1-4c80-9c82-68e0c0065c30&pd_rd_w=3NPBR&pd_rd_wg=NiFJ2&pf_rd_p=d5c9797d-0238-4119-b220-af4cc3420918&pf_rd_r=M9S1NVQC881X6BWBWZP2&psc=1&refRID=M9S1NVQC881X6BWBWZP2).

**Comment by rhaschke** [comment]
My point is that the decision of using an API requiring Android 6.0 was wrong, ruling out many phones in use.

**Comment by bersbersbers** [comment]
> I am using Android 4.4.2. Corresponding phones are still sold nowadays, e.g. Sony Xperio Z1
> My point is that the decision of using an API requiring Android 6.0 was wrong, ruling out many phones in use.

Unless I am mistaken, that phone received its latest security update (on Android 5.1.1) in December 2015, with version 14.6.A.1.236. Your latest security update is likely even older. Not supporting devices that include 5+ years worth of security holes for the sake of not having to implement the API on one's own is not a decision I would plainly call "wrong".

**Comment by speedy-1702** [comment]
As you can see in the list of android versions [here](https://de.wikipedia.org/wiki/Liste_von_Android-Versionen), Kitkat is unupported since long. How should the cwa developers consider to use those old versions? IMAO it was a good compromise to set the requirement to Android >6.0.

**Comment by BjoernPetersen** [comment]
Generally, I think it's a shame that Android phones typically only receive software support up to two years after their release date. In fact, it's a terrible state of affairs and manufacturers should be obligated to change their behavior. That being said, there's nothing the developers of this app can do about that and, as @bersbersbers already said, it isn't feasible for support older OS versions right now.

**Comment by rhaschke** [comment]
The goal here was not to create a fancy new app, which could be used by some people if they like. This was going to address the majority of people in Germany! If common apps like WhatsApp are able to support an OS as old as KitKat, then the Corona app should do as well. If we don't reach a decent coverage within the population, this app will be kind of useless.

**Comment by tomjschwanke** [comment]
See #165

**Comment by tkowark** [comment]
Thanks fo your comment. Neither of the apps you mentioned uses the Exposure Notification Framework, which is a prerequisite for the current app. As Google made the decision to provide this for API versions 23+, we cannot fix this issue by ourselves w/o reimplementing the ENF.

**Comment by mahoe** [comment]
Hi Robert,
it's not only the OS version the device itself has to provide
bluetooth chips that can work with the low energy profile.
You mentioned that the app has to target the majority of the country's
population. Yes that's right!

Here you can find some data about the installed versions of Android:
https://de.statista.com/statistik/daten/studie/180113/umfrage/anteil-der-verschiedenen-android-versionen-auf-geraeten-mit-android-os/


and IOS:
https://t3n.de/news/verbreitung-ios-12-70-prozent-1130480/

On the other hand supporting older versions would increase the budget
needed a lot. So in the end it's not a simple question and I'm sure this
was not an easy decision.


Am Mi., 17. Juni 2020 um 10:04 Uhr schrieb Robert Haschke <
notifications@github.com>:

**Comment by rhaschke** [comment]
@mahoe thanks for this great statistics link. According to this, we will achieve at most 75% coverage, which is a pity. According to https://github.com/corona-warn-app/cwa-app-android/issues/165#issuecomment-638875255, it is Google to blame for providing the [Exposure Notification Framework](https://www.heise.de/news/Apple-und-Google-veroeffentlichen-Schnittstellen-fuer-Corona-Warn-Apps-4726167.html) only for Android >= 6.0.

**Comment by speedy-1702** [comment]
There are brandnew smartphones with Android >=6.0 [available](https://www.welt.de/wirtschaft/webwelt/article194093365/Einsteiger-Smartphone-Guenstige-Handys-mit-guter-Leistung.html) for around 70€.

This might be a better solution, than fighting against Google's policy.

**Comment by rhaschke** [comment]
@speedy-1702, actually I'm looking for a new phone since years, but I want to have a small one (less than 4,5") but the market only focusses on large phones >> 5". Hence, I'm still stuck with an old one.

**Comment by lpfann** [comment]
> 
> 
> @speedy-1702, actually I'm looking for a new phone since years, but I want to have a small one (less than 4,5") but the market only focusses on large phones >> 5". Hence, I'm still stuck with an old one.

Maybe [this](https://www.ogadget.com/x/jelly-2?utm_medium=mrmobile&utm_source=mrmobile) is something for your taste.

Regarding the topic in general:
I think supporting Version 4 of Android is not worthwile considering the low market share when including iphones (less than 10%).
Most likely most of devices in that generation do not support Bluetooth low energy.

Android Version 5 on the other hand has a bigger, significant market share and maybe Google could backport the changes in Play Services for those devices when they support BLE.

PS: @rhaschke great seeing another CITEC member here. :)

**Comment by corneliusroemer** [comment]
There's actually a question about whether Android 5 is not enough on the Google API repo, Google's reference implementation needs only Android 5: https://github.com/google/exposure-notifications-android/issues/16
