### ISSUE TITLE
Zertifikate lassen sich nicht erneuern

### ISSUE THREAD

**Issue by Byggvir** [corona-warn-app/cwa-app-android#5777]
Es gibt keine Option „Zertifikat erneuern“, wie beschrieben ist.

Entgegen der Beschreibung erscheint im „Status-Nachweis“.

Ich frage mich, warum es unter dem Zertifikat im Hinweis darüber, dass es abgelaufen ist, nicht statt einer langatmigen Erklärung und einem Querverweis auf eine andere Stelle nicht möglich ist, kurz und knappe eine Button „Zertifikat erneuern“ unterzubringen?

---
Internal Tracking ID: [EXPOSUREAPP-13380](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13380)

**Comment by dsarkar** [comment]
Guten Morgen @Byggvir,

Generell werden Sie eine Benachrichtigung bekommen, wenn ein Zertifikat erneuert oder ausgetauscht werden muss, siehe FAQ-Artikel: [Wie und wann können Zertifikate in der App neu ausgestellt werden?](https://www.coronawarn.app/de/faq/results/#dcc_replacement_howto).

> 
> Erhalten Sie eine entsprechende Nachricht in der Corona-Warn-App, können Sie freiwillig ein neues Impfzertifikat bzw. Genesenenzertifikat kostenlos über die App anfordern. Nachdem Sie Ihr Einverständnis gegeben haben, übermittelt die App das Zertifikat oder mehrere Zertifikate zur Überprüfung an das RKI, welches ein aktualisiertes Zertifikat ausstellt und an Ihre App übermittelt. Sie finden das aktualisierte Zertifikat dann in der Zertifikate-Registerkarte.
> 
> Das alte Zertifikat wird automatisch in den Papierkorb verschoben und nach 30 Tagen gelöscht. Das alte Zertifikat kann innerhalb der 30 Tage jederzeit wiederhergestellt werden.
> Die Möglichkeit zur Neuausstellung beginnt 28 Tage vor dem Ablauf des Zertifikats und endet 90 Tage nach dem Ablauf des Zertifikats.
> WICHTIG: Die Neuausstellung kann innerhalb dieses Zeitraums maximal drei Mal getätigt werden. Wir empfehlen Ihnen wegen dieser Beschränkung das neu ausgestellte Zertifikat als PDF-Datei zu exportieren und auszudrucken damit Sie bei Bedarf den QR-Code des Zertifikats erneut einscannen können (siehe "[Wie erstelle ich einen Ausdruck meines Digitalen COVID Zertifikates der EU?](https://www.coronawarn.app/de/faq/results/#eu_dcc_export)"
> Siehe auch FAQ-Artikel:
> 
> [Warum werden Zertifikate neu ausgestellt?](https://www.coronawarn.app/de/faq/results/#dcc_replacement)
> [Welche digitalen COVID Zertifikate der EU werden neu ausgestellt?](https://www.coronawarn.app/de/faq/results/#dcc_replacement_which)
> [Verliere ich meinen Impfstatus wenn eines meiner Zertifikate abläuft?](https://www.coronawarn.app/de/faq/results/#dcc_replacement_vac_status)
> [Ich kann ein Zertifikat in der App nicht erneuern. Woran kann das liegen?](https://www.coronawarn.app/de/faq/results/#dcc_replacement_issues)
> [Gültigkeit eines EU digitalen COVID-Zertifikats.](https://www.coronawarn.app/de/faq/results/#glossary_validity)

**In folgenden Fällen können Zertifikate nicht über die App erneuert werden:**
Siehe FAQ-Artikel: [Ich kann ein Zertifikat in der App nicht erneuern. Woran kann das liegen?](https://www.coronawarn.app/de/faq/results/#dcc_replacement_issues)
- Lediglich für den Impfstatus relevante Zertifikate können erneuert werden, beispielsweise [Auffrischimpfungen](https://www.coronawarn.app/de/faq/results/#glossary_auffrischimpfung) oder Genesenenzertifikate.
- Das Zertifikat ist noch länger als 28 Tage gültig.
- Das Zertifikat ist bereits vor mehr als 90 Tagen abgelaufen. In diesem Fall ist die Neuausstellung innerhalb der App nicht mehr möglich. Bitte wenden Sie sich an eine Apotheke, um ein neues Zertifikat zu erhalten.
- Nur das Impfzertifikat mit dem neusten Ausstellungsdatum kann neu ausgestellt werden.
- Nur in Deutschland ausgestellte Zertifikate können über die App erneuert werden.
- Die Anzahl der Neuausstellungen ist auf drei Neuausstellungen je Zertifikat begrenzt.
- Ihre Corona-Warn-App wurde nicht auf die Version 2.23 aktualisiert. Bitte nehmen Sie ein Update vor.

Evtl trifft einer dieser Punkte bei Ihnen zu, evtl. der erste?

Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by GisoSchroederSAP** [comment]
> Es gibt keine Option „Zertifikat erneuern“, wie beschrieben ist.
> 
> Entgegen der Beschreibung erscheint im „Status-Nachweis“.
> 
> Ich frage mich, warum es unter dem Zertifikat im Hinweis darüber, dass es abgelaufen ist, nicht statt einer langatmigen Erklärung und einem Querverweis auf eine andere Stelle nicht möglich ist, kurz und knappe eine Button „Zertifikat erneuern“ unterzubringen?
> 
> Internal Tracking ID: [EXPOSUREAPP-13380](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13380)

Was oben steht ist korrekt und bedeutet in kurz: Wenn das Zertifikat die Bedingungen erfüllt, gibt es auch den Button zum "Zertifikat erneuern". Aber eben nicht jedes Zertifikat kann erneuert werden.

**Comment by Ein-Tim** [comment]
@GisoSchroederSAP Ich denke, es wäre tatsächlich gut, diesen ewig langen Text, der erklärt, warum eine Neuaustellung nicht notwendig ist, etwas kürzer zu machen und auch die verschiedenen Optionen rauszunehmen. Siehe dazu: https://github.com/corona-warn-app/cwa-wishlist/issues/839

**Comment by dsarkar** [comment]
@Ein-Tim, you mean to shorten the FAQ article, or the text shown in the app (which is your suggestion in https://github.com/corona-warn-app/cwa-wishlist/issues/839), or both.

**Comment by Ein-Tim** [comment]
@dsarkar 

Shorten & make the in-app text easier is most important.

**Comment by GisoSchroederSAP** [comment]
We can, certainly, request to shorten the text in the App. But to be fair, I have serious doubts, this will be done. It would require a new round of approval and a translation. And the benefit? That we explain with less words, why not all certificates can be renewed.
And in the end, the "long" version of the explanation is still required somewhere else, right? 

Having stated this, what would be a suggestion for a more concise text block, that legally covers the above aspects? I'm happy to let the PO know, that a smarter phrase will make the app more valuable for the users.

**Comment by Ein-Tim** [comment]
@GisoSchroederSAP The optimal out coming would not be a shorter text, but as I described in https://github.com/corona-warn-app/cwa-wishlist/issues/839 would be a dynamic text. So the user is only shown the information that is actually relevant in their case. So if I don't need to reissue my certificate, just show "Keine Erneuerung notwendig" and not "If this is not your currently used certificate [...]" and so on...

**Comment by GisoSchroederSAP** [comment]
Okay, I got it. Will see, what our DEV team thinks about this. 
Thank you.

**Comment by Byggvir** [comment]
Thanks, I found a work-a-round. 

I deleted the newer certificates and reimported them.

**Comment by Ein-Tim** [comment]
@Byggvir In this case, please close this issue!

**Comment by Byggvir** [comment]
Works obviously as designed, but poorly described.

Closed.
