### ISSUE TITLE
Samsung S8 - Google API Errors

### ISSUE THREAD

**Issue by 0xA1B2** [corona-warn-app/cwa-app-android#580]
![Screenshot_20200616_105248](https://user-images.githubusercontent.com/55597745/84871989-29615f00-b079-11ea-8986-4ceeb346d353.jpg)

**Comment by 0xA1B2** [comment]
![2020-06-17 09 08 55](https://user-images.githubusercontent.com/55597745/84872629-0c795b80-b07a-11ea-8664-d6860fb5a095.jpg)

**Comment by ChuangSheep** [comment]
Duplicated. Please refer: #508 and #499
