### ISSUE TITLE
Does a failing RootBeer check prevent users from warning others using the SRS feature?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-android#5813]
## Avoid duplicates
* [X] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Question is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Question has not already been asked in another issue

## Your Question
The app perfroms RootBeer checks to detect if the device is rooted. If the RootBeer check fails, will this disable the ability to use others using the new SRS feature of version 3.0? Or will the SafetyNet attestation also fail in all cases where the RootBeer check fails?

**Comment by thomasaugsten** [comment]
The SafetyNet attestation is very similar to the RootBeer checks. 
But only the SafetyNet attestation is used to ensure the rate limit for SRS submissions.

**Comment by Ein-Tim** [comment]
@thomasaugsten Thanks for the fest answer, however, I'm not sure, I fully understand. Let's get concrete:
If I root my device, which leads to a failing RootBeer check, will I be able to warn others using the SRS feature (because SafetyNet attestation succeeds) or will this not be possible (because attestation fails)?

**Comment by thomasaugsten** [comment]
SafetyNet will also check for root access and the attestation will fail

**Comment by Ein-Tim** [comment]
Thanks, answered!

**Comment by MikeMcC399** [comment]
@Ein-Tim 

This case should probably also be added to the description on
https://www.coronawarn.app/en/faq/results/#rooted_devices "[Google/Android]: Can I use the app on a rooted device?"

Maybe you would like to propose a PR for this, since you initiated this topic?

**Comment by Ein-Tim** [comment]
@MikeMcC399 I'll take care of that later today!
