### ISSUE TITLE
Why does this error exist?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-android#5817]
A user on Twitter [posted this](https://twitter.com/jimmyfreak88/status/1617540238288773122?s=46&t=4yaH7MA4nZSzAR_wMYdDLQ) screenshot of the CWA:
<img src="https://user-images.githubusercontent.com/67682506/214079986-f3d7c6cf-9e48-48e6-927d-057ef4b1ada5.jpeg" width="300">

Why does this error exist? CWA only considers the last 10 days so this error isn't an error.

---
Internal Tracking ID: [EXPOSUREAPP-14630](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14630)

**Comment by mlenkeit** [comment]
@Ein-Tim thanks for raising this! This message is designed as a security means to protect the server in case there are too many key submissions. The number (i.e. 10) is configurable, so that we can adjust it if there was too much traffic. At the moment this mechanism should not be activated.

As you correctly mentioned, CWA anyway only considers the last 10 days and this message should not show up. My assumption is that by some means, the app submitted keys that were older than 10 days. I'll try to figure out why this happens. Is this the only report so far that you've seen?

For what it's worth, it's not an error message but just a notice 😉

**Comment by Ein-Tim** [comment]
@mlenkeit FYI: https://twitter.com/Jimmyfreak88/status/1617591246427672576?s=20 seems like Ursache10 also plays a role here.

**Comment by mlenkeit** [comment]
> @mlenkeit FYI: https://twitter.com/Jimmyfreak88/status/1617591246427672576?s=20 seems like Ursache10 also plays a role here.

@Ein-Tim thanks for referencing the tweet. This might indeed be a series of events. Ursache10 has always been very hard (not to say _impossible_) to reproduce, let's see if we find a link between the two.

**Comment by Ein-Tim** [comment]
@mlenkeit

Have you tried warning yourself yet? Here's a second user reporting the same issue: https://twitter.com/muc_neko/status/1617893129507729408?s=61&t=zkhUfqeLvv1PZzwKxfMKyA

Maybe the Android implementation is faulty? I issued a SRS warning on my iPhone 6s (I deleted all contacts via the OS settings previously) and did not get an error like this.

**Comment by Ein-Tim** [comment]
@mlenkeit / @dsarkar / @thomasaugsten 

I'd like to escalate this issue. From reports on Twitter I tend to say that this is not an isolated issue but always occurs. I will try warning myself on an Android device with version 3.0.1 installed and error logging active. Let's see if I'll get the same error.

First users on Twitter are starting to interpret this warning/informational pop-up as a confirmation that the SRS feature is broadly used to troll others: https://twitter.com/trollvanknall/status/1618762048246251520?s=46&t=or1WPnZNeDFj-OmlLAXdpQ

**Comment by dsarkar** [comment]
@Ein-Tim This issue is currently being analysed, and I have actually seen it also on iOS.

**Comment by Ein-Tim** [comment]
@dsarkar In this case this issue can be transferred to the cwa-documentation repository.

**Comment by thomasaugsten** [comment]
We adopt the configuration to prevent this warning which maybe confuse the user

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Okay so this was already done on server side? Is there a corresponding PR?

**Comment by MikeMcC399** [comment]
@thomasaugsten 

> We adopt the configuration to prevent this warning which maybe confuse the user

Did you mean "adapt" not "adopt"?
If it is "adopt" what is the configuration you are adopting?

**Comment by thomasaugsten** [comment]
Is already done. It should not occur further notes. There was a direct change. I will have a look if we a default value in the repo. Yes it was adapted.

**Comment by mlenkeit** [comment]
It's an environment variable configuration setting that is not reflected in any of the repositories. We changed the value of this variable, which was set to `10`:
https://github.com/corona-warn-app/cwa-server/blob/50063b0df5e16eee6a137e64ae35307492347f26/services/submission/src/main/resources/application.yaml#L23-L24

**Comment by Ein-Tim** [comment]
@mlenkeit 

Means the change isn't visible in the repo?

**Comment by Ein-Tim** [comment]
Congrats, this error made it into ZDF Wiso: https://www.zdf.de/verbraucher/wiso/wiso-vom-30-januar-2023-100.html (at 01:26). 

But seriously, as this should be fixed now, I'll close this issue.
