### ISSUE TITLE
Is the app still active and working, if I press the virtual button "close all"(apps)?

### ISSUE THREAD

**Issue by beceha** [corona-warn-app/cwa-app-android#582]
- I use a Galaxy Note 9 with Android 10.
- I have installed the Corona-Warn-App.
- With the "virtual button" on the bottom of the device I can "close all" apps.

**My Question:**

When I use this button and "close all" apps, that are currently active, **is the Corona-Warn-App still active and working in the background?**
Or have I to open the app again every time I press the virtual button "close all apps"?

Thank you.

**Comment by tomjschwanke** [comment]
The tracing is done by Google's API, so most likely yes.

**Comment by beceha** [comment]
> 
> 
> The tracing is done by Google's API, so most likely yes.

What do you mean?
My question was not about tracing.

**Comment by tkowark** [comment]
What @tomjschwanke is referring to is that the contact tracing done by the ENF framework is still working. Your question is probably about whether the risk calculation is still happening even when you close the app, right?

We'll add this to the FAQ section, as this questions comes up regularly for both applications. Thanks for pointing that out

**Comment by mynchau** [comment]
If the app is closed, encounters will still be logged. Yes. As long as you have activated risk identification in the app and Bluetooth is on, encounters are logged. The app itself doesn't have to be open for this. This question has been added to the FAQ. Reference: https://www.coronawarn.app/en/faq/
