### ISSUE TITLE
Missing 3.0.2 GitHub release

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-android#5826]
* [X] None of the other issue templates apply to this issue.

Version 3.0.2 is available in the Play Store, however, there is no GitHub release for this version yet. Please create a GitHub release. Thank you!

**Comment by mtwalli** [comment]
[v3.0.2](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v3.0.2)
