### ISSUE TITLE
Confusing message when there is no active internet connection

### ISSUE THREAD

**Issue by pussinboots** [corona-warn-app/cwa-app-android#583]
## Current Implementation
The current message about Open Internet connection is just confusing it looks like the bluetooth 
tracking is also not working without an active internet connection.

After reading the FAQ and the online documentation it was clear to me that the internet connection is not needed for the bluetooth tracking. 
![nointernet](https://user-images.githubusercontent.com/541464/84872718-86adde00-b082-11ea-8e5d-fd373e758717.jpg)

## Suggested Enhancement
Outline in the message "Open Internet Connection" that the tracking feature is still working just the calculate exposures isn't.

## Expected Benefits
Less confusion about the functionality of the corona warn application without an active internet connection.

Thanks for working on those application. Great job.

**Comment by kbobrowski** [comment]
I've raised this issue here: corona-warn-app/cwa-documentation#262

**Comment by tkowark** [comment]
Thanks for pointing out this issue. As @kbobrowski mentioned, we are tracking this centrally for both apps in the documentation repo and therefore close this here.

**Comment by corneliusroemer** [comment]
But it's still a good reminder that this issue is important - it gets independently rediscovered.
