### ISSUE TITLE
Contact statistics feature for feedback to user

### ISSUE THREAD

**Issue by TipaRiordan** [corona-warn-app/cwa-app-android#584]
## Current Implementation
App currently displays only number of days with data accquisition

## Suggested Enhancement
1. Add some statistics on a daily basis (to decouple by manner of time) about contacts, at least number of registered contacts for each day with data (in the last n days).
2. Icing on top would be  (i.e.) an additional matrix detailing the registered contacts (of the last n days) into [close / mid range / far] and [short time / medium time / long time]. Eventually with background color coding for "social distancing impact" from red (close/long time) to green (far/short).
## Expected Benefits
1.  Would provide feedback to the user about how active the app is in his envnironment, i.e. give a hint about how many app user he meets over a whole day. Would probably increase acceptance.
2. Would give the user some feedback about his overall contact behaviour, even if there are no risky encounters, probably enhancing the user's behaviour.

Data security / privacy impact ist expected to be neglectible.

**Comment by JProof** [comment]
similar to that #518

**Comment by MikeJayDee** [comment]
Not available from API.

**Comment by tkowark** [comment]
As mentioned by @MikeJayDee , this is not available through the API. Nevertheless, we created a central tracking issue for this idea on both devices here corona-warn-app/cwa-documentation#270
