### ISSUE TITLE
What does the error `SRS_OTP_SERVER_ERROR` mean?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-android#5850]
## Avoid duplicates
* [X] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Question is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Question has not already been asked in another issue

## Your Question
I have a user on Twitter who attempted to warn others but ran into the `SRS_OTP_SERVER_ERROR`, what does this error mean? 

Cross ref to Twitter: https://twitter.com/Billstein/status/1626175057968918561?s=20

**Comment by MikeMcC399** [comment]
@Ein-Tim 

... and did your user try again, as the error message recommended?

**Comment by Ein-Tim** [comment]
@MikeMcC399 Yes he did (cross ref https://twitter.com/Billstein/status/1626589979223945216?s=20)

**Comment by Ein-Tim** [comment]
@thomasaugsten Could you have a look at this to make sure this is not a server-side error? Thank you!

**Comment by thomasaugsten** [comment]
Which version has the user installed and which phone.

**Comment by Ein-Tim** [comment]
@thomasaugsten I asked the user for more information and will relay them here when I get them

**Comment by Ein-Tim** [comment]
@thomasaugsten 
- Fairphone 3
- App Version 3.0.1
- ENS Version v 1.8 (18230413000)
- CCL Version: 3.5.1
- Android Version: 11

**Comment by thomasaugsten** [comment]
The update on 3.0.2 is required to use the SRS Feature.

**Comment by Ein-Tim** [comment]
Ok, thanks @thomasaugsten. I'm assuming this is related to the certificate pinning, then. I relayed that information back to the user and will close this issue as soon as I have confirmation that this fixes the issue.

**Comment by Ein-Tim** [comment]
Yes, this fixed the issue, thanks @thomasaugsten. Maybe it would make sense to add a FAQ entry reg. this? I'll think about it.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> Maybe it would make sense to add a FAQ entry reg. this? 

It would have been good if the FAQ link on the error message had led to a relevant suggestion.

Considering though that [CWA Android v3.0.2](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v3.0.2) was already released on Feb 3, 2023, if the user's device had been auto-updating their apps then this version would have been automatically installed by Feb 6 or 7.

See 

- [How to update the Play Store & apps on Android](https://support.google.com/googleplay/answer/113412?hl=en) or 
- [So aktualisieren Sie den Play Store und Apps auf Android-Geräten](https://support.google.com/googleplay/answer/113412?hl=de)

Unlike the CovPass / CovPassCheck apps there is no warning / information produced by CWA Android if a newer version is available and not yet installed.
