### ISSUE TITLE
Set Notifications to onGoing (sticky)

### ISSUE THREAD

**Issue by flomero** [corona-warn-app/cwa-app-android#586]
The warning notifications, if you have turned of bluetooth or location access, can currently be swiped away or deleted, while deleting all notification.

I would prefer if they stay fixed, as long as contact tracing is enabled in the app, so people don't forget to turn bluetooth on again.

**Comment by tkowark** [comment]
Thanks for the proposal. We are tracking sticky notifications centrally in corona-warn-app/cwa-documentation#271

**Comment by tomjschwanke** [comment]
The notification is generated by Google Play Services
