### ISSUE TITLE
Samsung Galaxy S7 listed as not supported device?

### ISSUE THREAD

**Issue by ceeram** [corona-warn-app/cwa-app-android#592]
## Describe the bug

Samsung Galaxy S7 listed as not supported device in play store

## Expected behaviour

Samsung Galaxy S7 listed as supported device in play store

## Steps to reproduce the issue
Go to play store
<img width="496" alt="Screenshot 2020-06-17 at 12 24 35" src="https://user-images.githubusercontent.com/111448/84887130-9d116500-b095-11ea-8f9c-3098a013f8b1.png">

## Technical details

Android 8.0.0

## Additional context

Im not German, does this affect this maybe?

**Comment by IXArcanumXI** [comment]
"Im not German, does this affect this maybe?"

Yes - unfortunately the app isn't available if your Google account is not German. This is labeled a bug in https://github.com/corona-warn-app/cwa-app-android/issues/478 and is in clarification with SAP legal departement.

**Comment by uschindler** [comment]
The app works fine on Galaxy S7 (I have one).

The error message does not have anything to do with the origin of the phone (it can be an US/Chinese/... or anything else), the problem is the Google Account you're using, it must be located in Germany. The rest is #478 (legal stuff by SAP).

**Comment by uschindler** [comment]
Addendum: The error message in play store on the internet browser is a bit misleading. It says "incompatible". If you open play store on the phone as app, it will say "not available in your country".

**Comment by Adminius** [comment]
German Appstore:
![image](https://user-images.githubusercontent.com/17052262/84902368-08b2fc80-b0ad-11ea-88a1-41788e21787e.png)

**Comment by eharvester** [comment]
This is somehow  geoblocked. I have a German Google account, but I am not in Germany: play.google.com: "Diese App ist nicht mit deinem Gerät kompatibel." Playstore app:  "Dieser Artikel ist in deinem  Land nicht verfügbar".

**Comment by corneliusroemer** [comment]
@eharvester Known issue #478, don't get me started ;)

**Comment by treysis** [comment]
> "PEGI 3" is not used for classification of apps in Germany and also the language of play store implies that you are from another country.

PlayStore language is only a very vague indicator. I am using my German PlayStore in English-language, and I am thus able to find the app without any problem. I could set the PlayStore to any language I wish, it will still be the German PlayStore.

**Comment by uschindler** [comment]
> > "PEGI 3" is not used for classification of apps in Germany and also the language of play store implies that you are from another country.
> 
> PlayStore language is only a very vague indicator. I am using my German PlayStore in English-language, and I am thus able to find the app without any problem. I could set the PlayStore to any language I wish, it will still be the German PlayStore. But yes, it shows "USK" instead of "PEGI". So that is the actual identifier for a foreign PlayStore.

Please read my answer. The first paragraph exactly describes the problem (location of Google Account).

The second paragraph was clearly intended as "it looks like". The language is some indication, but PEGI3 was making it clear that the Google account was not from Germany.

**Comment by treysis** [comment]
@uschindler I just wanted to point out that the language really doesn't mean anything :)

**Comment by ceeram** [comment]
Thanks for all the explanations, i was being mislead by the unclear message in Play store
