### ISSUE TITLE
Certificates tab refers to unavailable Scan button after EOL

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#5920]
## Technical details

- Android version: 13
- App version: (3.2.0-RC14 `deviceForTestersDebug`) and 3.2.0 released version

## Describe the bug

After EOL date has passed (set in Test Menu) Certificates show "No certificates available yet" with the instructions

"To scan the QR code of the certificate, use the "Scan" button in the lower navigation bar."

There is however no longer a Scan button after EOL.

I will check again on the released version after the official EOL (April 30, 2023). Edit: no change. The bug is there as well.

---
Internal Tracking ID: [EXPOSUREAPP-15132](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-15132)

**Comment by Ein-Tim** [comment]
I just checked this under iOS, and it is not a problem there.

**Comment by MikeMcC399** [comment]
Confirmed as issue under the released version CWA 3.2.0 Android, both during onboarding and in regular use with no certificates stored. The `ì` info button also leads to the out-of-date info screen.

![no_certificates](https://user-images.githubusercontent.com/66998419/235405845-58aba297-8ffe-4f86-b862-48cda1604981.jpg)

![onboarding](https://user-images.githubusercontent.com/66998419/235405832-ec262c78-e6e6-4abc-b9df-949a28c2f1ab.jpg)

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Just out of interest, what happens on iOS when you tap the `i` symbol? Do you also get an info screen about adding certificates?

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Due to https://github.com/corona-warn-app/cwa-app-ios/issues/5162 I am not able to open the iOS app anymore, but yes, I also get this info screen. I will check later on a Simulator what it says.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Thank you for checking!

Since today, May 1, 2023, CWA allows storing certificates, but not scanning them. (See https://www.coronawarn.app/en/faq/results/#ramp_down_features.)

The [CovPass-App](https://digitaler-impfnachweis-app.de/) 1.42.0 allows scanning certificates and storing them.

I guess it is questionable how much benefit there is in correcting any inconsistencies in CWA in this area when there are only a few more weeks of life left in CWA and CovPass-App offers a working alternative for certificate management. The FAQ for CovPass https://www.coronawarn.app/en/faq/results/#ramp_down_covpass says that it will continue until end of June 2023, however it is not clear whether there is any extension planned after that date.

**Comment by Ein-Tim** [comment]
@MikeMcC399 This is what the info screen looks like under iOS (tested on a simulator using the `release/3.2.x` branch.

<img src="https://user-images.githubusercontent.com/67682506/235430924-b359c384-8f00-499b-ae11-b02e589ce045.png" width="300">

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Thanks. So it's also a problem in iOS, that the info screen says "Add your certificate", although this function is no longer available.

**Comment by Ein-Tim** [comment]
FYI: Contact journal information:

<img src="https://user-images.githubusercontent.com/67682506/235708254-db6d95c4-5f1d-4f39-b37c-fc1524b5d805.PNG" width="300">
<img src="https://user-images.githubusercontent.com/67682506/235708268-615ccf9f-a670-4c2c-867f-6ba438d3b488.PNG" width="300">

Same under Android @MikeMcC399?

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Please move the journal feedback into a new issue and you can put it into https://github.com/corona-warn-app/cwa-documentation, since it also affects Android.

**Comment by MikeMcC399** [comment]
Judging by the lack of response to this issue (apart from allocating it an Internal Tracking ID: [EXPOSUREAPP-15132](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-15132)) I will assume that there will be no change in the app. There are only a few more days to go before it is withdrawn from the app store so the issue automatically becomes obsolete.
