### ISSUE TITLE
Risk status not updating after reopening backgrounded app

### ISSUE THREAD

**Issue by SoerenBusse** [corona-warn-app/cwa-app-android#594]
## Describe the bug
The risk status page shows "0 von 14 Tagen aktiv" when the app is reopened after the operating system put it into background.

_I'd love to add a screenshot. This is not possible as described in the appropriate issue. This makes reporting bugs very hard_.

## Expected behaviour
The app should show "1 von 14 Tagen aktiv" when the app will be reopened from the background.

## Steps to reproduce the issue
1. Open the cwa-app
2. Open the risk status page
3. Change the app to something RAM intensive like a game etc.
4. Change back to the cwa-app
5. The App shows "0 von 14 Tagen aktiv" instead of "1 von 14 Tagen aktiv".

## Technical details
Android 8.1.0
I think this issue will only occur on older devices with less RAM.

## Additional context
I think this is a minor or cosmetic bug, however I would like to share this unexpected behavior to you.

**Comment by tkowark** [comment]
Hi @SoerenBusse , just to clarify: before putting the app to the background, it was showing "1 von 14 Tagen aktiv"?

**Comment by SoerenBusse** [comment]
Hi @tkowark

Exactly. It was showing "1 von 14 Tagen aktiv". I think this might be related to am Life Cycle issue where the number of days isn't correctly initialized and the default int value is beging shown.

**Comment by HeeTattSap** [comment]
hi @SoerenBusse thank you for bringing this issue up.

Could you please check on the date and time settings on phone if:
- the date and time settings are correct
- if network-provided time is on

**Comment by jan-hofmeier** [comment]
I can also reproduce the issue on my device. (Xperia XA2, Android 9). It seems to happen, when the App get's evicted from RAM and then gets restored, when you reopen it.

To reproduce: go to the risk status activity and then open lots of other apps, so the CWA app, will be killed. The next time it gets opened, it takes a little bit longer, as it gets restored from storage and it will show "1 von 14 Tagen aktiv"

**Comment by jakobmoellersap** [comment]
Just as a quick question: If you say you can reproduce it would mean that it shows "0 von 14 Tagen aktiv" not "1 von 14 Tagen aktiv" after restoring the app like you describe @jan-hofmeier. Did I get this wrong or is there a misunderstanding?

**Comment by jan-hofmeier** [comment]
@jakobmoellersap You are correct, I meant "0 von 14 Tagen aktiv"

**Comment by jakobmoellersap** [comment]
Okay, just for confirmation: Does this issue persist with 1.0.4 of the App?

**Comment by SoerenBusse** [comment]
Hi, 

I think this is related to not calling `refreshActiveTracingDaysInRetentionPeriod()` in the OnResume in the RiskDetailFragment:
https://github.com/corona-warn-app/cwa-app-android/blob/dev/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/riskdetails/RiskDetailsFragment.kt#L57

https://github.com/corona-warn-app/cwa-app-android/blob/dev/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/TracingViewModel.kt#L150

Is it intended that `activeTracingDaysInRetentionPeriod` isn't a LiveData type?
https://github.com/corona-warn-app/cwa-app-android/blob/dev/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/viewmodel/TracingViewModel.kt#L53

**Comment by jan-hofmeier** [comment]
@jakobmoellersap yes, I just tested it again to make sure. I have 1.0.4 and still have the issue
