### ISSUE TITLE
Turning off Bluetooth but still have the keys saved?

### ISSUE THREAD

**Issue by Bumblebee38** [corona-warn-app/cwa-app-android#599]
Is it possible to let "Risiko-Ermittlung" on and use it with Bluetooth on if I am outside but turn Bluetooth off if I think that I really do not need it for now like if I am at home and only want to go to sleep without losing the saved random keys of other devices. Is it possible to use the app if I would than turn Bluetooth on again as if I never turned Bluetooth off? I still want to be notified if a case of a person I was nearby gets positive.
Or does turning off Bluetooth delete all random keys my device just saved within 14 days?

**Comment by DE-Max-42** [comment]
No, just turning off Bluetooth does not delete the keys.

**Comment by HeeTattSap** [comment]
hi @Bumblebee38, thank you very much for your question.

@DE-Max-42  is right, turning off Bluetooth does not delete the following:
- the temporary exposure keys you received from other phones. These are used to check if you come in proximity with a user that is tested positive and submitted their keys
- your own keys (that you could choose to voluntarily submit, in the case that you are tested positive).
