### ISSUE TITLE
Darstellungsfehler - Englisches User Interface

### ISSUE THREAD

**Issue by LordEphidel** [corona-warn-app/cwa-app-android#601]
## Describe the bug

Nachdem ich Exposure Logging für einen Tag eingeschaltet hatte, wurde in der App in der Box, in der das aktuelle Risikoniveau angezeigt wird, folgender Text angezeigt:
"1 of  days active" (2 Lücken zwischen of und days) - Die Grafik links daneben, die anhand eines Kreises veranschaulicht, wie lange Exposure Logging aktiv war, zeigt einen etwa zu 1/12 ausgefüllten Kreis an.

## Expected behaviour

Erwartet hätte ich einen vollständig ausgefüllten Kreis und den Text "1 of 1 days active"

## Screenshot

![threema-20200617-164004-d8117bdefcf5e225](https://user-images.githubusercontent.com/20282311/84912052-44ec5a00-b0b9-11ea-907f-7dc28ee96d41.jpg)

## Technical details

- Device Info:
Moto G5 Plus, Android 8.1.0
Englisches User Interface

**Comment by jakobmoellersap** [comment]
Duplicate of #569

**Comment by LordEphidel** [comment]
Das ist aber nicht das gleiche Problem... Im anderen Issue wird vorgeschlagen, "days" durch "day(s)" auszutauschen. Das Problem, das ich habe, ist, dass die Gesamtzahl an Tagen fehlt (siehe Screenshot). Da steht "1 of  days" statt "1 of 1 days"

**Comment by blinry** [comment]
Scheint bereits in #446 gefixt worden zu sein :)
