### ISSUE TITLE
CAUSE: 3 Something went wrong // Error when communicating with Google API (17)

### ISSUE THREAD

**Issue by Freundschaft** [corona-warn-app/cwa-app-android#602]
## Describe the bug

The app starts, but exposure logging fails with the following error message:

![image](https://user-images.githubusercontent.com/5065616/84915658-60596400-b0bd-11ea-9539-8a1b65dc93e9.png)
![image](https://user-images.githubusercontent.com/5065616/84915666-62bbbe00-b0bd-11ea-8ac3-a000ce4f5cc1.png)

## Expected behaviour

I expect the app to activate exposure logging without throwing an error

## Steps to reproduce the issue

1. Install App from Google Play Store
2. Start App.
3. Try to activate exposure logging
4. Error appears

## Technical details

- Running on an Oppo A57 phone with ColorOS V3.0 Android 6.0.1. 
- Play Services do not ship with this device, but are installed and Google Services work correctly in general.
- Google Play Services is Version 20.21.17

## Possible Fix

Possibly related to this error: https://github.com/google/exposure-notifications-android/issues/8
and this error https://github.com/corona-warn-app/cwa-app-android/issues/508

**Comment by rejuce** [comment]
Exactly same error.
I am using Huawei Evr-al00 Mate 20x. Android v10, 
![Screenshot_20200617_200142_com weberdo apps serviceinfo](https://user-images.githubusercontent.com/28755821/84932978-6f4c1080-b0d5-11ea-9a35-9a523fcada5d.jpg)

**Comment by ChuangSheep** [comment]
Duplicated. Please refer #499 and #508 
**Also, this has been a really big issue since I have seen 2 new issues about this problem just today. If we could not fix it now, please at least consider making an announcement about this.**

**Comment by jbauerrfid** [comment]
Proposal for the devs maintaining this git repo: add a Duplicate label, then you can filter by it in the git issue tracker.
Example: issue search query `-label:duplicate`

**Comment by tkowark** [comment]
Thank you all for your input. While we cannot solve this issue directly, the team implemented a more descriptive error description in the latest app version that also links to the [FAQ](https://www.coronawarn.app/de/faq/#cause_3) which contain more information than could possible fit into a single mobile screen.

**Comment by stefanbschneider** [comment]
Same here, with "Error when communicating with Google API(10)"

**Comment by ejgeo** [comment]
Cause: 3 Something went wrong. error when communicating with Google API (39508)

The app sometimes show this error and sometime work properly.
