### ISSUE TITLE
Question: Android Enterprise Work Profile Support

### ISSUE THREAD

**Issue by CJHarms** [corona-warn-app/cwa-app-android#604]
## Your Question

* Question: Is running the Corona Warn App in the Android Enterprise Work Profile "Container" officially supported?

A few colleagues are reporting that running the App inside the Work Profile produces the "Fehler bei Kommunikation mit Google API(17)" Error. Anyone getting the same Error or got it working?

Any official Documents from Google if this is supported? If this is not (yet) supported maybe we can get Google to consider fixing this or adding this feature to the Android Enterprise Work Profile Mode.

---
Internal Tracking ID: EXPOSUREAPP-1942

**Comment by mbanck** [comment]
https://github.com/corona-warn-app/cwa-app-android/issues/499#issuecomment-645526261 might be related

**Comment by GPclips** [comment]
Hello @CJHarms ,

to follow up after a while: Does this error still exist?

Also,
can you please share the affected app version as well ats the devices where the error did occur?

Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by svengabr** [comment]
Due to missing feedback, I assume the issue does no longer occurs. The Issue will be closed to keep the boards clean.

Best regards,
SG

Corona-Warn-App Open Source Team

**Comment by John4711** [comment]
Hallo Sven,

ich bestätige das Verhalten von Corona App auf den Android Enterprise Devices/Installationen.

Somit können wir ca. 1000 Installation auf den Geräten nutzlos, weil keine Funktion - aber gut für die Installationsstatistik.

**Comment by John4711** [comment]
![20200622_090430-1536x1152](https://user-images.githubusercontent.com/73314970/96930801-99b33d80-14bc-11eb-9bc1-e0c35bdff709.jpg)

**Comment by svengabr** [comment]
Duplicate of https://github.com/corona-warn-app/cwa-app-android/issues/1458
