### ISSUE TITLE
[Feature request] Ship the app with "App Bundles" to reduce size to a third

### ISSUE THREAD

**Issue by corneliusroemer** [corona-warn-app/cwa-app-android#606]
@R4md4c made an excellent observation why the app is so large. In fact he seems to show that reducing the space required to a third would not be difficult at all. As a result, it makes sense to consider this very concrete proposal.

Here is his post:
>I've taken a deeper look on why the app is too big for what it does, and found out that's because of the native libs that are getting shipped for every architecture in a single apk, that means an `arm` device would get an `x86` lib binary even though it is not needed at all. 

>![image](https://user-images.githubusercontent.com/297007/84824432-37cf5c80-b020-11ea-9aa6-a053e42bd236.png)

>To remedy this we have two options AFAIK: 
>1. [App Bundles ](https://developer.android.com/guide/app-bundle) ~~(the hardest) Obviously not possible with the current code structure as it requires some modularization steps to be taken for the project which I'm not sure if the maintainers have time for that or not.~~
Which are like a blue-print apk that Google Play will use to generate multiple apks that fits your device specs exactly (e.g. GP will only serve just the files necessary that fits your screen density, architecture and language hence will result in even less download size than Option 2). 
>I followed the steps in [this guide](https://developer.android.com/guide/app-bundle/test) and tried them out with a `Galaxy_Nexus_API_23` emulator, and found out that a total of *14 MBs* of apk size got installed to the emulator vs *17.2 MB* in Option 2.

>2. Using [APK splits](https://developer.android.com/studio/build/configure-apk-splits) (the easiest) which I tried it out as an experiment and resulted in three different apks: 

* `Corona-Warn-App-device-arm64-v8a-release-unsigned.apk` size *16.3 MB*
* `Corona-Warn-App-device-armeabi-v7a-release-unsigned.apk` size *14.4 MB*
* `Corona-Warn-App-device-x86_64-release-unsigned.apk` size *17.2 MB* 

>That means if a user has a phone with one of these architectures, he'd just download the corresponding apk to his architecture hence saving almost 50% of the current download size. 

>~~I could try to open a PR for option 2, but not sure if it would get accepted by the maintainers or not.~~

_Originally posted by @R4md4c in https://github.com/corona-warn-app/cwa-app-android/issues/482#issuecomment-644997677_

A similar issue is also open at #527 but with less concrete proposals.

**Comment by tkowark** [comment]
As #482 is now reopened, we'll close this one to only have a single location for ideas about file size reduction.

**Comment by corneliusroemer** [comment]
Great, thanks for reopening #482 !
