### ISSUE TITLE
Does the app work as background service after beeing closedby the taskmanager? 

### ISSUE THREAD

**Issue by ckuetbach** [corona-warn-app/cwa-app-android#609]
## Does the app work as background service after closed? 

- If yes, a icon would be fine, to show that "everything works"
- If not, there should be a warning message not to close the app completely.

**Comment by tomjschwanke** [comment]
Yes, as mentioned in #582

**Comment by ckuetbach** [comment]
Or in the german FAQ as well:

https://www.coronawarn.app/de/faq/#close_app

Shame on me for neither finding the issue, nor the website.
