### ISSUE TITLE
Why is permanent Internet connection necessary? I'm on Prepaid.

### ISSUE THREAD

**Issue by beceha** [corona-warn-app/cwa-app-android#610]
Why is permanent Internet connection necessary? I'm surely not the only one who uses Prepaid with a limited data (Congstar).
Therefore it is not possible (too expensive) to stay online all the time.
If I close my internet connection, the app shows an error "no internet connection".
Why isn't Bluetooth enough?
-------------

Samsung Galaxy Note 9
Android 10
Congstar Prepaid

**Comment by fdellwing** [comment]
Telekom said that all mobile providers in Germany agreed on zero-rating traffic of the CWA. Did you ask Congstar about this?

**Comment by robertbastian** [comment]
Travellers or border commuters might not be on a German network so will have to pay for data. Also, zero-rating messes with the device's capability to track data usage (it doesn't know which packets count).
So the question stands, why isn't Bluetooth enough?

**Comment by Eyremba** [comment]
@robertbastian I guess because every content inside of the App is loaded live from the internet.

**Comment by fdellwing** [comment]
I guess because the app regulary downloads data from the https://github.com/corona-warn-app/cwa-server to check if you are likely to be infected.

**Comment by kolyaopahle** [comment]
Hey,
exposure key exchange is still active even without having an internet connection.
The app does require a internet connection for risk score calculation since it uses remotely configurable parameters for this functionality.
We also require an internet connection to fetch test results since this data is not persisted on the device.

**Comment by mwbaumstark** [comment]
Is an internet connection really necessary all the time? Could I swtich of mobile data and WLAN as long as I'm outside and switch it on at home? This would allow all fetching of data mentioned above.

**Comment by kbobrowski** [comment]
App will exchange bluetooth information with other phones even without the internet. There is some confusion about it due to unfortunate visual design of the app. Main issue where it is discussed is here: corona-warn-app/cwa-documentation#262

**Comment by jab4** [comment]
Hey Kolya, exposing an "error" condition to users is especially bad for a quite common scenario.

Please consider degrading the error to a soft warning/notice: 

`You are currently offline. Displaying results is suspended while Bluetooth data exchange still works in the background. Results will be updated once an Internet connection is available.`

DE: `Sie sind derzeit offline. Die Anzeige von Ergebnissen ist ausgesetzt, während der Schlüsselaustausch über Bluetooth weiterläuft. Die Ergebnisse werden mit der nächsten Internet-Verbindung aktualisiert.`

**Comment by kolyaopahle** [comment]
Hi @jab4,
im not sure that i understood you correctly, which "error" condition are you talking about?

**Comment by corneliusroemer** [comment]
@jab4 and @beceha could you possible provide a screenshot for the error that is shown in this case? That would make it easier to judge whether the severity of the bug is justified.

**Comment by kbobrowski** [comment]
@kolyaopahle @corneliusroemer I think it's very clear what this error is about, @beceha clearly explained:

> If I close my internet connection, the app shows an error "no internet connection"

You can recreate it easily by just switching off internet when using CWA, it displays "no internet connection" at the top, which easily gets interpreted as an error. Screenshots are disabled by the app (likely for security reasons)

**Comment by fkarg** [comment]
Why screenshots are disabled is discussed in more detailed in https://github.com/corona-warn-app/cwa-app-android/issues/516 and linked issues.

In my understanding it is because the main 'activity' (sharing test-TANs) should not be screenshottable, and currently the whole app has only one activity, so until everything else is a separate activity, it will not allow native screenshots. It seems not to be deactivated for the iOS app though.

**Comment by corneliusroemer** [comment]
I rephrase, a picture of the screen would be good. Here we go.
![Photo on 17-06-2020 at 21 20](https://user-images.githubusercontent.com/25161793/84940743-8e03d480-b0e0-11ea-99ea-d9def92ed809.jpg)
![Photo on 17-06-2020 at 21 21](https://user-images.githubusercontent.com/25161793/84940748-8fcd9800-b0e0-11ea-9e10-aa32664d08af.jpg)

**Comment by kolyaopahle** [comment]
@kbobrowski ah, i see. I was honestly expecting an actual error dialog for a condition we did not catch. My bad :)

@jab4 in case this is the error you are referencing please also leave your comment in the linked issue here: corona-warn-app/cwa-documentation#262 as this concernes both versions of the app.

**Comment by kolyaopahle** [comment]
> Why screenshots are disabled is discussed in more detailed in #516 and linked issues.

👍 

> In my understanding it is because the main 'activity' (sharing test-TANs) should not be screenshottable, and currently the whole app has only one activity. An activity describes a form of window, including sub-frames (as far as I understand). So until everything else is a separate activity, it will not allow native screenshots.

The screenshot issue actually requires some more discussion, it was initially raised by the BSI in #9 
because these automatic screenshots taken by the os could be accessible to other apps, which might lead to data leaks not only concerning TAN's but also the users test status.

>  It seems not to be deactivated for the iOS app though.

This is purely because deactivating screenshots is not possible on iOS.

**Comment by corneliusroemer** [comment]
@kbobrowski See, it actually helped now to have pictures to get it across to the dev :)

**Comment by beceha** [comment]
> 
> 
> Telekom said that all mobile providers in Germany agreed on zero-rating traffic of the CWA. Did you ask Congstar about this?

No, I haven't, but it is nice, that the Telekom said this concerning the Corona Warn App. But this is not the only app I have on my smartphone.
As soon as I enable the internet connection, many other apps uses this then, too, like for notifications, e-mail and other things.

**Comment by tkowark** [comment]
We have an open enhancement issue for this particular warning: https://github.com/corona-warn-app/cwa-documentation/issues/262

**Comment by corneliusroemer** [comment]
> We have an open enhancement issue for this particular warning: [corona-warn-app/cwa-documentation#262](https://github.com/corona-warn-app/cwa-documentation/issues/262)

I'm not sure issue #262 should be labelled enhancement. Imho it's a bug.

**Comment by hofschroer** [comment]
I have installed the App on the phone of my son. He uses Congstar without mobile data connection. The usage of the corona warn app with only WLAN at home works fine

**Comment by corneliusroemer** [comment]
@hofschroer yes, there is no real need to have continuous internet. The error/warning you get when internet is off is a bug in the way it's phrased. Only occasional internet connectiton ~2xdaily is sufficient.

**Comment by kbobrowski** [comment]
There might be the need for continuous internet connection actually - see recent developments discussed in issue corona-warn-app/cwa-documentation#262 (and [this comment](https://github.com/corona-warn-app/cwa-documentation/issues/236#issuecomment-646238207)).

It might be that if there is no internet connection in a short time window (one minute) during the day, the next attempt to retrieve infected people data will be only next day, and again only during short time window. This may result in severe delays in receiving exposure notification.

So for now, **I need to take back my statements made in [this comment](https://github.com/corona-warn-app/cwa-app-android/issues/610#issuecomment-645539781) until issue discussed in corona-warn-app/cwa-documentation#262 is resolved, and encourage everyone to keep the internet on as much as it is possible**.

**Comment by beceha** [comment]
> There might be the need for continuous internet connection actually ... It might be that if there is no internet connection in a short time window (one minute) during the day, the next attempt to retrieve infected people data will be only next day, and again only during short time window. This may result in severe delays in receiving exposure notification.

I understand this ... but perhaps there could be a solution for example like with my Fitbit tracker.
It "memorize" steps etc. for 24h, and within 24h I have to connect my phone to the internet for synchronisation.
Wouldn't it be a solution for the Corona Warn App?

**Comment by kbobrowski** [comment]
@beceha I think this would be a good solution, but I'll let CWA team clarify issues around it, I'm not working for SAP so don't take my word for it. I've added above clarification since I think it's highly likely that this is how the apps work right now, but let's wait for SAP response about this issue.

**Comment by monikaschmitt** [comment]
Thanks again for the fruitful discussion in here. The original question of this issue has been answered. @beceha that's why we will close this issue here and defer further discussion about the unnecessary delay in exposure notification to https://github.com/corona-warn-app/cwa-backlog/issues/2 (already moved over to backlog)
Best regards
MS 
Corona Warn-App Open Source Team
