### ISSUE TITLE
Total Days missing in risk status

### ISSUE THREAD

**Issue by Bandyt** [corona-warn-app/cwa-app-android#613]
The English user interface does not show the total number of days (14). The message is "1 of  days active" in the overview and the risk status.

The german interface is correct.

**Comment by pwoessner** [comment]
Hi @Bandyt , this issue was resolved in https://github.com/corona-warn-app/cwa-app-android/pull/446 . The fixed version 1.0.2 is now also available in the Play Store as an update. 

Best regards,
Philipp
