### ISSUE TITLE
"Your device isn't compatible with this version"

### ISSUE THREAD

**Issue by eharvester** [corona-warn-app/cwa-app-android#614]
App requires Android 6+. Many people are left out of the loop, especially elderly people, who do not want to buy and learn a new phone. Can you add support for KitKat?

**Comment by kolyaopahle** [comment]
Hi @eharvester,
sadly we cannot support any android devices with an api level lower than 23 (Android 6.0).
This is due to google not supplying the exposure notification api's for older os versions.
See #489 and linked issues for more information.

**Comment by speedy-1702** [comment]
There are brandnew smartphones with Android >=6.0 available for around 70€.
The cwa could be a good oportunity to make this investment into health.
