### ISSUE TITLE
Statistik über "engere" Begegnungen der letzten 14 Tage anbieten

### ISSUE THREAD

**Issue by ikarisan** [corona-warn-app/cwa-app-android#615]
Hallo!

Ich hätte einen Vorschlag für eine der nächsten Versionen. :) 

## Current Implementation
Momentan zeigt die App nur an, ob man in den letzten 14 Tagen einen längeren Kontakt zu einem als positiv getesteten Mitbürger hatte. 

## Suggested Enhancement
Ich fände es super toll, wenn die App mir mein Sozialverhalten der letzten 14 Tage näher bringen würde. Daher wünsche ich mir eine Art Statistik, die mir in etwas so etwas sagt:

 "In den letzten 14 Tagen hatten sie mit 673 Personen engeren (<2m) Kontakt, hiervon mit 80 Personen länger als 15 Minuten.  Mit diesen 80 Personen hatten sie in 32 Fällen einen Erstkontakt innerhalb der letzten 14 Tage."

## Expected Benefits
Durch eine solche (optionale) Angabe/Statistik würde der Benutzer bzgl. seines Sozialverhaltens sensibilisiert. Vielen ist eventuell garnicht bewusst, dass sie so viele und so lange Kontakte (zu Fremden) haben.

**Comment by robertbastian** [comment]
Anzahl von Personen und Erstkontakte können mit dem Protokoll nicht festgestellt werden. Es kann nur die Anzahl der 15(?)-minütigen Kontakte gezählt werden, wobei ein 30-minütiger Kontakt genauso aussieht wie zwei 15-minütige Kontakte (das andere Gerät ändert nach 15 Minuten seine ID und sieht wie ein neues Gerät aus). Wenn man also z.B. mit jemandem zusammenwohnt, und 18h am Tag zusammen ist, dann sieht das genauso aus als wenn man 72 Kontakte hätte.

**Comment by kolyaopahle** [comment]
Hi ikarisan,
erstmal danke für die tolle Idee, Feedback und Vorschläge sind immer gerne gesehen.

Leider stellt uns die Google Schnitstelle keine Informationen über nicht positive Begegnungen zu Verfügung.

Weiteres kannst du hier: #584 nachlesen.

**Comment by corneliusroemer** [comment]
Maybe there is still some sort of useful information that is provided to the app by the Exposure API. I recommend that interested people read the Exposure API specs and see for themselves. Maintainers will probably not spend time on something this optional.
