### ISSUE TITLE
Improve: Use a better term for "Mundschutz"

### ISSUE THREAD

**Issue by IOIO72** [corona-warn-app/cwa-app-android#618]
https://github.com/corona-warn-app/cwa-app-android/blob/c3416440e644a918f4001489de85f203c7681099/Corona-Warn-App/src/main/res/values-de/strings.xml#L281

Because many people are wearing their masks above the mouth, but not the nose, it would be better to use the term "Mund-Nasen-Schutz":

```xml
<string name="risk_details_behavior_body_wear_mask">"Tragen Sie einen Mund-Nasen-Schutz bei Begegnungen mit anderen Personen."</string>
```

**Comment by bersbersbers** [comment]
Also consider using "Mund-Nasen-Bedeckung" instead, which is a less medical term that better corresponds to what is required by law in many places. Compare
> Der Mund-Nasen-Schutz [...] ist ein Medizinprodukt
https://de.wikipedia.org/wiki/Mund-Nasen-Schutz

vs. https://www.rki.de/SharedDocs/FAQ/NCOV2019/FAQ_Mund_Nasen_Schutz.html , https://de.wikipedia.org/wiki/Mund-Nasen-Bedeckung (which redirects to https://de.wikipedia.org/wiki/Alltagsmaske), etc.

**Comment by tomjschwanke** [comment]
Propose text changes to #332

**Comment by tkowark** [comment]
Let's close this one as it is already part of 332.
