### ISSUE TITLE
Uninstall toast message says "Corona-Warn uninstalled"

### ISSUE THREAD

**Issue by Fabus1184** [corona-warn-app/cwa-app-android#622]
## Describe the bug

When uninstalling the app, the toast Message says "Corona-Warn uninstalled"

![Screenshot_20200618-083813](https://user-images.githubusercontent.com/43907020/84987098-e61df380-b13f-11ea-9947-b7568382355a.jpg)

## Expected behaviour

the Toast Message should say "Corona-Warn**-App** uninstalled"

## Steps to reproduce the issue

Uninstall the app 

## Technical details

Android 10 on

Motorola Moto G5s plus (sanders) 

## Possible Fix

change some kind of name that is used to create the toast message text ?

**Comment by tomjschwanke** [comment]
This message is generated by your OS and just has the App-Name in it, which happens to be `Corona-Warn`

**Comment by HeeTattSap** [comment]
hi @Fabus1184 thanks for your question.
@tomjschwanke is right, the app name is configured as `Corona-Warn` and the toast is from Android OS, just like if you would uninstall any other app.

**Comment by Fabus1184** [comment]
I know that the message is generated by android, but for all other apps it display the "real" name, but for the Corona Warn App it does not, so I assume there must be some kind of value in some config I dont know that is set to "Corona-Warn"

**Comment by tomjschwanke** [comment]
> I know that the message is generated by android, but for all other apps it display the "real" name, but for the Corona Warn App it does not, so I assume there must be some kind of value in some config I dont know that is set to "Corona-Warn"

The app name is `Corona-Warn`. That is the real app name. Just the title in the store is different.
