### ISSUE TITLE
Provide better/real changelog

### ISSUE THREAD

**Issue by chrjsorg** [corona-warn-app/cwa-app-android#623]
## Current Implementation
An update was released this morning. Unfortunately the changelog was not very meaningful. "Minor adjustments" (German: "Kleinere Anpassungen")

## Suggested Enhancement
This might be fine for the Play Store (in my opinion it's not), but there should at least be a detailed changelog on Github.

How can we handle this in the future?

## Expected Benefits
More transparency for users and developers

**Comment by fdellwing** [comment]
I'm with you on that, but v1.0.1 and v1.0.2 where literally minor adjustments.

#447
#470

**Comment by chrjsorg** [comment]
Okay, so the changelog for the Play Store might fit here. Nevertheless, the changes should be more visible via "Releases" or a "Changelog.md".

**Comment by tkowark** [comment]
Thanks for your proposal. We already have an issue open for that #511

**Comment by jakobmoellersap** [comment]
Release Notes provided in https://github.com/corona-warn-app/cwa-app-android/releases/tag/1.0.3
