### ISSUE TITLE
Make screenshot protection optional

### ISSUE THREAD

**Issue by Alestrix** [corona-warn-app/cwa-app-android#625]
## Current Implementation
Due to #9 screenshots are completely disabled in the app.

## Suggested Enhancement
Implement a setting that gives the user the possibility to allow screenshots.

## Expected Benefits
Sometimes it is desirable to share the screen (not only the main screen) with others, e.g. for discussion about the functionality or displayed documentation. This is only feasible with a screenshot.

On top of this, the risk of "malicious apps" stealing "sensitive information" as portrayed in #9 is IMHO largely exaggerated: The probability of sensitive information being displayed (red status? TAN for covid test?) multiplied with the probability of having a malicious app on the phone whose purpose it is to steal medical information (instead of banking information as most apps of this kind are after) is so low that it is disproportionate to the restriction placed upon the user.

**Comment by ironjan** [comment]
Additional benefit: screenshots can also be very useful when reporting bugs. In fact, the bug report template contains this part:
```
## Steps to reproduce the issue

<!-- include screenshots, logs, code or other info to help explain your problem -->
```

**Comment by corneliusroemer** [comment]
Additionally, you may want to read @Bengt's valuable insights into the possibility of workarounds: https://github.com/corona-warn-app/cwa-app-android/pull/620

**Comment by tkowark** [comment]
Thanks for this proposal. Since #516 has bee turned also into a feature request, we'll close this issue to focus on a single issue for any further discussions
