### ISSUE TITLE
Give user access to the terms he/she agreed to

### ISSUE THREAD

**Issue by Alestrix** [corona-warn-app/cwa-app-android#627]
## Current Implementation
To use the app the user needs to agree to (or can optionally agree to) various terms. Out of my head these are: Datenschutz, Nutzungsbedingungen, Risiko-Ermittlung.

There is no way for the user to document/store what he/she actually agreed to.

## Suggested Enhancement
Give the user access to the terms that were displayed on the phone at the time. Either by giving the user an external link to open in the browser from where it can be saved or by sharing the agreed terms to another app (store as file, send as email, ...) from within corona-warn-app.

## Expected Benefits
Whenever someone signs a contract (agreeing to terms in an app is similar), the person receives a copy of the terms at the time for later reference and also for later study. The user does not have this possibility here which could fuel allegations of malicious intent ("change of terms later without the user knowing", "trying to hide information from the user"). There might also be legal implications to the missing of such a "carbon copy" possibility, but IANAL.

It is also an obstacle when trying to discuss the contents with others and when trying to emend someone's wrong understanding of the app, where those terms and explanations would greatly help discussion.

**Comment by DE-Max-42** [comment]
I think the issue already exists in #596

**Comment by gizmo21** [comment]
Could be related:
https://github.com/corona-warn-app/cwa-app-android/issues/596

**Comment by Alestrix** [comment]
Correct, didn't see that issue. Closing this (not sure whether I can mark it as duplicate)

**Comment by Alestrix** [comment]
Duplicate of #596

**Comment by Alestrix** [comment]
PS: Thinking about it, maybe continuing the issue here in #627 would be better than in #596 due to usage of the English language?

**Comment by corneliusroemer** [comment]
@Alestrix Or: Suggest to the author of #627 to change the title to English if that issue has gotten more traction thus far.
