### ISSUE TITLE
URIs/URLs/links in texts not active

### ISSUE THREAD

**Issue by Alestrix** [corona-warn-app/cwa-app-android#633]
## Describe the bug
Almost all texts in the "App-Informationen" menu (some of which are also displayed when the app is started for the first time) include URIs, email addresses, phone numbers. These can not be opened directly.

On top of this, in "Nutzungsbedingungen" there is also a text "[Link]" without a URI.

## Expected behaviour
URIs must be active/clickable.

## Steps to reproduce the issue
Open e.g. the "Nutzungsbedingungen" and try to open one of the links or try to send an email to one of the email addresses listed in those texts.

## Possible Fix
Make https links, email addresses and possibly also phone numbers within those texts clickable/active.

## Additional context
As it is now, URIs need to be either memorized or written down on a piece of paper, then typed into the phone's browser. This is completely unacceptable form a user's point of view.

**Comment by PhilippNowak96** [comment]
Looks like this PR will fix it: https://github.com/corona-warn-app/cwa-app-android/pull/564
