### ISSUE TITLE
Persistent notification for app activity

### ISSUE THREAD

**Issue by len17** [corona-warn-app/cwa-app-android#634]
## Feature description

I'd like to have a persistent notification (or the option to activate a persistent notification) in the notification pull-down overview, that tells me whether the app is active or not. 

## Problem and motivation

My (and I'm sure other peoples) phone sometimes randomly reboots and I'm not quite sure if the app restarts with the reboot. Furthermore, I'd like to be reminded that some app is tracking my contacts and that the feature is still active. If I leave my phone somewhere (e.g. when doing sports), I turn the app off. To be reminded to do that, I'd like to see the persistent notification. Also, I'd like to be reminded if the app does not currently track my contacts, so that I don't forget to turn the feature back on.

## Is this something you're interested in working on

I have zero experience in app-development, so unfortunately: no.

**Comment by tkowark** [comment]
Thanks a lot for this proposal. We're tracking this centrally for both apps at corona-warn-app/cwa-documentation#271
