### ISSUE TITLE
Links can not be clicked/copied

### ISSUE THREAD

**Issue by GlOwl** [corona-warn-app/cwa-app-android#635]
## Current Implementation
On the "Introduction" and "App Information" Screens, links are not click or copyable. (Especially Links to the Google exposure logging information wich are long and complicated)

## Suggested Enhancement
Enable copying of the whole text on these screens or make the links clickable.

## Expected Benefits
No one has to type horrible two line long links with Numbers and Special Characters by hand any more.

**Comment by eliaszemanek** [comment]
duplicate of #633
