### ISSUE TITLE
CWA interfers with app that use bluetooth sync functions (Polar Flow)

### ISSUE THREAD

**Issue by Henheidrik** [corona-warn-app/cwa-app-android#643]
First of all, thank you for contributing to a safer and healthier world!

## Describe the bug

The CWA interferes with the app Polar Flow that uses Bluetooth to sync wearables or bike computers.
When CWA is installed, only the connection to the wearables is possible and sync does not work anymore. The wearable seems to be connected to the device, but it does not connect to the app to sync. When CWA is uninstalled, the syncing is working. It also occurs on an other device with another wearable using the same service (friend of mine) and likewise, uninstalling CWA fixed the issue. 

## Expected behaviour

The CWA is installed and Bluetooth and GPS is on. 
When syncing the wearable you make sure Bluetooth and GPS is on, that you are connected to the internet and your device is connected to the wearable. Then you open the Polar Flow App and start the syncing with your wearable. The wearable connects to the app and syncs your data. This all happens while CWA is installed.

## Steps to reproduce the issue

You need to install CWA and try to sync a wearable with Polar Flow. There will be no error message in CWA, but the syncing will fail.

## Technical details

Android 10 on Samsung Galaxy M31

## Additional context

The wearable used was the Polar V800.

**Comment by ralle12345** [comment]
CWA does not interfere with the sync process of my Fitbit Charge 3. So it seems to be a problem on Polar's side IMHO.

**Comment by jakobmoellersap** [comment]
As mentioned above this looks like an issue on Polar Flow. Therefore I will close this issue.
