### ISSUE TITLE
Risiko-Ermittlung nicht möglich

### ISSUE THREAD

**Issue by Zoidson** [corona-warn-app/cwa-app-android#645]
Ich habe CWA am 15.06. installiert.
Heute ist 18.06.
Ich bekomme die Meldung
"Risiko-Ermittlung nicht möglich. Ihre Risiko-Ermittlung konnte seit mehr als 24 Stunden nicht aktualisiert werden. Letzte Risiko-Ermittlung: Niedriges Risiko. Aktualisiert 16. Juni, 10:28."

Handy-Modell: Huawei P30
An Uhrzeit/Datum wurde nichts verändert.
Für die App ist keine Akku-Sonderbehandlung aktiv.

**Comment by D3N14L** [comment]
Ich habe den gleichen Fehler auf einem Huawei P30 Pro beoachten können. 
Hier beschreibt jemand ebenfalls das gleiche Problem auf einem Huawei-Gerät: https://basic-tutorials.de/corona-warn-app-ihre-risiko-ermittlung-konnte-seit-mehr-als-24-stunden-nicht-aktualisiert-werden/

**Comment by D3N14L** [comment]
This is a duplicate od #637 (and #638)

**Comment by marcmuschko** [comment]
@Zoidson thank you for reporting this! We are aware of this and already working on a fix. I will post an update in #637 as soon as we have solved this.
Therefore I am closing this duplicate issue now.

Thanks and best,
Marc
