### ISSUE TITLE
"1 of  days active"

### ISSUE THREAD

**Issue by ansvonwa** [corona-warn-app/cwa-app-android#647]
## Describe the bug

After a little more than one day of usage, the app displays it is "1 of&nbsp;&nbsp;days active".

<img src="https://user-images.githubusercontent.com/9501177/85037101-35d2de00-b185-11ea-9b69-9507de87260d.jpg" width="300"/>

## Expected behaviour

I would expect a number between the two consecutive spaces.

## Steps to reproduce the issue

1. Install the app
2. Open and close it
3. Wait more than one day
4. Open it and look at the green box

## Technical details

Observed on Android 10

**Comment by tomjschwanke** [comment]
As mentioned in #618, the newest update 1.0.2 fixes this.

**Comment by pwoessner** [comment]
Hi @ansvonwa , 

thanks for your issue. This was resolved in #446 . The fixed version 1.0.2 is now also available in the Play Store as an update.

Best regards,
Philipp
