### ISSUE TITLE
Show the number of stored keys in the local database

### ISSUE THREAD

**Issue by asdil12** [corona-warn-app/cwa-app-android#65]
## Feature description

The app receives keys from other smartphones via bluetooth and stores the keys for the last 14 days (IIRC) in the local database. Even though the app doesn't know if multiple keys in the local db correspond to one single person in real life, it would be nice to have this number as it could be used as a rough indicator if the app is working at all and give some transparency how well it is performing.

Also it could be helpful by providing some feedback to the user how well he is keeping distance to other people eg. by looking at the counter before and after going to the supermarket.

The counter could be put into a debug submenu to prevent confusing users with less technical knowledge.

## Problem and motivation

As a technically interested person I would like to gain some insignts und transparency how the app is performing.

## Is this something you're interested in working on

No

**Comment by raethlein** [comment]
Hey @asdil12, thanks for opening the issue! Based on the [API specification](https://static.googleusercontent.com/media/www.google.com/en//covid19/exposurenotifications/pdfs/Android-Exposure-Notification-API-documentation-v1.3.2.pdf), it seems as it is currently not possible to get the information of how many Rolling Proximity Identifiers you have collected from the API. Hence, this is not something the app can decide or provide.
