### ISSUE TITLE
Does clearing the cache or all data cause irretrievable tracing data loss?

### ISSUE THREAD

**Issue by corneliusroemer** [corona-warn-app/cwa-app-android#651]
Was requested to be opened as a separate issue by @jakobmoellersap:

Does clearing the cache or all data cause irretrievable tracing data loss?

This is what @MikeJayDee originally wrote about this:

>Clearing the cache or even all data should not be a problem in my view; the received rolling proximity identifiers, and the daily tracing keys used to calculate the sent rolling proximity identifiers are not stored by the app, but by the API.

>Would be good if someone could confirm.

>The only disadvantage might be that the app would then incorrectly state that it has only been active for a day, but that's just a minor inconvenience (I had the Latvian app installed for two weeks or so, so in principle the CWA should show "14 of 14 days active" for me, but as the app does not have this information, it only shows "1 of 14 days active").

_Originally posted by @MikeJayDee in https://github.com/corona-warn-app/cwa-app-android/issues/574#issuecomment-645235187_

**Comment by tkowark** [comment]
We now have added this question to the FAQs and the answer is, in short, that only deletion via the system settings will delete the collected RPIs:
https://www.coronawarn.app/en/faq/#delete_random_ids
