### ISSUE TITLE
Recording and Updates seem not to work

### ISSUE THREAD

**Issue by Timo1993** [corona-warn-app/cwa-app-android#654]
I have used the app on a Xiaomi Redmi 5 with MIUI 11 without errors. GPS and Bluetooth is enabled and the app showed me a risk level.
However the last update was two days ago at 2pm. 

Therefore I expect that the updates do not Work. Furthermore the usage time decreased from 2 days (of 14 days) to 0 days (of 14 days). 

Are there known issues with the MIUI Energy saving mode? From my experience, Background applications (services) are killed after some time.

**Comment by MareikeTaeubner** [comment]
I did have the same issue on my OnePlus 3 (Android 9). My last update was on June 16, 11:59 AM.

Disabling and reenabling exposure logging yesterday did not work. But rebooting the phone seems to have fixed it, I just received the next update.

**Comment by nicouh** [comment]
Can confirm. I run it on my Xiaomi 9T with all updates installed, but the risk level only gets updated once after I reboot. Otherwise it says not updated "seit vorgestern" ('since the day before yesterday'), etc.

**Comment by astrukme** [comment]
I can partly confirm this behavior on a Nokia 5 (TA-1053) with Android Vers. 9 (sec. update 01.04.2020)
Even after rebooting the phone, there is no update (last update 17.06.2020 / 3 of 14 days active).

**Comment by astrukme** [comment]
Seems to be the same bug as referenced in #621

**Comment by Timo1993** [comment]
Reboot did not solve problem

**Comment by kaddyr** [comment]
My Xiaomi Redmi Note 8T (Android 9, MIUI 11.0.9) has the same problem. The app is 4/12 days enabled and shows "Aktualisiert 16. Juni, 10:00" and "Risikoermittlung nicht möglich". The date is the moment I installed it, therefore it never updated but on the first start. Rebooting and enabling the app in battery saver mode does not help. I really wish for a manual updating button, cause right now the app is completely useless for me.

**Comment by skick3** [comment]
Das klingt nach einem Xiaomi und Stromsparmodus-Problem. Die Lösung:
> Hier müsst Ihr den Punkt "Autostart" beziehungsweise "App-Start" suchen. Bei Huawei-Smartphones findet sich dieser je nach OS-Version entweder direkt im "Apps"-Menü oder bei den Stromspar-/Akku-Optionen. Bei Xiaomi-Telefonen liegt der Punkt im Unterverzeichnis "Rechte" unter "Apps" verborgen.

That sounds like a Xiaomi and power saving problem. The solution:
> Here you have to search for "auto-start" or "app-start" On Huawei smartphones, depending on the OS version, you can find it either directly in the "Apps" menu or in the power save/battery options. On Xiaomi phones, the item is hidden in the "Apps" subdirectory in the "Rights" folder.

Quelle/Source: https://www.androidpit.de/corona-warn-app-probleme-loesungen-fehler-bugs

**Comment by tkowark** [comment]
In the meantime, the team identified a workaround that solved the problem at least for some users: https://www.coronawarn.app/de/faq/#no_risk_update. Would be great if you can let us know whether it worked for you as well.

Of course, the team is nevertheless still working on a proper solution for the issue.

**Comment by Timo1993** [comment]
@tkowark It did not solve the problem. The web request seems to be not reliable. Sometimes I get the Error "Error web request 901". I have implemented an own ble application some time ago which worked without any crash. So it is obviously a bug.

**Comment by jakobmoellersap** [comment]
Would you mind checking out if the latest Version (1.0.4 as of now) solves this problem for you? Also as a hint: 901 is an UnknownHostException that could result from blocking out the t-systems domain or tampering with your internet connectivity.

**Comment by Timo1993** [comment]
The update seems to work now. However I would recommend to close the bug tomorrow. Then you can see if the bug still persists.

**Comment by tkowark** [comment]
Thanks a lot. Would be great if you can close the issue yourself if the state is properly updated tomorrow.

**Comment by Timo1993** [comment]
Another update today. So it seems to work.

**Comment by MareikeTaeubner** [comment]
@tkowark it is a bit late, but I can confirm that the app update fixed it on OnePlus 3 too - no additional reboot was necessary to receive the next update from the backend.
