### ISSUE TITLE
Exposure Logging is in false "active" state when Internet is turned off

### ISSUE THREAD

**Issue by jpizarrom** [corona-warn-app/cwa-app-android#657]
## Describe the bug

After switching off the Internet, the app displays that Exposure Logging is not active, when in fact it should be active.

## Expected behaviour

Exposure Logging should not depend on whether the Internet is active or not.
Internet connection should be only used to get ids or send ids of persons with positive corona tests, and this could be done only when there is internet connection.
The interchange of ids should depend only on bluetooth, because this should be done peer to peer, between phones.

## Steps to reproduce the issue

1. download the app
1. agree to exposure logging
1. turn internet off

## Technical details

- Android 8.1.0

## Possible Fix

Separate the concept of the Exposure Logging

1. interchange of ids using bluetooth (depends only on bluetoth)
1. send my ids (depends only on internet)
1. get my ids (depends only on internet)

**Comment by kbobrowski** [comment]
@jpizarrom I think you may have in mind the same issue as corona-warn-app/cwa-documentation#262 , it's in the documentation repository since it affects both apps

**Comment by marcmuschko** [comment]
@jpizarrom thanks for reporting this issue! It is a valid concern, however as pointed out by @kbobrowski (thanks!) it is a general issue relevant for iOS and Android, therefore please move the discussion to the [documentation repository issue 262](https://github.com/corona-warn-app/cwa-documentation/issues/262).

Thanks and best,
Marc
