### ISSUE TITLE
[UX] Risk View Countdown unclear

### ISSUE THREAD

**Issue by kosmar** [corona-warn-app/cwa-app-android#658]
not sure how to submit UX issues that affect all platforms
so here is just a reference:
https://github.com/corona-warn-app/cwa-app-ios/issues/719

**Comment by ironjan** [comment]
@tkowark https://github.com/corona-warn-app/cwa-app-ios/issues/719 can also be moved to documentation ;)

**Comment by tkowark** [comment]
Already done :) As mentioned, we're working on a better process for that and keep you posted about that.
