### ISSUE TITLE
[UX] hotline / help

### ISSUE THREAD

**Issue by kosmar** [corona-warn-app/cwa-app-android#659]
crossplatform issue:

https://github.com/corona-warn-app/cwa-app-ios/issues/706

**Comment by ironjan** [comment]
@inf2381 Should https://github.com/corona-warn-app/cwa-app-ios/issues/706 be moved to cwa-documentation? This seemed common practice for cross platform issues.

**Comment by tkowark** [comment]
Yes, we'll move 706 to documentation and close this one here. We're also working on finding a more obvious place for such cross platform feature requests to make this a bit clearer where everything should go to in the first place.
