### ISSUE TITLE
Change default branch to dev

### ISSUE THREAD

**Issue by ironjan** [corona-warn-app/cwa-app-android#664]
## Current Implementation
Currently, the default branch is `master`.

## Suggested Enhancement
Change the default branch to `dev`.

## Expected Benefits

According to [github's PR explanation](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request#changing-the-branch-range-and-destination-repository), pull requests automatically compare with the repository's default branch: 
> By default, pull requests are based on the parent repository's default branch.

Currently, this repository's base branch is `master` despite the [contributing document](https://github.com/corona-warn-app/cwa-app-android/blob/master/CONTRIBUTING.md#pull-request-checklist) implicitely stating that `dev` is the base branch:
> Branch from the dev branch and ensure it is up to date with the current dev branch before submitting your pull request. If it doesn't merge cleanly with dev, you may be asked to resolve the conflicts. Pull requests to master will be closed.

In addition, when cloning the repository, the default branch is automatically checked out by git. Setting the default branch would simplify the process of getting started.

Finally, the master branch is "not up to date" with current development as it only gets updated once a release is made. This could potentially lead to duplicate work (auto-checkout of master, implement fix, re-do work on dev) or "already fixed in dev"-issues.

---
On a side-note: the `master` branch could also benefit from a rename to `releases` or similar. This conveys what the branch actually is responsible for and also [removes the "racially-charged" nature of the branch name `master`](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/).

Note that this issue is explicitly about changing the default branch. Any discussions about renaming the `master` branch lie with the maintainers and should not be part of this issue here.

**Comment by jakobmoellersap** [comment]
Hi :) We are currently checking out if this has implications on our build environment but currently I am confident we can pull this through and do the change but I want to be sure this has no further implications disrupting our delivery processes. Thanks for making us aware of it again!

**Comment by jakobmoellersap** [comment]
Default is now dev.
