### ISSUE TITLE
App Translation

### ISSUE THREAD

**Issue by winacid** [corona-warn-app/cwa-app-android#666]
Please translate the app to more languages.

https://www.destatis.de/DE/Themen/Gesellschaft-Umwelt/Bevoelkerung/Migration-Integration/Tabellen/auslaendische-bevoelkerung-staatsangehoerigkeit-jahre.html

**Comment by marcmuschko** [comment]
@winacid thanks for reaching out! 
Please move the discussion to #86,
I am closing this as duplicate as it is already ongoing.

Thanks and best,
Marc
