### ISSUE TITLE
Button "Risiko-Ermittlung Einschalten" is displayed even though risk detection a still active

### ISSUE THREAD

**Issue by tricodon** [corona-warn-app/cwa-app-android#667]
## Describe the bug

Button "Risiko-Ermittlung Einschalten" is displayed even though risk detection a still active since 3 days. Also a "risk detection is not possible" message is shown.

## Expected behaviour

If risk detection is active, no "activate" button is displayed.
 
## Steps to reproduce the issue

- Blutooth always on
- first day: "Unknown Risk" grey background
- 2nd day: "Low risk" green background
- 3rd day: "Risk detection not possible" white background, "Last detection: Low Risk on 16th June"

## Technical details

App: 1.0.2
HUAWEI P10
VTR-L09
Android 9.0.1
30GB free space on device

**Comment by marcmuschko** [comment]
@tricodon thank you for reporting this error! 
We are aware of this and already working on a fix, I will update #637 once it is fixed.

Meanwhile, please make sure you are using the most recent version of the Corona-Warn-App and if possible, disable battery optimizations for the Corona-Warn-App.
I am closing this issue to avoid duplicates. 

Thank you and best,
Marc
