### ISSUE TITLE
Diagnosis Keys Upload: Transmission Risk Levels are applied in reverse order

### ISSUE THREAD

**Issue by mh-** [corona-warn-app/cwa-app-android#678]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only - I think so, on iOS the [sort order](https://github.com/corona-warn-app/cwa-app-ios/blob/5618da6fc3faa4ecef3a6763250230501fae3774/src/xcode/ENA/ENA/Source/Services/ExposureSubmissionService.swift#L207) seems to be correct.
* [x] Bug is not already reported in another issue (at least I didn't find it)

## Describe the bug

The "Epidemiological Motivation of the Transmission Risk Level" [document](https://github.com/corona-warn-app/cwa-documentation/blob/master/transmission_risk.pdf) gives the "Transmission risk level for the Base Case" (Figure 14) as **5, 6, 8, 8, 8, 5, 3, 1, 1, 1, 1, ...** for values 0..13 of _Delay from Exposure to Consent for Upload_. This is counting backwards, 0 (today) should be assigned **5**, 1 (yesterday) should be assigned **6**, and so on.

However, `fun List<TemporaryExposureKey>.transformKeyHistoryToExternalFormat()` [(link)](https://github.com/corona-warn-app/cwa-app-android/blob/c2e5bd49093193060dded4d1545f783a498a96da/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ProtoFormatConverterExtensions.kt#L35) assigns these values the other way around: The key with the _lowest_ `rollingStartIntervalNumber`, i.e. the _oldest_ key is assigned **6** (**5** as the value for today is ignored, because the API doesn't provide today's key), and so on.

## Expected behaviour

The risk levels should be applied as explained in the "Epidemiological Motivation of the Transmission Risk Level" document, not the other way around, because then risk levels would make no sense. (This is not extremely critical in the beginning of the roll-out, when users have only 6 keys to upload, as the curve is quite symmetrical on the left end, but will cause nonsense risk estimations once users have all 14 keys saved on their device.) 

## Possible Fix

I plan to provide a Pull Request with a fix and a test case for the function.

**Comment by tklingbeil** [comment]
I think you are right. 

This should be `this.sortedWith(compareBy { it.rollingStartIntervalNumber }).asReversed()` instead of just `this.sortedWith(compareBy { it.rollingStartIntervalNumber })`.

**Comment by mh-** [comment]
Yep, and maybe do .asReversed() again afterwards, so that the list is ordered again - although I'm not sure if that matters.
I'm currently working on a PR for this, including a test case.

**Comment by mh-** [comment]
@tklingbeil The part that I don't understand yet: I think that, because today's TEK cannot be retrieved from the API, a second `SubmitDiagnosisKeysTransaction` will be triggered one day later, is that correct? Will this again upload 14 keys, with the same Transmission Risk Level profile, but shifted by one day? Or should this upload only one key, and use the `TRANSMISSION_RISK_DAY_0 = 5` risk level? I didn't find that.

**Comment by ChristopherSchmitz** [comment]
Resolved. Thanks!

**Comment by mh-** [comment]
> @tklingbeil The part that I don't understand yet: I think that, because today's TEK cannot be retrieved from the API, a second `SubmitDiagnosisKeysTransaction` will be triggered one day later, is that correct? Will this again upload 14 keys, with the same Transmission Risk Level profile, but shifted by one day? Or should this upload only one key, and use the `TRANSMISSION_RISK_DAY_0 = 5` risk level? I didn't find that.

According to [this statement](https://github.com/corona-warn-app/cwa-documentation/issues/326#issuecomment-647470114), no second submission is planned.

**Comment by daimpi** [comment]
> 
> 
> > @tklingbeil The part that I don't understand yet: I think that, because today's TEK cannot be retrieved from the API, a second `SubmitDiagnosisKeysTransaction` will be triggered one day later, is that correct? Will this again upload 14 keys, with the same Transmission Risk Level profile, but shifted by one day? Or should this upload only one key, and use the `TRANSMISSION_RISK_DAY_0 = 5` risk level? I didn't find that.
> 
> According to [this statement](https://github.com/corona-warn-app/cwa-documentation/issues/326#issuecomment-647470114), no second submission is planned.

The second submission (for the last day) seems to be something they actually want to support and have on their radar. It just didn't make it into the first release: https://github.com/corona-warn-app/cwa-documentation/issues/326#issuecomment-648000824

**Comment by tklingbeil** [comment]
Correct.
