### ISSUE TITLE
Beacons are sent only sporadically on OnePlus 6, Android 10

### ISSUE THREAD

**Issue by florianwgnr** [corona-warn-app/cwa-app-android#684]
Because the app doesnt provide any feedback or stats about beacons sent/received, i used "BeaconScope" on an other device to check if the app works.

## Describe the bug

In our household we have two main phones: an iphone and my android phone (OnePlus 6. Android 10). When i opened up "BeaconScope" on a third device to check if both phones advertise themselves correctly, i could only see the iPhone, sending out beacons with a 1 Hz rate. 

After turning the androids bluetooth off and on again the phone appeared, i could see it with BeaconScope but only for 1 or 2 packets. Then it disappears while the iPhone still works fine. Every once in a while (30s up to 5 min interval) it appears again, sends out 2 or 3 packets and disappears again. 

Even after turning energy-saving off for the app, it still does not work correctly.

## Expected behaviour

I expect the app to send out beacons in a fixed interval, e.g. 1 Hz. 

## Technical details

First screenshot: both phones are discovered

![Screenshot_20200620-101159](https://user-images.githubusercontent.com/39341393/85197842-0a1a3a00-b2e4-11ea-8914-e9ae935454ba.png)

Second screenshot, 8 seconds later: only the iphone is still sending beacons

![Screenshot_20200620-101206](https://user-images.githubusercontent.com/39341393/85197844-0be3fd80-b2e4-11ea-8775-311b0425cd0d.png)

## Additional context

This issue kind of relates to https://github.com/corona-warn-app/cwa-wishlist/issues/5 because stats about beacons sent or received/stored in DB could show that somethings might be wrong here. 

---
Internal Tracking ID: EXPOSUREAPP-1933

**Comment by kbobrowski** [comment]
I gave it a quick smoke-test: two devices (OnePlus 5T with Android 10 and Motorola G2 with Android 6) next to each other and at the same very short distance to sensitive Bluetooth antenna (10 cm). Frequency is the same, but indeed OnePlus seems to be transmitting beacons with **much** weaker signal strength, corresponding to measured distance (if we translate it with proper equation) couple of times greater than for Motorola beacons. Maybe this is a factor why you don't see as frequent beacons from OnePlus device. But don't take my word for it - I'm also listening to music over Bluetooth on OnePlus so these are not laboratory conditions (although quite real-life).

![oneplus_vs_moto](https://user-images.githubusercontent.com/28542783/85199271-06041180-b310-11ea-83d8-d094bf6974cc.png)

**Comment by florianwgnr** [comment]
> Maybe this is a factor why you don't see as frequent beacons from OnePlus device

Although these results are interesting (weaker signal, but still frequent), in my test scenario the iPhone was placed 4 meters away (as seen in the screenshot), but the Oneplus was placed next to the test phone (sometimes the distance is displayed correctly with 0,1m, sometimes not (2m)).

**Comment by kbobrowski** [comment]
That's interesting, perhaps there is some hardware issue with OnePlus 6 (I wonder if it differs much in terms of hardware from OnePlus 5T). Can just confirm that when placed far away from receiver in the second room, and with all applications closed the results from OnePlus 5T and Motorola seem to be consistent:

![moto_vs_oneplus_2](https://user-images.githubusercontent.com/28542783/85199861-7745c380-b314-11ea-95fa-c840925e7bd8.png)

**Comment by sansha** [comment]
I’d like to add to this that the app shows conflicting information on my Oneplus 6 also on Android 10, Oxygen OS v10.3.4
As you can see in this picture:
![537C1CE6-5D83-4709-AABA-4D69E118C1D1](https://user-images.githubusercontent.com/11016199/85295458-3e3a5a00-b4a0-11ea-9c11-080f0a8e13d0.jpeg)
The top bar shows that I have tracing enabled, but the card below it says it is not. If I click on „einschalten“ this does not change. I have also set the app to „not optimized“ in battery settings.

**Comment by heinezen** [comment]
Hey @florianwgnr,

 Did the bug eventually disappear for you?

Regards,
CH

---
Corona-Warn-App Open Source Team

**Comment by florianwgnr** [comment]
> Hey @florianwgnr,
> 
> Did the bug eventually disappear for you?

I just checked it again and yes, beacons are now sent regularly. Thanks!

**Comment by heinezen** [comment]
@florianwgnr Thanks for checking. One bug less to worry about :)

----
Corona-Warn-App Open Source Team
