### ISSUE TITLE
"Risikoermittulng nicht möglich" after manually setting a date in the past

### ISSUE THREAD

**Issue by joe-sch** [corona-warn-app/cwa-app-android#685]
Two days ago I set the date of the device to two days in the past (16.06.2020).
After a day I reset the device to network time. Since then, the app says "Risikoermittulng nicht möglich"
I installed the app on the day it came out, also on June 16.

## Technical details

- Mobile device: Xiaomi 9t
- Android version: 10 QKQ1.190825.002

**Comment by skick3** [comment]
Hi Joe,
das klingt nach einem Xiaomi und Stromsparmodus-Problem. Die Lösung:
> Hier müsst Ihr den Punkt "Autostart" beziehungsweise "App-Start" suchen. Bei Huawei-Smartphones findet sich dieser je nach OS-Version entweder direkt im "Apps"-Menü oder bei den Stromspar-/Akku-Optionen. Bei Xiaomi-Telefonen liegt der Punkt im Unterverzeichnis "Rechte" unter "Apps" verborgen.

Quelle: https://www.androidpit.de/corona-warn-app-probleme-loesungen-fehler-bugs

**Comment by de-hash** [comment]
Si

Risikoermittlung nicht möglich:
Similar error on Samsung Note 10
I'm using the app since it was published.
Today I noticed the error message:
Description: 
"Ihre Risiko-Ermittlung konnte seit mehr als 24 Stunden nicht aktualisiert werden"

**Comment by jakobmoellersap** [comment]
Hi! Thanks for your issue description. As of now manual date / time settings are not supported, as our Index relies on UTC based on the automatic Timezone Calculation of your device. This might change in the future but for now we will only support automatic date and time. If you still want to use the App, my suggestion is to reset the App after switching to automatic Date/Time Calculation by your device. Sorry for the inconvenience.

**Comment by joe-sch** [comment]
Hi,thanks for your explanation. I've already resetted the app.
I understand that it is a problem if the datetime setting is switched to manual setting and the app cannot work properly during this time. 
I hoped that it might be possible to get the app more robust, that it can recover from the state if the device time is resetted to  automatic Date/Time Calculation.
