### ISSUE TITLE
Display number of contacts

### ISSUE THREAD

**Issue by joerghaf** [corona-warn-app/cwa-app-android#689]
## Avoid duplicates
* [x ] Feature request is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Feature request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x ] Feature request is not already reported in another issue

## Feature description

It would be interesting for me as a user if the app would show the number of contacts with other devices. As a user, that would give me a feeling of whether the system "works". To maintain anonymity, only one update per day.

Example:
- Detected contacts: 10 devices
- Contacts >15min: 2 devices

## Problem and motivation

As a user, that would give me a feeling of whether the system "works".

## Is this something you're interested in working on

No

**Comment by tens0rfl0w** [comment]
This is not possible to accomplish, please see my [comment](https://github.com/corona-warn-app/cwa-app-ios/issues/678) on this issue in the iOS repository.

**Comment by ModdyLP** [comment]
I think that is possible to implement. You can count the number of local stored keys for example. That would give a first impression on how many contacts there are. The time is more complicated i think. If I am wrong with this idea, pls tell me.

**Comment by tens0rfl0w** [comment]
> I think that is possible to implement. You can count the number of local stored keys for example. That would give a first impression on how many contacts there are. The time is more complicated i think. If I am wrong with this idea, pls tell me. 

Please see my mentioned comment above for the reason you cannot count the total number of keys. The app has only restricted access to the key database and cannot fetch all keys. More precisely, the app only gets information from framework if a matching key was tested positive.

**Comment by JProof** [comment]
similar to  https://github.com/corona-warn-app/cwa-wishlist/issues/5

**Comment by tkowark** [comment]
Thank you all for your feedback and @joerghaf for the initial idea. Since we already have a wishlist item for that, we'll close this ticket here in this repository.
