### ISSUE TITLE
Add en-US strings for ease of understanding features and use-cases for development purposes

### ISSUE THREAD

**Issue by kedar1607** [corona-warn-app/cwa-app-android#69]
## Current Implementation
Currently when app is run on the phone with with any locale, all of the content within the app is only in German. This sometimes can get harder for people to understand the requirements and feature use-cases. 

## Suggested Enhancement
I'm proposing that we add en-US strings.

## Expected Benefits
Easy understanding.

**Comment by marcauberer** [comment]
#60 will resolve this

**Comment by kedar1607** [comment]
> #60 will resolve this, once it's merged.

Ah, thanks for pointing that out. @marcauberer I'll go ahead and close this.

**Comment by marcauberer** [comment]
Could you reopen this? My pr got rejected.

**Comment by kedar1607** [comment]
Reopening as this might be needed.

**Comment by marcmuschko** [comment]
Hello @kedar1607,

thank you for pointing this out. 
We have English translations in our backlog and we will add them as soon as possible once the texts are final and approved. For further reference please have a look at issue #72. 
To avoid multiple threads on one topic, I will close your issue for now as it is part of #72. 

Thank you and best,
Marc
