### ISSUE TITLE
App is not compatible with Samsung Galaxy A6 (year of purchase 2019)

### ISSUE THREAD

**Issue by Peter-PA6** [corona-warn-app/cwa-app-android#690]
## Avoid duplicates

* [ x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is not already reported in another issue

## Describe the xbug

Try to install from Google Play

## Expected behaviour

App installs normally
## Steps to reproduce the issue

Select Corona App from GooglePlay from Moble Phone Samsung Galaxy A6
Error Message appears:
Corona-Warn-App
Robert Koch-InstitutGesundheit & Fitness
PEGI 3PEGI 3
39.485
Diese App ist mit keinem deiner Geräte kompatibel.

## Technical details

- iOS Version: Andriod  10
- Device: Samsung Galaxy A6

## Possible Fix
Determine the cause of incompatibility
Update the App to resolve this
![Capture_010](https://user-images.githubusercontent.com/67197176/85204778-166bba80-b317-11ea-91b9-58f2e6ef4ee9.PNG)

**Comment by Peter-PA6** [comment]
How do I change the URL to a German site please?
![Capture_011](https://user-images.githubusercontent.com/67197176/85210393-af163080-b33f-11ea-8786-f66653fc17cc.PNG)
I keep getting routed to this one in Google Play.
I have an 1&1 SIM card and I am connected via a Telekom -WLAN

**Comment by akuckartz** [comment]
@Peter-PA6 https://www.bundesregierung.de/breg-de/themen/corona-warn-app/corona-warn-app-kontakt-1759708

**Comment by realansgar** [comment]
@Peter-PA6 This isn't about a specific URL. Your Google account has to be set to Germany. This happens when you create your account or you can change it once a year in your account settings. This issue is being handled by SAP. Hopefully, the app will be released to the whole world in the near future. For further discussion, check out this issue: https://github.com/corona-warn-app/cwa-app-android/issues/478

**Comment by tkowark** [comment]
Having the app running on a Samsung A6 at home, this is indeed not a general issue but in your case seems to be the issue #478 instead. As written there and in many other issues, we're working on resolving that with the RKI and hopefully have some news on that soon.
