### ISSUE TITLE
First time contributors "Unauthorized" on CircleCI

### ISSUE THREAD

**Issue by pr1metine** [corona-warn-app/cwa-app-android#695]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Describe the bug

It appears that first time contributors are **unable to pass the CI check** which prevents them from merging pull requests **into the dev branch**. CircleCI will not carry out any checks because the **user is "Unauthorized"**.
[![IMG_0360](https://user-images.githubusercontent.com/50841263/85219355-49f42680-b3a3-11ea-8c4e-758771ac1cc9.jpeg)](https://app.circleci.com/pipelines/github/corona-warn-app/cwa-app-android?branch=pull%2F655)

What's strange is that **anyone on the master branch is allowed to be CircleCI checked**. Thing is that you are bound to fail this check.
[![IMG_0359](https://user-images.githubusercontent.com/50841263/85219384-89bb0e00-b3a3-11ea-9c3a-becedab7e6a8.jpeg)](https://app.circleci.com/pipelines/github/corona-warn-app/cwa-app-android/2241/workflows/01c99876-686e-4f1d-9650-43b5160cdf35/jobs/2224)

## Expected behaviour

New contributors are authorized to use CircleCI for the dev branch and the CI check passes. This way the maintainers **can merge the pull request**.

## Steps to reproduce the issue

1. Be a first time contributor
2. Fork this repository
3. Branch off and make some commits
4. Create a Pull Request to the dev branch

## Technical details

- CircleCI
- dev branch

## Possible Fix

Maybe there is an option to authorize anyone? Do something like the master branch?

## Additional context

I have seen it happen with Pull Requests such as #683, its duplicate, #548, and my own #677 and #655 .

**Comment by tkowark** [comment]
Could you try to remove [this line](https://github.com/pr1metine/cwa-app-android/blob/6303e3b8d82981fc96fe688a966d3b9474700858/.circleci/config.yml#L52) in the config.yml of your fork? And also the colon in the line before. Might be that the context is not accessible. If the build starts then, we'll have to remove the context and add the SONAR_TÒKEN as a separate instance variable in our builds...

**Comment by pr1metine** [comment]
Thank you @tkowark 🙏 . You def made my day.

I'll close this issue for now. Will the CI fix end up in production?

**Comment by pr1metine** [comment]
What about moving to GitHub Actions?

**Comment by tkowark** [comment]
Let's keep this issue open until that change finally made it into the master branch. Could you turn this into a separate PR?

**Comment by pr1metine** [comment]
Sorry for this necropost, this is what the CircleCI Support Engineer has to say:


> Hi Thanh,
>
> Thank you for getting back to me.
>
> I looked again at the projects settings, and it appears the "Pass secrets to builds from forked pull requests" setting is disabled for that project.
>
> Could you ask the Organization Admin to enable it? This should allow you to access the SonarCloud context.
> 
> Let me know if this helps.
> 
> Yann - Support Engineer - CircleCI

It might generally be that SonarCloud does not work with forked PRs because of said setting. But enabling this setting probably is a security hazard.
