### ISSUE TITLE
Echtes Changelog bei Updates / Real changelog for updates

### ISSUE THREAD

**Issue by jumoog** [corona-warn-app/cwa-app-android#701]
Ich habe gerade ein Update für Android bekommen und als neue Funktionen ist nur "Kleinere Verbesserungen" aufgelistet. Für eine staatliche App hätte ich mir einen echten Changelog erwartet/gewünscht.

I just got an update for Android and as new features only "minor improvements" are listed. For a government app I would have expected/wished for a real changelog.

**Comment by AndroidFire9704** [comment]
Dito, würde schon gerne wissen was SAP an der App ändert.

**Comment by DevFlamur** [comment]
Ich denke mal es kommt auf dem Update an - was ist Tatsächlich neu um da überhaupt eine 'anständige' changelog zu verfassen. Wenn es nur Bug Fixes sind muss mann ja nicht ins kleinste detail erwähnen. Aber z.b. Added Bluetooth v5 Support - wäre Prima und das nur für die nutzer, weil für entwickler ist ja open source 👌

**Comment by jumoog** [comment]
> 
> 
> Ich denke mal es kommt auf dem Update an - was ist Tatsächlich neu um da überhaupt eine 'anständige' changelog zu verfassen. Wenn es nur Bug Fixes sind muss mann ja nicht ins kleinste detail erwähnen. Aber z.b. Added Bluetooth v5 Support - wäre Prima und das nur für die nutzer, weil für entwickler ist ja open source 👌

Ja ich denke da an den "normalen" Benutzer

**Comment by MikeJayDee** [comment]
I think it would be good to give a brief description of even small changes, e.g. "increased stability in fetching diagnosis keys", so that people that had a certain problem know that it was fixed.

**Comment by ch4d1** [comment]
> > Ich denke mal es kommt auf dem Update an - was ist Tatsächlich neu um da überhaupt eine 'anständige' changelog zu verfassen. Wenn es nur Bug Fixes sind muss mann ja nicht ins kleinste detail erwähnen. Aber z.b. Added Bluetooth v5 Support - wäre Prima und das nur für die nutzer, weil für entwickler ist ja open source ok_hand
> 
> Ja ich denke da an den "normalen" Benutzer



> > Ich denke mal es kommt auf dem Update an - was ist Tatsächlich neu um da überhaupt eine 'anständige' changelog zu verfassen. Wenn es nur Bug Fixes sind muss mann ja nicht ins kleinste detail erwähnen. Aber z.b. Added Bluetooth v5 Support - wäre Prima und das nur für die nutzer, weil für entwickler ist ja open source ok_hand
> 
> Ja ich denke da an den "normalen" Benutzer

Würde es für nicht git affine Nutzer zumindest transparent machen und das ist ja das Ziel bei der App Entwicklung.

**Comment by ironjan** [comment]
Duplicate of #511 and #623 

However, since this issue popped up, I don't think that the problem of missing changelogs was fixed.

**Comment by jumoog** [comment]
![photo_2020-06-22_11-53-25](https://user-images.githubusercontent.com/5268791/85274466-446c0e80-b47f-11ea-91ee-6f708cb69940.jpg)

**Comment by DavAlbert** [comment]
Lasst doch Deutsch schreiben, diese App wird eh nur hier verwendet

**Comment by ironjan** [comment]
Nach https://github.com/corona-warn-app/cwa-documentation#working-language ist die Projektsprache Englisch. Dies wird aber leider nicht direkt im cwa-android Repository erwähnt.

According to https://github.com/corona-warn-app/cwa-documentation#working-language, the working language is English. Unfortunately, there is no explicit mention of the project language within the cwa-android repository.

**Comment by jsuelwald** [comment]
Yes, this is a Problem. A webpage listing versions (like 1.0.4 and so on) with detailed recent changes woudn't hurt either. 

But "small improvements" / "Kleine Verbesserungen" does not help to gain trust regarding this app.

**Comment by ferdinand** [comment]
The same applies to iOS. Therefore the issue should be moved to [corona-warn-app/cwa-wishlist](https://github.com/corona-warn-app/cwa-wishlist).

**Comment by ironjan** [comment]
@tkowark see https://github.com/corona-warn-app/cwa-app-android/issues/701#issuecomment-652352728

**Comment by tkowark** [comment]
> The same applies to iOS. Therefore the issue should be moved to [corona-warn-app/cwa-wishlist](https://github.com/corona-warn-app/cwa-wishlist).

Actually, we don't have to go the wishlist route. We heard your feedback and now established a process to turn the Github changelogs into proper communication for the app store releases. We'll leave the issue open until the next app store release.

**Comment by alqu** [comment]
>> The same applies to iOS. Therefore the issue should be moved to corona-warn-app/cwa-wishlist.
>
> Actually, we don't have to go the wishlist route. We heard your feedback and now established a process to turn the Github changelogs into proper communication for the app store releases. We'll leave the issue open until the next app store release.

Actually, in the iOS App there is already a proper changelog - see corona-warn-app/cwa-app-ios#691.

**Comment by jumoog** [comment]
okay its fixed

![grafik](https://user-images.githubusercontent.com/5268791/88094676-41566200-cb94-11ea-9451-cdc6937509d6.png)
