### ISSUE TITLE
Opening app in landscape mode causes immediate recreation of UI in portrait

### ISSUE THREAD

**Issue by ironjan** [corona-warn-app/cwa-app-android#710]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue
   * Closely related to #630 - however, #630 prefers to add support for landscape. This issue here solely is interested in "the current behavior does not match the assumed design protrait-only" and prefers to "never open in landscape".
   * Opened as a separate issue because of the fundamental difference in preferred solution

## Describe the bug

When the phone is in landscape mode, the app first shows as landscape and is then re-oriented as portrait.

## Expected behaviour

The current design seems to imply "portrait only". Consequently, the app should never be shown in landscape.

## Steps to reproduce the issue

1. Open CWA
2. Switch to another app supporting landscape
3. Turn the phone into landscape
4. Switch back to CWA via gesture navigation (thus, not turning the phone)

## Possible Fix
As described in https://github.com/corona-warn-app/cwa-app-android/issues/630#issuecomment-646537149

I assume that the cause is that the screen orientation is set **after creation of the activity** (L108), i.e. the activity is created in landscape, then turned:

https://github.com/corona-warn-app/cwa-app-android/blob/dev/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt#L96-L109

Adding `android:screenOrientation="portrait"` to the corresponding activity-tag in the `AndroidManifest.xml` may fix this issue/create and lock the activity in portrait mode. An alternative approach could be to move the preferred orientation  requesting into an earlier callback (perhaps `onActivityStarted`).

## Additional context

I'm interested in working on this issue but cannot get to it until next weekend. If anyone would like to pick it up, feel free to do so.

**Comment by AlexanderAlferov** [comment]
@ironjan , I just tried your proposed solution and it worked. It would be shipped with one of the nearest releases.
Thank you for your input!

**Comment by AlexanderAlferov** [comment]
@ironjan, PR was merged: https://github.com/corona-warn-app/cwa-app-android/pull/738

**Comment by ironjan** [comment]
@aleksandr-tikhonov thanks.
