### ISSUE TITLE
If INet is not active User gets irritating Message.

### ISSUE THREAD

**Issue by ewicms** [corona-warn-app/cwa-app-android#715]
## Current Implementation
(A) If you are alone and have INet connection the screen shows "RISIKO-ERMITTLUNG AKTIV".

(B) In the case you are out in a crowd, e.g. buying your groceries, but do not have an INet Connection, the info line shows "KEINE INTERNETVERBINDUNG".

It's correct but might give the user the feeling that the Bluetooth measurements aren't working too.

![irrit000](https://user-images.githubusercontent.com/20739565/85310861-d3dfe480-b4b4-11ea-9933-c8652ce6a984.png)

## Suggested Enhancement
Maybe use in the Info-Line three words:
"RISIKO ERMITTLUNG ABGLEICH"
Put "RISIKO" in black and use green|red for the states of "ERMITTLUNG" and "ABGLEICH"?!?.

**Comment by aurisnoctis** [comment]
duplicate of https://github.com/corona-warn-app/cwa-backlog/issues/1

**Comment by tkowark** [comment]
Yes, this is indeed part of the linked issue. Thanks for bringing this to our attention, though!
