### ISSUE TITLE
Text and Translation Contributions

### ISSUE THREAD

**Issue by marcmuschko** [corona-warn-app/cwa-app-android#72]
Dear contributers,

first of all, we are really happy to see the amazing support we are receiving from the community, thank you very much for that! 
As we have encountered several issues and pull requests regarding translations and text improvements that we sadly had to reject, I am creating this pin thus adding it to the list of known issues as soon as possible. 

Text and translation are not handled by the development team but by a dedicated stream within the project. Once they are finalized, they will replace them alltogether which should solve all related issues.
**Therefore, to reduce efforts for everyone, we cannot accept PRs regarding texts and translations at the moment.** Once the final texts and translations are available I will close this issue.

Thank you for understanding! 
Best regards,
Marc

**Comment by kedar1607** [comment]
If anyone at all wants to get english strings, they can get from https://github.com/corona-warn-app/cwa-app-android/pull/60 and put the english strings.xml file in values-en-US folder *locally* in their Android studio project *without commiting* the file. I hope that helps people understand the context.

**Comment by mh-** [comment]
> Once the final texts and translations are available I will close this issue.

Will they be 'final' or will there be another chance for corrections?

**Comment by marcmuschko** [comment]
@mh- 
As soon as I close this issue, we should have all texts within the app for German and English ready and approved. Then of course we certainly are looking forward for feedback because it still can be the case that we have a few typos (I don't hope so but you never know).... So yes, another chance for improvement suggestions is coming :)

**Comment by mlenkeit** [comment]
Let me just take the opportunity to point out that the German texts in values-de still have inconsistencies, such as:
- COVID-19 vs. Covid-19 (upper case vs. lower case)
- Smartphone vs. Handy
- [Kassenärztlicher Notdienst](https://github.com/corona-warn-app/cwa-app-android/blob/9aada864536c2ed58b171cb41414817b562322c6/Corona-Warn-App/src/main/res/values-de/strings.xml#L240) does not seem to exist (see [Google search](https://www.ecosia.org/search?q=kassen%C3%A4rztlichen+bereitschaftsdienst&addon=chrome&addonversion=3.2.0&method=topbar)), AFAIK, it's "ärztlicher Bereitschaftsdienst" (see [116117.de](https://www.116117.de/de/index.php))

**Comment by kaluju** [comment]
> Let me just take the opportunity to point out that the German texts in values-de still have inconsistencies, such as:
> 
> * ~COVID-19 vs. Covid-19 (upper case vs. lower case)~
> * Smartphone vs. Handy -**-> all instances changed to "Smartphone" except 2 legal texts, which I can't change myself.** 
> * [Kassenärztlicher Notdienst](https://github.com/corona-warn-app/cwa-app-android/blob/9aada864536c2ed58b171cb41414817b562322c6/Corona-Warn-App/src/main/res/values-de/strings.xml#L240) vs [ärztlicher Notdienst](https://github.com/corona-warn-app/cwa-app-android/blob/195c7ef4465122f7277ce9ad3c326a94abae7af4/Corona-Warn-App/src/main/res/values-de/strings.xml#L543)  - according to [116117.de](https://www.116117.de/de/index.php), it's "ärztlicher Bereitschaftsdienst", though [Wikipedia](https://de.wikipedia.org/wiki/%C3%84rztlicher_Notdienst) knows multiple terms; anyway, should be consistent in the app

**--> all instances changed to "ärztlicher Bereitschaftsdienst"**
