### ISSUE TITLE
"unchanged exposure risk" notification is shown and cannot be turned off

### ISSUE THREAD

**Issue by ironjan** [corona-warn-app/cwa-app-android#729]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
  
* [x] Bug is not already reported in another issue

## Describe the bug

Today I received a notification that my exposure risk did not change within the last week. Since this information is useless, I wanted to turn off this notification and went to "Settings - Notifications". There were two options, none of which is concerned with "unchanged exposure risk":

 * "your risk of infection changed" is not applicable. The notification was explicitly telling me "no change". Also, I want to receive notifications about changes.
 * "status of covid-19 test" is not applicable.

This bug occured on Android. It may however also affect the iOS app as both apps should behave the same AFAIK.

## Expected behaviour

Above notification should not be sent. It does not convey any information to the user and there is no need for the user to act in any way. 

## Steps to reproduce the issue

1. Go to Settings - Notifications
2. There is no option to turn off the "unchanged exposure risk" notification

## Possible Fix
This notification should not be sent. It does not convey any information to the user. 

An alternative to not sending the notification would be to make it configurable, i.e. an option "Your risk of infection remained the same" should be added to the notification settings. This alternative however seems much more complicated than just not sending a notification.

**Comment by jumoog** [comment]
Same problem here

**Comment by jakobmoellersap** [comment]
Unfortunately these notifications do not come from CWA, but the Google Play Services and the Exposure Notification API directly. As such we cannot influence these notifications from our side.

**Comment by ironjan** [comment]
@jakobmoellersap ok, thanks for the info. Just out of interest: is there any information about how often this notification will appear? Every 14 days?
