### ISSUE TITLE
URSACHE: 3; Etwas ist schief gelaufen.

### ISSUE THREAD

**Issue by traut21** [corona-warn-app/cwa-app-android#733]
Nachdem die Diskussion 
Fehler bei Kommunikation mit Google API(17)
#499 
zu sehr zerfasert starte ich hier mal neu:

Die Corona Warn-App scheint selbst inzwischen besser zu funktionieren. Jetzt liegt es am Geräte-Hersteller, die **COVID-19-Benachrichtigungen** nachzurüsten

Die vollständige Fehlermeldung der CWA nennt:

_Ihre Corona-Warn-App ist korrekt installiert. Leider fehlen Ihrem Smartphone die Benachrichtigungen zu möglicher Begegnung mit COVID-19-Infizierten und Sie können die Corona-Warn-App nicht nutzen. Weitere Informationen finden Sie in unseren FAQ: [htps://www.coronawarn.app/de/faq/](htps://www.coronawarn.app/de/faq/) (17)_

Die Bundesregierung glaubt, dass die CWA nun auf 85 % aller Geräte laufen soll. Ich habe da ehrlichgesagt deutliche Zweifel. Berichtet doch mal, auf welchem Gerät ab Android 6 die CWA nicht läuft:

**Comment by traut21** [comment]
Hier kommt die Fehlermeldung auf 
Gerät: **Sony Xperia XA1 Plus**
Android: **8.0.0**
letztes Update: 1. August 2019

**Comment by traut21** [comment]
Ich vermute, hier fehlt das System-Update, das unter _Einstellungen > Google_ unter **Dienste** folgenden Punkt anbieten muss: **Benachrichtigungen zu möglichem Kontakt mit COVID-19-Infizierten**
![corona-app_005](https://user-images.githubusercontent.com/25948981/85508143-c67d4400-b5f3-11ea-98c2-e1247636987f.JPG)

**Comment by ChuangSheep** [comment]
Es funktioniert bei mir nicht, und die FAQ hilft gar nicht. Ich sehe keine Möglichkeit für mich, diese App zu nutzen. 

It still does not work for me even after I have read the FAQ. Appearently it just does not want us to use the app. True that this may be a problem that the app team cannot fix, but thus we could not use it, and I will not contact with google about this - I am not the developer. Instead, I just want to use this app to help to contain the virus.

**Comment by traut21** [comment]
> Es funktioniert bei mir nicht, und die FAQ hilft gar nicht. Ich sehe keine Möglichkeit für mich, diese App zu nutzen.

Welches Gerät, welche Android-Version benutzt du?

**Comment by ChuangSheep** [comment]
> > @ChuangSheep Thanks for clarifying. Can you add as much info as possible:
> > 
> > * OS version
> > * Model
> > * Play services version
> > * is anything on your phone modified from original shipped state (eg rooted, different OS etc.)
> > * are you logged into a Google account?
> > 
> > Then we have some structured info on where there are issues.
> > Plus, if possible list the things you have tried and that have failed.
> > PS: I'm not associated with the project, not getting paid or anything. Maybe also try calling the technical support hotline. Not sure this helps bit give it a go.
> 
> As in my previous comment:
> 
> > I have faced the same issue on Mi 9. My app was downloaded from Google app store so I am not so sure why it is not working
> > ```
> > CAUSE: 3
> > Some thing went wrong
> > ---
> > Cause:
> > k0.b.a.a.c.k.b:17:API:Nearby.EXPOSURE_NOTIFICATION_API is not avaliabe on this device.
> > Connection failed with: a{statusCode=UNKNOWN_ERROR_CODE(39501,resolution=null,message=null)} at ......
> > ......
> > at .... (@@17.3.0:**)
> > at android.os.Looper.loop(Looper.java:201)
> > at android.osHandlerThread.run(HandlerThread.java:65)
> > ```
> 
> **More info:**
> OS: Android 10 (MIUI 11.0.9 stable)
> Model: Mi 9 (Xiaomi)
> 
> _I have updated the framework, service und play store manually but it does not work either._
> Play service version: 20.21.17
> Play store version: 20.5.19-all [0] [PR] 316024227
> Google Framework version: 10(29)
> 
> Additional Information: The phone is not rooted, neither changed OS.
> I have logged into my google account. I believe it is worth to mention that I have 2 accounts on this phone. I'm not sure if it is because of what @Chrakker has mentioned. However, switch to the other account does not fix my issue.
> 
> > I do have the same issue but I can add a very useful insight that affects not only me, but also another user with an equal setup.
> > Whenever using/installing the app as a NON-Android Administrator account (Second User on the phone, not Guest-Account!) the BLE-beacon will not activate and throw this error.
> > When switching to the main account that has access to all the administrative features on the phone, it works abolutely fine.
> > [...]
> > Also with Sony Xperia ZX1 Compact with NON-ADMIN Account -> Same error.
> 
> **Tried:** Reboot, clear data/cache, reinstall app, manually update the google suit (framework, service, store)


Do we really need to do this every time?
Sollen wir das wirklich jedes Mal machen?

**Comment by ChuangSheep** [comment]
As the issue 499 and 508 are closed, it's clear that they will not or cannot fix the issue (Cause 3). So, we can do nothing here.

**Comment by kebechsenuef** [comment]
![02](https://user-images.githubusercontent.com/6011872/85846459-24518d80-b7a6-11ea-800c-e17e47dd66f9.png)
![01](https://user-images.githubusercontent.com/6011872/85846462-24ea2400-b7a6-11ea-8419-eb250a222bd6.png)

Although the Play Service update was okay- the error appears after successfully used 3 days using the app.
Its a unrooted Samsung Galaxy Xcover 3 SM-G388F.

**Comment by jakobmoellersap** [comment]
@kebechsenuef please refer to #737

**Comment by MysticMagican** [comment]
In meinem Fall ist das Problem der "nicht administrative" Benutzer. Hier ist meiner Meinung nach Google gefragt, damit die "EXPOSURE_NOTIFICATION" bei allen Benutzern eines Gerätes funktioniert. 
Eine Gegenprobe wäre interessant, ob dies auf generell alle Geräte zutrifft - falls nicht, gibt es mglw. doch die Chance, es ohne Zutun von Google zu lösen.

**Comment by void-arch** [comment]
Exakt die gleiche Fehlermeldung bei meiner Mutter und Großmutter. Nutzen die App beide jetzt seit 14 Tagen.
Moto G v2
Android 6.0
Google Play Services 20.21.17

**Comment by MarcusSchwarz** [comment]
39508 auch hier, auch seit gestern wie bei @void-arch. Aber nicht die selbe Meldung wie bei @kebechsenuef . Da ich warum auch immer keinen Screenshot machen kann und auch keine Lust habe, einen Stacktrace abzutippen müsst ihr auch damit zufrieden geben, dass es außer der "39508" keine weitere textliche Information gibt, was der Fehler sein könnte. Bis gestern lief die App seit Erscheinungstag einwandfrei.

**Comment by enveeed** [comment]
Gleiches Problem hier 39508 auf einem Moto G4, lief bisher einwandfrei. XPosed ist aktiv, hatte bisher keine Zeit zu testen ob es ohne läuft. Ich vermute dass das Problem Google seitig ist tbh

**Comment by traut21** [comment]
> edit: Problem ist bekannt und Lösung ist in Arbeit #737

Fehler 10 mit dem validation key ist ein anderer der hier genannte Fehler 17 mit der "_Api Exception Nearby.**EXPOSURE_NOTIFICATION_API** is not available_" - also das, wo der Smartphone-Hersteller ein System-Update anbieten muss.

**Comment by xhain** [comment]
Device: BQ Aquaris X5 Plus

```
Ursache:
com.google.android.gms.common.api.ApiException:39508
at android.support.v4.media.MediaDescriptionCompatApi21$Builder.setResultOrApiException(MediaDescriptionCompatApi21.java:3)
at com.google.android.gms.internal.nearby.zzae.onResult(com.google.android.gms:play-services-nearby@@18.0.2-eap:2)
at com.google.android.gms.common.api.internal.IStatusCallback$Stub.zaa(com.google.android.gms:play-service-base@17.3.0:2)
at com.google.android.gms.internal.base.zaa.onTransact(com.google.android.gms:play-services-base@@17.3.0:3)
at android.os.Binder.execTransact(Binder.java:565)
```

**Comment by cydur** [comment]
Ursache: 3 Etwas ist schief gelaufen
Fehler bei Kommunikation mit Google API(39509)
Auch nachdem ich alles aktualisiert und die App komplett neu installiert habe. Sie läuft immer einige Tage problemlos, dann dieser Fehler und es gibt keinen Datenabgleich mehr.
Sony Xperia Z3 Compact, Modell D5803
Android 6.0.1
Kernel 3.4.0-perf-gc14c2d5
Build Nummer 23.5.A.1.291
Google Play Dienste V 20.24.14 (040306-319035315)

**Comment by jcdescy** [comment]
Selber Fehler auch hier. Das geht tagelang und plötzlich geht es nicht mehr. Ich hab kein Auto-Update von irgendwas, darum kann es wohl an falschen Versionen nicht liegen.

**Comment by tkowark** [comment]
Since the issue again starts to mix different Android issues, we'll have to close it, unfortunately. For devices where the ENF is not available, we cannot offer any workaround and, hence, Error 17 cannot be resolved by the app. The other issues (39508, 10) are already being worked on in the above mentioned issues.
