### ISSUE TITLE
Google API Notifications: Title of the "weekly update" is misleading for low-risk status

### ISSUE THREAD

**Issue by hiergiltdiestfu** [corona-warn-app/cwa-app-android#734]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Describe the bug

After a week of operating the CWA on Android, the app produced a notification in the middle of the night, titled "Benachrichtigungen zu möglicher Bege..." with a red font color.  This produced a mild shock in the user, because the wording and the style was received as a positive hit, implying an increased infection risk.

However, the rest of the notification read "Wöchentliches Update - Dein Smartphone hat **keine** mögliche Begegnung mit infizierten Personen gefunden" and the app itself still shows the green "low risk" badge, so the risk has clearly not increased upon further inspection, i.e. a negative hit.

## Expected behaviour

The notifications title and style should directly reflect a non-hit for the negative case. 
* Should use a green font style akin to the green badge for "low risk"
* Wording of notification title should directly hint at "no hit", e.g. "Keine Begegnung mit infizierten Personen gefunden"

## Steps to reproduce the issue

![EbQXednWAAMWKwk](https://user-images.githubusercontent.com/10924590/85516989-18779700-b5ff-11ea-9878-a2df36e89ac9.jpg)

## Technical details

- App version: 1.0.4
- Mobile device: Samsung Galaxy S10e
- Android version: 10 (Kernel 4.14.113-18731944), OneUI 2.1

**Comment by MichaelPFrey** [comment]
- App version: 1.0.4
- Mobile device: Lenovo Tab E10 (Lenovo TB-X104F)
- Android Version: 8.1.0 (Kernel 3.18.71)
- Google Play-Dienste Version 20.18.17 (040300-311416286)

![Screenshot_2020-06-24-10-04-27-352](https://user-images.githubusercontent.com/24962768/85519969-912c2280-b602-11ea-966c-6834798d09b1.jpeg)

This looks like a message generated by the google play service. Clicking on the notification open the google play Dienst, not the corona-warn-app.
![Screenshot_2020-06-24-10-12-27-170](https://user-images.githubusercontent.com/24962768/85520616-727a5b80-b603-11ea-90b5-eb26c24cbe0e.jpeg)

**Comment by nhnb** [comment]
When I got that notification, I am quite sure that it said something very similar to "Wöchentliches Updates // Sie haben ein erhöhtes Risiko, weil sich Ihr Smartphone in der Nähe..." So i tapped it without paying attention to anything else. To my surprise, the Corona Warn App did not open, but I ended up on my home screen. As expected, the notification is gone.

When I opened CWA manually, It showed green with a low risk assessment.

So, now I am wondering, If i misread  that message (I guess that is by far the most likely explanation) or whether the OS did see something, but the App considered it too short or too far away.

Ending up on the home screen and not being able to find the message with a grep through this repository, seem to support the thesis, that this message is generated by the operating system/play services.

**Comment by tkowark** [comment]
This notification seems to be coming directly from the Exposure Notification Framework / the OS. We‘ll add that to the FAQ

**Comment by MikeJayDee** [comment]
May I suggest that you ask Google not to show this message in the first place? For 99.9% of users, there will not be any risk anyway so I'm not sure what it adds; it seems rather confusing to the user as they are not taken to the CWA when tapping on the notification.

**Comment by jakobmoellersap** [comment]
We are currently investigating whether we can avoid this notification by using the intent data of the broadcast receiver as a means to avoid creating the notification by calling getExposureInformation(). We will update here once we have more information.

**Comment by jakobmoellersap** [comment]
@MikeJayDee We are in contact with Google regarding these notifications as well and will update accordingly if we have any news regarding any possible behaviour change.

**Comment by MichaelPFrey** [comment]
for cross reference here the lnik to FAQ entry incl. pull request where the entry was added:

https://www.coronawarn.app/de/faq/#notif_weekly_update

https://github.com/corona-warn-app/cwa-website/pull/135

https://github.com/corona-warn-app/cwa-website/blob/00aa0b8e0662ff50be2be60e6a85ff081c9d76fd/src/data/faq.json#L142-L147
https://github.com/corona-warn-app/cwa-website/blob/00aa0b8e0662ff50be2be60e6a85ff081c9d76fd/src/data/faq_de.json#L142-L147

**Comment by nhnb** [comment]
I did not get the message today. Perhaps Google already removed it?

**Comment by pflammertsma** [comment]
The notification has been removed from Google Play Services. In coming weeks, a different, more generic notification will appear with words to the effect that exposure notifications are enabled for a specific app.

The purpose of the new notification is to reassure users that the system is working, while avoiding any specifics regarding risk assessment or matches.

**Comment by TuringTux** [comment]
The "weekly update" notification's wording seems to have changed by now. 

Still, it was quite scary for me to see the red virus icon in my notification bar for the first time (even though the message provided instantaneous relief). Furthermore, a lot of the warning effect is lost on me now because the next time I'll see the icon, I'll probably assume that it will just be another "everything's okay" message and not actively look at what the text is saying.

Would it be possible for you to ask Google to change the virus icon's color to green, or something neutral, or change the icon altogether?

I believe this would be a considerable UX improvement.

Thanks in advance for your time :smiley:
