### ISSUE TITLE
Example: Huawei Custom Rom Patch 10.0.0.197(C431E8R2P7patch02)

### ISSUE THREAD

**Issue by speedy-1702** [corona-warn-app/cwa-app-android#736]
## Your Question

* Source File:
* Line(s):
* Question:
Huawei is advertising a new Patch MAR-L21 10.0.0.197(C431E8R2P7patch02). Within their advertising they state improvements reagarding 3rd-party applications concerning COVID-19 functionalities. The changelog is not describing precisely what they have improved. I assume, there are other manufacturers doing similar.

```
Changelog:
[Liste der Änderungen]
Dieses Update verbessert die Systemkompatibilität mit bestimmten Drittanbieter-Apps.

```
My questions:
- Since I have learned, that cwa is utilizing functionalities of "Google Play Services", then why do the manufacturers need to improve their custom ROM?
- is the patch mandatory for a operational cwa? 
- is there a good overview description ("big picture") of the interaction of OS, Google Play Services and CWA? The pictures, that I have found in the [documentation](https://github.com/corona-warn-app/cwa-documentation), are much too technical for the non-professionals.
- is the cwa core-team in contact with the manufacturers and know about their activities?

**Comment by MichaelPFrey** [comment]
>  Huawei is advertising a new Patch MAR-L21 10.0.0.197(C431E8R2P7patch02). 
>  Within their advertising they state improvements reagarding 3rd-party applications concerning COVID-19 functionalities.

Could you link to the change log (or make a screenshot from the update process) that specifically mentioned **COVID-19**, **Exposure Notifications API**, **BLE** or "anything" specifically related?

I am unable to find an official change-log. (please check the About Page - some URLs may sound official, but the About Page may clarify that it is just an independent news page)

The unofficial change-log that I found with a quick google search  mentioned something like

> This update improves system compatibility with certain third-party apps.

or

> Dieses Update verbessert die Systemkompatibilität mit bestimmten Drittanbieter-Apps.

_compatibility_ and _certain third-party apps_ can mean anything (or nothing) and speculating on unspecific unofficial change-logs is just speculation.

If you have question about a specific phone, you should ask the manufacturer about changes and recommendation etc.

**Comment by speedy-1702** [comment]
Thank you @MichaelPFrey for your contribution. Unfortunately I didn't made a screenshot for the advertisement.

At least 2 of my 4 questions are not specific for a particular manufacturer

- is there a good overview description ("big picture") of the interaction of OS, Google Play Services and CWA? The pictures, that I have found in the documentation, are much too technical for the non-professionals.

- is the cwa core-team in contact with the manufacturers and know about their activities?

Answers would be appreciated

**Comment by tkowark** [comment]
Thanks for your questions. As we also cannot see the patch notes, we unfortunately cannot comment, as well (and thus also have to close the issue).

Regarding the other questions:

* The picture in https://github.com/corona-warn-app/cwa-documentation/blob/master/solution_architecture.md#introduction is as much of a high level picture as we currently have. In short, CWA just calls functions of the exposure notification framework, which is part of the Google Play Services. How that framework implements the functions (e.g., how it makes sure that beacons are sent and received) by interacting with the OS, is beyond the control of CWA
* Therefore, there is also not much benefit of us being in constant exchange with device vendors, as all their changes affect functionality which we do not implement.
