### ISSUE TITLE
Android: Trouble to BT Connect with Ford Sync3 after installing APP

### ISSUE THREAD

**Issue by derbazi2020** [corona-warn-app/cwa-app-android#740]
Hi,

usually connects my Smartphone (Moto G5plus) with Android 8 automatically to my car (Ford Focus MK4) entertainment via BT.

After installing the APP I have to connect manually (?). After manual Connect the connection works.

APP 1.0.4

best regards, Martin

**Comment by tkowark** [comment]
Unfortunately, we cannot influence how bluetooth connectivity on certain devices is influenced by the Exposure Notification Framework. As described in the [FAQ](https://www.coronawarn.app/de/faq/#various_device_problems), we need to refer you to your mobile phone vendor for that matter.
