### ISSUE TITLE
Please add a button to show all stored data

### ISSUE THREAD

**Issue by flowl** [corona-warn-app/cwa-app-android#742]
Please add a button to view all generated ids, ids contacted and cwa server URL.

In its current state, users don't see anything.
Like a car where you can't open the engine cover.

**Comment by kiranbayram** [comment]
It would be nice to see total count of contacts (all time, last two weeks, last day etc.)

**Comment by daimpi** [comment]
Similar to https://github.com/corona-warn-app/cwa-wishlist/issues/5

Afaik the CWA doesn't have access to most of the data you want to see. It's mostly handled by the Google/Apple ENF and not exposed: https://github.com/corona-warn-app/cwa-app-ios/issues/678#issuecomment-647116562

**Comment by flowl** [comment]
> Similar to [corona-warn-app/cwa-wishlist#5](https://github.com/corona-warn-app/cwa-wishlist/issues/5)

That covers my concern, thanks!
