### ISSUE TITLE
Remove the need for Google Play Store and other Google services

### ISSUE THREAD

**Issue by probonopd** [corona-warn-app/cwa-app-android#743]
## Avoid duplicates
* [ ] This enhancement request has not already been raised before
* [X] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

The app prides itself in being respectful of data privacy.

Yet it forces users to use the Google Play Store and other Google services.

This is a stark contradiction, as Google is known to collect personally identifiable information about its users.

__As it stands now, users' data may not be collected centrally by government, but government is forcing users into a system where a private U.S. company is collecting user's data.__

## Suggested Enhancement

1. Provide the apk for download directly (and, optionally, also via https://f-droid.org/) without the need for Google Play. This should be very easy to do.
2. Remove any dependencies on proprietary Google services that require users to disclose any information to Google

## Expected Benefits

Live up to the standards that are claimed by the government regarding caring for users' data privacy.

**Comment by probonopd** [comment]
Please do not close this without any _meaningful discussion_, including thinking about _what would need to be done_ to get rid of all Google services.

**Comment by SebastianWolf-SAP** [comment]
Dear @probonopd,

please have a look at the already existing issues:
- https://github.com/corona-warn-app/cwa-wishlist/issues/57 addresses suggested enhancement 1
- https://github.com/corona-warn-app/cwa-app-android/issues/75 focuses on suggested enhancement 2

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
