### ISSUE TITLE
Ursache 9002 / Error 9002

### ISSUE THREAD

**Issue by tegutistgut** [corona-warn-app/cwa-app-android#746]
## Describe the bug
Ich habe die App ganz normal geöffnet

## Expected behaviour
Die App sollte sich ohne Fehlermeldung öffnen

## Steps to reproduce the issue
Einfach die App (GPS, Bluetooth an oder aus ist egal) öffnen, und die Fehlermeldung kommt.

## Technical details

- Mobile device: Samsung Galaxy A51
- Android version: Android 10, OneUI 2.1, Kein root, April 2020 Sicherheitspatch,

## Possible Fix
Keine Ahnung

## Additional context
Hier ein paar Bilder: (bei der GitHub app kann man keine Bilder hinzufügen)
https://ibb.co/rHmKKhN
https://ibb.co/Msx116Y

**Comment by jakobmoellersap** [comment]
Thanks for your issue. Can you try to click the error away, enable the Exposure Notification Framework and see if that solves the Problem?

**Comment by tegutistgut** [comment]
Danach kam die Fehlermeldung nicht mehr wieder. 

Das habe ich eigentlich schon vorher gemacht, als dieselbe Fehlermeldung kam, aber es ging nicht weg. Jetzt geht es irgendwie.

Danke

**Comment by jakobmoellersap** [comment]
Closed as the issue does not seem to be reproducible. Please open a ticket again if the error persists and can be deduced from a pattern.
