### ISSUE TITLE
App shows as "inactive" even though Bluetooth and GPS are on

### ISSUE THREAD

**Issue by 8192K** [corona-warn-app/cwa-app-android#751]
## Describe the bug

This is how I use the app: I switch off Bluetooth and GPS when I'm home and switch both back on when leaving the house (at night I am in flight mode). When either of the two are switched off, I get a notification to switch it back on. Those notifications disappear when I switch them back on. I do not open the app in between.

So I had been doing this for 3 days (last time I opened the app was June 20th), next time I opened the app was June 23rd. I was applying the pattern I described above during the 3 days in between. When I then opened the app on June 23rd, it showed as "exposure tracking not possible" (the grey field), even though everything was on. It did not help to switch Bluetooth or GPS off and on again while in the app. The only thing that helped was switching "activate exposure tracking" off and on again (it was set to "on" all the time!). Then the main field became green again and the app seemed to work just fine. I suspect the app to not have worked for those 3 days.

So from now on I kept opening the app everytime I switched Bluetooth and GPS back on (when leaving the house). The main field then stayed grey for a few seconds before turning green by itself or showed as green right away.

## Expected behaviour

The app works as expected without opening the app itself after switching on Bluetooth and GPS.

## Steps to reproduce the issue

Probably as described above (keep app closed for a couple of days while switching BT and GPS off and on). Haven't tried that though.

## Technical details

- Mobile device: Sony Xperia XA2 (H3113)
- Android version: Android 9

## Possible Fix

See in description

---
Internal Tracking ID: EXPOSUREAPP-1940

**Comment by jonathanschad** [comment]
I'm running in a similar issue. I'm also greeted with the same message: "Exposure Logging is not possible". If I click on Activate Exposure Logging, I'm told that my exposure tracking is already active. If I try to disable the logging and then enable it again the message still appears. My message doesn't turn green again!

In addition there is no further error message displayed that might indicated what causes the issue.

In contrary to @8192K I have my Bluetooth and location service active all the time. If I try to toggle either of the two I'm receiving a notification that may exposure notification are off. This seems to be working as intended.

## Technical Details

Mobile device: Xaiomi Mi 9t
Android version: Android 10

**Comment by jakobmoellersap** [comment]
@jonathanschad Since when do you have CWA installed?

**Comment by jakobmoellersap** [comment]
@8192K could you try to reproduce the issue and see whether waiting a few seconds in the main screen makes the card turn green?

**Comment by 8192K** [comment]
@jakobmoellersap  I did that when I first encountered the issue (where I could only fix it by turning the exposure logging off and on again). I did wait a long time waiting for the green screen, but it just dodn't come.
I can try to reproduce which would mean keeping the app closed and potentially left in a faulty state for three days. I'll give it a try.

I installed the app right on the day it was published.

**Comment by jonathanschad** [comment]
@jakobmoellersap I've installed the App a few hours after release. The first few days I encountered no Problems at all. Then about a week ago I've noticed the described issue. A few hours after this I restarted my phone and the app seemed to work again for some time (I saw the green message again). I dont know exactly when it went back to the error message, might be a matter of hours or days. Fast forward to yesterday and I noticed the bug again, searched for and  found this issue.

Yesterday I tried force stopping the app (but I was not restarting my phone) and nothing changed for the evening. This morning I checked again and suddenly I'm getting the green message again. 

I dont really know what to make out of this. I have no idea if the app worked the last week and if it was just a visual bug or something else.

**Comment by jakobmoellersap** [comment]
Thanks for your detailed description guys. We think this is also related to background job behavior. Please do not be worried for now as the key generation on your device is unaffected of this issue and we most likely deal with a simple hiccup on the key retrieval caused by killed background jobs or a failing web request. We are working on
- giving users better feedback on when data is being loaded into the App
- ensuring better and consistent background job behavior

Most likely our planned fixes will also solve your issue so I would, unfortunately, ask for some patience. In the meantime, just going into the App now and then to ensure Risk Status Updates should be a working workaround for you. If the card goes and stays green, everything is okay. If it is greyed out even after reinstating the App multiple times, please report back to us.

**Comment by Saiberman** [comment]
Same issue here. Even with GPS and Bluetooth on the whole time the I have to deactivate / activate tracking from time to time...

**Comment by GPclips** [comment]
Hello @8192K and @jonathanschad and community,

since it has been a while, I like to ask you if this error still occurs for you.

Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by svengabr** [comment]
Due to missing feedback, I assume the issue does no longer occurs. The Issue will be closed to keep the boards clean.

Best regards,
SG

Corona-Warn-App Open Source Team

**Comment by Saiberman** [comment]
Doesn't occur on my phone anymore.

Best regards
Bernd



________________________________

**Comment by 8192K** [comment]
Yes, sorry, it doesn't occur any more.
