### ISSUE TITLE
Add option to change language manually

### ISSUE THREAD

**Issue by davidhusz** [corona-warn-app/cwa-app-android#753]
My phone is set to English, and as a result the app is in English as well. I would appreciate an option to change the language of the app to German without changing the language of the operating system.

App version: 1.0.4
OS version: Android 9

**Comment by tkowark** [comment]
Thanks for the suggestion, @davidhusz . We are already tracking a similar proposal in corona-warn-app/cwa-wishlist#22 and will therefore close this issue here.
