### ISSUE TITLE
Number of exposure checks increases daily

### ISSUE THREAD

**Issue by AllesMeins** [corona-warn-app/cwa-app-android#769]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Describe the bug

According to the "Exposure check log" in android settings the number of checks performed increases daily. For June 24th there was one check at 9:19, June 25th there were two checks at 9:51, for June 26th there were three checks at 10:56 and today I'm at four checks at the same time... 

![Screenshot_20200627-130536_Google_Play_services](https://user-images.githubusercontent.com/2261844/85920867-be353b00-b877-11ea-95da-a20698fa1c84.png)

Every additional check gets a new hash - so the first check of the day always has the hash XXXXXX, the second check of the day always has the Hash YYYYYYY,...

## Expected behaviour

One check per day

## Steps to reproduce the issue

Open Android Settings
Go to Google
Select COVID-19 Notifications
Select Exposure checks

## Technical details

Sony Xperia XZ1 Compact
Android 9 (Lineage OS)

## Additional context

I've seen the same behavior on the screenshots posted at issue #744 but it wasn't discussed there as far as I know.

**Comment by jakobmoellersap** [comment]
This is not a bug but our current behavior. Currently, we do not use batching and thus call the function provideDiagnosisKeys up to 14 times (our retention period). This is subject to change however and we are working on optimizing this.

**Comment by jakobmoellersap** [comment]
Also, concretely this means your calls are working properly. That means the keys are on your device per day.
