### ISSUE TITLE
Split "submission" activity from main activity

### ISSUE THREAD

**Issue by uschindler** [corona-warn-app/cwa-app-android#77]
## Current Implementation
The current implementation has 2 activities:
- onboarding
- main activity

The onboarding activity is only shown on first start of the app. On the main class this state is checked and then either the main or the onboarding activity is started. This is perfectly good design, as the onboarding activity is mostly not used, so all fragments, images, text don't need to be loaded. 

## Suggested Enhancement
The submission of a positive COVID-19 case should be implemented as a separate activity. The transition to this should not be to hard. The fragments (in package "submission") should be removed from main activity and moved to a new activity.

## Expected Benefits
Like the onboarding, the submission code is not needed in 99% of all cases and should not be loaded when app starts. This is not necessarily an important thing with today's devices, but there are some other things to imagine:
- The submission of a positive COVID-19 result is a security/privacy sensitive task and involves scanning a QR-code or entering the teleTAN. The data involved by this should be protected. Therefore screenshots should be disabled (which also involves the preview image shown if you close app with home button - see issue #9). Pull request #41 tries to disallow screenshots by enabling/disabling them on enable/disable of the fragment. IMHO, a more clear approach would be to just disable screenshots for the submission activity. Screenshotting and app snapshot images should be allowed for all other parts (like main app showing actual status and onboarding). This seems very important to me. The enable/disable screenshotting is a setting for the activity's window and can't be enabled/disabled easily without hacks per fragment.
- The submission interface could be started without starting the app by directly triggering the activity by an URI handler: It may be possible to encode the QR code key as an URI (that's my other suggestion - should I open separate issue?). In that case users can just open the default mobile's camera app, scan the barcode and the camera app will trigger the URI encoded into it. The app can then provide an URI handler that automatically starts the submission activity in the CWA Android app. This is much more easier to understand to most people, because when they see a QR/barcode, they intuitively scan it with the camera app (recent phones have QR code reader embedded into camera app) or their favourite QR code scanning app.

Internal Tracking ID: EXPOSUREAPP-18

**Comment by uschindler** [comment]
I have not enough Android app coding experience (I am more the backend guy), so I leave an implementation of this open to others. Please see this as an suggestion, although it should be not hard to implement.
It is just something I figured out from reviewing the app's code.

**Comment by tobidwest** [comment]
## Your Question
* Source File: [CoronaWarnApplication.kt](https://github.com/corona-warn-app/cwa-app-android/blob/970e8b859cff3c8beeca83ac83e9ed534927107a/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/CoronaWarnApplication.kt)
* Line(s): 101 - 103
`activity.window.setFlags(
WindowManager.LayoutParams.FLAG_SECURE,
WindowManager.LayoutParams.FLAG_SECURE
)`
* Question:
Welchen Vorteil bietet es, Screenshots zu verhindern? Ist es nicht sehr wünschenswert, wenn die Nutzer*innen Screenshots in den sozialen Medien verbreiten und so andere zur Installation der App anregen?

**Comment by kolyaopahle** [comment]
#9 is the BSI's response to the screenshot functionality

**Comment by mtwalli** [comment]
Not planned
