### ISSUE TITLE
Fehler URSACHE: 9002 Etwas ist schief gelaufen. "The Exposure Notification Framework must be active, check your tracing status" when switching from other COVID-19 App

### ISSUE THREAD

**Issue by Drachenbauer** [corona-warn-app/cwa-app-android#770]
Hallo

Ich habe ein Samsung Galaxy A40 mit Android 10 und bekomme diesen Fehler:

> Fehler URSACHE: 9002
> Etwas ist schief gelaufen.
> 
> The Exposure Notification
> Franework must be active, check
> your tracing status
> 
>                          DETAILS      OKAY

Bei Details kommt dann noch das hier:

> Ursache:
> java.lang.IllegalStateExeption:
> The Exposure Notification
> Franework must be active, check
> your tracing status
> at
> de.rki.coronawarnapp.transaction
> .RetriveDiagnosisKeysTransacti
> on$executeSetup$2.invokrSuspe
> nd(RetriveDiagnosisKeysTransa
> ction.kt:11)
> at
> kotlin.coroutines.jvm.internal.Bas
> eContinuationImpl.resumeWith(C
> ontinuationImpl.kt:2)
> at
> kotlinx.coroutines.DispatchedTas
> k.run(DispatchedTask.kt:18)
> at
> kotlinx.coroutines.scheduling.Cor
> outineSheduler.runSafely(Corout
> ineSheduler.kt:1)
> at
> kotlinx.coroutines.scheduling.Cor
> outineSheduler$Worker.run(Coro
> utineSheduler.kt:15)
> 
>                                        OKAY

Der Fehler tritt immer auf, wenn ich die Risikoermittlung einschalten will und auch wenn ich das Gerät aus dem Standby zurückhole, wenn zuletzt diese App angezeigt war..

Wie überprüfe ich meinen Tracing-Status, um das zu aktivieren, was da steht?

Ich hab das jetzt bei Bugs reingepackt, weil mir auch sonst keine Kategorie hier passend erschien.

**Comment by jakobmoellersap** [comment]
Did you change the App from Immuni or deactivate the Tracing Framework by Google manually outside of the App?

**Comment by Bila66** [comment]
@jakobmoellersap : Same bug on my company phone (Huawei p20 lite).
Since installation I never switched the tracing manually to off, but it turned off itself, showing the bug as described by @Drachenbauer 
Please check if this might be related with crossing the border to another country > 24 h ago.
I am living at the border to Germany, sometimes I am in the German phone system, sometimes in the foreign.

**Comment by falkorichter** [comment]
<img width="567" alt="Screenshot 2020-06-29 at 09 57 09" src="https://user-images.githubusercontent.com/50506/85988987-273fbe80-b9f0-11ea-9e36-931a1980cd32.png">

This looks like an error but is a normal use case if you switch from other apps to the German app. Imagine you are commuting from Germany to Switzerland or Austria... 

Especially this:
<img width="567" alt="Screenshot 2020-06-29 at 10 07 52" src="https://user-images.githubusercontent.com/50506/85989135-6a019680-b9f0-11ea-9f57-7832871e1d5b.png">
scares the normal user unnecessarily.

**Comment by jakobmoellersap** [comment]
We agree that the behaviour should not be an error with Stack trace but instead, be handled like a normal use case. We are investigating and working on a solution

**Comment by goebelhanshermann** [comment]
Der Fehler ist bei meinem Handy auch vorhanden. Was muss ich tun damit die Corona Warn App wieder funktioniert?

**Comment by Drachenbauer** [comment]
I didn´t deactivate anythingon my phone...

**Comment by kirinawust** [comment]
Because of another Corona Warn-App error, I followed instructions to delete Google Play-Dienste cache and data. Now I have error 9002 and this is wirse, because it swirches off the tracing. What di I do now?
I have an LG5, Android 6.0.1

**Comment by SebastianWolf-SAP** [comment]
@kirinawust Do you have the latest version 1.1.1 of the app installed? If not, please perform an update via the Google Play Store. This should fix the issue.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by kirinawust** [comment]
Salut Sebastian,
nein, ich habe 1.0.5, aber der Google Play Store bietet kein Update an, sonder nur "öffnen".

Und nu?

----------------------------------------------------------------- 
K. Irina Wust
 Technische Redakteurin
 Hindenburgdamm 93e, 12203 Berlin
 phone: +49-(0)30 8963 7463,  kirinawust@web.de

**Comment by SebastianWolf-SAP** [comment]
Wenn es Probleme mit dem Play Store gibt, gibt es verschiedene Möglichkeiten. Der Artikel hier gibt einen schönen Überblick: https://www.nextpit.com/google-play-not-working Vielleicht gibt sich das Problem aber auch die nächsten Stunden automatisch. Die 1.1.1 ist auf jeden Fall freigegeben. 

Mit freundlichen Grüßen/Best regards,
SW
Corona Warn-App Open Source Team

**Comment by kirinawust** [comment]
Fein. Jetzt habe ich die 1.1.1 und der Fehler 9002 ist weg. Dafür ist der 39508 wieder da.

Was tun?

----------------------------------------------------------------- 
K. Irina Wust
 Technische Redakteurin
 Hindenburgdamm 93e, 12203 Berlin
 phone: +49-(0)30 8963 7463,  kirinawust@web.de

**Comment by Zaelnorth** [comment]
This isn't closer, I'm having the same issue on app 1.3.0 what should i do? I get the 9092 when I try to scan my testing QR code.

**Comment by svengabr** [comment]
@Zaelnorth could you maybe open a new issue with your error 9092 and provide some additional information? I will then forward this to the development team so it gets in the hand of the right people.

Thank you very much!

Best regards,
SG

Corona-Warn-App Open Source Team

**Comment by Zaelnorth** [comment]
I just created a new bug, all good. thanks for the prompt response.
