### ISSUE TITLE
Screen shots disabled by app policy

### ISSUE THREAD

**Issue by ascheman** [corona-warn-app/cwa-app-android#775]
Find everything else in #774

**Comment by tomjschwanke** [comment]
This is being discussed in #9

**Comment by PeterB2020** [comment]
This is not a bug.

**Comment by Morl99** [comment]
I think the purpose of this issue is, to allow sharing exceptions/errors with the developers/github. Maybe a better alternative would be to allow to directly create an issue on github with attached details, or to at least allow copying a stack trace in the shown error screen in #774.

**Comment by ascheman** [comment]
Yes, @Morl99 is right: please enable a good opportunity to create issues directly from the app if it fails. I do not know much about Android development but probably something like a general exception handler is possible? If it could start a dialogue with the user to create an issue and include the stack trace this could probably help.

**Comment by tkowark** [comment]
This issue is already discussed in #516 
As further noted [here](https://github.com/corona-warn-app/cwa-app-android/pull/619#issuecomment-645920236), the dev team is currently discussing the way forward with the screenshot protection. Updates on that matter will be provided in #516.
