### ISSUE TITLE
[Kleiner Schönheitsfehler]: CWA zeigt zunächst „Unbekanntes Risiko“ um danach „Niedriges Risiko“ anzuzeigen…

### ISSUE THREAD

**Issue by Jo-Achim** [corona-warn-app/cwa-app-android#777]
{„Android one - Nokia 7.1“, Android 10 mit Sicherheitspatch vom 01. Mai 2020, CWA 1.0.4}

Hallo, 

seit dem 16.06. läuft die CWA und zeigte zunächst ausschließlich „Niedriges Risiko“. Am Morgen des 24.06. war im Infobereich des Startscreens ein Virus-Symbol zu sehen und das nachfolgende Öffnen der CWA zeigte „Unbekanntes Risiko“. Nach Schließen und erneutem Öffnen der CWA wechselte die Anzeige wieder auf „Niedriges Risiko“. 

Seitdem wird beim Öffnen der CWA regelmäßig für knapp eine Sekunde zunächst „Unbekanntes Risiko“ angezeigt um danach automatisch auf „Niedriges Risiko“ zu wechseln. 
Das könnte unbedarfte Nutzer irritieren. Es wäre also wünschenswert gleich das korrekte Risiko (hier: „Niedriges Risiko“) anzuzeigen.

Mit freundlichen Grüßen, Joachim.

-----------------------------------

[Small blemish]: CWA first shows "Unknown risk" and then shows "Low risk" ...
{"Android one - Nokia 7.1", Android 10 with security patch from May 1st, 2020, CWA 1.0.4}

Hello,

since June 16 runs the CWA and initially only showed "Low Risk". On the morning of June 24th there was a virus symbol in the information area of the start screen and the subsequent opening of the CWA showed "Unknown Risk". After closing and reopening the CWA, the display changed back to "Low Risk".

Since then, when you open the CWA, “Unknown Risk” is displayed regularly for just under a second, after which it automatically switches to “Low Risk”.
This could irritate inexperienced users. It would therefore be desirable to immediately display the correct risk (here: "Low Risk").

Sincerely, Joachim.

---
Internal Tracking ID: EXPOSUREAPP-1938

**Comment by tkowark** [comment]
Just to clarify, did the virus symbol show up in the Corona-Warn-App or just on your phone's home screen as a push notification?

**Comment by Jo-Achim** [comment]
Das Virus-Symbol wurde auf dem Home-Screen in der Benachrichtigungszeile (oben links) angezeigt.
(Weitere CWA-Infos wurden nach dem Herunterwischen in der üblichen Weise angezeigt.)

-----------------

The virus symbol was displayed on the home screen in the notification line (top left).
(Additional CWA informations was displayed in the usual way after wiping down.)

**Comment by Jo-Achim** [comment]
Eine, vielleicht wichtige, Besonderheit habe ich vergessen: Mein Smartphone darf nur per WLAN ins Internet.

---------------

I forgot one, perhaps important, special feature: my smartphone can only access the Internet via WLAN.

**Comment by jakobmoellersap** [comment]
We are currently in process of analyzing how we best show the querying of data. Your status is a result of us still evaluating your risk level and thus it did not update right away after a day. Sometimes this takes a while and thus you see this screen. We will update here once we have the proper solution defined and in a PR

**Comment by arnowelzel** [comment]
I can confirm, that when starting the app, the initial view says that "Risk Unknown" and after about 1-2 seconds it will change to the actual risk level, which is irritating.

It would be better, if the initial view would display a message like "please wait" until the app knows what to display.

**Comment by Jo-Achim** [comment]
Genau, das wäre eine Idee.

------------------

Exactly, that would be an idea.

**Comment by MichaelPFrey** [comment]
> On the morning of June 24th there was a virus symbol in the information area of the start screen

Did look like the screenshots in #734 ? If so, that part issue is traced separately in #734 and this issue could focus on the other aspect(s):

> Since then, when you open the CWA, “Unknown Risk” is displayed regularly for just under a second, after which it automatically switches to “Low Risk”.
> This could irritate inexperienced users. It would therefore be desirable to immediately display the correct risk (here: "Low Risk").

Which not only irritating, it can also desensitize as people get used to that behavior.

**Comment by jakobmoellersap** [comment]
Hey everyone, sorry for us being silent on this for a while. We are working on a loading indicator that indicates the fetching of data in case we need to fetch additional key packages before showing a risk state on the app startup. This is the first step that (together with optimised background behavior) should solve or at least mitigate most of the issues and display behaviors that are occurring in 1.0.4

**Comment by Jo-Achim** [comment]
> Did look like the screenshots in #734 ? 

Ich meine mich zu erinnern, dass diese Anzeige bereits „Unbekanntes Risiko“ beinhaltete.
I think I remembered that this screen already included "Unknown Risk".


@jakobmoellersap 
Danke für die Info.
Thanks for informaton.

**Comment by daimpi** [comment]
@Jo-Achim does this problem still exist, or has this been solved in the meantime?

Is this issue related to- or superseded by https://github.com/corona-warn-app/cwa-app-android/issues/1081?

**Comment by Jo-Achim** [comment]
Sorry, I've lost sight of the little thing. But I will look into the matter again with the next notification. 
Regarding https://github.com/corona-warn-app/cwa-app-android/issues/1081#issuecomment-713344103; see my post today.

(The problem may be related to https://github.com/corona-warn-app/cwa-app-android/issues/998#issuecomment-677286822 !?)

**Comment by daimpi** [comment]
@Jo-Achim 
> (The problem may be related to [#998 (comment)](https://github.com/corona-warn-app/cwa-app-android/issues/998#issuecomment-677286822) !?)

Good question 🤔. I guess we shouldn't exclude the possibility but tbh I'm not familiar enough with all the factors surrounding this issue to make any confident guess there currently.

**Comment by dsarkar** [comment]
@Jo-Achim, is this still an issue? Thanks for feedback.

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by Jo-Achim** [comment]
@dsarkar, thank you for your demand.
I guess it's not an issue anymore. At least I didn't notice it anymore.

Best regards.

**Comment by dsarkar** [comment]
@Jo-Achim, 

Thanks for the feedback. I will forward info to the developers and close this issue. Thanks again for contributing. 

Best wishes,
DS

---
Corona-Warn-App Open Source Team
