### ISSUE TITLE
Fehler bei Kommunikation mit Google API(10)

### ISSUE THREAD

**Issue by buergerapp** [corona-warn-app/cwa-app-android#781]
* 
![IMG_20200628_175547](https://user-images.githubusercontent.com/67011857/85955628-371fba00-b980-11ea-8db8-28ff41a2f0ed.jpg)
![IMG_20200628_175542](https://user-images.githubusercontent.com/67011857/85955629-3850e700-b980-11ea-9480-a97335981acb.jpg)
![IMG_20200628_175536](https://user-images.githubusercontent.com/67011857/85955630-39821400-b980-11ea-9128-87a3ae576cc1.jpg)

## Describe the bug
See attached screenshots

## Steps to reproduce the issue
Not possible

## Technical details

- Mobile device: huawei mate 10 pro
- Android version: 9

**Comment by tkowark** [comment]
Thanks for reporting. The team is already tracking that bug in #737
