### ISSUE TITLE
Corona-Warn-App Spanish translation

### ISSUE THREAD

**Issue by adrianapintod** [corona-warn-app/cwa-app-android#784]
## Avoid duplicates
* [x] This enhancement request has not already been raised before
* [ ] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

No Spanish language support.

## Suggested Enhancement

Translate the Corona-Warn-App into Spanish language.

## Expected Benefits

Spanish community will be able to leverage the application enabling the app to reach a bigger audience in Germany.

**Comment by adrianapintod** [comment]
I'm already working on this translation. I would like to later send the PR with the issue resolution.

**Comment by tkowark** [comment]
Dear @adrianapintod , thank you for your offer. As noted in corona-warn-app/cwa-documentation#350 translations are done by a dedicated team in close collaboration with the RKI. Hence, we cannot accept community translations at this point.

**Comment by zyth0s** [comment]
Inadvertedly, I started the translation before being aware of this. Anyhow, if it is of any interest I share a link to [my efforts](https://github.com/zyth0s/cwa-app-android).
