### ISSUE TITLE
Could someone do a branch without the National location restrictions?

### ISSUE THREAD

**Issue by VWFeature** [corona-warn-app/cwa-app-android#786]
If I understand correctly, under the Apache 2.0 license, people can create derivative works. While the logo and name are trademarked to the RKI, would someone please fork this project and create a version that is NOT restricted as to country?  
(This is way beyond my abilities!)

Thanks!!

**Comment by treysis** [comment]
That is difficult. To test the app, you need to be a whitelisted developer. Otherwise your app won't be able to use the Contact-Tracing-API. Furthermore, Google restricts the API to one app per country. Thus, an international version would never work without the support by Google. Furthermore, you'd need to get all the labs and local health administrations on board to implement the issuance of TAN codes in case of positive test results.

**Comment by VWFeature** [comment]
https://www.businessinsider.com/apple-google-coronavirus-contact-tracing-tech-states-dont-plan-using-2020-6



Apple and Google's ambitious COVID-19 contact-tracing tech can help contain
the pandemic if used widely. But so far only 3 states have agreed — and
none has started to use it
Aaron Holmes <https://www.businessinsider.com/author/aaron-holmes> and Hugh
Langley <https://www.businessinsider.com/author/hugh-langley>
Jun 10, 2020, 11:30 AM
In May, Apple and Google released their ambitious COVID-19 contact-tracing
technology, which lets government health agencies build smartphone apps to
track the spread of the virus.
<https://www.businessinsider.com/apple-google-coronavirus-contact-tracing-tech-states-dont-plan-using-2020-6>

   - But public-health agencies in the US have been reluctant to adopt the
   technology.
   - Business Insider contacted officials in all 50 states and Washington,
   DC; only three states confirmed plans to use the technology from Apple and
   Google. Meanwhile, 17 states ruled out the possibility of building
   contact-tracing apps entirely.
   - The slow uptake casts doubt on the viability of containing the
   coronavirus with contact-tracing apps, which require the majority of people
   to participate in order to function.

**Comment by treysis** [comment]
If some states don't want to use it, there's not much to do about it. The contact tracing system doesn't work without involving the local health authorities, as you need some official entity to 1. publish the app, and 2. provide infrastructure for checking positive test results.

Or what is the purpose of posting this article without any further comment?

**Comment by akuckartz** [comment]
@treysis It is worth noting exactly which health authorities and which politicians are opposed to using such Apps to fight the virus.

**Comment by tkowark** [comment]
Thanks @treysis for mentioning some of the limitations that make this rather hard. To add to that, of course, terms of use, data privacy notice, imprint, and hotline contacts would also have to be altered and provided anew by a forked application.

By that, the initial question is mostly answered: yes, this can be done, but there are at least the above mentioned ToDos.

Further political discussions about where and why apps like CWA are not being used should further be taken outside the Github repositories of the CWA apps, where we want to focus on technical aspects of the development.
