### ISSUE TITLE
Accu drains faster by factor 2 since installation and enabling bluetooth for the app

### ISSUE THREAD

**Issue by nudgegoonies** [corona-warn-app/cwa-app-android#789]
* [/] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [/] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [/] Bug is not already reported in another issue

## Describe the bug

Accu drains faster by factor 2 since installation and enabling bluetooth for the app. Google Play Services is now the the application with the highest accu usage with 15%.

## Expected behaviour

Enabling bluetooth and installing the app should not take that much power. More than factor 2 is not tolerable.

## Steps to reproduce the issue

1. Enable Bluetooth
2. Install the app

## Technical details

- Mobile device: Motorola Moto G (falcon)
- Android version: 7.1 (LineageOS 14.1 with Open GApps)

## Possible Fix

Maybe this is an upstream Google Bug because it is Google Play Services?

## Additional context

---
Internal Tracking ID: EXPOSUREAPP-1903

**Comment by doak** [comment]
@nudgegoonies, sorry for the late reply.
Did you try to always switch WiFi off as soon as you leave home (i.e. as soon the device can't connect to an access point)?

I don't have that issue with my day to day Android device, which is the reason I initially ruled that variant out. But this is the only (obvious) thing left, which match both of our cases.
Btw., bluetooth is always switched on on my device without any noticeable impact on battery life.

**Comment by mtb77** [comment]
@nudgegoonies may you have any additional tracing details? Which version of GPS is installed? 

Thanks,

Sascha

Corona-Warn-App Open Source Team

**Comment by mtb77** [comment]
We updated the FAQ accordingly: https://www.coronawarn.app/de/faq/#battery

**Comment by nudgegoonies** [comment]
Thank you for the update. GPS is deactivated except for the Osmand Navi. I am able to root and flash but i am not firm with Debug Modes and Tracing.

**Comment by doak** [comment]
@nudgegoonies, you didn't try to turn off wifi while out of home, did you? In my case I see the postive effect cleary looking at the battery graph of Android after half an hour.
If it is the same for you this would not solve the issue, of course, but could lead the developers in the right direction.
