### ISSUE TITLE
App shows "Risikobegegnung", but no push/change in risk state

### ISSUE THREAD

**Issue by MartinUnt** [corona-warn-app/cwa-app-android#790]
I checked the app manually today and noticed a Risikobegegnung has been logged. I didn't receive any push message and the risk is not enhanced. What's the point of showing Risikobegegnungen to the user then? Is this intented behaviour?

![risk1](https://user-images.githubusercontent.com/44837036/86125255-a0b4db00-badc-11ea-9877-6327a493404a.png)

**Comment by tkowark** [comment]
We are currently preparing further examples about how the risk level is calculated and how even though there are Risikobegegnungen, the Card stays green: corona-warn-app/cwa-documentation#338. 

You can also find explanations of the behavior here: corona-warn-app/cwa-documentation#344
