### ISSUE TITLE
Caching fünf Minuten oder drei Minuten? 

### ISSUE THREAD

**Issue by DestructionOfPlanetJupiter** [corona-warn-app/cwa-app-android#80]
https://github.com/corona-warn-app/cwa-app-android/blob/90c49ae4ee75659cc96b603d0e0440e0dc0edcd3/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/request/ApplicationConfigurationRequest.kt#L27
`private const val SOFT_TTL = 5 * 60 * 1000 // in 3 minutes cache will be hit, but also refreshed on background`

**Comment by jakobmoellersap** [comment]
Thanks for pointing it out, I will fix this in a coming PR!
