### ISSUE TITLE
Counting the days seems not to be OK

### ISSUE THREAD

**Issue by tomtaa** [corona-warn-app/cwa-app-android#806]
Iphone App

After "12 von 14 Tagen aktiv"
begins a new count with "3 von 14 Tagen aktiv"
Will now only the contacts from the last 3 days compared or for all of the 14 days?

**Comment by pwoessner** [comment]
As this was raised for the iPhone app please create this issue in the iOS repository https://github.com/corona-warn-app/cwa-app-ios/issues

But in general: The number of days shown on the UI is no indicator which days will actually be compared to determine your risk. This is only an indicator which lets the user know how many hours the app recognised that tracing was active.
