### ISSUE TITLE
URSACHE: 9002 Timed out waiting for 60000 ms

### ISSUE THREAD

**Issue by aurisnoctis** [corona-warn-app/cwa-app-android#809]
## Describe the bug

Opening CWA today ( = day 17 after installation, CWA `firstInstallTime=2020-06-16 11:19:14`) I first had the `Google API(10)` error https://github.com/corona-warn-app/cwa-app-android/issues/737#issuecomment-652873704. Sending CWA to the background then opening again `Aktualisiert` changed from `Day before yesterday 11:34` (01 Jul) to `Today, 8:48`, which is good. After that the app seemed in a normal state (except that `days active` keeps hanging at `13 of 14 days` #796).

But then a new error appeared - not seen on this device before:
```
URSACHE: 9002
Timed out waiting for 60000 ms
```

## Expected behaviour

No error appears when opening the app.

## Steps to reproduce the issue

1. Install CWA on `firstInstallTime=2020-06-16 11:19:14`
2. Update CWA to 1.0.4 on `lastUpdateTime=2020-06-22 13:45:53`
3. Use it and encounter Google API errors since 25 Jun 2020, see https://github.com/corona-warn-app/cwa-app-android/issues/788#issue-648032737 and https://github.com/corona-warn-app/cwa-app-android/issues/788#issuecomment-652461851 plus follow-up comments below for a sequence of errors appearing; see also https://github.com/corona-warn-app/cwa-app-android/issues/737#issuecomment-649702108 and other comments by me there
4. Have `days active` not updated since 01 Jul 2020 https://github.com/corona-warn-app/cwa-app-android/issues/796#issuecomment-652502040 and following comments
5. Have `Aktualisiert:` not updated for the first and only time on 02 Jul 2020, when `Google API(20)` error appeared for the second time https://github.com/corona-warn-app/cwa-app-android/issues/788#issuecomment-652871916
6. Open app first time for today (03 Jul 2020)
  * `Google API(10) error` appears as described above, dismissed by user with `Okay`
  * Main screen of app is visible for some time (the error to come suggests 1 minute)
  * A new error appears for the first time: `Timed out waiting for 60000 ms`; some time (1 minute?) after it is overlaid by another error of the same type, see pics below

| | | |
|:-------------------:|:---------------------:|:---------------------:|
<img width="300" src="https://user-images.githubusercontent.com/8195964/86466232-90e30400-bd33-11ea-869a-80a647a60d81.jpg"> Error `Timed out waiting for 20000 ms"`; the new pop-up is overlaying the same error in the background, for which I had already opened the details | <img width=300 src="https://user-images.githubusercontent.com/8195964/86466238-92acc780-bd33-11ea-852a-5444c0e96c82.jpg"> Details part 1 | <img width=300 src="https://user-images.githubusercontent.com/8195964/86466249-950f2180-bd33-11ea-8adc-bc1a1615504c.jpg"> Details part 2

### Device
- App Version: 1.0.4
- Android Version: 6.0.1 (stock Android of device, not rooted)
- Device Model and Manufacturer: Samsung S5 (SM-G900F)
- Latest OS Update: can't determine date, Android menu says all available updates installed
  - Kernel: 3.4.0-14131106 from 06 Aug 2018
  - Build number: MMB29M.G900FXXU1CRH1
- Latest Update of CWA:  `lastUpdateTime=2020-06-22 13:45:53`, update to 1.0.4
- Installation Date of CWA:  `firstInstallTime=2020-06-16 11:19:14`
- Date/Time of the error: 03 Jul 2020, 08:48 local time in Germany
- Google Play Services version: 20.21.17 (040308-316502805)
- Google Mobile Services (GMS) version:
  - com.google.android.gms [202117018] [20.21.17 (040308-316502805)] [Container]
  - com.google.android.gms.nearby_en [v202304013]

**Comment by Petk12** [comment]
Hi,
this exception comes also with my ALE-L21 Android 6.0, but i do not know, how to reproduce.

Since I have version 1.05 I can exactly reproduce another similar exception:
java.net.SocketTimeoutException: timeout
at okio.SocketAsyncTimeAsyncTimout.newTimeoutException(JvmOkio kt:1)
...

To reproduce the issue, I have to kill all apps and to execute the Speicherbereiniger first.
After that I start the corona app which shows this exception after down/uploading some MBs of data
After a couple of seconds a follow up exception occurs:

Etwas ist schief gelaufen (something went wrong).
Ursache (Reason)
com.google.android.gms.common.api.ApiException:39508:
at android.support.v4.media.MediaDescriptionCompatApi21$Builder.setResultOrApiException(MediaDescriptionCompatApi21.java:3)
at com.google.android.gms.internal.nearby.zzae.onResult(com.google.android.gms:play-services-nearby@@18.0.2-eap:2)
....

**Comment by aurisnoctis** [comment]
Haven't encountered this error recently. It seems CWA version 1.1.1 either avoids the Google API errors or the notifications, so I close this issue.

The screenshots of #913 look different.
