### ISSUE TITLE
Code Coverage Badge & Changes

### ISSUE THREAD

**Issue by Jeehut** [corona-warn-app/cwa-app-android#81]
## Current Implementation

There's no code coverage badge for the main branch and also no way to see the difference on pull requests.

## Suggested Enhancement

Add a coverage badge to the README and setup a service to automatically post coverage changes to PRs.

## Expected Benefits

Long term improved code coverage and therefore also increased trust from our users (which is important for this app to become a success).

**Comment by Jeehut** [comment]
I could fix this myself if I had access to the [organization](https://github.com/orgs/corona-warn-app) (currently I can't add any GitHub Apps like Codacy, CodeCov or CodeClimate).

**Comment by jakobmoellersap** [comment]
we setup a sonar cloud connection and will continue with integrating coverage reports down the line.
