### ISSUE TITLE
Ursache 2: Nicht genug Speicherplatz

### ISSUE THREAD

**Issue by jan-wolter** [corona-warn-app/cwa-app-android#811]
The app was installed several days ago and worked fine.
A few days ago, every time I open it the following appears:

## Describe the bug
> ### URSACHE: 2
> ### Etwas ist schief gelaufen.
> Sie haben nicht genug Speicherplatz.
> 
> **Details:**
> Ursache:
> de.rki.coronawarnapp.exception.NotEnoughSpaceOnDiskException: the app detected that not enough storage space is available for the required operation at de.rki.coronawarnapp.util.CachedKeyFileHolder$asyncFetchFiles$2.invokeSespend(CachedKeyFileHolder.kt:90) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2) at kotlix.coroutines.DispatchedTask.run(DispatchedTask.kt:18) at kotlix.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1) at kotlix.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:15)

If I klick "okay" the notification disappears and the app seems to function properly. Risiko-Ermittlung is active.

## Steps to reproduce the issue
Everytime I open the app.

## Technical details
- Mobile device: Samsung G900F
- Android version: 9 (using Lineage OS 16)
- App version: 1.0.4

## Additional context
I have 594 MB of internal disk space available.

**Comment by christianneu** [comment]
As this might be a duplicate I would ask you to have a look here: #732
