### ISSUE TITLE
Any solution for GrapheneOS

### ISSUE THREAD

**Issue by tarek437248** [corona-warn-app/cwa-app-android#812]
## Avoid duplicates
* [ ] This enhancement request has not already been raised before
* [ ] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

**Comment by christianneu** [comment]
Closed as duplicate entry #813
