### ISSUE TITLE
Any solution for GrapheneOS? Ursache 3 Etwas ist schief gelaufen.

### ISSUE THREAD

**Issue by tarek437248** [corona-warn-app/cwa-app-android#813]
I have a GrapheneOS installed on my Pixel 3a. 
Well in GrapheneOS we don't really have anything to do with google services, including google Benachrichtigungen.
I really want to use the app. like all of us should use the app. But I don't want to go back to Android as I'm more than happy with GrapheneOS. I was just wounding if someone has any idea or solution on how to solve it?

**Comment by christianneu** [comment]
I would also close this issue as this topic is already mentioned here: #484 

There is also an FAQ entry available regarding the apk topic: https://www.coronawarn.app/en/faq/#apk
