### ISSUE TITLE
enIsEnabled = !asyncIsEnabled()

### ISSUE THREAD

**Issue by mh-** [corona-warn-app/cwa-app-android#814]
## Avoid duplicates
* [x] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Question is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Question has not already been asked in another issue

## Your Question

* Source File:
https://github.com/corona-warn-app/cwa-app-android/blob/18cc335780b08935527963e7baefac6cc6fa100b/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/TimeVariables.kt#L194
* Line(s): 194
* Question: Why "!"? Shouldn't this be `enIsEnabled = InternalExposureNotificationClient.asyncIsEnabled()` without the negation?

**Comment by ironjan** [comment]
I assume that the variable name is wrong based on the history. In [480488](https://github.com/corona-warn-app/cwa-app-android/blame/4804888ad0d3ee4c4abfb85294bab3006b75c250/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/TimeVariables.kt#L186) `(!InternalExposureNotificationClient.asyncIsEnabled())` is used, which was changed to `enIsEnabled = !InternalExposureNotificationClient.asyncIsEnabled() /* omitted */ if(enIsEnabled)` in #16 (see [git history](https://github.com/corona-warn-app/cwa-app-android/blame/18cc335780b08935527963e7baefac6cc6fa100b/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/TimeVariables.kt#L194)).

---

@SebastianWolf-SAP and @pwoessner  worked on this part of the code, so maybe they can give more information.

**Comment by mh-** [comment]
Somehow the linking of Issue and PR didn't work, so I just manually close this now.

**Comment by ironjan** [comment]
Good point about the linking. It should be explained better in the
corresponding files. I'll submit a corresponding PR later.

Just mentioning the issue number within the title does not link the PR to
the issue; the number has to be mentioned in the PR's description (or, if
that's possible, manually set).

**Comment by mh-** [comment]
>  the number has to be mentioned in the PR's description 

... and an additional comment (which I tried first) is not sufficient, but editing the PR's description would have done the trick.
