### ISSUE TITLE
Google APIException (39508) after using the SwissCovid App

### ISSUE THREAD

**Issue by lennard0711** [corona-warn-app/cwa-app-android#816]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue (kind of)

## Describe the bug

When you disable the SwissCosid App and try to use this one again you get an error saying: 
> CAUSE: 3
> Something went wrong.
>
> Error when communicating with Google API(39508)

## Expected behaviour

The app should function normally

## Steps to reproduce the issue

1. Download the SwissCovid App
2. Activate the SwissCovid App
3. Switch the active Corona App to the Swiss version
4. Deactivate the Swiss App
5. Open the CWA
6. Activate exposure logging
7. Switch the active App to the German one

## Technical details

- Mobile device: OnePlus 3
- Android version: LineageOS 10 / Android 10

## Additional context

A similar bug is documented here: #774 

---
Internal Tracking Id: EXPOSUREAPP-1854

**Comment by Th3Ph4nt0m** [comment]
Got the same problem, I changed nothing in my device settings or app pool.
Screenshot Ist attached.![IMG-20200708-WA0000.jpg](https://user-images.githubusercontent.com/44142235/86850518-b19fb680-c0b1-11ea-8df9-040010ebe47e.jpg)

**Comment by johannes** [comment]
Ich habe den selben Fehler, mit selber Exception, auch ohne eine andere App isntalliert zu haben. Bin seit Tag eins dabei. Fehler poppt jedes mal auf, wenn ich die App aufrufe. NAch einem "Force Stop" der App ist die Meldung weg. Android 10. Vor 6 Stunden habe ich die Google App aktualisiert auf 11.17.15.21.arm64.

**Comment by lennard7001** [comment]
@Th3Ph4nt0m @johannes Da ihr beide den Bug so habt, am besten in #774 melden

**Comment by treysis** [comment]
Liegt vermutlich an der Uhrzeit. Der Fehler tritt aktuell immer zwischen 0 und 2 Uhr auf.

**Comment by lennard7001** [comment]
Also bei mir ist es zu jeder Uhreit aufgetreten, das einzige was geholfen hat die deutsche App neu zu installieren @treysis

**Comment by w-flo** [comment]
The app should gracefully detect error 39508 and show a message like "temporary failure, please try again after 2am". Same for error 13 in the iOS app and other known errors, but it's especially important for these rate limiting errors. Often these errors occur because a user reinstalled the app after getting hit by some other issue, and then there's this other error, so many of them probably give up and uninstall.

**Comment by tkowark** [comment]
Agreed. We'll take that to the product management. Especially the point about not trying to reinstall the app is really paramount and should become much clearer also within the app.

**Comment by vaubaehn** [comment]
> 
> Agreed. We'll take that to the product management. Especially the point about not trying to reinstall the app is really paramount and should become much clearer also within the app.

Obviously there is already the plan to introduce a more user friendly error report according to google API errors, as a new error dialog combining API 10 and API 39508 errors was merged to the dev.

I made a suggestion to seprerate that single error message to 2 different messages, and now also added @tkowark idea to propose to the user not to uninstall or reinstall the app to keep the logged exposures.

As this is my first day on github, I did not know how to correctly make this contribution... Maybe someone can transform this https://github.com/corona-warn-app/cwa-app-android/pull/864#issuecomment-659356206 into a pull request?

**Comment by tkowark** [comment]
@vaubaehn thanks for your proposals. As written above, we have to run this by the product management, so please wait with a dedicated PR. But just to summarize the suggestions:

1. 39508 should ideally never be exposed to the user, but gracefully captured and a retry should happen at the next possible point in time
2. If 39508 has to be shown, your proposals from (https://github.com/corona-warn-app/cwa-app-android/pull/864#issuecomment-659356206) are great starting points, through we might have to shorten them a bit

**Comment by DooMMasteR** [comment]
Can confirm this issue. For me, since today, the app is not functional.

**Comment by svengabr** [comment]
@lennard0711 could you please update your CWA app to 1.5 and wait up to 24 hours after the installation was complete? The developers have fixed the problem.

**Comment by svengabr** [comment]
Since missing feedback, I will close this issue.
We created a new issue if the 39508 problem persitzt after updating to the latest version: https://github.com/corona-warn-app/cwa-app-android/issues/1459
