### ISSUE TITLE
App doesn't run because of Google Play version

### ISSUE THREAD

**Issue by thek71** [corona-warn-app/cwa-app-android#820]
## Describe the bug

I downloaded the app yesterday and when I tried to use it I got an error saying "Corona-Warn won't run unless you update Google Play", but Google Play is in the latest version, no possible update.

## Expected behaviour

The app should just start.

## Steps to reproduce the issue

No steps to reproduce. It just doesn't start. Maybe depends on the device/system

## Technical details

- Mobile device: Samsung Galaxy A3 2017
- Android version: 8.0
-Google Play version : 20.7.16-all [0] [PR] 31756459

**Comment by tkowark** [comment]
+1 via Email for Samsung Galaxy S9, Android 10. Google Play Version 20.7.16-all [0] [PR] 317546459

**Comment by pwoessner** [comment]
Hi @thek71 
Can you please check your Corona Warn App version in the device settings under  `Apps > Corona-Warn` ?

You currently need the version 1.0.4. If you have a version below please try to go manually into the Google Play Store, go to `My apps & games` in the side menu, check the `Updates` category and see if you have an update available for the CWA-App.

Thanks,
Philipp

**Comment by thek71** [comment]
> Hi @thek71
> Can you please check your Corona Warn App version in the device settings under `Apps > Corona-Warn` ?
> 
> You currently need the version 1.0.4. If you have a version below please try to go manually into the Google Play Store, go to `My apps & games` in the side menu, check the `Updates` category and see if you have an update available for the CWA-App.
> 
> Thanks,
> Philipp

Hi Philipp,

I just checked the app version and it's 1.0.4.

Thanks,
Katia

**Comment by ironjan** [comment]
@thek71 is the exact message "Update Google Play **services**. Corona-Warn won't run unless you update Google Play **Services**. Clicking on 'Activate Exposure Logging' has no effect."? (Bold text from me)

If so: this may be a duplicate of or closely related to #542 


----

Also, for your information: Google Play and Google Play Services are two different things, even if named very similar. "Google Play" (no services) is the app store used to install the app, while "Google Play Services" is a collection of multiple programming interfaces developed by Google.

**Comment by thek71** [comment]
> @thek71 is the exact message "Update Google Play **services**. Corona-Warn won't run unless you update Google Play **Services**. Clicking on 'Activate Exposure Logging' has no effect."? (Bold text from me)
> 
> If so: this may be a duplicate of or closely related to #542
> 
> Excerpt of the relevant information in #542: the problematic phone had access to Google Play Services `20.18.17` and showed above error. The error does not occur for Google Play Services `20.21.17`. #542 also mentions that Google Play Services updates are not always available for everyone immediately, e.g. `20.21.17` could already be available for my phone but not for yours.
> 
> Also, for your information: Google Play and Google Play Services are two different things, even if named very similar. "Google Play" (no services) is the app store used to install the app, while "Google Play Services" is a collection of multiple programming interfaces developed by Google.

@ironjan 
The exact message that I see is "Update Google Play services. Corona-Warn won't run unless you update Google Play" and then the app crashes. If there is something more in the error message I cannot see.
I have also installed Google Play Services because I thought exactly that, that the Services are also needed for the this app, but I got the exact same message even after that.

But now that by your suggestion I updated the Services to version 20.21.17 I get a different error. "Cause :3 Something went wrong". I know have to figure this out...

**Comment by ironjan** [comment]
Ok, we're moving on to the next related issues I guess ;)

The new problem seems to be related to #733 and https://github.com/corona-warn-app/cwa-app-android/issues/737#issuecomment-651970428 - according to the latter, the devs are working on a fix for the problem but they do not have an estimated time of arrival.

**Comment by thek71** [comment]
Thank you for the help.
I guess now I have to wait.

**Comment by pwoessner** [comment]
Hi @thek71 
Since you were able to update your Google Play Services version and start the app can we close this issue?
As mentioned by @ironjan the Error 3 of the Google API is covered in a separate issue.
Thanks,
Philipp

**Comment by thek71** [comment]
Hi Philipp,

yes of course you can close it.
Thank you all for the help.
