### ISSUE TITLE
App not actually submitting keys to the Exposure API

### ISSUE THREAD

**Issue by Spacefish** [corona-warn-app/cwa-app-android#821]
Hello, 

Google Play services offer functionality to show all exposure keys submitted by an App to the Exposure API. This export (attached to this ticket). Shows that for every submission to the API 0 keys where submitted.. Furthermore, the API seems to be called multiple times in a very short timeframe (same minute) without any keys being submitted..

There is not a single packet that contains at more than 0 keys according to the attached file (which was exported from Google Play Services).

Wonder if the app is even working :(

[data.json.zip](https://github.com/corona-warn-app/cwa-app-android/files/4875383/data.json.zip)

**Comment by Spacefish** [comment]
Probably duplicate of #744 I am running the latest Android 11 beta on my device (Google Pixel 2 XL) and have the latest play services.
I suspect that the app does not work at all if this "0" keys turns out to be true...

**Comment by jkrwdf** [comment]
Hi @Spacefish , did you consider https://github.com/corona-warn-app/cwa-app-android/issues/744#issuecomment-650532041 which can be seen as a kind of proof that the "0" in the "Anzahl der Schlüssel" is a copy/paste issue in the code which updates the database behind this UI?

**Comment by pwoessner** [comment]
Hi @Spacefish ,
this is a known issue which was also added to the faq: https://www.coronawarn.app/en/faq/#keys0
Br,
Philipp
