### ISSUE TITLE
need a crash/error report facility

### ISSUE THREAD

**Issue by teicher** [corona-warn-app/cwa-app-android#823]
The "Etwas ist schief gelaufen" dialog needs a "send error report" option.
As screenshots are disabled, the only was to report a detailed issue is the make a photo of the screen with another device. That is quite cumbersome.
Automated error reporting would allow you to collect and priorize real issues and real fails on real devices, and an idea how often it really occurs.
On Android, ACRA comes to mind.
A preview of the error report being sent would help to mitigate concerns about privacy.

Imagine the "report error" button here on the left side
![IMG_20200705_123302](https://user-images.githubusercontent.com/4208890/86544000-c9493480-bf23-11ea-946a-b643b3813948.jpg)

* [ y] This enhancement request has not already been raised before
* [ y] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

**Comment by styxxx** [comment]
Or at least: Make it possible to select and copy the error message. Why are screenshots disabled at all?

**Comment by rugk** [comment]
> Why are screenshots disabled at all?

That's a very good question. See https://github.com/corona-warn-app/cwa-app-android/issues/625 for details maybe.

So possibilities:
* I would decline automatic error reporting here, we are dealing with sensitive data and people could get crazy about this.
* However, manual error reporting via ACRA via mail is e.g. fine and would be transparent and privacy-preserving.
* Enable screenshots, yeah…
* Or, the best and IMHO, simplest method would be to allow me to copy that stacktrace to **the clipboard**.

**Comment by daimpi** [comment]
Related: 
- Allow screenshots on Android: #516
- Report Error Context if Exception Appear: https://github.com/corona-warn-app/cwa-wishlist/issues/17

**Comment by tkowark** [comment]
Since Screenshots will be re-enabled in an upcoming version (#745) and there is already a wishlist item (https://github.com/corona-warn-app/cwa-wishlist/issues/17), we'll close this issue.

**Comment by teicher** [comment]
Hmm, this is/was about integrating ACRA into the Android build for optional (user-triggered) crash/error reporting.
Not sure the wishlist entry, which is of rather general nature, will lead to this.

**Comment by tkowark** [comment]
As there currently is no development activity planned for such a feature, we have to go through the wishlist route. But since this issue is linked there, the conversation can always be followed back if an implementation decision is made.
