### ISSUE TITLE
active days stuck at 14 days

### ISSUE THREAD

**Issue by schindlboeckLi** [corona-warn-app/cwa-app-android#829]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Describe the bug

Installed app at Saturday the 4th of June. Now today on day 17 it still say 14 out of 14 days active.

## Expected behaviour

Counter starts at one again.

## Steps to reproduce the issue

Open app.

## Technical details

- Mobile device: Samsung Galaxy S8
- Android version: 2
- App version: 1.0.4

**Comment by tkowark** [comment]
https://www.coronawarn.app/de/faq/#days_active_explanation
