### ISSUE TITLE
The 14 out of 14 days active was misleading to user

### ISSUE THREAD

**Issue by devtechcorp** [corona-warn-app/cwa-app-android#832]
Hello,

many of my friends and family ask me about the 14 out of 14 days active that are displayed. Some expected that the counter would go further up or were unsure if the app is still working. This seems not the be a uncommon thing, as I ask a couple of users (  n > 50 )

## Avoid duplicates
* [ ] This enhancement request has not already been raised before
* [ ] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation
Shows 14 out of 14 days regardless how long the app been active.

## Suggested Enhancement
The app should make it more clear, that everything is working as expected. Also this countner needs a tab information field describing what the counter means. Maybe someone from the UX department could take another look.

## Expected Benefits

Less confusion about the status of the app. The UI must be understandable for everyone

**Comment by tkowark** [comment]
Please see https://github.com/corona-warn-app/cwa-wishlist/issues/102 for a related proposal.
