### ISSUE TITLE
Incorrectly showing "14 von 14 Tagen aktiv" though Bluetooth disabled

### ISSUE THREAD

**Issue by icrf2000** [corona-warn-app/cwa-app-android#840]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Describe the bug

I disabled Bluetooth on my device 6 days ago. The app still shows "14 von 14 Tagen aktiv". I think this is not correct? If I understand right, in the phrase "X von 14 Tagen aktiv", the "X" means on how many of the last 14 days exposures could be collected, means device switched on, Bluetooth on, no airplane mode etc. So in my case it should say "8 von 14 Tagen aktiv"?
## Expected behaviour
According to the [FAQ](https://www.coronawarn.app/en/faq/#days_active_explanation), the "active days" count should decrease when I disable Bluetooth. 

## Steps to reproduce the issue
* Disable Bluetooth and leave it disabled for a while (>> 1 day to avoid possible influence of numerical rounding)
* Observe what the app shows

## Technical details

- Mobile device: Galaxy S10
- Android version: 10

**Comment by jkrwdf** [comment]
The number of days shown in the CWA  is only calculated from what the app itself knows about its own state, represented by the On/Off switch therein. When you toogle this, the app notices, stores, integrates over 14 days, and emits the value from this. 

Any setting performed outside of the CWA which also disables the technical process of beacon sending and receiving, as there are:

- Disable Bluetooth
- Disable Location Data main switch
- Disable in Settings / Google / COVID-19

are not recognized by the app and hence not considered in the integration process. This is I heard technically not possible, all those settings cannot send an event to the app, and the Google framework itself does not offer a counter/timer which the app could read out. 

Together with the various bugs in the calculation of this number (13 of 14 for days, 15 of 14, there was a ticket with "-6 of 14") this led me to the suggestion to drop this visualization completely in https://github.com/corona-warn-app/cwa-wishlist/issues/102.

**Comment by pwoessner** [comment]
Hi @icrf2000 

the explanation by @jkrwdf is correct. 
Therefore we cannot improve the display and the counting of the active days and I have to close this issue now.

Thanks,
Philipp
