### ISSUE TITLE
CWA should control communication with backend

### ISSUE THREAD

**Issue by gitbrueck** [corona-warn-app/cwa-app-android#841]
## Avoid duplicates
* [+ ] This enhancement request has not already been raised before
* [+] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [ -] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

The communication with the backend is controlled by the Exposure Notifications Framework.

## Suggested Enhancement

CWA should be the master calling functions of EN or directly communicating with the backend.

## Expected Benefits

Fix of the problems loading keys.

**Comment by pwoessner** [comment]
Hi @gitbrueck 
Can you please specify what you mean with "communication with the backend is controlled by the Exposure Notifications Framework" and where do you see this happening (that the EN framework is taking responsibility of calling our backend)?
Thanks,
Philipp

**Comment by gitbrueck** [comment]
Hi Philipp,
sorry, it was just an idea.

If I would be whitelisted, I would step through the callback-function "onReceive" and check if there is something more then just storing data and setting a semaphore. There must be no calling of the framework and no communication with the backend.

Best Regards,
gitbrueck

**Comment by mh-** [comment]
> If I would be whitelisted

As you are not whitelisted, you might want to resort to this: https://github.com/kbobrowski/en-i13n
