### ISSUE TITLE
Cannot see BLE signal on other phone

### ISSUE THREAD

**Issue by sdschulze** [corona-warn-app/cwa-app-android#842]
I have installed the app on my (old) LG L70 (LG-D320), running LineageOS 14.1 (Android 7.1.2) with OpenGApps Pico.  Everything in the app seems fine, ("13 von 14 Tagen aktiv"), and in the settings, it says it checked 134 encounters during the past 14 days, so it appears to be receiving something.

On my other phone (Moto G5), I am running BLExplorer (from F-Droid). I do see a couple of other signals with the "fd6f" UUID at -80 dB or weaker, but even when I put both phones directly next to each other, nothing stronger appears.  When I check RaMBLE on the phone with the CWA, they see pretty much the same sources (except for the very weak ones), so BLExplorer seems to be working.

Even if the LG-D320 just does not support BLE, I think that silent failure should not be tolerated.  Out of personal interest::  As it appears that encounters were checked, does it mean that I will get notified in case any of them report a positive test, even though I did not send any BLE myself?

**Comment by jkrwdf** [comment]
You might look at #674 and #688 .

There are devices where the hardware does not support _sending_ out beacons, and actually neither the CWA nor the underlying framework report this fact. 

Regarding your second question: When you device is capable of _receiving_ beacons (which you might check with an app like [RaMBLE](https://play.google.com/store/apps/details?id=com.contextis.android.BLEScanner) against a sending device), then you will get warned.

**Comment by sdschulze** [comment]
Thanks, it says that peripherial mode is indeed not supported, so that seems to be the explanation.  Still, I think that the user should be informed about this, rather than letting things fail silently.

**Comment by tkowark** [comment]
Agreed that this should be made know. But we are Tracking this centrally in #688 and if we have a list or an approach to determine BLE PM availability, we make it know there.
