### ISSUE TITLE
Risiko-Ermittlung schaltet sich von alleine aus / Sie haben nicht genug Speicherplatz

### ISSUE THREAD

**Issue by ennyKey** [corona-warn-app/cwa-app-android#851]
Ich habe die App direkt am ersten Tag installiert und die Risikoermittlung aktiviert.
Die ersten 2 Wochen habe ich auch immer mal wieder rein geschaut und die App funktionierte.
Jetzt habe ich nach längerem die App mal wieder geöffnet und musste feststellen, dass die App die Risikoermittlung von sich aus selber ausgeschalten hat, ohne hierzu eine Meldung zu bringen.
Das sollte so nicht sein. Seit 30.06. wurde keine Risiko-Ermittlung mehr durchgeführt.
Eine Benachrichtigung hierfür wäre sinnvoll.

Versuche ich nun die Risiko-Ermittlung wieder zu aktivieren zeigt sich auch die vermutliche Ursache für die Deaktivierung.
Ich erhalte die Fehlermeldung "URSACHE: 2 Etwas ist schief gelaufen"
"Sie haben nicht genug Speicherplatz."

Die Frage ist nur: Wieviel Speicherplatz braucht die App denn? Ich habe über 600MB internen Speicher frei und über 100GB auf der externen SD-Karte. Das sollte doch locker reichen für die paar IDs die gespeichert werden.
Wie bekomme ich denn nun die Risiko-Ermittlung wieder eingeschaltet?

(Screenshots kann ich leider keine beifügen, da Screenshots in der App unterbunden sind).
App Version: 1.0.4

**Comment by chartm** [comment]
Bei mir tritt der gleiche Fehler auf, habe auch "nur" 500 MB freien internen Speicher. Leider finde ich auch keine Info wie viel Speicher die App tatsächlich benötigt und auch sonst gibt es keine Informationen zu diesem Fehler.

**Comment by daimpi** [comment]
Is it the same Error as in #732?

Afaiu a fix has been [merged](https://github.com/corona-warn-app/cwa-app-android/pull/760) into dev, but is not yet deployed (hopefully 1.0.6 will have it).

**Comment by chartm** [comment]
Bei mir ist es derselbe Fehler.  Ich denke nach 18 Tage sollte er auch in den FAQ zu der App stehen. Auch fehlt mir die Antwort: Wie viel Speicherplatz braucht die App?

**Comment by ennyKey** [comment]
@daimpi: Yes, you are right, its the same error.
I did not found it, because I searched for the error message in german language.
