### ISSUE TITLE
API error when (manually) updating risk status between midnight and ~3 am.

### ISSUE THREAD

**Issue by treysis** [corona-warn-app/cwa-app-android#855]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Describe the bug

When I open the app between roughly midnight and 3 am, risk status is shown as 'unknown' (grey). If I open 'risk status' it doesn't get updated, and when I return to the main menu the app throws an error. Risk status turns green, but with the last timestamp from successful risk status update. The app does start again afterwards, but with the same erroneous behavior. If I open the app after ~3 am, updating seems to work, risk status timestamp gets updated. Everything looks good. Error returns the next night.

## Expected behaviour

No error.

## Steps to reproduce the issue

Screenshots still disabled 😡!

## Technical details

- Mobile device: Samsung Galaxy NoteFE
- Android version: Android 9.0
- CWA version: 1.0.5

## Additional context

I don't know the exact time window. It always happened after midnight. Earliest successful return to normal functionality was at 3:02 am. I couldn't make a screenshot and didn't have the option to write down the error message yet, but I remember it was something about the API. I will try to write it down when this error occurs again.
I have been using the app since the first day of release. It also seems as if automatic updating in the background doesn't work. I have to open the app manually. I made sure to exclude it from battery optimization and to prevent the phone from sending it to sleep. It still needs to be opened manually to update risk status.

**Comment by SebastianWolf-SAP** [comment]
Dear @treysis,

the errors which you are describing are probably related to already existing issues. Please check the error code which the app is telling you and use the search for open issues here to check if for example #774 applies to you as well. For the background update error please see #756.

In case you really can't find an already existing issue with this error code/text, please open another issue with the detailed description.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
