### ISSUE TITLE
Cause 3: Something went wrong

### ISSUE THREAD

**Issue by Arghh** [corona-warn-app/cwa-app-android#856]
I never had any exceptions until today. Tried restarting app, phone, bluetooth. Everything is up to date. If it's a problem with googles api, a lot of devices could be affected. Can anyone confirm this problem? 

Commication with google api doesn't work.

I just open the app and this exception gets thrown. 

![IMG-20200712-WA0001.jpg](https://user-images.githubusercontent.com/9199258/87234885-ab714900-c3d5-11ea-953d-cc8770f542e1.jpg)

![IMG-20200712-WA0000.jpg](https://user-images.githubusercontent.com/9199258/87234889-b035fd00-c3d5-11ea-8622-f54f037bb517.jpg)

- Mobile device: OnePlus 6 oxygen 10.3.4
- Android version: Android 10
- Google play services: 20.24.14
- corona-warn-app: 1.0.5

**Comment by SebastianWolf-SAP** [comment]
This is an already reported issue, please follow-up in #774

Mit freundlichen Grüßen/Best regards,
SW
Corona Warn-App Open Source Team
