### ISSUE TITLE
Exposure checks not listed in date order

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#860]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Describe the bug

Exposure checks displayed in apparently random chronological order depending on Android language.
This is a minor Google Play services UI display issue.

## Expected behaviour

The exposure check list should be displayed in chronological order (preferably newest first).

## Steps to reproduce the issue

CWA must have been running and active for several days.
1. Android settings -> General management -> Language and input -> Language
ensure that English (United Kingdom) is at the top of the language list
2. Android settings -> Google -> COVID-19 exposure notifications -> Exposure checks
3. Scroll down and note date order:
9 JULY
13 JULY
10 JULY
11 JULY
12 JULY
(13 JULY is out of order)
4. Change first language to Deutsch (Deutschland)
5. Return to exposure checks
Android settings -> Google -> Benachrichtigungen zu möglicher Begegnungen mit COVID-19-Infizierten -> Überprüfung auf mögliche Begegnungen
10 JULI
13 JULI
11 JULI
9 JULI
12 JULI
(This seems random)
6. Change first language to English (United States)
Allgemeine Verwaltung -> Sprache und Eingabe -> Sprache
7. Return to exposure checks
JULY 12
JULY 11
JULY 13
JULY 10
JULY 9
(JULY 13 is out of order)

## Technical details

- Mobile device: Samsung Galaxy A50 SM-A505FN
- Android version: 10
- CWA Version 1.0.5
- Google Play Services 20.24.14 (120400-319035315)

---
Internal Tracking ID: EXPOSUREAPP-1931

**Comment by fredsleeve** [comment]
Same issue here and really annoying. But I think this is a Google related issue and cannot be solved here. Hopefully the developers will this adress to Google.

**Comment by MikeMcC399** [comment]
> Same issue here and really annoying. But I think this is a Google related issue and cannot be solved here. Hopefully the developers will this adress to Google.

Agreed! Unfortunately the developer e-mail address [mailto:apps-help@google.com](url) listed on [https://play.google.com/store/apps/details?id=com.google.android.gms](url) reponds with: 

"Thank you for contacting Google.
You have emailed to an address that is no longer being monitored.
To get help, please visit https://support.google.com/." 

so I was hoping that the CWA developers have a direct connection to the Google Play services exposure notifications developers and could pass this issue on to Google.

**Comment by jkrwdf** [comment]
In case a Googler reads along: It is also annoying that, if you scrolled down the list and click a certain verification event, and then go back, you are thrown to... to top of the list again. Together with the unordered dates and the length of the list this makes using this list nearly impossible.

**Comment by fredsleeve** [comment]
@MikeMcC399 @jkrwdf 
I checked the Google repos regarding this issue, but didn't find anything. Maybe it's a good place to address the issue there: https://github.com/google?q=exposure
Especially since ENF-internal code has been released 3 days ago.

**Comment by MikeMcC399** [comment]
@fredsleeve 
Thanks for your suggestion. Before diving into details in the Google repositories I've just asked on 
https://github.com/google/exposure-notifications-internals/issues/3#issue-664648756 
whether it would be a good place to go to.

The dates shown under "Exposure Checks" are still unsorted and in the meantime my configuration has been upgraded to:
Mobile device: Samsung Galaxy A50 SM-A505FN
Android version: 10
CWA Version: 1.1.1
Google Play Services 20.26.14 (120400-320008519)
Exposure Notifications Version: 15202902003

**Comment by MikeMcC399** [comment]
The reply in https://github.com/google/exposure-notifications-internals/issues/3#issue-664648756 recommended channelling issues with the Google Exposure Notification Framework through the relevant Public Health Authority/App developer, so it seems this is the right place to be!

In the meantime I can see a new label "transferred-jira" attached to this issue so I assume it is queued for being looked at.

**Comment by MikeMcC399** [comment]
I addressed this issue (Exposure checks not listed in date order) via e-mail to exposure-notifications-feedback@google.com and Google responded with:
> We're aware of this bug and hope to get it corrected for the next release.

Unless the CWA Open Source Team has a different view I would leave this issue open until a future release of the Exposure Notification System has corrected the shortcoming. Versions 16203302004 (20.33.03) and 16203314000 (20.33.14) still show the problem.

**Comment by MikeMcC399** [comment]
With Exposure Notification System version 16203613000 (Google Play Services 20.36.13) 
Settings -> Google -> COVID-19 exposure notifications -> Exposure checks
lists the checks in reverse date order (newest first) for each of the different languages listed in the original issue report:
English (United Kingdom), English (United States) & Deutsch (Deutschland).
