### ISSUE TITLE
Google API communcation error: OpenMatchingRequestStore

### ISSUE THREAD

**Issue by rugk** [corona-warn-app/cwa-app-android#867]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Describe the bug

Some strange error happened when I was using the app, i.e. it showed me a `OpenMatchingRequestStore`.

## Expected behaviour

No error.

## Steps to reproduce the issue

0. App enabled etc. as usual.
1. Opened the app, location off, Bluetooth enabled.
2. Tapped on the "Bluetooth deaktiviert" at the top to enable it.

(I was quite fast, maybe it is a race condition somehow)

-> it showed me some "Error communication with Google API". When I clicked on details, it showed me some `OpenMatchingRequestStore` exception being thrown in a stacktrace.

## Technical details

- Mobile device: FP3
- Android version: 9

## Additional context

Due to https://github.com/corona-warn-app/cwa-app-android/issues/625 / https://github.com/corona-warn-app/cwa-app-android/issues/823 I unfortunately could not get a screenshot or copy the whole stacktrace and when I pressed "okay" the thing was already gone, sorry.

I could not reproduce it again, sorry.
Anyway creating this issue in case someone else encounters this stacktrace or can explain what this exception/error means.

**Comment by rugk** [comment]
Or is this https://www.coronawarn.app/en/faq/#API39508 ? If so, your FAQ should be more specific, there are very likely multiple reasons that may result in a Google API communication error.

**Comment by tkowark** [comment]
Dear @rugk thanks for reporting this issue. Did it occur again over the last couple of days?

**Comment by rugk** [comment]
No

**Comment by SebastianWolf-SAP** [comment]
In this case we are closing this issue. In case you can reproduce it again, please let us know.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
