### ISSUE TITLE
Exposure Logging is in false "active" state when Location is turned off

### ISSUE THREAD

**Issue by kbobrowski** [corona-warn-app/cwa-app-android#881]
## Describe the bug

After switching off Location app still displays that Exposure Logging is active, when in fact it is not. There is a notification displayed from Play Services to turn Location back on, but it can be dismissed (even accidentally, by dismissing all notifications), and user stays in a state with exposure logging not working, false "active" status displayed in the app, and no clue how to turn it back on.

## Expected behaviour

App should always display correctly whether exposure logging is active, and guide user to turn Location back on if this is the reason for exposure logging not working. This is already handled correctly for the case when Bluetooth is off.

## Steps to reproduce the issue

1. download the app
2. agree to exposure logging
3. turn location off
4. dismiss all notifications
5. check if you are in a false state of "active" exposure logging with no clue how to turn it back on

## Technical details

Android 10

## Possible Fix

I'd suggest to take a look how Immuni app from Italy handles this. If using "Location" word is not desired here app can simply display "Service inactive", and a button to activate it which brings up "Turn on COVID-19 Exposure Notifications?" prompt again and leaves it up to Exposure Notifications framework to handle turning on all required services.

---
Internal Tracking ID: EXPOSUREAPP-1618

**Comment by tkowark** [comment]
Sorry about the moving back and forth. This issue is already being worked on, so it should stay in the android repo.

**Comment by btreut** [comment]
@aurisnoctis

sorry for the late answer ...

> On my German Android version 6.0.1 it is:
> `Android Einstellungen` > `Standort` > `Modus` > `Nur GPS`.

on my German Android 8.0.0 (Samsung Galaxy S7) the only hint for "Only GPS" is far down in tree:

`Android Einstellungen` > `Verbindungen` > `Standort` > `Suchmethode` > `Nur Telefon`

and on all higher levels it is called "Nur Telefon" which I find a bit misleading, but that is Googles fault.

<img src="https://user-images.githubusercontent.com/8996291/87660651-b3c3de00-c75f-11ea-9714-a91b31b74f74.png" alt="screenshot" width="50%">

**Comment by aurisnoctis** [comment]
Update to https://github.com/corona-warn-app/cwa-app-android/issues/881#issuecomment-648214790

Google seems to have fixed wrong ENF-Notifications about missing location and bluetooth as of ENF version 15202902003 (on Samsung S5 with stock Android 6.0.1), so I closed https://github.com/google/exposure-notifications-android/issues/35.

At least this helps to now correctly inform people that location has to be turned on. Happy that the CWA team is working on it as well.

**Comment by kbobrowski** [comment]
Fixed for me (v1.2.0) - when switching off location, exposure logging is no longer displayed as "active" in the app
