### ISSUE TITLE
Change Text for "Notification of possible encounter"

### ISSUE THREAD

**Issue by andipabst** [corona-warn-app/cwa-app-android#891]
## Avoid duplicates
* [x] This enhancement request has not already been raised before
* [x] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [x] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

Currently, if bluetooth or the location service is enabled on the device, a notification pops up with the main title "notification of possible encounter" (see first Screenshot attached). After disabling bluetooth again, a notification with the same title shows a second time. The intent of the notifications is to suggest to enable the contact tracing by enabling bluetooth and location services. But due to the title and the red alert logo, every time I see this notification, for a moment I am not sure if it is a warning about me having a possible encounter with someone who is infected.

![Bluetooth enabled](https://user-images.githubusercontent.com/9639382/87822640-160d0380-c872-11ea-9309-cb741e1d7542.png)
![Bluetooth disabled again](https://user-images.githubusercontent.com/9639382/87822569-fc6bbc00-c871-11ea-974e-2cd5b2233953.png)

## Suggested Enhancement

I propose to use a different wording for the notification, e.g. "To start tracing, turn on bluetooth and location services", like currently shown in the subtitle of the notification.

## Expected Benefits

I expect the intent of the notification to be clearer to the user and thus increasing the user experience for using the app.

**Comment by SebastianWolf-SAP** [comment]
Thanks for this enhancement proposal. However, we already have a corresponding issue. Please follow-up in #532 We will therefore close this issue.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
