### ISSUE TITLE
Datenübernahme bei Handy - Wechsel 

### ISSUE THREAD

**Issue by wataga** [corona-warn-app/cwa-app-android#892]
Es fehlt eine Option, bei einem Handy-Wechsel die aktuellen Daten zu exportieren, um sie später auf dem neuen Handy wieder zu importieren.

**Comment by tkowark** [comment]
Vielen Dank für den Vorschlag. Wir verfolgen diesen, wie auch andere Vorschläge zu erweiterten / neuen Funktionen im CWA Wishlist Repository (https://github.com/corona-warn-app/cwa-wishlist/issues/8).
