### ISSUE TITLE
Release Notes for Google Play services / COVID-19 exposure notifications?

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#894]
## Avoid duplicates
* [X] Question is not already answered in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Question is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Question has not already been asked in another issue

## Your Question
CWA on Android is completely dependent on the COVID-19 exposure notifications service in Google Play services. I'm struggling to understand what enhancements / bug fixes are expected to be in a certain version of the COVID-19 exposure notifications service and how these are rolled out. 

Does Google make this information (publicly) available? Are there any links to release notes of the COVID-19 exposure notifications service which discuss the exact version numbers, functionality and correlation with the Google Play services version? Also for users subscribed to Google Play services (Beta)?

I currently have three different devices running Android 8, 9 and 10 and they have Android / COVID-19 / Play services versions as follows:
8 / 15202902002 / 20.26.13
9 / 15202902002 / 20.24.14
10 / 15202902002 / 20.26.14
So currently I'm wondering what is supposed to be in version 15202902002 and whether this is a beta version or generally released version. Thanks for any insight!

**Comment by SebastianWolf-SAP** [comment]
Thanks for this question. There is actually some information available and just yesterday Google extended their site considerably for instance by adding some code snippets how their Exposure Notification Framework works. We compiled the information which we know and added a new entry to our FAQ: https://www.coronawarn.app/en/faq/#ENF_version

You already seem to run the ENF version 1.5 on all of your three devices!

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
Thank you so much for the new entry to the FAQ on https://www.coronawarn.app/en/faq/#ENF_version ! That is amazing and clears up my uncertainty.

Just one very minor point: in
"YYWW**W**xxxxx, where YY is the year (for example, 20) and WW is the week. If you see the version number in this format, your phone is not yet using version 1.5."
I think that should be "YYWWxxxxx" i.e. with two "W"s not three.

**Comment by SebastianWolf-SAP** [comment]
Thanks for the report - the wrong third 'W' was removed. :)
