### ISSUE TITLE
Is there a timer for the Risiko-Begegnung?

### ISSUE THREAD

**Issue by unmerkbar** [corona-warn-app/cwa-app-android#896]
* [X] None of the other issue templates apply to this issue.

Hi there.

I am asking for a friend who is not so tech-experienced and doesn't have a github account :).

We talk and exchange often about the corona-warn-app project (very good project by the way, kudos to everyone). The Friend recently showed my that he had 1 Risiko-Begegnung with low risk. Thus, still in green state by the UI. The friend, of course, was a little bit nervous then but calmed down quickly.

The Risk occured at 30th of June.

I read some documentation and expected that data is erased after 14 days. Thus, we expected that the UI will not show a Risiko-Begegnung after 14 days anymore, but by yesterday (19th of July) it still shows the Risiko-Begegnung.

We ask ourself now: 
- Is there a time which should set the Risiko-Begegnung timer to zero after 14 days as well?
- Did the friend had another Risiko-Begegnung in the meantime/overlapping time? (But then he should have seen 2 Risikio-Begegnungen, right?)
- Will the Risiko-Begegnung stay with 1 as a counter for longer than 14 days? Maybe unlimited?
- How to differentiate if there was 1 other/new Risiko-Begegnung overlapping with a timer which sets the "old" value to zero? Would be good to see a difference if how many values are really "new" / different from "old" (Does this make sense? The use case with an tiny time slot resetting the old count to 0 and having a new risk could be very low I guess)

Thank you all and best regards.

**Comment by daimpi** [comment]
Somewhat related: https://github.com/corona-warn-app/cwa-wishlist/issues/100 (and https://github.com/corona-warn-app/cwa-backlog/issues/23)

**Comment by SebastianWolf-SAP** [comment]
As @daimpi already mentioned, improvements to the risk encounter screen are addressed in https://github.com/corona-warn-app/cwa-wishlist/issues/100. We addressed especially this topic as higher priority to the product management and there are good chances (no promises though ;)) that there will be significant improvements in one of the next releases. I copied your questions to the wishlist item. As soon as it's scheduled for one of the next releases, we will move it to the cwa-backlog repository.

We will close this issue, but feel free to follow-up in https://github.com/corona-warn-app/cwa-wishlist/issues/100

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by unmerkbar** [comment]
Hi @daimpi and @SebastianWolf-SAP. Thank you for answering (and my late reply due to vacation :) ).

I read all the related wishlist and backlog items and I think everything is covered. I wanted to provide today also more input wrt documentation and hotline answers (because my friend called the hotline as he was afraid what this could all mean), but even this is covered by the related items.

Thanks a lot and looking forward for further releases 👍 .

Have a nice summer.
