### ISSUE TITLE
Setting prioritized background activity doesn't work after the first time (needs a reboot)

### ISSUE THREAD

**Issue by tomjschwanke** [corona-warn-app/cwa-app-android#906]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Describe the bug

After disabling battery optimizations via the app but then enabling it again, trying to disable it again via the app doesn't work anymore. The app thinks optimizations are disabled when they're not (checked in system settings). Disabling and then enabling optimizations via system settings makes the app aware again of the disabled optimizaions. It still can't enable them again.
**Edit: it seems that after a reboot the optimizations are correctly disabled** 

## Expected behaviour

Disabling battery optimizations should work every time. Without a reboot.

## Steps to reproduce the issue

Go into Corona-Warn-App settings and "prioritized background" activity. Enable it and click "Ok" in the promt to disable battery optimizations. Now click the blue button underneath which guides you into system settings. Enable battery optimizations again. Go back to the app and try to enable it again. Select Ok on the prompt again. Now go back into system settings and see that the app is still optimized.
Reboot to have the list show the correct status again

## Technical details

- Mobile device 1: OnePlus 7 Pro
Android version: Android 10 (OxygenOS 10)
App Version: 1.1.1 (PlayStore)

- Mobile device 2: Samsung Galaxy S7
Android version: Android 8 (Samsung Experience 9.0)
App Version: 1.2.0 (dev branch)

- Mobile device 3: Google Pixel 3a (Emulator)
 Android version: Android 11 (Emulator)
App Version: 1.2.0 (dev branch)

---
Internal Tracking Id: EXPOSUREAPP-1853, [EXPOSUREAPP-3094](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3094)

**Comment by tomjschwanke** [comment]
This may not be fixable through this app if it's an Android problem.

**Comment by SebastianWolf-SAP** [comment]
Thanks for the report. We will definitely add it to the FAQ and also check with the product team to get this hint in the app.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by GPclips** [comment]
This issue has been completed (fixed version 1.2) and will be closed now.

**Comment by daimpi** [comment]
@GPclips 
> This issue has been completed (fixed version 1.2) and will be closed now.

Are you sure about this? I can still reproduce this issue on CWA 1.3.1 with my Samsung Galaxy S8 (Android 9).

**Comment by dsarkar** [comment]
Hi @daimpi, @tomjschwanke. This issue should have been fixed with EXPOSUREAPP-3094 CWA 1.6.1. Is problem still persisting? Thanks for the feedback. Best, DS

---
Corona-Warn-App Open Source Team

**Comment by tomjschwanke** [comment]
Yep, the setting takes effect immediately. I'm not sure how user friendly that UX is (honestly that's caused by Android though), so maybe you could implement a little tutorial on how to do this.

**Comment by daimpi** [comment]
@dsarkar yap I can also confirm on my Samsung Galaxy S8 (Android 9) that the status of Prioritized Background Activity (PBA) is now shown correctly. 

But I also concur with @tomjschwanke's statement that the process to enable PBA is a bit clumsy with the new version: There is no simple slider/button to activate PBA anymore, instead one gets thrown into the "optimize battery usage" menu of the device where you manually have to find CWA (which is only possible after changing the filter from "apps not optimized" to "all") and disable "battery optimization" for CWA.

But that's a somewhat different problem which probably deserves it's own issue (@tomjschwanke would you like to open a new issue for this or should I? 🙂)

**Comment by MikeMcC399** [comment]
@daimpi 
>But I also concur with @tomjschwanke's statement that the process to enable PBA is a bit clumsy with the new version: There is no simple slider/button to activate PBA anymore, instead one gets thrown into the "optimize battery usage" menu of the device where you manually have to find CWA (which is only possible after changing the filter from "apps not optimized" to "all") and disable "battery optimization" for CWA.
>
>But that's a somewhat different problem which probably deserves it's own issue (@tomjschwanke would you like to open a new issue for this or should I? 🙂)

I suggest you upvote (and comment on) https://github.com/corona-warn-app/cwa-app-android/issues/1606. I don't think a new issue is necessary.

**Comment by daimpi** [comment]
@MikeMcC399 thanks for the pointer, that's exactly what I was looking for 👍

**Comment by dsarkar** [comment]
Dear @tomjschwanke, @daimpi, @MikeMcC399, and community

Thank you for your contributions. We will close this issue now. However, agreed that the wording is a bit confusing. We keep open https://github.com/corona-warn-app/cwa-app-android/issues/1606 and in the meantime just might improve at least the FAQ. 


Best wishes,
DS

---
Corona-Warn-App Open Source Team
