### ISSUE TITLE
Backend URLs should not be changeable by intents.

### ISSUE THREAD

**Issue by timo-drick** [corona-warn-app/cwa-app-android#91]
## Describe the bug
DynamicURLs object is used to store the backend URLs. All urls are defined as var so they can be changed any time. This is a security issue. Currently they are only changed in LauncherActivity depending on the URL schema that is used to launch the app. So every app could start the "Corona-Warn-App" with any backend urls.
I assume that it was introduced to make testing possible. But the risk forget to remove it later for the production version is to high.

## Expected behaviour
Define the backend URLs in DynamicURLs as "val" read only variables. 

## Steps to reproduce the issue
Look at the code in LauncherActivity.kt and DynamicURLs.kt files.

## Possible Fix
Define the backend URLs in DynamicURLs as "val" read only variables.
(Maybe you could also introduce flavors which allow URL changing for testing proposes but in my opinion it would be a security nightmare when any other app could change the backend URLs of this app.)

**Comment by pwoessner** [comment]
Hi @timo-drick , as stated in #156 this will be removed in the release app. Thanks, Philipp
