### ISSUE TITLE
9002 The Exposure Notification Framework must be active, check your tracing status

### ISSUE THREAD

**Issue by Raptormet** [corona-warn-app/cwa-app-android#910]
## Describe the bug

java.lang.IllegalStateExeption: 

The Exposure Notification Framework must be active, check your tracing status
at 
de.rki.coronawarnapp.transaction.(etc.)

## Expected behaviour

Starting the app with or without bluetooth on. Expect no failure code :)

## Steps to reproduce the issue

![20200722_160155](https://user-images.githubusercontent.com/68651300/88188276-e70edd00-cc37-11ea-8c8e-78b1c224b8e2.jpg)

![20200722_160206](https://user-images.githubusercontent.com/68651300/88188346-03ab1500-cc38-11ea-85d1-2b8c1e938cd7.jpg)

## Technical details

- Mobile device: Samsung S7
- Android version: 8.0.0
- Samsung Experience-V: 9.0

**Comment by Raptormet** [comment]
Already closed #852

**Comment by Raptormet** [comment]
Might be wrong, but did I closed the issue prematurely? Taking a look at the screenshots of other problems, mine does differ.

**Comment by vaubaehn** [comment]
@Raptormet Yes, for me it looks like you have discovered a different bug, or let's say, an unhandled exception. Are you able to reopen your issue?

**Comment by Raptormet** [comment]
The version update went under my radar. Updated the app and the issue seems to be resolved for now. Thank you for mentioning that.

**Comment by SebastianWolf-SAP** [comment]
OK, please let us know if the issue re-occurs. We can reopen the issue or you can simply create a new one.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team
