### ISSUE TITLE
Dialogbox "Etwas ist schiefgelaufen"

### ISSUE THREAD

**Issue by jgberlin** [corona-warn-app/cwa-app-android#917]
CAT S60 Android 6.0.1 - Nach Deinstallation erneute Installation - Fehlermeldung bei Erststart

(Meldung von Hand abgeschrieben)

Etwas ist schiefgelaufen:
Ursache: 
...ApiException: 10: Unable to validate key file signature: Pipe is closed

at  

android.support.v4.media.MediaDescriotionComputApi21Builder.setResultOrApiException(MediaDescriptionCompatApi21.java:3)

Stacktrace geht weiter über diverse com.google.android.gms.* Klassen

**Comment by daimpi** [comment]
Duplicate of #737 ([FAQ entry](https://www.coronawarn.app/de/faq/#API10)) 
Related to #774 (For technical details cf. [these](https://github.com/corona-warn-app/cwa-app-android/issues/774#issuecomment-662335129) [comments](https://github.com/corona-warn-app/cwa-app-android/issues/774#issuecomment-662588296))

**Comment by tkowark** [comment]
In der Tat ist das ein Duplikat. Könnten Sie aber bitte nachschauen, welche Version des Exposure Notification Frameworks sie haben? Unter https://www.coronawarn.app/de/faq/#ENF_version finden sie eine entsprechende Anleitung.

**Comment by gitbrueck** [comment]
Today, I got v1.5 of EN API and the problem disappeared. 👍

**Comment by jgberlin** [comment]
> 
> 
> In der Tat ist das ein Duplikat. Könnten Sie aber bitte nachschauen, welche Version des Exposure Notification Frameworks sie haben? Unter https://www.coronawarn.app/de/faq/#ENF_version finden sie eine entsprechende Anleitung.

Version 15202902003

**Comment by jgberlin** [comment]
...Möglicherweise wurde die ENF Version neu aufgespielt. Der Fehler liess sich Deinstalltion und Neuinstallation der App nicht reproduzieren.

**Comment by tkowark** [comment]
Ja, das ist dann die neue Version, mit der der Fehler nicht mehr auftreten sollte. Das Update der Play Services passiert dabei im Hintergrund. Sollte das Problem noch mal auftreten können sie natürlich gern einen neuen Issue aufmachen.
