### ISSUE TITLE
Prioritized background activity can't be disabled

### ISSUE THREAD

**Issue by error401de** [corona-warn-app/cwa-app-android#921]
## Current Implementation
Using a Samsung S9. Set new slider "Prioritized background activity".
Now a infobox explains I need to go to the device settings to disable it. If I click the shown button I'm redirected to the app optimisation settings. In there I can "optimise" the CWA, which means the background tasks would be surpassed. But even if I activate this optimisation, the "Prioritized background activitiy" slider stays activated.
I therefore now have no clue if the app is working or not.

## Suggested Enhancement
Read system configuration and show what actually is happening.

## Expected Benefits
Right now it can't be interpreted whats going on.  So the benefit it at least a better UX, at most is brings back the required functionality.

**Comment by daimpi** [comment]
Related to #906 
Can you reboot your Phone and check which status it is showing then? 

@corneliusroemer said was actually showing the correct status for him (on) as he manually exempted it from "optimization" before the update, so it seems to be reading the system settings, but might get confused if turned on, and manually off again. A reboot might fix this as described in #906.

**Comment by error401de** [comment]
On **second** reboot it's shown correct. Interesting.
Thanks for the info, I'll close this ticket.

**Comment by daimpi** [comment]
> 
> 
> On **second** reboot it's shown correct. Interesting.

That's quite interesting indeed. I tried to reproduce this on my Galaxy S8 (Android 9) and could only reproduce what is already stated in #906 : My slider was showing the correct status except after 
1. disabling "battery optimizations" for CWA (in CWA)
2. enabling "optimizations" in the Settings
3. disabling "optimizations" again (in CWA) 

After Step 3 my phone showed "Prioritized background activity" activated in CWA, but in the phone settings it showed "battery optimizations enabled" for CWA.
But after **one** reboot, the settings also showed the correct "battery optimizations disabled" without any further interference on my part.

@error401de Can you reliably reproduce the problem on your phone? If so you might wana reopen this issue, as it seems related to, but still different from #906.
