### ISSUE TITLE
Possible bug in background priority settings logic

### ISSUE THREAD

**Issue by AdrianLxM** [corona-warn-app/cwa-app-android#923]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Describe the bug
This is a finding from code review:
* In `fragment_settings_background_priority` the logic to show that background priority is enabled is negated:
`app:enabled="@{!settingsViewModel.isBackgroundPriorityEnabled()}"`
* The copy for this setting suggests that the logic should not be negated: `<string name="settings_background_priority_title">"Prioritized Background Activity"</string>`

## Expected behaviour

When the user has enabled "Prioritized Background Activity" (in system lingo `isIgnoringBatteryOptimizations`) it should show as enabled. When the setting is disabled, it should show as disabled.

## Steps to reproduce the issue

_It is not in current release yet_

## Possible Fix

Remove the negation here:
https://github.com/corona-warn-app/cwa-app-android/blob/dev/Corona-Warn-App/src/main/res/layout/fragment_settings_background_priority.xml#L66

## Additional context

The system preferences also show "isIgnoringBatteryOptimizations" (= "Prioritized Background Activity") as enabled. The logic in the app should not be different in order to not confuse the user.

---
Internal Tracking ID: EXPOSUREAPP-1928

**Comment by SebastianWolf-SAP** [comment]
Thanks for the report. We will discuss it with the dev team and get back to you as soon as we have news.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by mamoch** [comment]
I am not familiar with Android development, but from what I see, https://github.com/corona-warn-app/cwa-app-android/blob/7590e2a777e28808d08096ccd4260f4d445443be/Corona-Warn-App/src/main/res/layout/fragment_settings_background_priority.xml#L66 seems to be used to disable the _settings switch_ in the UI, once the setting is on. This is needed, because the user cannot switch off the setting from within the CWA, but needs to do it through Android’s app settings.

The “status” of the setting seems to be queried here: https://github.com/corona-warn-app/cwa-app-android/blob/7590e2a777e28808d08096ccd4260f4d445443be/Corona-Warn-App/src/main/res/layout/fragment_settings_background_priority.xml#L71 which would be correct.

**Comment by MikeMcC399** [comment]
Hi @AdrianLxM 
This topic seems to have got lost! Would you like to check if you think it is still an issue?

I checked it on my Samsung Galaxy A50 SM-A505FN device running Android 10 with CWA version 1.10.1. 

- When the app is showing Prioritized Background Activity On, then the app is showing battery usage not optimised.
- When the app is showing Prioritized Background Activity Off, then the app is showing optimising battery usage.

This is a correct correlation. Below are screen shots to illustrate.
The left column is from CWA > three-dot overflow menu > Settings.
The right column is from Settings > Apps > Corona-Warn > Battery.
The two screen shots on the top row belong together, as do the two screen shots on the bottom row.

![Background Activity overview](https://user-images.githubusercontent.com/66998419/104626461-3b9a8e80-5696-11eb-9b0a-3d176da75421.jpg)

**Comment by AdrianLxM** [comment]
I'm currently not in Germany and using the Austrian counterpart. As you can only have one tracking app, it will take a while to get onto this. If there are no other people reporting this, I'd consider this issue closeable. Sorry band thanks

**Comment by dsarkar** [comment]
@AdrianLxM Thanks for the feedback and contributions. We will therefore close this issue for the time being, however, re-open it if necessary.

@MikeMcC399, Thanks for checking. We all realize how confusing the wording is. We still have an open issue regarding a clear FAQ. We keep your comments in mind.

Again, thanks to everybody. Best wishes, DS
