### ISSUE TITLE
Error code 8: attempt to write a readonly database

### ISSUE THREAD

**Issue by pathmapper** [corona-warn-app/cwa-app-android#924]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only (didn't find any similiar issue in the other repos)
* [x] Bug is not already reported in another issue

## Describe the bug

When resetting the CWA (Anwendung zurücksetzen), the following error message appears:

> Ursache: 9002
> Etwas ist schief gelaufen
> Error code 8: attempt to write a readonly database

<img src="https://user-images.githubusercontent.com/20856381/88452246-72b58300-ce5d-11ea-8c63-3a8e59d2670a.png" width="300" />

<img src="https://user-images.githubusercontent.com/20856381/88452277-9ed10400-ce5d-11ea-9401-1c053a6ab502.png" width="300" />

## Expected behaviour

No error

## Steps to reproduce the issue

1. Go to CWA Settings
2. Click on "Anwendung zurücksetzen"
3. Confirm all the dialogues to use the CWA again

## Technical details

- Mobile device: Motorola Moto G 3
- Android version: 6.0.1 (not rooted)
- CWA version: 1.1.1

---
Original Issue ID: EXPOSUREAPP-1904, EXPOSUREAPP-1851

**Comment by pathmapper** [comment]
Just reproduced the error again and it seems that you have to reset the CWA two times to trigger the error 8 (the error was only there on the second and any further reset).

**Comment by GPclips** [comment]
This issue has been marked as obsolete and will be closed now.

**Comment by GPclips** [comment]
Hello community,

this issue has been closed by mistake. I reopened the issue.

Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
Dear @pathmapper,

We would appreciate some feedback: Do you still experience this issue with the actual CWA version 1.6.1? 

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by pathmapper** [comment]
Hi @dsarkar,

the issue is not reproducible with CWA `1.6.1`, please feel free to close here.
