### ISSUE TITLE
Make "prioritized background" more present

### ISSUE THREAD

**Issue by error401de** [corona-warn-app/cwa-app-android#926]
## Current Implementation
Important setting is hidden in the settings menu, I only heard of this in the news.
It's good that this issue has been addressed. But as long as this is not well-known, it's not resolved.

## Suggested Enhancement
There should be a visible hint on the start page, maybe even a one-time-notification.

## Expected Benefits
Avoid situations that many users will not get notified

**Comment by daimpi** [comment]
Duplicate of #925
