### ISSUE TITLE
Simplify Fragments view unbinding code

### ISSUE THREAD

**Issue by henriquenfaria** [corona-warn-app/cwa-app-android#927]
## Avoid duplicates
* [x] This enhancement request has not already been raised before
* [x] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [x] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

The View Binding usage inside the app's Fragments is a bit complicated and repetitive.

1. duplicated binding properties to be able to get rid of the null checks:

```
private var _binding: FragmentMainBinding? = null
private val binding: FragmentMainBinding get() = _binding!!
```

2. duplicated code, every Fragment  override `onDestroyView` in order to unbind the view:

```
override fun onDestroyView() {	
     super.onDestroyView()	
    _binding = null	
}
```

## Suggested Enhancement

My suggestion is to create a lifecycle-aware delegated property that automatically unbinds the view during `onDestroyView`. As a nice side-effect, we would be able to remove the `_binding` property.

The implementation would be similar to https://proandroiddev.com/make-android-view-binding-great-with-kotlin-b71dd9c87719

## Expected Benefits

- The code would become simpler and cleaner. 
- Less duplicated code.
- Less chance of Fragment memory leaks caused by missing `_binding = null` statements.

---
Internal Tracking ID: EXPOSUREAPP-1926

**Comment by henriquenfaria** [comment]
Pull Request: https://github.com/corona-warn-app/cwa-app-android/pull/928

**Comment by henriquenfaria** [comment]
Hi @pwoessner 
Any updates from your side regarding this issue/pr?

**Comment by svengabr** [comment]
Hey @henriquenfaria sorry for the late response here. We are currently working hard on finalizing the next release. I have re-assigned the issue to make sure it gets in the hand of the right people soon.

Best regards,
SG

Corona-Warn-App Open Source Team

**Comment by henriquenfaria** [comment]
No problem @svengabr :)
Let me know if you need my help to rebase/update my PR.
