### ISSUE TITLE
Exposure Checks only show 100 entries in the log (Android)

### ISSUE THREAD

**Issue by daimpi** [corona-warn-app/cwa-app-android#941]
## Avoid duplicates
checked: this is the Android counterpart to https://github.com/corona-warn-app/cwa-app-ios/issues/934 as [suggested](https://github.com/corona-warn-app/cwa-app-android/issues/930#issuecomment-665063945) by @SebastianWolf-SAP 

## Describe the bug

When checking the Google Exposure Notification (ENF) log, only 100 entries are displayed even though the main ENF screen might show well over 200 checks performed in the last 14 days. This makes it hard for people trying to find out whether their app is working correctly or trying to debug an issue, as the listed entries can be misleading (cf. e.g.  https://github.com/corona-warn-app/cwa-app-android/issues/930#issuecomment-664658857)

## Expected behaviour

The ENF log should show all entries for checks performed within the last 14 days. 
Bonus points for chronological order and easier navigation 🙂.
## Steps to reproduce the issue

On your Android phone:
1. Go to Settings -> Google -> Covid-19 Notifications
2. Note the number of Checks performed in the last 14 days and then Tap this field to get to the actual log. 
3. Count the entries in the log (either manually or by exporting them and looking at the .json file)
4. The number of items in the log seems to deviate significantly from the number of checks performed shown on the previous screen: the log only contains 100 items  while the previous screen might show well over 200 checks performed in the last 14 days.
<img src="https://user-images.githubusercontent.com/22129968/88575206-c5e92a80-d043-11ea-87f3-a6b3beb4329e.jpg" width="400">

- my logs from the 26th and 27th: [my logs.zip](https://github.com/corona-warn-app/cwa-app-android/files/4984606/my.logs.zip)

## Technical details

I could verify this Problem on at least two devices:
- Samsung Galaxy S8 (Android 9, ENF v.15202902003)
- LG G5 (Android 8, ENF v.15202902003)

## Possible Fix

This obviously seems to be a problem of Google’s ENF. Please coordinate with them to get this issue resolved.

## Additional context

I can confirm this issue is consistently happening on the above listed devices (I checked on multiple days). Other examples can be found [here](https://github.com/corona-warn-app/cwa-app-android/issues/744#issuecomment-663952891) and [here](https://github.com/corona-warn-app/cwa-app-android/issues/930).

Otoh the exposure check log [here](https://github.com/corona-warn-app/cwa-app-android/issues/899#issuecomment-661965164) actually contains >200 entries. Given that this last example is from longer ago, maybe this 100 entries limit is something Google introduced more recently?

---
Internal Tracking ID: EXPOSUREAPP-1935

**Comment by SebastianWolf-SAP** [comment]
Thanks for opening this one and for providing detailed information - I'm really curious if Apple and Google actually agreed on this strange behavior...

**Comment by DerVogel2020** [comment]
The same behaviour on my Samsung A5 (2017) SM-A520F with android 8 and ENF 15202902003.
On the previous screen is '238 Überprüfungen innerhalb der letzten 14 Tage'. In the detailed log are exactly 100 entries.

**Comment by Waldkotz** [comment]
I can verify the Problem using a OnePlus5 (A5000).
Android 10, 
![image](https://user-images.githubusercontent.com/68939801/88761710-f1693380-d16f-11ea-98fd-7d7de8a5a8ab.png)
The *.jason contained 100 timestamps.
[all-exposure-checks.txt](https://github.com/corona-warn-app/cwa-app-android/files/4992842/all-exposure-checks.txt)

**Comment by MikeMcC399** [comment]
"Export exposure checks" is exporting the 100 most recent records. I could see that after I imported the all-exposure-checks.json into Excel and analysed it with an Excel pivot table. It should at least be able to cope with 14 x 14 = 196 records, and ideally export exactly what is displayed in the UI.

The sorting issue mentioned in 
>Expected behaviour
...
Bonus points for chronological order ... 

is also logged under https://github.com/corona-warn-app/cwa-app-android/issues/860 .

**Comment by MikeMcC399** [comment]
Hi @JoachimFritsch !
Any chance to get some movement on this issue with Google?

**Comment by harambasicluka** [comment]
Hi @MikeMcC399,

we brought it up and let you know if we get an update. Thanks for your patients.

Cheers,
Luka

**Comment by vaubaehn** [comment]
Hi @MikeMcC399 and @harambasicluka ,
today I checked my exposure matching log: It holds 16 days, all 14 matchings - except one from August 18 with 20 matchings (API39508 day). So, in all the log holds 230 entries. Announced on the main page of "Covid-19 notifications" are also 230 entries.
So for me, everything is in line now (except sorting and better UX). :+1:

**Comment by daimpi** [comment]
@vaubaehn oh nice! Which ENF version do you have? 🙂

**Comment by MikeMcC399** [comment]
Hi @vaubaehn 

Thank you very much for checking! 

I checked with ENS 16203302004 and I can confirm that I am also seeing all 224 entries (14x16).
I see on https://www.apkmirror.com/apk/google-inc/google-play-services/google-play-services-20-33-14-release/ that 20.33.14 was released today.
Going through the Google Play Store the latest version for my device is listed as 20.30.19, so I guess the 20.33.14 version is just being rolled out, and the 16203302004 version of ENS I am using is probably still a beta version.

**Comment by daimpi** [comment]
I can confirm this: ENF 16203302004. It tells me that 221 checks have been performed, and indeed I find 221 checks in the exposure log 😊.

@SebastianWolf-SAP @JoachimFritsch this issue seems to be resolved, feel free to close it unless you want to keep it open for some other reason 🙂.

**Comment by vaubaehn** [comment]
Hi @daimpi ,

> @vaubaehn oh nice! Which ENF version do you have? 🙂

I also have version 16203302004, but configuration (https://github.com/corona-warn-app/cwa-app-android/issues/933#issuecomment-677463999) is unknown though 😉

@MikeMcC399 : I suppose 16203302004 to be a current productive version, it's been with me for a couple of days already, and I'm not in beta program.

Just one little flaw I came across later: main screen of Covid-19 notifications says 230 checks of the past 14 days. It's actually 16 days, but for me more a minor cosmetic problem though.

Have a great night @ all!

**Comment by MikeMcC399** [comment]
@vaubaehn 

> I also have version 16203302004, but configuration ([#933 (comment)](https://github.com/corona-warn-app/cwa-app-android/issues/933#issuecomment-677463999)) is unknown though 😉

Thanks for confirming your version and that you are not in the beta program!

> Just one little flaw I came across later: main screen of Covid-19 notifications says 230 checks of the past 14 days. It's actually 16 days, but for me more a minor cosmetic problem though.

I already reported the other issue that you mention, which is logged under [Recorded number of exposure checks too high after 14 days](https://github.com/corona-warn-app/cwa-app-android/issues/1020) https://github.com/corona-warn-app/cwa-app-android/issues/1020.

Also wish you a good night!

**Comment by kereng5** [comment]
I have version 16203302004 since August 19, but yesterday there were still only 100 lines in my exposure log (2 lines of August 19 and 14 each day from August 20 to 26).
Today (August 27) there are 238 (14 times 17) lines starting August 11. The main page says "238 Überprüfungen innerhalb der letzten 14 Tage" as ist does every morning before it says 224 later in the evening.
Google play services v. 20.30.19 but I don't know since when. App v. 1.2.1

**Comment by vaubaehn** [comment]
Hi @MikeMcC399 , cross-renferencing from [here](https://github.com/corona-warn-app/cwa-website/issues/320#issue-686476461), I have some additional questions, to understand better, what is actually happening. In the time, when CWA as well as SwissCovid had been installed, did the "log" display entries for *both* apps, and after you uninstalled either app, the entries for the other were kept in the log?

**Comment by MikeMcC399** [comment]
@kereng5 

I'm confused about whether you still have the problem. Can you confirm that you are now seeing more than 100 records?
I checked again today and my "Export exposure checks" is exporting 238 records (17 days x 14 each day).

If you are seeing more than 100 records, then I think this issue can be closed.
The issue about ageing out old records is covered in https://github.com/corona-warn-app/cwa-app-android/issues/1020 which is still open.

Thanks!

**Comment by kereng5** [comment]
@MikeMcC399 
Before Juli 23 there were 17 days in my exposure log. Then it was limited to 100 lines (7 days). Since yesterday 17 days again.
[all-exposure-checks_20200828.txt](https://github.com/corona-warn-app/cwa-app-android/files/5140708/all-exposure-checks_20200828.txt)

**Comment by MikeMcC399** [comment]
@kereng5 
Thanks for your clarification. It sounds like this issue can be closed. Maybe Daniel @daimpi would like to re-confirm his opinion?

**Comment by daimpi** [comment]
Yap I guess we can close it 🙂.
