### ISSUE TITLE
Switching phones deletes two weeks worth of contact tracing

### ISSUE THREAD

**Issue by PhilLab** [corona-warn-app/cwa-app-android#962]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
    - The problem is briefly touched [here](https://www.coronawarn.app/en/faq/#backup) but without mentioning the larger implications
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Describe the bug

Neither backup nor transferal to a new phone is possible. This means that if you had a Covid-19 encounter in the past 14 days before you switched to a new phone, the warnings will go unnoticed.

As a result, switching phones during the pandemic puts you at risk. It also puts your previous contacts at risk if you have a positive test result but the app cannot notify them anymore.

## Expected behaviour

If a backup of IDs is technically not possible, at least a data transferal between the two phones should be possible, e.g. via Bluetooth. During this procedure, the "ownership" of the random IDs shall be transferred from the old to the new phone.

However, a true backup (if technically possible) would be the best solution as it also deals with the problem of lost / stolen devices.

## Steps to reproduce the issue

1. Have a phone with the corona app installed
1. Setup a new phone
2. Install the corona warn app
3. now there is no way to retrieve the previous 14 days of random IDs for the newly installed app.

## Technical details

- Mobile device: all
- Android version: all

## Possible Fix

Add a button to the app which allows transferal of ids to a different phone, e.g. via bluetooth.

## Additional context
--

**Comment by RoxanaVuc** [comment]
Dear PhiLab,

thank you very much for your proposal.

To give the community a space for discussing new feature ideas or enhancements that might not be taken up immediately by the development teams, we created the cwa-wishlist repository.

This idea is one of these feature ideas or enhancements. Consequently, we will move this issue to this repository and allow the community and you to further refine it, discuss pros and cons, and evaluate alternatives.

The issue will not be closed in this repository to ensure long-term visibility. All issues in the cwa-wishlist repository will be discussed with our contracting entities. They will decide whether they will be implemented or pursued further. As soon as we have any updates, we will let you know about the details.

Best regards,

RV

Corona-Warn-App Open Source Team
