### ISSUE TITLE
Display of planned update should be more precise

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#964]
## Avoid duplicates
* [X] This enhancement request has not already been raised before
* [X] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

The risk card shows "Updated daily" at the bottom when a background update process is running.

## Suggested Enhancement

The information about the next planned update should be more precise, such as:
Updated daily: next update planned today / tomorrow at nn:nn or
Updated daily: next update planned today / tomorrow between nn:nn and nn:nn 

## Expected Benefits

The additional timing information about when the next risk update is planned to take place would increase user confidence in the predictability of the app's working.

It seems for instance that the background update timings are unaffected by a risk update triggered by opening the app. Instead of the next background update taking place around 24 hours after the last update (whether automated in the background or run in the foreground) the background update looks like it just happens around 24 hours after the last **background** update.

**Comment by RoxanaVuc** [comment]
Dear MikeMcC399,

thank you very much for your proposal.

To give the community a space for discussing new feature ideas or enhancements that might not be taken up immediately by the development teams, we created the cwa-wishlist repository.

This idea is one of these feature ideas or enhancements. Consequently, we will move this issue to this repository and allow the community and you to further refine it, discuss pros and cons, and evaluate alternatives.

The issue will not be closed in this repository to ensure long-term visibility. All issues in the cwa-wishlist repository will be discussed with our contracting entities. They will decide whether they will be implemented or pursued further. As soon as we have any updates, we will let you know about the details.

Best regards,

RV

Corona-Warn-App Open Source Team
