### ISSUE TITLE
Test results not being updated

### ISSUE THREAD

**Issue by ranjithvenkatesh** [corona-warn-app/cwa-app-android#991]
We had a Corona test done on 05.08.2020 by our doctor. The results were given to us by the doctor on 06.08.2020.
We had added the test using the QR code scanner on the App. Till today the App still says "Your result is not yet available"

## Expected behaviour

If the doctor has the results, then the App should also have the results.

## Steps to reproduce the issue

1. Scan the QR code using the App
2. Wait for App to display the test results

## Technical details

- Mobile device: Samsung SM-G398FN
- Android version: 10

## Possible Fix

The doctor works with a lab who did the test. Who is responsible to send the results? The lab or the doctor?

**Comment by SonaliDK** [comment]
Hi @ranjithvenkatesh,

Thanks for your query. Please refer to the [FAQ](https://www.coronawarn.app/en/faq/#qr_test) related to your question.

Best regards,
SD

Corona-Warn-App Open Source Team

**Comment by tkowark** [comment]
We are tracking all these QR code related issues centrally in the documentation repository: https://github.com/corona-warn-app/cwa-documentation/issues/400 - Hence, we'll close this issue here.

As noted in the linked issue, a variety of issues could lead to the result not showing up in your app and we're actively looking for solutions for the different aspects of thsi problem.

**Comment by jahic** [comment]
Hello
I have took a test at an airport upon arrival. It has been 5days now and no results. Other people receive their results after 12 hours. May I ask, what is the problem?

**Comment by tkowark** [comment]
From that description alone, it's pretty hard to tell what actually went wrong in your particular case.

Potential sources for error are noted here: https://www.coronawarn.app/en/blog/2020-08-25-notes-qr-codes/
Also, the issue in the documentation repository tries to collect as many potential scenario as possible https://github.com/corona-warn-app/cwa-documentation/issues/400

**Comment by jahic** [comment]
> From that description alone, it's pretty hard to tell what actually went wrong in your particular case.
> 
> Potential sources for error are noted here: https://www.coronawarn.app/en/blog/2020-08-25-notes-qr-codes/
> Also, the issue in the documentation repository tries to collect as many potential scenario as possible [corona-warn-app/cwa-documentation#400](https://github.com/corona-warn-app/cwa-documentation/issues/400)

There was only one QR code. The test is added in the app. However, it says "test result is not available yet".

Please let me know should you need any more details.

**Comment by tkowark** [comment]
Then, it is possible that the respective box in the form was not checked (https://github.com/corona-warn-app/cwa-documentation/issues/400#issuecomment-669990063) and the result will never by transmitted to the app. In case you are actively waiting for the result, we can only urge you to contact the lab or testing institution (gesundheitsamt, hospital, etc.) to get the result through this channel.

**Comment by jahic** [comment]
> Then, it is possible that the respective box in the form was not checked ([corona-warn-app/cwa-documentation#400 (comment)](https://github.com/corona-warn-app/cwa-documentation/issues/400#issuecomment-669990063)) and the result will never by transmitted to the app. In case you are actively waiting for the result, we can only urge you to contact the lab or testing institution (gesundheitsamt, hospital, etc.) to get the result through this channel.

That is really strange. At the airport, where I was tested, they just told me about the app. No one said anything about ticking any box...
May I ask, how can I contact the lab? At the paper I received after testing, I only have instructions about downloading the app and the QR code.

**Comment by svengabr** [comment]
> May I ask, how can I contact the lab? At the paper I received after testing, I only have instructions about downloading the app and the QR code.

Hello @jahic, the best would be to contact your specific Airport and ask them directly regarding your specific laboratory. As @tkowark said you need to agree to a data processing policy by ticking a checkbox in the form. A possible reason could be that this was left blank and therefore the data was never submitted to our servers.

This is also a high priority issue where the team is actively working on.

If you have any additional information, please let us know.

Best regards,
SG

Corona-Warn-App Open Source Team
